### ISSUE TITLE
Order of Actions

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1000]
I would like to rearrange the Your Actions menus for transcribers and Coordinators.

 

For the basic menu can we change the order.

CSV Batches

Search Place Name

FreeCEN Handbook

Communicate

Profile

Roadmap

FreeUKGenealogy Policies

 

For Coordinators can we have:

CSV Batches

Search Place Name

FreeCEN Handbook

Manage County

Manage Syndicate (Can we move Display Userids inside this menu please?)

Contacts

Communicate

Profile

Roadmap

FreeUKGenealogy Policies

 

This puts the most used Actions at the top and regroups them.

**Comment by Captainkirkdawson** [comment]
Changes made except Display Userids This allows the coordinator to look up any one who is a member not just their syndicate which Freereg coordinators found useful from time to time. Deployed to test3

**Comment by richpomfret** [comment]
@rhodamackenzie to register as a new transcriber on TEST3 and take it from there. @DeniseColbert to assist if required.

**Comment by geoffj-FUG** [comment]
Kirk
Coordinators look good.
I see no change as a Transcriber (even when I refreshed the screen). For the basic menu can we change the order please?
CSV Batches
Search Place Name
FreeCEN Handbook
Communicate
Profile
Roadmap

That would be similar to the one you have done and the most often used Actions are at the top.

Geoff

**Comment by Captainkirkdawson** [comment]
Sorry @geoffj-FUG had done the checker; have now done the transcriber and validator and tweaked the data manager

**Comment by geoffj-FUG** [comment]
Kirk
Looks good at the Transcriber Proofreader level too.
I will have a look at Data Manager when I test #879
Geoff

**Comment by geoffj-FUG** [comment]
Kirk
Data Manager looks good too.
What is the attic?
Geoff

**Comment by Captainkirkdawson** [comment]
Whenever a file is replaced,downloaded or reprocessed the current file is moved to the attic and the new one placed in the main folder.
We never throw anything away. Disk storage is cheap!!
It means that in the event of a major foul up the datamanager can recover a version of the file for a coordinator or transcriber.
They can download the version they want, strip the unix date extension and have a perfectly loadable file.
