### ISSUE TITLE
Rationalize District, Piece and Civil Parishes names

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1003]
@johnt-freecen @geoffj-FUG 

This is an aspect of a much wider issue that we need to address and one that needs to be part of a new document. The Initial Setup of a county under FC2.

As you are aware we extract the District, Piece and Cial Parishes from TNA for all years. Unfortunately for us they and/or the original  District and Sub District Superintendents were not consistent with their naming over the years. More unfortunately we have to be consistent. The matter raised here by John is most timely. If you both look at Freecen2 Civil Places for Rutland you will see what I mean.
![rutland civil parishes.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/979ca345-170e-499f-b86d-0cc6c8536ae9)
There you will see 2 spellings for Beaumont Chase and Beaumont-Chase. 
Before actually addressing John's issue of the download it is essential that there be only one spelling otherwise we will never be able to achieve consistent and reliable searching. In this case we should change Beaumont-Chase in 1841, 1851 and 1861 to Beaumont Chase,
This is done by clicking on the Yes for each year in turn and editing the Civil Parish.
![rutland edit 1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/c635a3aa-c6fb-4773-8ad3-062dbfb273a9)
and you get
![rutland edit 2.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/8e705184-3f83-45a1-8910-d7a8a69ed9e6)
Now we see that Beaumont Chase does not have a  Freecen2 Place so we have to add that before proceeding!! When we have done that we select the name and proceed to the next year.
Once we have done the 3 years with a name change we need to look at the other years to see if they link to an appropriate Freecen2 Place

**Comment by Captainkirkdawson** [comment]
Looking down Rutland there is a similar issue for Edith Weston/Edith-Weston; Holt/Holt or Nevill Holt; Leigh-Field Forest/Leighfield; Market Overton/Market-Overton: There are a few others that may need consideration.
Perhaps we should write this as a separate story.
IMO the fist task  the initial setup of a county is to go through the Districts, Pieces and Civil Parishes to ensure consistency and linkage to Places

**Comment by Captainkirkdawson** [comment]
Kirk, John
Whilst this is being considered should we throw in the Out of County Places as well?
If you look at Somerset you will find that Appledore is shown in Somerset in 1901, and only 1901. It is actually in Devon so is showing in the incorrect County. 
Similarly Bitton is in GLS but the Registration District was in Somerset from 1851-1911. 
These examples will also cause problems during searching.
I think that this background issue is now showing its true colours.
Maybe we need an additional field so that when the Coordinator is doing their review for hyphens etc they can enter the correct County. It could be prefilled with the County of the Reg District and the Coordinator just does a few edits. 
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @johnt-freecen the aspect you mention of Out of County Places should be dealt with through the process outlined in 
Add ability to copy a district and it Pieces and Civil Parishes to another County #879  and 
Add ability to remove civil parishes and pieces from a duplicated district #1009
which have both been coded and are in Need Review and testing

**Comment by geoffj-FUG** [comment]
The instructions are now in the Full Handbook.
When we deploy we will need to have each Coordinator tidy up their PARMS before they start using the system.
We will need to get some volunteers to assist Brenda or she is going to be swamped!

On another point we will need a data manager. They will be needed to move pieces between counties. It will be quite a task for a while.

Geoff

**Comment by DeniseColbert** [comment]
Re. Data Manager, we have one! Introducing @rhodamackenzie who joins us at the FreeCEN scrums, but doesn't have a background as a transcriber/coordinator. Do you see that as an issue @geoffj-FUG ? If so, perhaps, someone _with_ that experience could partner with Rhoda? That way, she can pick up some insider knowledge whilst becoming familiar with the system.

**Comment by geoffj-FUG** [comment]
Denise

 

I see no problem. 

 

Rhoda has been preparing a transcription from some Somerset images using the Abbreviated Handbook as a guide. A couple of items have been clarified in the Handbook following Rhoda’s feedback. These are included in the November version on test3.

 

There is a section in the Full Handbook that covers some Data Manager functions. These have been tested and the procedures written.

 

I will contact Rhoda and work through the transfer of pieces between counties with her. It will be an important task as we cut each county over.

 

Geoff

**Comment by DeniseColbert** [comment]
Great!

**Comment by richpomfret** [comment]
Now complete, so closing.
