### ISSUE TITLE
Are notes to be displayed for uninhabited building?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1006]
@geoffj-FUG 
Chas has said that notes should be displayed for uninhabited buildings. Could you confirm that this as a requirement or not.

P2 U6 9 c5:P22

**Comment by PatReynolds** [comment]
I'm thinking of an entry that I cannot, of course, now find .. where it was recorded as being 'The home of  Col. John Smith and family' or some such - for my purposes, this was very useful informatin (I was scrolling through trying to find 'the big house' in a village, not knowing who actually lived there (trying to identify a potential father for my illigitimate grandfather).  Similarly, anyone working on the history of a house or place would want the complete information.

**Comment by geoffj-FUG** [comment]
Kirk

 

The notes field should be displayed for every record. It is where we enter comments for the researcher to see. These notes can cover a range of things that are not normally captured, such as enumerator’s notes.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Currently the notes field is not processed if the uninhabited flag is set hence at this point there is no information to display.
Implementation requires a change to CSV Proc to always process the notes field and then to display.
Perhaps we should only display the field if it contains information

**Comment by geoffj-FUG** [comment]
Kirk

I am happy to display the notes field if it contains information. We get notes against all sorts of fields.

 

Geoff

**Comment by Captainkirkdawson** [comment]
CSV Proc has been modified to always process the notes field. Deployed to test3.
The display for a transcriber/proof reader / validator/ coordinator is similar to this
![unoccupied1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2153d2d4-fb4f-4b2d-99d9-11e564a995e1)
A researcher viewing a dwelling would have something like 
![unoccupied21.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/3613deaa-e3ea-4ae0-8c60-1443740ada68)
and 
![unoccupied 2.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/eabad674-6f48-4e53-a0b0-6d61fe2b016c)

These were generate on test3 with the search results from a search for surname Green in Beaumont Chase of Rutland;

**Comment by geoffj-FUG** [comment]
Thanks Kirk
Tests OK
Geoff
