### ISSUE TITLE
Bilingual codes

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1007]
@geoffj-FUG  said
We changed the use of B in the language column to eliminate ambiguity.

 

The existing language data is all for Wales. It has B’s in it. All of these will need to be changed to WE in the new system.

 

The existing data will need to be amended at some point. Will it be possible to do a global change on the FreeCEN database?

E0 U6 8 C6:P20

**Comment by Captainkirkdawson** [comment]
We can use a simple test on the display

**Comment by Captainkirkdawson** [comment]
A display look up is deployed to test3.
However there is a corresponding need to make changes to the language filter in the search

**Comment by Captainkirkdawson** [comment]
Since we cannot perform a filter against inconsistent field contents I propose to remove the language filter (The field for language in the results still displays)
Have written a new story Reactivate the Language Filter#1016 once in production and the database reconstructions has occurred.

**Comment by geoffj-FUG** [comment]
This can be closed
Geoff
