### ISSUE TITLE
Make unincorporate task a batch task

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1008]

**Comment by Captainkirkdawson** [comment]
Avoids gateway time out message

**Comment by Captainkirkdawson** [comment]
@johnt-freecen The record removal has been changed to a rake task. Deployed to test3

**Comment by johnt-freecen** [comment]
Hello Kirk,

I have just run this task. All seems ok, sample records checked were removed from the system and a completion message received.

I am now running the re-implement the file  process.

Regards

John

Sent from Mail for Windows 10

**Comment by johnt-freecen** [comment]
Hello Kirk,

All seems to be working I have done a remove a file, edit the file and re-implementation to check the change is in place.

Regards

John

Sent from Mail for Windows 10

**Comment by Captainkirkdawson** [comment]
Thanks @johnt-freecen
