### ISSUE TITLE
Add ability to remove civil parishes and pieces from a duplicated district 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1009]
For district that cross county borders we propose to duplicate a district in another county. We should then be able to remove Civil Parishes from each county.

**Comment by geoffj-FUG** [comment]
Will be tested when I test #879
Geoff

**Comment by geoffj-FUG** [comment]
I have successfully done this as a data manager. See comments on #879
Geoff
