### ISSUE TITLE
Add action to look uo a specific District, Piece or Civil Parish

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1018]
Rather than having to look through an index it is useful to select a specific District, Piece or Civil Parish. Add anchors and push the full index down a level

**Comment by Captainkirkdawson** [comment]
Implemented into test3. Examples follow
![District.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/3b3f55e8-87c1-4171-b0c3-891d6c0c644e)
![District 1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/e9a4a143-c836-48a9-a52e-2b41b6ffa57f)
![piece.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/adb02c3e-fa1e-43af-8fa8-2cee3869bdc7)
![parish.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/3536195b-701f-42f8-959b-c5cf83a24acd)
![parish1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/880a07d3-ec73-49bb-8513-73ef420facc4)

**Comment by geoffj-FUG** [comment]
I ;ooked at this during the transferring of a piece to another county as a data manager. I was comfortable with the result.
@johnt-freecen Did you raise this one? If so, is this what you needed?
Geoff

**Comment by Captainkirkdawson** [comment]
Geoff
I added of my own volition based on my use of the system;
