### ISSUE TITLE
Add file selection for coordinators to list files incorporated and files in validation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1019]
Based on recent experience these would be useful management additions

**Comment by Captainkirkdawson** [comment]
Incorporated into test3
@geoffj-FUG @johnt-freecen FYI as coordinators  you can now select on files being validated and files incorporated
![actions.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/5a1fd974-e404-4a2e-ad7d-b20956b86f54)
![actions1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/e286f7b7-291a-4ebe-8066-47d0411664ea)

**Comment by geoffj-FUG** [comment]
John

 

Can you test this for me please?

 

I am currently testing at Data Manager level and so won’t necessarily get the same results as you.

 

Geoff

**Comment by johnt-freecen** [comment]
Hi Geoff,

The selection process produces the correct files when you use either the list of options or the  buttons across the top of the selected files.

However there is a problem once you have the selected view. When you select either the in validation or incorporated options the display is in alphabetical order, If you select the order by latest or oldest buttons to re-order the view you get the total list of files for the county not the selected view. This should not be a problem for  in validation view, bit incorporated files could be a problem where it would be easier to sort by date.

Regards

John

**Comment by geoffj-FUG** [comment]
Thanks John

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @johnt-freecen 

This is the manner in which the files display had always worked. It always works on the totality of the files. It was not designed to provide different sorts on the subsets created by selecting those with errors, being validated or incorporated. Perhaps it should. 

Doing that is a major rewrite. Estimate of 13 would be applicable (~2 weeks)

**Comment by geoffj-FUG** [comment]
Kirk
If this is to be done it should be a post implementation improvement.
I suggest that it be left as it is at the moment and moved to 'On Ice'
Geoff

**Comment by Captainkirkdawson** [comment]
Will close story as completed.
Will raise a new story for the enhancement.
