### ISSUE TITLE
Write rake task to load records from a csv file into Freecen2 Places

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1020]

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
An initial version of a csv place file is ready; needs a few tweaks but is ready anytime that Paul has LDN far enough along.
His work does not need to be **complete** before we start ingesting the information.
I can also give him a list of missing place name for London from the parms ingests
Example page ![csv place ingest.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/e057b235-174a-4557-94fe-c8eb219236cf)

Perhaps we should drop the (City) and just call it London

**Comment by PatReynolds** [comment]
Maybe Londin (1881) - or whatever year has been chosen?

**Comment by Captainkirkdawson** [comment]
Have also written rake tasks to download csv files from Freecen2 Places and Places by county and in total

**Comment by geoffj-FUG** [comment]
Three spreadsheets with additions to Place Names forwarded to Kirk:
Part of London
Isle of Wight
Ireland
Geoff

**Comment by Captainkirkdawson** [comment]
Will close as it works and remaining action is to run the task as and hen needed
