### ISSUE TITLE
Birth place in VLD entries

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1021]
@geoffj-FUG @FreecenBren I am puzzled why the Alt Birth County and Alt Birth Place are always set in vld entries and always the same as the verbatim birth county and verbatim birth place

E0 U4 S9 C2: P15

**Comment by geoffj-FUG** [comment]
Kirk

 

I have no idea. The spreadsheet version of a vld when converted only has the entries for alternatives. See columns AD and AE in the attached csv version of the vld file.

 

Are you sure that you are not referring to the Civil and Ecclesiastical Parishes? They were often the same as a work around when wincc became unusable. This has been fixed in the new spreadsheets and instructions.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I am indeed talking about the verbatim birth county/place and the Alternate birth county/place.

When cen2 (NOT CSV Proc) processes the vld file it loads an Individual collection which is then used to display search results.

I was looking at it  so that we could populate the Birth Place field in the display of search results; that Pat has been requesting.

I was puzzled to see both sets of fields were always propulated.

So are you telling me that CEN1 only displays the alternate fields? So a researcher never sees the verbatim fields if they are different?

I see the following definition for a vld entry
 VLD_POSITION_MAP =
    {
      :deleted_flag => [0,1],
      :hh => [5,6],
      :suffix => [1,3],
      :parish => [15,20],
      :enum_n => [35,3],
      :enum_a => [38,1],
      :sch_n => [48,3],
      :sch_a => [51,1],
      :house_n => [52,4],
      :house_a => [56,1],
      :street => [57,30],
      :prem_flag => [87,1],
      :ecc_parish => [256,20],
      :individual_flag => [87,1],
      :seq_in_household => [11,4],
      :s_name => [88,24],
      :f_name => [112,24],
      :name_err => [136,1],
      :rel => [137,6],
      :m_stat => [143,1],
      :sex => [144,1],
      :age => [145,3],
      :age_unit => [148,1],
      :p_det_err => [149,1],
      :occ => [150,30],
      :occ_err => [180,1],
      :t_born_cty => [181,3],
      :t_born_place => [184,20],
      :place_err => [204,1],
      :dis => [205,6],
      :language => [211,1],
      :notes => [212,44],
      :born_cty => [276,3],
      :born_place => [279,20],
      :fo_n => [39,4],
      :fo_a => [43,1],
      :pg_n => [44,4],
      # :s_name_sx => [88,24], # original has soundex of iu1
      # :born_place_sx => [279,20], #original has soundex of iu19
      :unoccupied_notes => [212,44],
    }

This implies that both are in the vld entry

PS you cannot attach a file to a github reply; could you please sen by email.

**Comment by geoffj-FUG** [comment]
Kirk

 

Just went to try it.

 

The link to FreeCEN1 has disappeared from the Search screen!

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
As far as I can see the the verbatim_birth_place is taken from :t_born_place => [184,20], in the vld entry; the alternate birth place is taken from :born_place => [279,20], in the vld entry
The verbatim_birth_place is the birth place shown in the search details. The alternate birth place is unreferenced anywhere in the code and not displayed to the researcher by the modern version of cen1. Confirmed using a name from your file
TRUMP	William	Visitr	U	M	27	Farm Servant	SOM	Chezey	
The original version of CEN1 displays both
TRUMP	 	William	 	Visitr	 	U	 	M	 	27	 	Farm Servant 	 	Somerset - Chedzoy(Originally: Somerset - Chezey)

**Comment by PatReynolds** [comment]
Just looked at link - still there
![image](https://user-images.githubusercontent.com/6338822/96564576-3dcd9680-12bb-11eb-939c-c4d4252ee852.png)
It isn't on test3, though.

**Comment by Captainkirkdawson** [comment]
Note this is a bug in the CEN implementation of CEN1

**Comment by PatReynolds** [comment]
Agreed that the Verbatim place needs displaying in FreeCEN2.  

I think proof reading and validation should only check the verbatim place name if requested by transcriber - e.g. the transcriber is  not able to make out whether it is - as written - Bleeden or Bleedon and needs a more expert pair of eyes to decide on one or the other (for the standardized name: Bleadon).

**Comment by Captainkirkdawson** [comment]
Superseded by #1312 and #1313
