### ISSUE TITLE
Augment the error trapping during incorporation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1022]
Dear Colleague:

Incorporation completed

RG12_1944.csv for SOM undefined method `titleize' for nil:NilClass

The FreeCEN Team

Unquote

This can be missed.

**Comment by Captainkirkdawson** [comment]
Added failure message; trapped the backtrace and added to message.
Resolved the specific problem
Deployed to test3

**Comment by geoffj-FUG** [comment]
File that casued the problem now Incorporated OK. Search birth range problem in separate email.
Kirk, What do I need to do to a file to get No Warnings, No Errors yet cause Incorporation to fail? I need to know so that I can test through to failure. Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
This is one where you have to just me 
It was a coding error.
The trap did work before; it was just that there was bad error reporting,
Propose to close; no further work on your part needed

**Comment by geoffj-FUG** [comment]
😊
