### ISSUE TITLE
catch xlxs upload

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1023]
It should be stopped but clearly is not
{
  "action" => "create",
  "authenticity_token" => "LDblcLMnw/TF9hFZeE1WArnb8K+jrGZ4rG9LhbYH9xibbdVILfzg4pRndGZ1f6N8MWl85zLKvOabnNoZpjHA1A==",
  "button" => "",
  "controller" => "csvfiles",
  "csvfile" => {
    "action" => "Upload",
    "csvfile" => "{\"tempfile\":[],\"original_filename\":\"RG13_2301.xlsx\",\"content_type\":\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\",\"headers\":\"Content-Disposition: form-data; name=\\\"csvfile[csvfile]\\\"; filename=\\\"RG13_2301.xlsx\\\"\\r\\nContent-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\\r\\n\"}",
    "type_of_processing" => "Check(Warn)"
  },
  "locale" => "en",
  "utf8" => "✓"
}

**Comment by Captainkirkdawson** [comment]
Added a test and message. Deployed to test3

**Comment by geoffj-FUG** [comment]
Kirk
Tests OK
Geoff
