### ISSUE TITLE
Which current spreadsheets to support

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1024]
Almost all work to date has involved use of the new spreadsheets. These perform well. However there is a significant amount of work in progress that use the existing original spreadsheet, interim forms and the final validation output.
What is the best way of transitioning this workload into  Freecen2 directly and not through Cen1

**Comment by Captainkirkdawson** [comment]
The system on test3 will accept the original traditional header

It will also accept the Freecen2_traditional header

If I recall correctly we introduced the latter to reflect the output of the offline validation app; the expectation being that we could import those

However it has been months since we talked about these aspects.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG responded
Let us look at the process as it exists in FreeCEN1.

Transcriber transcribes the piece. This is columns A to Y of the FreeCEN2 Traditional spreadsheet.

Proofreader proofreads the spreadsheet. In the original system with WinCC the Proofreader adds the Ecclesiastical Parish (only they actually added the Civil Parish again instead because of an apparent misunderstanding 20 odd years ago, but that is not the current issue). So that covers columns A to Y plus AC of the FreeCEN2 Traditional spreadsheet.

Validator validates the piece and completes the Alt CHP and Alt POB fields as necessary. So now we have Columns A to AA plus AC

Columns AB and AD are there in case they are needed.

 

If we allow the FreeCEN1 Traditional spreadsheet to be tested in CSVProc we have no method of enforcing the spreadsheet be updated to what is needed for Incorporation. We have a high probability of a Piece going through the system to Incorporation without columns Z to AD being included in the spreadsheet fields. Why? Because it can and its easier than changing it.

It is easiest to capture the ecclesiastical data at Proofreading stage if the old spreadsheet has been used for transcription. So my view is that the FreeCEN2 Traditional spreadsheet is the minimum. FreeCEN1 Traditional needs to be phased out or people will still be (mis)using it in ten years time. The easiest way to make this happen is to make the change in spreadsheet format happen before the piece can be tested.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
This unfortunately is where my lack of awareness of the actual detail of cen past practices makes it difficult to make sensible solutions.
However what is wrong with the proofreader using the reports produced by CSVProc if we process the minimum spreadsheet? 
Should we not also be able to accept the current output of validation in CSV format The validation spreadsheet does not appear to be the same as the Freecen2_tradional layout based on the file you sent me. I agree entirely that the original csv file should not be allowed to be incorporated. That is straightforward.

**Comment by geoffj-FUG** [comment]
Kirk
If we dont enforce the Proofreader using a minimum of the FreeCEN2 Traditional spreadsheet then the eccesiatstical parish will not be captured.
That means that the Validator has to start with a spreadsheet full of errors (no ecclesiastical parish). 
That means that they have to go through the images. That has already been done twice! It is not the validators role to do this. Their role is to resolve the issues that are presented to them, not to back up the transcriber and proofreader.
We need to enforce the ecclesiastical parish being entered at the Proofreading stage at the latest. All that means is that the spreadsheet is copied to a FreeCEN2 Traditional spreadsheet or converted to a new spreadsheet format. The former is a simple copy and paste. The latter means that the utility is used to do the conversion.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
I now understand and will go with the Freecen2_Traditional for the transcriber/proof reader.

Next what about the files currently going through validation, you sent me a csv formatted file with an example. That is a different layout. How are we going to have those entered? Using the Freecen2_Traditional or do we need to specify a Freecen1_Validator format?

**Comment by geoffj-FUG** [comment]
Kirk
The columns in a vld spreadsheet are
A - Processing flag (system dependent)
B - Blank (used by the system I believe)
C - Family number (system generated)
D - family position (system generated)
E - Civil Parish
F - ED number
G - Folio
H - Page
I - Schedule
J - House number
K - Address
L - uninhabited flag and address flag
M - Surname
N - Given name
O - Name flag
P - Relationship
Q - Condition
R - Sex
S - Age
T - flag
U - Occupation
V - Occupation flag
W - Verbatim Chapman code
X - Verbatim place of birth
Y - Language
Z - Disability
AA - Flag
AB - Notes
AC - Ecclesiastic Parish
AD - Alt CHP
AE - Alt POB
So FreeCEN2 Traditional has it covered as the system generated fields are not transferrable.
We should start all new transcriptions on the proper CSVProc spreadsheets. Transcriptions in the system can be converted to either FreeCEN2 Traditional or the new format (using the utility)
I would suggest that the best option for legacy files is to use the conversion utility between transcription and proofreading but use the FreeCEN2 traditional between proofreading and validation.
Geoff

**Comment by Captainkirkdawson** [comment]
Thanks @geoffj-FUG that was useful; some clarification please
You said **the system generated fields are not transferrable.**. 
Could you explain what you mean by that as those fields were in the spreadsheet you provided.

**We should start all new transcriptions on the proper CSVProc spreadsheets. Transcriptions in the system can be converted to either FreeCEN2 Traditional or the new format (using the utility)**
Sounds appropriate on the understanding that the utility converts to FreeCEN2 Traditional
**I would suggest that the best option for legacy files is to use the conversion utility between transcription and proofreading but use the FreeCEN2 traditional between proofreading and validation.**
This also sounds fine for new validations of files in progress. My thoughts were more focussed on those files that were currently undergoing validation. You say  **So FreeCEN2 Traditional has it covered**. it does but the order of the additional fields is different.
Sorry to be labouring this but I want to avoid downstream hiccups

**Comment by geoffj-FUG** [comment]
Kirk

 

What I meant was that they are generated for FreeCEN1. You have generated them yourself in FreeCEN2. Whilst they do not appear on the spreadsheet they do appear on the screens when we edit.

 

I will add the conversion to FreeCEN2 Traditional to the Utility. It will be sometime later this week.

 

If files are currently being validated they will be ready for publication after validation. As they would be loaded via FreeCEN1 at present and these files create a vld file for loading I think that they should be Incorporated using the current FreeCEN1 system. There will only be a few of them. FreeCEN loads between 30 and 40 pieces a month. So if we have a 1 month transition using FreeCEN1 that should be the maximum number of files affected. As one validator validates several file in a month the number should be much smaller. Having said that migration may take a few weeks to get every coordinator across to the new system. So there will be a period when both FreeCEN1 Loading and FreeCEN2 Incorporation will both be being used.

So my view is that if validation is done using Valdrev then the piece is loaded via FreeCEN1. If the validation is done using CSVProc the Incorporation is done from CSVProc. It is a transition arrangement.

 

Does this make sense?

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Yes it does make sense. The only caveat is that the transition make take months rather than weeks. 
We can close.
