### ISSUE TITLE
Enhance file selection options for coordinators 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1025]
It currently always works on the totality of the files. 
It was not designed to provide different sorts on the subsets created by selecting those with errors, being validated or incorporated. 
It should.

E0 U3 S5 C4: P12

**Comment by Captainkirkdawson** [comment]
Have adjusted the Manage County file actions to  do a preselect.
![fc_1025_1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/4e3f86c1-866f-467f-916b-a071229a1f57)
The actions for the files display for the coordinator are now sort actions that work against the preselection

![fc_1025_2.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/0d8672c2-7287-44b8-8613-3e6b7fefe215)
@geoffj-FUG and  @johnt-freecen needs review on test3

**Comment by geoffj-FUG** [comment]
Kirk
Problem
I have 4 pieces in test3. Two are  marked as validation under way. (County SOM)
I have no pieces in the Under validation lsit.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Sorry about that misspelt validation
should work now

**Comment by geoffj-FUG** [comment]
Kirk
Works well.
Once it is live I will check with Incorporated files as there are several there.
Geoff

**Comment by PatReynolds** [comment]
Thanks, both.  Does this need further testing, @Captainkirkdawson or can it be closed (if so, please do).

**Comment by geoffj-FUG** [comment]
Kirk
I still need to do instructions for Coordinator actions before a 1901 or 1911 year can be started. I am not sure ablut the actions and tools for this as I think they are being used by Rhoda. I dont have the knowledge yet.
Geoff
