### ISSUE TITLE
Search problem with the CSV incorporated record responding to birth years range

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1026]
File RG12_1944 incorporated OK. This was a FreeCEN2 Traditional format file.
I searched for Thomas Cleavely (see image below). His birth year is abt 1855 (=1891-36).
If I leave the birth from / to empty I find him. If I put in the date range I don’t.

There seems to be a search problem with the birth years range.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG  Thanks for picking that up; an error in the creation of the search date. Fixed on test3.
You will need to delete the current search records and do a new incorporation (no need for an upload or reprocess of the file)

**Comment by geoffj-FUG** [comment]
Kirk
I have sent an image in a separate email.
Geoff

**Comment by geoffj-FUG** [comment]
Will test after #831 and #1028
Geoff

**Comment by geoffj-FUG** [comment]
This has been tested with several broad and narrow birth ranges. Working OK.
Geoff
