### ISSUE TITLE
Place search option not working correctly 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1028]
While researching indexes discovered that the place selection as part of a search was not working correctly since we use 2 place collections. 1 for the old CEN1 files and 1 for the CEN2 CSV Proc. The search place options use only the CEN1 places.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG the solution to this has been developed. It required changes to both CSV Proc and Incorporation code. To properly test it we will need to reprocess and reincorporate files. Do we want to do this now? Will it have an impact on the team? I have not deployed to test3 because of its potential impact. It has to be done before deployment to production.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG the deployment to test3 has been done so it can now be tested

**Comment by geoffj-FUG** [comment]
On the assumption that the Place search refers to the Census District, this is now producing the correct results.
Geoff
