### ISSUE TITLE
Geolocate the Hundreds and Wapentakes of the 1841 Census.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1031]
The conclusion of story #975 was not to let the ideal (the Cambridge University data) get in the way of adequate (enabling 'nearby places' searching in the 1841 census).

Therefore, where the data is available on https://www.wikidata.org/w/index.php?search=wapentake&title=Special%3ASearch&fulltext=1&ns0=1&ns120=1 for wapentakes, and https://en.wikipedia.org/wiki/List_of_hundreds_of_England_and_Wales for hundreds.

Where the hundred/wapentake is not georeference in either list, please take the georeference from the named place (e.g. Charlton - https://en.wikipedia.org/wiki/Hundred_of_Charlton - is not georeferenced, then the place name in the hundred title (e.g. in this case, Charlton) should be used. Typically the place name in the hundred title is the place of the moot hill (or not too far from it), which is typically in the centre of the area, so this use is not going to be far off a more precise centre.  

If the hundred/wapentake name does not reference a place in the area - e.g. Amounderness, all we can do is find a map, and pick a fairly central place, e.g. Inskipp and use it's georference.  Being a few miles out won't make a huge difference to the search, and is better than nothing.

Priority is for those which we have transcriptions / imasges to transcribe

Coords need to geolocate new hundreds/wapentakes when starting a new 1841 census, and do for the existing ones when moved to FreeCEN2 (fine while on FreeCE1).  @PatReynolds to ask @geoffj-FUG to update handbooks with this information (email to follow, Geoff).

E2 U6 S8 C2:P18

**Comment by geoffj-FUG** [comment]
Pat

 

The cutover version of the Handbook has this included.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Implementing as part of cutover
