### ISSUE TITLE
Test Freecen2 deployment process

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1035]

**Comment by Captainkirkdawson** [comment]
Step 1 has been completed on my server. There were just 3 code conflicts. Resolved

**Comment by Captainkirkdawson** [comment]
Step 2 has been started; my own tests showed nothing odd.
Have asked @SteveBiggs  and @Sherlock21 if they would kick it

**Comment by Captainkirkdawson** [comment]
Have done basic tests of test2 CEN for Step 3. Looks OK so will proceed to step 4

**Comment by SteveBiggs** [comment]
I had a good play with test2 REG and found no problems.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Thanks very much Steve I owe you one

**Comment by Sherlock21** [comment]
Been away for a couple of days, so only just got started.
and of course I wrecked Test2 at the first chance!

I decided to look up Location of a place name.

chose DEV / Sidmouth which I clicked on in the alphabetic list of Active Places.
Got this. (  repeated the test and got the same)

SO I have stopped - Eric B

**Comment by Sherlock21** [comment]
Kirk
forget the item below.

I had not realised I had to swap the url to CEN

will have another try later when I am back from garage.\Eris

On 5 Nov 2020, at 12:12, Eric Booker <ericbooker8@gmail.com> wrote:

Been away for a couple of days, so only just got started.
and of course I wrecked Test2 at the first chance!

I decided to look up Location of a place name.

chose DEV / Sidmouth which I clicked on in the alphabetic list of Active Places.
Got this. (  repeated the test and got the same)

SO I have stopped - Eric B










On 3 Nov 2020, at 23:47, Kirk Dawson <notifications@github.com <mailto:notifications@github.com>> wrote:


Step 2 has been started; my own tests showed nothing odd.
Have asked @SteveBiggs <https://github.com/SteveBiggs> and @Sherlock21 <https://github.com/Sherlock21> if they would kick it

**Comment by Sherlock21** [comment]
Kirk

ignore this one please.!

the other email with the Error details still stands
EB

**Comment by SteveBiggs** [comment]
Eric, it is unclear to me what actions you took and your error does not show up in your post.

Please detail precisely what action buttons you pressed and what error you saw.

**Comment by Captainkirkdawson** [comment]
The problem @Sherlock21 was having was looking at an active place in devon called sidmouth. The system crashed. I was able to duplicate and fix.
Actually it was nothing to do with the actual code base at all but a configuration setting on development that raised an error when it could not find a file. Normally we ask the server to respond with a nil and our code works around the problem.
I have changed the setting and the system no longer crashes.
@sherlock is welcome to kick some more

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @Sherlock21 I have confirmed that the site does exactly the same thing running the master code. Suspect it is a result of the trapping of communications from test2. The logs tell me that the download file si prepared.
Do not believe this is an issue that should stop us deploying the master code with the CEN2 code changes.
Thank you both.

**Comment by Sherlock21** [comment]
OK, I go with your proposal.

you have a better grasp of the overall picture than I do.
Eric B

**Comment by Captainkirkdawson** [comment]
Have tested Freereg on test2.
Have tested Freecen on test2
