### ISSUE TITLE
Create 'worked example' of FreeCEN2 transcription to send to new volunteers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1041]
This is to preceded the tailored (actual piece) as is sent at the moment.  Nice clear handwriting!

@DeniseColbert to ask John Topliss for an England example, possibly Margaret for Scotland??

E0 U6 S8 C7: P21

**Comment by geoffj-FUG** [comment]
I have already done this.
I have sent all Coordinators a 1901 transcription with 1500 rows on it. It is called RG13_Sample.
It has a complete ED plus the start of the next ED and a whole range of entries.
1901 has all the columns in it to create any year except 1911. Coordinators just delete the columns that they dont need to create the sample for the year that they want a sample for.
Geoff

**Comment by PatReynolds** [comment]
@geoffj-FUG do we need one for Scotland? Maybe only 'in due course'?

**Comment by geoffj-FUG** [comment]
Pat
Scotland has fields that have been specified but not developed as yet. The spreadsheets exist, but not the test. We need to treat Scotland as a separate project to be developed when resources are available and England and Wales have been cut over.
We managed to create the E&W PARMS from the TNA download. We currently have not examined the Scottish indexes and how useful they will be. I suspect that we dont have access currently anyway. Scotland's People have effectively blocked any further development in this regard and this situation may be long term. Until we have something to test we cannot develop sample spreadsheets. 
Geoff

**Comment by PatReynolds** [comment]
@DeniseColbert please take a look.

**Comment by DeniseColbert** [comment]
In light of Scotland not being needed and E&W example is done, this can be closed
