### ISSUE TITLE
Document the use / actions of Syndicate Coords vs County Coords

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1049]
Pat to check this when doing other work on this issue.

Issues arising:
 -[ ] rewrite Information for Coords, making roles of County Coord and Syndicate Coord distinct, removing all materials now covered in the Handbook

**Comment by PatReynolds** [comment]
Checked,.

**Comment by DeniseColbert** [comment]
@PatReynolds to review and update story

**Comment by PatReynolds** [comment]
Include Master Coords (experts who can assist other coords).

**Comment by PatReynolds** [comment]
Looking at the DRAFT information for coords on test3, it appears to be a copy of the Information for Transcribers. Have marked 'do not use' on both test 3 and live.  

I think this story is complete. However some updates to this page are needed / will be needed and I will start a new story.

**Comment by DeniseColbert** [comment]
Please close when new story is made

**Comment by PatReynolds** [comment]
Cannot sign in to the members' area on  test3 ....

**Comment by PatReynolds** [comment]
Being undertaken as part of #1170
