### ISSUE TITLE
185881975 Website Problem (Sue)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1050]
Issue reported by **Sue** at 2020-11-21 09:52:55 UTC
Time: 2020-11-21T09:51:27+00:00
Session ID: e1071e86ffd459c4007f854d203bcfcb
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
I have removed adblock and refreshed, etc. but I continually get the message remove adblock. Please advise. Thanks.

**Comment by DeniseColbert** [comment]
Contacted Sue 23/11 for more info

**Comment by DeniseColbert** [comment]
Sue replied: I am using Chrome and it's Windows.
