### ISSUE TITLE
186093265 Website Problem (Dianne Baker)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1051]
Issue reported by **Dianne Baker** at 2020-11-23 20:34:25 UTC
Time: 2020-11-23T20:29:02+00:00
Session ID: 0b1abc1a6ba235a0434aedf501d3083a
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
Annoyed, not happy with the constant  pop up about turning off ad-blocker.  I have Kaspersky, and there is no option to turn it off.  
Freecens was my first site I always use for my Cornish research,  but if it is going to be a money making site so you can sell my data,  then change the name to Paidcens.
Dianne

**Comment by Captainkirkdawson** [comment]
@DeniseColbert @PatReynolds @Vino-S 
Another very unhappy customer

**Comment by Vino-S** [comment]
The ad-blocker pop-up does seem strict. The pop-up does not allow users to use our website unless the adblocker is disabled

**Comment by PatReynolds** [comment]
Have disabled existing message.  Will create message with choices (thought that was what I had done) and check that versions for FreeREG and FreeCEN are OK.

**Comment by PatReynolds** [comment]
Could you test, please Vino - does not seem to be any message to ad blockers on FreeCEN now.

**Comment by Vino-S** [comment]
Yes @PatReynolds , the adblocker message still displays on FreeCEN

**Comment by PatReynolds** [comment]
But can you close it?

**Comment by Vino-S** [comment]
No Pat. It does not have close

**Comment by Vino-S** [comment]
Hi @PatReynolds , The close button is now there. Apologies I had my window zoomed up to 110% so the close button got cut-off

**Comment by PatReynolds** [comment]
Thanks, @Vino-S  @DeniseColbert could you contact Dianne to reassure her that this was an oversight, and she and other users can now enter the site while using an adblocker.

**Comment by DeniseColbert** [comment]
Will do

**Comment by DeniseColbert** [comment]
Done.
