### ISSUE TITLE
Problems with Message reply email 

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1052]
**Issue 1**

I replied to Pat's message and received an email notification addressed to her.

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/5d72e7fb-eb33-4dff-af60-23f066d5f49c)

**Issue 2**

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/ed4b1d13-4f9d-48ed-aef1-a44dc38f8197)

The same happened with another reply I sent (to UserID Jennypin)

**Comment by richpomfret** [comment]
@Vino-S to take a look at when possible (this sprint).

**Comment by Captainkirkdawson** [comment]
Fixed
