### ISSUE TITLE
Remove "Manage FreeCEN Coverage Action"?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1056]
For discussion:
"Manage FreeCEN Coverage" is not management, it is information.  Is it need now at all given:  the information now in 'Database Statistics' and Is identical to content of 'Records ' Tab for the public

**Comment by Captainkirkdawson** [comment]
It is a place holder action which will likely be needed in the future
It is ONLY  visible to you, rich and system administrators
