### ISSUE TITLE
CSVProc may not handle the Enumerator Special Situations correctly

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1058]
CSVProc does not handle the Enumerator Special Situations correctly for dwelling number and sequence in household. For those cases the spec states  **There will be no Schedule Numbers: Use "0" (zero).** CSVProc  is interpreting this as a new dwelling and the person as the first person in the dwelling

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG discovered while developing the VLD download. Not sure we ever tested this aspect.

**Comment by geoffj-FUG** [comment]
Kirk

 

That is correct.

 

The ED number is for instance 0#3. The schedule number is 0.

 

The entry that the ED and schedule number are against is the first entry in the household. So it is a new dwelling.

 

The piece that you are looking at if it is Bedminster Union in Long Ashton is a piece that has not been put through CSVProc. The transcriber will probably have repeated the ED number for each new folio as per the old system. I suspect that is what is causing your problem. 

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG The piece I was looking at was RG12/1953.vld which is on the production system.
You are totally correct that provided the schedule number is not repeated then CSVProc does function correctly in almost every circumstance. The error was mine in the extraction of the VLD as a CSV where I had duplicated the schedule number of 0 with every record in the special ED. This has now been corrected.
The remains one possible issue with our validation of the civil parish.
The notes say
 _Civil_parish – This is the parish in which the census was lodged. If the ship was at sea on census night, it will be the first port visited._
The first part of that should well be OK. However the last part about first visited port will likely generate an incorrect civil parish in some (many?) cases

**Comment by geoffj-FUG** [comment]
Kirk

 

The civil parish of the first port should be one and the same as the parish in which the census return was lodged. That was the  instructions in the census. If it was not we will never know because all we see is the civil parish in which it was lodged.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Thanks @geoffj-FUG  for the explanation; my lack of knowledge showing through.
Closing
