### ISSUE TITLE
Initialize geolocation data to support nearby places search

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#106]
This task is related to #53 and #99, but entails adding geolocation data (lat/long) for places, whereas #99 provides the facility to manually add/edit geo data in the database and #53 utilises the geo data to do searches. Many places can be initialized programmatically using FreeReg places and publicly available geo data (this story), but many other places will not be able to be added programmatically.  Lat/long for those places will require manual entry by coords or volunteers at a later time (not part of this story).

**Comment by helhyde** [comment]
Can we take lat/long data from elsewhere - e.g. Historical GIS project?

*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by dougkdev** [comment]
The programmatic part of this is done.
