### ISSUE TITLE
Upload of VLDs is possible

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1067]
Story identified in Roadmap meeting

**Comment by Captainkirkdawson** [comment]
Do not understand this story. We have spent 9 months implementing a replacement for VLD processing called CSVProc. What is being proposed here? Upload of a file is trivial. It will just sit there. There are no current processes that would take the entries and put them in the database. The latter is a 21 size task.

**Comment by PatReynolds** [comment]
VLDs can already be uploaded as CSV files - so deleting from Roadmap and will then close.
