### ISSUE TITLE
Correct Errors in the Pieces Report

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1068]

**Comment by PatReynolds** [comment]
@geoffj-FUG have I got the title correct for this issue?  Please could you let me have the sub-stories for this epic.

**Comment by geoffj-FUG** [comment]
Pat

 

This is the work that Brenda is currently doing. The errors are in FC1 pieces.

 

Geoff

**Comment by FreecenBren** [comment]
This months errors in FC1 are as below.

I have corrected DOR. HAM and HUN.
They will be uploaded at the next scheduled update.
The LEI one I sent an email to John to fix and send me an amended VLD.
 FreeCEN - Errors
CountyFileMessage
DOR H01071858.VLD Invalid Census Type
LEI RG103297.VLD  corrupt (invalid record length) 595591
HAM RG120896.VLD ignored - duplicate
HUN ho107448.vld  Invalid County PUC (ED: 4 Schedule: Record: 9, LYON,
William)6

Not sure if this is what you mean.
Waiting for Vino to do an update on FC2.

I then compare the FC1 error report with the one for  FC2 that Vino
supplies.
They normally match.

FC2 though sometimes have extra ones that FC1 did not pick up.
I investigate those as and when and amend on FC1 which then corrects the
error on FC2 at the following update.

Hope that helps.

**Comment by geoffj-FUG** [comment]
Brenda

 

Does that mean that the list of vlds with errors that you were chasing about a month ago are now mostly clear?

 

Geoff

**Comment by FreecenBren** [comment]
No really. Will not know till I get the next FC2 report from Vino.
If they worked then they will not be on Vino error report.
Because they work on FC1 does not necessarily mean that FC2 has accepted
them

**Comment by geoffj-FUG** [comment]
OK Thanks

 

Can you keep me in the loop please?

 

Geoff

**Comment by PatReynolds** [comment]
Hi Geoff,

My understanding is (and @Captainkirkdawson may need to correct me) that the  file uploaded to FreeCEN1 is corrupt, and there is no way of checking this - FC1 accepts it, but FC2 does not.

The resolution seems to be that the file as transferred to FC2 needs to be downloaded (i.e. as a CSV file) the converted into the appropriate format for FC2 upload, and processed using CSVProc.

It will need deleting from FC1 so that it is not uploaded over the corrected file.

This has been converted to being an EPIC, and I will make stories / make existing stories that are part of this epic.

**Comment by PatReynolds** [comment]
Duplicates #803 so closing.

**Comment by geoffj-FUG** [comment]
Pat

 

I can try one in test if you like to see what happens. Logic says it should work.

 

We now have quite a few records uploaded via CSVProc. Probably getting on for 20,000 between John and I by next weekend.

 

When is the next error report run, please? We need to see whether any of these pieces report problems first.

 

Geoff
