### ISSUE TITLE
Recent additions report (urgent)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1076]
Links to https://github.com/freeukgen/systemwide/issues/158

E0 U6 S8 C4: P18

**Comment by Captainkirkdawson** [comment]
Has to be a component of a redesigned Reports system for CEN

**Comment by Captainkirkdawson** [comment]
Basic code written to generate statistics.
Reports to be added

**Comment by Captainkirkdawson** [comment]
The first set of reports for overall statistics and county level statistics can now be generated on test3
![overall statistics.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/62b246d7-2670-4955-9e6a-0e5524e8662b)
![somerset statistics.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2f252205-f6f1-4996-bb77-33e8d61336d1)

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
A very first cut of statistics on the content, including additions, for Freecen2 has been prepared on test3.
There is an overall report
![overall statistics.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/753b5f9f-832e-478d-b175-897b1adfd7a6)

As well there is a county level report; somerset is an example
![somerset statistics.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/c184a63f-a3a0-4966-b9ee-a634c253fd27)

**Comment by geoffj-FUG** [comment]
Kirk
That covers a lot of good information.
However, RG11_2391 (8 Feb) and RG11_2392 (26 Feb) were Incorporated for SOM in the past 30 days but have not appeared on the report.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
This is a report from test3 and there are no incorporated files there. 
The code can be applied to production if it looks like it may be useful
There is a considerable amount that can be done with other reports if the basis is acceptable.

**Comment by geoffj-FUG** [comment]
Kirk
The base is acceptable. It contains far more information than FC1 reports.
