### ISSUE TITLE
Potential Coord issue with Volunteer registration

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1079]
I would be interested to know in what you do when FreeCEN notifies you
that a new transcribers has joined your group (or when one transfers
into it), and what the typical outcomes of it are.

With me, I always send an email to the transcriber, introducing myself,
let them know why I am writing to them, refer them to my project website
(so they can see which pieces I have available), and so, always a brief
email, few lines at most.

The responses however to these emails seems to be a problem for me, so
am wondering how others get along.  In most cases, I never hear back
from the person.  As to those that do respond, almost all have asked (in
various ways), why am I contacting them, my email was not expected. 
Have had just one registration what progressed beyond this, and that
person never completed a single page anyway.

In case anyone asks, all of my current team either came to me directly
via links found outside of FreeCEN, or through the old website (when the
links to co-ordinators were still there).

**Comment by DeniseColbert** [comment]
Story to gain tips/feedback for the Coord. Have suggested he checks if on any spam blacklists and use read receipts.

**Comment by Captainkirkdawson** [comment]
Not sure you will get this through a story. Few coordinators have access to zenhub

**Comment by DeniseColbert** [comment]
I will feed back any info we have for the Coord

**Comment by PatReynolds** [comment]
Denise to ask Chris to bcc her, so she can check they are getting out of his system.
