### ISSUE TITLE
188482263 Missing contact message from System (John)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1082]
Issue reported by **johnt** at 2020-12-21 12:11:03 UTC
Time: 2020-12-21T12:06:54+00:00
Session ID: 9b60ecec5fb774a92e584acc319e98bf
Problem Page URL: [/messages/userid_messages?locale=en](/messages/userid_messages?locale=en)
Previous Page URL: [https://www.freecen.org.uk/manage_resources/new?locale=en](https://www.freecen.org.uk/manage_resources/new?locale=en)
Reported Issue:
I have received a FreeCEN Servant email message for a contact action request 188438390, but when I login to the system I cannot see the message in my message list, so I cannot generate a response from the system.    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
Have confirmed there is an issue.

**Comment by Captainkirkdawson** [comment]
Talking through back of the head. No issue
