### ISSUE TITLE
Add standard name to District, Piece and Civil Parish.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1083]
Given that there are no standards on case control and special characters for TNA names and that transcriber input may vary in case there will be occasions when we will not be able to do a match. Hence we propose to add a standard name for the District, Piece and Civil Parish in the same manner as we did for Freecen2 Place and select based on that.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Databases updated with new field Code changed to use the new field and deployed to test3 for testing.

**Comment by Captainkirkdawson** [comment]
JohnT tested and we deployed.

**Comment by geoffj-FUG** [comment]
Done and dusted!
