### ISSUE TITLE
Ensure that there is not multiple processing of the same file from the same user

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1084]
Looking at the logs shows simultaneous processing of the same file from the same user this should not be permitted

E0 U6 S9 /C6: P21

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Interlock added and code deployed to test3.
Test by trying to do a replace on an existing file immediately after submitting the first; should get an error message

**Comment by geoffj-FUG** [comment]
Not a big enough load on the server this evening. 
From	Subject	Received	Size	
Test FreeCEN Servant	somt.cen processed rg10_2377.csv at 2021-01-27 11:34:03 +0000	9:34 PM	39 KB	
Test FreeCEN Servant	somt.cen processed rg10_2377.csv at 2021-01-27 11:33:41 +0000	9:34 PM	39 KB	
Test FreeCEN Servant	somt.cen processed rg10_2377.csv at 2021-01-27 11:31:22 +0000	9:31 PM	39 KB	
Test FreeCEN Servant	somt.cen processed rg10_2377.csv at 2021-01-27 11:30:53 +0000	9:31 PM	6 KB	
Test FreeCEN Servant	somt.cen processed rg10_2377.csv at 2021-01-27 11:30:31 +0000	9:31 PM	6 KB	
It was processed before I could reload it.
Try again tomorrow.
Geoff

**Comment by Captainkirkdawson** [comment]
Yes that may always be the case; may have to wait until its in production;
works on my test server which is slow
Kirk Dawson
Fairmont, B.C. Canada

**Comment by geoffj-FUG** [comment]
Kirk
In that case we may just have to let it go live.
Geoff

**Comment by Captainkirkdawson** [comment]
Yes
We moved test3 to a much faster and more lightly loaded server last week
