### ISSUE TITLE
Promulgation of the folio number

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1087]
@geoffj-FUG 
I have confirmed that the download of a file will **always have both the folio and page numbers** set whenever **a page number changes**.
This clearly is incorrect from a strict interpretation of the TWYS rules
But as far as I can see this will not interfere with any offline or online changes being made by transcribers, proofreaders, validators or coordinators.
It can be corrected if required by separating the treatment of folio and page numbers in the download.

**Comment by geoffj-FUG** [comment]
Kirk

 

That creates a problem.

 

If we take the process:

Transcriber – Uploads transcriptions several times. No need to download. Instructions say enter only when Folio changes. No impact.

Coordinator copies piece to Proofreader.

Proofreader downloads piece – Folio numbers added. Warnings produced for every second Folio number. Proofread and Uplaoded.

Coordinator copies piece to Validator.

Validator receives a piece with additional Warnings and has to accept every one of them. In a typical 5000 record piece this is an additional 125 records to accept.

 

So …

Can we change the Folio test to test whether on transition of the folio number is greater than 1 more than the previous folio number (i.e. a difference of 0 or 1 is valid). That will make things easier for converted FC1 spreadsheets too.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 

I have fixed the download so that the folio number is only included when it changes which means the file will represent what was uploaded.
This fix will apply to all new uploads, but not to those already downloaded.

Have also fixed the Folio and Page change display so that only displays the folio number when it changes
![folio change.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/e9067f64-0299-44a8-9413-d5c8a412b3b8)

Do not understand your comment about changing code to accommodate FC1; please explain

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

I will check it on the next piece I validate. I will get John to watch for it too.

 

I have a couple of priorities before that.

 

Geoff

**Comment by PatReynolds** [comment]
Needs confirmation that this issue is resoved. @geoffj-FUG to test

**Comment by geoffj-FUG** [comment]
I have just downloaded a couple of recently uploaded pieces and the folio number is not duplicated.
I have also uploaded a FC1 Traditional spreadsheet,, converted it to the new Headers, and downloaded it. No duplicated Folio numbers.
Looks good now
:)
Geoff
