### ISSUE TITLE
Durham Parms

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1092]
Ali is currently working on Durham at District level.

**Comment by Captainkirkdawson** [comment]
It is reported by @geoffj-FUG that _Durham presents another problem. It has listed wards at the District level._

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Is this true for all years or just one? Extent of issue is important in determining action

**Comment by Captainkirkdawson** [comment]
Ali reports _Classic examples are Islandshire and Norhamshire for DUR 1841.

These are NBL places, pieces are in FreeCEN1 for NBL. How have they changed to DUR in CEN2?_

**Comment by Captainkirkdawson** [comment]
Ali noted _the two 1841 districts mentioned above are not inter-county/inter-parish problems, they are erroneously linked by TNA to wrong county, being far away from Durham border. Yes, they will need moving, due to mistakes by TNA._

**Comment by FreecenBren** [comment]
I am not up to date with things. So here goes my questions or thoughts that
are probably all wrong as I have my FC1  head on.

This is what Genuki says about DUR/NBL

*From History, Topography 1841. Just one place as an example.*
*"KYLOE, a parish in the division of Islandshire, county Northumberland,
formerly in Durham.*

I am sure we will have many of these kind of situations in the future.
NTT and DBY  are but just two.
Even in today’s geography, places move from one county to another for the
Parliamentary Elections wards and reorganised County And City Councils.

FreeCEN have always gone by the National Archives split and the relative
PIECE number allocated by them.

I do not have an answer to this but I do know I am confused by just reading
what is happening.
Why cannot we just use the PARMS as they are in FC1 that match the images
in the respective Piece numbers that we are transcribing.
J
I am sure someone will  explain the issue in ‘Simple Terms’

Knowing how I feel at the moment I just get more confused.
I know some COORDS are as well.

Some clarity is needed.  Sorry to be a pain.

**Comment by Captainkirkdawson** [comment]
@FreecenBren 
Thanks for the comment. I will try to respond in simple terms

The Parms for CSVProc are 100% based on TNA. They are a complete extract of their information.
They have been extracted into a District> Piece>Civil Parish structure. Which is the TNA structure.

So **CSVProc is based on the same information used by Freecen1.** 

It has just being displayed in ways they were not previously available that makes analysis easier including by linking each District and Piece in CSVProc directly to the entry on TNA.

Hence I do not understand the source of the confusion. 

I also find the comment about KYLOE, a parish in the division of KYLOE, a parish in the division of Islandshire, county Northumberland,
formerly in Durham, county Northumberland, somewhat difficult to respond to based on your and Ali's comment

Freecen1 does not mention Durham in its content until 1851 so its not clear what or how they might have dealt with the 1841 parms. No files have been created in freecen1 or 2 for 1841 or 1851 in Durham

TNA has the KYLOE, a parish in the ward of Islandshire in Durham; it is in piece HO107_318 and that piece is not in Northumberland or Durham on Freecen1.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I do not understand why the 1841 districts are a problem by being a ward. Wards are the equivalent of Hundreds in other counties and that is how TNA has described all of 1841

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG  from wiki
County Durham was divided into wards, analogous to hundreds. From an 1840 map of County Durham [6].

Chester-le-Street
Sadberge
Easington
Stockton

Northumberland was subdivided into baronies, which were arranged in six wards ] The wards were analogous to hundreds. From the National Gazetteer of Britain and Ireland (1868) [12]

Bamburgh
Castle[45]
Coquetdale
Glendale[46]
Morpeth
Tynedale

So neither county seems to have some of the wards in TNA Durham

**Comment by geoffj-FUG** [comment]
Kirk

 

It was late at night and I did not investigate further.

 

My experience was that Hundreds, Wapentakes, Baronies were the same thing. 

 

In my experience Wards were a Borough administration area. Now I know better.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG No problem I did not know until I did some research.

There may well still be issues with 1841 in Durham but that is likely to be a common statement for 1841 everywhere
