### ISSUE TITLE
Put preview of messages into email

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1095]
See FreeREG1404
Reported Issue:
In the same way as we have for Contact messages, we should include the message content in the email from the SC to their syndicate members via the Syndicate Messages action so they don't have to login to read it.    

We should also do this for general message emails from the Message System action so they only need to login if they want to reply.

Consider limiting the amount shown.

Attachments - add or not?

![Screenshot](https://www.freereg.org.uk)

E0 U3 S8 C5: P16

**Comment by Captainkirkdawson** [comment]
Tweak code implemented for FreeREG when that is done

**Comment by Captainkirkdawson** [comment]
Being done as part of reg will apply automatically
