### ISSUE TITLE
Additional Rooms field in 1891 spreadsheet

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1096]
The spreadsheet for the year is missing this column, and the handbook states that the columns was only used for the 1901, and 1911 census. It has come to light that we have missed the entry in 1891.
I went through all of these fields several times and had them double checked. We have been transcribing and testing for months and this was completely missed.
A column called Rooms needs to be inserted after house_or_street_name. It should be tested for a value <=5 or null. If it is greater than 5 it should produce a Warning.
Geoff

**Comment by geoffj-FUG** [comment]
Note above should read <5  not <=5. The test is the same as 1901.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG field added to spreadsheet for 1891.Verification of the field is the same as 1901 Deployed to test3 for checking

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

I will test this evening

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

Spreadsheet downloaded.

 

Data populated with a range of Rooms entries. All test OK

 

Can be migrated.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Deployed to production
