### ISSUE TITLE
189842274 Place name additional space (Geoff)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1097]
Issue reported by **somt.cen** at 2021-01-06 05:57:54 UTC
Time: 2021-01-06T05:54:23+00:00
Session ID: c98c15c88c36bb371170455e20c2e589
Problem Page URL: [/freecen_csv_entries/5ff45571f493fd686ca759e4?locale=en](/freecen_csv_entries/5ff45571f493fd686ca759e4?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen_csv_entries/5ff45571f493fd686ca759e4/edit?locale=en](https://www.freecen.org.uk/freecen_csv_entries/5ff45571f493fd686ca759e4/edit?locale=en)
Reported Issue:
Kirk
Strange one here.
I cant get a match because the POB says Mc Arthur (note space).
The Place Names database has McArthur (no space) and is correct.
If I remove the space, make it true and accept it then the space reappears.
I have also tried replacing Mc Space with Mc but still it happens.
I have forced a review so that I can follow it.
Geoff
   E0 U4 S7 C7: P18

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed in #1120
