### ISSUE TITLE
189907836 Ireland searches(Clare Pierson)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1098]
Issue reported by **Clare Pierson** at 2021-01-07 00:10:36 UTC
Time: 2021-01-07T00:06:20+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
How on earth do I get no results when I search for McQuilkin in County Antrim census records??  Several McQuilkins lived in County Antrim, some in East Torr and Culfeightrin Civil Parish. I already have a copy of one census, but not of the McQuilkin for whom I want more information.

**Comment by DeniseColbert** [comment]
Contact enquirer that we're temporarily removing Ireland from the search.

**Comment by DeniseColbert** [comment]
Replied to Clare, closing
