### ISSUE TITLE
189929771 Incorrect year report (Geoff)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1099]
Issue reported by **somt.cen** at 2021-01-07 06:16:11 UTC
Time: 2021-01-07T06:11:46+00:00
Session ID: 5f552abe6cb8ef8b34721f960ea22544
Problem Page URL: [/csvfiles/new?locale=en](/csvfiles/new?locale=en)
Previous Page URL: [https://test3.freecen.org.uk/freecen_csv_files/my_own?locale=en](https://test3.freecen.org.uk/freecen_csv_files/my_own?locale=en)
Reported Issue:
Kirk
I am in test.
I have downloaded HO511924.vld which has become HO107_1924.csv.
I had a real query so I am actioning it in test.
I amended the incorrect record (a given name)
I saved it as a .csv file.
I uploaded it and got the following report:
We are sorry but the file and its records were not processed. The processing log follows and should contain a reason.
Started on the file HO107__1924.csv for somt.cen at 2021-01-07 06:10:29 +0000. 
Error: there is no piece HO107_ in 1841 for HO107__1924.csv in the database}. 
It has looked for the piece in 1841 instead of 1851. We had this issue once before. It seems to be back.
Geoff
    

![Screenshot](https://test3.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG It was my error in the formatting of the file name. For 1851 there was a double  hyphen rather than a single one. HO107__1924.csv  rather than HO107_1924.csv Corrected and deployed
