### ISSUE TITLE
Offline listing of index displays for District, Piece and Civil Parish

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1101]
@rhodamackenzie has identified that it would be extremely useful for the DM and Coordinators to be able to obtain an off line report of the index display

**Comment by Captainkirkdawson** [comment]
@rhodamackenzie CSV downloads of the District, Piece and Civil Parish full and yearly indexes are deployed to test3 for final testing. If OK will deploy to production.
@geoffj-FUG  FYI you may or may not want Coordinators to be aware of these or simply allow Rhoda to use them with coordinators in their clean up
Links on thye pages eg
![Districts.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/86e2f0ec-c01b-45c6-aa5b-d4b9cde28710)![district1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/400ab892-74d7-4b8b-8f02-ae782abfb37e)
Produce resulting cav files 
![district2.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/eb528ed7-9305-46a4-9e00-e756b96f9105)![district3.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/9796e95f-d8e3-4a84-ba8b-253160bdd15c)

**Comment by geoffj-FUG** [comment]
Kirk

 

Thanks for this. I will have a look.

 

Yes, I will make Coordinators aware as soon as they are available. I will write something to go with  it.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG In most cases @rhodamackenzie will have to action changes. They should use these to note what they want changed and why IMO

**Comment by rhodamackenzie** [comment]
Geoff,
Please ask the coordinators to use these when they are asking me to do name changes or moves as this will speed things up considerably. They can ignore punctuation issues as I will sort them out.
Thanks to you both for for doing this,
Rhoda

**Comment by geoffj-FUG** [comment]
Rhoda / Kirk
I will ask once they are live. Are they under the County menu?
Geoff

**Comment by rhodamackenzie** [comment]
Click:

County
Manage District (or pieces or civil parishes)
Choose year
Button is there at the top

There is another one for a large file under the full index button but best if they do not use that so only mention the one on the individual years
Cheers, Rhoda
[cid:image002.jpg@01D6E680.6854D240]

**Comment by geoffj-FUG** [comment]
Rhoda

 

That makes it all transparent and therefore so much easier.

 

Well done

 

Geoff

**Comment by Captainkirkdawson** [comment]
@rhodamackenzie @geoffj-FUG 

The full index one is the one that is used to ensure that Districts/Pieces or Civil Parishes have the same spelling. It can be used by Rhoda without reference to the coordinator to ensure a common spelling.

Coordinators though likely do need it if they want to try to line up the 1841 hundreds

I will add a final column for their notes or should I call it Actions Required @rhodamackenzie  and then deploy

**Comment by rhodamackenzie** [comment]
Yes, actions required is best title for that column.

**Comment by Captainkirkdawson** [comment]
@rhodamackenzie @geoffj-FUG Deployed to production
