### ISSUE TITLE
FreeREG Servant CC'd in email notification of reply to message

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1106]
When I open the message it appears that I'm getting the email the recipient gets, addressed to them:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/8090ee4d-e11e-42b4-97c2-b3ac9486b49d)

E0 U8 S7 C5: P20

**Comment by DeniseColbert** [comment]
Also see FreeREG in list of recipients, but I think we have a story for this already.

**Comment by Captainkirkdawson** [comment]
Thanks to @Vino-S the issue has been resolved. It occurred with replies to messages. Applied to test3
