### ISSUE TITLE
Issues with transcriber's "email address invalid" message 

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1109]
**UserID: ObeOne68**

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/c3bd8d54-c115-4a74-8617-093385fb8110)

1. The transcriber has no way of knowing why their email address was made invalid- can we give more info?
2. The request to check whitelist is confusing - can we give a link with a bit more information? If not our own Help, then Wikipedia maybe?
3. The message mentions @freereg.org.uk rather than @freecen.org.uk

ETA: The error message persists upon confirming and logging in again.

**Comment by DeniseColbert** [comment]
@DeniseColbert to request more info

**Comment by PatReynolds** [comment]
@DeniseColbert do you have more info?
