### ISSUE TITLE
Add processing option to list only errors

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1111]

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @johnt-freecen @rhodamackenzie Test3 is running the new upload and replace pages that add the Error only option also added an explanation

 ![New replace.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/79cfde81-51e5-4f12-b3f9-eb53e0265be6)

![New upload page.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/81b7082b-6ef6-4200-bdc4-71ab7f3315cf)

**Comment by johnt-freecen** [comment]
Hi All,

Just a comment, we could do with a way of publishing the introduction of these changes to the user community, at the moment I drop a note to my team who are live, but as we spread its use a smarter method is needed.

Regards

John

Sent from Mail for Windows 10
