### ISSUE TITLE
The 1911 census TNA civil parish extraction is incorrect in many cases

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1112]
Well as you know I am not a census expert and worked on certain assumptions.

It appears that 1911 blows those working assumptions into pieces (sorry about the pun)

My working assumption had been that a census document specified a single civil parish and that the entries that followed were part of that parish.

That is not necessarily true for 1911 where the census document can specify many civil parishes and the entries that follow do not identify a specific civil pariah.

See attachment for Tattenhall in Cheshire.

So my comments about separation and our guidance on the set up of the parms are likely in need of review and adjustment (including the one sent to me for proof reading.)

What is clear is that there is still an error in our TNA extraction. For the extraction all parishes should be just one entry

Waverton Cotton Abbotts Cotton Edmunds Foulk Stapleford Bruen Stapleford  

Now who knows if all entries for 1911 should only have a single entry for the parish(es) it appears that way since the cover page says parish or parishes
![tattenhall.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/4185a803-295f-48ef-bd8c-1963d97cb30a)

**Comment by rhodamackenzie** [comment]
The TNA entry has each parish on a separate line in other years, but for 1911 either all are on the same line or, or one is alone, with the others all together on the next line  - the former is what happened in Kirk's example. Presumbaly our extraction works on the principle of one parish per line
![image](https://user-images.githubusercontent.com/62574522/104855237-7fde9680-5903-11eb-98cf-c2f8690b2f73.png)

**Comment by Captainkirkdawson** [comment]
Yes we take a line break as a new parish. Clearly for 1911 we should have concatenated the 2 entries!!!!!!!!!!!!!!!!!!

**Comment by geoffj-FUG** [comment]
I have taken a step back and used Sock Dennis Somerset as an example.
The problem appears to me that we are applying 19C transcription rules toa 20C Census. (This problem may raise its head again in 1921, but I dont know their rules).
The first thing that we must take into account is that there is a one to one relationship between the Piece and the ED in 1911. The Piece is not broken into various EDs. Therefore the ED title is all the parishes in the Piece. That is also what Ancestry have. (We managed to split Chilthorne Domer out somehow). It is a brand new structure.
In previous years there were several EDs to a piece and an new ED for each parish so only one parish appeared in each ED.
That is where the Where census taken field comes in. 
Schedule 1 is Mr Mills of Northover, Ilchester. Northover is part of Ilchester. It was logical for him to appear in the same ED as Ilchester.
(Sock Dennis is also only about 2Km away).
If the powers that be in 1911 had simply named this ED as Ilchester we would have accepted it and gone on our merry way. Our system would have worked and our lat/long would have been recorded accurately and we could have been none the wiser.
My contention then is that we could simply put Chilthorne Domer back into the list for this ED. We record the ED with all the parishes in the PARMS just as Ancestry have done. We record the actual Parish in Civil Parish.
I had a look at RG14_14255 which has Ash Priors and Coombe Florey. The first part of the ED has been transcribed as Ash Priors. The report for the upload on 1st January says:
Working on Bishops Lydeard for 1911, in SOM.
Info: line 2 New Enumeration District 5.
Info: line 2 New Civil Parish Ash Priors.
Info: line 2 New Ecclesiastical Parish Ash Priors Holy Trinity.
Info: line 2 New Where Census Taken Ash Priors.
Info: line 2 New Ward -.
Info: line 2 New Parliamentary Constituency Western or Wellington Division of Somerset.
No Errors generated.

So the transcription issue can be handled in the Handbook Instructions.

Now I go back to my email to Kirk yesterday. What is the effect of this PARMS entry on searching? I have no experience with the search coding so do not know how the PARMS and searches interact.

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG To say I am exceedingly confused is an understatement. I finally found Sock Dennis after some head scratching. Its in piece Yeovil (RG14_14403)  
TNA has it as 
![14403](https://user-images.githubusercontent.com/2874694/104859376-29149500-58e2-11eb-8fff-c9913af54f53.png)
We extracted that as 2 parishes Chilthorne Domer and Sock Dennis Ilchester Northover
This is clearly incorrect. Ancestry call it Chilthorne Domer, Sock Dennis, Ilchester and Northover which is different from what is in the document itself so one could say it is also wrong as the order is wrong. But is there  logic to the order anyway
![Yeovil](https://user-images.githubusercontent.com/2874694/104859550-79d8bd80-58e3-11eb-8ea1-ab947da5ea72.png)
The first entry is the Parker household not The Mills; the latter is their address.
I do not understand where you get the **Where this census was taken** field nor the **civil parish** unless they are both
**Chilthorne Domer Sock Dennis Ilchester Northover** I would hesitate to put any punctuation into the parms; clearly the transcriber can by reading the document.
In your second example of the piece RG14_14255  The piece is Bishops Lydeard and the civil parishes are Ash Priors and Coombe Florey according although Ancestry lists them in the reverse order. I do not understand how it has been determined that this is the Civil Parish of Ash Priors with the Ecclesiastical Parish of Ash Priors Holy Trinity as there are multiple Ecclesiastical Parishes nor how we could say Where Census Taken is Ash Priors.
![Bishops](https://user-images.githubusercontent.com/2874694/104860709-ac85b480-58e9-11eb-8781-322cbaa0b9ef.png)
Searching on FreeCEN2 is currently based on the piece name not the civil parish ie in the latter case it would be Bishops Lydeard

**Comment by DeniseColbert** [comment]
@PatReynolds to look on Ancestry to see if the intersection of parishes is clear.

**Comment by Captainkirkdawson** [comment]
To be done when we decide on format of civil parish names for 1911
 district Leicester

 

RG14_19165 to 217        North West Leicester (all currently incorrect)

RG14_19218 to 264        North East Leicester  (these are all correct)

**Comment by Captainkirkdawson** [comment]
Following a video call with @geoffj-FUG we concluded that the TNA extract of 1911 was the best that could be done programmatically. That the issue was that the original TNA listing is flawed when it lists more than 1 Civil Parish.
When there are 2; the second may contain 1, 2 or more civil parishes with no clear separation between the names. If a name contains 2 words those can just as easily be 2 parishes.
The contents of the piece however do appear to contain the a separation between the parishes with a document listing the end of a parish.
![parish mtransition.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/53411e84-a95b-4180-8c49-0296e5e357fe)
We propose the following:
System actions 1)update the civil parishes list to 1911 to eliminate the second parish if it has more than a single word and inserts 'needs review' 2) provide access to the existing action of adding a civil parish to county and master county coordinators
Documentation. The instructions for the transcriptions of 1911 be updated to reflect that the coordinator when starting work on a new 1911 piece; reviews the list of parishes. If there is a needs review parish then they are to review the piece and determine and enter the appropriate civil parishes and delete the 'needs review parish' when complete.
It is likely that fewer than 20% of the pieces will be impacted.
