### ISSUE TITLE
Shorten the text under the We found n records

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1114]
The current text increases the white space
![Extra.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/8d749fc8-1963-4bb1-acbd-1594d9056ab4)

**Comment by Captainkirkdawson** [comment]
Test shortened; others may wish to wordsmith. But reduction on space is achieved
![shorter.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/1e04e953-a71b-4c20-932b-50be2d32af60)
see test3

**Comment by Captainkirkdawson** [comment]
@AlOneill please cast your eyes over the text but no extra words please

**Comment by AlOneill** [comment]
'Select' is more inclusive than 'click'.

Listed by birth date. Select a heading to sort by that column: select again to reverse the order. See individual details by selecting the View button.

Same number of words (26). Tone more friendly.

**Comment by Captainkirkdawson** [comment]
@AlOneill I have always used select when there are alternatives. Here there is just the one option.

**Comment by AlOneill** [comment]
Ah, select is a versatile and hard-working word! The thing is that keyboard-only users, both sighted and unsighted, _cannot_ click: they select (follow) a link by using Enter or whatever key combo works in their screen-reader software. Maybe not all that important, but I can imagine that being asked repeatedly to click must be irritating — one more straw on the camel's back. Cannot think of a parallel situation just now …

**Comment by Captainkirkdawson** [comment]
Wonderful explanation. TY

**Comment by AlOneill** [comment]
@Captainkirkdawson Removing the class `hard--bottom` from the containing `section` restores overall balance and adds only a little to the height. Is this acceptable?

![no-results-alt-01.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/98f6eea3-3c05-483c-b077-fe7ddda1364b)

**Comment by Captainkirkdawson** [comment]
Personally I would say that making that paragraph larger than the You searched for adds addition empty space to page which is what we were trying to eliminate

**Comment by AlOneill** [comment]
It adds a few pixels only. Re-writing the text has made a big improvement. Visual balance for the "We found …" section is also important — imbalance is uncomfortable for some (even many?).

Let the Scrum decide!

**Comment by Captainkirkdawson** [comment]
Its always been out of wack; less so now

**Comment by PatReynolds** [comment]
Scrum agreed that the few pixels of grey improve legibility, so should be implemented.
