### ISSUE TITLE
Update the civil parishes list for 1901 and eliminate all entries

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1128]

**Comment by Captainkirkdawson** [comment]
I have run the civil parish delete on 1901

There were 99 pieces that had csv entries and therefore could not be deleted. 

Those pieces need to be checked for accuracy of the civil parishes.

List sent to @geoffj-FUG  off line

**Comment by geoffj-FUG** [comment]
Kirk

I have been though the 99  entries for 1901 CON and SOM and all are genuine entries and do not need amendment or removal.

Geoff

**Comment by PatReynolds** [comment]
Thank you @geoffj-FUG . @Captainkirkdawson what is needed now?
