### ISSUE TITLE
Enable access to the adding a civil parish to a piece for county and master county coordinators in 1901 and 1911

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1129]
There is an exiting action on the freecen2_piece that allows the adding of a new civil parish. Currently restricted. Activate it for the county_coordinator and master_county_coordinator for 1901 and 1911 pieces while retaining it for those currently permitted.

**Comment by AnneV-Learn** [comment]
Pulled to Master and deployed
