### ISSUE TITLE
Enable access to the deleting a civil parish to a piece for county and master county coordinators in 1901 and 1911

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1130]
There is an exiting action on the freecen2_parish that allows the deletion of civil parish. Currently restricted. Activate it for the county_coordinator and master_county_coordinator for 1901 and 1911 pieces while retaining it for those currently permitted.

**Comment by AnneV-Learn** [comment]
Hi Kirk,

On freecen2_piece, from what I can determine, there is currently the option to delete a piece but not a civil parish (that appears on the freecen2_civil_parishes pathway).
Can you please clarify what is required for #1130 as the story is 'Enable access to the deleting a civil parish’.
Thanks
Anne

**Comment by Captainkirkdawson** [comment]
Da Huh

Never write from memory without checking

Story amended

**Comment by AnneV-Learn** [comment]
Pulled to Master and deployed
