### ISSUE TITLE
Add userid to file name in the Freecen2 Piece show

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1133]
The current show of a piece provides a list of files associated with the piece.
![piece file name.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/3de18253-94be-4bbd-9a7e-3fc5577c431c)
As in this example there are 2 and could be as many as 4 (One each for transcriber, proofreader, validator and coordinator)

It would be useful to know the userid of the person who owns each of the files. Hence the suggestion to add the userid in () after the file name.

Every file belongs to just one userid

**Comment by AnneV-Learn** [comment]
Pulled to master and deployed by KD
