### ISSUE TITLE
London in 1861

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1134]
We need to decide if we intend to create and use LND as a county in 1861. Currently there are no pieces identified as LND in 1861.   

The first pieces relevant to London in our database start with 1871. It has been an accepted practice that 1871 and 1881 fit into “London” as this is what they were recognised as being at the time even before the formal change of making London officially a County in 1889. 

The pieces for 1861 appropriate for London are known and recognizable as such. Currently they are included in their historical counties of Kent, Middlesex and Surrey.

**FC1 does not have London in 1861** ; it starts in 1871. However from a transcription perspective it was managed as a separate entity.

The people involved recognize it can be set up either way. Technically it can be supported either way. 

We need to adopt a formal position as to what we will do.

**Comment by PatReynolds** [comment]
Pat to explore with Kirk

**Comment by PatReynolds** [comment]
Is this now resolved by current work on Gazatteer and place?

**Comment by Captainkirkdawson** [comment]
This was dealt with in story #960
