### ISSUE TITLE
Add additional statistics to the statistics collection

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1135]

**Comment by Captainkirkdawson** [comment]
Set up a new collection targeted at FreeCEN.
Code currently has an issue with duplication

**Comment by Captainkirkdawson** [comment]
There is now a basic data collection system available to run on test3. It is basically only viable through statistical reports
Fields collected for each year and county as well as totals are
      [:individuals] 
      [:dwellings] 
      [:vld_files_on_line] 
      [:vld_files] 
      [:csv_files] 
      [:csv_files_incorporated] 
      [:vld_entries] 
      [:csv_entries] 
      [:csv_entries_incorporated] 
      [:search_records] 
      [:added_vld_files] 
      [:added_vld_entries] 
      [:added_csv_files] 
      [:added_csv_entries] 
      [:added_csv_entries_incorporated] 
      [:added_search_records]

**Comment by DeniseColbert** [comment]
@PatReynolds suggested Institutions and Vessels; @Captainkirkdawson to have a think about this

**Comment by PatReynolds** [comment]
Possibly date last vld added as something reported in the Records?

**Comment by Captainkirkdawson** [comment]
last vld added is something that I would expect that we would add to the new Reports @AnneV-Learn

**Comment by Captainkirkdawson** [comment]
As I said at the meeting things like institutions and vessels are specific characteristics of a field and generally not meanable to generalised statistics for the full site. The cost of their extraction on a county by county basis is going to be high
