### ISSUE TITLE
Page number reported as error with ED in middle of page

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1137]
Issue reported by **somt.cen** at 2021-02-09 12:04:29 UTC
Time: 2021-02-09T11:57:28+00:00
Session ID: 56a5cb1e7850b8b21f5e180ab907638f
Problem Page URL: [/freecen_csv_entries/60227871f493fd7447464bf7?locale=en&type=Err](/freecen_csv_entries/60227871f493fd7447464bf7?locale=en&type=Err)
Previous Page URL: [https://www.freecen.org.uk/freecen_csv_entries?locale=en&type=Err](https://www.freecen.org.uk/freecen_csv_entries?locale=en&type=Err)
Reported Issue:
Kirk
I have uploaded a FC1 file
It reported errors so I fixed them
Replaced it in FC1 format. Row 5859 passed test.
Converted it to FC2 format and downloaded it. 
Tidied up some flags.
Replaced it and got an error report.
Row 5859 page number error.
I will send the report by email
Geoff    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
I am sorry Geoff but I really do not understand the sequence of events. It would appear that the second was a reprocessing to create the warnings and that this was followed by a conversion which appears fine by looking at it in the attic Ecclesiastical Parishes were then added The failure was cause by line 5859 have an Ecclesiastical Parish of St John added without page/folio information to an entry that looks like it was in the middle of a page
 5,Yeovil,St Johns,Yeovil,-,-,Yeovil,,,,134,,1,Middle Street,,WADMAN,Robert S,,Head,M,M,40,,Draper,,SOM,Yeovil,,,,,, 
Kirk

**Comment by Captainkirkdawson** [comment]
The whole design was based on the concept that a new ED would always have folio/page information; 

I do not really understand as the FC1 has no ED break at that point.

It is not seeing a 0 but a blank when it is expecting something because it is an ED

**Comment by Captainkirkdawson** [comment]
Kirk
Can we wrap the test in an if statement?
If new Ed Number <> old ED number
       Do page number test
Endif
That would stop it testing for a page number when the transition is in the middle of a page, or the ED number is repetitive such as with merchant vessels. Transitions in the middle of a page can happen with ecc parishes (like the reported problem) or a new where_census_taken such as a change of hamlet.
This is one of those conditions that will crop up regularly but does not conform to what is expected. My gut tells me that all three instances I have come across are related to this problem.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
Turns out the issue was a little different, I was erroring out on a non digit field. There was code to handle a blanks but it was never being activated because of the earlier detection of a non digit.
Will deploy in the next deployment
