### ISSUE TITLE
Develop regex capability to search for string in Freecen2Place name

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1140]
This is the core requirement to support a number of string search capabilities

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG what is the minimum size of the search string? 2 or 3 characters? Clearly 1 is too few.

**Comment by geoffj-FUG** [comment]
Kirk

 

I think we could go for 3. Two is pointless as it will bring up too many options.

 

Geoff

**Comment by Captainkirkdawson** [comment]
OK minimum of 3 it is

**Comment by AnneV-Learn** [comment]
Deployed to Test3 by KD.
@geoffj-FUG this is ready for testing now.
