### ISSUE TITLE
Apply Search Place Names regex to any part of place name

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1143]
Add option selection to Search Place Names Search page
Add selection code
Augment Search Place Names Results to indicate form of search

**Comment by AnneV-Learn** [comment]
Deployed to Test3 by KD.
@geoffj-FUG this is ready for testing now.

**Comment by geoffj-FUG** [comment]
Anne

 

Magic!

 

Can you please migrate this to FreeCEN2.

 

Well done. I think that the users will be pleased.

 

Geoff
