### ISSUE TITLE
Timeout on removal

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1145]
Two attempts at removal.

Unlocked incorporation - OK

Removed but timed out both times.

Record removal failed

rg11_2389.csv for somt.cen in SOM ProceedingErrno::ETIMEDOUT: Operation timed out - Took more than 100 seconds to receive data (for 88.99.215.156:27017 (mongo1.freeukgen.org.uk:27017, TLS)) (on mongo1.freeukgen.org.uk:27017, connection 1:1, retries disabled), ["/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/socket.rb:419:in `rescue in map_exceptions'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/socket.rb:415:in `map_exceptions'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/socket.rb:190:in `read'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/protocol/message.rb:232:in `deserialize'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection_base.rb:168:in `block (2 levels) in deliver'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection_common.rb:84:in `add_server_diagnostics'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection_base.rb:165:in `block in deliver'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection_common.rb:124:in `ensure_connected'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection_base.rb:155:in `deliver'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection.rb:300:in `block in deliver'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection.rb:306:in `handle_errors'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection.rb:299:in `deliver'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection_base.rb:145:in `dispatch'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/executable.rb:63:in `dispatch_message'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/executable.rb:56:in `get_result'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/response_handling.rb:96:in `add_server_diagnostics'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/response_handling.rb:82:in `unpin_maybe'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/executable.rb:26:in `do_execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/executable_no_validate.rb:25:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/write.rb:49:in `block in execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server/connection_pool.rb:590:in `with_connection'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/server.rb:425:in `with_connection'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/operation/shared/write.rb:39:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/collection/view/writable.rb:196:in `block (2 levels) in delete_many'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/retryable.rb:261:in `nro_write_with_retry'", "/usr/local/lib/ruby/2.6/forwardable.rb:230:in `nro_write_with_retry'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/collection/view/writable.rb:185:in `block in delete_many'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/client.rb:1018:in `with_session'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/collection/view.rb:212:in `with_session'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/collection/view/writable.rb:179:in `delete_many'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongoid-7.1.5/lib/mongoid/query_cache.rb:188:in `block (2 levels) in alias_query_cache_clear'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/mongo-2.13.1/lib/mongo/collection.rb:646:in `delete_many'", **"/home/apache/hosts/freecen2/production/lib/freecen_csv_file_unincorporate.rb:29:in `unincorporate_records'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_file_unincorporate.rb:14:in `unincorporate'", "/home/apache/hosts/freecen2/production/lib/tasks/freecen_update.rake:41:in `block in <top (required)>'",** "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `block in execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `each'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/airbrake-11.0.1/lib/airbrake/rake.rb:19:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'", "/usr/local/lib/ruby/2.6/monitor.rb:235:in `mon_synchronize'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/bin/rake:23:in `load'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/bin/rake:23:in `<main>'"]

**Comment by Captainkirkdawson** [comment]
Alternate way of deletion adopted and deployed to test3

**Comment by Captainkirkdawson** [comment]
Deployed to production as critical

**Comment by PatReynolds** [comment]
Thanks, @Captainkirkdawson
