### ISSUE TITLE
[production][freecen2_places#destroy] Errno::ETIMEDOUT: Operation timed out - Took more than 100 seconds to receive data (for 136.243.1...

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1153]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/5b63313de937903f2020c67f/problems/602b0039e93790b8acadc6ad)

**Comment by Captainkirkdawson** [comment]
This is a one off; given the code I fail to see why it was not an immediate response. The socket timeout having been doubled should help. I suggest this be closed and reopened if it reoccurs.

**Comment by Captainkirkdawson** [comment]
Turns out it was not fixed and was not a one off
The method was making sure that there were no records; districts, pieces or civil parishes using that place. I had forgotten to add the indexes that  would support such checks. it was reading all search records! My bad. 
Indexes are added should behave as designed. (Fingers crossed)

**Comment by Captainkirkdawson** [comment]
Ali reports that the fix has worked.

**Comment by PatReynolds** [comment]
Thanks @Captainkirkdawson and Ali Closing
