### ISSUE TITLE
[production][search_records#show] nil can't be coerced into Integer

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1154]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/5b63313de937903f2020c67f/problems/600c80e1e93790e8d4d6200c)

**Comment by Captainkirkdawson** [comment]
Added test to avoid a nil situationand deployed to test3

**Comment by PatReynolds** [comment]
@Vino-S to test
