### ISSUE TITLE
[production][search_records#show_citation] SearchRecordsController#show_citation is missing a template for this request format and variant.
...

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1155]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/5b63313de937903f2020c67f/problems/5ffe2112e93790ed19319b78)

**Comment by Captainkirkdawson** [comment]
Code in wrong place. Fixed. applied to test3

**Comment by PatReynolds** [comment]
Thanks, @Captainkirkdawson I will test
