### ISSUE TITLE
[production][freecen2_civil_parishes#show] undefined method `chapman_code' for nil:NilClass

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1156]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/5b63313de937903f2020c67f/problems/60284625e93790c6c83d79ca)

**Comment by Captainkirkdawson** [comment]
Put in trap in view and deployed to test3
Seemed that it was likely restricted to data managers

**Comment by PatReynolds** [comment]
@Captainkirkdawson just been told about your email by Denise - do you want this testing first, if so please ask Vino, otherwise just deploy (same for others where people have been allocated to test).
