### ISSUE TITLE
[production][search_queries#create] Errno::ETIMEDOUT: Operation timed out - Took more than 100 seconds to receive data (for 88.99.215...

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1157]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/5b63318ae937903f2020c6a0/problems/602c1401e937907c168a482f)

Occurring 2-3 times a day on all servers

**Comment by Captainkirkdawson** [comment]
These are occurring daily on all servers. Freereg is also exhibiting 1 or 2 a week on all servers. Topography of Mongos is different. CEN has a primary and a single secondary with no sharding so all requests go to these 2 servers. Do not believe that to be an issue.
Tracing 1 particular case on CEN a search for James in Chesterfield. Search created at  : ISODate("2021-02-17T15:02:58.025Z").  Time out message recorded at Feb 17 15:06:19. **That search does not seem to appear in our search performance stats. Likely because there is no runtime and the display is by run time!** 
There have been 15 such timeouts in the past 10 days.
Now we have a maximum search time of 100 seconds yet a timeout on an operation of 100 seconds. Need to think about that. Now do we reduce the search time maximum or increase the timeout?
Have set the socket timeout to 200 seconds on all servers for the FreeCEN2 database. Will monitor for a week.

**Comment by Captainkirkdawson** [comment]
Was no timeout on 18th or 19th on any server; However there was an increase in the number of searches terminated for running too long which is a controlled termination as opposed to a red screen crash

**Comment by PatReynolds** [comment]
Could you let us-all or me know what you need discussing, please?

**Comment by Captainkirkdawson** [comment]
Awareness only
