### ISSUE TITLE
Why are first name in a place taking more than 100 seconds?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1158]
There were 6 first name searches on 18 Feb that took more than 100 sec. Why?
![place first name.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/9487be21-e85c-4fa7-8316-a29dcdeecdca)

E1 U4 S9 C5:P19

**Comment by geoffj-FUG** [comment]
I have a report of timeouts when a Place Name is being Disabled in the Gazetteer. This is affecting the Yorkshire linking in particular.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG what you refer to is a different issue although it appears to be similar. [production][freecen2_places#destroy] Errno::ETIMEDOUT: Operation timed out - Took more than 100 seconds to receive data (for 136.243.1...#1153. That story has had a fix applied  and Ali confirms it is now working

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

Geoff

**Comment by Captainkirkdawson** [comment]
Resolved by index restructuring
