### ISSUE TITLE
Automated processing and checking of uploaded CSV file

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#116]
A report will be generated by a from CEN2 File Processor somewhat along the lines of that produced by CSVCHECK and returned to the uploader.   Should prevent empty fields. Checks should implement Free UK Genealogy methodology.

**Comment by Captainkirkdawson** [comment]
The multimodal code has been adjusted to use the physical files collection for FreeCEN2, The same process for rake processing initiation has been adopted and is functioning.
Now for the checking processes.
