### ISSUE TITLE
IOW place names when dealing with HAM

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1162]
The IOW place names are not being seen when I am updating the HAM PARMS. IOW is a subset of HAM.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Should IOW be incorporated into HAM or remain as a separate county?

**Comment by geoffj-FUG** [comment]
Kirk

IOW is part of HAM. But it can be enumerated as IOW or HAM.

We need the Chapman Code model of level 2 HAM level 3 HAM or IOW for validation of POBs. 

As far as PARMS is concerned they can be one County.

PARMS and validating are using the same Gazetteer for 2 different purposes.

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG deployed

**Comment by geoffj-FUG** [comment]
Kirk

 

All good

 

These are now linked

 

This can be closed

 

Geoff
