### ISSUE TITLE
Freecen1 update on freecen2 has files that occasionally crash due to file content errors

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1166]
Did you notice the 3 errors

starting self.process_vld_file() for /raid/freecen2/freecen1/pieces/LAN/rg123026.vld at 03:47:43 PM
   transform start at 03:47:52 PM
***EXCEPTION CAUGHT while processing process_vld_file:
  undefined method `match' for nil:NilClass

["/home/apache/hosts/freecen2/production/lib/freecen1_vld_transformer.rb:23:in `block in transform_file_record'",

starting self.process_vld_file() for /raid/freecen2/freecen1/pieces/LAN/rg123155.vld at 03:51:29 PM
   transform start at 03:51:37 PM
***EXCEPTION CAUGHT while processing process_vld_file:
  undefined method `match' for nil:NilClass

["/home/apache/hosts/freecen2/production/lib/freecen1_vld_transformer.rb:23:in `block in transform_file_record'",

 starting self.process_vld_file() for /raid/freecen2/freecen1/pieces/LAN/rg123340.vld at 03:51:45 PM
   transform start at 03:51:57 PM
***EXCEPTION CAUGHT while processing process_vld_file:
  undefined method `match' for nil:NilClass

["/home/apache/hosts/freecen2/production/lib/freecen1_vld_transformer.rb:23:in `block in transform_file_record'",

unless dwelling.uninhabited_flag.match(Freecen::Uninhabited::UNINHABITED_PATTERN)

That code is 6 years unchanged!! 

Implies a nil for  dwelling.uninhabited_flag  in unless dwelling.uninhabited_flag.match(Freecen::Uninhabited::UNINHABITED_PATTERN)

Very strange

**Comment by Captainkirkdawson** [comment]
@Vino-S @FreecenBren An offline processing of the file RG123155 under diagnostic conditions shows that the crash is a symptom of an incorrectly formatted record. While it would be possible to avoid the crash this would simply allow the  creation of incorrect entries. Hence we are better to let the crash occur.
 age: nil, age_unit: nil, birth_county: "ber", birth_place: "bach          -", birth_place_flag: nil, civil_parish: "ton Upon Irwell  14", deleted_flag: nil, detail_flag: nil, disability: nil, dwelling_number: 97000, ecclesiastical_parish: "herine", enumeration_district: " 11", folio_number: "  16", forenames: "                  -Wife", house_number: "  Pe", house_or_street_name: "l Green Road  Ivy Farm-PLATT", individual_flag: nil, language: nil, marital_status: "-", name_flag: nil, notes: "                                      St Cat", occupation: "                        -CHSCo", occupation_flag: "m", page_number: 96, relationship: "MF58 y", schedule_number: nil, sequence_in_household: 0, sex: nil, surname: "                  Elizth", uninhabited_flag: nil, unoccupied_notes: "                                      St Cat", verbatim_birth_county: "ber", verbatim_birth_place: "bach

The next step is to investigate why the vld parser which extracts the data is having difficulty

**Comment by Captainkirkdawson** [comment]
@Vino-S @FreecenBren  Further off line investigation shows where these files go wonky

Processing **rg123155.vld**
**The line BEFORE the following was where there was a special character present. It then appears also in the following records**

"000970003Barton Upon Irwell  14  11   16  96       Peel Green Road Ͼ� Ivy Farm-PLATT                   Frances R E             -Daur  SF15 y-(Em'ee)                       -DENLlanraider          -                                                   St Catherine        DENLlanrhaeadr         C\u0000\u0000\u0000\u00000000"
{:deleted_flag=>"0", :hh=>"0003Ba", :suffix=>"0097", :parish=>" Upon Irwell  14  11", :enum_n=>"   ", :enum_a=>"1", :sch_n=>"   ", :sch_a=>"P", :house_n=>"eel ", :house_a=>"G", :street=>"reen Road Ͼ� Ivy Farm-PLATT   ", :prem_flag=>" ", :ecc_parish=>"ine        DENLlanrh", :individual_flag=>" ", :seq_in_household=>"rton", :s_name=>"               Frances R", :f_name=>" E             -Daur  SF", :name_err=>"1", :rel=>"5 y-(E", :m_stat=>"m", :sex=>"'", :age=>"ee)", :age_unit=>" ", :p_det_err=>" ", :occ=>"                     -DENLlanr", :occ_err=>"a", :t_born_cty=>"ide", :t_born_place=>"r          -        ", :place_err=>" ", :dis=>"      ", :language=>" ", :notes=>"                                   St Cather", :born_cty=>"aea", :born_place=>"dr         C\u0000\u0000\u0000\u00000000", :fo_n=>"6  9", :fo_a=>"6", :pg_n=>"    ", :unoccupied_notes=>"                                   St Cather"}

Processing **rg123026.vld**
**The line BEFORE the following has something wrong with it.**

"\u0000\u0000\u00000007810005Sutton              35  73   26  150 25   Walkers Lane                  -CARNEY                  Thomas                  -BoardrSM21 y-Farm Labourer(Em'ee)          -IRL-                   -                                                   St Nicholas                                N\u0000"
{:deleted_flag=>"\u0000", :hh=>"078100", :suffix=>"\u0000\u000000", :parish=>"tton              35", :enum_n=>"  7", :enum_a=>"3", :folio=>"   2", :page=>"  15", :sch_n=>"0 2", :sch_a=>"5", :house_n=>"   W", :house_a=>"a", :street=>"lkers Lane                  -C", :prem_flag=>"A", :ecc_parish=>" Nicholas           ", :individual_flag=>"A", :seq_in_household=>"05Su", :s_name=>"RNEY                  Th", :f_name=>"omas                  -B", :name_err=>"o", :rel=>"ardrSM", :m_stat=>"2", :sex=>"1", :age=>" y-", :age_unit=>"F", :p_det_err=>"a", :occ=>"rm Labourer(Em'ee)          -I", :occ_err=>"R", :t_born_cty=>"L- ", :t_born_place=>"                  - ", :place_err=>" ", :dis=>"      ", :language=>" ", :notes=>"                                          St", :born_cty=>"   ", :born_place=>"                  N\u0000", :fo_n=>"   2", :fo_a=>"6", :pg_n=>"  15", :unoccupied_notes=>"                                          St"}

Perhaps you can find the errors , correct and let me have copies and I can confirm

**Comment by Captainkirkdawson** [comment]
@Vino-S I have committed to master the code that detects when a vld file has got out of correct sequence. A crash is caused on the first detected incorrect line. The actual line that is incorrect  is the one PRIOR to this.

**Comment by FreecenBren** [comment]
Neil is on holiday so I will look at them tomorrow.
It looks like the same problem he had last  year.
I have copies so will let you know.

Strange that neither CSVCHECK nor FC1 upload rejected them as they went
through on there.Thanks for pointing them out.
I will let him know anyway to what adjustment I make.

This is what it looks like on FC1 search page for the address.
Strange it happens for LAN each time.


*Piece:* RG12/3155 *Place:* Barton upon Irwell -Lancashire *Enumeration
District:* 14
*Civil Parish:* Barton Upon Irwell *Ecclesiastical Parish:* St Catherine
*Folio:* 11 *Page:* 16 *Schedule:* 96
*Address:* Peel Green Road Ï¾ï¿½ Ivy Farm


Will sort it out tomorrow and it will get updated  next week at the FC1
 upload.
Many thanks Brenda

**Comment by FreecenBren** [comment]
This is the 2nd one. The issue is in the occupation.
Will fix it as well tomorrow

*Piece:* RG12/3026 *Place:* Prescot -Lancashire *Enumeration District:* 35
*Civil Parish:* Sutton *Ecclesiastical Parish:* St Nicholas
*Folio:* 73 *Page:* 26 *Schedule:* 150
*Address:* 25 Walkers Lane

------------------------------
  Surname First name(s) Rel Status Sex Age Occupation Where Born Remarks
    TIMBLIN   John   Head   M   M   32   Blacksmiths Labourer(Em'ee)
 Lancashire
- Woolton
    TIMBLIN   Margaret   Wife   M   F   24       Lancashire - Rainhill
    TIMBLIN   Ellen   Daur   -   F   2       Lancashire - Sutton
    NEE   John   Boardr   M   M   50   Sï¿½alt Works Labourer(Em'ee)    Ireland
- -
    CARNEY   Thomas   Boardr   S   M   21   Farm Labourer(Em'ee)    Ireland
- -
    CAHILL   Bridget   Ma-Law   W   F   65       Ireland - -

Cheers Brenda

**Comment by Captainkirkdawson** [comment]
Long term solution is the same as #803
