### ISSUE TITLE
1841 Missing from Isle of Man PARMS

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1167]
The Isle of Man is missing the Isle of Man District, its pieces and Civil Parishes in 1841. They are attached to the Channel Islands.
The Isle of Man 1841 needs to be moved to the rest of the Isle of Man records.
Geoff

**Comment by FreecenBren** [comment]
Can you clarify this please as I am a little confused.

We do not have the 1841 for either Isle Of Man, nor for what was called in
1841 the *Islands in the British Seas* which includes Guernsey and Jersey.

Piece numbers are as follows for 1841
H0107/1460 to 1465 as follows

This is split  between the 3 places.
1460 are Guernsey
1461 to 1462 are  for Jersey
1463 to 1465 are the Isle of Man.

When it comes to 1851 it is as follows. H0107/2523 to 2531

2523 to 2526 are for Isle of Man
2527 to 2529 are Jersey
2530 to 2531 are Guernsey.

1. We do not have any images nor PARMS for 1841 nor 1851 for the Channel
Islands in FC1.

2. We also do not have the Census Images nor the PARMS  for 1841 for Isle
of Man.

3. We do have 1851 and 1861 for the IOM  and will all soon be online.

1841 ; Looking at the Census places in the *Isles in the British Seas* i
cannot see where the  IOM are attached to it.

As we have no PARMS in FC1 for either of these 1841 places could you please
point out where I am missing them.

As I look after both Counties, and there are NO PARMS created yet nor any
Census Images to look at, what am I missing.

I  would appreciate any more information about where they are showing?

Many thanks Brenda

**Comment by Captainkirkdawson** [comment]
@FreecenBren this story has nothing to do with FreeCEN1 and whatever parms or images you may or may not have.

It refers to Freecen2  where we are doing a one time establishment of the District, Piece and Civil Parish information based on TNA extracts. We do not worry about whether or not we have the images. After all we may have access to them one day.

At this point in time we are making sure that the TNA information  is consistently structured on FreeCEN2 across all years.

As you correctly observed in 1841 TNA included the IOM with Guernsey and Jersey in a county called Islands in the British Seas.

This story says that **for FreeCEN2** we need to move the information from Islands in the British Seas into their appropriate counties.

So there is nothing that you need to do. The story is an action request for me.

**Comment by geoffj-FUG** [comment]
Brenda

 

The story refers to FC2. TNA have IOM under British Seas, which is otherwise CHI in 1841. The story is for Kirk to move it so that the FC2 PARMS can be done.

 

Geoff

**Comment by geoffj-FUG** [comment]
The 1841 census detail for 1841 is recorded under CHI. As well as the problems with IOM, 1841 is the only year where JSY, GSY etc are entered under CHI. In the other years they are under their own Chapman Codes.
Geoff

**Comment by Captainkirkdawson** [comment]
Completed

**Comment by geoffj-FUG** [comment]
IOM resolved and PARMS amendments done.
