### ISSUE TITLE
Multi county parms report

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1172]
Geoff is beginning to consider what has happened to the PARMS. The Coordinator needs to know where the whole of the piece is. We have broken it up. The ‘home’ Coordinator has all the Images and will need to organise transcription even if part of the piece is in another County. They therefore need to be able to enter a TNA piece number and see the various parts of it in our PARMS.

E0 U6 S7 C5: P18

**Comment by PatReynolds** [comment]
Sorry, @geoffj-FUG - another one that I don't know whether or not it is still needed.

**Comment by geoffj-FUG** [comment]
Resolved by Locate a piece in the County Coordinator actions.
Geoff
