### ISSUE TITLE
Display the pieces loaded for a specific county by year and by total

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1173]
There is a FreecenSiteStatistics collection that contains a records hash that has information for every county for every year. This is used to drive the County Statistics action ( It also drives the full Site Statistics action used by management.
An example follows
![county.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/b1835e6e-c3b0-49e9-b5b6-da6147ab0584)
What is need is a link from the contents of the fields in the highlighted boxes to take one to an index display of the files that are included in those boxes.
There are existing index displays that likely can be used for this purpose. The vld one may need some modernization. Breadcrumbs will need adjustment to allow one display to meet multiple uses. We need to add two columns  On Line and Physical.  The former is taken from the online status in the piece while the other is found by looking up the actual files. They SHOULD be the same. But if not it indicates a problem
![vld files.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/3979f35e-36c2-4ad2-947e-bd2be2ee62fa)
The csv one is likely OK
![csv files.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/552f6971-cc65-4bdd-998b-c7dcc7f90f19)

**Comment by AnneV-Learn** [comment]
Deployed to Test3 - 2 CSV columns with drill down and 5 data integrity check ‘flags’. 
Ready for initial review.
