### ISSUE TITLE
Add 'Back' buttons to the 'Data Coverage' Pages

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1174]
Back buttons are needed from the totals and percentage graphs (link from 'Data coverage'  detail of county/year page) and from the 'Data coverage' detials of county/year pages back to the Records detail page back to the main 'Database coverage' page (Records page).

I am suggesting doing this to discourage users from using their browser back button anywhere on the site

**Comment by Captainkirkdawson** [comment]
Suggest that this be part of the overall recode of the FreeCEN Records action

**Comment by PatReynolds** [comment]
Back buttons now in place and functioning as expected.
