### ISSUE TITLE
Volunteer Coordinator role

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1175]

**Comment by DeniseColbert** [comment]
Currently looking to find out what to do with:

- new transcribers who have selected a county of Brenda's that she is letting go of
- new transcribers who have selected England Syndicate

Awaiting responses to emails re. the above from @geoffj-FUG 

Also wondering why I've been receiving file processing emails since 6th March:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/04e87f63-cc1a-4b9c-8c27-6fc90d75437d)

@Captainkirkdawson @geoffj-FUG - does the Vol COORD need these for something?

**Comment by Captainkirkdawson** [comment]
Those are actually being sent to the syndicate coordinator and I implemented the process by naming the Volunteer Coordinator as the syndicate coordinator who gets the email if different from the county coordinator if different. I can turn off if you like

**Comment by geoffj-FUG** [comment]
Kirk

I need to think about that one. Denise will need to receive test results from Newbies but once handed over to the Coordinator she will no longer need them.

Denise, if you can set a rule to move them into an email sub-folder that will get them off your screeen for now. 

I need to get the process straight in my mind before I make a final comment.

We dont want them going back to Brenda.

Geoff

**Comment by DeniseColbert** [comment]
No problem then, I'd already created a filter but wondered if I should be doing anything with them. I'll ignore them until I hear otherwise. Many thanks, @geoffj-FUG & @Captainkirkdawson

**Comment by geoffj-FUG** [comment]
Thinking aloud …
If we use Any County as a landing page and the Volunteer Coordinator moves the volunteer to a County after training then the problem should be resolved. The only syndicate members will be those being trained.
Thoughts please.
Geoff

**Comment by DeniseColbert** [comment]
Plan: All new transcribers enter training syndicate and then VC passes them on to Coord.

**Comment by PatReynolds** [comment]
@DeniseColbert is anything further needed?

**Comment by DeniseColbert** [comment]
I have been gathering training materials and need to work with Geoff to set up the training syndicate next. Still in progress.

**Comment by DeniseColbert** [comment]
Closing
