### ISSUE TITLE
195501885 activate Yorkshire as search names county (Ian)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1179]
Issue reported by **monty6** at 2021-03-12 18:04:45 UTC
Time: 2021-03-12T17:07:50+00:00
Session ID: 0167cd927b78f4e728dcb0b73a436cfd
Problem Page URL: [/freecen2_places/search_names_results?locale=en](/freecen2_places/search_names_results?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/search_names](https://www.freecen.org.uk/freecen2_places/search_names)
Reported Issue:
In encountering a difficulty in transcribing a Place of Birth one may begin to focus on the stated county.  In the case of Yorkshire a problem arises. One may not know which Riding applies and the gazetteer has four options, Yorkshire, Yorkshire East Riding , North and finally West. I also understand there have been some county boundary changes and one might have to add Lancashire. As a finding tool I suggest that the enquiry should not be so specific and search Yorkshire (with no further definition) and also search its adjacent counties. Once the Place has been found one is provided with the greater definition, eg YWR, but that is of little interest since the transcription has to be YKS. I appreciate that using soundex and not specifying a county probably would find the answer but one tries to use the use the firm evidence that is to hand in order to limit the search.    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
The idea is to search all ridings

**Comment by Captainkirkdawson** [comment]
Revised version deployed to test3
