### ISSUE TITLE
Existing Volunteers can log into the system

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#118]

**Comment by PatReynolds** [comment]
Pat/Brenda/Denise need to identify which coordinator is responsible for each volunteer

**Comment by PatReynolds** [comment]
People will be able to correct/choose their Coord alongside correcting/choosing their unique ID (via mailchimp).

**Comment by richpomfret** [comment]
To mock-up a button for user log-in - using the CSS style buttons we currently use (replaces the RSS feed button/icon).

**Comment by richpomfret** [comment]
Vino to let Pat know when it is ready to test.

**Comment by Vino-S** [comment]
As @PatReynolds  suggested, Users will be able to change their Userids.  It will throw error if a user chooses a Userid that is already taken. 
 Currently updated in test2 for testing.

**Comment by richpomfret** [comment]
Shall test in test3.

**Comment by richpomfret** [comment]
For Brenda/Pat & myself (if possible) to test and check.

**Comment by richpomfret** [comment]
Tested and now on production.
