### ISSUE TITLE
195991940 Strange result from replace activity (John)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1184]
Issue reported by **johnt** at 2021-03-18 10:12:20 UTC
Time: 2021-03-18T10:07:30+00:00
Session ID: 2ef7b58fcec93ed590005f8812ee7346
Problem Page URL: [/freecen_csv_files/my_own?locale=en](/freecen_csv_files/my_own?locale=en)
Previous Page URL: [https://www.freecen.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2021-03-18+10%3A06%3A46+UTC&session_id=2ef7b58fcec93ed590005f8812ee7346&user_id=johnt&problem_page_url=%2Ffreecen_csv_files%2Fmy_own%3Flocale%3Den&previous_page_url=https%3A%2F%2Fwww.freecen.org.uk%2Ffreecen_csv_files%2F60506887f493fdd0a670a534%3Flocale%3Den&feedback_type=issue](https://www.freecen.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2021-03-18+10%3A06%3A46+UTC&session_id=2ef7b58fcec93ed590005f8812ee7346&user_id=johnt&problem_page_url=%2Ffreecen_csv_files%2Fmy_own%3Flocale%3Den&previous_page_url=https%3A%2F%2Fwww.freecen.org.uk%2Ffreecen_csv_files%2F60506887f493fdd0a670a534%3Flocale%3Den&feedback_type=issue)
Reported Issue:
I have just at 09:49 done a replace activity for RG12_2545_k. The email sent shows that there are a series of warnings of places not found, the first of which is SFK Criswell in line 9 of the file. However when I select the file it is showing only 1 warning exists and that is for an entry in the notes column. When I select the relevant line 9 it shows Criswell as true    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
Problem caused by poor implementation of No POB Warning.
Reimplemented and deployed
