### ISSUE TITLE
Remove comscoord.freecen@freeukgenealogy.org.uk from "Volunteering Question" emails

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1188]
When Volunteering Question email notifications are sent to the Vol Coord, comscoord.freecen@freeukgenealogy.org.uk should not be CCd.

This is likely a temporary measure to avoid duplication of work and the potential for enquiries being answered by both the Vol Coord and the Comms Coord, until the roles are established.

**Comment by Captainkirkdawson** [comment]
I am afraid this is not easy to do as it is integrated code with FreeREG and we have spent extensive resources to ensure that the coms coordinator is kept in the loop .
Can this not be dealt with through a working agreement between the parties?

**Comment by FreecenBren** [comment]
No problem Kirk.
Not a time consuming issue. OK by me.
Many thanks.

**Comment by DeniseColbert** [comment]
Brenda, this story is because you _don't_ need to answer Volunteering Questions anymore; that is now fully in the role of Volunteer Coordinator (which I'm temporarily doing). Could you leave all of these for me to answer?

OK @Captainkirkdawson, thanks for letting me know.

**Comment by DeniseColbert** [comment]
Closing
