### ISSUE TITLE
Duplicate word in email notification

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1193]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/39a276d4-2b2b-4dfb-b85d-68a90fe0ea2a)

Does this occur in all Contact Us emails?

**Comment by Captainkirkdawson** [comment]
@DeniseColbert It was because the forename and the surname for the userid were the same Cencoms. So it was not really a duplicate.
Have edited the name to be Cen as forename and Coms as Surname
