### ISSUE TITLE
Add 'FreeCEN Gazetteer' to Main menu bar 

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1195]
The Search Place Names menu item currently in Your Actions also needs to be available from the main menu bar after 'Your Actions'.
This is becasue if the Gazetteer needs to be opened when working in other areas of the system the volunteer has to go back to Your Actions and then navigate back to the page they were working on.
This is probably not important to a Transcriber or Proofreader as they only go one or two screens deep. However Validators and Coordinators go deeper in the menu heirarchy. The additional item on the menu bar will make it easier to open the Gazetteer and remove an annoyance.
Geoff

E1 U3 S8 C7: P19

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
But I thought that we recommended that the coordinator/validator and others open the gazetteer at the start of any session and leave it open.
Should we change the name of the action to Gazetteer since that is what people seem to be calling it rather than Search Place Names

**Comment by geoffj-FUG** [comment]
Kirk

That is what we recommend. But sometimes we forget and then have to back out again to My Actions and start again.

Also if we do repetitive Create New Place Names (i.e. do one and then do the next from the information screen) the breadcrumbs lose the plot and end up in the County editing screens. An option to start the Gazetteer from the top menu would solve this.

I think that your idea is a good one and it should be called FreeCEN Gazetteer. That is what it has become and is becoming quite popular amongst transcribers. We do need acknowledgements of Bristish Place Names and Irish Townlands somewhere if we do that.

Geoff

**Comment by DeniseColbert** [comment]
Just spotted this on Test3, and I know it's still in progress (i.e. not in ready for testing/review) but thought I'd make a couple of observations while I was here (may already be on the to-do list, please ignore if so @Captainkirkdawson )

- Could "FreeCEN" be removed, making the link just "Gazetteer"? Issues with the styling of the project name, and it's a bit superfluous)
- The link is only accessible if logged in; perhaps only display the link for those logged in?

**Comment by Captainkirkdawson** [comment]
Revised version on test3

**Comment by geoffj-FUG** [comment]
Looks Good - tested and works OK
Geoff
