### ISSUE TITLE
Upload and process VLD file

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1199]
Initially designed to enable researchers to create vld files, entries and records for code checking purposes

**Comment by Captainkirkdawson** [comment]
Designed primarily for system developers to create test database; may be useful in the long run for uploading all vldfiles

**Comment by Captainkirkdawson** [comment]
The system for VLD uploads is now available on test3. It is restricted to developers at this time.
The documentation is available at
https://drive.google.com/file/d/1wVGoZhpiXG8PbmJB4eskMeQepO8YZcCt/view?usp=sharing

Testing should be done by @AnneV-Learn by installing first on her own server

**Comment by AnneV-Learn** [comment]
Testing successfully completed on my local server.

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn can you please test on test3

**Comment by AnneV-Learn** [comment]
Ok Kirk I’ll not be able to do that until Tuesday now.
Bye for now,
Anne

On 29 Apr 2021, at 15:53, Kirk Dawson ***@***.***> wrote:

﻿

@AnneV-Learn<https://github.com/AnneV-Learn> can you please test on test3

**Comment by AnneV-Learn** [comment]
Tested on test3. 
Successfully uploaded new files, edited files uploaded, deleted and replaced files previously uploaded. 
 Only comments are: unable to replace a file originally uploaded via monthly upload and the order of the VLD file display might be better if it were alphabetic file name.

**Comment by PatReynolds** [comment]
@PatReynolds to consider how to take forwards

**Comment by PatReynolds** [comment]
@PatReynolds to take forwards
