### ISSUE TITLE
New methodology communicated to transcribers and checkers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#120]
Dependent on #117
See Communication Plan https://docs.google.com/document/d/1nRBwcoy-QpCBIHNJc0hxLcCdr0rzyFwVTIHtSrv775Y/edit?usp=sharing

Training - Videos https://docs.google.com/document/d/18BFuneT2bjbqaQGfT3QLUVW-cCE_ZRPD_RcgpTm3CIE/edit?usp=sharing

Basic training plan is to implement training for coords gradually, with sufficient time between each new one-two moving over for them to become familiar enough to help others.  

When a coord is confident, they can train their validators, proofreaders and transcribers.

New transcribers will be brought into the system when new training materials are available : epics 1040, 117 and 825

**Comment by PatReynolds** [comment]
@geoffj-FUG is this now closed or an ongoing processess during cutover?

**Comment by geoffj-FUG** [comment]
Pat
This should not be closed until cutover is complete. I have been mentoring Coordinators where necessary. Those that have been cut over are taking to the testing systems OK. Help with the pARMS is ongoing. One Coordinator was completely lost so I have fixed that County up myself. Most other Coordinators just need help with sprecific questions.  I suspect that there will be a bit of work needed when Coordinators start following the copy / allocation of work processes. Only the Coordinators who were involved in testing are this far down the track. Transcribers and Proofreaders seem to be going OK. There is a lot more to absorb as a Coordinator.
Geoff

**Comment by geoffj-FUG** [comment]
Cutover is now complete and help is in place via the downloadable Handbook. Videos are in place (The additional captioning being managed by Alison is not fundamental to this, but it is an accessibility issue covered by other stories).
Coordinators are trained, as are other volunteers. The Transcribers and Coordinators Boards are working well inn resolving issues and the knowledge displayed by volunteers offering solutions is sound.
I believe that this story can be closed.
Geoff

**Comment by DeniseColbert** [comment]
Closing
