### ISSUE TITLE
Catch and process CSV::MalformedCSVError

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1200]
The CSVProcessor crashed please provide the following information to your coordinator to send to the System Administrators Illegal quoting in line 5094. ["/usr/local/lib/ruby/2.6/csv/parser.rb:879:in `parse_quotable_robust'", "/usr/local/lib/ruby/2.6/csv/parser.rb:818:in `block in parse_quotable_loose'", "/usr/local/lib/ruby/2.6/csv/parser.rb:31:in `block in each_line'", "/usr/local/lib/ruby/2.6/csv/parser.rb:28:in `each_line'", "/usr/local/lib/ruby/2.6/csv/parser.rb:28:in `each_line'", "/usr/local/lib/ruby/2.6/csv/parser.rb:779:in `parse_quotable_loose'", "/usr/local/lib/ruby/2.6/csv/parser.rb:303:in `parse'", "/usr/local/lib/ruby/2.6/csv.rb:1236:in `each'", "/usr/local/lib/ruby/2.6/csv.

**Comment by DeniseColbert** [comment]
@PatReynolds I don't think you meant to assign Anna?

**Comment by AnneV-Learn** [comment]
Code updated to provide a simpler more informative email to the user when MalFormedCSVError is encountered. 
Full code trace is still available in log.
