### ISSUE TITLE
When do we set the piece online status for csv files

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1202]
When do we set the online status for a Freecen2piece?  
For FC1 the piece status was set to online when a validated file was loaded.  There was only a single file for a piece. It is not clear to me if that  necessarily means the total piece in online or just some part. Conventionally I presume online meant complete?
With CSVProc a piece can be loaded in a number of parts or files. It does not need to be a single file. A part or file can be incorporated into the database when it is validated. Hence do we set the online flag when a file is incorporated or only when it is complete? 
CSVProc can do that if we only need to know part of a piece is online. 
If online means that the total piece is online then we likely need to add an action for the coordinator to set that flag when they know that all parts of the piece have been completed

**Comment by geoffj-FUG** [comment]
Kirk
If a piece number is an exact match to the piece number in the PARMS then the piece can be identified as Online.
If however the piece number has a Coordinator applied suffix of _a etc, then the piece should be identified by default as (part) and the Coordinator asked on Incorporation if this is the final part of that piece. If the answer is Yes then the (part) disappears and the piece can be identified as Online.
Geoff

**Comment by FreecenBren** [comment]
That sounds good to me.
Brenda

**Comment by Captainkirkdawson** [comment]
In other words the Online status of a Piece is to be interpreted as Complete. Incorporating a csv file that has a part file name is to set the Freecen2Piece status to Part (or Part Online). The coordinator is to be given some means of changing removing the Part qualification. Should they be asked on every new part incorporation?

**Comment by AnneV-Learn** [comment]
@Captainkirkdawson - Do you agree this is what is needed for CSVProc - Piece Online Status & Date setting at file incorporation?

1. Set online status and date for piece on csv file incorporation where it is not a partial piece i.e. full match on file name. 
2. On csv file incorporation ask question ‘Is this final csv file for this piece?’ if partial piece file name. If ‘yes’  - set piece online status and date. 
3. Clear piece online status and date if 'any' csv file for a piece is 'unincorporated'. 
4. Update online status and date retrospectively for all existing whole piece csv files via rake job. (Use csv file incorporation date?)
5. List existing online csv partial piece files that are currently online as we will need to reach out to coordinators  to ask if ALL csv files have been incorporated for the piece or not and then have a special rake job to handle setting of online status and date retrospectively for specific pieces.  (Use date from 'newest' document Id?)

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn we need to tighten up some aspects. There are currently 2 "piece" collections. 
There is the freecen_piece collection of 17945 entries that is derived from the freecen_parms and used with VLD files. The frrecen_parms is manually created based I believe on a persons reading of the TNA. 
There is the freecen2_piece collection of 66253 entries which is based on an automatic extraction from TNA with manual adjustment made during the initial cutover and used with CSV files.
At some point there will be a need to just one collection but that is for another day and another story.
1. Agreed but noting that it is the Freecen2Piece collection being updated
2. Agreed that for a partial file the coordinator is asked that question. If yes then process 1 is applied. However if no then the the incorporation process sets freecen2_piece status to 'Part'
3. Agreed for single file piece. For a part that is unincorporated then the unincorporation rake sets the freecen2_piece status to 'Part'
4. Agreed we need to have a rake task to review and set as appropriate.Yes incorporation date is appropriate for single file. 
5. Agreed.
@geoffj-FUG to review and flag any concern

**Comment by geoffj-FUG** [comment]
Anne

 

Answers to numbers below:

 

1                     Yes

2                     Yes, if it is a partial piece name (identified by the underscore letter at the end. E.g. _a

3                     Yes

4                     Yes

5                     Can we list files that have parts as (part) until the final piece flag is set? There should not be many partial pieces online so far. They can be identified by the underscore letter at the end so asking the Coordinators should not be a big job. I suspect that there are only a couple of partial pieces online so far. 

Geoff

**Comment by geoffj-FUG** [comment]
Anne

 

I agree with Kirk’s answer to number 3. 

 

Geoff

**Comment by PatReynolds** [comment]
@Captainkirkdawson currently testing.

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn I have tested the incorporation/unincorporation for full and part CSV file and it all works as it should. Well done.
I wonder if we should add a comment about setting the Part status on the yes/no screen; there is the comment about online but not the other.
Only other observation is that in the freecen_csv_controller the new line Line276 should come after the guard clause in line 277 ie only proceed if file linked correctly
Will have a look at the rake tasks on Friday

**Comment by AnneV-Learn** [comment]
Thanks @Captainkirkdawson. I'll look at the 2 points you raise.

**Comment by Captainkirkdawson** [comment]
Deployed to test3

**Comment by PatReynolds** [comment]
Needs testing by loading a partial CSV file and checking result.

@geoffj-FUG or @johnt-freecen could you test this please?

**Comment by Captainkirkdawson** [comment]
Apart from the application code changes there are 3 rake files to be run by Tech Support (not users). 

1. rake set_piece_status_for_whole_piece_csvfiles - sets the piece status to Online for all ‘whole piece’ csv files that have already been incorporated.
2.rake list_partial_piece_csvfiles - lists partial piece files that have already been incorporated. The list could be reviewed  and then co-ords contacted to work out what the piece status should be set to for each partial piece file. 
The csv file that is the ‘last’ for the piece (if that has already been incorporated) should be processed last so that the final setting for the piece is Online.
3. set_piece_status_for_partial_piece_csvfile - sets the piece status for a specified partial piece csv file to the specified status (i.e. Online or Part) - takes 2 arguments - full csv filename and status 
eg. rake “set_piece_status_for_partial_piece_csvfile[RG10_640_a.csv,Online]” —trace

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn reran task 1 with revised code
Set Piece Status: Started.
County: SOM - Piece: RG11_2389 status updated to Online
County: SOM - Piece: RG14_14114 status updated to Online
County: KEN - Piece: RG9_519 status updated to Online
County: SOM - Piece: RG11_2392 status updated to Online
County: KEN - Piece: RG9_468 status updated to Online
County: WRY - Piece: RG10_4663 status updated to Online
County: KEN - Piece: RG9_470 status updated to Online
County: KEN - Piece: RG10_957 status updated to Online
County: WRY - Piece: RG9_3393 status updated to Online
County: BDF - Piece: RG10_1535A status updated to Online
County: SOM - Piece: RG11_2391 status updated to Online
County: KEN - Piece: RG10_923 status updated to Online
County: WRY - Piece: RG10_4664 status updated to Online
County: KEN - Piece: RG10_996 status updated to Online
County: ERY - Piece: RG10_4748 status updated to Online
County: ERY - Piece: RG10_4787 status updated to Online
County: OXF - Piece: RG10_1425 status updated to Online
County: OXF - Piece: RG10_1426 status updated to Online
County: ERY - Piece: RG10_4772 status updated to Online
County: ERY - Piece: RG9_3561 status updated to Online
County: ERY - Piece: RG9_3558 status updated to Online
County: OXF - Piece: RG10_1448 status updated to Online
County: OXF - Piece: RG10_1447 status updated to Online
County: SOM - Piece: RG11_2394 status updated to Online
Set Piece Status: Found 581 Whole Piece CSV files and 109 Partial Piece CSV files
Set Piece Status: Found 24 Incorporated Whole Piece CSV files with blank status
Set Piece Status: 581 csvfile records for whole pieces updated successfully
Set Piece Status: 24 piece records updated successfully
Set Piece Status: Completed in 2.416751665 seconds.

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn @geoffj-FUG Have rerun the partials list. The log is on the gdrive and accessible with your freeukgen email address

https://drive.google.com/file/d/13qULznNqVJjs8ILbLzwc6H8B7Wqh76fU/view?usp=sharing
The only person to have incorporated partials is John Toplis and he has provided the information on completions.
The other people have partials but not incorporated them and some of the partial names are definitely non standard.

**Comment by AnneV-Learn** [comment]
@Captainkirkdawson Just wondering why the listing on the gdrive appears to have duplicates in it??? I didn’t get duplicates when I did my testing locally.

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn they are not duplicates in the sense that they belong to different userids. There may be up to 4 or perhaps even more copies if a file. The transcribers version, the proofreaders version, the validators version and then the Coordinators version. Normally only the coordinator will incorporate. So we are only interested in incorporated files. We likely should report the owners userid for the incorporated file just in case someone else had done it.
Hence I suspect you are seeing these other versions. Likely need to tweak to work only with incorporated files 

See also the new story #1253 on the tweak for the setting rake to enable is to specify both file and its owner so we get the correct file.

**Comment by Captainkirkdawson** [comment]
The latest set of changes have been deployed and are working; complete status has been applied to the Lei files.
This ca  be closed

**Comment by DeniseColbert** [comment]
Closing
