### ISSUE TITLE
Should there be any check between a file being uploaded and /or incorporated to see if it had already been loaded into the database through a vld

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1206]

**Comment by geoffj-FUG** [comment]
Kirk
If we try to Incorporate a file then it should not be able to be Incorporated if a vld is already there. The vld will need to be removed before the new file can be Incorporated.
However the PARMS work has destroyed our ability to do this easily as the Piece numbers no longer match. 
Any alpha character at the end of the new file will need to be removed to do a match. Even then we have a problem in that there may be more than one suffix where a large piece has been broken up. We can therefore remove a file and have more than one piece on the new system.
This appears to me to be dangerous but may only ever occur once or twice. 
Checking at Upload also makes sense as it can save unnecessary work. This is the point that we need to capture the duplication. 
Geoff

**Comment by Captainkirkdawson** [comment]
Will wait until Anne has done the initial rake work on 1228 before proceeding

**Comment by geoffj-FUG** [comment]
We need to be able to load a csv file even if a vld file exists. When we have a data error reported by a researcher and we need to fix it we need to be able to download the vld file as a csv. This capability exists.
At this point the vld needs to be online or we can lose it.
The amended file (now a csv) needs to be uploaded for testing. It then needs to go through a truncated Validation process (it has already been validated in FC1).
It then needs to be Incorporated. 
We are Incorporating a csv file to replace the vld file. There needs to be a test to make sure that we do not end up with 2 files. The vld file should be removed by the Coordinator before the csv file is able to be Incorporated. 
Also remember that we may need several csv files to replace one vld file under the new PARMS structure. So when a vld file is removed we need to remove the complete piece flag and then have it replaced by the Coordinator when the piece is complete.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG check has been added. Running on test3

**Comment by DeniseColbert** [comment]
@geoffj-FUG could you check this please?

**Comment by geoffj-FUG** [comment]
Tested and working OK. The risk of having pieces incorporated as a csv when a vld file exists has been removed and works OK. :)
It looks like we have a workable process now. This can be deployed.
Geoff
