### ISSUE TITLE
Transcriber, checkers and validators can upload and replace their CSV files.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#121]
Envisaged process:
A transcriber receives an assignment from their coordinator and prepares a csv file using spreadsheet software following currently established practices. The transcribers uploads their csv file to CEN2 when ready. They will receive a report from CEN2 somewhat along the lines of that produced by CSVCHECK. The transcriber corrects their csv file on their computer and uploads a replacement file. They again receive a report. This can be repeated until the transcriber is satisfied with the quality of their work and wishes it to go to the next stage. ( Note they could do their transcribing and checking incrementally if they wished rather than waiting until it is all transcribed.)

They inform their coordinator when the csv file is ready for proofreading. The coordinator assigns a proof reader to review the file. The proof reader downloads the csv file file, the last processing report and any other files they need. They following a similar process of off line editing and uploading until they are satisfied. The proof reader informs the Coordinator that the file is ready for validation. The coordinator assigns a validator (Often the Coordinator themselves or one of their
trusted helpers that the Coordinator has trained) who follows the same process as the proofreader of downloading the csv file, the report and any other files they need. The validator inform the coordinator when they are satisfied with the file.

**Comment by Captainkirkdawson** [comment]
The upload capability has been implemented based on minor modifications to the multimodal code.

**Comment by Captainkirkdawson** [comment]
The basic upload/replace capability exists.

The file is processed and an error report produced and sent to the uploader.

**Capability to access your batches(files) added**

![batch.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/528ca9e9-ca9c-4d19-a49e-a13fbda02849)

**Capability list batches and files added**

![batches.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/cc271706-7bae-4c36-8706-c118beecf7f7)

The current upload allows the user to identify traditional field formatting ie maximum length or modern

**They may also select warning or information level reports. Information is more verbose than warning (both include errors). Information reports all changes in civil parish, ED, folio and page**


![upload.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/b671b239-65c4-44cc-aa57-e405c46f785f)

** A file can be replaced**

![replace.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/f1cb14f0-c002-4dbf-ae88-ce7ab133b859)

**This capability will be available for initial testing once the freen_cen_file_processor model is completed in a day or two**

**Comment by Captainkirkdawson** [comment]
Do we adopt the modern format ie there is no limit of field length?

**Comment by PatReynolds** [comment]
Certainly we adopt the modern format ie there is no limit of field length.
For fields where a certain number of characters is expected (eg one letter) then the checking process should flag unexpected results (eg two letters or more). TWYS always trumps this check.

**Comment by Captainkirkdawson** [comment]
Have implemented the modern format by default. ie. we will accept longer fields. This means of course that csv files processed through cen2 will only be loadable into freecen2. The selection on upload has been removed.
The images loaded above are no longer applicable.
Deployed to test2

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
As noted above the initial system for uploading and downloading has been developed. It is now deployed to test3 for evaluation.
An initial document on the process is available at.
https://drive.google.com/file/d/1WpEM-1O4A11l6TtQQ7YzsQZ2XvX2WMod/view?usp=sharing
Please remember this is a workin progress.

**Comment by Captainkirkdawson** [comment]
Ready to restart testing on test3.
