### ISSUE TITLE
198314701 No email alert (Ali)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1210]
Issue reported by **AH001** at 2021-04-14 07:25:01 UTC
Time: 2021-04-14T07:23:12+00:00
Session ID: 5c9ffcfd77ac76f4fb11237bbec4060c
Problem Page URL: [/freecen_csv_files?locale=en](/freecen_csv_files?locale=en)
Previous Page URL: [https://www.freecen.org.uk/manage_counties/select_action?locale=en](https://www.freecen.org.uk/manage_counties/select_action?locale=en)
Reported Issue:
Two uploads to NTH on 13/4/2021 for which I did not receive email alerts.

Previously no problem.    

![Screenshot](https://www.freecen.org.uk)

E0 U4 P9 C6: P19

**Comment by Captainkirkdawson** [comment]
Files in question were
![files.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/5770b52d-d852-41c1-b207-f12a6a71aadd)
Transcriber is member of Any County syndicate.
Emails sent were just to syndicate coordinator
![emails.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/52ec115a-e60e-4776-ae68-4331676bfefb)
A copy should have gone to county coordinator as well
Looks like there may be bug in code

**Comment by Captainkirkdawson** [comment]
Duplicate
