### ISSUE TITLE
Provide report of pieces (records) added to the database for use by Chris Mahoney in reporting progress to volunteers

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1211]
Chris Mahoney wrote:
I have not received notification from anyone about any uploads that have taken place to FreeCEN2.  A reminder that it is up to you co-ordinators to let me know when a piece has been uploaded as I do not have any other way of knowing what has happened at this time

Solution
A FC2 report is needed for management and reporting purposes of all pieces Incorporated into FC2 in say the last 2 months. This should not be filtered by County. It may well be able to be generated from the current FreeCEN report with a date filter. It should include all pieces incorporated by everyone.

It can be quite simple - Chapman Code, Year, Piece number, date incorporated, number of entries as a starting point.

As well as being useful for the newsletter it would be useful for Pat, the Executive etc to monitor progress.

Geoff

Maybe to go in "Site statistics" button? 

E4 U6 S8 C5 (may need to revise once begun)

**Comment by PatReynolds** [comment]
@Captainkirkdawson and @AnneV-Learn to discuss before proceeding.

**Comment by Captainkirkdawson** [comment]
Likely should include both incorporated and vld loaded files with ability to display either or both

**Comment by Captainkirkdawson** [comment]
Best solution is likely a csv download report

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
Just getting to look at this now and I need some clarification on the requirements please. 
The number of VLD and CSV files recently incorporated (ie previous 30 days) are reported for the whole database  on the Site Statistics page ![Screenshot 2022-01-17 at 22.31.48.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/99bc0937-e956-41e9-9722-3b95574e6a6a) and for each County on the County Statistics page ![Screenshot 2022-01-17 at 22.33.36.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/8c1eb8f4-a281-4cf1-8f19-0d782cd7ea71)(both accessed via Your Actions). Also the newly deployed Records pages report on new pieces (ie incorporated in the previous 30 days) ![Screenshot 2022-01-17 at 22.41.28.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/74a18f13-dfd2-42d8-9b24-828f9a84dcdd)and you can drill down through county and place to see the status of pieces.![Screenshot 2022-01-17 at 22.42.15.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/b1a6b8ab-dad6-4808-98c5-0042982e615f) and both have Recent Additions buttons.
Is this an additional requirement for a csv file download perhaps that lists Pieces incorporated across the whole database in the previous xx days (xx range from 0 - 99) or between a date range or something else?

**Comment by geoffj-FUG** [comment]
Chris

 

You compile the newsletter and statistics.

 

What are your specific requirements, please?

 

Geoff

**Comment by geoffj-FUG** [comment]
Chris Mahoney replied:
For any given piece, the newsletters report the following facts about it (refer to newsletter for sample):

County
Year
Piece Number
Place
Locations
Number of Entries

Have asked people what stats they would like me to report on, but beyond the above, have had no particular requests as to what they want to see.

I did discuss with Denise (I think it was Denise, but it could have been Pat) some sort of notification system for whenever a new piece is incorporated, and was told that it was on the list of things to do.  One of my suggestions to her on this was that, when the website emailed a co-ordinator that a piece had been incorporated, others such as myself would be CC'd in on that email.

Have seen Kirk's email on the new look Records Displayed on the website, and responded to it, with three points covered:

*  While I can obtain the requested stats from the website, some email notification system as discussed with Denise still preferred as it will be quicker and easier to obtain the required information than browsing though the website for it
*  Request that we still have the ability for any given county/year to view the overall pieces for that county/year see which pieces have been uploaded, what has yet to be done etc  (do know that general users of the website are interested in this info)
*  Request that a review of how it works out how many pieces there are for any given county/year, and gave him two samples in different counties of where the numbers were incorrect, thus misleading people as to the actual progress of the transcription in that county/year

**Comment by geoffj-FUG** [comment]
Anne
I concur with Chris' comments but would add that the 'previous 30 days' could present a problem in 31 day months or when the stats are reported on on the 2nd or 3rd of the month.
I would like to see an option to select a date range or an option to select either the last 30 days or the last 45 days. That will overcome this issue.
The report images suggest that the report is County by County. With over 70 Counties Chris would need to look at every one of them to compile his report. For other FreeCEN actions a Coordinator has an option to select a County if they Coordinate more than one County. This information is a report and is published to everybody. So could all Coordinators have an option to select either a County or 'All'. This would allow Coordinators to manage their County(ies) and allow Chris and other management level people to view the whole results for the period.
The report formats look good subject to Chris' comments above.
Geoff.

**Comment by geoffj-FUG** [comment]
Chris Mahoney has commented on my last comment:
Viewing a selected date range would an answer to ensure that no uploads on any given day have been missed, but a quicker, and easier way of getting the stats would still be preferable.  

While the "Recent Additions for All Counties" page will let me view all additions for all counties over the past 30 days in one go, there were 122 locations on it when I looked just now, and getting the requested information would require me to go through each of them one at a time.  Although the page will give me the requested stats for a given location when I click on the "View Pieces" action button, what is really needed is a way to get all the stats for a given time-frame in one go instead of going through each place one at a time.

Not sure if Kirk has been filling you in on my response to his email to the list about the new look records section on the website, but he has replied to my email, and I have since responded to it.  To my three points raised to him:

1.  Website stats (refer above), but still cannot recall exactly what it is that Denise had decided about this, Kirk did not know anything about it
2.  Refer to attached scans that he sent me - have agreed with him on his suggestion for this
3.  Where the website lists a piece as being split into separate parts (HO_368 from 1841 the sample we used) some options here are needed as the piece has been completed, and uploaded as one single file, but the website thinks the piece is split into two parts, second of which has not been done, and never will be unless I split the original upload into two, and upload again.  My suggestion to him on this is to leave the pieces split as they are, but give someone the ability to combine them where a piece has actually been uploaded in one single part instead of several smaller ones.

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG This story has become too confused and cluttered with other matters. Others are being written
Have written story `Add display of pieces per year per county#1353` for the work `Ability for Researchers and Members to view Piece Status by County`. This requirement could be met by your suggestion for RECORDS County view to be enhanced to include 'View Pieces' button etc.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG` Recent additions shows totals of all piece for a place#1352` raised in response to comment by coordinator

**Comment by Captainkirkdawson** [comment]
Have narrowed focus of this story to meeting the reporting needs for Chris. The needs of management have already been addressed by the Site Statistics and Search Statistics

**Comment by AnneV-Learn** [comment]
@Captainkirkdawson Just need final clarification as to where this functionality should sit. The first comment states : Maybe to go in "Site statistics" button? (not sure who said that) but I think you would prefer it to be on the Records page. I am slightly more in favour of Site Statistics which is where a CSV File download facility already exists and this is a type of statistic too as it is counts of pieces and records that Chris needs I believe.

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn site statistics is fine; but means we will need to open that up to coordinators

**Comment by Captainkirkdawson** [comment]
Download of report requested by Chris has been added and deployed to test3. Date range is selectable. Available through the Site Statistics Action. Action has been opened up to county coordinators.

**Comment by PatReynolds** [comment]
Believe to be deployed now, so closing
