### ISSUE TITLE
Extend VLD upload to deal with existing files uploaded through the monthly update

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1215]
This will require consideration of where to store the upload. In the users folder or the cen1 folder
E0 S3 S8 C6: P 17

**Comment by PatReynolds** [comment]
@Vino-S to consider where they should be kept.

**Comment by Captainkirkdawson** [comment]
Propose to keep the files in the same locations as the monthly upload files so all VLD files are in the same location
/raid/freecen2/freecen1/pieces/chapman_code.

**Comment by Captainkirkdawson** [comment]
Integrated code written and deployed to test3 for testin by @FreecenBren and possibily @geoffj-FUG and @rhodamackenzie

**Comment by Captainkirkdawson** [comment]
Instruction document written and draft video added to test3
https://drive.google.com/file/d/1wVGoZhpiXG8PbmJB4eskMeQepO8YZcCt/view?usp=sharing
