### ISSUE TITLE
Transcriber can review and correct errors online

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#122]
Correcting errors off-line will not be possible.

**Comment by Captainkirkdawson** [comment]
First version deployed to test2

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
As noted above the initial system online system for editing and viewing files and entries has been developed. It is now deployed to test3 for evaluation.
An initial document on the process is available at.
https://drive.google.com/open?id=1IPIx_VTc0NoEUawjckbPgkGzv4Kw1C6t
Please remember this is a workin progress.

**Comment by Captainkirkdawson** [comment]
There have been no change requests or bug reports. Propose this is ready for deployment

**Comment by geoffj-FUG** [comment]
Kirk

 

Just checking with Chas and Paul but it seems we are OK

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

We all seem to be happy with the View and Edit system.

 

It has been pretty thoroughly tested and it seems to be going well in validation as well.

 

I am happy with it.

 

Another one to tick off as done.

 

Geoff
