### ISSUE TITLE
Add information on FreeCEN1 directing users to FreeCEN2 for current information

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1220]
This arose from a discussion with @FreecenBren and @johnt-freecen - 
 -[ ] replace FreeCEN1 - statistics with a link to FreeCEN2-records
 -[ ] radd note to FreeCEN1 - recent additions explaining that this does not include records added recently directly into FreeCEN2.  
in due course
 -[ ] replace FreeCEN1 - recent additions with a link to FreeCEN2-recent additions

E1 U3 S6 C3: P13

**Comment by Captainkirkdawson** [comment]
Rather than invest time in FC1 I would prefer it to be frozen both software UI and data content

**Comment by PatReynolds** [comment]
Closing as duplicate
