### ISSUE TITLE
Convert VLD to use Freecen2Place rather than Place

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1228]
CSV uses Freecen2Place VLD uses Place; going forward there should only be one place collection. This will simplify searching searching.

E2 U9 S9 C5: P25

**Comment by Captainkirkdawson** [comment]
@PatReynolds agree that this option is better. Will it add significantly to the workload in getting FC1 uploads into FC2?

**Comment by Captainkirkdawson** [comment]
@Captainkirkdawson wrote
I propose that we undertake story Convert VLD to use Freecen2Place rather than Place#1228. and that we apply this after the next monthly update (due this or next week) and that that be the LAST update from FC1.
What to do with work underway by Bev and others? It is either converted to CSVProc or uploaded directly into FC2 as a VLD using the capability in story Upload and process VLD file#1199 that is ready for final test and deployment.

**Comment by Captainkirkdawson** [comment]
@PatReynolds commented
I agree that this option is better. Will it add significantly to the workload in getting FC1 uploads into FC2?

**Comment by Captainkirkdawson** [comment]
No operational work for me. It can be done by the coordinator or Brenda or we could have Rhoda do it. It is just like uploading a cvs file

**Comment by Captainkirkdawson** [comment]
@FreecenBren commented
Sorry to be a pain.
Before it goes to the COORDS, A little history of FC1 uploads.
Also anticipated questions for those who do not see this list.

When I and all the COORDS uploaded them into the FC1 Database they all had
a sign-on for each County they looked after.
They could upload a VLD at any time, but we did have a date each 4 week
cycle to work to as per the schedule we all use now with FreeREG, FreeBMD,
FreeCEN and Maintenance.
The system changed for FC1 because NETWORK PLACES was closed down by the
service operator.
We did not like having to go into a different county each time to upload a
VLD all though each COORD had the same password for all their counties.
I could use them all. But if it has to be so then OK!

Dave Mayall then set up the current system that we use today.
I know the COORDS liked to do it themselves.
At the moment they send them to me before the scheduled update which is
this week, I collate them for Lemon. They have to be done using two
categories.

New VLDs
In each one the VLD’s have to be saved in a another folder by each County.
Example: Notts will be NTT etc. All census years together.
This is to make sure that Lemon knows which County it needs to be added too.

Number amended VLD’s.
This is always an issue.
FC1 does not let you add an amended to the FC1 automatically.
The original one online, has to be removed first, then the amended version
added.
Otherwise, if not, then the newly amended VLD, when added, would fail as
a duplicate. (As previously mentioned to Anne or Rhoda.)

Personally I think the COORDS would prefer to go back to being able to
upload the finished VLD.

So what would they be asking is?
1. Would that be by county!
2. Would it be by PIECE number. (FC1 format)! or (FC2 format with the
underscore)
3. Would it be by Census Year!
4. How would they deal with replacing an amended PIECE and removing the
original.
5. Would the FC1 Stats show it is online as it does now.
6. Would they have instructions how!
7. Will they be able to use the test system to have a go?
8. Any questions I might have missed to add here from the COORDS.
9. I do not have any preference wether COORDS do it themselves, or myself
as now, or a volunteer COORD!
10. Anymore question or suggestions.

Sorry it is long winded but I need to know the answers myself .
Not being in the testing myself!
It is very easy to miss something.

Cheers Brenda

**Comment by Captainkirkdawson** [comment]
Should we decide to proceed with the implementation of this story then the response to @FreecenBren questions are
1 Yes by county
2. It would be by FC1 piece number. There would be NO change to the VLD as currently implemented.
3. Yes see above 1 and 2
4. It would replace the version that is currently uploaded.
5. FC1 stats would not be updated. But FC2 stats would be
6. Yes
7.Yes the capability would be first made available on test3

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn As discussed on the scrum the first step is to at the current status to determine possible issues.
So perhaps a rake task that goes through for each county and for each piece number in freecen_piece and determine district_name, look up its place and determine place_name (should be same as district _name but who knows) and for the same piece number in freecen2_piece determine its piece name and look up the place_name from freecen2_place. We may want to extend that down to the subplaces of the freecen_piece and compare that with the freecen2_civil_parishes for the freecen2_piece and its associated freecen2_place place_name. 
We likely will not worry about Scotland and Ireland results at this time but!!!
You are totally free to take this as a broad thinking spec and adjust as you see fit.

**Comment by DeniseColbert** [comment]
Needs to be in Master to test on production

**Comment by Captainkirkdawson** [comment]
There is  believe a better way of connecting. Since vld belongs to freecenpiece we use the value from there.
Rather than do a direct computation of Freecen2Place to store in freecenpiece we should link the freecenpiece directly to the freecen2piece and that fives full access to all the data model to both freecenpiece and vld

**Comment by Captainkirkdawson** [comment]
Use the set_fc2_piece_for_fc1_v3 rake to create the linkage between freecen_piece and freecen2_piece. This means the the freecen2_place becomes usable for freecen_piece and we then use the freecen2_place from the freecen2_piece.

**Comment by Captainkirkdawson** [comment]
There appear to be code issues

**Comment by Captainkirkdawson** [comment]
Completed and deployed to test3
