### ISSUE TITLE
Transcriber can review and add/change records online

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#123]
This is not the online transcription tool: it enables a missed entry to be added or an existing one changed if a better understanding of the content has been achieved.

**Comment by Captainkirkdawson** [comment]
Will only apply to uploaded files and entries

**Comment by PatReynolds** [comment]
A question: do we want an amended file to be proofread and validated again, and in the interim, is it live, or is the live file not replaced until it has been validated?

**Comment by Captainkirkdawson** [comment]
Records are not "live" until the coordinator has said "Process" or perhaps we should say "Incorporate" or "Activate" the file. ie the system creates search records.

**Comment by Captainkirkdawson** [comment]
Deployed to test2
Note creation is turned off at the moment as I am unsure of the implications of creating a new entry online

**Comment by richpomfret** [comment]
Ready for testing on TEST3.

**Comment by Captainkirkdawson** [comment]
There have been no change requests or bug reports. Propose this is ready for deployment
