### ISSUE TITLE
Link civil parishes to gazetteer

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/FreeCENMigration#1231]
Problem is transcriber types TWYS rather than the PARMS form.  

Please would it be possible to code civil parish name check to use alternate names in gazetteer? answer: not possible.

Coords are getting error messages for parish names even if there is a correct alternative spelling in the gazetteer.

Process for Transcriber for dealing with errors is documented in the handbook.

E2 U7 S9 C6: P24

**Comment by suffolkroots** [comment]
On second thoughts could this impact on rationalisation of parish names across census years, so perhaps not such a good idea?

**Comment by Captainkirkdawson** [comment]
It is good that you ask the question.
Since we use the "standard" parish name in all the displays there should not be any issue. (Says he but will think a bit more)

**Comment by PatReynoldsFUG** [comment]
@PatReynolds to let SuffolkRoots know

**Comment by DeniseColbert** [comment]
We need to show linkages in the gazetteer. @AnneV-Learn to think about how this can be achieved.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG When showing the information for a specific place in the Gazetteer I have renamed 'records online' to 'search records online' (as that is what that is) and added 'Number of pieces'. See screenshot below and this change has been deployed to Test3. 
Is this sufficient information? ![Screenshot 2022-10-19 at 11.01.37.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/e2f7a36c-db26-4e4d-8b69-6b65badd3f7f)

**Comment by geoffj-FUG** [comment]
I have had a look and the renaming the stat as search records is better.
Is it possible to include a "Linked to PARMS record" Yes/No stat as well. It would save a lot of problems knowing what unseen links are there.
Geoff

**Comment by AnneV-Learn** [comment]
Ok @geoffj-FUG I have added "Linked to PARMS record" stat and the change has been deployed to Test3.

**Comment by DeniseColbert** [comment]
@geoffj-FUG to test

**Comment by geoffj-FUG** [comment]
Looks Good. This can be deployed
Geoff

**Comment by geoffj-FUG** [comment]
The original request cannot be done. The Civil parish links and tests to the PARMS, not the Gazetteer. The PARMS entry is then linked to the Gazetteer.

**Comment by DeniseColbert** [comment]
Done so closing
