### ISSUE TITLE
Is search working in Channel Islands?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1235]
No smiths of any age, any year, in any place found on a search of the Channel Islands (FC1 has 'too many' to display).

E3 U4 S9 C6: P22 (for finding cause)

**Comment by PatReynolds** [comment]
Pat to review

**Comment by PatReynolds** [comment]
FreeCEN2 still no search results for Smith, Channel Islands

FreeCEN1 timing out on a search for Smith, Channel Islands, 1861 (works fine for ALcock, NRY, 1861

Error on FreeCEN2: for Records 1861 St Helier: Error message: Validation of FreecenDwelling failed. summary: The following errors were found: Place can't be blank resolution: Try persisting the document with valid data or remove the validations.

**Comment by DeniseColbert** [comment]
@Captainkirkdawson @AnneV-Learn to explore what is going on

**Comment by AnneV-Learn** [comment]
@PatReynolds 

I have just done several searches for SMITH in Channel Islands Census and get results with them all:

![Screenshot 2021-07-17 at 11.17.29.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/1da128f7-a65e-43ab-8cae-7d8746f9db3a)

![Screenshot 2021-07-17 at 11.18.21.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/5bc3eee4-6676-4849-8caf-b4f9f476f6a3)


![Screenshot 2021-07-17 at 11.18.57.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/6bf4491d-a0a5-43ac-bce7-8e4e6c3c261e)
￼
![Screenshot 2021-07-17 at 11.28.20.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/7e647e52-5d49-4038-bc40-c095a647d0bc)


￼
￼

￼
