### ISSUE TITLE
Scotland PARMS

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1236]
As I understnd it the PARMS, as amended by the geographical work, will be used to enhance the search reports for by researchers.
We are now nearing the end of the England and Wales geographic work to establish links between PARMS entries and places in the Gazetteer.
However transcriptions exist for some Scotland Counties and years, though these are not currently being added to. In order for our reporting to work, does a FC2 PARMS need to be created for those Counties and years in FC2?
I doubt whether Scotlands People will allow us to do any downloads from their system so it may well need to be a massaged version of the FC1 Scotland PARMS.
Geoff

**Comment by PatReynolds** [comment]
Already a story (#1060) so closing
