### ISSUE TITLE
1921 Geographical heirachy

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1237]
The 1921 Census will be released in late 2021. We will need to establish geographical heirachy for 1921 before any work can be done on that census year. This may involve another download from TNA.
Geoff

E4 U3 S2 C (for contacting TNA) 8: P 17

**Comment by PatReynolds** [comment]
Pat to check with TNA colleague to see if we can get heirachy from them

**Comment by PatReynolds** [comment]
Asked TNA for contact 7/10/21

**Comment by DeniseColbert** [comment]
Data structure is the same as 1911

**Comment by DeniseColbert** [comment]
Closing
