### ISSUE TITLE
Landing page once new transcribers have signed up (was Transcriber registration process defined)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#124]

**Comment by richpomfret** [comment]
Brenda/Pat to talk through user flow for this.

**Comment by PatReynolds** [comment]
see also 213

**Comment by richpomfret** [comment]
To define role-types (if indeed they differ to FreeREG). See story 222

**Comment by PatReynolds** [comment]
https://www.freereg.org.uk/cms/information-for-transcribers is current for FreeREG - will set up as a google doc for @Brenda and Coords.

**Comment by PatReynolds** [comment]
FreeREG has this information after sign-up, so I think it ok to move ahead without it for the moment, and carry on as normal (i.e. Brenda gets the email, and contacts the person as she does at the moment.

**Comment by richpomfret** [comment]
Consider adding new story for docu update.

**Comment by PatReynolds** [comment]
They need to be taken to a landing page with text - to be supplied by Pat (based on FreeREG, in consultation with Brenda).

**Comment by PatReynolds** [comment]
No landing page in existence on FreeREG that I can find.  Pat drafting ....

**Comment by PatReynolds** [comment]
Resent links 11/10/2017

**Comment by benwbrum** [comment]
I'm trying to track this down in my various email accounts.  @PatReynolds, is https://docs.google.com/drawings/d/1_k3bTuenpBTq-s3WZWXy-giQgVb-1m5_rccruk7Wbic/edit?ts=5938205f the landing page draft you sent me?

**Comment by richpomfret** [comment]
Pat has now sent through the doc to Ben. Ben to review.

**Comment by PatReynolds** [comment]
Resent to Ben for any changes to text needed.

**Comment by benwbrum** [comment]
Reviewed -- no changes needed.

**Comment by PatReynolds** [comment]
@Vino-S please give my profile access to refinery in both tests and production, so I can implement.

**Comment by Vino-S** [comment]
Hi @PatReynolds ,
I had given  access to Refinery in both test2 and test3 for your Userid.
I had also added Profile action to your list of actions in test and live website.

**Comment by PatReynolds** [comment]
TY, Vino.  I have made the landing page on test3. Is the layout correct (I cut and pasted, so should not be typos)? 
We then need to make this where transcribers go once they have pressed the 'register' button on https://freecen2.freecen.org.uk/userid_details/transcriber_registration? . I couldn't find that page on refinery, so couldn't see how/what to change - let me know how to edit it, please.

**Comment by PatReynolds** [comment]
Thanks, @Vino-S  - tests fine.

**Comment by richpomfret** [comment]
Now on Live - to test and ensure it is working fine.
