### ISSUE TITLE
203065863 Breadcrumbs astray when I add a Place to Gazetteer (Geoff)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1241]
Issue reported by **GeoffJ** at 2021-06-08 07:11:03 UTC
Time: 2021-06-08T07:09:22+00:00
Session ID: 23502655bed79ff93fb075660a3800f4
Problem Page URL: [/freecen2_places/60bf17a2f493fda4db8e7a37?locale=en](/freecen2_places/60bf17a2f493fda4db8e7a37?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/new?locale=en](https://www.freecen.org.uk/freecen2_places/new?locale=en)
Reported Issue:
Kirk
If I add a place to the Gazetter the breadcrumbs no longer allow me to go back to the Search screen. They take me into the County. 
Geoff    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I am unable to find an issue.

1. If you go to Create New Freecen2 Place from the Gazetteer the breadcrumbs are for the Gazetteer

2. If you go to Create New Freecen2 Place from the the Freecen2 Places displays from the Manage Freecen2 Places as a coordinator the breadcrumbs are for the Freecen2 Places

3. If you go to the Gazetteer while managing a county and Create New Freecen2 Place from the Gazetteer the breadcrumbs are for the Gazetteer.

I can only suspect that you did the creation through 2 above
