### ISSUE TITLE
204030570 Unable to remove errors when a piece moved to another County (Geoff)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1242]
Issue reported by **GeoffJ** at 2021-06-19 11:09:30 UTC
Time: 2021-06-19T11:00:11+00:00
Session ID: 71e510a6bef50d6ef87d3ca1c1de0349
Problem Page URL: [/freecen_csv_files/60cdcca4f493fd71084e5d9e?locale=en](/freecen_csv_files/60cdcca4f493fd71084e5d9e?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen_csv_files/my_own?locale=en](https://www.freecen.org.uk/freecen_csv_files/my_own?locale=en)
Reported Issue:
Kirk
I had a mis-transcription report from a researcher. So far I have:
Downloaded the original file from FreeCEN as a csv (RG9_1698)
Amended the csv file
Uploaded the csv file.
I have an error report that says that Bitton, Hanham and Siston are not in the list of civil parishes. These 3 civil parishes are in the original parish list in the file info.
These 3 Parishes werre moved to GLS when the PARMS was done.
All three Civil Parishes are in the Gazetteer under GLS.
It appears that I do not need to add the parishes to the piece in the PARMS as they are already there.
I suspect that the County move has caused the problem. Any ideas?
Geoff
    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Seems to me that the system is functioning as it was designed to do. i.e If the civil parishes are in a different county then records for those civil parishes will have to be in a transcription for the other county.
So if you are dealing with a vld file the process you have followed will not work. You need to split into 2 files.

**Comment by geoffj-FUG** [comment]
However, I have no way of knowing at the moment where my pieces have gone and what the numbers are.
If the piece has been transferred to GLS (as it has) I no longer have access to it as Coordinator but it is in a SOM RD so SOM will receive the queries. 
See Story #1208. This story will allow Coordinators to see which County the piece number is in. It just needs a listing by year in numerical order with the County identified for each piece number. Then we can identify the parts of the piece and where they are.
Geoff

**Comment by geoffj-FUG** [comment]
This is related to the new story #1257
Geoff

**Comment by DeniseColbert** [comment]
Closing- create new story if persistant issue
