### ISSUE TITLE
June monthly update failed

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1245]
Need to recovered 27 deleted VLD files
Need to add the planed uploads for June

**Comment by Captainkirkdawson** [comment]
Deleted files replaced
Most (all?) new loads/replacements for June/july done.
@PatReynolds to confirm with @FreecenBren if this is now completed and can be closed

**Comment by PatReynolds** [comment]
Contacted Brenda and passed message on 16  July 2021

**Comment by PatReynolds** [comment]
Sent again 28 July 2021
