### ISSUE TITLE
Freecen2_site_statistics controller crashes

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1246]
Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit. (96) (on localhost:27017, modern retry, attempt 1
Problem code is https://github.com/FreeUKGen/MyopicVicar/blob/master/app/controllers/freecen2_site_statistics_controller.rb#L92-L102 specifically line 93

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn can you look at; crashes the site statistics; on test3; will be even worse in production

**Comment by AnneV-Learn** [comment]
Yes I’ll try to look at this today.
