### ISSUE TITLE
The Freecen2 Place Misterton in Dorset (DOR) does not exist

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1250]
It should be removed however it is being used by either a district/piece or civil parish

**Comment by geoffj-FUG** [comment]
Misterton is in SOM. Mosterton is in DOR
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @rhodamackenzie The issue is deeper than just the Gazetteer. There are actually 3 FreeCen2Pieces in DOR that are said to be named as Misterton. Don't these need to be fixed as well? i.e. moved to SOM. TNA flags them as SOM
HO107_1860A;  RG9_1363; RG10_2023;

**Comment by rhodamackenzie** [comment]
These 2 places are only 2 miles apart though, probably OK to have Misterton in both counties

**Comment by geoffj-FUG** [comment]
I have had a look at Genuki. The boundaries of Misterton and Mosterton are adjacent and the boundary of the Counties of SOM and DOR make up the boundary of the two parishes. 
They are two distinct places in two distinct counties. 
Any entries of Mosterton in SOM civil parishes should be moved to DOR.
Any entries of Misterton in DOR civil parishes should be moved to SOM.
That includes the 3 entries identified by Kirk.
Imagine asking a local the way - if I put a Somerset accent on and say the the name, both parishes come out as Moisterton!
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @rhodamackenzie Finally had time to look at this again. The files that are loaded are VLD files. VLD files cannot be split into the separate civil parishes. The freecen_piece has been assigned to Misterton in Dorset when originally entered in FC1 rather than the regional district of Beaminster which was the normal practice. 
So what I can do is assign it to Beaminster in DOR if you wish. Changing Misterton from DOR to SOM whould mean moving it from one county to the other. Does that give coordinator issues?

**Comment by geoffj-FUG** [comment]
Kirk

 

It should not affect the Coordinator.

 

Beware – Misterton in SOM and Mosterton in DOR are adjacent. They cause endless problems. 

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I understand your comment about those 2 places. But what are we trying to do here? This was your request. vld files belong to a single piece which has to reside in one county. In this case the Regional District of Beaminster in DOR has a piece in 1841, 1861 and 1871 for the sub district Misterton which has 5 parishes , 3 in DOR and 2 in SOM. When originally set up the pieces where given the place name Misterton  in DOR. This has been continued. What is it you want me to do? and for what benefit?

**Comment by geoffj-FUG** [comment]
Kirk

 

I think we should close this story. It is shuffling deck chairs and there will be a lot of them to shuffle.

 

This is a micro story that really belongs in a big one. It is a result of the first instance I came across.

 

Let me stir up the grey matter and come up with a proper story. It will be about improving the Gazetteer.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I agree on closing; Not sure it is a Gazetteer issue at all. It is a census place location issue; to a degree it will be resolved by the nearby place search functionality.
