### ISSUE TITLE
205585993 List of Freecen1 pieces (Geoff)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1254]
Issue reported by **somt.cen** at 2021-07-07 11:13:13 UTC
Time: 2021-07-07T11:08:10+00:00
Session ID: f9a8107528220e2f5d75a9077eb9ae52
Problem Page URL: [/freecen_pieces/SOM/1861/index?locale=en](/freecen_pieces/SOM/1861/index?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen_pieces](https://www.freecen.org.uk/freecen_pieces)
Reported Issue:
Kirk
This screen appears to be quite random in the way that it displays.
Can we either display it in piece number order or provide an option to sort it into piece number order please. 
Coordinators work on piece numbers so an index or sort into that order will suffice.
Thanks
Geoff
    

![Screenshot](https://www.freecen.org.uk)

**Comment by DeniseColbert** [comment]
@Captainkirkdawson to take a look

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG It was not random it was ordered by piece name.
Have changed the order to piece_number.
Deployed to test3
