### ISSUE TITLE
205616971 1861 Essex  (Brenda)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1255]
Issue reported by **Brenhanna** at 2021-07-07 19:49:31 UTC
Time: 2021-07-07T19:44:47+00:00
Session ID: 2f34454d9a40fb6b6d571b853436d3a2
Problem Page URL: [/freecen_pieces/ESS/1861/index?locale=en](/freecen_pieces/ESS/1861/index?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen_pieces](https://www.freecen.org.uk/freecen_pieces)
Reported Issue:
We have No Parms file  for 1861 Essex and the program we used  for creating one from the csv no longer works in a Windows 7 pc, and  never worked in Windows 10. 
 Can FC2 create one or should I ask  Richard light if he can help.     

![Screenshot](https://www.freecen.org.uk)

**Comment by DeniseColbert** [comment]
@PatReynolds  to get more info from Brenda re. VLD files

**Comment by Captainkirkdawson** [comment]
@FreecenBren all of the ESS 1861 pieces are already there in Freecen2Pieces

**Comment by DeniseColbert** [comment]
@PatReynolds to contact Brenda re. no PARMS files/ assistant Coord for FC2

**Comment by PatReynolds** [comment]
Contacted 24/9/2021
