### ISSUE TITLE
Tidy up Replcement of vld with csv.

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1257]
Kirk
I have now processed a file RG9_1698 as a result of a Researcher's Report. This piece spanned 2 Counties, SOM and GLS. I did the work as Coordinator for SOM (somt.cen) .
Issues arose as follows:
The whole piece when uploaded produced errors because some parishes had been transferred from SOM to GLS in the PARMS - this was handled correctly.
**Issue 1 - as stated before the Coordinator of a County has no way of knowing whether part of a piece has been transferred to another County, or whether it even exists. A basic solution has been proposed. This report is critical to Coordinators managing their County.**
I split the piece into 2 pieces RG9_1698 and RG9_1698A. I Uploaded the csv files for both piece numbers. RG9_1698 was OK. RG9_1698A reported a missing parish. TNA have Hanham as a hamlet whilst the enumerator has used it as a Parish. 
**Issue 2 - Because RG9_1698A iis now a GLS piece managed by SOM (The RD is in SOM so SOM has the images) there is no way that the SOM Coordinator can see what is in the GLS PARMS. Again the report mentioned above would resolve this.**
I askedthe Data Manager  to add Hanham to RG9_1698A and replaced the cdv file - All OK
I checked the No POB upload reports and there were no issues in either file.
I then validated both files and used the Accept All Warnings option. The file had previously been validated in FC1 so that was an acceptable option.
I then Incorporated RG9_1698 as SOM Coordinator. I received the Incorporation report OK.
I Incorporated the RG9_1698A as SOM Coordinator and did not receive an Incorporation report because the piece is now GLS in the PARMS.
**Issue 3 - The Coordinator doing the Incorporation should receive a copy of the Incorporation report as well as the County Coordinator of where the piece now resides.**
I then destroyed the old vld file successfully.
**Issue 4 - I have just Incorporated 2 pieces that will appear in the monthly report for FC2. Has Anne allowed for the removal of the original vld file in her stats work?**
I have marked tis as High Priority becasue Coordinators will keep asking for Parishes to be added to PARMS incorrectly if they cannot see the rest of a piece that has been moved to another County.
Geoff

E 0 U6 S8 C 6:P20

**Comment by Captainkirkdawson** [comment]
Issues 1 and 2 were fixed in story 1208
Issue 3 has been fixed and deployed to test3
Issue 4. The vld file should have been deleted not the piece. The stats would have been OK

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG The copy of **We have processed the request to include RG14_14172.csv of Captkirk into the database** went to both you and myself confirming the fix for 3 works

**Comment by DeniseColbert** [comment]
Awaiting @geoffj-FUG to let us know if this is OK

**Comment by geoffj-FUG** [comment]
Kirk
Advice received OK so it works OK.
Geoff
