### ISSUE TITLE
Track who made edits and why to the Gazetteer

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1259]
E2 U6 S9 C6: P23

**Comment by PatReynolds** [comment]
Data Manager to make _changes_ to existing entries.  Anyone can add a place (e.g. place of birth) or an alternate place name.  

@DeniseColbert to create google forms so that the Data Manager has all the information they need to make changes.

If workload is too much for Data Manager, we should recruite deputies with the ability to make _changes_

**Comment by rhodamackenzie** [comment]
Fields for google form for Gazetteer changes:
Required:
1) Place name
2) County 
3) Either a Grid Reference OR the latitude and longitude
4) Information source

Optional:
1) Other name for place
2) Other name for place
3) Other name for place

**Comment by rhodamackenzie** [comment]
Fields for google form for Civil parish changes:
Required:

1) County
2) District
3) Piece number 
4) Civil Parish
5) Freecen2 place name for linkage (to be checked/requested to be added to gazetteer by requestor before filling in this form) 

choice for civil parish action requested - add, change or delete (Denise - please see if its easier to do 3 different forms for these 3 options

Optional if adding or changing parish:
Hamlet(s)
Notes to add

**Comment by Captainkirkdawson** [comment]
A new version of the tracking system for gazetteer entries has been written. Edits made are entered into an embedded collection for the FreeCEN2 Place. A rake task has been written to convert the existing changes into a single edit.
The system has been deployed to test3 for evaluation.

The reason box is a mandatory field currently freeform. However it might be better to do it as a selection from a small list. Comments would be appreciated.

**Comment by Captainkirkdawson** [comment]
New version committed to test3 that uses defined reasons and has the ability to add reasons.

**Comment by rhodamackenzie** [comment]
I have just changed a placename on test3 and the list of reasons are sensible except that often more than one change is made at the same visit - could multiple reasons be highlighted using CTRL? Also, not seeing any tracking info after i made the change and went back in, but that is perhaps not in place on test3

**Comment by Captainkirkdawson** [comment]
Tracking info is available at a new field in the Freecen2 Place display (show)
![edits](https://user-images.githubusercontent.com/2874694/129461086-f36bf340-c061-4a52-a6bd-e26f5d5f8998.png)

**Comment by Captainkirkdawson** [comment]
Interesting comment on multiple selections will look at adding

**Comment by Captainkirkdawson** [comment]
Your wish for multiple reasons is my command. Look at test3 again

**Comment by rhodamackenzie** [comment]
great thanks - may be worth adding to the sentence "Multiple reasons may be selected using the CTRL key"
