### ISSUE TITLE
Online help and transcriber process documentation for new systems available

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#126]
Basic information urgently needed.

 -[ ] Help page for transcribers (https://www.freecen.org.uk/cms/information-for-transcribers) probably needs revision in light of progress in recent months - draft started on test 3
 -[ ] link from Help page for transcribers to  model spreadsheet and blank spreadsheet (?)
 -[ ] Handbook (current version online as pdf, being continually revised by @geoffj-FUG and copyediing in progress by @AlOneill 8/12/2020

E0 U6 S9 C6: P21

**Comment by PatReynolds** [comment]
@Vino-S could you provide me of a screenshot of what transcribers see when they log on?

**Comment by PatReynolds** [comment]
Comment for draft.
https://docs.google.com/document/d/1SLLodOLQK8JfFherLUp86G6Xjmo27fhUMx4_xVSAJDE/edit?usp=sharing

**Comment by PatReynolds** [comment]
Sorry - that should be 'draft for comment' - @FreecenBren @AlOneill Rena and Geoff (emailed 14/3)

**Comment by richpomfret** [comment]
Moving this back into Sprint Backlog as it remains urgently needed - if a user logins into the site and clicks on 'help' they are taken to a page with nothing on it other than 'placeholder'. We need even a simple or basic bit of text here or set of links to assist transcribers. @PatReynolds or @AlOneill any idea if we have anything for this?

**Comment by Captainkirkdawson** [comment]
See the New action FreeCEN Handbook authored by @geoffj-FUG 
![handbook.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/585d265a-b7d3-4e91-9a70-c13bbd85fcb2)
Takes you to a link
![handbooka.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/ba4f0c64-cecf-44ba-8fde-3e8f9d634296)
Document on the new processes in there

**Comment by geoffj-FUG** [comment]
At present I am releasing a new version at the beginning of each month. Version 1.1 is Online in test3. I am doing edits to Version 1.2 and this will be released in early October.
Geoff

**Comment by PatReynolds** [comment]
Thanks, Geoff.
Currently, when a member logs in, the 'help' button on the header links not to help for users, but to https://test3.freecen.org.uk/cms/information-for-coordinators - which I think (please correct me!) is now replaced by the Handbook.
So ... this story needs to change to be: what do we do with that button and https://test3.freecen.org.uk/cms/information-for-coordinators?
Is there anything that is, or should be on https://test3.freecen.org.uk/cms/information-for-coordinators which isn't in the handbook?
Is there anything on https://test3.freecen.org.uk/cms/information-for-coordinators that could or should be in the handbook?
If there is no need for the link https://test3.freecen.org.uk/cms/information-for-coordinators, does everyone just get shown the help for users (https://test3.freecen.org.uk/cms/help)? Or is the button removed entirely once someone logs in?

**Comment by FreecenBren** [comment]
Hi,
I have clicked on everything and also in test3 and cannot see the handbook
link anywhere.
Kirks   link goes to the Handbook name but does not open.
Can someone send me a link direct please so I can check it out?
Sorry to be a pain

Brenda

**Comment by FreecenBren** [comment]
Please forget that. Eventually it opened ok in test3.

Cheers. Brenda

**Comment by AlOneill** [comment]
@geoffj-FUG @PatReynolds 
I've browsed the Handbook and have a number of initial concerns:
* How will volunteers know when a new version of the Handbook is available? The temptation is to download the document and work from that. A volunteer will need to know that their copy is out-of-date

* The Handbook is not navigable. At 69 pages, we need to provide hyperlinks from the contents page, or an outline view or something similar to help people find the information they need

* Much of the text is written in the passive voice which is significantly harder to understand than the active voice (see the current [Spreadsheet fields](https://freecen.org.uk/cms/information-for-transcribers/the-spreadsheet-fields) for examples of how we have improved the language we use — it isn't perfect, but it is better than the original.)

* Microsoft Access Runtime is Windows-only: what about Coords who are not on Windows?

**Comment by geoffj-FUG** [comment]
Alison

 

They can be told on the message boards and in the Newsletter. Coordinators can reinforce the message if they wish. Once the system is bedded down releases should be few and far between. 2021 then 2039 presumably. In the interim message boards and newsletters will have to be the way to go.

It may be possible to add a message to the ‘Your Files’ page once we are established.

 

The links are in the original. I have just converted it again  and they all work. I am not sure where they went. I will test the next version before I release it.

 

Sorry Alison, but that is my writing style. I have written lots of study guides in the past including ones for International students studying at what you would call a Polytechnic that provide exemptions at Universities (and had to meet up to three Institutions needs). I still have to do some images for the first few pages which will improve the presentation. I seem to be doing a lot of writing at the moment.

 

Geoff

**Comment by geoffj-FUG** [comment]
Alison 
The Utility was written just to make the life of testers easier. It was taking about 1 1/2 hours to manually convert a single file. 
It then became obvious that the utility, sespite its shortcomings, was useful to Coordinators. If a Coordinator is using a Mac then they can delegate conversion to one of their volunteers. My statement that it would only be made available to Coordinators was to prevent misuse if it was freely available. I will need to provide support and I am not willing to do that for the world at large. So I have limited its availability. 
Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG Thank you. You've answered most of my points. However, I am still concerned about the writing style of the Handbook.

We cannot assume that our current (and future) volunteers are all comfortable with information presented in the passive voice — they are not Polytechnic/University students! Some will have stayed in education post-16, but many won't. As a secondary school teacher, I have experience of the range of reading levels achieved by those who don't progress to tertiary education. I'm not aware of any correlation between reading level and ability as a transcriber.

Are there plans for anyone to edit the Handbook, in respect of voice, apart from yourself? Would @rhodamackenzie be a suitable sub-editor?

**Comment by AlOneill** [comment]
@geoffj-FUG wrote:

Alison
 
I have now incorporated your Guiding Principles of Transcribing into the Handbook. I have also created an Appendix on Shipping Returns using your spreadsheet fields information.
 
I have made some minor amendments to bring them in line with the new system (e.g. removed field length info). Most of the Handbook inclusion is a copy and paste from your web page.
 
These will be in the next version of the Handbook at the beginning of October.

**Comment by rhodamackenzie** [comment]
I can look at writing style throughout the handbook once geoff is ready though I am used to writing in the passive voice and fear I am the culprit!

**Comment by geoffj-FUG** [comment]
Alison

 

Rhoda has already been asked to proofread up to page 33.

 

I am awaiting her feedback.

 

She has also already proofread some of the parts written by Kirk. The updated versions will be included in the next version of the Handbook.

 

Please realise that this was written on the fly. It is a collection of information that has just been reformatted into a Handbook. It is still a fluid document but will get there in the end.

 

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG @rhodamackenzie Thank you both. I understand completely. My first drafts are always littered with the passive voice and unnecessarily technical terms (or niche, British idioms)  — them's the skills that higher education teaches us!  However, we all know that if the mature version of the Handbook is not accessible, in terms of language, our transcribers and their coords will be up in arms and other Bad Things could happen. That's the crux of it.

Keep up the good work!

**Comment by geoffj-FUG** [comment]
The Handbook Downloads OK.
I have now also produced a Quickstart Guide to Transcribing the England and Wales Census. It prints back to back on 4 x A4 pieces of paper. 
It emphasises the links to the Handbook but is less daunting than the Handbook.
I will ask Kirk to include it behind the FreeCEN Handbook button when I release the next version of the Hnadbook.
I suggest we leave this  one open until the Quickstart Guide is available.
Geoff

**Comment by geoffj-FUG** [comment]
Please see my comments on #354
Geoff

**Comment by geoffj-FUG** [comment]
Version 1.2 of the FreeCEN Handbook is now available for download from test3. It still needs some revision in places but seems to be getting there. If you notice that something is missing please let me know. It has been proofread to page 35 only. It does not include all of the Managing County or Managing Syndicate functions.

There are also 2 other documents available from the same Handbook Page.
Ready Reference which is essentially a replacement for Fields.htm but does not replace the Handbook for some functions. I have tried to keep it as short as possible.
Quick Start Guide which is a short desktop reference for experienced transcribers.

We have taken onboard feedback over the original download page and there are now deatiled instructions on Downloading or Printing each document.

Geoff

**Comment by richpomfret** [comment]
@AlOneill can you take a look at the latest draft and assess the changes/passive voice?

**Comment by AlOneill** [comment]
@richpomfret @geoffj-FUG The **page** [FreeCEN Handbook](https://test3.freecen.org.uk/cms/freecen-handbook) on t3 is _not_ a draft (for obvious reasons, I guess) but it is **not** sync-ready as there is no layout and no proper headings (and maybe other problems — I have not read it properly, yet).

I'll get the page into shape first, and then have a look at the actual Handbook, if that is what you mean?

**Comment by geoffj-FUG** [comment]
Alison

 

You are correct. The document on t3 is a pdf.

 

It is not a final draft. It is being written on the fly as things are tested and a process becomes clear.

To do otherwise would mean that we would miss things if we try to document the whole system when it is ready.

 

I have attached a document for you. It is an Abbreviated Handbook and is being looked at be a tester at the moment to make sure everything is covered.

This abbreviated handbook is now quite stable as it is for Transcribers and  Proofreaders and we have moved on in testing from the content. 

It is a subset of the Full Handbook. I was expanding the Ready Reference and got feedback on the format and we realised that we had almost achieved an Abbreviated Handbook. So that suddenly made sense.

 

I have attached the word version as it should be easier for you to use. The styles used are Headings 1 to 3 plus Normal and Notes plus TOC. All links should be in place.

 

Does this help?

 

Geoff

**Comment by AlOneill** [comment]
I've fixed the basic HTML markup of the Refinery page, [FreeCEN Handbook](https://test3.freecen.org.uk/cms/freecen-handbook) on t3 (i.e. _not_ the Handbook itself or the Ready Reference or the Quick-start Guide, but the HTML page that is opened by the "FreeCEN Handbook" Action).

Next, I'll create a DRAFT version of the Refinery page that addresses other issues that I've spotted.

(I'll reply to @geoffj-FUG offline about reviewing the PDF documents — attachments do not survive.)

**Comment by AlOneill** [comment]
The DRAFT version of the edited Refinery page, [FreeCEN Handbook](https://test3.freecen.org.uk/cms/draft-freecen-handbook) is ready for review.

The changes made are:
* replace passive voice with active 
* acknowledge browser differences and non-Windows users
* polish text for consistency and readability

Have I missed or distorted anything?

**Comment by geoffj-FUG** [comment]
Alison

 

The Ready Reference has been replaced by the Abbreviated Handbook for England and Wales Transcribers and Proofreaders.

 

I have canned the Quickstart guide because the differences in the systems are significant and people will use it to take shortcuts.

 

The instructions for the Abbreviated Handbook are currently:

 

Abbreviated FreeCEN2 Handbook for England and Wales Transcribers and Proofreaders 

The Abbreviated Handbook is an easy to use computer based or desktop reference. It is suitable for Transcribers, new Transcribers and Proofreaders working on England and Wales (including Isle of Man and the Channel Islands). It can be printed on A4 paper, either one sided or back to back.

*         Select Download the Abbreviated Handbook

The Abbreviated Handbook will appear on your Screen in Acrobat Reader

*         Select the Download Icon (An underlined downward arrow)

*         You will be asked where you want to Save the Abbreviated Handbook. Save it.

*         Open the Abbreviated Handbook in Acrobat Reader

*         Select the Print Icon (or File … Print)

*         Select your Printer

*         Set Pages to Print to All

*         If you want to Print on both sides of the paper, tick the Print on both sides of the paper box

*         Set the Orientation to Portrait

*         Select Print

The Abbreviated Handbook will now print. It contains about 60 pages (or 30 if printed back to back).

The Abbreviated Handbook may be updated from time to time. You will be advised when a new version of the Abbreviated Handbook becomes available.

 

Can you standardise these instructions for Refinery as you did for the Handbook, please?

 

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG Have uploaded the Abbreviated Handbook file and updated the (not-draft) Refinery page on t3, [FreeCEN Handbook](https://test3.freecen.org.uk/cms/freecen-handbook).

However, the file does not open directly in Firefox (which the full Handbook does), so guess there is some bit of 'magic' missing? Or, I'm beginning to suspect that I've misunderstood crucial?

Will update the DRAFT page tomorrow.

**Comment by AlOneill** [comment]
Mea culpa! Brain malfunction, big style, with realisation dawning too late last night. All now as expected on "FreeCEN Handbook" page.

**Comment by AlOneill** [comment]
@geoffj-FUG The [DRAFT FreeCEN Handbook](https://test3.freecen.org.uk/cms/draft-freecen-handbook) has been updated with the details for the (new) Abbreviated Handbook. Have also tweaked some other parts of the page.

Is the DRAFT page OK to be promoted to the actual page? Does anything need changing or adding?

**Comment by geoffj-FUG** [comment]
Alison

 

The order in the menus have been amended to make them more logical.

 

I have quite a few images to replace.

 

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG I think we are at cross-purposes: I'm talking about the DRAFT Refinery page which has links to each version of the Handbook. I'm asking if you are happy with my re-write of the accompanying text which explains how to download (and print) each Handbook.

My re-write is on t3 at:
https://test3.freecen.org.uk/cms/draft-freecen-handbook

**Comment by geoffj-FUG** [comment]
Alison

 

Yes that is fine.

 

I will align the Handbook so that they are the same.

 

Geoff

**Comment by PatReynolds** [comment]
I believe this  can now be closed.  I will copy the comments relevant to the NEW systems to the appropriate story (#126)

**Comment by PatReynolds** [comment]
Information copied from #354 which is for FreeCEN1 systems, not the new systems:
Version 1.2 of the FreeCEN Handbook is now available for download from test3. It still needs some revision in places but seems to be getting there. If you notice that something is missing please let me know. It has been proofread to page 35 only. It does not include all of the Managing County or Managing Syndicate functions.

There are also 2 other documents available from the same Handbook Page.
Ready Reference which is essentially a replacement for Fields.htm but does not replace the Handbook for some functions. I have tried to keep it as short as possible.
Quick Start Guide which is a short desktop reference for experienced transcribers.

We have taken onboard feedback over the original download page and there are now deatiled instructions on Downloading or Printing each document.

Geoff

**Comment by AlOneill** [comment]
I have now received a .docx copy of the Abbreviated Handbook v1.3 that has been revised using many of my suggestions for pages 6 and 7.

Now that I know which of my suggestions are likely to be accepted and which are not, I will continue to review the Abbreviated Handbook with regard to the use of passive voice and similar language issues.

**Comment by geoffj-FUG** [comment]
Alison
What is your timeline please? Just so I know to update the test version.
I will also need to have the final version ready by the end of November.
Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG I am working as fast as I can (which is nothing like as fast as I could do in the past). I may or may not be finished before the end of November. Sorry, but that's how it is.

**Comment by geoffj-FUG** [comment]
Alison

 

Given your timeline and the fact that we have a proposed Deployment on 1 December I will proceed with my version of the Handbooks.

 

I am still editing the full Handbook so needed the Abbreviated one with any proposed changes pretty soon to get it all done.

 

The version I sent you will be the version that we will deploy.

 

Geoff

**Comment by geoffj-FUG** [comment]
Alison
Given your timeline and the fact that we have a proposed Deployment on 1 December I will proceed with my version of the Handbooks.
I am still editing the full Handbook so needed the Abbreviated one with any proposed changes pretty soon to get it all done.
The version I sent you will be the version that we will deploy.
Geoff

**Comment by geoffj-FUG** [comment]
The Full Handbook will be ready by the time we deploy. I only have a couple of minor processes to write up and a few pages still to tidy up.
Geoff

**Comment by AlOneill** [comment]
@PatReynolds @geoffj-FUG

I don't know what to say. I will feel that I've let people down if the unedited Handbooks are what is presented to our volunteers when the new system is deployed.

Is there something special about Dec 1st, something that means that everything has to be ready by then?

**Comment by Captainkirkdawson** [comment]
Next opportunity is 8 weeks later on January 26. Implementation is county by county not all at once.

**Comment by PatReynolds** [comment]
Is the commencement of training linked to deployment? Is it envisaged as a mass start (I had thought it was going to start with a few and move on in batches.  The importance of a 'finished' handbook is dependent on these.

**Comment by Captainkirkdawson** [comment]
@PatReynolds as noted above implementation is phased. The initial phase involves setting the system up in production; that cannot start until after deployment and the system is active. Once set up in production the plan is to proceed with implementation county by county; starting with SOM then RUT and LEI and after that who knows. Those 3 counties have people who have been using the documentation as it has been developed. This likely should all be discussed at the next CEN scrum

**Comment by geoffj-FUG** [comment]
The latest versions of the FreeCEN Handbooks have been loaded onto test3.
The abbreviated Handbook for England and Wales Transcribers and Proofreaders is shovel ready. There may be minor changes before 1 December but nothing significant.
The Full Handbook for Validators, Coordinators and the Data Manager still requires my last proof read. I am about half way through at the moment. If you notice any procedures that I have not covered, now is the time to let me know. (I think that I have included all the procedures that need to be there on 1 December. My final proof read is just a presentation tidy up).
Geoff

**Comment by AlOneill** [comment]
I'm planning on finishing my opening set of suggestions for making the text of the Abbreviated Handbook more user-friendly either this week or next.

It will not be completely finished, but I need a break. I will, however, have looked through the whole document.

**Comment by PatReynolds** [comment]
Thanks, @AlOneill I'm reviewing the other actions (all mine, I think) that have got lost and will make them as tickyboxes in the story itself.

**Comment by PatReynolds** [comment]
Draft Information for Transcribers ready for content check on test3

@geoffj-FUG any further changes needed?  
We envisioned the following sub-pages, are they still needed?
![image](https://user-images.githubusercontent.com/6338822/101476819-38e5a480-3946-11eb-8a46-c132a2ba2058.png)

**Comment by AlOneill** [comment]
Latest round of suggested edits to Abbreviated Handbook sent today to @geoffj-FUG for consideration.

**Comment by geoffj-FUG** [comment]
Alison

 

I will get to it in the New Year. I have put it in my To Do list.

 

Geoff

**Comment by PatReynolds** [comment]
Hi @geoffj-FUG how are you getting on with this? any help needed?

**Comment by geoffj-FUG** [comment]
Pat
Its still on my to do list. Cutover is taking more time than originally envisioned. I have been updating images to align with the new screens. 
I will evetuallly get to it but have more than enough on my plate at the moment.
Geoff

**Comment by DeniseColbert** [comment]
Complete: closing
