### ISSUE TITLE
VLD deletion process does not function correctly

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1260]
VLD deletion is supposed to remove the file from the piece, the entries, search records, individuals and dwelling associated with the file and then the file itself from the raid storage in  /raid/freecen2/freecen1/pieces
Code is currently https://github.com/FreeUKGen/MyopicVicar/blob/master/app/controllers/freecen1_vld_files_controller.rb#L68-L86

**Comment by Captainkirkdawson** [comment]
Had a quick look and there is no attic folder in SOM and the vld file is still present in /raid/freecen2/freecen1/pieces/SOM

**Comment by AnneV-Learn** [comment]
I tested the VLD file delete on my server and it did delete it fully - although didn't appear to create attic folder (or should the attic folder already exist?), so no attic file present. Could this be a permissions issue?

I did notice that the Piece doesn't exist (SOM - 1951 - 1943) for the file that Geoff had tried to delete (HO511943.VLD) - should it still be present?

**Comment by suffolkroots** [comment]
Yesterday I deleted OXF vld RG12_1165 before incorporating replacement in CEN2. The vld has gone from the list, but I have no knowledge of residual contents elsewhere.

**Comment by AnneV-Learn** [comment]
Looked this morning and again the VLD file must still be hanging around as it is in the list

**Comment by AnneV-Learn** [comment]
![D37CA184-0ED5-45F1-94DB-F33B0A855215](https://user-images.githubusercontent.com/72746727/125591550-f1091e73-f08a-4f64-a278-67ab301b2241.jpeg)

**Comment by suffolkroots** [comment]
It's in the list "Manage vld files", but not available (button inactive).

It's not in the list of "Manage FreeCEN1 pieces" (from where it was deleted)

**Comment by suffolkroots** [comment]
Strange that there is no delete option in "Manage vld files"

**Comment by AnneV-Learn** [comment]
I believe that relies on your access level. @Captainkirkdawson ?

**Comment by AnneV-Learn** [comment]
I have pushed a modification to you for review @Captainkirkdawson  - there was a problem with the path to the attic directory. Tested on my local server and attic directory and attic file now created successfully.
However there might be a problem with the way users are removing VLD files - seems they are doing by deleting the Piece and don't have access to the Delete option in the VLD Index view.

**Comment by suffolkroots** [comment]
Apologies---vld delete option seems to be accessible through button, not through Show, or Edit. Perhaps need consistency of approach across all actions.

**Comment by Captainkirkdawson** [comment]
After much head scratching @AnneV-Learn and I have concluded that @geoffj-FUG and Ali are equating a vld file to a Freecen1 Parm  and rather than deleting the vld file through the Manage vld files action they are deleting the specific Parm though the Manage Parms action. The latter action does NOT delete the associated vld file. 
It is only the Manage Vld Files action that deletes the file, its entries, its search records, its individuals and dwellings.
Actions required add a restriction on the deletion so if there are dependants the Parm cannot be deleted. 
Restrict parm deletion to to system administrator and Data manager.
Locate vld files that need to be deleted by identifying those vld files are connected to a freecen_piece that no longer exists

**Comment by suffolkroots** [comment]
In my defence @Captainkirkdawson I went to Actions in VLD list, didn't find delete, so went to Manage FreeCEN1 Pieces where I found delete.
We need consistency of approach across all actions.

**Comment by Captainkirkdawson** [comment]
Ali No defense is needed. Those actions have grown from a simple capability for me to see what was what into actively used actions by people with little overall planning , instructions and video's. We will put that right.

**Comment by AnneV-Learn** [comment]
Deleted HO511943.VLD (Geoff's file mentioned above)  - this resolved Data Integrity check no. 2 issue for SOM 1851.
Updated FreeCen code so that a FC1 Piece cannot be deleted if there is an  associated VLD file or dwellings and modified roles permitted to delete/destroy Pieces and VLDs.
There are now as follows:
Destroy Piece:
system_administrator data_manager
Delete VLD:
system_administrator data_manager county_coordinator master_county_coordinator 
Code pushed to Kirk for review who pulled into Master and  deployed to Test3.

**Comment by DeniseColbert** [comment]
Deployment needs to be done and then follow up work (story #1269)

**Comment by geoffj-FUG** [comment]
Story #1269 has no information.
I think this story is completed?
I seem to be going OK on the live system.
Geoff
