### ISSUE TITLE
Improve search form (place of birth searching text)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1262]
There are over 20 stories which relate to searching by place.  Immediately before implementation, I think it would be good to conduct some UX research and comparisons with other genealogical search engines before reviewing the stories we have.  
 - [x] Write replacement text
 - [ ] Take down feedback form

**Comment by Captainkirkdawson** [comment]
This needs to be 2 stories as they are very different requirements with very different implementations

**Comment by PatReynolds** [comment]
Draft text for comments: https://docs.google.com/document/d/1mozGpzFbhY2dYzlMj5U2dEG9yXV8bHfjSMbFwgOs01E/edit?usp=sharing

**Comment by Captainkirkdawson** [comment]
Some edits made

**Comment by PatReynolds** [comment]
I have changed the title of this story (was "Conduct UX research on place of birth and place of census searching" as that is to be done later (v4) and the replacement of the survey needs to be done as soon as convenient.

**Comment by PatReynolds** [comment]
Closing as completed (some time ago).
