### ISSUE TITLE
Places in County not displaying corretly

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1266]
Richard L noted " I selected Dorset, but the list of places didn't then fill as expected. After giving me an error message about an incomplete search, it then did provide a list of places in Dorset.  However, when I selected Iwerne Minster (and 1841) for my search, it again complained about the lack of a place in the search, and my selection was no longer highlighted.

This seems to be an issue with some counties and not with others: if I select Essex I get a list of places (in Essex); if I then select Dorset this list doesn't change"

Checked this and found that some counties (e.g. Beds and Cambs) are displaying their places as expected.  Others (e.g. Bucks and Berks) do not.  If you chose somewhere that is displaying correctly, and then one that is not, the places remain as for the previously selected county.  If you then choose a county which is displaying correctly, the places change to being those expected for that county.

I will put up a message of the day to note this.

**Comment by Captainkirkdawson** [comment]
@PatReynolds This can be fixed by a system administrator running the Refresh Place Cache utility

https://docs.google.com/document/d/1RPUADzvJVqDkxp7VK6JWhbnS3N3WxEumdPZNNDI3yxo/edit#

I have done that. Message may be removed

**Comment by PatReynolds** [comment]
Thanks, Kirk.  I have removed the message.
