### ISSUE TITLE
Census places not showing for some counties

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1267]
For some counties, places do not show when the county is chosen.  If you had previously selected a different county, the places of that different county remain.  If 'search is pressed when either no places or the wrong places are shown, the whole county is searched. 

There is a work-around: if you search the whole county and  then use the 'revise search' button, the correct places for the county appear, and users can then select the one they wanted in the first place.

I have placed a message on the search page, but if @DeniseColbert or @AlOneill could take a look and correct/improve, I'd be grateful.

**Comment by AlOneill** [comment]
Did some minor tidying: "do not" for "don't" and some curly quotes.

**Comment by PatReynolds** [comment]
Thanks, Alison!

**Comment by PatReynolds** [comment]
Caused by needing to rebuild the place cache - now done, so closing.
