### ISSUE TITLE
Front end processor of transcriptions

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#127]
This processor must do all the checking currently done by CSVCHECK, WINCC and DALDREV.
It must produce an error report and store the records for review and correction.
It must compute and add any additional fields derived by WINCC and VALDREV eg sequence in household. Dwelling number and age unit. There may be others

**Comment by Captainkirkdawson** [comment]
A first version that processes a file and identifies, information, warnings and errors has been written

**Warning level example**

Started on the file RG094177.csv for Captkirk at 2020-03-19 16:40:35 -0600. <p>
Working on Cardigan for 1861, in CGN
Warning: line 4 New Civil Parish St Dogmaels.<br>
Warning: line 11 House address cwm garwd?  has trailing ?. Removed and flag set.<br>
Warning: line 13 Surname  morris? has trailing ?. Removed and flag set.<br>
Warning: line 14 Forenames  margret? has trailing ?. Removed and flag set.<br>
Warning: line 15 Occupation labourer son? has trailing ?. Removed and flag set.<br>
ERROR: line 18 Marital status n is invalid value.<br>
Warning: line 26 Schedule number 0 is less than the previous one .<br>
Warning: line 34 Schedule number 8 increments more than 1 .<br>
Warning: line 74 Occupation farm labourer ? has trailing ?. Removed and flag set.<br>
Warning: line 98 Occupation servant in husbandry? has trailing ?. Removed and flag set.<br>
Warning: line 234 Occupation for the bath? has trailing ?. Removed and flag set.<br>
ERROR: line 257 Civil Parish has changed to moilgrove which is not in the list of subplaces.<br>
Warning: line 257 Enumeration District changed to 15.<br>
Warning: line 257 New Folio number increment larger than 1 13.<br>
Warning: line 257 Schedule number 1 is less than the previous one .<br>
ERROR: line 262 House address ceybwr - ? Of part of pantywylan is invalid address.<br>
ERROR: line 262 Occupation farmer of 2 1/2 acres & ag. Lab. is field too long 32.<br>
ERROR: line 267 Occupation farmer of 39acs & master mariner is field too long 32.<br>
ERROR: line 302 Occupation farmer of 330acs emply 3 ag labs is field too long 32.<br>
ERROR: line 325 Occupation farmer of 52acs emply 1 ag. lab. is field too long 32.<br>
ERROR: line 371 Occupation farm servt. Under Revd DE Morgan is field too long 32.<br>
ERROR: line 372 Occupation dairy maid under Revd DE Morgan is field too long 31.<br>
ERROR: line 386 Occupation farmer 220acs emply 1 lab 2 boys is field too long 32.<br>
ERROR: line 471 Occupation farmer 109 acres emply 1 ag lab is field too long 31.<br>
ERROR: line 483 Occupation farm bailff frm 277acs empl 17L is field too long 31.<br>
ERROR: line 492 Occupation farmer 100acs emply 3 lab 1 boy is field too long 31.<br>
ERROR: line 499 Occupation late lieut. In the army sold out is field too long 32.<br>
ERROR: line 537 Occupation mstr mariner & frmr emply 1 Lab is field too long 31.<br>
ERROR: line 563 Occupation coast guard man-wife on bus. Ab. is field too long 32.<br>
Warning: line 569 House address cottage opposite ?  has trailing ?. Removed and flag set.<br>
ERROR: line 578 Occupation husband ag. Lab in Glamorganshre is field too long 32.<br>
ERROR: line 626 Occupation husband (ag. Lab) is at swansea is field too long 31.<br>
Warning: line 642 Schedule number 0 is less than the previous one .<br>
Warning: line 691 Civil Parish has changed to llantood.<br>
Warning: line 691 Enumeration District changed to 16.<br>
Warning: line 691 New Folio number increment larger than 1 25.<br>
Warning: line 691 Schedule number 1 is less than the previous one .<br>
ERROR: line 762 Occupation farmer 116acs emply 2labs 2boys is field too long 31.<br>

**Info level output**

Started on the file RG094177.csv for Captkirk at 2020-03-19 13:57:47 -0600. <p>
Working on Cardigan for 1861, in CGN
Warning: line 4 New Civil Parish St Dogmaels.<br>
Info: line 4 New Enumeration District 0.<br>
Info: line 4 Initial Folio number set to 4.<br>
Info: line 4 Initial Page number set to 1.<br>
Warning: line 11 House address cwm garwd?  has trailing ?. Removed and flag set.<br>
Warning: line 13 Surname  morris? has trailing ?. Removed and flag set.<br>
Warning: line 14 Forenames  margret? has trailing ?. Removed and flag set.<br>
Warning: line 15 Occupation labourer son? has trailing ?. Removed and flag set.<br>
ERROR: line 18 Marital status n is invalid value.<br>
Info: line 25 New Page number 2.<br>
Warning: line 26 Schedule number 0 is less than the previous one .<br>
Warning: line 34 Schedule number 8 increments more than 1 .<br>
Info: line 48 New Folio number 5.<br>
Info: line 48 New Page number 3.<br>
Info: line 48 Schedule number retained at 10.<br>
Info: line 72 New Page number 4.<br>
Warning: line 74 Occupation farm labourer ? has trailing ?. Removed and flag set.<br>
Info: line 97 New Folio number 6.<br>
Info: line 97 New Page number 5.<br>
Info: line 97 Schedule number retained at 22.<br>
Warning: line 98 Occupation servant in husbandry? has trailing ?. Removed and flag set.<br>
Info: line 120 New Page number 6.<br>
Info: line 145 New Folio number 7.<br>
Info: line 145 New Page number 7.<br>
Info: line 145 Schedule number retained at 32.<br>
Info: line 168 New Page number 8.<br>
Info: line 193 New Folio number 8.<br>
Info: line 193 New Page number 9.<br>
Info: line 218 New Page number 10.<br>
Warning: line 234 Occupation for the bath? has trailing ?. Removed and flag set.<br>
Info: line 243 New Folio number 9.<br>
Info: line 243 New Page number 11.<br>
Info: line 243 Schedule number retained at 56.<br>
ERROR: line 257 Civil Parish has changed to moilgrove which is not in the list of subplaces.<br>
Warning: line 257 Enumeration District changed to 15.<br>
Warning: line 257 New Folio number increment larger than 1 13.<br>
Info: line 257 reset Page number to 1.<br>
Warning: line 257 Schedule number 1 is less than the previous one .<br>

**Comment by Captainkirkdawson** [comment]
The processor needs to be extended to calculate the derived fields and to store errors/warnings and information messages

**Comment by richpomfret** [comment]
Done - closing and any new issues will be new stories.
