### ISSUE TITLE
Data missing from Statistics

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1273]
Previously collected (there 10/2/2021 but not there 31/7/2021):
Total number of transcribers who have accepted Transcription Agreement, but have no records
Percentage of active (existing) users who accepted Transcription Agreement

**Comment by Captainkirkdawson** [comment]
@PatReynolds  I see nothing wrong with the statistics
![statistics.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/55eba4dc-094d-4ae6-8b7b-bc0546f0e95d)

**Comment by PatReynolds** [comment]
Nopthing wrong with the statistics that are there - but the stastitics for transcribers who have signed the transcription agreement are missing (they used to be there).

**Comment by Captainkirkdawson** [comment]
Inconsistency caused by some calculations used the old transcription_agreement field ans some the new_transcription_agreement field.
They now all use the new_transcription_agreement field.
In addition lt was used when it should have been gt. Also fixed
