### ISSUE TITLE
Add code to VLD save that ensures that the freecen piece has a freecen2_place_id once we deploy the latter

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1276]

**Comment by Captainkirkdawson** [comment]
Code at process_vld_file(filename, userid) lines 20 to 30

**Comment by PatReynolds** [comment]
@Captainkirkdawson where are we up to on this?

**Comment by Captainkirkdawson** [comment]
This will be deployed when all other components of the transition to Freecen2 data model are ready

**Comment by Captainkirkdawson** [comment]
There appear to be code issues

**Comment by Captainkirkdawson** [comment]
Code added and deployed to test3
