### ISSUE TITLE
Load Civil Parishes from TNA Extraction for 1901 and 1911

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1280]
Some months ago it was decided that since the TNA had included many Hamlets and Townships and other Geographic places as well as Civil Parishes into the contents field from which we extract the civil parish without any form of distinction between the entries we would remove them.
Coordinators would then be expected to create the appropriate civil parishes at the point of transcription.
It has become apparent that this has the potential to be a great deal of work.
It is therefore proposed to re add those entries for 1901 and 1911.

**Comment by Captainkirkdawson** [comment]
Will require modifications to the original code so that it adds civil parishes to the existing District?piece structure if they are not already present. In many cases they are.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @rhodamackenzie The rebuild of the civil parish structure for 1901 and 199 has been completed. You may wish to review.

**Comment by geoffj-FUG** [comment]
Kirk

 

I went to FreeCEN2 live.

 

When I select 1891 I get the list of civil parishes for the year OK.

When I select 1901 I get the red message.

When I select 1911 I get the red massage.

 

So I decided to look on test3. I only have 2 parishes listed on test3. 

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @rhodamackenzie should be OK now.

**Comment by rhodamackenzie** [comment]
Looks fine, thank you
Rhoda

**Comment by PatReynolds** [comment]
Thank you @rhodamackenzie 

Closing, but please re-open, @Captainkirkdawson  If I have done so too early
