### ISSUE TITLE
209234088 Mauritius (Michael): Edit and creation of gazetteer entries Via the Gazetteer can change county

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1283]
Issue reported by **MikeS** at 2021-08-18 16:34:48 UTC
Time: 2021-08-18T16:31:40+00:00
Session ID: bad6538314158048c706056fd63a6ee4
Problem Page URL: [/freecen2_places/5fdf24bdf493fd15ed00a0a5?locale=en](/freecen2_places/5fdf24bdf493fd15ed00a0a5?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/5fdf24bdf493fd15ed00a0a5/edit?locale=en](https://www.freecen.org.uk/freecen2_places/5fdf24bdf493fd15ed00a0a5/edit?locale=en)
Reported Issue:
Mauritius: Whilst editing I have noticed that this is in DUR (Durham) not OVB as it should be, or maybe OVF. All information and references are otherwise correct although the coords were not.
Can this be amended centrally or does it have to be deleted and redifined? MikeS    

It is clear that the edit will indeed move the Place to the county in which you are currently active. Hence you are correct that people with multi county authority can effectively move a place between counties.
This will occur if you use the edit or create action from the gazetteer page. 
It will not occur if you use those actions from the Manage Freecen2 Place action of a for a specific county.

The specific entry has been corrected

**Comment by Captainkirkdawson** [comment]
Fixed and deployed
