### ISSUE TITLE
Action to list dependencies of a Gazetteer entry

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1290]
Often there is a need to disable an incorrect Gazetteer entry. This cannot be done if the entry is being used by a District, Piece or Civil Parish. There is no way for a Member to find these dependencies and a programmer has to locate them.
Hence write an action for the master county coordinator, data administrator or system administrator to list the dependants.

E2 U6 S8 C6: P22

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG FYI

**Comment by PatReynolds** [comment]
@Geoff-FUG is this still a live issue?

**Comment by geoffj-FUG** [comment]
This is a live issue and it should have a high priority. 
@rhodamackenzie is the one who knows how much heartache this is causing, but I have a big backlog of Gazetteer amendments that need to be done to get things tidied up.
Geoff

**Comment by DeniseColbert** [comment]
@Vino-S to run the rake task and @rhoda to check once ready

**Comment by Vino-S** [comment]
First list completed and ready for test

**Comment by DeniseColbert** [comment]
@geoffj-FUG could you send @Vino-S your list please?

**Comment by geoffj-FUG** [comment]
Vino
You say that the first list is ready for test. This has me confused.
The Gazetteer in Production is a live document and changes from hour to hour (or more often) as additional places are added. If these amendments have been made to test3 how are they going to be transferred to the live Gazetteer. You cannot do a copy as the production Gazetteer has been amended radically over time.
The changes should have been run on the live Gazetteer. Is that where they have been done?
Geoff

**Comment by DeniseColbert** [comment]
Vino confirmed that they are ready to be tested on the live website @geoffj-FUG

**Comment by geoffj-FUG** [comment]
Thanks

I will have a look

Geoff

**Comment by geoffj-FUG** [comment]
List forwarded to Vino from Rhoda

Geoff

**Comment by DeniseColbert** [comment]
@Vino-S to send issue with list to @geoffj-FUG and @rhodamackenzie

**Comment by DeniseColbert** [comment]
@Vino-S to send an email to Geoff and Rhoda highlighting the entry

**Comment by DeniseColbert** [comment]
@Vino-S did you finish Geoff's last spreadsheet?

**Comment by DeniseColbert** [comment]
Deployed: closing
