### ISSUE TITLE
Age problems with 999 entry

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1299]
Issue reported by **Suzy Cairns** at 2021-09-17 08:43:42 UTC
Time: 2021-09-17T08:41:37+00:00
Session ID: 
Problem Page URL: [https://www.freecen.org.uk/search_records/5a156098f4040b9d6e760b0b/james-turner-1841-roxburghshire-kelso-1839-?locale=en](https://www.freecen.org.uk/search_records/5a156098f4040b9d6e760b0b/james-turner-1841-roxburghshire-kelso-1839-?locale=en)
Previous Page URL: [https://www.freecen.org.uk/contacts/5a156098f4040b9d6e760b0b/report_error?locale=en&query=6144548933045b476c36d01f](https://www.freecen.org.uk/contacts/5a156098f4040b9d6e760b0b/report_error?locale=en&query=6144548933045b476c36d01f)
Reported Issue:
Searching for "James Turner" born 1839 in Roxburghshire, Scotland.  He was in the 1841 Scotland Census in Roxburghshire.  He is the only result however on the search results it shows his year of birth as 1836 hut when you open up the transcription he is only 2 years old in 1841 which would make his year of birth 1839, somehow the search results is displaying an inaccurate year.    

E0 U2 S6 C 6: P14

**Comment by Captainkirkdawson** [comment]
This is likely not unique to Scotland

**Comment by Captainkirkdawson** [comment]
Margaret Singleton <lanark_census@btinternet.com> wrote

However it has highlighted a couple of points and I’m not sure if they are already being dealt with.

In FreeCEN1 when an age was recorded as 999 it was displayed in both the summary page and detail as unknown.

In FreeCEN2 it is not displayed in the summary page as unknown and the Year of birth is given as 839 which does not compute to 999?

Also in FreeCEN2 if you search on Francis Coutts with Birth year 825-845 you don’t find any.

If you search Francis Coutts 800-1845 you find 8 but not the one displayed as 839 previously.

I thought maybe they were allowing in some way for the 5 year round down for 1841 but this does not appear to be the case.

It would seem that as well as the 999 problem that the age is not accurate for children under 15.

E.g. searching for Francis Coutts in 1841 there are 9 records 4 of whom are under 15.

FreeCEN1 age 3 is displayed as born in 1835

Age 4 is displayed born 1834

Age 5 is displayed born 1833

Age 12 is displayed born 1826

 

Also search for Andrew Coutts in the 1841 census and there are 2 under 1 year

8m in FreeCEN1 and born in 1837 in FreeCEN2 - wrong

1m in FreeCEN2 and born in 1841 in FreeCEN2 - correct

 

Do you know if these discrepancies are known?

 

I’ve attached a few screen shots to highlight these issues.
![age1](https://user-images.githubusercontent.com/2874694/135472883-ae5bfa69-29a8-4244-9567-52ddbf289a09.jpg)
![age2](https://user-images.githubusercontent.com/2874694/135472910-f98c5bcc-de4e-4150-8e65-814305b4dfae.jpg)
![age3](https://user-images.githubusercontent.com/2874694/135472942-17cf3cc3-01e4-4463-ae36-b3ee0c1f30bb.jpg)

**Comment by DeniseColbert** [comment]
@AnneV-Learn to take a look

**Comment by AnneV-Learn** [comment]
I have completed the investigation. There is a note in the code about the way ages where recorded for 1841 Census:
# Census day: June 6, 1841
        #
        # Ages in the 1841 Census
        #    The census takers were instructed to give the exact ages of children
        # but to round the ages of those older than 15 down to a lower multiple of 5.
        # For example, a 59-year-old person would be listed as 55. Not all census
        # enumerators followed these instructions. Some recorded the exact age;
        # some even rounded the age up to the nearest multiple of 5.
        #
        # Source: http://familysearch.org/learn/wiki/en/England_Census:_Further_Information_and_Description

Some some 'adjustment' of the calculated birth year based on the age has been coded to take account of this when calculating the Birth Year displayed in Search Results for data from 1841 census. 
However I think the logic is wrong. it tries to adjust the year by 3 years (presumably using this as a 'mid point for 5 years??) if the calculated year is after 1826 (i.e.1841 - 15) 
when it should be if the calculated year is before 1826.

(
Code snippet from **SearchQueriesHelper**

def format_freecen_birth_year(search_date, record_type)
    search_year = search_date.gsub(/\D.*/,'')
    if search_year == record_type
      search_year
    else
      if record_type == RecordType::CENSUS_1841 && search_year > "1826"
        "#{search_year.to_i - 3}"
      else
        "#{search_year.to_i - 1}"
      end
    end
  end
)

Search Data review:
[GitHub_1299.xlsx](https://github.com/FreeUKGen/FreeCENMigration/files/7296794/GitHub_1299.xlsx)

**Comment by suffolkroots** [comment]
This makes a mockery of TWYS. Search results should accurately reflect entries.

**Comment by Captainkirkdawson** [comment]
he transcribed entry is correctly shown in the detail.

        "sequence_in_household" : 6,
        "individual_flag" : "-",
        "surname" : "TURNER",
        "forenames" : "James",
        "name_flag" : "-",
        "relationship" : "-",
        "marital_status" : "-",
        "sex" : "M",
        "age" : "2",
        "age_unit" : "y",
        "detail_flag" : "-",
        "occupation" : null,
        "occupation_flag" : "-",
        "birth_county" : "ROX",
        "birth_place" : "-",
        "verbatim_birth_county" : "ROX",
        "verbatim_birth_place" : "-",
        "birth_place_flag" : "-",
        "disability" : null,
        "language" : null,
        "notes" : null,
        "freecen1_vld_entry_id" : ObjectId("5a15605ef4040b9d6e75d3c7"),
        "freecen_dwelling_id" : ObjectId("5a156072f4040b9d6e75e8f9")

For the purposes of searching we transform the actual entry into a search record that has an actual date so that we can do the range search. The transformed record is
{
        "_id" : ObjectId("5a156098f4040b9d6e760b0b"),
        "transcript_dates" : [
                "1839-*-*"
        ],
        "search_dates" : [
                "1839-*-*"
        ],
        "location_names" : [
                "Kelso"
        ],
        "search_soundex" : [
                {
                        "first_name" : "J520",
                        "last_name" : "T656",
                        "type" : "p"
                }
        ],
        "transcript_names" : [
                {
                        "first_name" : "James",
                        "last_name" : "TURNER",
                        "type" : "primary"
                }
        ],
        "chapman_code" : "ROX",
        "record_type" : "1841",
        "place_id" : ObjectId("590261bae9379091b1b61c1d"),
        "birth_chapman_code" : "ROX",
        "freecen_individual_id" : ObjectId("5a156072f4040b9d6e75e8ff"),
        "search_date" : "1839-*-*",
        "digest" : "xh9uLZGWxuVMlRdIGMLtzA==",
        "u_at" : ISODate("2021-09-17T08:40:41.838Z"),
        "c_at" : ISODate("2017-11-22T11:33:44.387Z"),
        "search_names" : [
                {
                        "_id" : ObjectId("5a156098f4040b9d6e760b0c"),
                        "first_name" : "james",
                        "last_name" : "turner",
                        "origin" : "transcript",
                        "type" : "p",
                        "role" : null,
                        "gender" : "m"
                }
        ],
        "birth_place" : "-",
        "embargoed" : false
}

The code to do this is in https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/freecen1_vld_translator.rb#L23-L66.

This does an adjustment based on the actual date of the census

def translate_date(individual, census_year)
      age = individual.age.to_i
      age_unit = individual.age_unit

      adjustment = 0 # this is all we need to do for day and week age units
      if age_unit == 'y'
        adjustment = 0 - age
      end

      if age_unit == 'm'
        if census_year == RecordType::CENSUS_1841
          # Census day: June 6, 1841
          #
          # Ages in the 1841 Census
          #    The census takers were instructed to give the exact ages of children
          # but to round the ages of those older than 15 down to a lower multiple of 5.
          # For example, a 59-year-old person would be listed as 55. Not all census
          # enumerators followed these instructions. Some recorded the exact age;
          # some even rounded the age up to the nearest multiple of 5.
          #
          # Source: http://familysearch.org/learn/wiki/en/England_Census:_Further_Information_and_Description
          adjustment = -1 if age > 6
        elsif census_year == RecordType::CENSUS_1851
          # Census day: March 30, 1851
          adjustment = -1 if age > 3
        elsif census_year == RecordType::CENSUS_1861
          # Census day: April 7, 1861
          adjustment = -1 if age > 4
        elsif census_year == RecordType::CENSUS_1871
          # Census day: April 2, 1871
          adjustment = -1 if age > 4
        elsif census_year == RecordType::CENSUS_1881
          # Census day: April 3, 1881
          adjustment = -1 if age > 4
        elsif census_year == RecordType::CENSUS_1891
          # Census day: April 5, 1891
          adjustment = -1 if age > 4
        end
      end

      birth_year = census_year.to_i + adjustment

      "#{birth_year}-*-*"
    end
This code has done the calculation correctly.

There is then the code you have identified that manipulates the date used in the search to display the date in the search results.

I simply do not follow the logic of changing the date at the point of display; this will always cause discrepancies. 

The code is incorrect anyway as you indicate

But surely any adjustment should have been done to the date in the search record if it was deemed necessary to try to adjust for this rounding.

Dealing with this would address the earlier comments of Margaret. However there is no code that traps the 999 age entry which likely should have a search record of zero which translates to unknown

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn Can you delete the code that changes the display of the search record I believe we both agree that it is not needed (even if it were correct).
Can you also trap the 999 and set to zero

**Comment by Captainkirkdawson** [comment]
First part dealt with and deployed to test3.

![fixed.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/196f3701-29ab-4c71-ae7c-b635f3108d7d)
999 part remains open

**Comment by PatReynolds** [comment]
Moved to new issue: #1318 :

Serach for Ann Alcock, born 1841 +/- 2 (FC1) or 1838-1841 (FC) A, search anywhere for census county and birth county found one born notts, census notts, thurgaton 1841 is found (age 3 birth year in FreeCEN1 but not found by a search in FC2.  

James Alcock, same parameters finds him aged 1 in FreeCEN2, but 1 month in FreeCEN1 (only result for this search).

Apologies if I wasn't testing for the right thing.

**Comment by Captainkirkdawson** [comment]
The problem was that we were displaying a modified age in the Search Results that was different from the one on the search Detail for young people.  
See original statement.
_Searching for "James Turner" born 1839 in Roxburghshire, Scotland. He was in the 1841 Scotland Census in Roxburghshire. He is the only result however on the search results it shows his year of birth as 1836 hut when you open up the transcription he is only 2 years old in 1841 which would make his year of birth 1839, somehow the search results is displaying an inaccurate year._

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn when you have a few minutes could you look at the incorrect handling of the age 999; it has come up again

**Comment by Captainkirkdawson** [comment]
The fix developed by @AnneV-Learn has been deployed

**Comment by Captainkirkdawson** [comment]
The fix developed by @AnneV-Learn has been deployed
