### ISSUE TITLE
FreeCEN feedback goes to FreeCEN board, not FreeREG

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#13]
We need to set up a github issue repository for FreeCEN product feedback, then change the FreeCEN installation to use that instead of FreeREG's repository

**Comment by benwbrum** [comment]
For part of this work, I've created a new Github team for FreeCEN-related people, as we were getting complaints from FreeREG folks about notifications from this board.

**Comment by FreecenBren** [comment]
Thanks Ben. I know what they mean as I keep reading their issues just to see what kind of things we will most probably  get to see in the future.
