### ISSUE TITLE
Change statement on Volunteer page from FC1 to FC2 specific

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1300]
Currently:

> We will send you images to transcribe, links to specialist software needed (or you can use a pre-formatted spreadsheet) and guidance on how to transcribe.

Suggested:

> We will send you images to transcribe, a pre-formatted spreadsheet, and guidance on how to transcribe.

**Comment by Captainkirkdawson** [comment]
Done by @Vino-S
