### ISSUE TITLE
Remove OVB as Chapman Code

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1303]
Geoff wrote
This information only brings the OVF OVB issue back for discussion. The following suggestion refers to Places of Birth, not Civil Parishes so is something for the future. But we can fix it now.

The standard Chapman Code for Overseas is OVF. OVB is a FreeCEN invention presumably to try and capture the Nationality info that gets added in the census margins.

I am regularly disabling Gazetteer entries that have the OVF / OVB code incorrect. This is presumably to make a particular validator or validators life easier. However it is having an impact on all validators. In addition when the latitude / longitude search is being linked to the Gazetteer entry the OVB entries in the census for France for instance will not bring up a match.

(Kirk would find it interesting if he knew just how many transcribers do not identify Canada as a British Colony and enter OVF).

When we designed FreeCEN2 spreadsheets we took the first step towards capturing this information effectively by including the Nationality column even where the information was not formally captured in the census.

Maybe it is time that we abolished the use of OVB and made them all the standard OVF. The nationality column would display British subject etc.

 We would probably need to do an amendment to the current data by adding British to all OVB entries and then amending all OVB Chapman Codes to OVF. This would be a global replace in each instance.

All Gazetteer entries that are currently OVB would also have to be amended to OVF.

That would eliminate the OVB / OVF mess that has developed over the years and make Kirk’s latitude / longitude matching so much more reliable.

**Comment by Captainkirkdawson** [comment]
@PatReynolds wrote
 would certainly support removing the OVB (and adding OVF in its place, and the nationality British to the Nationality column (flagging for human review any person who already has data in the Nationality Column).

**Comment by suffolkroots** [comment]
Entering OV places is, and always has been, a huge can of worms, and has only been made worse by the need to grid-reference them.
Do we TWYS or make value judgements?
There is no indication anywhere explaing to us that, eg, OVB grid-referenced to foreign parts will not be linked to anywhere.
I 'm sure I'm guilty of this heinous offence, and can only apologise.
If OVB is discontinued, wonderful.
If OVB to remain, perhaps a comprehensive list of British Colonies could be included in the handbook.

**Comment by Captainkirkdawson** [comment]
Delete as duplicate see #1310
