### ISSUE TITLE
For Review: May 2021: Archival process for Site Stats

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1304]
We probably need to develop an archival process for the Site Stats data. 
Maybe not relevant until data collection has been running for a year or so.

**Comment by PatReynolds** [comment]
That's a very good idea.

**Comment by PatReynolds** [comment]
Hello @AnneV-Learn we've now benefited from FreeCEN stats for over a year - can we look again at archiving?

**Comment by AnneV-Learn** [comment]
@PatReynolds Yes of course. 
We need to decide how and when to archive a FreeCenSite Stats record.
One straightforward option might be to create a Site_stats_archive document/table/model and just write 'archived' records to that.Or they could be written to a CSV file (easy to read into spreadsheet etc.) and saved on a server somewhere.
Possibly run a monthly rake task that copies Site Stats records that are more than one year old and are not 1st of the month to the archive and delete them from the main table (this would leave deleted records still available just in case they where ever needed). Leaving the first of the month record would mean that we would still be able to see some of the 'older' stats.
This would reduce the number of records kept in the main Site Stats document/table/model and so reduce the load time for the page.
Those are just my initial thoughts but of course there will be many alternative approaches.

**Comment by PatReynolds** [comment]
Archive most, but keep 1st of Month in a table for easier access.

**Comment by AnneV-Learn** [comment]
implement solution on Test3 and ran the rake task there. All seems ok, so ready for deployment to production and then a monthly job needs to be set up to run the rake task each monthly.

**Comment by DeniseColbert** [comment]
Done so closing
