### ISSUE TITLE
Place Name editing

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1306]
Place name editing was designed to work on the County the member was managing.
With the ability to edit a place located in the Gazetteer search with assumption is now longer valid and mistakes can arise.
![FreeCEN Search Misson.jpg](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/68261b66-f592-4f1c-91bf-fc098f6446dc) 
![FreeCEN Search Misson Edit.jpg](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/8ab60044-5d8f-42c5-afa6-00ea5502c038)

E0 U6 S7 C6: P19

**Comment by Captainkirkdawson** [comment]
Code adjusted to use county of record when editing. Deployed to test3

**Comment by PatReynolds** [comment]
@rhodamackenzie to test.

**Comment by rhodamackenzie** [comment]
working well, closed
