### ISSUE TITLE
216303443 no return of pieces (Dave)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1319]
Issue reported by **32pascOE55** at 2021-11-08 12:17:23 UTC
Time: 2021-11-08T12:11:54+00:00
Session ID: 5381f21404c7ae04d532dcaaf47a1f91
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freecen.org.uk/](https://www.freecen.org.uk/)
Reported Issue:
entered three pieces to CSVProc to convert from freecen1 to freecen2

but nothing returned?    

![Screenshot](https://www.freecen.org.uk)

**Comment by PatReynolds** [comment]
@Captainkirkdawson to take a look - may have alarady been dealt with

**Comment by Captainkirkdawson** [comment]
Yes it was responded to . Improvement made to csvproc messaging
