### ISSUE TITLE
Resolve problems with vld Download in CSVProc

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1324]
Whilst I have replaced vld files with csv files on a few occassions I had not picked up a problem with record counts. I was preparing a file for Pat when I notoced that the 1861 vld file that I downloaded from CSVProc was 200 records short of the count in my tracking spreadsheet (in this case about 10% of the file). I did not have an original transcription for that piece any more so I found an 1871 piece that I did have the original transcription for. I reconciled the original transcription and the download and discovered that it was about 20 reciords short (about 2%) 
File sample RG10_2349. Observations as follows:
1.	When there is a proper schedule number entered against a 'u' in the uninhabited field it is being changed to 0 on download.
2.	UNK gets added as the Chapman Code of unoccupied buildings. I did not have instances of 'v' or 'b' so cannot comment on those.
3.	If a record has an 'x' as a flag, the record does not get downloaded into the csv file.  FreeCEN1 allowed the flags to be uploaded but they are no longer used by reports. CSVProc requires them to be resolved or replaced by an entry in the Notes field. This appears to be the cause of the missing reords.
4.	Schedule 0 and page number appear against second person on a ship as well as the first person (ships are correctly transcribed as schedule no 0 on original transcription)
I have both a file as downloaded and a corrected file that I can send to Kirik if and when needed.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I believe the latest version of the vld download as CSVProc works as expected. Deployed to test3 for you to test

**Comment by geoffj-FUG** [comment]
All of the reported issues are now correct in a download. I am happy for this to go live.
Geoff
