### ISSUE TITLE
Update Help Material for Nearby Places

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1327]
https://test3.freecen.org.uk/cms/draft-help

**Comment by AlOneill** [comment]
@Captainkirkdawson has created a draft page and edited the text of the Census location section. I'm not the sharpest knife in the box but I do not quite understand the meaning of Place (as in Census Place in the search form) as compared to the place of Nearby Places. Explaining our use of Place clearly for a researcher will take some thought …

My initial testing has revealed some anomalies (misplaced places) in the Gazetteer — I will open a separate issue for those.
Edit: it would not open a new issue, citing "internal error". Have used Contact us to report a Website problem.

**Comment by Captainkirkdawson** [comment]
There is no difference. When using the Nearby option it looks for records in nearest places to the place that was selected. It keeps moving to more distant places until the maximum number of places is attained (Initially set to 100). i.e. Imagine a circle based on the place selected that has its radius increased until we have enough places. It pays no attention to the county once the initial point has been selected.
Yes there are incorrect locations that we need to be told about and corrected. We need a contact report when that happens so it can be corrected.

**Comment by AlOneill** [comment]
Thank you @Captainkirkdawson. I understand about concentric circles. Where is the centre of such a circle? A notional centre of the RD or sub-RD? Or something else?

**Comment by AlOneill** [comment]
Have corrected some typos in the Draft page. Is this enough? I feel the wording could be improved but will need some time to come up with a version that is easier to understand.

**Comment by Captainkirkdawson** [comment]
The center is the Place selected in the Place List for the county. That is whatever that place is. For most it will be the Sub RD, sometimes the RD and sometimes the Civil Parish. In essence the Place is a place name with a lat/lon and we try to make it the smallest area possible

**Comment by AlOneill** [comment]
@Captainkirkdawson OK. I'll stop asking daft questions.

Fixed some grammar today and discovered more new text and some broken markup. If no more content is added or edited, all is now fixed. (Am still pondering how to make the text more accessible to the general reader.)

@the_Scum Do we publish the revised text as it stands or are there parts that need attention first?

**Comment by PatReynolds** [comment]
@PatReynolds @DeniseColbert to check, (and @DeniseColbert to write a blog post) and report back to @Captainkirkdawson

**Comment by Captainkirkdawson** [comment]
@AlOneill Can you do what you do to make the DRAFT Help ready for use and I will transfer to production

**Comment by AlOneill** [comment]
@Captainkirkdawson The draft page has been checked and promoted — it is sync-ready.

**Comment by Captainkirkdawson** [comment]
Thanks @AlOneill deployed.
