### ISSUE TITLE
Review Gazetteer Places within Counties

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1330]
The Nearby places search option is showing that we have incorrect coordinates for some of our Places.

It would help if we were to conduct a systematic review of the places in a county not by detail but by a visual review to identify outliers and correct those if necessary.

It is suggested we go county by county. List Active Places with Records; in the list visually scan for entries that look incorrect in their location; normally the lat lon will be withing a fairly small range. Pick out any strange entries and check them 
eg Go to BDF do the list as suggested pull down the list and get a sense of the lat/lon
![scan1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/c1fc722e-a3c4-40cf-ba17-4a144b7d0b0f)

You get the sense that lat/lons are 52 to51.9 / -0.4 to -0.6. Repeat that scan down with that in mind an look for oddities.

![outlier.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/521f301b-172f-490a-8338-a7d24e407e9d)

Barford hits one straight away with its -1.366 and a check shows that is not correct. Especially as it has no source!!!

It should be corrected. There are no other major outliers so a 5 minute review has done what we need.

Just need to do that with all counties

**Comment by rhodamackenzie** [comment]
Kirk, 
is there any way i can access the places as an excel file along withe county and lat/long? Both for fast scanning to find problems and to let me check i have not missed out any minus signs after i make changes? Happy to look at all placenames this way, or to only look at active ones. It's terribly time consuming plus i will have to go back and check them all manually again at the end.

**Comment by Captainkirkdawson** [comment]
@rhodamackenzie Sent off line

**Comment by rhodamackenzie** [comment]
Hi Kirk, 
I'm finding several places which are duplicates of correct places but in other counties a long way from the correct county, most were edited at some point, by sensible people who would not have made this mistake. I wondered if this is the situation you mentioned where an error occurred if someone was working in a different county then went into the gazetteer.
Anyway - I cannot disable these placenames as they have dependent records. Please let me know how to deal with these.

**Comment by Captainkirkdawson** [comment]
@rhodamackenzie Providing you have not created a new place of the same name in the correct county you should be able to correct the incorrect one. If you have already created a new one then that needs to be renamed and deleted; renaming is essential prior to disabling

**Comment by rhodamackenzie** [comment]
This is sorted, closing now
