### ISSUE TITLE
Rake task for unassigned or misassigned transcribers

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1332]
Ultimately, all transcribers should be in a syndicate that reflects their transcribing. A rake task to identify those in:

Any Questions? Ask Us
Any County and Year
Technical
Wales Syndicate (?)
Yorkshire Syndicate (?)

And all old syndicates that are no longer in the dropdown list on Registration page

**Comment by Captainkirkdawson** [comment]
Task written by @AnneV-Learn and deployed to production.

**Comment by Captainkirkdawson** [comment]
task run and report sent off line to @AnneV-Learn and @DeniseColbert

**Comment by DeniseColbert** [comment]
Could this be used to identify users in the England syndicate, for the purposes of #1375 ?

**Comment by Captainkirkdawson** [comment]
Possibly
