### ISSUE TITLE
Vld records marked as deleted  are not downloaded by CSVProc

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1333]
@geoffj-FUG reports that If a record has an 'x' as a flag, the record does not get downloaded into the csv file. FreeCEN1 allowed the flags to be uploaded but they are no longer used by reports. CSVProc requires them to be resolved or replaced by an entry in the Notes field. This appears to be the cause of the missing records.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I can confirm that the download does not download an entry that contains the deleted flag. It is NOT clear to me what action you want us to take.
From my research both FC1 and FC2 simply ignore the flag and treat it like any other record. In your file the first 2 deleted flag entries are in the same household. See attached.
![Bull1.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/fa00a50a-2294-4066-8167-66a68a6f836e) 
A search on FC1 produces the following result
![bull2.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/31c7ed17-c017-469f-a1de-ae9a1bcfdac9)
A search on FC2 produces the same result.
![bull3.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/be2ae852-48a9-48fc-a2a2-ef94d4369ada)
In both cases the record with the deleted flag is treated like any other record; i.e the flag is ignored.
So what should we be doing on the download? It is not clear to me.
It seems the record should be included. But should we add something to the notes ? 
As far as I am aware there is no deleted field in CSVProc.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG since there has been no advice yet and in order to make progress on the other aspects of the VLD download I propose to include the entries in the download and set the uninhibited flag to n and added a note "Deleted flag set on VLD; "

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Using n is not going to work. Will try x

**Comment by geoffj-FUG** [comment]
Kirk
The deleted flag is not that flag that is causing the problem. It is the flags that were put into the following columns in the FC1 tarditional spreadsheet - H (address flag and uninhabited etc. Uninhabited etc download OK), K (Names flag), P (Age etc flag), S (Occupation flag) and V (POB flag).
It is the x flags  in FC1 tht drew the attention of the proofreader / validator to a problem record.
In FC2 we require this flag to be replaced by a Note and for it to be removed before a piece can be Incorporated. In FC1 the flags were left if the issue was not resolved. It is these unresolved x flags that are causing the problem.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG sorry to disagree but the first problem is the deleted flag from the VLD entry. 
The code as originally written did not output any entry with the deleted flag field in the vld entry set to D.
A vld entry has 299 bytes and is set up as 
Entry field	Transcriber field	Starting_byte	Number_of_bytes	
A	X	0	1	Deletion marker (D or blank)
B	X	1	4	Not used. Was Registration district - this usage is discontinued.
C	X	5	6	A six digit number (leading zeros) which counts the households
D	X	11	4	A four digit number (leading zeros) which counts members in each household
E	A	15	20	Parish name (I do not check this, it is up to you to get it right!)
F	B	35	4	Enumeration district (3n+1a, the remaining numeric fields have trailing spaces)
G	C	39	5	Folio number (4n+1a)
H	D	44	4	Page number (4n)
I	E	48	4	Schedule number (3n+1a)
J	F	52	5	House number (4n+1a)
K	G	57	30	House/Street name (default -)
L	H	87	1	Uninhabited flag (b, u, v, n, x or -)
M	I	88	24	Surname (capitals, default -)
N	J	112	24	Forenames (default -)
O	K	136	1	Flag for name fields (x or -)
P	L	137	6	Relationship (default -)
Q	M	143	1	Condition (M, S, U, W or -)
R	N	144	1	Sex (M, F or -)
S	O	145	3	Age (no default but 999=unknown/unreadable)
		148	1	Age unit(y, m, w, d or -)
T	P	149	1	Flag for detail fields i.e. rel/cond/sex/age (x or -)
U	Q	150	30	Occupation
R				Employed Status (extracted from occupation field)
V	S	180	1	Flag for occupation (x or -)
W	T	181	3	County code (3a capitals, no default but UNK if not known)
X	U	184	20	Birth place (default -)
Y	V	204	1	Flag for birth place (x or -)
Z	W	205	6	Disability (default blank)
AA	X	211	1	Language (W, E, B, G or blank)
AB	Y	212	44	Notes (default blank, no case)
AC	X	276	3	Alternate birth county
AD	X	279	20	Alternate birth place

As I said earlier **From my research both FC1 and FC2 simply ignore the deleted flag and treat it like any other record.** 

Some of those records have other flags set but not very many. I have extracted the 552 vld entries in file RG10_2349 and listed them in the attached file so you can see what I am talking about.
[vld deleted entries.xlsx](https://github.com/FreeUKGen/FreeCENMigration/files/7584820/vld.deleted.entries.xlsx)
So do we just ignore the D flag and only may attention to the other flags (There is already code dealing with some of these). Do we add a message into the notes. What do we do?

**Comment by Captainkirkdawson** [comment]
@FreecenBren has confirmed as follows:
So I used the search for this PIECE I found where a D has been used.

You will see that at some stage the D was meant to be deleted but it was not.

The system though still passed it.

**Comment by Captainkirkdawson** [comment]
Excellent work Brenda.

You have confirmed that FC1 paid no attention to the deleted flag in the VLD and included that record in the database.

I have confirmed that FC2 also ignored the deleted flag. Hence the 2 databases are consistent but incorrect.

You have confirmed in that one case that the record with the deleted flag should not have been included.

Perhaps Geoff can confirm the situation with his example.

It means that the download of a vld file in CSVProc format should not download a record with the VLD deleted flag unless we want to flag it in some other way.

That leaves us with the question of what to do about it. FC1 cannot be corrected.  FC2 can be corrected by writing a database correction task, having first confirmed the extent of the problem.

**Comment by FreecenBren** [comment]
We could, well I will anyway, check all  of the VLD’s  I still have to
finish off, before they are added to the database, to ensure that all D’s
are amended.

Not sure about checking those already online, but if you can identify any
then I will do them,  no problem, as long as they are for my counties.
(Still plenty of those)

Cheers Brenda

**Comment by PatReynolds** [comment]
@PatReynolds  to research the utility to researchers of retaining the Deleted entries, and report back.

**Comment by PatReynolds** [comment]
Just checking: D means there was an entry in the census, which was struck through?  There are some examples mentioned in this online discussion: https://www.rootschat.com/forum/index.php?topic=791507.9

Thanks, 

Pat

**Comment by geoffj-FUG** [comment]
THIS HYPOTHESIS IS NOW DISPROVEN. See next message.


Pat

 

The old FC1 Wincc and Valdrev had a field that kept track of the progress on the piece for the volunteer. This had several codes including ‘D’. 

 

The ‘D’ was generated by the software when an entry was deleted by the Proofreader (WinCC) or the Validator (Valdrev). It was a soft delete.

 

There was no instruction apparent to me that the Coordinator needed to remove these records post validation so my presumption has always been that these records were deleted on upload but obviously they were not. 

 

Neither did FC1 seem to deal with them in any way. It seems to have been an idea that was sound but not finalised. Hence the current problem of deleted records appearing in the FC2 database.

 

The intention seems to be that these records were not needed for a variety of reasons and therefore would not be displayed.

 

From the actions that I have taken in the past I see no issue in simply removing them from the database. They are and always have been intended as deleted records.

 

Geoff

**Comment by geoffj-FUG** [comment]
At this point I am raising a **BIG RED FLAG.**
I have just downloaded a vld file. It is RG9 1705 Bedminster. I noticed that there is a Note in the Notes column that the vld flag is set to D. Soo I started looking at the entries.
Take Jane Brice F3 P1 Sch 2. She is on the image and should not be deleted. Yet she had a D. (I am afraid that the vld file is now in the attic as I was in the process of replacing it with a csv file).
So I have had a look at the next few entries. They are all valid entries, not deleted ones.
There were 470 entries with this comment. The number of soft deletions in a piece was typically less than 5.
This disproves the hypothesis that they are flags carried through  from the old WinCC,  Valdrev  system.

Geoff

**Comment by PatReynolds** [comment]
So the next task is to understand why the validator or coordinator marked entries as D (if not because the enumerator had deleted them).

**Comment by geoffj-FUG** [comment]
Pat
The Proofreader or Validator would not have added the D. The system would have.
The piece that I looked at was one that I would have validated many years ago. I can see absolutely no reason for the flags to be in the file.
What I have found disproves the hypothesis that the flags were entered by Wincc or Valdrev. 
The answer lies somewhere in FC1 itself.
Geoff

**Comment by PatReynolds** [comment]
Concluded that there is no reason why the D is there, so @Captainkirkdawson will remove them.

**Comment by Captainkirkdawson** [comment]
Records with a soft delete are now downloaded and a note added. Deployed to test3

**Comment by Captainkirkdawson** [comment]
All of the reported issues are now correct in a download. I am happy for this to go live.
Geoff
