### ISSUE TITLE
VLD download of shipping incorrect

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1336]
Schedule 0 and page number appear against second person on a ship as well as the first person (ships are correctly transcribed as schedule no 0 on original transcription)

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Freecen2 puts both page and schedule number against all shipping entries. Schedule number is given as 0 for all. Will remove for download for all except first

**Comment by geoffj-FUG** [comment]
Kirk

 

By first I presume that you mean first entry in a ship. There can be more
than one ship enumerated. A ship details in the address will identify the
start of a new ship.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Yes first person for the ship will have the entry

**Comment by Captainkirkdawson** [comment]
Code updated and deployed to test3 for testing

**Comment by Captainkirkdawson** [comment]
All of the reported issues are now correct in a download. I am happy for this to go live.
Geoff
