### ISSUE TITLE
Help : missing link content (advert missing)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1339]
![missing.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/b80494c6-7d4d-42e7-b11d-a878a5fabd74)
E2 U4 S9 C7: P22

**Comment by AlOneill** [comment]
@Captainkirkdawson That "missing link" is, in fact, a missing advert — not my territory.

**Comment by Captainkirkdawson** [comment]
@PatReynolds for you?

**Comment by PatReynolds** [comment]
Thanks @Captainkirkdawson taking a look at this now.

**Comment by PatReynolds** [comment]
Problem is it is a FreeREG/FreeBMD advert, not a FreeCEN advert.  Please confirm that the size wanted is width:336px;height:280px and I will make a FreeCEN advert that size (or whatever is needed).

**Comment by Captainkirkdawson** [comment]
@PatReynolds I have no idea on the structure of the Help but suspect so

**Comment by AlOneill** [comment]
The advert block is not fully responsive: depending on the window width, its appearance flips between as expected and variations on this:

![mal-responsive-advert.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/ff3136d5-245e-4352-b959-92883fb2a4bf)

**Comment by PatReynolds** [comment]
Sent code to Vino 14 Feb 2022

**Comment by PatReynolds** [comment]
Not working on test3, @Vino-S to push to live to test there.

**Comment by Vino-S** [comment]
code deployed to production
