### ISSUE TITLE
Detailed Results page displaying differently

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1346]
I have three FreeCEN tabs, all instigated within 2/3 minutes of each other. Each shows a different display:

https://www.freecen.org.uk/search_records/60fe6f81f493fd89eb38f46c/john-colbert-1861-huntingdonshire-st-neots-1794-?locale=en

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/22b9653e-de7a-4548-bc89-8db99951890c)

(Note: no function buttons at the top of the page, no Report a Data Problem text/link below Household, and no Donate text/button)

Same result:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/a588107d-da37-4000-89c1-344079db15ee)

(No text/link to report data problem or Donate)

https://www.freecen.org.uk/search_records/608bf085f4040bda1ae676a3/cyril-k-smith-1891-lancashire-prescot-1880-?locale=en

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/2d2cb99d-46fe-4908-9af1-37314a9b8253)

This last, is normal.

**Comment by Captainkirkdawson** [comment]
Its because you are logged in as a member and have been doing other things. Member displays are different for displaying entries

**Comment by PatReynolds** [comment]
To clear the specialist views, going back to the actions button clears it back to researcher view.
