### ISSUE TITLE
Recent additions shows totals of all piece for a place

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1352]
It would appear that we are showing the total number of records for all pieces of a place when 1 piece is added.
See the following for SFK
![recent additions SFK.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/b551190b-2974-44af-b3a5-c25a8e5eac33)
Listing the pieces show 2 pieces only one of which is recent.
![Not recent.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/8945fb32-c825-4f4d-bd65-7d0b353bc9f0)

**Comment by Captainkirkdawson** [comment]
Records online is correct but is misleading as the recent addition was only part of the total.
Perhaps the recent additions page should report what has been added and the total to be clear.

Colchester in Essex in 1891 is another example

**Comment by Captainkirkdawson** [comment]
Suggest we add an extra column
![Extra.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/17e62f4e-ada6-4514-a7d0-6ab3806299f3)

**Comment by AnneV-Learn** [comment]
Updated Recent Additions to show single column 'New Records Online'.
