### ISSUE TITLE
Extract a list of unique values in the sources field of the Gazetteer collection

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1359]
You request **Can you extract a list of unique sources please?** I interpret this as a request for a list of the unique values in the source field? Easily done but what will you do with it? Do you want the list as a txt file or ?

**Comment by geoffj-FUG** [comment]
My intention is to identify a standard entry for each source and a list of sources that we see as common.
I will then ask for a look-up table with these sources and Other in it. The Source field will then become a look-up field and stop rubbish such as a, b etc being entered.
If the entry is Other that is OK as long as we enforce the entry of a web address as well.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG there are 299 distinct (unique) entries
null,
        "",
        "ArchiUK",
        "Aussietowns",
        "Bath Record Office",
        "Bedfordshire Archive Service",
        "Berkshire Enclosure.org",
        "Bethnal Green Reg District",
        "Bing maps",
        "Britain Express",
        "Britannica",
        "Britiain Express",
        "British History",
        "British History Online",
        "British Listed Buildings",
        "British Place names",
        "Buckinghamshire Archeological Society",
        "Cambridge News",
        "Canal and River Trust",
        "Capestone Farm Website",
        "Ceredigion History Society",
        "Chedington",
        "Church of England",
        "City Town UK",
        "Co Curate",
        "Co-curate",
        "Coflein",
        "Cornish Place Names Wikidot",
        "DiCamillo, google maps",
        "Diocese of Derby",
        "Doogal",
        "Dover Kent Archives",
        "Durham Mining Museum",
        "Durham Mining Museum (dmm.org.uk)",
        "Dusty Docs",
        "EM Booker",
        "EMB",
        "English Heritage",
        "FIBIWiki",
        "Family Search",
        "Familypedia",
        "Familysearch",
        "Fibis Wiki",
        "Fibiswiki",
        "Forebears",
        "Forestry and Land Scotland",
        "Francis Frith old photos",
        "FreeReg1",
        "GAZETTEER",
        "GENUKI",
        "GENUKI Gazetteer",
        "GENUKI Gazetteer, 1871 Census",
        "GENUKI Gazetteer, Google Maps",
        "GENUKI Gazetteer, Wikipedia",
        "Gazatteer",
        "Gazeteer",
        "Gazeteer, gridreferencefinder.com",
        "Gazetteer",
        "Gazetteer ",
        "Gazetteer (straddles NTH/HUN border)",
        "Gazetteer of British Place Names",
        "Gazetteer of British Place names",
        "Gazetteer)",
        "Gazetteer, Google",
        "Gazetteer, Google Maps",
        "Gazetteer, Vision of Britain",
        "Gazetteer, Wikipedia",
        "Gazetteer, british-history.ac.uk",
        "Gazetteer, gatehouse-gazetteer.info",
        "Gazetteer, historicengland.org.uk",
        "Gazetteer, ukga.org",
        "Gazetteer, www.opcdorset.org",
        "Gazetter of British Place Names",
        "GenUKI",
        "GenUKI and gazetteer",
        "GenUKi",
        "Genuki",
        "Genuki Church Database",
        "Genuki St Nicholas",
        "Genuki and Gazetteer",
        "Genuki churches",
        "Genuki gazetteer",
        "Genuki, Stillington Community Archive",
        "Genukj",
        "GeoNames",
        "Geodata",
        "Geohack",
        "Geohack for location",
        "Get Outside Ordinance Survey",
        "Get Outside Ordnance Survey",
        "GetOutside",
        "GetOutside Ordinance Survey",
        "Getthedata",
        "Google",
        "Google Earth",
        "Google Maps",
        "Google Maps (Belmont)",
        "Google Maps, France This Way",
        "Google Maps, GENUKI Gazetteer",
        "Google Maps, Gazeteer",
        "Google Maps, Historic England",
        "Google Maps, Tripadvisor",
        "Google Maps, Vision of Britain",
        "Google Maps, Wikipedia",
        "Google Maps, https://twsitelines.info/",
        "Google Maps, https://www.dictionary.com/",
        "Google Maps, maplandia.com",
        "Google maps",
        "Google, Google Maps",
        "Hazetteer",
        "Henwyn Tyler Place Names",
        "Herts Gardens Trust",
        "Historic England",
        "Historic Landscape Characterisation",
        "Historic Place Names",
        "History of Llanbedrog",
        "Howard Evans",
        "Imperial Gazetteer",
        "Irish Townlands",
        "Jersey Deanery",
        "Lakes Guide",
        "Lincs to the past",
        "List of Historic Place Names",
        "Local",
        "Mapcarta",
        "Marton cum Grafton Village Website",
        "Mills Archive",
        "Mine data",
        "Mining Data ",
        "My London",
        "National Archives",
        "None quoted",
        "None. This place does not exist",
        "Norfolk Heritage",
        "Northumberland National Park",
        "OS Maps",
        "OS map",
        "OS maps",
        "Oceanhome",
        "Old Maps",
        "Ordnace Survey",
        "Ordnance Survey",
        "Ordnance Survey, Google",
        "Our Warwickshire",
        "Oxfordshire Gardens Trust",
        "Oxfordshire Villages",
        "Parish Registers",
        "Parks and Gardens",
        "Quaker Records",
        "Quakers Records",
        "Somerset Visitor Information Centre",
        "Sotonopedia",
        "South Willingham Org",
        "Southwark Diocese",
        "Southwark lost churches",
        "St Likes Church",
        "St Stephens Church",
        "Staffs Commercial Register",
        "Staffs cc",
        "Street Check",
        "Street check",
        "Streetcheck",
        "Streetmap",
        "TNA",
        "The Historic Environment Record for Exmoor National Park",
        "The Historic Environment Record for Exmoor national Park",
        "The Kirbys",
        "The Thoroton Society",
        "The Wokhouse Org",
        "The Workhouse",
        "Townlands.ie",
        "Travellingluck",
        "Treworgy History",
        "Tripmondo",
        "UK Genealogical Archives",
        "UK Genealogy Archives",
        "Varenne",
        "Victorian London",
        "Village Net",
        "Vision of Britain",
        "Vision of Britain, Google Maps",
        "Vision of Britain, Wikipedia",
        "Visit Bristol",
        "Visit Cornwall",
        "Visit Plymouth",
        "Wandsworth gov",
        "War Memorials Register",
        "We Relate",
        "West Cornwall Circuit",
        "Wikepedia, Google Maps",
        "Wiki",
        "Wikiopedia",
        "Wikipedia",
        "Wikipedia Visionofbritain.org.uk",
        "Wikipedia and Gazetteer",
        "Wikipedia, Google Maps",
        "Wikipedia/UK Genealogy Archives",
        "Wikishare",
        "Wikishire",
        "Wiltshire and Swindon History Centre",
        "Woodland Trust",
        "achurchnearyou.com",
        "ancestry",
        "archiuk.com, Google Maps",
        "bench-marks.org.uk",
        "breakspear crematorium",
        "british-history.ac.uk, Google Maps",
        "britishlistedbuildings",
        "britishplacenames.uk",
        "church web site",
        "discovery national archives",
        "error, disable",
        "gazetteer",
        "gazetter of British Place Names",
        "genuki",
        "geograph.org.uk",
        "geohack",
        "getoutside",
        "getoutside-ordnance survey",
        "getoutside.ordnancesurvey.co.uk",
        "getoutside.ordnancesurvey.co.uk/",
        "go",
        "google",
        "google maps",
        "greenford365",
        "grid reference finder",
        "gridreferencefinder",
        "hidden London",
        "historicengland",
        "historicengland.org.uk",
        "historicengland.org.uk, Google Maps",
        "http://www.tynehamopc.org.uk/off-limits/south-egliston/south-egliston-house/",
        "https://coflein.gov.uk/en/site/407677/",
        "https://en.wikipedia.org/wiki/Ballycastle,_County_Antrim",
        "https://en.wikipedia.org/wiki/Hundredsbarrow_Hundred",
        "https://en.wikipedia.org/wiki/Llanfachraeth",
        "https://en.wikipedia.org/wiki/Willesden",
        "https://en.wikisource.org/wiki/1911_Encyclop%C3%A6dia_Britannica/Sialkot",
        "https://gazetteer.org.uk/results?type=em&place=rake&loc=set",
        "https://gb.geoview.info/stoke_knap",
        "https://mapcarta.com/",
        "https://mapcarta.com/W548688334, Google Maps",
        "https://myyorkshiredales.co.uk/",
        "https://visionofbritain.org.uk/descriptions/2045000",
        "https://visionofbritain.org.uk/place/17290",
        "https://visionofbritain.org.uk/place/20576",
        "https://visionofbritain.org.uk/place/20659",
        "https://visionofbritain.org.uk/place/20736",
        "https://visionofbritain.org.uk/place/3743",
        "https://visionofbritain.org.uk/place/3770",
        "https://wiki.fibis.org/ google maps",
        "https://www.british-history.ac.uk/vch/hunts/vol3/pp1-3",
        "https://www.genuki.org.uk/big/eng/HEF/Brilley",
        "https://www.genuki.org.uk/big/eng/MDX/WestminsterStJohn",
        "https://www.genuki.org.uk/big/eng/SAL/Harley",
        "https://www.genuki.org.uk/big/eng/SRY/Battersea/StMary",
        "https://www.genuki.org.uk/big/eng/SRY/Lambeth/StMary-at-Lambeth",
        "https://www.genuki.org.uk/big/sct/ABD/Crathie",
        "https://www.genuki.org.uk/big/sct/ABD/Rhynie",
        "https://www.genuki.org.uk/big/sct/ANS/CortachyAndClova",
        "https://www.genuki.org.uk/big/sct/ARL/Coll",
        "https://www.genuki.org.uk/big/sct/ARL/KilmoreAndKilbride",
        "https://www.genuki.org.uk/big/sct/ARL/LismoreAndAppin",
        "https://www.genuki.org.uk/big/sct/ARL/SaddellAndSkipness",
        "https://www.genuki.org.uk/big/sct/BUT/Rothesay",
        "https://www.genuki.org.uk/big/sct/INV/Abernethy",
        "https://www.genuki.org.uk/big/sct/OKI/Walls",
        "https://www.genuki.org.uk/big/sct/PER/Liff",
        "https://www.genuki.org.uk/big/sct/SHI/Walls",
        "https://www.genuki.org.uk/gaz/INV/DuthillandRothiemurchus",
        "https://www.genuki.org.uk/gaz/MDX/RollsLiberty",
        "https://www.genuki.org.uk/gaz/MDX/boundary/17945",
        "https://www.genuki.org.uk/gaz/OKI/KirkwallandStOla",
        "https://www.genuki.org.uk/gaz/PER/KinlochAndLethendy",
        "https://www.red1st.com/",
        "https://www.thenorthernecho.co.uk/history/9604365.boar-blimey/",
        "https://www.townlands.ie/",
        "irelandlookup.com, Google Maps",
        "littleealinghistory",
        "londontown.com",
        "mapcarta",
        "mapit",
        "megalithic.co.uk",
        "mindat.org",
        "nationalarchives",
        "onefivenine explore india",
        "ordnance survey",
        "places of Worship in scotland",
        "rbkc.gov",
        "southwark diocese",
        "streetcheck.co.uk Google Maps",
        "streetmap.co.uk, Google Maps",
        "visionofbritian",
        "wiki",
        "wiki.fibis",
        "wikimapia.org",
        "wikipedia",
        "wikishire",
        "www.latlong.net/"
