### ISSUE TITLE
Amend every ‘Gazetteer’ entry with an url to ‘Gazetteer of British Place Names’ 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1360]

**Comment by geoffj-FUG** [comment]
The purpose of this is to sort out the spurious entries that have appeared in the Gazetteer.
Someone has used Gazetteer as a way of getting around a source. They have not been putting in a url. 
If we can change the source to the Academically correct Gazetteer of British Place Names for those entries that look correct then I can identify the other entries and fix them. 
It also means that we can display the correct reference if the References ever become available to researchers and avoids a future problem.
Geoff

**Comment by AnneV-Learn** [comment]
Deployed to production and rake task to make the updates has been run (see #1382)

**Comment by AnneV-Learn** [comment]
Closing
