### ISSUE TITLE
Create New FreeCEN2 Place dialogue fails to respect current county selection

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeCENMigration#1361]
Although it says, prominently:
Creating a New Place in Cumberland (CUL) 
the relevant county is _not_ selected in the drop-down list. If you go ahead and complete the entry without re-selecting your county, it complains that no county has been selected when you try to save your work.

**Comment by Captainkirkdawson** [comment]
We deliberately removed a preselection because too many coordinators were creating the place in the wrong county; specifically they were creating it in their county. So we make it a deliberate action.

**Comment by richardofsussex** [comment]
In that case I understand why you made the change. (Sigh - why can't people use the system properly.) However, in that case it should just say "Creating a New Place".

**Comment by Captainkirkdawson** [comment]
Happy to make that change

**Comment by Captainkirkdawson** [comment]
Change made and deployed
