### ISSUE TITLE
Write a collection management suite for the source field of the Gazetteer

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1362]
Currently the source field is a free form string field with no controls.
@geoffj-FUG has identified a requirement to control limit the content to a set of predefined values that are established by the data manager and system administrators.
This requires the ability to create, edit and destroy entries in the collection.
It also requires that the create and edit of the freecen2_place be changed to a selection from this new collection.
It is suggested we name the collection freecen2_place_source.
This has been used for a number of collections in FreeREG for example the denominations collection as well as the gap reasons.
There are 299 unique values in the field currently which is bad news!! See Extract a list of unique values in the sources field of the Gazetteer collection #1359

**Comment by AnneV-Learn** [comment]
@geoffj-FUG are you able to supply me with a list of the entries that you want to see in the source selection dropdown

**Comment by geoffj-FUG** [comment]
Anne
I need to go through a very long list. It will be a couple of days before I have shortened it down.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG of course - no problem.

**Comment by geoffj-FUG** [comment]
Anne

 

Sorry this took so long.

 

I have narrowed the list down to some sound primary sources relevant  to the census period. They are in the attached spreadsheet (I have set the filter so only the ones that we need are visible). 

 

When you make the changes can you make the entry into the web site field compulsory please? I have a lot of them to fix.

 

Geoff

**Comment by AnneV-Learn** [comment]
Thanks @geoffj-FUG but no spreadsheet was attached - unless I am not understanding how to see it.

**Comment by AnneV-Learn** [comment]
@Captainkirkdawson should the deployment of this one happen after you have finished the Gazetteer issues you are dealing with (#1367 - 1339, 1360)?

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn @geoffj-FUG  Should not have any impact **unless you are writing and running rake tasks to change the content of current fields then it would be a disaster**. If it just imposes a control on what that field contains in future edits there will be no impact.

**Comment by AnneV-Learn** [comment]
@Captainkirkdawson Ok thanks Kirk

**Comment by AnneV-Learn** [comment]
Deployed to Test3 - now ready for testing.
The management of Place Sources is restricted to data manager and system administrator roles - appears in 'My Actions' for users with either of those roles.
 Create and edit of the freecen2_place now require population of Source from drop-down of Place Sources and Website URL.
@geoffj-FUG supplied the list of of valid values for the Place Source drop-down and requested that Source and Website URL be mandatory when creating or editing freecen2_place records.

**Comment by Captainkirkdawson** [comment]
My testing was positive.
Only suggestion is to make the display of source name case insensitive

**Comment by geoffj-FUG** [comment]
Anne

 

Looks good.

 

We can run with that Can you go live, please?

 

Geoff

**Comment by AnneV-Learn** [comment]
> 

@Captainkirkdawson - sorry not clear to me what you are suggesting is changed.

**Comment by Captainkirkdawson** [comment]
@AnneV-Learn It is a minor matter. If a source is created with lower case it is displayed at the end of the list.
![test1](https://user-images.githubusercontent.com/2874694/154986463-e2c3bfe3-88e7-469e-b6ef-7bbf465ecb91.png)
![test2](https://user-images.githubusercontent.com/2874694/154986498-8799db8e-51c0-45c2-8b56-4eaf9d74f410.png)
People should not create with lower but people are people

**Comment by AnneV-Learn** [comment]
@Captainkirkdawson - Oh right - I think it is worth fixing that as you say.

**Comment by AnneV-Learn** [comment]
@Captainkirkdawson - now updated and deployed to Test3

**Comment by PatReynolds** [comment]
@Captainkirkdawson to test
