### ISSUE TITLE
Downloaded Pieces report for recent files loaded reporting issue

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1364]
It appears that the download report reports the total of parts uploaded not just the part uploaded
All rest of report is good.
![leicester part.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2e7acdee-fb88-4222-8ad7-7dc0da0dcd4d)
![lei.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/77752c0f-3ebc-4dab-a1ed-c00d805a1124)

**Comment by PatReynolds** [comment]
Now resolved and deployed.
