### ISSUE TITLE
Review Parms used in Scotland - short term

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1365]
It appears that in the Parms created from the material of Freecen1 I eliminated a number of Districts from the parms (Those where there were multiple districts  for a piece which had been manually separated when transcribing for Scotland  in freecen1 This means that a number of places in Freecen1 do not appear in Freecen2 eg. Old Machar; nor do they appear in any other place. Hence they are retrievable only by a county level search. When they are no census place is shown.
As a short term solution I propose to link the records to the main district of a piece. That will enable the records to be retrieved by a place level search and to identify a census place.
The full extent of the issue is unclear.

**Comment by Captainkirkdawson** [comment]
Old Machar records linked to Aberdeen

**Comment by Captainkirkdawson** [comment]
Savoch linked to Rhynie and Essie; Issue with New Pitsligo resolved.

**Comment by geoffj-FUG** [comment]
I have had a look at the civil parishes in ABD which are not in the PARMS. (More are missing than exist).
I have asked Margaret Singleton how the FC1 PARMS were built. (England was built manually for FC1 so I suspect that Scotland is the same).
Before we can develop the next steps in searching we need to align the existing Scotland data with the rest of the system.
Geoff
