### ISSUE TITLE
Resolve the Green source issues in Geoff's Source report

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1367]

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I have just started on these. Before going too far I think it best to evaluate what happens when we do this type of change.
The first Green entry is for Edlesborough BDF. VLD Entries exist for 1861 and 1891. 
The 1891clearly indicates that the location is in BKM although the census was BDF
![Edlesborough1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/52ec4a99-9587-4eba-9a5b-b50db8587057)
Having made the change to link to the correct Edlesborough
The search shows that Edlesborough is a place in BKM  and retrieves the record I was searching for.
![Edlesborough3.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/6a2890b2-5ef2-43e8-97d2-f6cdbe163c9a)
Personally I believe this is  OK. Do you?

**Comment by Captainkirkdawson** [comment]
Searching for a 1861 entry in BKM Edlesborough is also successful
![Edlesborough4.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2508f55c-c53f-4636-999f-7d369a528c12)
And to be absolutely clear there is no option to search for Edlesborough in BDF 
![Edlesborough5.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/5c6728e2-593e-46d6-9132-91934cfe96f8)

**Comment by geoffj-FUG** [comment]
Kirk

 

Looks good to me.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG will proceed. There are 177 corrections it will take a minimum of 20 hours active time to do these; likely a week

**Comment by Captainkirkdawson** [comment]
Have done 60 so far 117 left to do

**Comment by geoffj-FUG** [comment]
😊

**Comment by Captainkirkdawson** [comment]
117 done 60 left to do

**Comment by geoffj-FUG** [comment]
TY

 

Geoff

**Comment by Captainkirkdawson** [comment]
139 done that leaves the 37 in WRY

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

I am putting all the dregs into one spreadsheet so you can ignore the individual spreadsheets that I have been sending you.

 

When you are ready I can send London as nobody else can make the changes.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG London is already in progress. Rhoda has the ability to make changes

**Comment by Captainkirkdawson** [comment]
I have completed the green actions to the best of my ability.

Any further action requests should be done in other stories

**Comment by geoffj-FUG** [comment]
Kirk

 

Thank you.

 

We sent them to her in the first place but she said she didn’t have access.

 

Anyway it’s all good now.

 

Geoff
