### ISSUE TITLE
Colour of donate

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1371]
Is this the correct colour
![colour.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/dea7d319-973b-40da-bc79-f6e6293d8a97)

**Comment by AlOneill** [comment]
@Captainkirkdawson no. The updated colours (one CSS file) were sent to @Vino-S and are now in use on REG t3, but not yet on the other sites. The text has been moved to above the button though.

**Comment by PatReynolds** [comment]
Asset pipeline is awaiting deployment.

**Comment by Captainkirkdawson** [comment]
@Vino-S deployed latest CEN code to t3 and  ran precomile on t3 but colour is teal. Is that what was expected?

**Comment by AlOneill** [comment]
@Captainkirkdawson Yes, I was asked to make the button Teal for all 3 projects.

**Comment by Captainkirkdawson** [comment]
TY @AlOneill Guess we are good to go @Vino-S
