### ISSUE TITLE
Update Help page for new Records section pages

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#1372]
Have received updated text from @AnneV-Learn:

"Select RECORDS from the main menu to see statistics relating to the number of census Pieces currently in the database for each census year and details of recent additions (i.e. Pieces added to the database in the previous 30 days). Censuses are broken into Pieces by the National Archive (a Piece consists of a related set of census pages). From here you can choose a county and view the statistics for that county or select a specific place in the county and view that detail. At the County and Place level you can view details of the Pieces (including Civil Parish names). Where a Piece is online (i.e. has been transcribed by our volunteers and uploaded into the database) you can also get a list of names (surnames/forenames) in the database. We hope this detail will help you to refine your SEARCH criteria to get the best from the database."

Work in progress on [DRAFT Help](https://test3.freecen.org.uk/cms/draft-help).

**Comment by AlOneill** [comment]
@AnneV-Learn With a few tweaks to the text as given, the 'Database contents' section has been updated on t3:
https://test3.freecen.org.uk/cms/draft-help#dbContents

**Comment by AnneV-Learn** [comment]
Thank you @AlOneill, it looks good to me

**Comment by AlOneill** [comment]
Page promoted. It is sync-ready.

**Comment by AnneV-Learn** [comment]
Looks ok to me so probably ready for deployment now.
