### ISSUE TITLE
Update FreeCEN1 page to indicate that FreeCEN2 is now more complete than FreeCEN1

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1374]
See also #617

**Comment by PatReynolds** [comment]
@PatReynolds to write the text, @Vino-S to implement

**Comment by PatReynolds** [comment]
Text to be placed on FreeCEN1 homepage: https://drive.google.com/file/d/1RteHTnLjojazRPTlEDOtAgW0IBBh2WCx/view?usp=sharing - the text is to go where the purple "writing" is - text size at least as large as "UK Census Online".

Draft text sent to committee 27/6/2022

**Comment by PatReynolds** [comment]
Hmm .. could have sworn I'd written and circulated text - but can't find so new text here: https://docs.google.com/document/d/1Rthmu_W8Y6ECAoC_2nb33xHlESIca_f1irHeDDisB2k/edit?usp=sharing please let me know if the link does not work for you.

**Comment by DeniseColbert** [comment]
@DeniseColbert @AnneV-Learn and @vino have reviewed and combined text is good to go.

Vino will place this prominently on the FreeCEN1 Home page.

**Comment by DeniseColbert** [comment]
Geoff and Denise to look at test and live FC1 to see that these changes are OK

**Comment by DeniseColbert** [comment]
Hi Vino, FreeCEN1 home page changes are good, but could you make this (Please visit www.freecen.org.uk to search. By using this website you may be missing what you are looking for! It has not been updated for over 3 years. The database has grown by 9% - 3,646,742 records on the new website and is growing every day.) stand out a bit more by center-aligning it and putting some padding at the sided please?

**Comment by Vino-S** [comment]
Hi @DeniseColbert ,
Made the suggested changes. Please have a look and let me know your feedback

**Comment by DeniseColbert** [comment]
Done, closing
