### ISSUE TITLE
Transfer www.freecen.org.uk to FreeCEN2  release 11-13.12.18

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#138]
Make FC2 = www.freecen.org.uk, and FC1 freecen1.freecen.org.uk

Needed by #269
Needed by #387
Needs #537

Economic 4, Urgency 6, strategic 9, cost ?5 Priority-24

**Comment by PatReynolds** [comment]
Although this is planned for phase 1.4 (i.e. after search features on FC2 are as comprehensive as those on FC1, it occurs to m that we might want to flip now, and have the citation generator permanent urls be of the "www.freecen.org.uk" format, rather than as 'freecen2.freecen.org.uk' format - the reason being (a) saves a bit of effort to do once, rather than do and change, but mostly because the whole point of citations and permanent urls is so that researchers can provide a link to a source ... and if we use the FC2 url, it won't be truely permanent.

Thoughts welcome! @benwbrum @FreecenBren @sudaraka94

**Comment by PatReynolds** [comment]
Agreed - make the switch (but keep content as it is now, until all transferred to FreeCEN2

**Comment by richpomfret** [comment]
@PatReynolds any other essential tasks we may wish to complete before we do this e.g. ensuring Adsense/adverts are functioning correctly or Amazon is setup? I guess it would 'be nice' if we get the lovely citation generator feature live in time for this too - we can add it to the list of 'why you will love the new freecen' reasons to use it over FC1. :)

**Comment by PatReynolds** [comment]
New URL channels will be needed on FC2 - @smrr723 may be best placed to set them up.  I don't think it matters for Amazon.

**Comment by smrr723** [comment]
Yes, easily done @PatReynolds once the domain has been changed over.

**Comment by PatReynolds** [comment]
Speaking with Chris (newsletter editor) he suggests this is done in the 11/13 December release of FC1.  He will put out message to in his newsletter.

**Comment by richpomfret** [comment]
@lemon-ukgen what will be required on oyour side for this?

**Comment by lemon-ukgen** [comment]
Mostly we shuffle the HAProxy configuration around so that `www.freecen.org.uk` lands on the `cen2_*` backends. We'll create a DNS record for `freecen1.freecen.org.uk` and use that for the `cen_*` backends.

Have we considered redirects on FreeCEN2 for FreeCEN1 URLs that people have bookmarked? Or just going with the 404 ("Missing Page") boilerplate?

**Comment by PatReynolds** [comment]
Hi @lemon, looking at analytics, it seems that people start in a very limited number of places (landing page) and start new sessions (starting page)  in a very limited number of pages.  I think the cookie page is due to people not activating tracking until they've done so on the cookie page.  But we do need to ensure that freecen.org.uk/cgi/pl goes to freecen.org.uk (i.e. to the FC2 home/search page).  
![freecen1 analytics dec 2018](https://user-images.githubusercontent.com/6338822/49589292-ea6d2c00-f960-11e8-961c-07ad78d9b838.JPG)

**Comment by richpomfret** [comment]
Shall now close. Can create new stories for any old links which may not be there yet.
