### ISSUE TITLE
Scottish shipping

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1381]
Margaret reported  a SCS file in the ANS directory, HS612999 unloaded.
@PatReynolds assigned to @rhodamackenzie 
@rhodamackenzie reported shipping in Scotland having no pieces in FC2
@Captainkirkdawson confirmed those findings and in addition found that the other 7 SCS pieces while on line were assigned to other counties such as Bedfordshire.
He concluded: 
It is clear that there is no piece structure for Scotland. I will have to create one and then link the processed vld files into it; likely take a week.
Then we can reload the missing one that is sitting in ANS.
No attempt should be made to reload or somehow process SCS vld files until this work is completed.

**Comment by Captainkirkdawson** [comment]
@rhodamackenzie The misplaced Scottish Shipping files have been placed in SCS. SCS is now searchable with 2 places. Now to find out the issue behind the one in ANS

**Comment by Captainkirkdawson** [comment]
@rhodamackenzie Located and loaded the missing file into its proper place in SCS.
You can now report To Margaret and Brenda that the issues surrounding SCS and ANS have been resolved.

**Comment by DeniseColbert** [comment]
Complete: closing
