### ISSUE TITLE
Rake to list Freecen2_place sources not in Freecen2_place_sources list

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1382]
Rake to list Freecen2_place sources not in the recently deployed Freecen2_place_sources so that a further rake task can automatically set to the appropriate value from Freecen2_place_sources

**Comment by AnneV-Learn** [comment]
Rake to list freecen2_place sources not in  Freecen2_place_sources and rake to update all freecen2_place records with source = 'Gazatteer' to 'Gazetteer of British Place Names' ready for deployment.

**Comment by AnneV-Learn** [comment]
Deployed to production and both rake tasks run. Output from second rake task emailed to @geoffj-FUG

**Comment by AnneV-Learn** [comment]
@geoffj-FUG has provided spreadsheet of the updates that can be done programmatically. Rake to do these updates written and ready to deploy and test on Test3

**Comment by AnneV-Learn** [comment]
Successfully tested on Test3.

**Comment by DeniseColbert** [comment]
@Vino-S to deploy before @AnneV-Learn goes away for a few weeks

**Comment by AnneV-Learn** [comment]
Deployed to production and P1 updates have run.
@geoffj-FUG informed.
