### ISSUE TITLE
Empty link in header as part of the logo markup

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#1383]
The main problem is that **the logo is an empty link**. We need to add something to identify the link destination for a non-sighted user: it need not be a heading

The other sites have an `h1.accessibility` element as a child of the logo. FreeCEN does not. However, …

… It makes more sense, I believe, to make it a simple link to the main page, which is where the `href` points to. The alternative, if the link to SEARCH is present in every main navigation, is to remove the link from the logo.

**Comment by AlOneill** [comment]
FreeREG has this:

`<a class="site__header__logo  icon__freereg" href="/">
    <h1 class="accessibility">FreeREG | Free Parish Register Records</h1>
</a>`

FreeBMD has a shorter version:

`<a class="site__header__logo icon__freebmd" href="/">
        <h1 class="accessibility">FreeBMD</h1>
</a>`

What do we want for FreeCEN? Something like: FreeCEN: free census records ?

Also, what is our policy for app pages? Should they all begin with a level one heading (which could be made invisible to sighted users) to match the Refinery pages?

**Comment by AlOneill** [comment]
@Vino-S I could not hear what you were saying the Scrum (and apologies for interrupting you) — what are your thoughts? Please note the amended description — it describes the problem more accurately.

@PatReynolds et al. — apologies for not stating the main problem more clearly from the outset.

**Comment by Vino-S** [comment]
@AlOneill ,
I was just saying that the `h1.accessibility` in  will be available for the screen-readers. 
However as I understand the issue, we might have to remove the h1 tag from the logo.


We can go with the the first solution suggested by Alison. Because I believe most users have tendency use Logo to navigate to Home page.

**Comment by AlOneill** [comment]
@Vino-S thanks.
So, we can put a `span.accessibility` in the link that simply says "FreeCEN search" or "FreeCEN search page". Although it is the home page, I think that saying it is the search (page) is more helpful.

No `h1` element in the header, but ensure there is an `h1` on every app page, even if it is hidden from sighted users or the size is reduced using one of .beta, .gamma, etc. or it is prettified with .title.

**Comment by PatReynolds** [comment]
@Vino-S to take a look.

**Comment by AlOneill** [comment]
@Vino-S  I think the empty link should contain a `span.accessibility` and not an `h1`

The span should contain either 'FreeCEN' or 'Search FreeCEN' — I'm not sure which would be more appropriate.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by PatReynolds** [comment]
Could you test, please @AlOneill

**Comment by AlOneill** [comment]
@PatReynolds @Vino-S looks good
