### ISSUE TITLE
Remove True / False choice from Validation edit entryscreen

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1384]
At the bottom of the Validation edit screen there is a Record valid True False choice. If the Validator selects true the changes are not tested.
This creates the risk that a Validator can cheat the system by entering ann invalid Alternative POB (i.e. not on the Gazetteer and select True. This puts the invalid record into the system and no match will ever be achieved on a POB search.
The default value of this choice is False. I propose that we simply hide the choice so that it cannot be used. This means that all alternative POBs will be tested and the loophole closed. 
Once the alternative POB has been tested it is simply promulgated and accepted on the main screen.
I have just validated a whole piece without using this choice and I have had no problems doing it like that.
This change will increase our data integrity.
Geoff

**Comment by geoffj-FUG** [comment]
I have been updating the Handbooks. The Transcribers and Proofreaders Handbook is online. I have now almost finished the Addendum for Validators. The new version takes into account Story #1384.

It involves hiding an entry on a form. No coding is required as the result will be the default setting. I need to remove the alternative ‘true’ setting which is creating a loophole that allows Validators to force incorrect data into the system. The process is not affected other than removing a short cut option.

Is it able to be done, please? I will have the new Handbook version available this week.

Geoff

**Comment by PatReynolds** [comment]
It is useful for testing purposes, so will be hidden from all but SysAdmin and people in Technical.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this is ready for testing on Test3 now. 
Modified so that when editing a record during validation only users with role of system_administrator or technical will have the option to change the 'Record valid' flag (as this is useful for developers when testing etc). All other users will not be able to change the flag.
For them it will look like this (i.e. display only):
![Screenshot 2022-03-25 at 08.46.31.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/ce7325d0-86fe-4662-a5c5-df79a6137cc7)

**Comment by PatReynolds** [comment]
@geoffj-FUG have you been able to test this?

**Comment by geoffj-FUG** [comment]
Tested OK. 

 

I thought I sent a message asking if it could be hidden entirely rather than greyed out. It seems to be missing.

 

There is an alternative to put a note “for system admin and technical  use only” next to it. That stops people reporting the greying out as a problem.

 

 

Geoff

**Comment by AnneV-Learn** [comment]
Ok thanks @geoffj-FUG I’ll take a look at that when I’m back next week

**Comment by AnneV-Learn** [comment]
Ok @geoffj-FUG updated code has now been deployed to **Test3**. It should be entirely hidden from all users other than those with System-administrator or technical role.

**Comment by geoffj-FUG** [comment]
Anne

 

Looks good.

 

This can go live.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG - deployed to production along with new Validators Handbook. I think this story can be closed now.

**Comment by geoffj-FUG** [comment]
I have just run about 50 entries through it in production with no problems.
This story can now be closed.

**Comment by geoffj-FUG** [comment]
Anne

 

This screen Works well. 

 

I have been validating without using the option for a while now and so I am sure about the functionality.

 

I notice that it is greyed out. Is it possible to hide it completely? Otherwise people may start to report it as not working.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG are you sure users will not want to see if the record is currently valid or not? We could add (for information only) next to 'Record Valid'  field name for all but system_administrator/technical users.

**Comment by geoffj-FUG** [comment]
Anne
The true false was an extra keystroke and subject to abuse. In addition it didn't mean much to  the average validator. 
Record valid simply means that it has been validated (the true/false column in the csv download during validation).
The override button has replaced this. It allows the validator to override the system when there is more than one item to look at and makes it very clear that the validator is making a decision.
Once a record is incorporated all flags are true. So it does not affect the user.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I am a bit mystified by this now. Looking back at the code for the form, the 'Record Valid' item should not be showing for anyone at all. It was removed when the Override Warnings button was provided (#1424). I have just tested on my local installation (which is running the current software version) and on Test3, neither have the 'Record Valid' item showing when editing a record with warnings. Are you still seeing it?

**Comment by geoffj-FUG** [comment]
Anne,
If you download a csv file during validation the true/false flag downloads with it. 
When the file is incorporated the count of false flags must me 0.
Once a file is Incorported the flag is not needed. To me it is transitory. It appears when we select the Validate Action and is no longer needed once a file is Incorporated. It is only part of the Validation process.
Geoff

**Comment by AnneV-Learn** [comment]
Sorry @geoffj-FUG still a bit unsure what you want here.
Are you asking for the 'record_valid' column to be excluded from the 'Download File' output if the file has already been incorporated?
If not - would you please include some screenshots of the pages that you want changing.
