### ISSUE TITLE
225970602 Edit profile ID (Ali)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1385]
Issue reported by **AH001** at 2022-02-28 09:36:42 UTC
Time: 2022-02-28T09:35:07+00:00
Session ID: 30afbb1c6186bf61da6089e7f2e2d1a2
Problem Page URL: [/userid_details/my_own](/userid_details/my_own)
Previous Page URL: [https://www.freecen.org.uk/manage_resources/new?locale=en](https://www.freecen.org.uk/manage_resources/new?locale=en)
Reported Issue:
How do we set "Do not acknowledge my contributions" to TRUE please?    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
There is currently no method.
That is because there is no automatic system of recognizing the person who transcribed a file. 
It is a purely manual system which is rarely if ever used as it requires coordinator input.
Nor is the contribution recognized publicly

**Comment by suffolkroots** [comment]
Completely at odds with FreeREG system where transcriber is recognised by files in their profile?

**Comment by Captainkirkdawson** [comment]
True. They work in totally different ways and have done for 20 years

**Comment by PatReynolds** [comment]
No public recognition on CEN so closing.
