### ISSUE TITLE
Errors reported in ErrBit for Freecen2_contents

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1387]
Resolve errors reported in ErrBit for Freecen2_contents

1.undefined method `unique_forenames' for nil:NilClass - (app/controllers/freecen2_contents_controller.rb:142→ place_names)

2. undefined method `[]' for nil:NilClass - (app/controllers/freecen2_contents_controller.rb:56→ place_index)

3. undefined method `count' for nil:NilClass - (
app/controllers/freecen2_contents_controller.rb:155→ place_names)

4. undefined method `[]' for nil:NilClass - (app/controllers/freecen2_contents_controller.rb:85→ piece_index_setup
app/controllers/freecen2_contents_controller.rb:97→ display_pieces_by_status)

5. undefined method `each' for nil:NilClass - (app/helpers/freecen2_contents_helper.rb:4→ contents_check_for_partials
app/views/freecen2_contents/county_index.html.erb:72→ block in _app_views_freecen__contents_county_index_html_erb___4472978766823227229_17328601160
app/views/freecen2_contents/county_index.html.erb:69→ each
app/views/freecen2_contents/county_index.html.erb:69→ _app_views_freecen__contents_county_index_html_erb___4472978766823227229_17328601160)

**Comment by DeniseColbert** [comment]
Done, closing
