### ISSUE TITLE
226495919 Validation resetting (Geoff)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1388]
Issue reported by **somt.cen** at 2022-03-06 11:31:59 UTC
Time: 2022-03-06T11:28:52+00:00
Session ID: ff0166dbe8ca7d12ec34dc78f5f8c4c5
Problem Page URL: [/freecen_csv_files/62206921f493fd3c9df6c555?locale=en](/freecen_csv_files/62206921f493fd3c9df6c555?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen_csv_entries?locale=en&type=War](https://www.freecen.org.uk/freecen_csv_entries?locale=en&type=War)
Reported Issue:
I am validating Somerset RG13_2270. When I reprocess the file all the true/false flags that have been validated reset to false. Validation has to be started again.
I downloaded the piece and checked the validation flags (in fact I changed a couple to true). I replaced the file online and all the validated records went back to false.
Geoff
It is in the somt.cen userid    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
This story has been created at @geoffj-FUG request.
I had replied as follows
Geoff
There have been no changes to CSVProc for some months. The validation process has not been touched for over a year. So it would appear that you are asking for a change in specification. That would be best done by adding a new story or amending an existing one.
Kirk

**Comment by Captainkirkdawson** [comment]
To which he replied 
This was a fault report. I was validating RG13_2270.
I had validated about 50 records and downloaded the file. When I uploaded the file it had set everything back to false. I validated some of it again and re-processed the file. It reset all the validated work to false again.
I have a downloaded copy from the first download and it shows the validated records as true. It was the processing that caused the problem. I have left the file in somt.cen.

**Comment by Captainkirkdawson** [comment]
There have been no changes in CSVProc validation processes since it launch 15 months ago. In that time 544 files have gone through validation without comment from coordinators or validators hence my view that this is a new requirement that needs spelling out.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG when I look at the csv file you sent me the record_valid header is offset by one column whereas the data column for the record_valid is where it should be and it is followed by a blank column. 
enumeration_district,civil_parish,ecclesiastical_parish,where_census_taken,ward,parliamentary_constituency,location_flag,folio_number,page_number,schedule_number,uninhabited_flag,house_number,house_or_street_name,rooms,address_flag,surname,forenames,name_flag,relationship,marital_status,sex,age,individual_flag,Occupation,occupation_category,at_home,occupation_flag,verbatim_birth_county,verbatim_birth_place,nationality,birth_county,birth_place,birth_place_flag,disability,language,notes,,record_valid
1,Bradford,Bradford,Bradford,-,Western Division Of Somerset,,5,1,1,,,Ford Mills,,,NEWBERY,John H,,Head,M,M,31,,Miller And Farmer,R,,,SOM,Bradford,,,,,,,,TRUE,
Hence on upload it is reading the blank column as the record_valid value which is by definition false; hence the warning.

**Comment by Captainkirkdawson** [comment]
Subsequently I unincorporated a file, reprocessed it; downloaded it and replaced it and no warnings were generated hence I see no issue.

**Comment by geoffj-FUG** [comment]
Whenever I get a query from a volunteer I check the headers. Why didn't I do it for myself?

Problem now resolved.

Geoff
