### ISSUE TITLE
GAP - a system to indicate gaps in census information

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#139]
I.e. a system to record where the census information was lost/destroyed and no longer exists

This will be used:
to tell researchers that their search will not return a result / not return a complete result
to tell transcribers and coords (in online systems) that there is no image for transcription because it does not exist
to tell researchers and coords the % of records transcribed and % available on our system for transcription, both as a percentage of all available records, and as a % of records including those now lost.

**Comment by richpomfret** [comment]
@PatReynolds let's organise a separate review to go through the new additions on FC from FR.

**Comment by PatReynolds** [comment]
https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/census-records/ gives the methodology for finding out which census pieces have been lost or destroyed

**Comment by PatReynoldsFUG** [comment]
Three pages, covering different aspects:

https://blog.nationalarchives.gov.uk/missing-from-the-census/ for information on mis-scans by TNA and similar omissions 

https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/census-records/ (section ten)

https://www.findmypast.co.uk/articles/census-for-england-wales-and-scotland-missing-pieces

**Comment by PatReynoldsFUG** [comment]
https://blog.nationalarchives.gov.uk/missing-from-the-census/ for information on mis-scans by TNA and similar omissions 

https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/census-records/ (section ten)

https://www.findmypast.co.uk/articles/census-for-england-wales-and-scotland-missing-pieces

**Comment by PatReynoldsFUG** [comment]
Closing as duplicate issue - sources of info moved to other version of this issue
