### ISSUE TITLE
226832435 Contact us page link (Linda)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1390]
Issue reported by **Linda2469** at 2022-03-10 09:00:35 UTC
Time: 2022-03-10T08:59:33+00:00
Session ID: f6afc00dc4fc16a9d79838f43c229345
Problem Page URL: [/cms/help/frequently-asked-questions-researchers?](/cms/help/frequently-asked-questions-researchers?)
Previous Page URL: []()
Reported Issue:
The contact us page link goes to a cannot be found page.     

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@Vino-S @DeniseColbert This is likely VERY urgent

**Comment by Vino-S** [comment]
Fix deployed to production.

**Comment by AlOneill** [comment]
Working as expected, although Safari is unhappy about something — have to scroll to the very bottom to get the links in the same group as "Contact us" to behave as links.

OK on Firefox, but adverts are not showing up there.

**Comment by PatReynolds** [comment]
@AlOneill are you able to look into the Safari issue?  

Firefox issue no longer an issue.

**Comment by AlOneill** [comment]
@PatReynolds the links in the footer are working as expected in Safari.

However, there are a number of issues with trying to tab through the Search form — I'll open a new issue for those.
