### ISSUE TITLE
Advert breaks layout

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#1391]
The advert at the top of the page is breaking the layout. It is fine when page loads, but scrolling down and then back up again produces this:

![advert glitch.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/c8885e27-f3e9-4153-8dc8-bec177a192e8)

**Comment by AlOneill** [comment]
In the footer, this does not look as intended either:

![advert glitch-2.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/f32f4325-a58a-473d-b4f0-09583883f14e)

**Comment by AlOneill** [comment]
I was viewing on Safari — the ads do not show on Firefox. Personalised advertising is "On".

**Comment by AlOneill** [comment]
Back in Safari, and turning "Personalised advertising"  off, fixes (ties) banner ad to bottom of page. What is going on? I'm going to stop now.

**Comment by PatReynolds** [comment]
@PatReynolds to test to ensure fix has worked.  And if not, fix it.

**Comment by PatReynolds** [comment]
Fixed, so closing.

**Comment by PatReynolds** [comment]
Fixed, so closing.
