### ISSUE TITLE
Images and Files missing from Help on production (Refinery tables)

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#1392]

**Comment by AlOneill** [comment]
The two images that should be on the Help page are present in t3 but missing from production. Also the Handbook files.

Were the Refinery Images and File tables synced along with the Pages?

**Comment by PatReynolds** [comment]
@Vino-S to take a look.

**Comment by Vino-S** [comment]
The production Refinery was synced few weeks back. 
Please have a look again and let me know.

**Comment by AlOneill** [comment]
@Vino-S The images are still missing on production from
https://www.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen

**Comment by PatReynolds** [comment]
Images now there on production.
