### ISSUE TITLE
Red correction was in error

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1393]
LAN	Farnworth	53.383333	-2.716667	TRUE	Location is Widnes. Correct entry exists. Cannot disable as has search records	done
LAN	Farnworth (Kearsley)	53.545468	-2.399881	FALSE	Place name amended. Source added. 	

Unfortunately the original linkages had all freecen_pieces and therefore freecen2 pieces linked to LAN	Farnworth	53.383333	-2.716667; In reality some should have pointed to  LAN	Farnworth (Kearsley)	53.545468	-2.399881.

We will have to unscramble the LAN	Farnworth	53.383333	-2.716667 search records into the 2 Farnworth's and reconnect to LAN	Farnworth (Kearsley)	53.545468	-2.399881
This will require a unique rake task..

The issue was identified by a user in a
We have received feedback 227156809 from Corinne email corinnehmorris@aol.com at 03:02 on 2022-03-14.

The following is the information submitted On line access

issue:

Hi. I've been searching for a George Barnes born in 1797 in Little Bolton, Lancashire in the 1861 census. The "results" of the search has a "Census Place" of Widnes for him, but when I click on it and view the entry, according to the entry as listed there he was living in Farnworth in the parish of Kersley and not Farnworth in the parish of Prescot (the latter is where Widnes is). See Genuki page https://www.genuki.org.uk/big/eng/LAN/FarnworthD (Farnworth near Kersley) and https://www.genuki.org.uk/big/eng/LAN/Widnes (Farnworth near Widnes).

**Comment by PatReynolds** [comment]
@Captainkirkdawson to unscramble.

**Comment by Captainkirkdawson** [comment]
Task written and being tested on test3

**Comment by Captainkirkdawson** [comment]
Corrections applied to production.
