### ISSUE TITLE
227898084 error trying to replace RG12_2348 for user Hopkinal (John)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1396]
Issue reported by **johnt** at 2022-03-22 17:01:24 UTC
Time: 2022-03-22T16:57:43+00:00
Session ID: 42e850254d7abc8c7b998455b192ad01
Problem Page URL: [/freecen_csv_files/my_own](/freecen_csv_files/my_own)
Previous Page URL: [https://www.freecen.org.uk/manage_resources/new?locale=en](https://www.freecen.org.uk/manage_resources/new?locale=en)
Reported Issue:
The following message was received
Subject: Hopkinal/RG12_2348.csv processing encountered serious problem at 2022-03-22 12:17:48 +0000

Alison:
We are sorry but the file and its records were not processed. The processing log follows and should contain a reason.
Started on the file RG12_2348.csv for Hopkinal at 2022-03-22 12:17:48 +0000.
Working on Tardebigg for 1891, in WOR.
undefined method `<' for nil:NilClass
["/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:777:in `process_header_fields'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:365:in `a_single_csv_file_process'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:82:in `block in activate_project'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:78:in `each'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:78:in `activate_project'", "/home/apache/hosts/freecen2/production/lib/tasks/build.rake:688:in `block (2 levels) in '", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `block in execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `each'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/airbrake-11.0.1/lib/airbrake/rake.rb:19:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'", "/usr/local/lib/ruby/2.6/monitor.rb:235:in `mon_synchronize'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/exe/rake:27:in `'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/bin/rake:23:in `load'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/bin/rake:23:in `'"]
The CSVProcessor crashed please provide the following information to your coordinator to send to the System Administrators
If you do not understand the reason please ask your coordinator for assistance.
The FreeCEN Team
    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
John
The problem is quite simple.
The header is incorrectly formatted. The column for rooms (after house_or_street_name  and before address_flag) does not have a header. It is blank.
enumeration_district,civil_parish,ecclesiastical_parish,where_census_taken,ward,parliamentary_constituency,sanitary_district,location_flag,folio_number,page_number,schedule_number,uninhabited_flag,house_number,house_or_street_name,,address_flag,surname,forenames,name_flag,relationship,marital_status,sex,age,individual_flag,occupation,occupation_category,occupation_flag,verbatim_birth_county,verbatim_birth_place,nationality,birth_county,birth_place,birth_place_flag,disability,language,notes

We will look to see if we can make the code more robust. The transcriber can fix by putting in the rooms column header. 
Kirk

**Comment by Captainkirkdawson** [comment]
Requirement to to make the csv processor generate an error message and exit cleanly.

**Comment by AnneV-Learn** [comment]
Modifications have been deployed to Test3.
@Geoff-FUG are you able to test please?

**Comment by DeniseColbert** [comment]
@geoffj-FUG did you get a chance to test this?

**Comment by geoffj-FUG** [comment]
I referred this one to John Topliss for testing. He reported it and I have not beenn across it.

Geoff

**Comment by PatReynolds** [comment]
Waiting for John to comfirm success/failure.

**Comment by DeniseColbert** [comment]
Leaving this here until John Toplis has tested.

**Comment by DeniseColbert** [comment]
Decided to deploy and see if John has any feedback in general use

**Comment by DeniseColbert** [comment]
Done, closing
