### ISSUE TITLE
228045825 Warning on age of scholar (Ali)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1398]
Issue reported by **AH001** at 2022-03-24 10:03:45 UTC
Time: 2022-03-24T10:01:28+00:00
Session ID: 4f071354a432f362b21b94d3d1f5ea3e
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freecen.org.uk/cms/refinery/login](https://www.freecen.org.uk/cms/refinery/login)
Reported Issue:
Warnings are generated for age of scholar if apparently too young or too old, but if entry of n months, ie under one year, warning is not generated. This was reported some time ago in test3.    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
Code updated and deployed to Test3.

**Comment by PatReynolds** [comment]
@geoffj-FUG to test

**Comment by geoffj-FUG** [comment]
I have tested this for a range of ages including years, months and days and it is now working correctly.
This can be moved to production.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this has now been deployed to the production environment.
