### ISSUE TITLE
Can we redirect https://www.freecen.org.uk/freecen_coverage to https://www.freecen.org.uk/freecen2_contents?locale=en?

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1400]
TNA sends people to https://www.freecen.org.uk/freecen_coverage from this page: https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/census-records/

**Comment by PatReynolds** [comment]
@DeniseColbert to contact Lemon re this issue

**Comment by DeniseColbert** [comment]
Lemon is now on the case

**Comment by lemon-ukgen** [comment]
That's done. Note that the old FreeCEN1 URL https://www.freecen.org.uk/statistics.html used to direct to https://www.freecen.org.uk/freecen_coverage, so I updated that too.

```
% curl -I https://www.freecen.org.uk/freecen_coverage
HTTP/1.1 301 Moved Permanently
location: https://www.freecen.org.uk/freecen2_contents
```
