### ISSUE TITLE
Add CSV download feature to Search Statistics

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1401]
The table on this page: https://www.freecen.org.uk/freecen2_search_statistics has day-by-day number of searches performed in FreeCEN. This is info the trustees would like to see in my metrics report.

If the CSV download feature we have on Site Statistics (https://www.freecen.org.uk/freecen2_site_statistics?locale=en) could be added to the "Search Statistics" page, I could easily get the info I need.

**Comment by Captainkirkdawson** [comment]
Do not understand. There is no such capability for the researcher user. There is a print format.

**Comment by DeniseColbert** [comment]
Sorry for not being clear @Captainkirkdawson - I have added a description to the story.

**Comment by AnneV-Learn** [comment]
CSV download option added to Search Statistics page and deployed to Test3.

**Comment by PatReynolds** [comment]
@DeniseColbert to check download of VLD files and subesquent uploads of CSV files after correction are not included in the statistics.

**Comment by DeniseColbert** [comment]
@AnneV-Learn clicked Search Statistics in test3, received this error:

![image](https://user-images.githubusercontent.com/19173257/173798975-5133a14a-aa5a-4064-9dc7-2a577bbbb8e5.png)

**Comment by AnneV-Learn** [comment]
@DeniseColbert - strange because it was working a few weeks ago. I’ll investigate and get back to you.

**Comment by AnneV-Learn** [comment]
@DeniseColbert the issue with the deployment to Test3 has been fixed now. 
Please note that the range of dates available for the CSV file download is limited on Test3. Search Stats are not updated daily on Test3 but this should still allow you to test the CSV file download functionality.

**Comment by DeniseColbert** [comment]
Seems to be working Anne, thank you!

**Comment by DeniseColbert** [comment]
Done so closing
