### ISSUE TITLE
228127430 Wrong report when copied file to another ID (Ali)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1402]
Issue reported by **AH001** at 2022-03-25 08:43:50 UTC
Time: 2022-03-25T08:39:22+00:00
Session ID: 2ee26e5fdae2b124dbe617fd0e07ed79
Problem Page URL: [/freecen_csv_files/623d7853f493fdff14930415/change_userid?locale=en](/freecen_csv_files/623d7853f493fdff14930415/change_userid?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen_csv_files/623d7853f493fdff14930415?locale=en](https://www.freecen.org.uk/freecen_csv_files/623d7853f493fdff14930415?locale=en)
Reported Issue:
When option to copy file to another person is selected, there is no choice of which report to generate. A new proof reader receiving full report can be overwhelmed with validation demands.     

![Screenshot](https://www.freecen.org.uk)

**Comment by PatReynolds** [comment]
@AnneV-Learn to ask Ali for more information

**Comment by AnneV-Learn** [comment]
More info received and I responded (via Feedback reply) with what I thought the current process was ie:
My understanding of the CSVProc process  is that the ‘Copy to Another Person’ is used to transfer the actual transcription file to the Proofreader or Validator, it does not ‘Re-Process’ the file. 
That having been done would the Proofreader/Validator not just find the file in the list of ‘My Files’ in ‘Your Actions’ and then  ‘Show’ and then use the  ‘Download file’ option(button) then ‘Reload file’ that downloaded file and then select the type of Report they want?

**Comment by AnneV-Learn** [comment]
Ali clarified - The ‘Copy to Another Person’ also sends an All Warnings report by email to the file recipient. 
The request is to offer options on the type of warning report that is emailed.

**Comment by AnneV-Learn** [comment]
Added dropdown where type of processing report that will be emailed to the new user can be selected. Deployed to Test3.

**Comment by PatReynolds** [comment]
@PatReynolds to ask Ali to test

**Comment by PatReynolds** [comment]
@PatReynolds to tell Ali to there is now an option, please test. (Done, 29th June 2022).

**Comment by AnneV-Learn** [comment]
@PatReynolds I had actually modified the code to provide the functionality that Ali had requested and it was ready for User Testing on Test3. Bit confused now!

**Comment by PatReynolds** [comment]
Hello Anne,  I hadn't asked Ali to test a month ago, so did today.

**Comment by AnneV-Learn** [comment]
@PatReynolds 🙂👍🏻

**Comment by AnneV-Learn** [comment]
Response from Ali was as follows:

I can't test ATM as ID list in Test3 is not up to date---I don't want to copy to an un-witting active person!

However, the option selection box is now there so I am happy for it go live, if  there is subsequently a problem I'll let you know.

**Comment by PatReynolds** [comment]
@DeniseColbert wrote 14 days ago: @geoffj-FUG is happy for Ali to copy to his UserID (SOMT.CEN) to test

**Comment by PatReynolds** [comment]
Ali's reply "I can't test ATM as ID list in Test3 is not up to date---I don't want to copy to an un-witting active person!
"However, the option selection box is now there so I am happy for it go live, if there is subsequently a problem "

**Comment by DeniseColbert** [comment]
Geoff is in touch with Ali and will follow up if not heard back next scrum.

**Comment by geoffj-FUG** [comment]
Ali is happy with the result.
This can now be deployed.
Geoff

**Comment by DeniseColbert** [comment]
@AnneV-Learn to check this is deployed and if so, close.
