### ISSUE TITLE
Statistics link on main FreeCen landing page goes to old Database Coverage pages

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1407]
Statistics link on main FreeCen landing page goes to old Database Coverage Pages![DB01E71C-435A-4488-A150-E16C0DE35CA1.jpeg](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/a1bb07a3-d280-402e-993e-e891e3c0616d)

**Comment by AnneV-Learn** [comment]
@Vino-S I have just created a pull request for fc_1407_av, could you please deploy to Test3 and let me know when that has happened.
Thanks.

**Comment by AnneV-Learn** [comment]
Tested on Test3 - seems ok now.

**Comment by AnneV-Learn** [comment]
@PatReynolds this can be closed now I think.

**Comment by PatReynolds** [comment]
Thanks, Anne, now closing
