### ISSUE TITLE
Differentiating between 1841 and 1851 pieces

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1410]
HO107 covers the 1841 and 1851 censuses. When we developed FC2 we were under the impression that 1-999 was 1841 and anything from 1000+ was 1851.
It is now apparent that the boundary is HO107_1465 (1841) and HO107_1466 (1851).

The code needs adjustment as the system is reporting Errors in 1841 pieces from HO107_1000 to HO107_1465 as it sees these pieces as 1851 pieces.

Geoff

**Comment by Captainkirkdawson** [comment]
I am sorry that is just not true. We have always known where the transition occurred.
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/models/freecen2_piece.rb#L122-L124

**Comment by geoffj-FUG** [comment]
Back to the drawing board on the problem that I have.
