### ISSUE TITLE
230682055 Incorrect testing of Ecclesiastical parish and ward (Geoff)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1411]
Issue reported by **somt.cen** at 2022-04-23 22:20:55 UTC
Time: 2022-04-23T22:12:31+00:00
Session ID: 9931675059ee0ae51176f554b0eebb1c
Problem Page URL: [/freecen_csv_entries?locale=en&type=Err](/freecen_csv_entries?locale=en&type=Err)
Previous Page URL: [https://www.freecen.org.uk/freecen_csv_files/my_own?locale=en](https://www.freecen.org.uk/freecen_csv_files/my_own?locale=en)
Reported Issue:
Piece HO107_1437 has been converted from a FreeCEN1 format spreadsheet and is an 1841 piece. It is reporting that the Ward is Blank and that the Ecclesiastical parish is blank when uploaded after conversion. These fields are not in the 1841 spreadsheet.
There is a copy in userid somt.cen. We still have the original spreadsheet and upload.
Geoff    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
Points to note. 
This is a Welsh file. HO107_1437 (somt.cen) in Machynlleth of MGY.
The header is correctly formatted for 1841 and does not include Ecclesiastical or Ward fields
enumeration_district,civil_parish,where_census_taken,parliamentary_constituency,location_flag,folio_number,page_number,schedule_number,uninhabited_flag,house_number,house_or_street_name,address_flag,surname,forenames,name_flag,sex,age,individual_flag,occupation,occupation_flag,verbatim_birth_county,birth_county,birth_place_flag,notes
The freecen csv processor code is located at https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/freecen_csv_processor.rb
The file has been correctly identified as 1841 for  Machynlleth of MGY.
The processor code that extracts the location fields is at
https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/freecen_csv_processor.rb#L996-L1013
The Ecclesiastical parish extraction code is at
https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/freecen_csv_processor.rb#L1027-L1032.
The bug is immediately apparent in line 1028. We should also test for the Welsh counties and 1841 and not attempt to extract the Ecclesiastical parish. 
The Ward extraction code  in https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/freecen_csv_processor.rb#L1039-L1044
has a similar bug in line 1040.  We should be testing for the Welsh county codes as well as the English
Fix these 2 bugs and the problem should be solved.
I will not be doing. Either Anne or Vino needs to become familiar with the processor.

**Comment by AnneV-Learn** [comment]
Fix deployed to Test3. @geoffj-FUG are you able to test please?

**Comment by geoffj-FUG** [comment]
Anne
I have tested this with the original file and it ran OK

I then tested it with a old format 1841 spreadsheet, uploaded it, converted and downloaded it, then reloaded it. It also ran OK.

This can therefore be moved to production.

Geoff

**Comment by AnneV-Learn** [comment]
Great - thanks for testing Geoff
Anne

On 10 May 2022, at 11:50, geoffj-FUG ***@***.***> wrote:

﻿

Anne
I have tested this with the original file and it ran OK

I then tested it with a old format 1841 spreadsheet, uploaded it, converted and downloaded it, then reloaded it. It also ran OK.

This can therefore be moved to production.

Geoff

**Comment by AnneV-Learn** [comment]
Successfully deployed to production.
