### ISSUE TITLE
231405332 Replace file error (Ali)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1413]
Issue reported by **AH001** at 2022-05-02 07:15:32 UTC
Time: 2022-05-02T07:01:42+00:00
Session ID: aea628fe939eddb0f53e91c299513d03
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freecen.org.uk/cms/refinery/login](https://www.freecen.org.uk/cms/refinery/login)
Reported Issue:
On 26/4/2022 as CC I replaced  file RG10_1471 into ID FreeCEN00905.

ID FreeCEN00905 cannot now replace this file, has tried twice, receives the message:

"You are attempting to replace a file that you do not have, lkely you are a coordinator--" etc etc.    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
Resolved by using the Delete function on the file (available to Tech Support users only) which removes any spurious links.
