### ISSUE TITLE
Complete DRAFT 'Information for transcribers' page and make live

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#1420]
There is a [DRAFT 'Information for transcribers' page](https://test3.freecen.org.uk/cms/information-for-transcribers/draft-information-for-transcribers) that looks to have some updates for CSVProc, but no note of the issue or issues it addresses.

The current (live) page has links to pages and files that are related to CEN1, but the updated info for coords page tells coords that their volunteers should not be using CEN1. So, we need to publish an updated Info for transcribers page.

Is the DRAFT page ready to be made ready for publishing? If not, what else needs addressing first?

**Comment by PatReynolds** [comment]
@AlOneill to check and remove mentions of replaced processes.

**Comment by AlOneill** [comment]
@PatReynolds I've tidied up the the [DRAFT Info for transcribers](https://test3.freecen.org.uk/cms/information-for-transcribers/draft-information-for-transcribers) page. There are two outstanding issues:

1. the highlighted sentence is very awkward — it does not make sense to me so I do not know how to fix it (other than by deleting it!) — please would you explain

![transcribing.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/0d5cc3c7-54b1-45af-bc86-4c1faad6348c)

2. the 'Image Server' sub-section seems out of place as part of 'Syndicates and Counties'. I suggest it is moved to 'Making a transcription', at least until we actually have an Image Server when it will probably justify a section of its own

Thanks!

**Comment by DeniseColbert** [comment]
@AlOneill will remove highlighted part and adjust the reference to image server.

**Comment by AlOneill** [comment]
Changes made and page made ready for publication, i.e. sync-ready.

Out of date child pages moved into own folder — status clear and old bookmarks will no longer find them.
