### ISSUE TITLE
Errbit - drill(freecen2) - The action 'show' could not be found for Freecen2ContentsController

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1421]

**Comment by AnneV-Learn** [comment]
I think this is an error generated by a Bot. There is no 'show' method in the controller nor is there a show view - which is actually correct. I will attempt to add code to trap so that it does not show up in Errbit

**Comment by PatReynolds** [comment]
Moved to ready for testing. @Vino-S to test

**Comment by AnneV-Learn** [comment]
Tested - all seems ok ie no impact on existing functionality
