### ISSUE TITLE
Errbit - Colombus(freecen2) - undefined method `[]' for nil:NilClass - 

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1422]

**Comment by AnneV-Learn** [comment]
I think this is an error generated by a Bot. I will attempt to add code to trap so that it does not show up in Errbit

**Comment by PatReynolds** [comment]
@AnneV-Learn moving to sprint backlog, please move to backlog if more appropriate.

**Comment by AnneV-Learn** [comment]
Tested - all seems ok ie no impact on existing functionality
