### ISSUE TITLE
Errbit - Colombus(freecen2) - undefined method `unique_forenames' for nil:NilClass

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1423]

**Comment by AnneV-Learn** [comment]
This may have been caused when the rake task that collects 'names' for the Records displays was not running nightly for a few days. I believe this has now been resolved.
I will attempt to add code to the Records displays to trap that situation so that it does not generate a NilClass error.
@Vino is there an easy way that I can check that the overnight rake tasks have run each day?

**Comment by PatReynolds** [comment]
Vino says: there are no checks at the moment.

**Comment by AnneV-Learn** [comment]
Tested - all seems ok ie no impact on existing functionality
