### ISSUE TITLE
Feedback issue raised by Geoff. The record shows 16 children born alive. The Warning is generated at >15. If I change the spelling of a POB I cannot save it as the 16 is tested

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1424]

**Comment by geoffj-FUG** [comment]
Anne
We need to discuss this before any work is done. I have had a look at the old vld software and how it was handled. We need to do something similar.
Geoff

**Comment by AnneV-Learn** [comment]
Ok @geoffj-FUG. I did take a preliminary look and it seemed to me that the same issue could result from any record where there was a failed check and one wanted to update the POB via the online edit. 
Can you define the required processing as per the VLD approach?

**Comment by geoffj-FUG** [comment]
Anne

 

The problem emanates from my removing the true/false option from the form. I have validated over 100,000 entries with the true / false option unavailable and have only had 3 occurrences of the problem. However, it will need to be fixed.

I do not want to reinstate the true / false as its purpose was vague to a validator and it can be used to circumvent testing on submission.

 

The solution we need is to reinstate the true option from true/false on a button next to the submit button. The button should read something like “Ignore Warning”. The process should then take the user to the propagate / accept screen as if it had been a submit. (I am not sure now whether the true / false functionality did that).

 

Any entries made by the validator should not be negated (I am happy for that to be the default for submit as well as it means that the validator may only have one letter to change).

 

I am looking for something on the button that makes it clear that the validator is ignoring the warning on the screen. It emphasises the reason they are using the button, hence suggesting ‘Ignore Warning’.

 

We should also reinstate the code to test for the hyphens in the given name and surname fields. The button will remove the problem.

 

Geoff

**Comment by AnneV-Learn** [comment]
Ok @geoffj-FUG I’ll aim to code as per your requirement above. I wonder if ‘Override Warning’ might be slightly better as to me it suggests a clearer intention to submit the data as is but you have the last word on this of course.

**Comment by geoffj-FUG** [comment]
Anne

 

I am happy with Override Warning

 

Geoff

**Comment by PatReynolds** [comment]
@AnneV-Learn I have moved this to sprint backlog, but please move to backlog if this is the wrong place for it.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I have made modifications that I hope meet your requirements and they have been deployed to Test3. Could you please Test?

**Comment by geoffj-FUG** [comment]
Anne

That works and will cover a host of problems.
I will amend the Validators Handbook and reissue that to cover the change in the image..
This can be moved to production.
Geoff

**Comment by PatReynolds** [comment]
Tested and signed off by Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this has now been deployed to the production environment.
