### ISSUE TITLE
Update FreeCEN Handbook on line and add sample completed spreadsheet.

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1427]
I have sent Anne 2 files. 

One is an updated version of the March Handbook. It has an extra paragraph which addresses a new transcribers query.
The second is a csv spreadsheet for 1881. It is a sample that new transcribers can look at to see how their spreadsheet should look. It does not have an existing link in the Handbook section of Your Actions, so that will need to be created.

Geoff

**Comment by PatReynolds** [comment]
HI @geoffj-FUG if you tell me the text and position, I'll add it (with the link to the spreadsheet).

**Comment by geoffj-FUG** [comment]
Info sent by email

**Comment by geoffj-FUG** [comment]
I now have a rewrite of the web page and 2 additional parts of the Handbook to upload as well. Will send in the next few days.
Geoff

**Comment by DeniseColbert** [comment]
This is now with @PatReynolds for upload

**Comment by DeniseColbert** [comment]
If this is reassigned in the handover, ask Geoff to re-send the handbook to whoever get it.

**Comment by DeniseColbert** [comment]
@geoffj-FUG to send bundle to Denise

**Comment by PatReynolds** [comment]
Text is now ready for proofing on Test3.  Please notes, links have not yet been made on the document.  Cou,d you proof, please, @geoffj-FUG

**Comment by PatReynolds** [comment]
Links are now live.

**Comment by geoffj-FUG** [comment]
Pat

The version on test3 is an older version. It is the one that I updated again. 

 

The set we need to upload has the attached document as the text.  The associated documents will be dated June 2022.

 

Geoff

**Comment by geoffj-FUG** [comment]
Items on test3 are still out of date.
The updated items were sent to Denise.
Geoff

**Comment by DeniseColbert** [comment]
Refinery page to check: https://test3.freecen.org.uk/cms/freecen-handbook/draft-freecen-handbook-june-2022

**Comment by geoffj-FUG** [comment]
I have checked all the links and they are OK.
Content is OK except an unwanted indent part way down at Abbreviated Handbook.
This can be deployed once the indent is fixed.
Geoff

**Comment by AlOneill** [comment]
@DeniseColbert Allow me to fix the markup that has gone awry (in more than one place, as it happens).

**Comment by AlOneill** [comment]
@DeniseColbert @geoffj-FUG 
Markup fixed. Whilst fixing it I noted some issues that will need resolving, either before publication or as soon as is feasible:
    1. the example spreadsheet is **not** a CSV file, as stated: it has the file ending .xls
    2. some downloads are set to open in a new tab, some are not — which do we want?
    3. the tone and implied audience of the text is highly variable

In addition, I suggest we remove the date from the page name (so that incoming navigation is not broken) and record the revision date within the body of the page.

**Comment by geoffj-FUG** [comment]
Cc to Denise for file.

 

Alison

 

I have attached the csv version. Perhaps we should include both versions as the xls version has the markup which is lost in the csv version.

 

Geoff

**Comment by DeniseColbert** [comment]
@AlOneill what do you recommend for downloads- new/same tab?

I think it would be fine for you to standardise the tone/audience if you're happy to?

**Comment by AlOneill** [comment]
@geoffj-FUG I will include both the CSV and the .xls versions, with a brief explanation of the differences.

@DeniseColbert My recommendation for links to downloads is to follow the guidelines that apply to all links, adding the file size to the link text. So, **open in the same tab**, state the file format and size.

OK: I will attempt to standardise the tone, and address the text primarily to transcribers.

**Comment by geoffj-FUG** [comment]
Alison

 

Open in new tab please. These are instructions so volunteers refer to them. If they open in same tab then it will use their workspace.

 

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG
This is about user control and choice. If we _set_ a link to open in a new tab, then that is what will happen — the user cannot override the setting. However, if a link is set to open in the same tab, the default behaviour, then each user can choose to open it either in the same tab or in a new tab (or window) by way of the context menu: the mechanics of this vary but it is a right-click on a typical Windows desktop setup using a mouse.

Web usability guidelines recommend that links be set to open in the same tab unless there is an overriding reason to do otherwise. FUK Genealogy policy is that the Scrum can decide to force a link to open in a new tab only if there is an overwhelming reason to do so.

**Comment by AlOneill** [comment]
I've nearly finished tweaking the Handbook page. This part is not clear for the literal part of my brain:

"**Complete FreeCEN Handbook (now obsolete for Transcribers, Proofreaders, Validators and Coordinators)**

"This is the original comprehensive guide to working with FreeCEN2. It will gradually be replaced by parts 1 to 4 of the Handbook. Most of this Handbook has now been replaced by the above documents (which are more up to date). If you download this version we suggest that you save the Handbook to your computer. It is quite large, so printing is probably not a viable option."

@geoffj-FUG If the Complete Handbook is now obsolete for "Transcribers, Proofreaders, Validators and Coordinators", who does that leave needing or wanting to use it? Does the punctuation need adjusting to clarify the meaning?

I can see parts 1 to 3 of the Handbook, but not part 4: what will it contain and who will use it? Is it currently part of the Complete Handbook or will it be new material?

Thank you!

**Comment by geoffj-FUG** [comment]
Alison,

 

I still have the data manager part to write. I also have Part 1 for Scotland and Ireland to make available. These are all covered in the complete Handbook. 

Scotland has been reviewed by Margaret Singleton so I will be able to include part 1B soon. Part 1C Ireland is written but I still need to do my final proof read.

Once all the parts are written and available then I will have the Full Handbook removed. 

 

Geoff

**Comment by AlOneill** [comment]
The DRAFT [FreeCEN Handbook page](https://test3.freecen.org.uk/cms/freecen-handbook/draft-freecen-handbook-june-2022) is now ready for review.

**Comment by geoffj-FUG** [comment]
Alison
This looks good.
However, can you amend
Once you get going, please use Part 1 of the FreeCEN2 Handbook for England and Wales or Dave's Guide for New Transcribers.
To
This can be used in conjunction with Dave's Guide for New Transcribers. Once you get going please use Part 1 of the FreeCEN2 Handbook for England and Wales.
Amend
This page has download links for the various guides that help Transcribers, Proofreaders, Validators and Coordinators in the transcription of census documents.

Introduction to FreeCEN for New Transcribers
Dave’s FreeCEN2 New Transcriber Guide
FreeCEN2 Handbook —
Part 1 — Transcriber and Proofreader Handbook, for England and Wales
Part 2 — Validator Handbook
Part 3 — Coordinator Handbook
Last updated for June 2022

Introduction to FreeCEN for New Transcribers (England and Wales)
This Introduction is suitable for New Transcribers: it is a simple guide to get you started. Once you get going, please use Part 1 of the FreeCEN2 Handbook for England and Wales or Dave's Guide for New Transcribers.

Download the Introduction Guide (PDF, 258 KB)

The Guide will appear on your Screen in Acrobat Reader (or in the browser on a Mac):

select the Download Icon (an underlined downward arrow)
you will be asked where you want to Save the Guide. Save it.
open the Guide in Acrobat Reader (or in Preview on a Mac)
select the Print Icon (or File … Print)
select your Printer
set Pages to ‘Print to All’
select ‘Booklet’
set Booklet option to ‘both sides’
set the Orientation to Portrait
select Print
The Guide will now print on 4 pieces of A4 paper back to back. These can be folded into an A5 booklet.

The various guides and Handbooks are PDF (Portable Document Format) files. Most browsers can show the contents of a PDF file directly: if not, you’ll see a dialogue box rather than the Handbook itself. Follow the instructions from step two.

Dave’s FreeCEN2 New Transcriber Guide
This Guide was written by Dave as he learnt to Transcribe for FreeCEN. It aims to explain things from the point of view of the Transcriber.

Download Dave’s FreeCEN2 New Transcriber Guide (PDF, 4.71 MB)

select the Download Icon (an underlined downward arrow)
you will be asked where you want to Save the Guide. Save it.
open the Guide in Acrobat Reader (or in Preview on a Mac)
select the Print Icon (or File … Print) (it will print on about 15 sheets of A4 back to back)
select your Printer
set Pages to Print to All
select Back-to-back (flip on long side)
set the Orientation to Portrait
select Print
Sample Completed Spreadsheet
This is the beginning of a sample transcription (about 6 pages of images). It contains a range of entries so that you, as a new transcriber, can see what a completed spreadsheet looks like.

If your spreadsheet software can open Microsoft Excel format files, .xls, then we recommend looking at that one. It has some formatting that makes it nicer to look at and so easier to read than the CSV file. In particular, the first row of every census page has been given a yellow background as per Dave’s suggestion.

Download Sample Spreadsheet (.xls, 54 KB)
or
Download Sample Spreadsheet (CSV, 12.2 KB)

Depending on your operating system and browser, you might find that you are starting at step two rather than step one:

select the Download Icon (an underlined downward arrow)
you will be asked where you want to Save the spreadsheet — save it
open the spreadsheet using your spreadsheet software (any spreadsheet software can open a .csv file)
FreeCEN2 Handbook part 1 — Transcription —
To
FreeCEN2 Handbook part 1
I will align the Titles with parts 2 and 3 when I produce the next version of part 1.
Otherwise I am very happy with this.
I will still argue that these should open in a new tab. My computer is set up to open pdf's within Google Chrome. The download file therefore overwrites the FreeCEN page. If I was not wise to the system I might get very annoyed as a new transcriber if I had to go back and  find FreeCEN every time that I downloaded my instructions. It is more friendly to open the instructions in a new tab next to my FreeCEN menu.
Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG 
OK, but I will change some clauses back from the passive to the active voice and substitute some words and phrases with an unusual vocabulary or usage — most of our Transcribers are Brits but not all have English as their everyday language. The passive voice sounds unfriendly to many (which is off-putting) and is harder to take in if you are not accustomed to it.

As for forcing the downloads to open in a new tab, that is a decision for the Scrum. Maybe we need to point out to the user that they have a choice, describing the basics of how to open a link in a new tab if they wish to do so. (Education is empowering, yes.) I would be against taking away that choice — that would annoy me! (It would also clutter the link text with the required warning.)

**Comment by geoffj-FUG** [comment]
Alison

 

It didn’t used to be a problem when all pdfs opened in Acrobat or similar. The opening within a Google etc tab has created the problem.

 

If only things remained the same!

 

Geoff

**Comment by AlOneill** [comment]
The [DRAFT FreeCEN Handbook](https://test3.freecen.org.uk/cms/freecen-handbook/draft-freecen-handbook-june-2022) page text has been updated as per Geoff's requests (as I understand them) and is ready for review. It now includes an info box on opening links in a new tab so that users know why things have changed: Windows users with a mouse, the largest and (dare I say it?!) neediest group, have the full SP.

**Comment by DeniseColbert** [comment]
@geoffj-FUG could you check this please?

**Comment by geoffj-FUG** [comment]
Alison

 

We are at cross purposes.

 

The Handbook Action should open the Handbooks page in the same tab. The Download link should be where the volunteer makes their choices.

 

So I think we are on the same page. 

 

Geoff 

 

The links should open the document in a new tab. It can then be downloaded if the volunteer chooses.

**Comment by DeniseColbert** [comment]
@geoffj-FUG to check

**Comment by DeniseColbert** [comment]
@DeniseColbert to explore tab issue with Alison

**Comment by geoffj-FUG** [comment]
This is still waiting. I understand the protocol involved in the use of tabs and the undesirability of systems opening strings of tabs across the screen.
When pdfs were automatically opened within Acrobat that was a reasonable policy. Opening in Acrobat meant that there was an additional programme in use and therefore the opened file was isolated from FreeCEN. However Acrobat is now a programme that is in its final decline as far as the generic user is concerned.
Today users are more likely to open pdf files in Microsoft Edge or Google Chrome. In fact the use of the browsers is encouraged by the Browser vendors.
If our Handbook documents open in the same tab as the open FreeCEN tab then the access to FreeCEN is overwritten. A user can have either FreeCEN or the Handbook. As they are using the Handbook to assist them to use FreeCEN this is not a practical situation.
It is imperative that the Handbook opens in a new tab so that FreeCEN access is not overwritten. This documentation must be deployed to use new tabs.
The work to update FreeCEN with these Handbook documents was done some time ago. It is now urgent as people are working from old guidelines. 
This deployment is now Urgent.
Geoff

**Comment by DeniseColbert** [comment]
@geoffj-FUG Alison will make it clear on the Handbook page in Refinery (so that transcribers will see it at the right point) how to open any link in a new tab and how to get back to the list of actions. She's also let them know that it would be easier for the handbook to be opened in a new tab. This will give users the most control and will add to their repertoire of internet skills: useful for transcribing on our websites!

**Comment by AlOneill** [comment]
@DeniseColbert @geoffj-FUG 

I have edited the guidance on the [Draft FreeCEN Handbook](https://test3.freecen.org.uk/cms/freecen-handbook/draft-freecen-handbook-june-2022) page in Refinery as per the above comment. The text now reads:

"**What has changed?**

"We have set nearly all the links on this site to open in the same browser tab rather than a new one. This puts you in control and makes it easier for all users to understand what has happened when they select a link.

"**You are in control**

"Sometimes, it makes sense to get a link to open in a new tab: you can choose to do exactly that. The details will depend on your OS (Operating System) and how you move around the page. For example, a Windows user with a mouse will right-click on the link to get a context menu. They can then choose “Open link in new tab” or “Open link in new window”.

"**Keeping a useful page available**

"The items in the main menu are links. The list of Actions on the ‘Your Actions’ page look like buttons, but they too are links. You can open a link in a new tab at will. For instance, you can open this page in a new tab from the Your Actions page; you can open any of the Handbook links on this page in a new tab. Your decision.

"Please note that the ‘Report a problem’ buttons are buttons — you cannot choose to open a new tab with them."

I hope this is now acceptable. (Specific suggestions for improvement are welcome, as ever.)

**Comment by geoffj-FUG** [comment]
Alison

Please go ahead. We can then review if we have any issues with the outcome.

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG @DeniseColbert 
Updated draft published on t3 and made sync-ready.

**Comment by geoffj-FUG** [comment]
Alison

 

I view of the changes that have happened with pdf files appearing in Google Chrome and Microsoft Edge can we change:

In Introduction for New Transcribers.

The Guide will appear on your Screen in Acrobat Reader (or in the browser on a Mac):

To

The Guide may appear on your screen in Acrobat Reader or in your Browser:

 

Can we move the You are in control box to either above the Introduction to FreeCEN for New transcribers or to the Left of it? That way people see it first and are less likely to go ahead and just read the instructions.

 

That way it becomes more prominent.

 

I am also going to copy your box into the next version of the Handbook.

 

In Handbook Part 3 can we change Download the Handbook to Download the Coordinator Handbook? 

(Mea Culpa)

 

I am happy then for this to go live. I am away for  week so just go ahead.

 

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG 
I have made the text changes you requested on t3. They will appear on the live site when the two are synced.

As for moving some or all of the contents of "Links and tabs" (I am not sure exactly how much you mean), I am reluctant to do so. The information belongs together; the blue background makes it prominent — it would be easy to change the colour if required; nothing is actually broken if they ignore it; once read and understood I believe that many users would find it annoying for the box to be always in the way as they scroll to reach a download link. As a compromise, I will place a short reminder to read the information ahead of "Introduction to FreeCEN for new transcribers".

Moving any or all of the information would be a decision for the Scrum.

**Comment by geoffj-FUG** [comment]
Alison

 

The short reminder will help. Having the Handbooks available is critical.

 

I will put a short item in Chris’ next newsletter as well.

 

Geoff

**Comment by DeniseColbert** [comment]
@AlOneill if this is sync ready could you put the Ready for Deployment label on please, and Vino can do that.

**Comment by DeniseColbert** [comment]
@geoffj-FUG to progress (close if OK)

**Comment by geoffj-FUG** [comment]
All working online OK.
Geoff
