### ISSUE TITLE
FreeCEN1 no longer working?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1429]
Yesterday and today when searching on FreeCEN1 I get this error:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at cen-web@freecen.org.uk to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by DeniseColbert** [comment]
Fixed - closing
