### ISSUE TITLE
Add "you can make suggestions for improvements (after checking that they are not already in the Roadmap) at any time via the Report a Problem button " into volunteers and coords helps

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1430]

**Comment by Captainkirkdawson** [comment]
Interesting; that was what we had expected Feedback to be used for as it provided far more responsive review than the roadmap!

**Comment by DeniseColbert** [comment]
@geoffj-FUG is happy for Ali to copy to his UserID (SOMT.CEN) to test

**Comment by PatReynolds** [comment]
@PatReynolds to send a note to Chris asking him to include in the newsletter (coming out this week).

**Comment by PatReynolds** [comment]
@cmahoneynz emailed 27 July 2022

**Comment by DeniseColbert** [comment]
Newsletter went out with this in it a few days ago- can this be closed @PatReynolds ?

**Comment by DeniseColbert** [comment]
Still needs to be added to the Help

**Comment by AlOneill** [comment]
@DeniseColbert 
I do not know what a Transcriber sees in their Actions, but the "Feedback" (not really a) button takes me to a list of feedbacks from other volunteers. I cannot see how to create a message there.

Are we talking about the Google form, FreeCEN2 Feedback? Although this is accessed from "Information for Transcribers", it seems to be for non-members. I'm confused! What have I missed?

**Comment by DeniseColbert** [comment]
Title amended to make more sense

**Comment by AlOneill** [comment]
[DRAFT Information for Transcribers](https://test3.freecen.org.uk/cms/draft-information-for-transcribers) page edited to include advice detailed above.

There is no obvious place to include the advice on the Coordinators page, but as we encourage Coords to be familiar with the Info for Transcribers (and unnecessary repetition is a dangerous waste of time — what is the proper phrase for that idea, to say it only once?), perhaps that is enough?

**Comment by AlOneill** [comment]
I've remembered the acronym! It's DRY (don't repeat yourself).

**Comment by DeniseColbert** [comment]
Sync ready, thanks Alison!

**Comment by AlOneill** [comment]
Er, it's not sync-ready yet as final tasks need doing — you could say that it's ready to be made sync-ready!

**Comment by AlOneill** [comment]
[Information for Transcribers](https://test3.freecen.org.uk/cms/information-for-transcribers) is now sync-ready.

**Comment by DeniseColbert** [comment]
Deployment this weekend

**Comment by DeniseColbert** [comment]
@AnneV-Learn to check

**Comment by AnneV-Learn** [comment]
Appropriate text appears to have been added to Help so closing.
