### ISSUE TITLE
reduce the prominence of Override button. (Follow up from #1424)

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1431]

**Comment by AnneV-Learn** [comment]
@geoffj-FUG has requested changes to reduce the prominence of Override button.

Can we make the button with Submit on it longer please? Override is larger but is the option that we need to discourage use of.
 
The alternative is to put Cancel onto a similar button and put it between Submit and Override.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this is ready for testing on Test3

**Comment by geoffj-FUG** [comment]
Anne
That looks a lot better thank you. Lets go with it.
Geoff

**Comment by geoffj-FUG** [comment]
Looks good. Closed.

Geoff
