### ISSUE TITLE
User message on deletion of vld file needed.

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1433]
When I click delete on a vld file (so I can replace it with a csv file) I get no blue message at the top of the screen. Can we add the blue message please so that the user knows the delete has been accepted by the system. Geoff

(This is the feedback reference 23639050

**Comment by AnneV-Learn** [comment]
Fix deployed to Test3

**Comment by geoffj-FUG** [comment]
Anne
I tried to delete HO410148 Cornwall on Test3. 
Message that has been deleted and refresh work OK.
However, deletion can take a few minutes. Can we add a message when the OK button is accepted please? "Deletion in progress" with a spinner would be suitable . Then your message that piece deleted can follow.
That would work well.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG   (with help from Vino) Test3 has been updated to include a spinner and 'Deleting' message. Could you please retest.

**Comment by DeniseColbert** [comment]
@geoffj-FUG  to test

**Comment by geoffj-FUG** [comment]
All Good please deploy

Geoff

**Comment by DeniseColbert** [comment]
Done, closing
