### ISSUE TITLE
Can age be added to occupation scholar warning?

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1435]
Mike Simpson suggests
Can the message, typically:
Warning: line 332 Occupation scholar is unusual use of Scholar.
have the age added to read, typically:
Warning: line 332 Occupation scholar is unusual use of Scholar.aged 1

The reason is that it isn't uncommon for the line numbers to get out of phase with those on the spreadsheet due insertions and deletions, which makes it a problem as to which record is being referred to.

Geoff

**Comment by DeniseColbert** [comment]
Age to be added to warning (validation)

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this is ready for testing on Test3

**Comment by geoffj-FUG** [comment]
Anne
Looks good thank you. Can you move this to production.
Thanks
Geoff

**Comment by geoffj-FUG** [comment]
Migrated, Looks good.
Geoff
