### ISSUE TITLE
Remove propagation from 1841 validation

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1436]
1841 Validation offers propagation. However as there are only 2 Chapman Codes in general use propagating becomes disastrous.
Propagation should therefore not be offered during validation of 1841 pieces.
Geoff

**Comment by DeniseColbert** [comment]
Propagate button to be removed or hidden from 1841

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this is ready for testing on Test3

**Comment by geoffj-FUG** [comment]
Anne
That looks good too. Lets do it!
Geoff

**Comment by geoffj-FUG** [comment]
Completed. OK
Geoff
