### ISSUE TITLE
Add Wales in dropdown of counties for data managers and system administrators only in creation of new Gazetteer places

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1438]
Requested by Rhoda (& Geoff) so that South Wales can be added as a place in Wales

**Comment by AnneV-Learn** [comment]
Fix has been deployed to Test3. @rhodamackenzie or @geoffj-FUG are you able to test pls.

**Comment by geoffj-FUG** [comment]
Anne, Rhoda

 

Wales is hidden from me, which is correct.

 

Rhoda, can you test to make sure that your access level allows you to edit, please?

 

Geoff

**Comment by DeniseColbert** [comment]
@rhodamackenzie to test

**Comment by DeniseColbert** [comment]
@geoffj-FUG can also test

**Comment by rhodamackenzie** [comment]
Sorry i answered this email instead of on here, i can edit

**Comment by geoffj-FUG** [comment]
@AnneV-Learn WLS has not quite made it to freecen2, Anne is it possible to implement this now? It works fine on test3, 
Thanks, Rhoda

**Comment by AnneV-Learn** [comment]
I have asked @Vino-S to deploy to production.

**Comment by DeniseColbert** [comment]
Done, closing
