### ISSUE TITLE
CSV file processing - more user friendly error message if there is a problem with the header row

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1444]
Suggest: There is problem with the header row. Please correct and try again. 

Example of current message:

undefined method `<' for nil:NilClass
["/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:777:in `process_header_fields'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:365:in `a_single_csv_file_process'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:82:in `block in activate_project'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:78:in `each'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:78:in `activate_project'", "/home/apache/hosts/freecen2/production/lib/tasks/build.rake:694:in `block (2 levels) in '", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `block in execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `each'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/airbrake-11.0.1/lib/airbrake/rake.rb:19:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'", "/usr/local/lib/ruby/2.6/monitor.rb:235:in `mon_synchronize'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/exe/rake:27:in `'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/bin/rake:23:in `load'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/bin/rake:23:in `
'"]
The CSVProcessor crashed please provide the following information to your coordinator to send to the System Administrators

**Comment by DeniseColbert** [comment]
Superseded, closing
