### ISSUE TITLE
CSV File list empty after upload

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1445]

**Comment by AnneV-Learn** [comment]
Problem reported by Ali Hill via Feedback:
Hi Anne

Re this issue---I have uploaded a file to EWS, (manage county/upload new batch/browse for file/select ID/upload.)

As reported, there are no files shown in list following upload..

![Screenshot 2022-09-13 at 16.08.16.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/745db482-a428-4878-9bad-1eabf7f86f87)

**Comment by AnneV-Learn** [comment]
Quite difficult to replicate this but I have made some changes that might fix it. Perhaps someone could get Ali to test on Test3.

**Comment by AnneV-Learn** [comment]
Ali tested on Test3 and she is happy with the fix.

**Comment by DeniseColbert** [comment]
Done, closing
