### ISSUE TITLE
Wildcards are not working

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1451]
See story Tested wildcard searching on both place of birth and Test surname  P?ll?ser , no first name, census location North Riding of Yorkshire, Scarborough + nearby places - generates error "Wildcard can only be used with a specific place."
Test surname P?ll?ser, no first name, birth location North Riding of Yorkshire - generates error "Wildcard can only be used with a specific place."
Test surname Pal*ser , no first name, census location North Riding of Yorkshire, Scarborough - generates error "Wildcard can only be used with a specific place."
Test surname Pal*ser , no first name, birth location North Riding of Yorkshire generates error "Wildcard can only be used with a specific place."

**Comment by AnneV-Learn** [comment]
Fix deployed to Test3.

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG could you test Anne's fix please?

**Comment by AlOneill** [comment]
Er, CEN does not use wild-cards for transcribing, but perhaps using wild-cards for searching is an altogether different animal??

**Comment by AnneV-Learn** [comment]
This issue relates to wildcards in Searching FreeCen Census Records (ie the FreeCen main landing page functionality).

**Comment by AlOneill** [comment]
Oops!! Brain not in gear.

**Comment by DeniseColbert** [comment]
@DeniseColbert to test e.g. J*seph Colbert

**Comment by DeniseColbert** [comment]
![image](https://user-images.githubusercontent.com/19173257/211872000-29f2d5e6-d90b-4f03-8d6a-e4055cef4047.png)

There is one Joseph Colbert in that place so should have returned a result @AnneV-Learn

**Comment by AnneV-Learn** [comment]
Were you testing on Test3?
**BTW** just found that if you use a wildcard in the forename it has to be preceded by at least 2 characters.
This is my test on Test3:
![Screenshot 2023-01-11 at 17 34 04](https://user-images.githubusercontent.com/72746727/211877764-563a2db4-f8e5-4b96-8ba4-8e7a3110c513.png)

**Comment by DeniseColbert** [comment]
Yes, sorry Anne, I was on live :/

Tested on T3 and working fine, thanks.

**Comment by DeniseColbert** [comment]
Has this been deployed @Vino-S ? If so we can close this.
