### ISSUE TITLE
Wildcard search failing

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1452]
As @AnneV-Learn noted in August 2022 (see issue #829) the wildcard search does not work even if a place _is_ selected - true for both ? and * as wildcards.  Assigning Anne as she asked.

**Comment by AnneV-Learn** [comment]
@PatReynoldsFUG  I think this is already covered by #1451

**Comment by DeniseColbert** [comment]
Duplicate- closing
