### ISSUE TITLE
Change name of Report a problem button

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1454]
"Report a problem/Feedback"

Radio button choice for which option

Positive feedback to go to Chris for Newsletter

**Comment by DeniseColbert** [comment]
@geoffj-FUG to suggest text after discussion with committee

**Comment by geoffj-FUG** [comment]
FreeCEN Committee recommend that the button just says Feedback. When selected researcher taken to a radio button choice of either Report Problem or General Feedback
If Report Problem button selected report goes to Coordinator with copy to Commscoord
If Feedback report goes to Chris (Newsletter editor) for inclusion in Newsletter if appropriate.
Geoff

**Comment by geoffj-FUG** [comment]
See also story #250. This story will resolve story #250.
Geoff

**Comment by geoffj-FUG** [comment]
Denise advises that we should look at adopting the FreeREG system for this feedback. Denise Colbert7:39 PM
https://www.freereg.org.uk/cms/about/your-reviews

**Comment by DeniseColbert** [comment]
Proposal with context needed to gather opinions from dev teams etc.

**Comment by geoffj-FUG** [comment]
Suggestion.
WThe button image says 'Provide Feedback'
Rollover says 'Provide feedback or report a problem here'
Alt text should be 'Provide feedback or report a problem here' for screen readers.
