### ISSUE TITLE
Unsubscribe from FreeCEN transcribers list not working

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1455]
Tried to unsubscribe today and got this error message:
Message not delivered
There was a problem delivering your message to freecen-transcribers+unsubscribe@freeukgenealogy.org.uk. Contact the remote server administrator for details.

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG could you please try again?

**Comment by DeniseColbert** [comment]
Tested and I could unsubscribe so closing
