### ISSUE TITLE
Gazetteer - advanced search - deselect

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1456]
Once you've selected an advanced search option, you cannot deselect - one of the options always remains selected. There should be a way to deselect all.
(Feedback issue no. 246785629)

**Comment by AnneV-Learn** [comment]
Added N/A to Advanced Search options.

**Comment by DeniseColbert** [comment]
@Vino-S to test

**Comment by geoffj-FUG** [comment]
@AnneV-Learn  
Whilst this is being done can there be a clear button added to the County please? 
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG When I looked at the code I actually found a bug which meant that 'blank' (ie no county selected) was not appearing as the first entry in the county dropdown as it should have been. I have now corrected that and will let you know when it has been deployed to Test3 for testing.

**Comment by geoffj-FUG** [comment]
Anne

 

There is no problem with the blank displaying at the top of the list.

 

At present to get to another county I can overtype. Good

To get to the blank I have to type an A then scroll to the blank in the list and then enter. A validator does this many times in a day. It would be a lot user friendly if we could just have a button to clear the form.

 

Geoff

**Comment by AnneV-Learn** [comment]
Hi Geoff,
I was seeing a problem yesterday on my Mac - strange.
Anyway, I can easily add a clear button as you have requested.
 Anne

On 16 Nov 2022, at 01:02, geoffj-FUG ***@***.***> wrote:

﻿

Anne



There is no problem with the blank displaying at the top of the list.



At present to get to another county I can overtype. Good

To get to the blank I have to type an A then scroll to the blank in the list and then enter. A validator does this many times in a day. It would be a lot user friendly if we could just have a button to clear the form.



Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG - I have added a 'Clear County' button and it has been deployed to Test3 for testing.

**Comment by geoffj-FUG** [comment]
Anne

 

Clear County works well.

 

Is it possible for the radio button to default to N/A whenever Search Place Names is selected. It currently stays on the previous choice. In the original form the radio button choice was removed whenever the form was requested.

 

We still need the previous place name and county query to stay.

 

Geoff

**Comment by AnneV-Learn** [comment]
Yes I can do that Geoff. I’ll get back when available to test.
A

On 21 Nov 2022, at 10:23, geoffj-FUG ***@***.***> wrote:

﻿

Anne



Clear County works well.



Is it possible for the radio button to default to N/A whenever Search Place Names is selected. It currently stays on the previous choice. In the original form the radio button choice was removed whenever the form was requested.



We still need the previous place name and county query to stay.



Geoff

**Comment by AnneV-Learn** [comment]
Ok @Geoffj-FUG I have made the change (advanced search setting is not reloaded from previous search) and it is ready for testing on Test3.

**Comment by geoffj-FUG** [comment]
Looks Good. This can be deployed. Please let me know when it happens and I will put a message on the message boards.
Geoff

**Comment by geoffj-FUG** [comment]
Thanks Anne

 

I have marked it ready for deployment

 

Geoff

**Comment by AnneV-Learn** [comment]
🙂 I think @Vino usually does just one production deployment each month, so may have to wait a couple of weeks now.
Anne
On 22 Nov 2022, at 06:27, Geoff J ***@***.***> wrote:

﻿

Looks Good. This can be deployed. Please let me know when it happens and I will put a message on the message boards.
Geoff

**Comment by AnneV-Learn** [comment]
Deployed and checked so closing
