### ISSUE TITLE
Disabling of Place Name in Gazetteer

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1457]
When a place name is currently disabled in the Gazetteer it is moved to a file. When a person wants to add a place name to the Gazetteer several checks are made which includes this file. If the place is found it cannot be added.
This causes a problem when trying o tidy up the Gazetteer. If a place has two entries with different spellings with the same latitude and longitude the duplicate entry cannot be removed and re-added as an alternative place name, because the place name is in the disabled list.
We need to either not test the disabled list for duplicates or do a hard delete instead storing the old info. 
I do not know why the disabled place names are stored.
Geoff

**Comment by DeniseColbert** [comment]
Agreed to hard delete the disabled places

**Comment by DeniseColbert** [comment]
@Vino-S to check the collection "Master Place" and let Anne know what it is.

@geoffj-FUG what is the approval process for Gazeteer entries? Is there one?

**Comment by geoffj-FUG** [comment]
Gazetteer entries can only be made by the Validator or Coordinator. They are entered when a place name appears in  POB and the place is not already in the Gazetteer. When a new Gazetteer entry is made it is only accepted if all boxes in the form are completed. So latitude and longitude and a web reference are compulsory and the place can therefore be verified. The Gazetteer will not accept duplicated entries.
Early in the piece we had a lot of rubbish entries in the Gazetteer but the requirement for all fields to be compulsory has fixed this.
We are almost at the end of the task of tidying up the Gazetteer including removing place names without sources. Rhoda has a few PARMS entries to move and the search entries that Vino is waiting on can then be sent to her. There will only be a few to do this time.
Currently disabled entries are a soft delete. For some reason they are being tested as duplicates when an new Gazetteer entry is being made. Making it a hard delete means that the entry can be re-entered in the Gazetteer  when it crops up in a piece at validation.
The current inability to re-enter disabled place names is causing some angst amongst coordinators.
Geoff

**Comment by DeniseColbert** [comment]
@Vino-S to ask @Captainkirkdawson for info (if he has it)

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
Ready for testing on Test3

**Comment by geoffj-FUG** [comment]
Anne
I have just deleted a place a nd immediately re-entered it. Worked well. This can be deployed.
Geoff

**Comment by DeniseColbert** [comment]
Done, closing
