### ISSUE TITLE
Tetsing of 1851 csv files is looking for a field called Ward

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1467]
@AnneV-Learn  
Anne
When an 1851 file is being tested the system is looking for a field called Ward. Ward is not part of 1851.
Can we remove this part of the test please?
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Can you confirm that Ward is not part of 1851 census for all countries or is this just a request for it to be removed for Ireland 1851 (assuming you are testing Ireland??)?
(The code currently appears to exclude Ward for **England** 1851)

**Comment by geoffj-FUG** [comment]
Anne

 

Ward is not a field in England and Wales in 1851. It is being tested for and therefore reporting as an error

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Can you send me the CSV file you are using for the Testing please? Assuming you are getting an error when you use CSVProc to load the file.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Ok issue identified and corrected so that Ward is not required for all 1851 census. Now ready for testing on Test3. For some reason it won't let me move this issue into the Ready For User Testing Pipeline!?

**Comment by geoffj-FUG** [comment]
Anne 

It tests OK. I have marked it to be deployed.

Thank you

Geoff

**Comment by geoffj-FUG** [comment]
Anne

 

I cant mark it. We have been locked out of Zenhub!

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG This has now been deployed. I have checked the code change so I am closing.

**Comment by geoffj-FUG** [comment]
Deployed and working correctly
Geoff
