### ISSUE TITLE
Incomplete Registrations button not connected

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1468]
Should be a function for Syndicate Coordinators

**Comment by geoffj-FUG** [comment]
Not sure if this is related but Chris Mahoney mentioned at the Committee Meeting that he cannot access the syndicate info for a volunteer who did not do the second part of the registration.
The volunteer has been doing work but cannot upload to the system
Geoff

**Comment by DeniseColbert** [comment]
@Vino-S to move to test 3 and assign @geoffj-FUG when ready to test.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
@DeniseColbert to test

**Comment by DeniseColbert** [comment]
Working on Test3, Thanks @Vino-S : this can be deployed

**Comment by DeniseColbert** [comment]
Done, closing
