### ISSUE TITLE
Structure of vld data collection 

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1470]
@AnneV-Learn 
I am thinking ahead so that I know where to guide changes to the system.
In my mind (which thinks in terms of relational databases I am afraid) I see the needed structure for searching the vld data collection as:

PARMS - Contains piece information including valid civil parishes
PARMS / Records links file - Contains the links between the civil parish in each record with the PARMS civil parish
Vld Data Collection - contains the individual records uploaded by Coordinators in the pieces.
Records / Gazetteer link file - Contains the links between the POB in each record and the Gazetteer
GAZETTEER - Contains details of the valid Places of Birth.

This I presume mirrors the structure used in the csv data collection.

Can you please confirm my picture of the database structure or let me know where I am wrong.
Can you please have a look and see whether all the pieces required to create the links for the vld data collection and mirror the files used by the csv data collection already exist or whether we will need to create either of the links files.

This will help me understand what steps we need to take when uploads to the vld data collection eventually end.

(You did say that you didn't have a lot happening at the moment!)

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG You did say that you didn't have a lot happening at the moment! :/ 
All quite complicated and rather difficult to analyse but I have done my best!

GAZETTEER - Contains details of the valid Places - freecen2_places
PARMS - Contains piece information including valid civil parishes - freecen2_pieces
PARMS / Records links file - Contains the links between the civil parish in each record with the PARMS civil parish

        freecen2_pieces record:
	has_many :freecen2_civil_parishes
  	has_many :freecen_csv_files
  	has_many :freecen1_vld_files

VLD Data Collections - freecen1_vld_files - contains links to the individual records uploaded (via FreeCen2 'Load VLD file' functionality or the monthly upload) in the VLD file -> freecen1_vld_entries -> freecen1_vld_individuals -> one Search_record
CSV Data Collections -  freecen_csv_files - contains links to the individual records uploaded in the CSVProc file -> freecen_csv_entries -> one Search_record (when csv file is incorporated) 

VLD collections
	freecen1_vld_files record:																
	has_many :freecen1_vld_entries																					
  	has_many :freecen_dwellings
  	has_many :search_records

  	belongs_to :freecen2_place (∴ link to Gazetteer for census place) 								
  	belongs_to :freecen2_piece																														
	belongs_to :freecen2_district

	freecen1_vld_individual records:															

	has_one :search_record																	 

	belongs_to :freecen1_vld_file																
  	belongs_to :freecen_dwelling																
  	belongs_to :freecen1_vld_entry															
  	belongs_to :freecen2_place, (link for census place)
  	belongs_to :freecen2_piece, (link to PARMs - see above)

	There is no link from freecen1_vld_individual to the Gazetteer (freecen2_places) 					
 	for POB, so could there be POBs in uploaded VLD files that don’t exist 	 			
	in the Gazetteer (unless freecen2_places is a superset of freecen1 places (master_place_name?)? 		
	That would be resolved if a VLD is 'replaced' with a 'CSVProc' file,								. 		 			
	but if that is not feasible for all VLDs now loaded into Freecen2, then there would have to 			
	be a way of checking the birth_place for VLD files and just 'replacing' those 
	where the birth_place is not in the Gazetteer.

CSV collections
	freecen_csv_files record:

	has_many :freecen_csv_entries							
 	belongs_to :freecen2_place (∴ link to Gazetteer for census place)
  	belongs_to :freecen2_piece (link to PARMs - see above)
  	belongs_to :freecen2_district

	freecen_csv_entries records:

	has_one :search_record (when incorporated)

	belongs_to :freecen_csv_file
  	belongs_to :freecen2_civil_parish
  	
	There don’t appear to be links from freecen_csv_entries to Gazetteer for POB  but POB County is checked against Chapman Codes list and POB 			 			 	verbatim is checked against Gazetteer during the CSVProc validation/editing processes
	and will raise a validation Warning if not found. I.e
	"Verbatim Place of Birth in 'County' was not found so requires validation". 
	
Hoping this is understandable and that I haven’t missed or misinterpreted anything.

**Comment by geoffj-FUG** [comment]
Thanks Anne
Geoff
