### ISSUE TITLE
249216960 Data Problem (Pat Reynolds)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1471]
Issue reported by **Pat Reynolds** at 2022-11-24 10:56:00 UTC
Time: 2022-11-24T10:54:53+00:00
Session ID: 
Problem Page URL: [https://www.freecen.org.uk/search_records/5903a5c5e9379091b17b43bc/louisa-brown-1891-lincolnshire-glanford-brigg-1860-?locale=en](https://www.freecen.org.uk/search_records/5903a5c5e9379091b17b43bc/louisa-brown-1891-lincolnshire-glanford-brigg-1860-?locale=en)
Previous Page URL: [https://www.freecen.org.uk/contacts/5903a5c5e9379091b17b43bc/report_error?locale=en&query=637f4d57865574dd741125df](https://www.freecen.org.uk/contacts/5903a5c5e9379091b17b43bc/report_error?locale=en&query=637f4d57865574dd741125df)
Reported Issue:
Found with a search for  Occupation=Ship  Cannot see why this record returned.

**Comment by AnneV-Learn** [comment]
Unable to replicate this issue- filtering with occupation=ship returns zero result![9630E51F-5739-4598-813F-E99584522D8E.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/07ad84a7-ef1f-43b3-b6e1-857400d6db51)![1D489000-1B9A-4986-AF22-6228B917AABE.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/5b74306e-72b3-4ffb-bb15-d89d36a60c10)s

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG to review Anne's comment

**Comment by PatReynoldsFUG** [comment]
Sorry, @AnneV-Learn I have now tried my search again, and can happily report that searching for occupation =ship brings up entries containing "ship" in all positions (start, middle and end of text so closing.
