### ISSUE TITLE
Create link from vld data collection to Gazetteer and PARMS entries

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1472]
When a csv file is Incorporated links are created between the csv data collection and the Gazetteer. As I understand it this is the link that makes places of birth searchable.
In preparation for when we cease vld uploading and clean up the vld places of birth we will need to add this link to the vld collection.
The same goes for the link between the vld data collection and the PARMS Civil parishes.
This story is related to story #1458

**Comment by DeniseColbert** [comment]
@AnneV-Learn to investigate

**Comment by geoffj-FUG** [comment]
This is my investigating the amendments that are required to make the vld data collection reflect the functions available to the csv data collection for linking to the Gazetteer and PARMS to allow future matched searching. When we re-validate the vld data collection these links will need to be able to be established.
Geoff

**Comment by geoffj-FUG** [comment]
Once the vld civil parish reconciliation has been done there should be no civil parishes that are not linked to the PARMS entries. This simply needs to be checked.
Geoff

**Comment by geoffj-FUG** [comment]
Resolved that link already exists.
