### ISSUE TITLE
252432711 Videos not available (Michael)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1474]
Issue reported by **miked** at 2022-12-31 16:11:51 UTC
Time: 2022-12-31T16:09:09+00:00
Session ID: 5074e247b62d5af189cfa4cdeb5e19e7
Problem Page URL: [/freecen_csv_files/my_own](/freecen_csv_files/my_own)
Previous Page URL: [https://www.freecen.org.uk/manage_resources/new?locale=en](https://www.freecen.org.uk/manage_resources/new?locale=en)
Reported Issue:
I just volunteered as a transcriber.  Upon changing my password and landing on page: https://www.freecen.org.uk/freecen_csv_files/my_own, none of the video links are working.     

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
@denisecolbert I tried this and the videos all came up as unavailable for me too. Has something changed re the video links?

**Comment by DeniseColbert** [comment]
OK, I think I know the issue. Kirk asked me to put all of the videos onto our FreeUKGEN YouTube account, which I did and placed them all on this page https://www.freecen.org.uk/cms/instructional-videos (linked to from Your Actions page).

I didn't realise Kirk's were linked to elsewhere, so these links need to be updated with the ones on the above page. I think https://www.freecen.org.uk/freecen_csv_files/my_own is an app page so could you change the links please, @AnneV-Learn? Right-click on the thumbnail lets Windows users copy the url, might be the same for Macs?

**Comment by AnneV-Learn** [comment]
@DeniseColbert The current links include a lot more videos than I can see on https://www.freecen.org.uk/cms/instructional-videos. See screenshots
![Screenshot 2023-01-11 at 11.46.55.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/ff0fc7fb-0b36-461e-a974-06aebb85381c). 


![Screenshot 2023-01-11 at 11.47.35.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/0a69e104-7f2b-4f8b-a9bd-407288b492b8)Shall I just amend to offer the CSVProc videos that are available or are there more that need to be uploaded to cms/instructional-videos?

**Comment by DeniseColbert** [comment]
The ones on the FUG YT playlist replaced Kirk's videos, they should cover all topics. I think we can replace the individual links to kirks videos with the link to the new page, would you agree @geoffj-FUG ?

**Comment by geoffj-FUG** [comment]
I have an issue if the videos are not identified as belonging to a particular form. The original links across the top of the page referred directly to the videos covering that form. 
The videos will be used by new users, not experienced ones. A new user would not be able to identify which videos belonged to which page.
They need to be grouped in some identifiable way. For instance if the videos were grouped in sub-folders, one for each form, on You tube then only the applicable videos for that form would be seen once the link is clicked.
Geoff

**Comment by DeniseColbert** [comment]
This Page/Upload a CSV file: https://youtu.be/GnkkKkVGXs8
Download a spreadsheet file: https://youtu.be/2ekZ_VXmTn0
Upload traditional file: https://youtu.be/DM889numA-s
Show details of the file/errors display: https://youtu.be/f0l1tlWESII
Replace a file: https://youtu.be/XH-QBKRg9gQ

(remove a file can be deleted as we don't have a video for it and it's a Coord function)

**Comment by AnneV-Learn** [comment]
@DeniseColbert @geoffj-FUG 

The 'Show' page currently also has video links for the following:

**convert to modern headers**  <-- n.b. only displayed if the file being shown is a traditional file
**download the file**
**remove a file**    <--- guess I'll just remove that?
**download message report**
What do you want to do about those?

On the 'Show' page  there is a  **'On header line two**' line of video links that are just placeholders with no actual links to videos attached. Guess I should just remove that whole line?

Also a Coordinator will see the following additional link:
**remove a file**

**Comment by DeniseColbert** [comment]
convert to modern headers [REMOVE]

Download a spreadsheet file: https://youtu.be/2ekZ_VXmTn0

Remove a file {REMOVE]

Download message report: https://youtu.be/f0l1tlWESII

On the 'Show' page there is a 'On header line two' line of video links that are just placeholders with no actual links to videos attached. Guess I should just remove that whole line? [REMOVE]

Also a Coordinator will see the following additional link: remove a file [REMOVE]

**Comment by AnneV-Learn** [comment]
Updated as requested above and now ready for testing on **Test3.**

**Comment by DeniseColbert** [comment]
I've tested the vids on the My Files page; all good, thanks Anne. However, I have no files so could @geoffj-FUG perhaps test the ones on the "Show" page?

**Comment by DeniseColbert** [comment]
All good so ready to be deployed

**Comment by DeniseColbert** [comment]
Done, closing
