### ISSUE TITLE
Review the Vision of FreeCEN

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1475]
The Committee have identified that the Vision of FreeCEN is out of date.
We are in the process of reviewing the original Vision Statement and will make a suitable recommendation to the COO.
Geoff

**Comment by geoffj-FUG** [comment]
Inputs to be considered at January meeting.
Geoff

**Comment by geoffj-FUG** [comment]
FreeCEN Committee reviewed a draft of Vision Statement on 21 Jan. Helen to take to Denise and Trustees for approval.
If approved the statement on the FreeCEN page will need to be updated.

**Comment by DeniseColbert** [comment]
This was approved, text on the About page should be:

This project aims to provide a "free-to-view" online searchable database of UK census returns. 

The UK is defined as England, Scotland, Ireland and Wales together with the Crown Dependencies of the Channel Islands and Isle of Man, and including the Orkney and Hebrides Islands, provided that they were under the responsibility of the Crown at the time that the census was taken. 

(To replace the first, bold paragraph on About)

**Comment by AlOneill** [comment]
@geoffj-FUG @DeniseColbert 

A few questions:
1. Why is "free-to-view" in quotation marks? The term is common and to put it in quotation marks seems to imply that the meaning is actually something other than free-to-view.
2. Do we want _two_ lead paragraphs, just the first styled as a lead, or do I create a single paragraph?
3. Do we need to explain any of the geographical and political terms more explicitly?

**Comment by geoffj-FUG** [comment]
Alison

 

Most of the text was already there. All the Committee did was put a recommendation for an updated Mission Statement to the Trustees.

 

We did not review the rest of the page.

 

Geoff

**Comment by AlOneill** [comment]
Sorry, but I'm not clear about exactly what needs changing. The current top of the page looks like this:
![About___FreeCEN.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/1d4249b0-c33a-4ae5-8aea-367cefb25ccf)

My interpretation of the changes requested is this, with a small re-write:
![DRAFT_About___FreeCEN.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/3656330d-80d6-4eea-ae9b-20c04b056531)

Is this correct or have I misinterpreted the request?

**Comment by DeniseColbert** [comment]
1. Remove quotations
2. First paragraph styled as lead, second normal text (i.e. your interpretation is correct)
3. No, the words were considered at length by the committee

**Comment by AlOneill** [comment]
Thank you. I have removed the quotation marks, made the page sync-ready and published it on test 3.

**Comment by DeniseColbert** [comment]
Done, closing
