### ISSUE TITLE
Cannot save .png file to Refinery on t3

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#1477]

**Comment by AlOneill** [comment]
Have tried several times to save a .png file to Refinery on t3. Am getting this error message:

"

There were problems with the following fields:

    Your image must be either a JPG, PNG or GIF

"

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
@AlOneill could you please test?

**Comment by AlOneill** [comment]
Tested with one image file (the one that was rejected previously) and all seems well.
Closing.
