### ISSUE TITLE
247596894 Enhancement Suggestion (Helen MacGregor)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1478]
Issue reported by **Helen MacGregor** at 2022-11-05 16:54:54 UTC
Time: 2022-11-05T16:53:48+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
Would it be possible to introduce a search for an address rather than a name?

**Comment by DeniseColbert** [comment]
Duplicate: closing
