### ISSUE TITLE
Google summary when Googling FreeCEN

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1482]
If I Google FreeCEN I get the following:

Use FreeCEN to access 19th Century UK Censuses online and for free. You can use FreeCEN transcriptions to discover your ancestors' occupation, ...
1841 – All Counties
Use FreeCEN to access 19th Century UK Censuses online ...
1851 – All Counties
Use FreeCEN to access 19th Century UK Censuses online ...
1911 – All Counties
Use FreeCEN to access 19th Century UK Censuses online ...
1871 – All Counties
Use FreeCEN to access 19th Century UK Censuses online ...

You will notice the repetition of the words 19th century census. Are these entries driven by meta-tagging? If so the meta tags need updating. If they are driven by keywords the keywords need updating.
Geoff

**Comment by DeniseColbert** [comment]
Can you provide a snip of what you see Geoff? It could be organic or one of our Google Ads

**Comment by DeniseColbert** [comment]
![Julie Goucher pledge](https://user-images.githubusercontent.com/19173257/216007859-48a53e8c-a53b-455c-9f6d-032e2a97d115.png)

**Comment by geoffj-FUG** [comment]
![image.png](https://images.zenhubusercontent.com/5e8c52a8b7c1d94d472bb276/3523fe7d-f974-498e-a87f-4ab72378ddea)

**Comment by DeniseColbert** [comment]
Vino can change the meta description for the main page and sub pages

Main page:
Title: Search censuses
Meta:
Find 19th & 20th Century UK census transcriptions, for free, forever.

- Search - Discover your ancestors in our UK census transcriptions
- About - Find out about our free-to-search database
- Volunteer - Offer your time to our volunteer-led charity project
- Records - Find out about the coverage of our transcriptions

**Comment by Vino-S** [comment]
The Google summary is replaced with the latest text for FreeCEN search.
