### ISSUE TITLE
Things that must happen on 1st April to end vld Uploads

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1483]
The last day of uploading  New vld files to FreeCEN will be 31st March 2023.
The form found under the Your Actions: › County Options › FreeCen1 VLD Files Actions has an Action to 'Upload new VLD File'.
A modified copy of this form will need to be created without the Action to 'Upload New VLD File'. It will need to replace the existing form on 1st April 2023.
All other actions available from this form remain the same.
Geoff

**Comment by geoffj-FUG** [comment]
Three additional things that must occur on 1st April are:

The traditional spreadsheet must be removed from the spreadsheet formats available under CSVBatches ... Download Spreadsheet menu.

The revised Part 1 of the FreeCEN Handbook for England and Wales (April 2023 version) which will replace the Abbreviated Handbook will need to be loaded onto the site to replace the current Abbreviated Handbook for England and Wales. I have already prepared this version. 

The revised part 3 of the Handbook for coordinators will need to replace the current part 3 under the Handbook menu action. I have already revised this handbook.
Geoff

**Comment by geoffj-FUG** [comment]
The vld Upload function also needs to be removed from the vld listing screen.
I would like the data manager to retain the ability to upload a vld. This is important as amendments to the PARMS during the changeover will require any existing vld files for piece to be removed and replaced. Therefore somebody has to retain the ability to upload the replacement file.
Geoff

**Comment by DeniseColbert** [comment]
@geoffj-FUG to send @AlOneill a clear scheme of changes needed and links, so that she can have the page ready for 1st April.

@AnneV-Learn to make form changes

**Comment by AnneV-Learn** [comment]
@geoffj-FUG A few questions:
Should we be restricting the **Replace** VLD file (as well as Upload VLD file) to Data_manager and Country_coordinators?

Should the 'Upload Traditional File' instructional video link be restricted to Data_manager and Country_coordinators?

Also want to check that as we are moving away from FreeCen1 should the 'Manage FreeCEN1 Pieces' (which allows DM to create a new FreeCEN1 Piece, Edit a FreeCEN1 Piece and Destroy a  FreeCEN1 Piece) and 'Manage FreeCEN1 Places'(includes the ability to Edit a Place - DM only) buttons be removed from the List of actions when Managing a County? 

Last Question - can you please explain which spreadsheet (re The traditional spreadsheet must be removed from the spreadsheet formats available under CSVBatches ... Download Spreadsheet menu.) as I can't see traditional mentioned in the dropdown list.

**Comment by geoffj-FUG** [comment]
Anne

 

Replace vld file – yes please restrict it. It will stop abuse.

 

Upload traditional file video – please leave that there. We have transcribers in transition for several months. We can remove it once everybody s working on new spreadsheets.

 

Traditional spreadsheet – ah its not there! I just assumed that it was. People must have been using copies stored elsewhere.

 

Geoff

**Comment by AlOneill** [comment]
Have created a separate issue for the "FreeCEN Handbook" update, #1500, to avoid confusion (mine!).

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
As we are moving away from FreeCen1 should the '**Manage FreeCEN1 Pieces**' (which allows DM to create a new FreeCEN1 Piece, Edit a FreeCEN1 Piece and Destroy a FreeCEN1 Piece) and '**Manage FreeCEN1 Places**' (includes the ability to Edit a Place - DM only) buttons be removed from the List of actions available when Managing a County?

**Comment by geoffj-FUG** [comment]
Anne

 

All data manager functions must be maintained. Rhoda will need to use them as we clean the vld data collection civil parishes.

 

Coordinators will need all the current actions except Upload, Download and Replace.

 

Scotland Coordinator will need to keep these actions.

 

Geoff

**Comment by AnneV-Learn** [comment]
Form changes (restricting access as specified) are ready for testing on Test3.

**Comment by geoffj-FUG** [comment]
Anne

 

I am happy with that.

 

Lets see how we go. 

 

Geoff

**Comment by DeniseColbert** [comment]
Ready to go on 1st April

**Comment by AnneV-Learn** [comment]
Deployed by Vino 31/03

**Comment by geoffj-FUG** [comment]
This has now all happened. Thank you everybody.
Geoff
This story can now be closed
