### ISSUE TITLE
Any questions ask us does not go to the syndicate

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1486]
This appears to be a bug.

**Comment by geoffj-FUG** [comment]
Cannot switch off

**Comment by geoffj-FUG** [comment]
I have tried to list the syndicate members but the action just redisplays the select syndicate option. It cannot therefore be cleaned up and turned off.
Geoff

**Comment by DeniseColbert** [comment]
@Vino-S could you take a look please?

**Comment by DeniseColbert** [comment]
@AnneV-Learn did the removal of the "?" fix this?

**Comment by AnneV-Learn** [comment]
Yes it did. ‘Any Questions Ask Us’ syndicate now functions as the other syndicates do. This can be closed now.
