### ISSUE TITLE
Coordinators are reporting that not all of them are receiving Contact Action reports.

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1490]
Pat has asked why not all Coordinators are receiving Contact Action Reports. When reports are followed up the Coordinator advises that they are not being received.
Can the operation of the Contact Action report system be checked please to ensure that all Coordinators are listed, in the forst instance.
Geoff

**Comment by DeniseColbert** [comment]
E.g. CAM not being received by Coordinator, but they are receiving ESS (another of their counties)

**Comment by DeniseColbert** [comment]
@Vino-S could you take a look please?

**Comment by geoffj-FUG** [comment]
Chris M  advises that he cannot Reply to a Contact.

Geoff

**Comment by DeniseColbert** [comment]
@Vino-S to talk to @AnneV-Learn before deploying potential fix

**Comment by DeniseColbert** [comment]
Done, closing
