### ISSUE TITLE
Blog entries are not reaching volunteers

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1492]
There are occasional items in the blogs that need to be posted elsewhere for volunteers to see. Options are either the Newsletter or when they appear also put them on the transcribers and coordinators boards.
Nobody really sees the blogs as they stand at the moment.
Geoff

**Comment by DeniseColbert** [comment]
Indeed; Comms Coords should be encouraged to look at https://www.freeukgenealogy.org.uk/news/ regularly for new content to share in their newsletters

**Comment by DeniseColbert** [comment]
@cmahoneynz is this OK?
