### ISSUE TITLE
Provide the ability to download a vld file in an editable and reloadable format

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1493]
When we fix up the vld civil parishes we may need to amend the PARMS for some pieces. That requires us to download the vld and then replace it after the PARMS has been fixed.
The function should be available to the data manager only.
The alternative will be that the coordinator will have to download as csvpro, revalidate it and then upload it as a csv file. That will cause a lot of angst.
The Scotland Coordinator will also need this function to process action reports as the csv system is not implemented for Scotland.
Geoff

**Comment by geoffj-FUG** [comment]
@AnneV-Learn This is associated with the civil parish editing, story #1397
I have already found one instance where we will need to amend the PARMS file.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I think this should be possible

**Comment by geoffj-FUG** [comment]
Anne
In actual fact the download will be different to the transcribers spreadsheet. It will need to be a csv comma delimited file with the 80 (?) characters broken into their fields. We then need a means of converting them to a flat file so that it can be reloaded as a vld. I have copied part of an existing vld file as uploaded below. Is the format in the vld data collection the same or has it been changed? We need to go with whatever is simplest to create.
Geoff
[https://app.zenhub.com/files/28748917/9dc8ad24-013d-4b2a-8165-267307133b13/download]

**Comment by AnneV-Learn** [comment]
@Geoffj-FUG  To download the file in VLD format is relatively straightforward. To provide in an editable format is a rather different proposition. This requires more investigation/discussion.

**Comment by geoffj-FUG** [comment]
Anne

 

I am fishing to find out what is the best option. Whatever we download we have to be able to upload. It seemed to me easier to massage the download format than to change the upload routine that already exists.

 

I will accept whichever option you recommend.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I think one of the main issues is that if VLD data is edited and subsequently re-loaded it would need to be ‘re-validated’. Of course downloading as a CSVProc and loading that file goes through the appropriate validation steps. Downloading a VLD, then deleting it, editing FC2_pieces (Parms) and then uploading the VLD is relatively straightforward. And of course we have the new ability to edit Civil Parishes for a VLD (that process updates the VLD entries collection and the individuals collection). I think I need to better understand what sort of edits you envisage for a VLD.

**Comment by geoffj-FUG** [comment]
Anne

 

The purpose is purely to keep two things going

Margaret still needs to be able to do corrections for Scotland

I will need to get Rhoda to do PARMS corrections where there is a vld file.

 

There is absolutely no intention of giving anybody else this ability.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I have added a 'Download' action to the Manage VLD Files process. It can be tested on Test3, but be aware that the data on Test3 is pretty ropey and quite inconsistent and not all VLD files on Test3 are available for download even if they are in the List of VLD files. If you are testing I recommend that you choose 'SOM' (Somerset). 
I am really not sure how we can 'reverse engineer' to make all fields on a VLD editable and include the appropriate validation without a rather huge amount of programming (and testing) work. Do we know the specific format of the VLD files, I don't but probably Vino does? I feel this needs further discussion.

**Comment by geoffj-FUG** [comment]
That works well.
I downloaded, saved the vld on my PC, deleted the piece and then uploaded it. It was accepted. I then searched for a random entry and it was found and presented properly on the researchers screen.
This can be deployed.
Permission restricted to data manager and if possible Scotland Coordinator please.
Geoff

**Comment by geoffj-FUG** [comment]
Download verified by loading a new file and then downloading it and comparing the 2 versions visually. They both look the same. I will send the downloaded file to a volunteer to convert back to a csv as my computer no longer runs FCTools.
If that works OK then I can verify the download as editable.
Geoff

**Comment by DeniseColbert** [comment]
Deployed: closing
