### ISSUE TITLE
Remove Channel Islands from list of Counties that can be used for new place name. 

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1495]
Channel Islands is not a County. It is an area. The 'counties' used are the individual islands. The existence of this possible county entry is going to make the coding of searching more difficult (an deciding how to search more difficult for the researcher).
In the Chapman Code hierarchy this is not a code that can be used. I am not sure why it is there.
We already have places that hang off of this county. There are over 71000 search entries that point to CHI Guernsey alone. They will all need to be moved to GSY -. I have not checked the other islands.
Geoff

**Comment by DeniseColbert** [comment]
Anne to remove from Gazetteer
Geoff to clean up
Vino to move the links

**Comment by AnneV-Learn** [comment]
'Channel Islands' removed from list of counties available when creating a new Gazetteer place.
The change will be Deployed to Production in conjunction with the deployment of story 1473 (Gazetteer bug fixes and enhancements).

**Comment by geoffj-FUG** [comment]
Anne

 

Thankyou 

 

Geoff

**Comment by DeniseColbert** [comment]
Deployed: closing
