### ISSUE TITLE
Listing of pieces online for a county

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1499]
Michael Simpson has asked whether we can provide an online listing of pieces online.
The site statistics say click and you can drill down. But there is nowhere to click.
Is it possible for a Coordinator to click on a yer and see the pieces online and whether they are vld or csv?
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
To see the list of CSV files  and Incorporated CSV Files you need to click on the actually cell in either of those columns ie the actual number displayed in the cell. If the cell shows 0 (zero) then it does not have a link as there is nothing to list. See Screenshot below.
Bearing that in mind can you please just confirm what you want for this request.

![Screenshot 2023-03-08 at 13.13.22.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/827a48c7-9d80-456d-a60a-48ff69a053a5)

**Comment by geoffj-FUG** [comment]
Anne

 

Thanks for that. I got it to work on csv files but not vld files.

 

The one that is important is files incorporated.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG - So shall I just add a similar link in the appropriate cell for VLD files? Or remove the two links that are there and just have one link on the Year that lists all Pieces  and indicates for those online if it is VLD or CSV?

**Comment by geoffj-FUG** [comment]
Anne What is easiest? Geoff

**Comment by AnneV-Learn** [comment]
Don’t think there is too much in it @geoffj-FUG - so whatever you think will be best for the users.

**Comment by geoffj-FUG** [comment]
Anne

 

Remove the two links that are there and just have one link on the Year that lists all Pieces and indicates for those online if it is VLD or CSV would be the most useful. Go with that if it is not too difficult.

 

Geoff

**Comment by AnneV-Learn** [comment]
🙂👍🏻Ok will do

**Comment by AnneV-Learn** [comment]
Ready for Testing on Test3

**Comment by geoffj-FUG** [comment]
Anne 
Looks good. I sent a copy of the report to Mike who requested it and he is pleased.
This can be deployed. Let me know when it happens and I will issue an advice.
Geoff

**Comment by DeniseColbert** [comment]
Deployed: closing
