### ISSUE TITLE
Update "FreeCEN Handbook" page and sync for 01 Apr

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#1500]
@geoffj-FUG has sent me the updated Handbook files plus a list of changes for the "FreeCEN Handbook" page in Refinery. The plan is to:

1. make and update a DRAFT version of the "FreeCEN Handbook" page in Refinery on test3 for @geoffj-FUG  to check and approve
2. publish the page on test 3
3. ask Vino to sync test 3 to 'live' as soon as possible after 00:00 here (UTC + 0) on 01 Apr or whenever seems best to @geoffj-FUG and the team  — provided it is a reasonable UK time to do so!

**Comment by AlOneill** [comment]
Updates to "DRAFT FreeCEN Handbook" in progress — cannot provide a link to the document yet as the system is having hiccups.

**Comment by AlOneill** [comment]
Have fixed issue of the link to the document not working. Please see [DRAFT FreeCEN Handbook](https://test3.freecen.org.uk/cms/draft-freecen-handbook)

The cause was a similarly-named file at the foot of the listing on "Pages". That file is out of date and I will remove it in the next few days unless someone can make a case for keeping it. 
**Please put working (DRAFT) copies of pages adjacent to the original so that they are obvious. And do not forget to delete them when they become obsolete. Thank you.**

**Comment by AlOneill** [comment]
@geoffj-FUG 
I have updated the [DRAFT FreeCEN Handbook](https://test3.freecen.org.uk/cms/draft-freecen-handbook) as per your document (plus a small adjustment to the text of "FreeCEN Handbook part 3 — Coordination", para one, so that it makes sense).

Could you please review the DRAFT page?

We also need to decide **exactly when** we would like the draft to be published (to the live site): once the review is completed,  sometime on or around 01 Apr, or when?

**Comment by DeniseColbert** [comment]
I have asked @Vino-S to do the sync (a button-press) as soon after midnight on the 1st April as is convenient for her.

**Comment by AlOneill** [comment]
@DeniseColbert Thank you.

**Comment by geoffj-FUG** [comment]
Vino does not have to do this one minute after midnight. She can sleep until breakfast!
Geoff

**Comment by DeniseColbert** [comment]
She knows that :) I left it up to her as to what would be convenient

**Comment by DeniseColbert** [comment]
Ready to go on 1st April, thanks all

**Comment by AlOneill** [comment]
Page now published on t3 and is ready for syncing.

**Comment by geoffj-FUG** [comment]
This has now happened.

Thank you.

Geoff

**Comment by DeniseColbert** [comment]
Closing
