### ISSUE TITLE
Copy FreeCEN1 Scotland PARMS to FreeCEN2

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1502]
In order to move forward with searching we need to be able to compare the Scotland vld civil parish entries with the PARMS and make sure that they match.
As I believe that we cannot download the PARMS structure from the Scotland Archives we need to create our own somehow. The easiest way is to copy the manually compiled Scotland PARMS from FreeCEN1 to FreeCEN2. That will cover all the entries that we have to date.
We can then extend the matching process that we are doing for the vld entries in England and Wales to Scotland and clean the data.

Margaret Singleton will do the reconciliation.

Geoff

**Comment by DeniseColbert** [comment]
Anne will take a look (Vino to send info on updates)

**Comment by AnneV-Learn** [comment]
Just started looking at this and I am a bit confused - sorry.
If I look in FreeCen2 at **ABD** for example, there are **FC1 Pieces** (ie PARMS) for census years 1841 - 1871 and there are also **FC2 Pieces** (ie PARMS) for the same years.
@geoffj-FUG Can you please clarify what we are trying to achieve here.

**Comment by geoffj-FUG** [comment]
I have had a look at the PARMS spreadsheet for the Scotland Counties and I believe that the necessary changes can be done by Rhoda.
If we use the same principal as we have for Shipping the civil parish is the same as the piece name. We can then test for mis-matching civil parishes and Margaret Singleton can make the decision as to whether they re added or changed. Margaret still has the capability of amending vld files and will need it until we have finalised the Scotland spreadsheet testing.
I have had a quick look at AYR and Margaret should be able to decide whether the trascribed civil parishes are acceptable, and if so ask Rhoda to add them to the piece in the PARMS.
That should effectively populate the Scotland PARMS.
Geoff

**Comment by geoffj-FUG** [comment]
Being done inn conjunction with #1556
