### ISSUE TITLE
Create PARMS table for Shipping

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1503]
Pat 1 of a multi part project, the goal for which is to add Latitude and Longitude to make searching available.

The PARMS for Shipping did not download from TNA. When I search TNA there is no detail for the shipping pieces.
We now have a listing of civil parishes for shipping by using the vld civil parish matching report.
We need to create a PARMS entry manually using this download. We can do this as a csv file. 
Do we use the FreeCEN1 PARMS input csv or do you need a different structure?
Geoff

**Comment by suffolkroots** [comment]
@geoffj-FUG Pat is working on shipping parms

**Comment by geoffj-FUG** [comment]
This is more complex that I expected.

There are two formats for 0#8 and therefore they need separate guidelines in Appendix D. 

Then I can resolve the issue that will occur in one of those guidelines. The other one will be OK.

**Comment by DeniseColbert** [comment]
@geoffj-FUG to check with Ali that she's happy

**Comment by DeniseColbert** [comment]
Done: closing
