### ISSUE TITLE
Update 'Info for Coords' to remove references to the Abbreviated handbook

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#1504]
The page "Information for Coordinators" has several references to the "Abbreviated Handbook". These should be edited so that "Abbreviated" is not used.

There are no instances of "Abbreviated" on "Information for Transcribers".

**Comment by AlOneill** [comment]
I have edited the page so that the "Abbreviated Handbook" and the "Full Handbook" are simply the Handbook. These edits are clearly marked.

I have also taken the opportunity to correct typos and syntax errors whilst tweaking some of the language used to be more friendly.

@geoffj-FUG would you please review the [DRAFT Information for Coordinators](https://test3.freecen.org.uk/cms/draft-information-for-coordinators) for accuracy and sense? Thank you.

**Comment by DeniseColbert** [comment]
Geoff to check for accuracy and sense

**Comment by AlOneill** [comment]
I have now updated [Information for Coordinators](https://test3.freecen.org.uk/cms/information-for-coordinators) on test 3. It is ready to be synced tomorrow (01 Apr).

The changes made are to:
- edit references to the "Abbreviated" Handbook and to the "Full" Handbook 
- correct the use of "button" to describe an ordinary link — it matters because a real button does not behave in the same way as a link; 
- make some of the language used more 'friendly'; 
- correct syntax errors;

**Comment by DeniseColbert** [comment]
Done, closing. Thanks all!
