### ISSUE TITLE
csv download of online pieces report

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1505]
Story #1499 created a report showing the status of each piece in a county / year. 
A request has been made for a csv download of this report.
How much work is involved please?
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG not too much work - added estimate

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Ready for Testing on **Test3**

**Comment by geoffj-FUG** [comment]
Looks Good

Can be deployed

**Comment by AnneV-Learn** [comment]
Deployed by Vino 31/03

**Comment by DeniseColbert** [comment]
Closing
