### ISSUE TITLE
Create Civil Parish - reason for addition

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1509]

**Comment by AnneV-Learn** [comment]
Make 'Reason for addition' optional for system_administrator and data_manager users and populate with details of who created the new civil parish if reason for addition is not populated

**Comment by AnneV-Learn** [comment]
@rhodamackenzie this is ready for testing on Test3

**Comment by rhodamackenzie** [comment]
It works for a new parish, please can I also have the same if I make a change or addition to a parish, piece or district? I will have to change a lot!

**Comment by AnneV-Learn** [comment]
@rhodamackenzie I have made the additional changes as requested above and it is ready for testing on Test3

**Comment by rhodamackenzie** [comment]
now working fine for editing an existing parish, thanks

**Comment by AnneV-Learn** [comment]
Deployed by Vino 31/03

**Comment by DeniseColbert** [comment]
Closing
