### ISSUE TITLE
After using 'Locate pieces' links not appearing when 'showing' piece details

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1511]

**Comment by AnneV-Learn** [comment]
@rhodamackenzie this is is ready for testing on Test3. 
Not sure how you will actually test as not entirely sure how the problem you were having manifests itself. But if you could just go through some of the steps you were taking when you had the problem the other day in the production environment and make sure it all appears ok now.

**Comment by rhodamackenzie** [comment]
have a tried a few, seems OK so far

**Comment by AnneV-Learn** [comment]
Deployed by Vino 31/03

**Comment by DeniseColbert** [comment]
Closing
