### ISSUE TITLE
Syndicate name with question mark included

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1512]

**Comment by AnneV-Learn** [comment]
Syndicate names must not include a question mark as the name is used throughout the system as part of href(url). I have removed the question mark from 'Any Questions? Ask Us' syndicate name (via the Syndicate Coordinators/Edit options).
There are 3 Rake tasks that specifically reference 'Any Questions? Ask Us' as a syndicate name - I will update those.
I will also modified the forms that are used to create or rename a syndicate so that a question mark will not be permitted in the name.

**Comment by AnneV-Learn** [comment]
Updated code deployed to Test3 and I tested it there. 
All seems ok.

**Comment by AnneV-Learn** [comment]
Deployed by Vino 31/03

**Comment by DeniseColbert** [comment]
Closing
