### ISSUE TITLE
Case free sorting of all file lists

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1514]
At the moment file lists on FreeCEN2 under Manage County are not sorted case free (this applies to most, if not all lists). This makes finding a particular file more difficult because RG all come first, then Rg and lastly rg.
Can we fix up this so that there is just one list in order irrespective of  case, please?
Geoff

**Comment by AnneV-Learn** [comment]
@Geoff Yes I can work on this. 
In the meantime at the risk of 'teaching Grandma to suck eggs', if you use your Browser search (find on page) facility (ctrl + f) that search is case-insensitive. So for example, searching for rg11_2 on the page will find RG11_2, Rg11_2 and rg11_2.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG ready for testing on Test3

**Comment by DeniseColbert** [comment]
@geoffj-FUG ready for you to test :)

**Comment by geoffj-FUG** [comment]
Anne

Looks good. can be deployed.

Geoff

**Comment by DeniseColbert** [comment]
@geoffj-FUG to have a look and if all is well, close

**Comment by geoffj-FUG** [comment]
Deployed and looking good in production.

Geoff
