### ISSUE TITLE
Allow County Coordinators the same access as Master County Coordinators

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1516]
Once this is done, decommission the Master County Coordinator role

**Comment by AnneV-Learn** [comment]
This change will involve **3** steps:

**A**. Give county_coordinator role same access as master_county_coordinator ; _(tech note: branch = fc_1516a_av)_
**B.** Go into FreeCen and switch all users with role or secondary_role of master_county_coordinator to county_coordinator ;
**C.** Remove all references to  master_county_coordinator from FreeCen code. _(tech note: branch = fc_1516c_av)_

**Comment by AnneV-Learn** [comment]
@geoff-fug Step A (from above list of steps) has been deployed to Test3 and is ready for testing.

**Comment by geoffj-FUG** [comment]
Anne

Looks good

Geoff

**Comment by DeniseColbert** [comment]
Deployed, closing

**Comment by AnneV-Learn** [comment]
FYI - All active users with role 'Master_county_coordinator' have now been updated to 'County_coordinator' role.
