### ISSUE TITLE
incorporate asset sources into pipeline

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#152]

**Comment by dougkdev** [comment]
The more I look at this, the more messy it seems.  The scss sources are not self-contained.  They have dependencies on an external css framework called inuit.css. We could copy the inuit.css sources directly into the project as has previously been done with the classie and html5shiv dependencies.  We will also need to copy the scss sources from the Core-Frontend and each application-specific frontend into the MyopicVicar project, reorganise the directory structure some, and update the rake task that copies the app-specific assets/sources into the correct place.

We will also likely need to make some modifications to the the asset pipeline manifest files / directives to reflect the changes and make sure things are included in the right order (and not multiple times).  I guess my lingering question is whether I am the right person to be doing this.  @AlexAvlonitis , are you more experienced than I am with the asset pipeline and organising scss?  If not I can keep at it, but if you are more experienced with that than I am, we should reconsider whether this is the best use of my time now that you are aboard full time.

**Comment by dougkdev** [comment]
The front-end styles are now compiled from the source .scss files instead of using the .min.css directly (except for the app/assets_freexxx/styles/css/icons.data.*.css files that are copied directly from the frontend projects). I changed a couple of files to .scss.erb so we can handle  app-specific color schemes, etc. in a single set of files instead of three separate sets of files.

Deployed to test2.

Although the majority of this story is now done, there are still a couple minor things still to be done before I mark this task as ready for user test, primarily:
1 - a couple of frontend bugs we previously fixed directly in .min.css are back because they have not yet been fixed in the source .scss files that are now being used instead
2 - static files in /public that are app-specific need handling by the rake task that copies site-specific assets.

I plan to finish those last couple of items at beginning of Jan before the scrum.

**Comment by Captainkirkdawson** [comment]
I did some searches on test2 and find the response extremely good.

![cen1](https://cloud.githubusercontent.com/assets/2874694/21409686/cf19f5c4-c798-11e6-85cc-16095d24431c.JPG)

**Comment by AlexAvlonitis** [comment]
Deployed Doug's latest changes to production.

**Comment by dougkdev** [comment]
Did the last couple of remaining things related to this task and deployed to test2.
