### ISSUE TITLE
262338100 Enhancement Suggestion (Chris Wood)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1520]
Issue reported by **Chris Wood** at 2023-04-25 07:41:40 UTC
Time: 2023-04-25T07:34:08+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
A suggestion for improvement to the handbook (transcribers and proofreaders): notes for the relationship field should say what to do in the case of there being no head. Normally the husband of a family is the head, but if he's away this often seems to leave the enumerator confused. Also a lodger can be the de facto head of a family - should it be left like this? Guidance would be good.

**Comment by DeniseColbert** [comment]
@geoffj-FUG to take a look

**Comment by geoffj-FUG** [comment]
A note has been added to the next version of the Handbook.
Chris has been advised.
Geoff

**Comment by geoffj-FUG** [comment]
This can now be closed.
Geoff
