### ISSUE TITLE
262337607 How to suggest an improvement to the handbook(s) (Chris)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1521]
Issue reported by **ceperman** at 2023-04-25 07:33:27 UTC
Time: 2023-04-25T07:29:50+00:00
Session ID: f9eb1e817e726dc979137019438eba98
Problem Page URL: [/cms/freecen-handbook](/cms/freecen-handbook)
Previous Page URL: [https://www.freecen.org.uk/manage_resources/new?locale=en](https://www.freecen.org.uk/manage_resources/new?locale=en)
Reported Issue:
I always struggle to find (as I am now) where to go to make a suggestion or improvement to a handbook. There should be a link on this page.    

![Screenshot](https://www.freecen.org.uk)

**Comment by geoffj-FUG** [comment]
I know that it will be obscure but perhaps we can add a Make a suggestion button to the Handbook Action Page. (At the Top so it is not completely lost). It should have a note beside it hat if you find an error or problem  in one of the Handbook Parts, please let us know here.

**Comment by Vino-S** [comment]
Ready for testing in test3:
FreeCen handbook app page:
https://test3.freecen.org.uk/manage_documents/freecen_handbook

**Comment by DeniseColbert** [comment]
@geoffj-FUG to test

**Comment by geoffj-FUG** [comment]
Vino

 

Tested OK using your link. I sent a suggestion and received it OK.

 

Can you make the email address that the message goes to ***@***.*** ***@***.***>  which is Userid somt.cen

The email that this came to is my private email which one of my test user ids is attached to.

 

Thanks

 

Geoff

**Comment by geoffj-FUG** [comment]
Spelling error in message (priorization):
A member of our team will review the feedback and should respond as soon as we can. If they determine that a system change may be appropriate then the feedback will be referred to the by-weekly project management for priorization along with other issues and feature requests. 

Geoff

**Comment by geoffj-FUG** [comment]
This is feedback on a Handbook. Can we include a word document in acceptable documents? A volunteer may need to send us a suggested script or will need to embed a screen grab in a document.

Geoff

**Comment by AlOneill** [comment]
Should "by-weekly" be "bi-weekly" or even "fortnightly" as it is less ambiguous (bi-weekly could mean twice a week; by-weekly is not a thing)?

**Comment by geoffj-FUG** [comment]
Alison

 

Go for fortnightly. Kiss principle!

 

Geoff

**Comment by AlOneill** [comment]
On the other hand, is fortnight understood widely? I do not think it is used in the USA, for example. Perhaps go for the most direct: every two weeks. The remainder of the sentence would need re-writing around it.

Also, 'priorization'  (or 'prioritisation') is hardly a friendly word.

**Comment by geoffj-FUG** [comment]
Alison

 

This started out as a simple change – I did not write it but have ended up testing it.

The text appears to be copied from somewhere else. 

Quote

A member of our team will review the feedback and should respond as soon as we can. If they determine that a system change may be appropriate then the feedback will be referred to the by-weekly project management for priorization along with other issues and feature requests.

Unquote

 

I agree with you on closer examination that it is a mouthful and not appropriate for a Handbook suggestion. I suggest:

 

Thank you for your suggestion about an amendment to the FreeCEN Handbook. A member of our team will review your suggestion and will reply to you as soon as they can. If they decide that a change to the Handbook is needed, then the change will be included in the next version of the Handbook. We will let you know the outcome of your feedback in due course.

 

That is a quick draft. Please amend it as you see fit.

 

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG 
I assume that text is for the email that acknowledges receipt of a suggestion or comment via the 'Feedback' button.

This is my suggestion. The changes are mainly to the voice although I've also indicated that the decision to include the suggestion or not will be a team responsibility rather than fall to any one individual as I assume that will be the case.

"Thank you for your suggestion about the FreeCEN Handbook. Our team will review your suggestion and someone will reply to you as soon as they can. If the team decides that the Handbook needs changing, then we will include that change in the next version of the Handbook. We will let you know the outcome of your feedback in due course."

**Comment by geoffj-FUG** [comment]
Alison

 

Looks good! I am happy with that.

 

Geoff

**Comment by DeniseColbert** [comment]
@AlOneill is everything ready for this to be deployed?

**Comment by AlOneill** [comment]
@DeniseColbert 
I have no idea! The updated Refinery page is at an address that I'm not familiar with:
https://test3.freecen.org.uk/manage_documents/freecen_handbook

@Vino-S what do we do now to publish the version of the page with "Make a suggestion"?

Also, I suggested changes to the email message but have they been implemented?

**Comment by DeniseColbert** [comment]
@Vino-S to check email changes and where this button/link is, also to see if it's possible to have the 'make a suggestion' feature appear below the blue island on the right of the page

**Comment by DeniseColbert** [comment]
@Vino-S to try including blue banner in javascript fix

**Comment by Vino-S** [comment]
Ready for testing in test3
https://test3.freecen.org.uk/cms/draft-freecen-handbook
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3F5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--777d8a8a70fbec9b233dbb23173224f50eec8897/image.png" alt="image.png" />

**Comment by DeniseColbert** [comment]
Make 'S' of suggestion lower case @Vino-S

**Comment by DeniseColbert** [comment]
Please make the change and deploy @Vino-S

**Comment by AlOneill** [comment]
@Vino-S 
I've edited "Suggestion" to be "suggestion" so you can get on with something that needs your skills!

**Comment by Vino-S** [comment]
Thanks @AlOneill

**Comment by DeniseColbert** [comment]
Denise to test

**Comment by DeniseColbert** [comment]
I think this was deployed? It seems to be on live...

**Comment by geoffj-FUG** [comment]
Agreed
Geoff
