### ISSUE TITLE
Add Gazetteer entry to Notes field

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1529]
We get a lot of contacts that are correcting the mispelling of a place of birth.

The gazateer entry is displayed to the user (for CSV files) and may not be understood by the user - info button may be needed.

It is however, possible, that the contacts are all coming from VLD files, and this solutin would not cut down on the work of the Coordinators / their assistants in dealing with contacts. Pat to investigate

**Comment by DeniseColbert** [comment]
Revalidation of VLD data will add all info to transcriptions but we need to explain on-screen what the (bracketed) info is.

**Comment by DeniseColbert** [comment]
Closing
