### ISSUE TITLE
Problem - There are two pieces in the PARMS with the same number

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1532]
@AnneV-Learn 
RG10_3220 has two other pieces attached to it. However they are both numbered RG10_3220A but in different counties.

Piece Number	Chapman_code	Piece name	District	Place	Civil parishes
The part in () is the name of any Hamlet, Township, Ward or Place included in the Civil Parish
RG10_3220	LEI	Lutterworth	Lutterworth	Lutterworth	Arnesby, Ashby Magna, Ashby Parva, Bitteswell
RG10_3220A	NTH	Lutterworth	Lutterworth	Lutterworth	Welford
RG10_3220A	WAR	Lutterworth	Lutterworth	Lutterworth	Copston Magna, Monks Kirby, Pailton, Stretton under Foss(Newbold Revel), Wibtoft, Willey

We need to make the following adjustment please:
RG10_3220A NTH Lutterworth /Welford to become RG10_3220B. 

Are you able to make this change, please? We understand that Rhoda cannot make this adjustment.

Geoff

**Comment by geoffj-FUG** [comment]
Coordinator is John  Topliss 
Geoff

**Comment by AnneV-Learn** [comment]
@Geoff The  'shared vld file' scenarios (which this has) are complicated and I don't yet completely understand the full implications of changing the piece number (fc2 PARMS) as requested above, without doing a lot of investigation and testing. How has the perceived issue manifested itself in the Freecen system?

**Comment by geoffj-FUG** [comment]
Anne
The change should not affect the Vld collection, which is where the transcription sits now.
John wants to download it ad convert it to a new style csv file. He cannot re-incorporate it as there are 2 pieces with the same number. That is why the piece needs re-numbering.
This is important when it comes to searching as it puts the civil parish into the correct county. 
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG thanks for the additional info. The various collections involved in uploading/incorporating data are very interconnected not just by the record id (main key) but some also store the piece number (not sure why - maybe to improve efficiency) so I’ll need to search through the collections dictionary before I can proceed. Should be doable though.

**Comment by geoffj-FUG** [comment]
Anne

 

In this case the vld will be downloaded and converted to a csv

Then it will be split into its parts and each part will be re-validated

Then the vld file will be deleted. At this point there is no data in either collection so all links are gone

Then the new parts will be Incorporated. Therefore all new links will be created to the csv collection.

 

Geoff

**Comment by AnneV-Learn** [comment]
Yep that is what should happen - just want to also check the code for the ‘shared VLD’ scenario, which I suspect was an after thought and not in the original design(?) to make sure that the additional links created in that case would be cleared etc.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Ok I checked the code and all looked to be ok so I have now made the update and checked all still looks ok. Could you please let John Topliss know and I think this can be closed when he is happy with the situation.

**Comment by geoffj-FUG** [comment]
Accepted by John T

Geoff
