### ISSUE TITLE
Information Needed - Census County and Census Place in Search

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1533]
When a County is selected in the search form the Census Place is populated.

Can you clarify please the exact data that is entered into the Census Place and its source.

My initial thought was that it was the Registration District from the PARMS. But some of the places are not Registration Districts. Similarly I don't surmise that they are civil parishes.

Hence my query. Can you please explain the logic used in this display @AnneV-Learn ?

Geoff

**Comment by AnneV-Learn** [comment]
Census Place is the Freecen2_Place linked to the Freecen2_Piece.
Links are held in a 'cache' which is updated every time new data is uploaded(VLD), incorporated(CSVProc) or deleted/replaced (and also I believe by background Rake task and runs regularly to catch any stragglers).
See below for example:

![Screenshot 2023-06-07 at 16.39.55.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/491ed3a9-8550-447a-b9f2-fe031f1e3dff)

![Screenshot 2023-06-07 at 16.41.17.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/5adefee9-781d-4af0-8489-652f42377771)

**Comment by geoffj-FUG** [comment]
Anne

If I read that correctly we are already searching on the census civil parish and no modifications to the search are needed to get to the civil parish level.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
Searching  is on the freecen2_place (gazetteer place) that is associated with a  freecen2_piece. Freecen2_places have civil parishes linked to them. I don’t know how the FC2 PARMS (Freecen2_pieces) were originally setup so can’t comment on what decisions were made when freecen2_pieces were linked to freecen2_places. Perhaps we need to discuss if it is still unclear.

**Comment by AnneV-Learn** [comment]
@Geoffj-fug Looking at other data recently I am not sure I gave to correct answer. I need to do more checking.

**Comment by geoffj-FUG** [comment]
Anne

 

I think it may be me who misinterpreted your answer.

 

Yes, the piece is linked to its own civil parish.

 

The PARMS has three levels below County – 

Registration District / Hundred / Wapentake etc depending on the year

Piece AKA sub District

Civil Parish.

 

The third level is the one we should get to.

 

The PARMS has a place recorded against the piece as the piece name. Given that several pieces can each have the same piece place can we extract the civil parishes from all pieces with a similar name? The civil parish is the place name outside of the brackets. I do not want to extract the hamlets etc inside of the brackets. It results in too many options.

 

One we have the selected civil parish we should automatically use a default surrounding area to search around the parish.

 

Your thoughts please?

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Having looked again I believe we are already Searching at the Civil Parish level. 
When a single County has been selected the list of Places (with the census years where we have data in brackets) are actually Civil Parishes. 
Example:
1. Searching for Surname HEYLOCK in Census County HUN and picking Abbotsley from the list of places and 1881 from the list of years yields:

![Screenshot 2023-06-24 at 17.58.29.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/d9f432e7-bc14-4475-8437-784fd55904c5)

2. But Searching for Surname HEYLOCK in Census County HUN and picking 'St Neots' from the list of places and 1881 yields: 0 Records.

3. However if I revise Search 2 and check the Nearby Places box it yields the same result record as Search 1 above.

I do find it all rather confusing as Civil Parishes 'names' can also be Gazetteer Place names (ie Freecen2 Places) (Abbotsley is one such example).

**Comment by geoffj-FUG** [comment]
Anne

 

How do we know that the place listed has records? 

 

Your answer will tell me how we manage this search, … I think ☹

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG only places that have records are included in the list, with only the years that have records in brackets. The list is managed as records are loaded(VLD)/incorporated(CSVPro) or deleted(VLD/unincorporated(CSVPro).

**Comment by geoffj-FUG** [comment]
I have done some research comparing the PARMS with the Display.

The level that is missing is Registration District. This level will probably be required to allow one search across all three systems.

Geoff

**Comment by DeniseColbert** [comment]
Research complete, another story supersedes, closing
