### ISSUE TITLE
PARMS Numbering in Warwickshire

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1534]
There are some problems with the PARMS for Warwickshire. The PARMS numbering needs fixing so that Rhoda can make the place changes. The following amendments are needed:

There are three entries for RG9_2230A. Remove the blank GLS entry. Amend the WOR PARMS to RG9_2230B . (I am not game to remove it in case it is needed as and when this piece is eventually broken up). Add Clifford Chambers to the GLS PARMS for RG9_2230A. 

There are two entries for RG12_2478A. Change the WOR entry to RG12_2478B and add Alderminster to it. Add Marston Sicca to RG12_2478 PARMS (WAR).

There are three entries for RG12_2485A. Add Shipston on Stour as a civil parish to one or the WOR entries. Remove the second WOR entry. Rename the GLS entry RG12_2485B as we cannot have RG12_2485A in two Counties.
RG12_2486 – add Longdon to RG12_2486A (WOR). Again, we have 2 counties for RG12_2486A. Rename GLS as RG12_2486B. (I am not game to remove it in case it is needed as and when this piece is eventually broken up).

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
I have made updates for first part of the request i.e.

_There are three entries for RG9_2230A. Remove the blank GLS entry. Amend the WOR PARMS to RG9_2230B . (I am not game to remove it in case it is needed as and when this piece is eventually broken up). Add Clifford Chambers to the GLS PARMS for RG9_2230A._

Could you please just check it is now as you want as there is a **shared** VLD file relating to the GLS RG2230A and WOR RG2230B but WOR RG2230B has no place linked to it?!? What place should it be linked to?

**Comment by geoffj-FUG** [comment]
Anne

Piece Name - link to Stratford on Avon. I presume that Alderminster is linked. If not it will link to Alderminster WOR. (Alderminster in RG9_2230 will be linked to Alderminster WAR).

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I have made the updates, so could you please check it is now as you require.

**Comment by geoffj-FUG** [comment]
Entries now correct. We can close this issue.

Geoff
