### ISSUE TITLE
Adjustment of verbatim place of birth in the VLD Collection

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1535]
I have discovered that some coordinators have been allowing unk through as a valid place of birth in the vld collection (it creates a Warning in the csv collection and is therefore not an issue). 

Can we do a find ... replace where the verbatim place of birth is exactly unk and replace it with a hyphen (-) please?

This will remove a significant number of Warnings when we come to re-validate the vld collection.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Are you able to send me the details of a specific VLD file(s) that have this issue?
This kind of update could put a significant load on the servers so I need to work out the best way to tackle it 
(or in fact if it is feasible at all given the number of VLD records and the fact that birth place is not indexed) 
and track through to the Search record that will have been created.

**Comment by AnneV-Learn** [comment]
@Geoffj-FUG I’ve had another idea on this. This update could be made as part of the ’Automatic’ validation step outlined in your POB validation for VLD data specification. As that process will be checking every VLD entry so this approach might be the most efficient way to handle it. #1458

**Comment by geoffj-FUG** [comment]
Anne

 

I envisaged the automatic validation running only once. Otherwise it would reset previous work.

 

However if it only runs on False records it could be used like Re-Process File in the Validation screen menu. That would allow me to enter a place in the Gazetteer and then clear all entries that had that place.

 

Geoff

**Comment by cmahoneynz** [comment]
There will be situations where the county code is UNK, but we have a place name which we do want to leave as is.

It is not that unusual, especially among earlier years where the enumerator has entered a place name, but made no reference to a county.  While some will be obvious as to which county is being referred to there will be others where the listed name could mean any number of different places in different counties.

By leaving the place name gives researchers a name in which to work with even if we don't have a county.

**Comment by geoffj-FUG** [comment]
Anne

To be absolutely clear and to cover Chris' comment:

If the verbatim chapman code is UNK or any other valid Chapman Code and the verbatim POB is exactly Unk then the verbatim POB becomes a hyphen (-). 
If the verbatim chapman code is UNK or any other valid Chapman Code and the verbatim POB is Null then the verbatim POB becomes a hyphen (-).
If the verbatim chapman code is UNK or any other valid Chapman Code and the verbatim POB is NOT Unk and is NOT Null then the verbatim POB is not amended.

Geoff

**Comment by geoffj-FUG** [comment]
Chris

 

Note added to story for clarification.

 

Geoff

**Comment by DeniseColbert** [comment]
Handled by work in #1458

**Comment by DeniseColbert** [comment]
Done, closing
