### ISSUE TITLE
Remove OVB from validation options

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1538]
I notice that OVB still exists in the validation Chapman Code options. It needs to be removed.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG just want to check something before making this change.
When editing a CSV entry record it shows the following 2 fields:
Verbatim Birth County; _current value highlighted_ 
and
Birth County; _current value highlighted_.
If I remove OVB from the dropdown against those fields and the value in the field is actually OVB 
it won't be able to _highlight it in the list_ because it won't be in the list.
Is that OK?

**Comment by geoffj-FUG** [comment]
Anne 
I Agree.
This story should be actioned as soon as the last OVB change to OVF has been run.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG This is ready for testing on Test3 now.

**Comment by geoffj-FUG** [comment]
Anne

 

I have a problem on test3.

 

I have tried three SOM files and got the same result:

The first 2 were pieces that I had started validation on. I selected a Warning from the list and clicked Display. I got the dreaded red warning!

We're sorry, but something went wrong with processing your request. A report has been produced and sent to the webmaster. Please return to your prior activity but try to avoid doing the exact same action again.

So I went back and tried a third piece that I had to commence validation on in case there was something strange from a previous test. – Same result.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG - started to look at it and the same thing happened to me when trying to display a record in a CSVPro file. 
I’ll have to investigate further.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG The issue on Test3 has now been resolved I believe (it was unrelated to my recent modifications).

**Comment by geoffj-FUG** [comment]
Looks good. This can me deployed.

Geoff

**Comment by DeniseColbert** [comment]
@Vino-S to check if it's ready to be deployed

**Comment by DeniseColbert** [comment]
Deployed but Vino will close once rake task is set up to run on 1st of each month
