### ISSUE TITLE
Amend Piece Numbers in PARMS that impact NTT

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1542]
Chris M wrote

I have are four 1881 pieces, all officially under Nottingham as that is where they were administered from, and uploaded as VLD's under Nottingham, but in the case of these four pieces, none actually have any civil parishes that are in Nottingham.

Pieces in question are:
RG11_3308  (all parishes are in Yorkshire West Riding, and should be named RG11_3308A)
RG11_3309  (all parishes are in Derby, and should be named RG11_3309A)
RG11_3314  (all parishes are in Derby, and should be named RG11_3314A)
RG11_3326  (all parishes are in Derby, and should be named RG11_3326A)

As none of these actually need splitting into two, is there something we 
can do, such as simply renaming them to get these pieces showing up in 
the counties that match where the civil parishes actually are without 
the need to re validate the pieces.

I will tell Chris that he has to re-validate these once the change is made.

Geoff

**Comment by AnneV-Learn** [comment]
@Geoff - sorry I am obviously missing the point here.
When I look at the pieces (which already exist with the A suffix) - I see the following:![Screenshot 2023-06-15 at 11.46.47.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/749d75ac-fd70-46f2-bc1e-1807fddf46a6)
![Screenshot 2023-06-15 at 11.49.33.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/5ee9c883-0df5-4275-a7cf-f3a330dcf40b)
![Screenshot 2023-06-15 at 11.50.34.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/592bbc9b-b4a7-4286-a1ea-7df70430cf1f)
![Screenshot 2023-06-15 at 11.52.33.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/9f9ffbfb-d9cd-48fa-92bb-cbf190944f84)

Can you clarify please.

**Comment by geoffj-FUG** [comment]
Anne

 

Sorry, I should have checked. Chris is usually spot on.

 

Geoff
