### ISSUE TITLE
Next/previous dewelling "buttons" are missing

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1543]
The buttons for viewing preceding and subsequential households are missing - I haven't used this function for a while but wanted to today in order to find examples of the standardised place of birth or as transcribed place of birth not being used on a recently transcribed piece.

**Comment by DeniseColbert** [comment]
I can see it:

![image](https://github.com/FreeUKGen/FreeCENMigration/assets/19173257/27514f57-1230-4f35-bd06-aa147259dbe2)

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG were you on mobile by any chance?

**Comment by DeniseColbert** [comment]
Deployed, closing
