### ISSUE TITLE
Coordinators need to be able to see every piece under their control in reports

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1544]
When a piece crosses a county border it is broken into parts and parts receive a suffix of A, B C, D etc.

When we obtain a report such as the County Statistics and select a specific year in a specific county we get a list of all pieces in that county. However the parts that are in a different county are not listed. They are listed in the county in which the civil parishes belong.

The coordinator responsible for managing the county is the coordinator where the Hundred / Registration District belongs, not the county where the civil parish belongs. The coordinator cannot see the parts that are recorded in a different county and therefore cannot necessarily see that a piece has been split. Neither can they use the report as a management tool.

A Coordinator needs to be able to see all the parts of each piece that they are responsible for.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Could you please give me a specific example to help me work out how to resolve this.

**Comment by geoffj-FUG** [comment]
Anne

 

The following piece crosses the SOM border so that some of it is in GLS.

 


1944

Bitton

Kelston, North Stoke


1944B

Newton

Burnett, Compton Dando(Tucking Mills;Woolard), Corston, Marksbury(Houndstreet), Newton St Loe, Priston(Wilvington), Saltford, Stanton Prior


1944C

Keynsham

Brislington, Keynsham(Chewton Keynsham), Queen Charlton, Whitchurch


1944D

Bitton

Bitton, (Bitton;Hanham), Siston


1944E

Oldland

Bitton, (Kingswood;Oldland), Mangotsfield

 

If you call the county statistics for SOM and then select 1851 you will see that only the following pieces are listed:

 


HO107_1944

Bitton

Online (08/Jun/2018 16:18)

["ho511944.vld"]

		

HO107_1944B

Newton

Online (08/Jun/2018 16:18)

ho511944.vld

		

HO107_1944C

Keynsham

Online (08/Jun/2018 16:18)

ho511944.vld

		

 

If you call the same report for GLS you will find


HO107_1944D

Bitton

Online (08/Jun/2018 16:18)

ho511944.vld

		

HO107_1944E

Oldland

Online (08/Jun/2018 16:18)

ho511944.vld

		

 

They are not listed in the SOM report despite SOM being responsible for transcription as they are in a SOM Registration District.

 

Geoff

**Comment by AnneV-Learn** [comment]
@GoeffJ-fug
Drilling down I see that HO107_1944D and HO107_1944E are linked to districts in GLS ?!, what logic can determine that they are actually for SOM? If it is the presence of a suffix, is it the first piece (when ordered alphabetically) that holds the ‘appropriate’ County?

**Comment by geoffj-FUG** [comment]
Anne

 

The piece belongs to a Registration District. (One Registration District has many civil parishes).

 

The Registration District belongs to one county (One County has many Registration Districts).

 

Therefore, the entry needs to be reported against the county of the registration district.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Where are Registration Districts recorded in Freecen2? 
(As I commented -  HO107_1944D and HO107_1944E are linked to **districts** in GLS, so I guess they aren’t the Registration Districts)

**Comment by geoffj-FUG** [comment]
Anne

 

The PARMS has four levels:

County

Registration District

Sub District (which is a Piece)

Civil Parish.

 

Each level has a one to many relationship with the level below it.

 

Geoff

**Comment by AnneV-Learn** [comment]
Yes. 
Sorry this is going on a bit.
Now looking at 2 of the Pieces in your example just for illustration purposes.
**Piece HO107_1944C**:
Belongs to FreeCen2 District **Keynsham** in **SOM** _(a)_
![Screenshot 2023-07-04 at 15.07.23.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/a270cc55-04f8-4fb3-9c3f-e8dc52d5c126)
So that indicates **Registration District Number 327**
 (interestingly it shows no VLD files for this district but we know there is a shared VLD file! - that could be a different issue)
**Piece HO107_1944D**
Belongs to FreeCen2 District **Keynsham** in **_GLS_** (ie a different Freecen2 District record from _(a)_ above)
![Screenshot 2023-07-04 at 15.13.22.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/ebf569c2-b9e6-4a59-adec-2d5e66e7a890)
This also indicates **Registration District Number 327**
But what logic can be used to decide which County actually 'owns' the Registration District 327? 
i.e. 
how can I determine whether HO107_1944C should appear in SOM in the list of Pieces in the Stats Report or in GLS list 
and conversely
how can I determine whether HO107_1944D should appear in GLS in the list of Pieces in the Stats Report or in SOM list.

**Comment by geoffj-FUG** [comment]
Anne

 

I am not sure what Kirk did when he set up the PARMS. I wanted to set up two fields – the county in which the original piece was administered and the county that the place was actually in. I was over-ruled.

 

So, in this case the district in GLS is a hypothetical district. Keynsham is actually in SOM. 

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
I can’t see anyway of resolving this with the database structures we have at the moment. 
One way to resolve would be to have each FC2 Piece record the administration county (as you say above). This presumably would be the same as the County for the Piece Place for  the majority of Pieces with just the split Pieces being different. They would have to be set via a ‘manual’ process. So Rake task  to populate all but split Pieces then split Pieces populated via a different Rake with a mapping file as input. 
How are split Pieces dealt with for CSVProc data - the same way I presume(?). 
Still a bit confused as in the example the data for ‘all’ HO107_1944 data has been loaded via ONE VLD file (database records have shared_vld_file populated). 
The List of Pieces (from the County Stats drilldown report) could then use the admin county). 
Of course there could be other implications!
What would/should the impact be on the County that files are ‘loaded’ into (if any), 
What about the County Stats numbers themselves!?
How often does the split piece scenario occur???
All rather complicated but if it means the County Coordinators have a ‘total’ handle on their domain I guess it might be worth it. 
Not my decision to make.

**Comment by geoffj-FUG** [comment]
Anne

 

Some history:

There was a problem with searches in FC1. Take Appledore Devon as an example. 

If Joe Bloggs was born in Appledore DEV and I searched for it via our current search in FC2 I would not find him. Why? Because Appledore came under a sub District of Culmstock DEV and a Regn District of Wellington SOM. But a search under Appledore SOM would have located Joe.

 

So in FC2 it was decided to put every place into its correct county. This involved breaking up the TNA piece numbers into smaller parts (A, B, C etc) and treating them each as smaller pieces. These smaller pieces were hung off a pseudo Registration District, in this case Wellington DEV. 

 

The result is that when we try to report the inter county pieces are reported in their physical counties instead of their administrative ones. Coordinators manage the administrative counties. Unfortunately almost all of these problem pieces cross county lines and therefore have two or more counties recorded within them. We cannot just say ‘well you manage this piece and that will fix it’. 

 

We are now in a transition situation. All the old vld files have the entries in different counties mixed together. The csv files are broken into parts and the new pieces are in the correct counties for searching purposes. Once the civil parishes that are being adjusted by Rhoda at the moment are completed I am going to get coordinators to break up these vld files and re-validate them as csv to tidy up the data.

 

I hope that that all makes sense.

 

Geoff

**Comment by DeniseColbert** [comment]
@geoffj-FUG to determine the rules so that Coords get the right list

**Comment by geoffj-FUG** [comment]
The solution seems to be the same one that we used to identify whether an HO piece was 18841 or 1851.
There is a number range for each county for each year. If these are put into a table that table can be used to identify the owning county of each piece. The table should not include the suffix A, B etc that is added in the PARMS.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG ok. where can I find the number range for each county for each year?

**Comment by DeniseColbert** [comment]
If @Vino-S can send @geoffj-FUG a CSV dump of the PARMS with county, piece number and registration district, Geoff might be able to work this out

**Comment by DeniseColbert** [comment]
@Vino-S to send to Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I will email you a CSV file of the production FC2 PARMS which I hope will meet your requirement.

**Comment by geoffj-FUG** [comment]
Thank you Anne
The spreadsheet has been sorted by prefix and then piece number so that all county pieces are now listed together. Out of county pieces show up because the county name is mixed into the incorrect county.
I have forwarded a copy to each coordinator.
I have forwarded a copy to Rhoda for her information.
I have forwarded a copy to Anne so that she can see which group of numbers belong in each county. This provides the number boundaries to enable the County statistics to record the pieces belonging to each coordinator.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Looking at some entires in the file you sent out could you please clarify how I determine which County Stats listing (ie under which 'administrative' County) the ones highlighted below (for example) should fall into. (Still a bit confused as to how to resolve the original issue for this story.)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHlqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--573946d858d15c8f45ff74b437ca1516a511aae9/Pieces_Counties_1544.png)

**Comment by geoffj-FUG** [comment]
The spreadsheet of PARMS entries is the key. 
1841 BDF starts at HO107_1 and ends at HO107_10
1841 BRK HO107_11 to HO107_37
1871 SOM RG10_2348 to RG10_2518

Any A B etc suffixes at the end of the piece id and within the county/year range belong in the same Registration District as they fall in the main numbering sequence, so that is the County of the Coordinator. 
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Do you want an 'Admin_County' field added to the Piece Collection so that we can record the Administration County (based  above 'rules' and the PARMS spreadsheet data) and use that to drive the County Stats 'drilldown' report or will the County Coords just use that spreadsheet?

**Comment by geoffj-FUG** [comment]
Anne

 

Admin County sounds like a good solution.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this has now been deployed to Test3 for you to review. 
An example of what the output from the County Stats 'drilldown' now looks like. 
You will see that for SOM 1851 Piece HO107_1921D (owned by County DEV) now appears in the list of pieces. The 'owning' chapman code is shown in brackets after the Piece number. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0k3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82ea7a88bc491a7fe13e914ff348e77caaba31da/Screenshot%202023-10-16%20at%2013.51.37.png)

**Comment by geoffj-FUG** [comment]
Anne

I think that this is far better. The strays at the beginning of the report have also disappeared and that is good.

This can be deployed.

Geoff

**Comment by AnneV-Learn** [comment]
Deployed 25/10

**Comment by DeniseColbert** [comment]
Done: closing
