### ISSUE TITLE
Change number of SFK piece in PARMS

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1545]
The PARMS has a repeated piece number affecting NFK and SFK:

Piece Number	Chapman_code	Piece name	District	Place	Civil parishes
The part in () is the name of any Hamlet, Township, Ward or Place included in the Civil Parish
HO107_1832	NFK	Methwold	Thetford	Methwold	Cranwich, Feltwell St Mary and St Nicholas(Feltwell Anchor), Hockwold cum Wilton(Redmoor), Lynford, Methwold, Mundford, Northwold(Whittington), Santon, Sturston, Weeting with Broomhill(Broomhill), West Tofts
HO107_1832A	NFK	Thetford	Thetford	Thetford	Brettenham, Croxton, East Wretham, Great and Little Snarehill, Kilverstone, Rushford(Shadwell), Thetford St Mary, West Wretham
HO107_1832A	SFK	Methwold	Thetford	Methwold	Brandon
HO107_1832AA	SFK	Thetford	Thetford	Thetford	Barnham, Barningham, Coney Weston, Euston(Little Fakenham), Fakenham Magna, Hepworth, Honington, Hopton, Knettishall, Market Weston, Rymer, Sapiston

Please change the number of HO107_1832A SFK to HO107_1832B

Thanks

Geoff

**Comment by AnneV-Learn** [comment]
Done.

**Comment by geoffj-FUG** [comment]
Bev confirms that this is now as she needs it.

Can be closed.

Geoff
