### ISSUE TITLE
Amend ED Input mask

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1546]
The ED input mask is currently xxxa. How difficult is it to amend it to xxxaa please, where the last a is ‘can enter a digit or a letter'.
 
It will not affect the integrity of any existing data as it is an extra optional character.

Query - will this affect the report form displayed to volunteers.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I've made the change to allow the new pattern match and it is ready for testing on Test3. 
(It appeared to look ok in the report form displayed to volunteers and in Search Records results when I did some local testing)

**Comment by geoffj-FUG** [comment]
Anne
I have tested this with both letters and numbers in the new position in the mask. They are both working fine.
This can be deployed

Geoff

**Comment by DeniseColbert** [comment]
Done, closing
