### ISSUE TITLE
268482968 Age errors (Ali)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1547]
Issue reported by **AH001** at 2023-07-05 10:36:08 UTC
Time: 2023-07-05T10:34:02+00:00
Session ID: 39b33e1070ce6f8b694c2647df7afbb5
Problem Page URL: [/freecen_csv_files/my_own?locale=en](/freecen_csv_files/my_own?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen_csv_files/645f4cc9f493fd65a7300a6f?locale=en](https://www.freecen.org.uk/freecen_csv_files/645f4cc9f493fd65a7300a6f?locale=en)
Reported Issue:
Please could we have age 999 included in error warnings?     

![Screenshot](https://www.freecen.org.uk)

**Comment by geoffj-FUG** [comment]
999 cannot be an Error. It can only be a Warning.

If it generated an Error it would never be possible to get past it as the system stops progressing to Validation or Incorporation.

@AnneV-Learn - Making 999 a Warning is worthwhile. How big a task is it to add it to the Warning messages. Currently we test for 1d to 120y and let 999y pass. An age outside the 1d to 120y range generates an Error. 999 y is entered when there is no age or it is unreadable. It should not generate an Error so the current test stays. We need an additional test that generates a Warning if 999 has been entered as an age.
The test message should be Warning - 999 is an unusual age.

Geoff

**Comment by suffolkroots** [comment]
I'm sorry I meant please could we have it in the warnings list?

**Comment by AnneV-Learn** [comment]
@geoffj-FUG This is now ready for testing on Test3.

**Comment by geoffj-FUG** [comment]
Anne
Looks good.
I tried on a new upload and also on a reprocess file and both displayed the correct warnings.
Can be deployed.
Geoff

**Comment by DeniseColbert** [comment]
Done, closing
