### ISSUE TITLE
Ignore Marriage status in searches of 1841 censuses

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1548]
A user has found searching for marital status (e.g. Married) in the 1841 census returns no results - whether this is in an initial search or by refining a successful initial search.

How to support users?
e.g. add warning re 1841 census in the search box?  
ignore in the field in the 1841 census?

**Comment by DeniseColbert** [comment]
"Help" improvements story made, closing
