### ISSUE TITLE
Places called Over not appearing in Gazetteer search

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1559]
We have a problem where places called 'Over' are not appearing in Gazetteer searches. To my knowledge there is one in CAM and one in LAN (as a minimum).
We had this problem a couple of years ago and Kirk did a fix. The problem is back again.
Geoff

**Comment by DeniseColbert** [comment]
There is a note on stop words on Gazeteer search. @geoffj-FUG to let Coords/volunteers know

**Comment by geoffj-FUG** [comment]
I have written an item covering this. It has beed sent to Chris for inclusion in the next Newsletter due early October.
I have also added a paragraph about them to the next version of the Handbook.
Geoff

**Comment by geoffj-FUG** [comment]
Item published in October newsletter.
This info has also been included in the draft of the next version of the Handbook.
Geoff

**Comment by DeniseColbert** [comment]
Closing
