### ISSUE TITLE
Correction of Kent PARMS

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1561]
Beki house reports a problem with a piece number being duplicated. 
It is 1841 Kent piece as below:
KEN	HO107_477B	HO107	477B	Aloesbridge	Aloesbridge	Brenzett, Brookland, Fairfield
KEN	HO107_477C	HO107	477C	Bircholt Franchise and Barony	Bircholt Franchise and Barony	Aldington, Bircholt, Brabourne(East Brabourne;West Brabourne)
KEN	HO107_477E	HO107	477E	Folkestone	Folkestone	Alkham, (Reindon House), Capel le Ferne, Cheriton(Sandgate), Folkestone(Sandgate)
KEN	HO107_477F	HO107	477F	Lovingborough	Loningborough	Acrise, Elham
KEN	HO107_477G	HO107	477G	Newchurch	Newchurch	Bilsington
KEN	HO107_477H	HO107	477H	Oxney	Oxney	Ebony
KEN	HO107_477I	HO107	477I	Stouting	Stouting	Elmsted
KEN	HO107_477J	HO107	477J	Street	Street	Bonnington
SSX	HO107_477K	HO107	477K	Romney Marsh	Goldspur	Broomhill
KEN	HO107_477K	HO107	477K	Romney Marsh	Romney Marsh	Aldington, Bilsington, Blackmanstone, Bonnington, Brenzett, Burmarsh, Dymchurch, Eastbridge

You will see we have two 477K. (At this point I will point out that I made an amendment to the spreadsheet as one of these was recorded as H107_477K. Geoff)
The division is correct as the portion highlight in blue, Broomhill parish, sits in Sussex (at the time of 1841 census the parish was within the boundaries of the district of Romney Marsh which is Kent). Broomhill has always been in Sussex. Around 1850 its governance was moved out of Romney Marsh district back into a Sussex one so did not continue to be an issue.

Can we change the Romney Marsh 477K to 477L. I have had a look at the full piece 477 and can confirm that doing so will not effect the transcription, checking, validating or uploading process adversely.

Will leave this with you. Obviously not a high priority. I have made a note in my tracking spreadsheet that this issue needs to be dealt with before issuing the piece. 

Cheers Beki

So we need to change one of these entries to HO107_477L 
Geoff

**Comment by AnneV-Learn** [comment]
Requested change made 
![IMG_9974](https://github.com/FreeUKGen/FreeCENMigration/assets/72746727/83454bfd-f44f-45fd-84e6-9b0a635dabaf)

**Comment by DeniseColbert** [comment]
@geoffj-FUG to email Becki

**Comment by geoffj-FUG** [comment]
Beki confirms now corrected and she is happy. 
Geoff
