### ISSUE TITLE
274868047 Website Problem (Pat Reynolds)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1562]
Issue reported by **Pat Reynolds** at 2023-09-17 08:14:07 UTC
Time: 2023-09-17T08:12:56+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
Pages are not always displayig correctly - e.g. https://www.freecen.org.uk/search_records/619bc0daf493fd864c8fd5c7/william-rowntree-1861-yorkshire-north-riding-scarborough-1806-?locale=en does not show previous/following census entry 

This record was found by a search, not a saved url.

**Comment by AnneV-Learn** [comment]
Problem [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVdvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--197a07d94ecaa9c5a16e1279c99682c386ed6b65/IMG_9966.png)
occurs when displaying the first result from the search

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG this has now been fixed. Closing
