### ISSUE TITLE
All buttons missing from results page on iphone

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1563]
All buttons (New Search, Revise Search, Back to Results …..) missing from search results page when running on iPhone in Safari. 
NB the Accept ‘cookies’ pop-up dint appear either. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEc5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--825cdfd83435fc0bab5f419301efd57c83538885/IMG_9975.png)

**Comment by AnneV-Learn** [comment]
It happened when I searched for surname = Markham, census county = CAM and clicked the Detail button on the first result

**Comment by AnneV-Learn** [comment]
I tested on Test3 on my iPhone and there is still a problem. I searched for surname = Markham, census county = CAM and clicked the Detail button on the first result:

<img width="1731" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDg0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38374b1b7053cd6d6965821e13fba7d7e6446731/IMG_0288.png" alt="IMG_0288.png" />
<img width="1731" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUE0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--464728cbe96c55cf3a4da3820491ac18001ee16f/IMG_0289.png" alt="IMG_0289.png" />

**Comment by DeniseColbert** [comment]
@Vino-S to investigate

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
@AnneV-Learn could you test this on iPhone please?

**Comment by AnneV-Learn** [comment]
@Vino-S 
On my iPhone the first results page now looks ok but when I click down to the DETAIL page there are no buttons at the top of the page (see attached screenshot)
![IMG_0381](https://github.com/FreeUKGen/FreeCENMigration/assets/72746727/8b11c80a-8a68-4b2e-843f-ba57d1c5f6b6)

**Comment by DeniseColbert** [comment]
Done, closing
