### ISSUE TITLE
St Stephens Validation

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1564]
I have identified a problem during validation that indicates a problem with the identification of POBs in the Gazetteer.
St Stephens by Launceston is identifies colloquially as just St Stephens. However this entry s not in the Gazetteer and neither should it be. St Stephens by Saltash for instance is also referred to locally as St Stephens.
The following are the results of a search on Stephens in CON:

Coombe	**St Stephen in Brannel Coombe,** Kea Coombe	CON	50.326822	-4.880105	Location	Wikipedia		Edit
**St Stephen in Brannel**		CON	50.340809	-4.896413	Location	Gazetteer of British Place Names		Edit
**St Stephens Coombe**		CON	50.327685	-4.881563	Location	Genuki		Edit
**St Stephens by Launceston	St Stephens with Newport, Launceston St Stephens**	CON	50.646845	-4.370559	Location	Gazetteer of British Place Names		Edit
**St Stephens by Saltash**		CON	50.400315	-4.238618	Location	Gazetteer of British Place Names		Edit
Trematon	Saltash Trematon, **St Stephens by Saltash Trematon**	CON	50.408756	-4.267165	Location	Gazetteer of British Place Names		Edit

Yet when I examine the spreadsheet during validation all the St Stephens entries have been accepted. 

I have resolved the problem by amending the POBs so that our searches will be correct.

My question is why is St Stephens accepted when it is not in the Gazetteer?

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG It is accepted because the validation of POB checks 'original' county and place fields in the Gazetteer too and counts the POB as valid if there is at least one match on these (see screenshot below). 
I don't have any background knowledge of these 'original' fields - do you?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2hTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4f4dccd6ddc4e00c5e1513d2278b43e2e9eb3cf/Screenshot%202023-10-19%20at%2013.46.14.png)

**Comment by geoffj-FUG** [comment]
Anne

 

The image below is part of the description which appears when you click on a place name in the Gazetteer search results.

 

The Freecen2 Place St Stephen in Brannel in Cornwall (CON)

 <https://www.freecen.org.uk/freecen2_places/5fc6db76f4040beff481659e/edit?locale=en> Edit Freecen2 Place Information  <https://www.freecen.org.uk/freecen2_places/new?locale=en> Create New Freecen2 Place  <https://www.freecen.org.uk/freecen2_places/5fc6db76f4040beff481659e?locale=en> Delete Freecen2 Place


FIELD

VALUE


Place Name [Standard Name]:

St Stephen in Brannel [st stephen in brannel]


Original Place Name [Standard Original Name]:

St. Stephen [st stephen]


County:

Cornwall


Country:

England


Grid Reference:

SW940530


Latitude:

50.340809


Longitude:

-4.896413


Location: Opens in new tab

 <https://www.google.com/maps/search/?api=1&query=50.340809,-4.896413> Location

 

The original place name is the name that was originally entered for a place. It may have been refined as it has been in this instance.

 

So, St Stephens was the original download from the Gazetteer of British Place Names for at least three CON entries – St Stephen in Brannel, St Stephens by Launceston and St Stephens by Saltash. We cannot work with that as we want place names to be distinctive so that we can link them for searching purposes.

The Place name in the example above has been amended from the original St Stephens to the distinct St Stephen in Brannel which is what we should now be using for testing.

 

As far as I am concerned the original St Stephens should no longer be tested. Some of these got changed if they are entered by validators and later found to be incorrect. Some were also changed to make our Gazetteer contain distinct names for searching purposes. 

 

We should not be using the original place name for testing as it is now purely academic. We probably need to keep it as it was downloaded from the source of the entry. I am not aware of the reason for the test – it may be a FreeREG need as the Gazetteer was developed from their version. In fact typing this I realise that we may have copied the three amended places from them as they need to identify distinct parishes.

 

Incidentally I am now sure that I have seen this name problem previously but did not twig until it involved three nearby civil parishes and hundreds of entries. This need fixing before I start on the vlds or we will miss some entries that need amending.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Ok I have removed the code that validates against 'original place name' and it is ready for Testing
 on Test3.

**Comment by geoffj-FUG** [comment]
Anne
That looks a lot better. When I tested the file that I found the problem in, the Warnings identified 392 entries that were missed when I validated the live file.
Ready for deployment.
Geoff

**Comment by AnneV-Learn** [comment]
Deployed 25/10

**Comment by DeniseColbert** [comment]
Done: closing
