### ISSUE TITLE
275660791 Website Problem (Richard Francis)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1567]
Issue reported by **Richard Francis** at 2023-09-26 12:26:31 UTC
Time: 2023-09-26T12:23:10+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
When you find a census entry and then use the facility to move to "Previous Dwelling" or "Next Dwelling" and then select "Printable Format" it is the originally found entry that is displayed rather than the one you have moved to, which I think would be more logical and user friendly.

**Comment by DeniseColbert** [comment]
Vino is working on this

**Comment by DeniseColbert** [comment]
Tested, works as expected

**Comment by DeniseColbert** [comment]
Done, closing
