### ISSUE TITLE
Scotland Coordinator permissions

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1568]
Margaret Singleton tells me that she does not have the report vld pieces without civil parishes available to her.

Can we please give her the permission to access that report and also make sure that she is able to Edit Civil Parishes in vlds.

Geoff

**Comment by AnneV-Learn** [comment]
Deployed straight to Production (as can't easily be tested on Test3) 24/10

**Comment by DeniseColbert** [comment]
Closing as deployed
