### ISSUE TITLE
Move Betlow Links

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1569]
Ali reports that 
There are 2 entries for Betlow - one in BKM and one in HRT.
The BKM entry is incorrect so I have amended the place name by appending Incorrect Entry to it so that it can no longer be identified when a piece is validated or incorporated.
Can the links to the BKM entry please be moved to the HRT entry and the BKM entry deleted.
Geoff

**Comment by suffolkroots** [comment]
The links and place information for the HRT entry are correct, please do not remove. Deletion of BKM entry is sufficient

**Comment by geoffj-FUG** [comment]
Ali

 

There are search links to the BKM entry. We need to move them to HRT.

 

Geoff

**Comment by suffolkroots** [comment]
This was a difficult place to pin down, re info, website and lat/long.
It would be more accurate please if the info in the HRT entry was retained.
Or am I confused re search links and place links? 
Apologies if so.

**Comment by geoffj-FUG** [comment]
Ali

The farm that now exists is in HRT, Tring which it is referenced against and Long Marston that it is referenced against are both in HRT today.
However Genuki shows Tring in BKM in 1831 together with Long Marston and Wilstone.
The Gazetteer of British Place Names has all three places in HRT but there is evidence that they were in BKM and moved at some point (Possibly 1844?).
I believe that we should leave both entries (HRT and BKM) in the Gazetteer.
I have amended the Gazetteer to reflect this. I will close this story.
Geoff
