### ISSUE TITLE
No of Rooms Occupied is missing from 1891 validation screen

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1578]
Bev advised that the number of rooms occupied field is missing from the validation form. I have had a look at the form and the field is missing.

Can it be added please?

Geoff

**Comment by AnneV-Learn** [comment]
Ready for User Testing on **Test3**

**Comment by DeniseColbert** [comment]
@geoffj-FUG could you test this please?

**Comment by geoffj-FUG** [comment]
The number of rooms field is now showing in the initial display but when I go to the edit screen it is still missing.
Geoff

**Comment by AnneV-Learn** [comment]
@Geoff-FUG isn't 'number of rooms' part of the 'dwelling and so can't be edited online?

**Comment by geoffj-FUG** [comment]
Anne

 

Thank you. I missed that!

 

So this is now OK to go.

 

Geoff

**Comment by DeniseColbert** [comment]
Done; closing
