### ISSUE TITLE
Cannot add place names to gazetteer

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1579]
I cannot add some place names to the Gazetteer. For instance:
If I search for Brighton SSX I get Brighton St James, Brighton St Peter and Brighton Hove. None of these is exactly Brighton so an entry of Brighton SSX is not accepted at validation.
If I try to add Brighton as an alternative name to Brighton St James I am told that Brighton already exists.
If I amend Brighton St James to Brighton (an experiment) I am told that the existing alternative names already exist.
We should only be testing the places that are added or amended, not those that are carried through. Why does the rejection of the addition of Brighton happen?
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
The reason that Brighton can not be added to the Gazetteer is because there is a **disabled** place for Brighton (see info below). I can delete that entry or remove the disabled flag. I favour deleting it. Let me know your decision.
{
	"_id" : ObjectId("5fc6de4ef4040beff482482c"),
	**"disabled" : "true"**,
	"cen_data_years" : [ ],
	"country" : "England",
	"county" : "Sussex",
	"chapman_code" : "SSX",
	"place_name" : "Brighton",
	"last_amended" : "5-Nov-20",
	"grid_reference" : "TQ3104",
	"latitude" : "50.820734",
	"longitude" : "-0.141609",
	"source" : "Gazetteer of British Place Names",
	"genuki_url" : "http://www.genuki.org.uk/maps/gmap?GR=TQ310060&PLACE=BRIGHTON&CCC=SSX",
	"place_notes" : "",
	"original_country" : "England",
	"original_county" : "Sussex",
	"original_chapman_code" : "SSX",
	"original_place_name" : "Brighton",
	"original_grid_reference" : "TQ3104",
	"original_latitude" : "50.820734",
	"original_longitude" : "-0.141609",
	"original_source" : "Gazetteer of British Place Names",
	"reason_for_change" : [
		"",
		"Add Alternative Place Name"
	],
	"other_reason_for_change" : null,
	"master_place_lat" : "50.820734",
	"master_place_lon" : "-0.1416087",
	"data_present" : false,
	"location" : [
		-0.141609,
		50.820734
	],
	"standard_place_name" : "brighton",
	"u_at" : ISODate("2023-03-22T09:50:06.926Z"),
	"place_name_soundex" : "B623",
	"editor" : "GeoffJ",
	"original_standard_name" : "brighton",
	"original_website" : "http://www.genuki.org.uk/maps/gmap?GR=TQ310060&PLACE=BRIGHTON&CCC=SSX",
	"freecen2_place_edits" : [
		{
			"_id" : ObjectId("64082ca4f493fd04689afa61"),
			"editor" : "GeoffJ",
			"reason" : "[\"Add Alternative Place Name\"]",
			"previous_chapman_code" : "SSX",
			"previous_county" : "Sussex",
			"previous_country" : "England",
			"previous_place_name" : "Brighton",
			"previous_grid_reference" : "TQ3104",
			"previous_latitude" : "50.820734",
			"previous_longitude" : "-0.141609",
			"previous_source" : "Gazetteer of British Place Names",
			"previous_website" : "http://www.genuki.org.uk/maps/gmap?GR=TQ310060&PLACE=BRIGHTON&CCC=SSX",
			"previous_notes" : null,
			"created" : ISODate("2023-03-08T06:35:16.711Z"),
			"previous_alternate_place_names" : [ ],
			"u_at" : ISODate("2023-03-08T06:35:16.711Z"),
			"c_at" : ISODate("2023-03-08T06:35:16.711Z")
		}
	],
	"alternate_freecen2_place_names" : [
		{
			"_id" : ObjectId("64082ca4f493fd04689afa62"),
			"alternate_name" : "Brighton The Palace",
			"standard_alternate_name" : "brighton the palace",
			"alternate_name_soundex" : "B623"
		}
	]
}

**Comment by geoffj-FUG** [comment]
Anne

 

We had this problem a long time ago. I thought that we stopped testing for disabled places.

 

Yes please, you can delete it.

 

I will create a story for handling disabled place names so that we can formulate a policy.

 

Geoff

**Comment by geoffj-FUG** [comment]
Anne

 

Looking at the record below it was me who caused the problem! It was right a the beginning when we were setting up the Gazetteer.

 

We live and learn.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG - disabled Gazetteer place for Brighton has now been deleted.

**Comment by geoffj-FUG** [comment]
Thank you

 

Enjoy your trip down under. Remember it is hot at this time of the year. Until you get to Sydney you can expect anywhere in the low to high 30s.

 

Geoff

**Comment by AnneV-Learn** [comment]
Thanks Geoff - Yep we will be set up for hot weather.
Anne
On 9 Nov 2023, at 11:51, Geoff J ***@***.***> wrote:

﻿

Thank you



Enjoy your trip down under. Remember it is hot at this time of the year. Until you get to Sydney you can expect anywhere in the low to high 30s.



Geoff

**Comment by DeniseColbert** [comment]
Closing
