### ISSUE TITLE
Read only access to Coordinators listing 

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1582]
There is a screen that allows Data Managers, Executive etc to add or change the coordinator for a county.

We need to make a read only view of this listing to coordinators please

This is also needed for Pat and others who have access to the communications system and may need to forward information to the coordinator for a specific county or country

Geoff

amended by Pat after Committee Meeting 11 Nov 2023

**Comment by geoffj-FUG** [comment]
As discussed at scrum.
Geoff

**Comment by DeniseColbert** [comment]
As I understand, we need a list of Counties/Syndicates - Name of Coord - contact (Communicate function?)

@geoffj-FUG do you think this should be available to all FreeCEN members/volunteers?

**Comment by geoffj-FUG** [comment]
I see no harm in that. It makes our organisation more transparent.
Geoff

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
New actions: "Display Syndicate/County Coordinators"

**Comment by geoffj-FUG** [comment]
Vino

Functionality looks good. I would like to review it after Deployment to check the data displayed is correct.

I will close it after I have checked the data.

Geoff

**Comment by DeniseColbert** [comment]
To be communicated to volunteers.

**Comment by geoffj-FUG** [comment]
Chris Mahoney wrote:

Hi Denise

Discussion came up at the weekend's FreeCEN committee meeting the County, and Syndicate coordinator lists that are now available on the website, and we had a few queries on what was listed:

County Coordinator List:
HAM Hampshire  -  We thought that this one currently has no coordinator, one is currently listed IOW Isle of Wight-  We thought that this one currently has no coordinator, one is currently listed OKI Orkney Islands  -  Listed Twice SAL Shropshire  -  Currently Vacant SHI Shetland Island - Listed Twice SSX Sussex  -  We thought that this one currently has no coordinator, Pat is listed  (am sure that Pat has one of the shipping ones)


Syndicate Coordinator List:
Central - No idea on what this is, consider eliminating if not needed, currently has no people in syndicate HAM Hampshire  -  We thought that this one currently has no coordinator, one is currently listed IOW Isle of Wight-  We thought that this one currently has no coordinator, one is currently listed Mid Glamorgan -  This one is mine, but is not being used, and has no people (all moved to Glamorgan)  -  consider eliminating POWYS  -  Consider eliminating, and has no people in it.  Better covered by the general Wales syndicate South Glamorgan -  This one is mine, but is not being used, and has no people (all moved to Glamorgan)  -  consider eliminating Technical  -  Consider excluding from listing - do we really want general volunteers knowing how to contact Vino West Glamorgan -  This one is mine, but is not being used, and has no people (all moved to Glamorgan)  -  consider eliminating

**Comment by geoffj-FUG** [comment]
Chris Mahoney wrote:

Hi Denise

Discussion came up at the weekend's FreeCEN committee meeting the County, and Syndicate coordinator lists that are now available on the website, and we had a few queries on what was listed:

County Coordinator List:
HAM Hampshire  -  We thought that this one currently has no coordinator, one is currently listed IOW Isle of Wight-  We thought that this one currently has no coordinator, one is currently listed OKI Orkney Islands  -  Listed Twice SAL Shropshire  -  Currently Vacant SHI Shetland Island - Listed Twice SSX Sussex  -  We thought that this one currently has no coordinator, Pat is listed  (am sure that Pat has one of the shipping ones)


Syndicate Coordinator List:
Central - No idea on what this is, consider eliminating if not needed, currently has no people in syndicate HAM Hampshire  -  We thought that this one currently has no coordinator, one is currently listed IOW Isle of Wight-  We thought that this one currently has no coordinator, one is currently listed Mid Glamorgan -  This one is mine, but is not being used, and has no people (all moved to Glamorgan)  -  consider eliminating POWYS  -  Consider eliminating, and has no people in it.  Better covered by the general Wales syndicate South Glamorgan -  This one is mine, but is not being used, and has no people (all moved to Glamorgan)  -  consider eliminating Technical  -  Consider excluding from listing - do we really want general volunteers knowing how to contact Vino West Glamorgan -  This one is mine, but is not being used, and has no people (all moved to Glamorgan)  -  consider eliminating

**Comment by geoffj-FUG** [comment]
Chris Mahoney wrote:

Hi Denise

Discussion came up at the weekend's FreeCEN committee meeting the County, and Syndicate coordinator lists that are now available on the website, and we had a few queries on what was listed:

County Coordinator List:
HAM Hampshire  -  We thought that this one currently has no coordinator, one is currently listed IOW Isle of Wight-  We thought that this one currently has no coordinator, one is currently listed OKI Orkney Islands  -  Listed Twice SAL Shropshire  -  Currently Vacant SHI Shetland Island - Listed Twice SSX Sussex  -  We thought that this one currently has no coordinator, Pat is listed  (am sure that Pat has one of the shipping ones)


Syndicate Coordinator List:
Central - No idea on what this is, consider eliminating if not needed, currently has no people in syndicate HAM Hampshire  -  We thought that this one currently has no coordinator, one is currently listed IOW Isle of Wight-  We thought that this one currently has no coordinator, one is currently listed Mid Glamorgan -  This one is mine, but is not being used, and has no people (all moved to Glamorgan)  -  consider eliminating POWYS  -  Consider eliminating, and has no people in it.  Better covered by the general Wales syndicate South Glamorgan -  This one is mine, but is not being used, and has no people (all moved to Glamorgan)  -  consider eliminating Technical  -  Consider excluding from listing - do we really want general volunteers knowing how to contact Vino West Glamorgan -  This one is mine, but is not being used, and has no people (all moved to Glamorgan)  -  consider eliminating

**Comment by DeniseColbert** [comment]
@Vino-S to look into whether Data Manager can make these changes now or if more coding is needed, to make that happen.

**Comment by DeniseColbert** [comment]
@cmahoneynz could you let volunteers know in the next newsletter that these Read Only lists are now ready and available for both Counties and Syndicates?

@PatReynoldsFUG to let Ali know that she can turn on SAL to accept new transcribers when she's ready to train them.

**Comment by cmahoneynz** [comment]
Before I let people know about these lists, could you let me know where to find them.

Knew where the link to the coordinator list was when I commented on this back in February, but this seems to have disappeared recently, and have not been able to locate it

**Comment by Vino-S** [comment]
@cmahoneynz : Added the actions again.

**Comment by cmahoneynz** [comment]
Have seen the lists, some amendments/queries on what I have seen:

County Coordinator List:
Hampshire:  -  Currently vacant, but list has a coordinator named
Isle of Wight:  Linked to Hampshire, am sure we have no coordinator, but one is named
Sussex:  -  Currently vacant, but list has a coordinator named


Syndicate Coordinator List:
Clwyd:  One of the new Welsh county names, currently has no people, so consider removing, better covered by Wales Syndicate
Gwent:  One of the new Welsh county names, currently has no people, so consider removing, better covered by Wales Syndicate
Gwynned:  One of the new Welsh county names, currently has no people, so consider removing, better covered by Wales Syndicate
Hampshire:  -  Currently vacant, but list has a coordinator named
Isle of Wight:  Linked to Hampshire, am sure we have no coordinator, but one is named
Shropshire:  Refer county coordinator list, needs updating with Ali Hill's details
South Glamorgan:  Consider removing, better covered by the general Wales syndicate, currently has no members
Tehnical:  Do we want this one listed, currently has Vino's details, and I think only coordinators, and above should have this one

**Comment by DeniseColbert** [comment]
@Vino-S to remove Technical from list

**Comment by DeniseColbert** [comment]
Deployed: closing

**Comment by DeniseColbert** [comment]
Reopening as Chris reports that other changes haven't been made @Vino-S could you take a look please?

**Comment by DeniseColbert** [comment]
@Vino-S to remove OVB county from the system

**Comment by DeniseColbert** [comment]
Done: closing
