### ISSUE TITLE
Minor adjustments to validation of vld collection 

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1587]
Anne

When you return can we have 2 adjustments made to the validation of vlds please?
Replace Dwelling number on validation screen with schedule number;
Can we adjust the report please so that it only displays files with a count of invalid POBs > 0.

Geoff

**Comment by AnneV-Learn** [comment]
Updated code deployed to Test3.
Here are screenshots of email from running the Rake for SOM on Test3:
Pre code update:
<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem83QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0fcb8b0acc12e5a480ad664b98e7e70ef0399f5/Screenshot%202023-12-06%20at%2018.34.53.png" alt="Screenshot 2023-12-06 at 18.34.53.png" />
Post code update:
<img width="638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenc3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f25216c6cb20bef874617b1e4580208c4cf43e8a/Screenshot%202023-12-06%20at%2018.35.39.png" alt="Screenshot 2023-12-06 at 18.35.39.png" />

So files with zero invalid POBs are no longer listed.
Could you test the 'replace Dwelling number on validation screen with schedule number' - requirement on Test3 pls @geoffj-FUG

**Comment by geoffj-FUG** [comment]
Anne

The report looks good. 

The schedule number is also good.

These changes can be deployed.

Geoff

**Comment by DeniseColbert** [comment]
Deployed: closing
