### ISSUE TITLE
279818942 Gazetteer updating timing out (Michael)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1593]
Issue reported by **MikeS** at 2023-11-13 15:29:02 UTC
Time: 2023-11-13T15:26:55+00:00
Session ID: c04ff9d662545b260014c91ae13b5c13
Problem Page URL: [/freecen2_places/search_names_results?locale=en](/freecen2_places/search_names_results?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/search_names](https://www.freecen.org.uk/freecen2_places/search_names)
Reported Issue:
Due to timing out attempts, the entry for Edinburgh now shows 4 additions of City of Edinburgh    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
@Vino-S 
I have looked in the production database and found this:
db.freecen2_places.find({"chapman_code" : "MLN","place_name" : "Edinburgh"}).pretty()
{
    "_id" : ObjectId("5fc6dd41f4040beff481f0f8"),
    "disabled" : "false",
    "cen_data_years" : [
        "1841",
        "1851"
    ],
    "country" : "Scotland",
    "county" : "Midlothian",
    "chapman_code" : "MLN",
    "place_name" : "Edinburgh",
    "last_amended" : "9-Apr-16",
    "grid_reference" : "NT268733",
    "latitude" : "55.94714",
    "longitude" : "-3.173655",
    "source" : "Gazetteer of British Place Names",
    "genuki_url" : "http://www.genuki.org.uk/maps/gmap?GR=NT270730&PLACE=EDINBURGH&CCC=MLN",
    "place_notes" : "",
    "original_country" : "Scotland",
    "original_county" : "Midlothian",
    "original_chapman_code" : "MLN",
    "original_place_name" : "Edinburgh",
    "original_grid_reference" : "NT2573",
    "original_latitude" : "55.944168",
    "original_longitude" : "-3.202386",
    "original_source" : "Gazetteer",
    "reason_for_change" : [
        "",
        "Add Alternative Place Name"
    ],
    "other_reason_for_change" : null,
    "master_place_lat" : "55.944167",
    "master_place_lon" : "-3.2023862",
    "data_present" : true,
    "location" : [
        -3.173655,
        55.94714
    ],
    "standard_place_name" : "edinburgh",
    "u_at" : ISODate("2023-11-13T15:26:22.500Z"),
    "place_name_soundex" : "E351",
    "original_standard_name" : "edinburgh",
    "alternate_freecen2_place_names" : [
        {
            "_id" : ObjectId("6048805ff493fdeda301c501"),
            "alternate_name" : "Edinburgh Castle",
            "standard_alternate_name" : "edinburgh castle",
            "alternate_name_soundex" : "E351"
        },
        {
            "_id" : ObjectId("65523b12f493fd40906a8f9f"),
            "alternate_name" : "City Of Edinburgh",
            "standard_alternate_name" : "city of edinburgh",
            "alternate_name_soundex" : "C313"
        },
        {
            "_id" : ObjectId("65523cc8f493fd40906a8fa1"),
            "alternate_name" : "City Of Edinburgh",
            "standard_alternate_name" : "city of edinburgh",
            "alternate_name_soundex" : "C313"
        },
        {
            "_id" : ObjectId("65523e07f493fd40a86a2991"),
            "alternate_name" : "City Of Edinburgh",
            "standard_alternate_name" : "city of edinburgh",
            "alternate_name_soundex" : "C313"
        },
        {
            "_id" : ObjectId("6552401ef493fd40906a901d"),
            "alternate_name" : "City Of Edinburgh",
            "standard_alternate_name" : "city of edinburgh",
            "alternate_name_soundex" : "C313"
        }
    ],
    "freecen2_place_edits" : [
        {
            "_id" : ObjectId("61180540f4040b4a683e9b81"),
            "editor" : "unknown",
            "reason" : null,
            "previous_chapman_code" : "MLN",
            "previous_county" : "Midlothian",
            "previous_country" : "Scotland",
            "previous_place_name" : "Edinburgh",
            "previous_grid_reference" : "NT2573",
            "previous_latitude" : "55.944168",
            "previous_longitude" : "-3.202386",
            "previous_source" : "Gazetteer",
            "previous_website" : "http://www.genuki.org.uk/maps/gmap?GR=NT270730&PLACE=EDINBURGH&CCC=MLN",
            "previous_notes" : "",
            "created" : ISODate("2021-03-10T08:16:31.213Z"),
            "previous_alternate_place_names" : [
                "Edinburgh Castle"
            ],
            "u_at" : ISODate("2021-08-14T18:02:40.980Z"),
            "c_at" : ISODate("2021-08-14T18:02:40.980Z")
        },
        {
            "_id" : ObjectId("65523b12f493fd40906a8f9e"),
            "editor" : "MikeS",
            "reason" : "[\"Add Alternative Place Name\"]",
            "previous_chapman_code" : "MLN",
            "previous_county" : "Midlothian",
            "previous_country" : "Scotland",
            "previous_place_name" : "Edinburgh",
            "previous_grid_reference" : "NT2573",
            "previous_latitude" : "55.944168",
            "previous_longitude" : "-3.202386",
            "previous_source" : "Gazetteer of British Place Names",
            "previous_website" : "http://www.genuki.org.uk/maps/gmap?GR=NT270730&PLACE=EDINBURGH&CCC=MLN",
            "previous_notes" : "",
            "created" : ISODate("2023-11-13T15:04:50.441Z"),
            "previous_alternate_place_names" : [
                "Edinburgh Castle"
            ],
            "u_at" : ISODate("2023-11-13T15:04:50.441Z"),
            "c_at" : ISODate("2023-11-13T15:04:50.441Z")
        },
        {
            "_id" : ObjectId("65523cc8f493fd40906a8fa0"),
            "editor" : "MikeS",
            "reason" : "[\"Add Alternative Place Name\"]",
            "previous_chapman_code" : "MLN",
            "previous_county" : "Midlothian",
            "previous_country" : "Scotland",
            "previous_place_name" : "Edinburgh",
            "previous_grid_reference" : "NT268733",
            "previous_latitude" : "55.94714",
            "previous_longitude" : "-3.173655",
            "previous_source" : "Gazetteer of British Place Names",
            "previous_website" : "http://www.genuki.org.uk/maps/gmap?GR=NT270730&PLACE=EDINBURGH&CCC=MLN",
            "previous_notes" : "",
            "created" : ISODate("2023-11-13T15:12:08.167Z"),
            "previous_alternate_place_names" : [
                "Edinburgh Castle",
                "City Of Edinburgh"
            ],
            "u_at" : ISODate("2023-11-13T15:12:08.168Z"),
            "c_at" : ISODate("2023-11-13T15:12:08.168Z")
        },
        {
            "_id" : ObjectId("65523e07f493fd40a86a2990"),
            "editor" : "MikeS",
            "reason" : "[\"Add Alternative Place Name\"]",
            "previous_chapman_code" : "MLN",
            "previous_county" : "Midlothian",
            "previous_country" : "Scotland",
            "previous_place_name" : "Edinburgh",
            "previous_grid_reference" : "NT268733",
            "previous_latitude" : "55.94714",
            "previous_longitude" : "-3.173655",
            "previous_source" : "Gazetteer of British Place Names",
            "previous_website" : "http://www.genuki.org.uk/maps/gmap?GR=NT270730&PLACE=EDINBURGH&CCC=MLN",
            "previous_notes" : "",
            "created" : ISODate("2023-11-13T15:17:27.634Z"),
            "previous_alternate_place_names" : [
                "Edinburgh Castle",
                "City Of Edinburgh",
                "City Of Edinburgh"
            ],
            "u_at" : ISODate("2023-11-13T15:17:27.635Z"),
            "c_at" : ISODate("2023-11-13T15:17:27.635Z")
        },
        {
            "_id" : ObjectId("6552401ef493fd40906a901c"),
            "editor" : "MikeS",
            "reason" : "[\"Add Alternative Place Name\"]",
            "previous_chapman_code" : "MLN",
            "previous_county" : "Midlothian",
            "previous_country" : "Scotland",
            "previous_place_name" : "Edinburgh",
            "previous_grid_reference" : "NT268733",
            "previous_latitude" : "55.94714",
            "previous_longitude" : "-3.173655",
            "previous_source" : "Gazetteer of British Place Names",
            "previous_website" : "http://www.genuki.org.uk/maps/gmap?GR=NT270730&PLACE=EDINBURGH&CCC=MLN",
            "previous_notes" : "",
            "created" : ISODate("2023-11-13T15:26:22.494Z"),
            "previous_alternate_place_names" : [
                "Edinburgh Castle",
                "City Of Edinburgh",
                "City Of Edinburgh",
                "City Of Edinburgh"
            ],
            "u_at" : ISODate("2023-11-13T15:26:22.495Z"),
            "c_at" : ISODate("2023-11-13T15:26:22.495Z")
        }
    ],
    "editor" : "MikeS"
}

So **alternate_freecen2_place_names** array elements with indexes **2,3,4** need to be removed as do 
**freecen2_place_edit**s array elements with indexes **2,3,4**.

I was thinking of doing updates to resolve this directly in Mongodb ie.

The updates:
1.

db.freecen2_places.update({ "chapman_code" : "MLN","place_name" : "Edinburgh" },{$unset : {alternate_freecen2_place_names.2 : 1}});
db.freecen2_places.update({ "chapman_code" : "MLN","place_name" : "Edinburgh" },{$unset : {alternate_freecen2_place_names.3 : 1}});
db.freecen2_places.update({ "chapman_code" : "MLN","place_name" : "Edinburgh" },{$unset : {alternate_freecen2_place_names.4 : 1}});

db.freecen2_places.update({ "chapman_code" : "MLN","place_name" : "Edinburgh" },{$pull : {alternate_freecen2_place_names : null});


2.

db.freecen2_places.update({ "chapman_code" : "MLN","place_name" : "Edinburgh" },{$unset : {freecen2_place_edits.2 : 1}});
db.freecen2_places.update({ "chapman_code" : "MLN","place_name" : "Edinburgh" },{$unset : {freecen2_place_edits.3 : 1}});
db.freecen2_places.update({ "chapman_code" : "MLN","place_name" : "Edinburgh" },{$unset : {freecen2_place_edits.4 : 1}});

db.freecen2_places.update({ "chapman_code" : "MLN","place_name" : "Edinburgh" },{$pull : {freecen2_place_edits : null});

Are you ok with this approach??

**Comment by DeniseColbert** [comment]
@Vino-S to check with Anne if speed improved

**Comment by AnneV-Learn** [comment]
This issue (actually a data issue) has now been resolved, so closing.
