### ISSUE TITLE
280137018 Childs Wickham duplicate entry in Gazetteer? (Chris)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1594]
Issue reported by **ceperman** at 2023-11-17 07:50:18 UTC
Time: 2023-11-17T07:45:47+00:00
Session ID: f9eb1e817e726dc979137019438eba98
Problem Page URL: [/freecen2_places/search_names_results?locale=en](/freecen2_places/search_names_results?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/search_names](https://www.freecen.org.uk/freecen2_places/search_names)
Reported Issue:
Childs Wickham and Childswickham exist as separate entries in the Gazetteer but look like the same place.    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
There is POB data for both Childswickham in GLS (388 search records) and Childs Wickham in GLS (84 search records). _BTW - There is also POB data for Childswickham in WOR (11 search records)._
How should this be resolved @geoffj-FUG?

**Comment by cmahoneynz** [comment]
All three are the same place, but going by the maps I have, it is a parish that crosses the boundry line between the two counties.  As such, I would leave the Worcester entry as is, and combine the two Gloucester entries into one (maps show both variations to be correct)

**Comment by geoffj-FUG** [comment]
Childswickham was transferred to WOR in 1931. I have therefore amalgamated all three entries into the one GLS entry. Geoff
