### ISSUE TITLE
Update Handbooks to January 2024 Versions

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1595]
Geoff has prepared 2024 versions of the Handbook.

How do you want this update handled?

Geoff

**Comment by DeniseColbert** [comment]
I will email Alison to see if this is something she will be able to manage

**Comment by DeniseColbert** [comment]
Please send the updated handbook to Alison, @geoffj-FUG so she can update the page.

**Comment by AlOneill** [comment]
Done so far:
- move, reword and box "suggestions" link — thank you @Vino-S
- move draft next to published version in Refinery listing — https://test3.freecen.org.uk/cms/draft-freecen-handbook

Awaiting 2024 file(s)

**Comment by geoffj-FUG** [comment]
Alison

 

3 x files sent directly by email. They are in pdf format.

 

Geoff

**Comment by AlOneill** [comment]
Updated handbook files are now uploaded to Refinery and
- links on Handbook page edited
- file sizes edited
- "last updated" dates edited

@geoffj-FUG if you can confirm that all is as expected, I will publish the draft "FreeCEN Handbook" page.

**Comment by geoffj-FUG** [comment]
Alison

 

I don’t have access to refinery. Test3 gives me the old versions. Can you link to test 3 so that I can check please?

 

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG 
The test 3 URL is https://test3.freecen.org.uk/cms/draft-freecen-handbook (as given in my comment of 29 Jan)

**Comment by geoffj-FUG** [comment]
Alison

 

Looks good. We can deploy this.

 

Geoff

**Comment by AlOneill** [comment]
@DeniseColbert @geoffj-FUG 

Revised [FreeCEN Handbook](https://test3.freecen.org.uk/cms/freecen-handbook) page published on test 3

**Comment by DeniseColbert** [comment]
Thanks @AlOneill ! Geoff to take a look

**Comment by geoffj-FUG** [comment]
Looks good

Please deploy

Geoff

**Comment by DeniseColbert** [comment]
Done, closing
