### ISSUE TITLE
Add Skip button to bottom of vld re-validaion form.

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1604]
@AnneV-Learn 

Anne

We currently have 2 buttons at the bottom of the re-validation form - Submit and Accept.

If I accept then it removes changes the entry from false to true and it never gets looked at again. This is often not suitable so I have to cancel, go back to the POB listing and find where I got to and select the next entry I want to work on.

Can we add a Skip button please that just moves me forward without requiring propagation and without changing the flag form false to true. I am ending up with a number of entries that are too complex and I am skipping in each file (hence the 397 file count does not drop). Most of these entries have notes against them from the original validation and I do not want to redo the research.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG
Implementation of a 'Skip' button is for testing on Test3 now.

**Comment by geoffj-FUG** [comment]
Anne

Looks good. Please deploy

Geoff

**Comment by Vino-S** [comment]
Code Deployed

**Comment by DeniseColbert** [comment]
Done; closing
