### ISSUE TITLE
Add Herefordshire as a search county in Gazetteer when WLS is selected

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1617]
The Wales coordinator (Chris M) has asked whether Herefordshire can be included in the WLS Gazetteer search as well as the ENG one please.
 
This is because Herefordshire is a border county and there is often confusion as to whether places are in England or Wales.
 
If HEF can be included in both can you add it to the WLS search please? 
 
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG THis can be tested on Test3 now

**Comment by geoffj-FUG** [comment]
Anne

Looks good

geoff

**Comment by DeniseColbert** [comment]
Done; closing

**Comment by DeniseColbert** [comment]
@Vino-S to check if deployed and if not, will deploy

**Comment by DeniseColbert** [comment]
Done; closing
