### ISSUE TITLE
284210105 Gazetteer - Other Names for Place cannot be duplicated (Geoff)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1620]
Issue reported by **GeoffJ** at 2024-01-03 11:15:05 UTC
Time: 2024-01-03T11:12:43+00:00
Session ID: 857ebf7acb8d1c1dac4a6a5b152b30d6
Problem Page URL: [/freecen2_places/5fc6decbf4040beff4826ec4?locale=en](/freecen2_places/5fc6decbf4040beff4826ec4?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/5fc6decbf4040beff4826ec4/edit?locale=en](https://www.freecen.org.uk/freecen2_places/5fc6decbf4040beff4826ec4/edit?locale=en)
Reported Issue:
I am trying to add Worcester St Helens to the entry for Worcester. However, it is testing the existing entries and stopping the addition. I am getting the blue message Other Names for Place cannot be duplicated.
This is not the first time that I have experienced this problem.
Geoff    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
Ready for Testing on Test3

**Comment by geoffj-FUG** [comment]
Anne
I added Worcester St Andrew to Worcester. All OK.

I then went back in and edited the place name by changing Worcester to Worcester St George. I got the following message:
Other Names for Place cannot be duplicated - (Worcester St Andrew,Worcester St Helens,Worcester St Martin) already exist
The problem appears to be that the alternative place names are being tested against themselves when the main place name is edited.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I have made some changes which I hope will resolve that bug.
However, I have also removed the ability to update a Place Name as this could be stored on the Search record as the Birth Place not just a link to it (the link to a place from a Search Record holds the Census Place). All rather complicated but if a Place Name needs to be changed I think it would have to come as a request to System Administrator - I believe this will be a pretty rare occurrance.
The changes are ready for Testing on Test3.

**Comment by geoffj-FUG** [comment]
Anne

 

I am signed into test3 as data manager.

 

I cannot amend the place name. I have several on my plate to do at the moment but cant because of the bug.

 

I tried to do one on test 3 but cannot because the place name is now hidden. 

 

I am happy for the ability to  be restricted to the data manager but I do need to make the changes at that level.

 

I am finding lots of instances as I do the vld validation, so access is a must. Where it is a  major issue I am creating stories. Where it is spelling and no conflict is created I am doing it myself.

 

Geoff

**Comment by AnneV-Learn** [comment]
@Geoffj-FUG I think we will have to discuss this at the next scrum, I’m not sure about changing the place name in the edit place form. 
The POB place name is stored on a Search records as the actual name not a link!! So if a place name is changed then to maintain the integrity of POB  data I believe that it would have to be updated there too. This is a big processing overhead. 
 IE for VLD data the name change would need to be propagated down through all the levels of data to the source record (as happens during the VLD POB validation processes). However it would not be possible to change the ‘actual’ source file of course. For CSVProc data it is rather simpler but still a lot of processing. 
I am still developing the code associated with story 1566 (move place linkages)  I think that would handle a place name change would it not?

**Comment by geoffj-FUG** [comment]
Anne

 

Yes #1566 should be able to handle a place name change because the data manager will be moving the links.

 

Geoff

**Comment by DeniseColbert** [comment]
Geoff and Anne to discuss offline, with Vino's help if needed.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG
Given that we agreed (in the Scrum) that it should not be possible to rename a Gazetteer place other than via the ‘Move Place Links’ process, are you happy with the changes made to resolve the original bug addressed by this story or do you need to do further testing?

**Comment by geoffj-FUG** [comment]
We can go ahead with the changes made so far.

Geoff

**Comment by DeniseColbert** [comment]
Done, closing
