### ISSUE TITLE
Add Thank You option to the Contact US form 

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeCENMigration#1626]

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
Denise to send a test 'Thank you' to see that Pat receives.

**Comment by DeniseColbert** [comment]
Test sent. @Vino-S please could you remove the hyphen so 'Thank-you' becomes 'Thank you'?

**Comment by Vino-S** [comment]
@Vino-S deploy the changes to production

**Comment by Vino-S** [comment]
Deployed
