### ISSUE TITLE
Gazetteer - When LND is selected as a chapman code for a Gazetteer search also search MDX and SRY

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1627]
When a person searches the Gazetteer for London then search Middlesex and Surrey as well.

I will amend the Chapman Code table to show LND as a level 2 chapman code as well as the existing level 3 code.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG ready for testing on Test3

**Comment by geoffj-FUG** [comment]
Anne

I have a suggested change to this after discussion with a Coordinator.

The search should include KEN.

Sorry

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG - no prob. Test3 now updated to include KEN.

**Comment by geoffj-FUG** [comment]
Looks good

Geoff

**Comment by DeniseColbert** [comment]
Deployed; close
