### ISSUE TITLE
RAP - The Records Available report

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1638]
The RAP is for volunteer and public consumpton, and reports:
- What we have available for transcription
- What we have in process of being transcribed
- What we have being validated
- What we have transcribed (this already is in place)

The RAP will tell a researcher if their search result  included one or more parts of the census that is a RAP and is not yet incorporated into the database.

If a search included one or more parts of the census that is a RAP available for transcription, the researcher will told that and invited to become a transcriber.

**Comment by PatReynoldsFUG** [comment]
The RAP will tell a researcher if their search result did not include one or more parts of the census that is a RAP.

**Comment by DeniseColbert** [comment]
IF we can add fields to Parms (Vino to check) we could place two text fields, each with three options:

Available in the Universe: Yes, No, Part
Available in FreeCEN: No, Yes but not digitised, Yes and digitised

**Comment by geoffj-FUG** [comment]
In progress see #247
Geoff
