### ISSUE TITLE
DAP - the Digitization Progress report

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1640]
The DAP report shows which images we have if they are not covered in the RAP, and their status e.g. not yet digitized, digitized but needing re-scanning, etc.)
This includes: Show report when a new set of images has been completed #1079

The DAP will tell a researcher if their search result did not include one or more parts of the census that is not a GAP.

**Comment by DeniseColbert** [comment]
IF we can add fields to Parms (Vino to check) we could place two text fields, each with three options:

Available in the Universe: Yes, No, Part
Available in FreeCEN: No, Yes but not digitised, Yes and digitised

**Comment by geoffj-FUG** [comment]
In progress see #247

Geoff
