### ISSUE TITLE
284850597 WES Westmorland 1891 CP Index (Michael)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1646]
Issue reported by **MikeS** at 2024-01-10 21:09:57 UTC
Time: 2024-01-10T20:59:02+00:00
Session ID: c04ff9d662545b260014c91ae13b5c13
Problem Page URL: [/freecen_csv_entries?locale=en&type=Err](/freecen_csv_entries?locale=en&type=Err)
Previous Page URL: [https://www.freecen.org.uk/freecen_csv_files/my_own?locale=en](https://www.freecen.org.uk/freecen_csv_files/my_own?locale=en)
Reported Issue:
Westmorland 1891 Civil Parish Index for RG12_4327 has "Yanwath & Eamont Bridge", which produces an 'Illegal Text' Error. Trying it with "and" produces a 'Non-existant' Error. Please can the Index be changed to "and". Thanks
    

![Screenshot](https://www.freecen.org.uk)

**Comment by DeniseColbert** [comment]
Geoff to check there is a story for this and let Mike know we're aware and working on it.

**Comment by geoffj-FUG** [comment]
Mike confirms that this is now sorted out.

Geoff
