### ISSUE TITLE
285142290 Gazetter search for castle (Geoff)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1647]
Issue reported by **GeoffJ** at 2024-01-14 06:11:30 UTC
Time: 2024-01-14T06:10:09+00:00
Session ID: ce0ca2cf0866baec6201d0eb6eedb71d
Problem Page URL: [/freecen2_places/search_names?locale=en&new_search=true](/freecen2_places/search_names?locale=en&new_search=true)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/search_names_results?locale=en](https://www.freecen.org.uk/freecen2_places/search_names_results?locale=en)
Reported Issue:
If I enter Castle into the gazetteer with no other information I get the red message.

This has also been reported to me by another coordinator.

Geoff
    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
I think this might possibly be related to the issues with Edinburgh Gazetteer entries (#1593) - I need to do further investigation.

**Comment by AnneV-Learn** [comment]
@Geoffj-FUG this issue (which was related to #1583) has now been resolved, so closing.
