### ISSUE TITLE
286876038 LLanedern dupication (Chris)

### ISSUE THREAD

**Issue by FreeUKCen** [FreeUKGen/FreeCENMigration#1652]
Issue reported by **ceperman** at 2024-02-03 07:47:18 UTC
Time: 2024-02-03T07:43:28+00:00
Session ID: f9eb1e817e726dc979137019438eba98
Problem Page URL: [/freecen2_places/search_names_results?locale=en](/freecen2_places/search_names_results?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/search_names](https://www.freecen.org.uk/freecen2_places/search_names)
Reported Issue:
See screenshot. Looks like some duplication here.

Chris Wood
https://www.freecen.org.uk/uploads/feedback/screenshot/65bdef86f493fd58b0fd9507/Screenshot_from_2024-02-03_07-45-37.png    

![Screenshot](https://www.freecen.org.uk)

**Comment by geoffj-FUG** [comment]
Done
