### ISSUE TITLE
Transcribers upload stats 

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeCENMigration#1659]

**Comment by DeniseColbert** [comment]
Review a sample of Coordinators, one county for each Coordinator to see if generally, transcribers are uploading for themselves.

This list can then be used by Coordinators to make inactive transcribers as such.

**Comment by DeniseColbert** [comment]
Needs from date and to date, and UserID count within role

**Comment by Vino-S** [comment]
@Vino-S deploy the changes to LIVE

**Comment by Vino-S** [comment]
Deployed
