### ISSUE TITLE
Appoint Coms Coord volunteer (Was FreeCEN feedback needs changing)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#166]
Currently goes to the development team (including Sean).  Needs to be a single point of contact by the time we invite the FreeCEN1 users over to take a look. Eric took this role in the early days, but it is much better with a Communications Coordinator who can  be more focused on the role.

**Comment by edickens** [comment]
Interesting that now the new website has really got going, we are
    getting many more feedback messages every day than we did in FR1.
    
    In the light of this, we have changed the system slightly in that
    Sandra (Communications Coordinator) sees every message and can
    usually respond as necessary.  She will pass the message on to a
    Syndicate Coordinator if they have asked to handle all their
    queries, otherwise she will either reply, or post the message on the
    FR waffle board for the Project Manager to assign.  These latter are
    usually software problems or suggested enhancements.
    
    We are very lucky to have Sandra because she used to work in the
    Virgin Atlantic call centre, so she is used to dealing with the same
    question again and again.  I think she has set herself up as a call
    centre with a standard set of replies.  Because of her disability,
    this is really useful to her well-being.
    
    Eric
    
      On 02/11/2016 09:35, PatReynolds wrote:
    
    
      Currently goes to the development team (including Sean). Needs
        to be a single point of contact by the time we invite the
        FreeCEN1 users over to take a look. Eric took this role in the
        early days, but it is much better with a Communications
        Coordinator who can be more focused on the role.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeCENMigration","title":"FreeUKGen/FreeCENMigration","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeCENMigration"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"FreeCEN feedback needs changing (#166)"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeCENMigration/issues/166"}

**Comment by FreecenBren** [comment]
I deal with all the FreeCEN 1 emails, queries and complaints.

If they are County specific (errors) they are forwarded on to the COORD for that county anyway.

This is not a problem at the moment as we do not get many.

 

The FreeCEN 2 ones Doug relays them to me and I deal with them.
If they can come direct to me that would be easier for all.

I am happy to carry on with them at the moment as there are not many.

They all originate from the Testers anyway!

 

As soon as they pick up that will be a different matter.

In the meantime I will contact the COORDS and try to get a volunteer.

 

Brenda

**Comment by dougkdev** [comment]
I have marked the FC2 accounts for Sean and Helena as inactive and switched the roles for everybody else (except Brenda, Pat, and Myself) to either "technical" or "transcriber" so the feedbacks will not be sent.  I left Brenda and myself with the "system administrator" role, so we will both get all of the contacts and feedbacks.  I marked Pat as "executive director" which should receive the same types of emails received in freeReg.
