### ISSUE TITLE
Review birth place test feedback

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#167]

**Comment by PatReynolds** [comment]
From what I've found so far, the conclusion of the feedback is:
a) people do not like a change from FreeCEN1, but
b) people do not like the version used in FreeCEN1
we therefore need to do some research.
However, I feel if we launch FreeCEN2 with only a birth county search, we are going to get a lot of feedback that one is needed, with no additional information as to _what_ is needed.  I am missing quite a lot of knowledge, so have started a page of notes to record what I know - please add! https://docs.google.com/document/d/10vfCkJU7NZ9s8sNLMQKWbSbIGrKkSIj7YA1uTGgoo_Y/edit?usp=sharing
