### ISSUE TITLE
Blandford Forum DOR

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1674]
The entries for Blandford St Mary and Blandford Forum are the same place. Blandford St Mary is the original entry.
Please move Blandford Forum as an alternative place name to Blandford St Mary. Please move Blandford Workhouse and Blandford Forum and Blandford entries with their search records to the Blandford St Mary entry.
Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG 
It is my understanding that Blandford Forum and Blandford St Mary are two separate places on opposite sides of the River Stour.

Wikipedia has, in an article entitled Blandford Forum, has this:
<img width="780" alt="Blandford_Forum_-_Wikipedia" src="https://github.com/FreeUKGen/FreeCENMigration/assets/14852554/c21fb16d-8ef9-41f7-a736-7408567b09f0">

The church in Blandford Forum is dedicated to St Peter and St Paul.

"The village [of Blandford St Mary] is on the south bank of the River Stour, immediately opposite the larger town of Blandford Forum."

**Comment by geoffj-FUG** [comment]
Thanks Alison

 

I was working on the basis of the closeness of the latitude and longitude entered.

 

I will close the story.

 

Geoff
