### ISSUE TITLE
Amend permissions to move a syndicate member between syndicates.

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1692]
Currently a Syndicate Coordinator can move a volunteer from their syndicate to a different syndicate (owning syndicate does the transfer).
We have a problem with Scotland where there is no syndicate coordinator to do the transfer. The Scotland Coordinator does not have permission.

Can we give the Scotland Coordinator permissions to edit any syndicate member in a Scottish County please?

In addition can we give the Data Manager the permission to edit a syndicate mamber in any county. In that way Rhoda or I will be able to fix up this problem in the future.

Geoff

**Comment by AnneV-Learn** [comment]
Ready for testing on TEST3

**Comment by DeniseColbert** [comment]
@geoffj-FUG could you test/ask Margaret to test?

**Comment by geoffj-FUG** [comment]
Tested as Data Manager permission. Ready for deployment

I cannot test as Scotland Coordinator but will ask Margaret to do so after deployment.

Geoff

**Comment by DeniseColbert** [comment]
Done. @geoffj-FUG to email Margaret

**Comment by geoffj-FUG** [comment]
Scotland Coordinator reports that she can now move people from her county syndicates.

Geoff
