### ISSUE TITLE
Write Roadmap (integrate text into roadmap)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#17]

**Comment by PatReynolds** [comment]
I have now created a folder 'FreeCEN2 system documents' to mirror what will be created in Registry, based on the structure of system documents for FreeREG2.  Please delete any folder we don't need!  
The only place with any documents so far is the Roadmap.

**Comment by sean-wood** [comment]
Is there a requirement for someone else to do something for this story. should it be re-assigned to that person and moved back to in-progress

**Comment by PatReynolds** [comment]
Hi Sean,

Should have been assinged to me with a task to create the gdrive folder to
hold texts awaiting the creation of the documentation pages on freeCEN2, I
think.  Currently on the phone so no waffleboard access at the moment.

Best wishes,

Pat
