### ISSUE TITLE
review birth county code

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#170]
see comments in #169

**Comment by dougkdev** [comment]
Found another problem with the birth county code in the VLD parser. It is not doing anything about INC (for individuals born in-county).  Reopening this issue as I believe the code related to birth information (county, place, age) should be reviewed thoroughly before we ask users to spend time testing it.  Unknown ages (999 / x flag) are not handled at all in FC2 by the VLD parser, either, like they are in FC1. (Although not part of birth counties, I am mentioning ages/birth year in this story because they likely would be handled in the same part of the code).

**Comment by benwbrum** [comment]
This is certainly a bug -- there's no code in FC2 yet to translate INC to the appropriate county.  As a result, the birth county search will miss anyone with INC.  This needs fixing, and I suspect we'll need a rebuild or a migration before we enable this feature successfully.

**Comment by dougkdev** [comment]
We may need a rebuild to fix any other issues you find or any necessary changes for birth years, but for the INC issue it appears we only need to reload 10 VLD files. While there are many thousands of entries with INC, they all appear to be within the following 10 VLD files:
AYR/HS410591.vld
CON/ho410133.vld
CON/ho410134.vld
CON/ho410135.vld
CON/ho410136.vld
CON/ho410137.vld
CON/ho410138.vld
CON/ho410139.vld
CON/ho410140.vld
CON/ho410142.vld

**Comment by benwbrum** [comment]
That's great news!  I'd think that's small enough to run on production, despite the replica set load.
