### ISSUE TITLE
1911 Census Search Problem

### ISSUE THREAD

**Issue by cmahoneynz** [FreeUKGen/FreeCENMigration#1709]
As we know when doing a search for someone on the FreeCEN website we get a list of potential results to browse through, and, on clicking of the view button, the website brings up the full details of that particular household.

However, if the result is from the 1911 census, and the location is for any of the Welsh counties, clicking on the View button results in the website giving us the message (in red text) "... something went wrong with your request..."

For example, if one were to do a search for an Alfred PENDER, born 1860 in Cornwall, the website gives three results, the third of these is for Anglesey in 1911, and clicking of the view button for this entry brings up the error message.  Entry in question comes from Anglesey 1911 piece RG14_34628.

I tried serching for someone else from the same piece, but in a different schedule, person shows up in overall search results, but clicking of the view button results in the same error message.  There are only three other Welsh 1911 pieces incorporated at this time (all in the county of Brecon), but we get the same problem with all of these in that if I do a search for someone at random from any of these pieces, they show up in overall search results, but clicking of the view button results in the error message.

Also checked random 1911 pieces that have been uploaded in England (only has occured for three counties, GLS, NTT, and SOM) but for these three, clicking on the view button brings up the full details as it is supposed to.

It would seem that at this time, while the website is capable of doing 1911 searches for any Welsh piece, and giving us potential matches in the overall results, it for some reason will not bring up the details when the view button is pressed.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Bug identified that affected viewing 1911 individual search results for Welsh Counties and IOW.
Solution now ready for testing on Test3. Note: I have uploaded 1911 AGY Piece RG14_34628 to Test3  to facilitate testing.

**Comment by PatReynoldsFUG** [comment]
Now working as expected on test3.

**Comment by AnneV-Learn** [comment]
@PatReynoldsFUG I have added the solution to #1747 to the code that resolves this issue as they are in a similar code area. I'll let you know when it is ready for re-testing on Test3.

**Comment by AnneV-Learn** [comment]
@PatReynoldsFUG this is now ready for re-testing on Test3.

**Comment by PatReynoldsFUG** [comment]
Tested with a search for Jones, any place born any year and there was only one result: John Samuel Jones on Anglesea, a lighthhouse keeper.

The lack of Jones (and no Prices!) means that I wonder if there is a big enough dataset on FreeCEN test3 to check.

**Comment by AnneV-Learn** [comment]
@PatReynoldsFUG I have just loaded some more 1911 data for Wales - Brecknockshire (BRE) in to Test3.
It includes folk with surname JONES, hopefully that will provide enough data now.

**Comment by cmahoneynz** [comment]
There is on one Anglesey 1911 piece incorporated at this time (and that only has the 15 entries in it (piece done to go with a newsletter article I wrote on the Anglesey light stacks).  Adding the three Brecon 1911 pieces should help as they have about another, 2,500 entries between them, and they do have both JONES, and PRICE's.

No other Welsh 1911 pieces are being worked on at this time so may be a while before there is in increase on what is there.

Unable to check this on the test servers as I do not have access to that

**Comment by PatReynoldsFUG** [comment]
Tested on test (Jones, no other data, Brenockshire) and it works fine.  Still produces error on live.

**Comment by AnneV-Learn** [comment]
@PatReynolds yes will still error on Live until fix is deployed.
