### ISSUE TITLE
delete census piece- available in interface

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#171]
current functionality allows adding and editing pieces and places. need to add functionality to the interface to delete existing pieces that are created erroneously. (currently, the ctyPARMS.DAT file needs to be amended and reloaded through the FC1 path, requiring a reload of all VLDs that are from that county/year combination).

E0 U6 S8 C?7: P21

**Comment by richpomfret** [comment]
Another meeting required to discuss this.

**Comment by Captainkirkdawson** [comment]
Suggest this be closed as we are evolving towards a fixed parms/piece structure based on TNA
