### ISSUE TITLE
investigate why long queries not handled properly

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#172]
When a query takes longer than max_search_time (configuration value in mongo_config.yml), a message is supposed to be displayed to the user that the query is taking too long and their query needs to be adjusted.  Instead, the application freezes and no response is returned. Multiple long queries of this type block the queue so no other requests are handled by the server, leading to an (unintentional) denial of service. All users seeing a message after a long wait that just says the gateway timed out or that the request queue is full (see story #169). Solution to #169 was to raise the limit to 50sec so this does not occur on a normal basis, however the underlying cause should be investigated and addressed. For investigation purposes, the error can be replicated by configuring the time limit to a very small value so even simple queries time out.

**Comment by richpomfret** [comment]
Not high priority but needs to be looked at to explore why this might be occurring.

**Comment by dougkdev** [comment]
Interestingly, I just got a gateway timeout like we were seeing previously. Request stuck in the passenger queue.
