### ISSUE TITLE
Huntingdon HUN

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1746]
The parishes have been entered without the place name before them. I have made the correct entries available.

Please move the search records from the individual parishes to the full place name and delete the parishes without a place name.

Geoff

**Comment by rhodamackenzie** [comment]
which piece(s)?

**Comment by geoffj-FUG** [comment]
Rhoda
The parishes that are entered as alternative names without Huntingdon before them.

Geoff

**Comment by rhodamackenzie** [comment]
I am probably being stupid, but do you mean for every district and piece called Huntingdon you want all of the parishes for all years to have the word Huntingdon in front of them? If so it will take a long time for me to do each one manually (It's not a spreadsheet). Or is there meant to be an attachment showing me which piece(s) this refers to? When you say you have "made the correct entries available" where do I find them please?

**Comment by rhodamackenzie** [comment]
I think I understand now - for all years, these 4 Huntingdon parishes - All Saints, St Mary, St Benedict, St John, rename them with the name Huntingdon in front of them and make sure they have, eg, Huntingdon St Mary as their place name? As they are all alternate placenames under the umbrella of Huntingdon, do you want 
me to make the 4 place names into 4 primary placenames or can they stay under Huntingdon?

**Comment by geoffj-FUG** [comment]
Done
