### ISSUE TITLE
Household table displaying data in wrong columns for 1911 census

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1747]
<img width="1771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXM5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94ccae1c38fa0e88f018949aeef70dde9e893438/image.png" alt="image.png" />

**Comment by PatReynoldsFUG** [comment]
Original:
<img width="1343" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXc5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e82f762d33c2ee597de256bc1a4e1cacb3fd609/image.png" alt="image.png" />
****

**Comment by AnneV-Learn** [comment]
I have added the code to resolve this issue to story #1709

**Comment by AnneV-Learn** [comment]
@PatReynoldsFUG this is now ready for testing on Test3.

**Comment by cmahoneynz** [comment]
Have checked the original CSV for this piece (I have kept copies of what I have uploaded, and incorporated), and that is showing everything to be in the right column

**Comment by PatReynoldsFUG** [comment]
Yes, I agree - working fine on test3.

**Comment by AnneV-Learn** [comment]
Ready for deployment (code fix is in fc_1709_av branch)

**Comment by DeniseColbert** [comment]
Done closing
