### ISSUE TITLE
"Pending" option for Contacts system (part of #1488)

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1749]
Current state of contacts system: The contacts system automatically deletes contacts after ??? days. If you are happy for that to happen, the recipient doesn't need to do anything.

This story is to implement a 'Pending' option' to be used if the recipent want longer to deal with the contact.

If the pending option is selected, the contact will not be deleted until the 'pending' option is deselected or the recipient uses the 'delete' or 'archive' buttons.

Suggestion (for discussion) if, after 3 months the contact has not been deleted, or archived, nor has a reply been sent to the contact sender, send a reminder to the contact recipient.

**Comment by DeniseColbert** [comment]
Closing as we have "Keep until I say so" option
