### ISSUE TITLE
Create an 'Archive' option for Contacts (part of #1488)

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeCENMigration#1751]
Create an 'Archive' option for Contacts - Archived contacts will not be automatically deleted.

Contact recipients who feel that there is important information in the Contact which they or others may need to see in the future, can use the ‘Archive’ option

**Comment by Vino-S** [comment]
@Vino-S to give access to List Archived Contacts for Pat

**Comment by DeniseColbert** [comment]
We don't need this, can use what we already have
