### ISSUE TITLE
Volunteer Handbook needs updating

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/FreeCENMigration#1752]
The last update was in May 2019 so many of the names in the org charts are out of date.

**Comment by DeniseColbert** [comment]
[Volunteer Induction Handbook (Dec 2023).pdf](https://github.com/FreeUKGen/MyopicVicar/files/13688828/Volunteer.Induction.Handbook.Dec.2023.pdf)

Updated handbook ready to replace the 2019 version. thanks for raising this Steve!

**Comment by SteveBiggs** [comment]
That was quick! Thanks Denise.

**Comment by DeniseColbert** [comment]
I generally update the Handbook every 6-12 months so it was a quick job. I just need to make sure it gets brought over to the website after future updates!

**Comment by DeniseColbert** [comment]
https://drive.google.com/file/d/1VQEW2vYCbuAB1gPul46XIZSRV9Y0b-6O/view?usp=sharing

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
Looks in order, please deploy @Vino-S !

**Comment by DeniseColbert** [comment]
Transferring to CEN for implementation there

**Comment by DeniseColbert** [comment]
Done, closing
