### ISSUE TITLE
Problem with search when age in months

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeCENMigration#1759]

**Comment by DeniseColbert** [comment]
Solution: Where there is an 'm' code should convert this to 'years' (i.e. /12)

**Comment by DeniseColbert** [comment]
Initial work is up on Test3 @Vino-S will send recors to Geoff to test and then if all is well, create rake task to fix this in all records.

**Comment by DeniseColbert** [comment]
@Vino-S to work with Anne on potential solutions as this fix didn't work as expected

**Comment by Vino-S** [comment]
@Vino-S to test the scenarios where age is 1 year 2 months (1921 census)

**Comment by Vino-S** [comment]
Code should now handle compound age unit: https://test3.freecen.org.uk/search_records/66a0bd07bd30f2219f718b30/minnie-eliza-marks-1871-london-city-bermondsey-1868-?locale=en

<img width="1758" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUVFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78e56e129897fb3dd89668b7fd65476b431f4de2/image.png" alt="image.png" />

**Comment by geoffj-FUG** [comment]
This is satisfactory for the current years up to 1911. I am not completely sure of the constraints for 1921. It may need review in a few years when somebody gets to 1921.

Can be deployed.

Geoff

**Comment by DeniseColbert** [comment]
@Vino-S to check if deployed and close if so.

**Comment by DeniseColbert** [comment]
Deployed: closing
