### ISSUE TITLE
Add code that removes commas and full stops from verbatim birth place and birth place to download of a vld file as csvpro.

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1772]
@AnneV-Learn 

Add code that removes commas and full stops from verbatim birth place and birth place to download of a vld file as csvpro.

Can we also removee apostrophes with this change please?

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
Good idea.

**Comment by AnneV-Learn** [comment]
Ready for testing on Test3

**Comment by geoffj-FUG** [comment]
Works well.

Can be deployed.

Geoff

**Comment by DeniseColbert** [comment]
Done, closing
