### ISSUE TITLE
Automate production deployments

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#178]
We need to either A) review and copy the update_freecen.sh script on vervet to all servers, or B) bit the bullet and finally install Capistrano.

**Comment by dougkdev** [comment]
You mean the update-freecen2 just outside the .../production directory? If so there is already the equivalent on the production servers, it is just in a different location (same place as the freereg script) and you need to run with sudo.  I'll email you and @AlexAvlonitis .  If you are talking about a different script I am not sure which one you mean.
