### ISSUE TITLE
Channel Islands pieces - Chapman Code integrity

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1781]
We have 4 Chapman Codes for the Channel Islands but they are all recorded in the PARMS under CHI. We have designated this in the Chapman Code structure as a country along with ENG, WLS etc.

I have had a look at the vld collection for the Channel Islands and the impact of the historical structures used by the TNA in their census collection, which is the basis of our PARMS structure.
In 1861 and 1891 (the only two years that FreeCEN has transcribed) they appear to have used a structure where the Channel Islands were the primary chapman code and not the chapman code of the individual islands. (The ability to search the whole channel islands has recently been introduced).
So we have a situation in the existing searches where if I search for John Smith in Jersey in 1861 I may not find him. However if I search for John Smith in the Channel Islands in 1861 I will be able to find him. 
This TNA structure caused headaches when the PARMS was established. The ongoing implications were not realised.
I am proposing that the Chapman code for CHI in the PARMS should be changed to that of the individual islands. This will affect 29 online pieces in 1861 and 8 pieces in 1891.
I can coordinate these changes with Rhoda. The data manager still has the ability to download and reload vld files. Once the piece is downloaded Rhoda can do the changes and then the piece can be reloaded.
There are also 5 x 1861 csv files that will need changing. There are no unincorporated 1861 csv files. There are 6 x 1891 csv files that will need changing. There are no unincorporated 1891 files.

In addition I propose that although the Piece name of RG9_4374 is Guernsey, the contents are Alderney. I therefore propose that we change  give it a Chapman Code of ALD.
In the interests of Chapman Code integrity I propose that we break up RG12_4707 into 4707 GSY, 4707A ALD and 4707B SRK. This will be the only online piece that is affected by the changes. It is currently a vld file so will need re-validation as a csv file.

There are no files online for 1841, 1851, 1871, 1881, or 1901 . 
From 1841 to 1901 the PARMS structure includes Alderney and Sark as Guernsey, which is the government structure. 
In 1911 the PARMS structure uses the islands of  ALD, GSY, JSY and SRK. From 1841-1901 the structure is only CHI with the Islands as piece names. Therefore the structure does not conform to our country / county / regn district / piece / civil parish structure.

I also propose that we adjust the PARMS for the other census years in a similar manner to give us a similar structure to the rest of the PARMS entries.

Referred for consideration, please.

This story has been triggered when considering story #341.

Geoff

**Comment by DeniseColbert** [comment]
Agreed in Scrum

**Comment by geoffj-FUG** [comment]
Gazetteer updated, Changes completed.

Geoff
