### ISSUE TITLE
Piece RG10_1617A and 1618A not showing up in CAM county statistics.

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1782]
Reported by Sue Johnson. My reply to Sue:
I have had a look at RG10_1617A and RG10_1618A.

Firstly, RG10_1617 does not exist so Rhoda doesn’t need to do anything. Only RG10_1617A exists. I have it listed as a NFK piece which it is geographically, but it is managed by CAM as it was in a CAM Registration District. I will log this as a bug as it should appear on the CAM county statistics, but it is shown in NFK.
The piece is online. When I look in the NFK county statistics for 1871 I see the following:
Piece Number (Chapman Code)	Piece Name	Status	Online VLD Files	Incorporated CSV Files	Unincorporated CSV Files
RG10_1617A	Walpole St Peter			["RG10_1617a.csv (Suej1949)"]	[]
I notice that RG10_1618A is not in the CAM county statistics but is not in the NFK county statistics either. There is no RG10_1618, only RG10_1618A. So it must all exist in NFK, but is a CAM piece to manage. There is a vld piece recorded as online for this piece. 
I will log this one as well.  
RG10_1619/19A and RG10_1620/20A are correctly in your county statistics. They are split between the 2 counties and so need to be split and converted to csv files. They are currently vld files.

The issue is that these 2 pieces do not have any records in the responsible coordinator's county (CAM). Because all the records are in NFK they appear to be showing up in NFK county statistics.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
Maybe I’m not fully understanding but for RG10_1617A  isn’t the solution to update the Admin County for the Piece to CAM? It should the appear in the County Stats for CAM rather than NFK.

RG10_1618A has the 'shared VLD file' link populated in the Piece - I do not think it should be populated so I can remove it but again the Admin County for the Piece should be updated to CAM I believe.  

Please let me know if you agree with my solutions.

**Comment by DeniseColbert** [comment]
@AnneV-Learn to make the changes she suggested

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
I have updated the 'Admin County' for RG10_1617A and RG10_1618A to CAM (was NFK) and they now appear in the CAM County Stats f0r 1871.<img width="1905" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c8893bf0d5260e0e46352ce4e11970a5df81234/Screenshot%202024-06-12%20at%2011.33.57.png" alt="Screenshot 2024-06-12 at 11.33.57.png" />

**Comment by DeniseColbert** [comment]
@geoffj-FUG to test on live

**Comment by geoffj-FUG** [comment]
Now showing OK.

Geoff
