### ISSUE TITLE
297616210 Search engine bug (Stephen)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeCENMigration#1784]
Issue reported by **algypug** at 2024-06-06 15:10:10 UTC
Time: 2024-06-06T15:06:18+00:00
Session ID: a81385e76628d286a341660c5ace5dae
Problem Page URL: [/freecen2_places/search_names?locale=en&new_search=true](/freecen2_places/search_names?locale=en&new_search=true)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/search_names?locale=en&new_search=true](https://www.freecen.org.uk/freecen2_places/search_names?locale=en&new_search=true)
Reported Issue:
Tried partial search for <contains "saint">.  Failed with incorrect error message "partial searches must contain at least 3 characters"
Any comment of mine would surely be superfluous.    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
Ready for User Testing on Test3

**Comment by DeniseColbert** [comment]
@DeniseColbert to replicte on Gazetteer search

**Comment by geoffj-FUG** [comment]
Search for Srats with Saint in CON works well. Listed all the place names starting with St.

 

Geoff

**Comment by AnneV-Learn** [comment]
Deployed by Vino 23/07 so closing and I will inform the user
