### ISSUE TITLE
Update of the validation process step 2

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1786]
This is part of the Epic #1783. Please read the document linked to #1783 when considering this story.

Step 1 of this Epic introduces Pre-validation to the validation process.

Step 2 allows future validation to update and build on the existing pre-validation data that was established during revalidation of the vld data collection.

Once a piece has been transcribed and proofread it may or may not contain information in the alternative Place of Birth fields. Pre-validation will populate some alternative Place of Birth fields that have not yet been populated. testing the piece will set all the records as true in the warning or error field that is associated with POBs. Therefore if a verbatim place of birth entry exists in the Gazetteer it will not need to be further validated and the flag set to true. This is the current process when a file is being validated.

When the current validation screen is displayed it does not show the Propagation Actions unless they have been edited. This should be amended so that they are shown if:
The verbatim Place of Birth is not the same as the Alternative Place of Birth then the Propagate POB action is available.
The Notes field is not null, then the Propagate Notes action is available.

At this point these actions will propagate through the piece as currently happens.

This change can be deployed once it has been tested.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG this is ready for testing on **Test3**

**Comment by geoffj-FUG** [comment]
Only one item left for this step. see end of this test log. See also test 1 for Upload problem.

Geoff

Test 1 – check upload of a file being validated (old style) when file is not on system as being validated.

HO107_1925 is a file where validation is almost complete. Uploaded as a new file. It should reject as a file that is not currently being validated.  Not uploaded and no email received. Does not appear in list of files. Problem, no email or response in this situation.

Test 2 – Upload a file that is not being validated
HO107_1925A is a file that has been validated and is online. Copy of file to be uploaded to test3. Validation True False column removed. Successful 226 warnings.

Test 3 – Mark HO107_1925A as ready for validation. 
Prevalidation requested. No updates made (but test3 does not have the data to do it.

Test 4 - Download validation spreadsheet.
Download successful with three columns. False flags appear to be OK. Added one false flag and entry to check that replace will be OK.

Test 5 – Reload validation spreadsheet. 
File reloaded OK. Count changed due to previous change.

Test 6 Display Warning messages.  OK 227 entries need validation. Correct.

Test 7 – Display entries needing validation.
Edited entry removed and accepted.
Stockland Bristol downloaded – change accepted. Fields propagated. Count should now be changed by more 3. One for removal of non POB entry and 1 for Stockland Bristol No Propagation.
File reprocessed. 225 entries.
North Petherton amended 224 Warnings and Propagated. Reprocessed Propagation working but propagation button does not disappear..
Note: Once a POB is Propagated the Propagate Alternative fields should be removed from the screen.
Warning re age and scholar accepted and count changed OK. Downloaded and flags correct.

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 
**Re - Test 1** - there was a problem with the email system on Test3 - Vino has now restarted it and it appears to be ok now. So please reTest.

**Comment by geoffj-FUG** [comment]
Anne

Test 1 now OK. Just making the Propagate button disappear to go. We could wait until step 3 ready and deploy all 3 steps together.

Geoff

**Comment by AnneV-Learn** [comment]
Geoff
RE: Test 7 - Once a POB is Propagated the Propagate Alternative _button_ should be removed from the screen.
Fix (hopefully) is ready for testing on Test3.
Anne

**Comment by geoffj-FUG** [comment]
Test 7 now OK.

Hold deployment until step 3 is available.
