### ISSUE TITLE
Welsh Returns

### ISSUE THREAD

**Issue by cmahoneynz** [FreeUKGen/FreeCENMigration#1789]
When it comes to the 1911 Census in Wales in which we have the individual household forms to transcribe, each household had the choice of of doing the return on a form written in English, or a form written in Welsh, result being that we have a number of returns done in Welsh.

A valid question that has come to me from a few people recently is what to do if a return has been done in Welsh, should they transcribe as is, or should they translate into English.

My response to them is that they are best transcribing as is without any attempt to translate, especially when it comes to people/place names, and the occuptions.

Other fields such as "Relationship to Head", "Marital Status" or "Language Spoken" will be using the same terms all the time so no problems with translating those.

Handbook has nothing covering this topic, so looking for official instructions on it.  Other websites such as FMP or Ancestry have done the 1911 returns with no translating done which is what I think we should be doing, and fits in with advice I have already given to transcribers

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG to look into fields on 1911 and we can begin shaping some guidance on this for the Handbook

**Comment by Vino-S** [comment]
@Vino-S to investigate that name search includes Welsh alternatives
Example: English: John
Welsh: Jein
If not covers, create a story.

**Comment by cmahoneynz** [comment]
As discussed at FreeCEN committee last weekend, this issue will also come up when we get around to doing the Irish, and Scottish 1911 census

**Comment by PatReynoldsFUG** [comment]
This story also applies to returns in Welsh in English censuses.

**Comment by PatReynoldsFUG** [comment]
For consideration: how far (if at all) should we go to support the users in understanding an entry not in English?  Should we provide a translation (in brackets), or a page(s) with some standard translations for Welsh, Irish and Scottish Gaelic?

**Comment by cmahoneynz** [comment]
Original query was should we translate returns into English, or leave them in whatever language was in, and update handbook etc with the appropiate information.

My view still is, leave as is, and don't translate.

I think the idea of providing users with guides, or other tools to translate such returns may be better in a separate story.

**Comment by DeniseColbert** [comment]
Decision: not to translate

@PatReynoldsFUG to create a story on how to support these searches and then this can be closed.

**Comment by PatReynoldsFUG** [comment]
Story created -  #3
