### ISSUE TITLE
299596208 Problem with replacing a file following the new pre-validate routine (John)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeCENMigration#1793]
Issue reported by **johnt** at 2024-06-29 13:10:08 UTC
Time: 2024-06-29T13:06:04+00:00
Session ID: 9bc94a66a1930db55c2448466367258b
Problem Page URL: [/freecen_csv_files/my_own?locale=en](/freecen_csv_files/my_own?locale=en)
Previous Page URL: [https://www.freecen.org.uk/csvfiles/667eb313b18f7c60c46c2e2e/edit?locale=en](https://www.freecen.org.uk/csvfiles/667eb313b18f7c60c46c2e2e/edit?locale=en)
Reported Issue:
I am in the process of updating an old VLD file, I downloaded it to the csv format, uploaded it then hit the commence validation routine. It gave me the new pre-validation routine which I accepted. Following the  successful message I downloaded the file and observed the 2 extra columns, but when I tried to replace the file it produced an error message about the 2 extra columns. I deleted the extra columns and the replace functioned correctly.    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
@geoffj-FUG  Ready for testing on Test3 now.

**Comment by geoffj-FUG** [comment]
See story #1785

This story will clear this bug.

Geoff

**Comment by geoffj-FUG** [comment]
Story #1785 is ready for deployment. Once deployed this story can be closed.

**Comment by AnneV-Learn** [comment]
@Vino-S This will be deployed with branch **fc_1785_86_87_93_av**  - see comment in story #1787
