### ISSUE TITLE
Duplication of Caud Hill and Cold Hill in Gazetteer

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1794]

**Comment by AnneV-Learn** [comment]
There is an issue in the Gazetteer, duplication of Caud Hill and Cold Hill which was identified as a result of a Feedback reference number 299757037. These must have been created before we tightened up the validation on Alternative Place names I guess. 
Could someone please review and advise on what the correct entry/entries should be.<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4c4fb904e2b35ff21b04d6356a738858405eaea/Screenshot%202024-07-01%20at%2012.25.05.png" alt="Screenshot 2024-07-01 at 12.25.05.png" />

**Comment by geoffj-FUG** [comment]
According to Genuki they are the same place. They have now been amalgamated in the Gazetteer as alternatives.

Geoff
