### ISSUE TITLE
If I search for St Mary in CHI I get results for IOM

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1799]
If I search for St Mary in CHI I get results for IOM. This also happens for other places with similar names.

Geoff

**Comment by AnneV-Learn** [comment]
Fix is ready for testing on Test3

**Comment by geoffj-FUG** [comment]
Now tests OK

Can be deployed.

Geoff

**Comment by DeniseColbert** [comment]
Done, closing
