### ISSUE TITLE
Define Quality Control functions (digital) for FC2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#180]

**Comment by edickens** [comment]
And we need Quality Control reports in FreeREG, so please remember when 
coding that the same could go into FR.  For example an analysis of the 
use of UCF.  Perhaps even the analysis of reported errors by researchers 
which may point to some bad transcriptions.  Also it is useful to know 
if a transcriber has had images for too long a time and needs to be 
contacted to find out why.  FreeREG is working on the RAP (Records 
Available Page) which will show what data we have and is waiting to be 
transcribed, and a GAP report which will show where registers have been 
missed and we need to get the gaps transcribed.  These reports, or 
versions of them, could be useful in the other projects.  We don't want 
to duplicate programming work. It is also useful for Coordinators and 
Transcribers if there is uniformity across the projects and we do have 
quite a few who work for more than one project.  E
