### ISSUE TITLE
Gazetteer not listing IOW places when HAM is selected as county

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1800]
Gazetteer not listing IOW places when HAM is selected as county. This should be working just like Yorkshire or Wales. See Appendix B of Handbook (Coordinator or Validator) This has the hierarchy in it.

Geoff

**Comment by geoffj-FUG** [comment]
Anne
I have tested HAM and IOW on test3. I removed 2 HAM entries for IOW places. I then tested a file with the IOW places in it, but entered as HAM. The validation process accepted them OK. 
So the problem is just in the Gazetteer.
Geoff

**Comment by AnneV-Learn** [comment]
Ok Thanks @geoffj-FUG

**Comment by AnneV-Learn** [comment]
@geoffj-FUG updated code now ready for testing on Test3

**Comment by geoffj-FUG** [comment]
Anne
That works well
We can deploy
Geoff

**Comment by DeniseColbert** [comment]
Done, closing
