### ISSUE TITLE
302972821 Adverts on working pages (Ali)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeCENMigration#1803]
Issue reported by **AH001** at 2024-08-07 15:07:01 UTC
Time: 2024-08-07T15:05:22+00:00
Session ID: 2c39d6b0855225cbd190b6f6f8d3d261
Problem Page URL: [/freecen2_places/search_names?locale=en](/freecen2_places/search_names?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen2_places/search_names_results?locale=en](https://www.freecen.org.uk/freecen2_places/search_names_results?locale=en)
Reported Issue:
Please could we not have adverts on logged-in working on pages? Thank you    

![Screenshot](https://www.freecen.org.uk)

**Comment by AnneV-Learn** [comment]
Hi Anne

I use Firefox, in Gazetteer the submit button is now below view so I have to scroll down to it as return doesn't work.

This seems to be due to space taken up by:

the advert at the top

or the expansion of the search counties info.

Any help would be appreciated

Thanks

Ali

**Comment by AnneV-Learn** [comment]
Actually this is more to do with the Note for county being expanded which pushes the Search button down. Screenshot sent by Ali:

<img width="1643" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5269476418f315bd4d511d04891eb748064faa87/Screenshot%202024-08-09%20at%2012-56-44%20FreeCEN.png" alt="Screenshot 2024-08-09 at 12-56-44 FreeCEN.png" />

**Comment by DeniseColbert** [comment]
Perhaps spread the text across the width of the white box, which would reduce the depth?

**Comment by AnneV-Learn** [comment]
I have tried to reduce the depth of the page and it is ready for testing  on Test3.

**Comment by DeniseColbert** [comment]
@geoffj-FUG to ask Ali to test

**Comment by suffolkroots** [comment]
@geoffj-FUG 

I've tested this, unfortunately not fixed, results sent to Anne.

Ali

**Comment by geoffj-FUG** [comment]
Ali

 

Thank you

 

Geoff

**Comment by AlOneill** [comment]
@AnneV-Learn 
Might I suggest removing the `grid` class from the form? It will not solve the original issue but it will fix the mis-alignment of the `fieldset`s wrt the light island,

**Comment by suffolkroots** [comment]
@geoffj-FUG 

Tested again all OK now, thanks all.

Ali

**Comment by AnneV-Learn** [comment]
@AlOneill 
Hi Alison - what mis-alignment is that (sorry but it is not obvious me)?

**Comment by AlOneill** [comment]
@AnneV-Learn 
No worries. I guess that asymetry might be a better description:

<img width="1546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmV1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08a5bb7f12b4cb9571886c87a3a1bb7dfd932ff4/FreeCEN___gazeteer.png" alt="FreeCEN___gazeteer.png" />

I have trained myself to spot this kind of thing. This is not the only similar instance in the members' pages — you'll be noticing similar issues yourself in due course.

In this case, no use is made of the grid and so deleting the class is the simplest fix. Hope that helps.

**Comment by AnneV-Learn** [comment]
@AlOneill  - Oh right - Thanks Alison, I'll sort that  :)

**Comment by AnneV-Learn** [comment]
Corrected and tested myself. 
Ready for Deployment.

**Comment by AlOneill** [comment]
@AnneV-Learn 
Looking good. Thank you.

BTW the fix for similar misalignment on other pages will not necessarily be to remove the grid class: the alternative might be to give (direct) children of the grid the class `grid__item`, especially where responsive classes are used. Sometimes it is simply a matter of ensuring that grids are closed as appropriate. But spotting the issue in the first place is the essential initial step.

**Comment by DeniseColbert** [comment]
Deployed: closing
