### ISSUE TITLE
Problem with display of Locate pieces

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1804]
Chris M writes that
There is a fault with the locate piece option on the website that was not there last week.
Tried it on a few pieces today to see what happens, two samples follows:
HO107_1408  -  Incorrectly showed only the one piece, not the three parts that this one is split into
HO107_2127  -  Correctly showed the two different splits of the piece
Tried other split pieces from different years, in almost all cases the website only showed the one split, not all the ones that the piece was split into.
This will need to be sorted as it was the easiest way to check how a piece has split, and what where the current civil parishes for the various splits of the piece.

I have tested it and the problem appears to be with the A B etc. If I try and locate RG12_1868 SOM I only get the SOM entry. I do not get the entry for DEV of RG12_1868A.
If I try and locate RG12_1872 I get nothing returned. There is a piece RG12_1872A which is in DEV.

The bug seems to have been introduced with the CAP update. It is essential that the breakup of the pieces be seen as this is the way that the Coordinators get their info to break up a piece.

Geoff

**Comment by Vino-S** [comment]
DEployed
