### ISSUE TITLE
Offset data problem RG9_2666

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1806]
@Vino-S 
Vino

I have a report from the Coordinator for Lancashire regarding with a problem in a vld file. I hve attached a vld download of the piece.

If you go to record with a key of 790003 you will see that the data is suddenly offset. I can reload the data but if I try to correct the glitch I may make things worse.

I have sent a copy of the txt file attached to an email.

Can you help please?

Geoff

**Comment by Vino-S** [comment]
Hi @geoffj-FUG ,
I have removed the file from the system. Could you have a look, please?

**Comment by DeniseColbert** [comment]
Please could you look on live @geoffj-FUG ?

**Comment by AnneV-Learn** [comment]
@geoffj-FUG 

I am not able to load the file that you emailed me (I get the same error as you). I don’t know enough about the VLD file format to try and fix it.
I am able to find a copy of the VLD (dated 08/03/2019) on the server and it didn’t appear to have an offset problem. When I tried loading that to my local copy of FreeCen it loaded ok and searches on the people around the supposed offset record seemed to work ok. I actually corrected the OVB birthplace records to be OVF (and added British to the Notes) prior to uploading locally. I tested searches on those records too and all seemed ok.
Do you want me to try loading that in the Production environment?

**Comment by geoffj-FUG** [comment]
Anne, Yes please.

I will send you the flat file by email.

Geoff

**Comment by geoffj-FUG** [comment]
Anne

 

Flat file attached. I have given it the suffix of vld.

 

The misplaced entry has been corrected and everything now aligns.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG there was something wrong with the format of the file you sent in the email - it would not load (I got the same error as you did originally).
I have now uploaded the file from the FreeCen attic (dated 08/03/2019) to Production system, however I corrected OVB birth county occurrences to be OVF (and added British to the Notes) prior to uploading.
Let me know if that is OK or not.

**Comment by geoffj-FUG** [comment]
Anne

 

That has fixed it. I pre-validated it and it now only shows 20 invalid POBs. I have downloaded it as csv and all records are structured correctly.

 

Thanks for your help.

 

Geoff

**Comment by geoffj-FUG** [comment]
I hve checked the corrected file that Anne loaded and it now downloads correctly as a csv.

I am closing this story.

Geoff
