### ISSUE TITLE
URLs with search query ids shouldn't be server specific

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#181]
search_query is in a distinct local_writable database on each server.  URLs (such as the search results and details) that use a search query parameter only work on the specific server the user is on when the query is made.  Any such URLs used for bookmarks,  sent in email, reported in contacts / feedback, etc. are only valid on the original server, but due to load-balancing users may be assigned to a different server on any particular visit (in which case they just get silently redirected to the new search page instead of what they expect to see).

If it is not too much of a performance impact, we can just move from a local database to replicated.

**Comment by richpomfret** [comment]
To review with 1.2 (not high priority).

**Comment by dougkdev** [comment]
This is done.  URLs with search query ids are no longer server-specific as search_queries are now stored in the main database instead of a separate local_writeable database on each independent server.
