### ISSUE TITLE
Update Move Civil Parish Rake to include population of Admin_county

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1812]

**Comment by AnneV-Learn** [comment]
Rhoda asked me to run the  Move Civil Parish Rake but it failed and I found that the Rake script needed to be updated to include the population of the Administrative County field.

**Comment by AnneV-Learn** [comment]
I have tested on Test3 and looks OK now so is ready for Deployment to Production.

**Comment by Vino-S** [comment]
DEployed
