### ISSUE TITLE
Archival process for RECORDS data

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1814]

**Comment by AnneV-Learn** [comment]
The FreeCen RECORDS feature has been live for about 2.5 years now but there is no archival process for the data and to remove historic records from the collection that drives these screens would probably be beneficial in terms of retrieval speed. 
During those 2.5 years there has never been a request to look back at historical RECORDS data, and I am not sure that would be a relevant thing to do anyway, so I am wondering if we should update the process so that the collection only stores the latest data.

@DeniseColbert, What are your thoughts please?

**Comment by DeniseColbert** [comment]
Suggest archive the data after 30 days, delete after 60 days. 

Review in 6 months.

**Comment by AnneV-Learn** [comment]
Coded and tested on Test3. This cannot be user tested,  so now Ready for Deployment to Production.

**Comment by DeniseColbert** [comment]
Done, closing
