### ISSUE TITLE
Update VLD POB Validation process so that it handles files with no 'Individual' records

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1815]

**Comment by AnneV-Learn** [comment]
Whilst running VLD POB validation across CHI encountered a VLD file that had no individual records. 

Explanation from the County Co-ord:

****
I have checked my records for CHI.
RG094389 is a piece number issued by TNA for the island of Sark, but there are no records anywhere, assumed lost.
The VLD was created to reflect this and should have one record explaining this.
I'm not concerned if it is deleted, except that someone, sometime, somewhere may look for these records, resulting in more head-scratching.


I recall thinking that if such pieces are ignored then the particular County will never be 100% complete. This will inevitably cause questions in the future.
****

VLD was reloaded and appeared to load successfully this time but need to update VLD POB validation process to handle this scenario.

**Comment by AnneV-Learn** [comment]
@Vino-S - Could you  you please deploy **fc_1815_av** to **TEST3** (I have created Pull Request)

**Comment by AnneV-Learn** [comment]
Successfully tested on TEST3.
Branch **fc_1815_av** is ready to be deployed to Production.

**Comment by DeniseColbert** [comment]
Done, closing
