### ISSUE TITLE
Add password to Manual validation option in vld collection

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1818]
I have found at least one coordinator who is trying to use this option (and still is despite my asking coordinators not to use it). 
Can we please add a fixed password to this item. It does not need to be changeable.

How about ManualValidation.

Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG Another solution would be to restrict 'Manual Validation' to System Administrators and Data Managers. Would that solve the issue?

**Comment by geoffj-FUG** [comment]
That would mean that I would have to redesignate the validator who is working on LAN to seed the north of England data would need to be promoted to Data Manager.

 

She is very reliable so I am happy to do that.

 

Geoff

**Comment by AnneV-Learn** [comment]
@geoff-FUG I have restricted  VLD Manual validation to System Administrators and Dara Managers on **Test3** as suggested, as that is a simple change. 
If moving forward that becomes cumbersome we can add a password.

**Comment by geoffj-FUG** [comment]
Anne

 

That sounds great. That should solve misuse of the action.

 

Geoff

**Comment by geoffj-FUG** [comment]
Tests OK. Coordinators now barred from the manual validation option. Data manager OK.
Ready to deploy.
Geoff

**Comment by Vino-S** [comment]
Deployed

**Comment by DeniseColbert** [comment]
Deployed: closing
