### ISSUE TITLE
Remove DEV Newton/Newtown from prevalidation data

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1819]
@AnneV-Learn 
There is an entry for Devon to prevalidate Newton as Newtown. This is incorrect as there are 2 Newtons in Devon.
Please remove this entry from the prevalidation data.
Geoff

**Comment by AnneV-Learn** [comment]
@geoffj-FUG I have now removed the revalidation propagation record (DEV Newton) as requested.

**Comment by geoffj-FUG** [comment]
Thank you.

 

Geoff

**Comment by geoffj-FUG** [comment]
Done. Closing
Geoff
