### ISSUE TITLE
ADSENSE 5 (3) the placement of adverts on other pages

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#184]
Consider adding a sticky advert to the right of the table

**Comment by AlexAvlonitis** [comment]
Hi @PatReynolds Which table is that?

**Comment by PatReynolds** [comment]
Cannot  now remember ... possibly on 'help'.  We have found sticky adverts don't work well there.  Can you put an advert same size/shape as the "Want to know more about Soundex?" block?  I think I might need to create a new advert to fit there - could you give me dimensions and whether it needs to be responsive or not?

**Comment by PatReynolds** [comment]
Draft layout sent to @Vino-S 5/4/2017

**Comment by PatReynolds** [comment]
No other place needing advertisements, so to close.
