### ISSUE TITLE
Update references to Free UK Genealogy to reflect change to CIO

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#189]
From 1st January 2017 - where we give the registered charity number, this is now: 1167484.  Where name is formal (e.g. where registered number is used) Free UK Genealogy should be changed to Free UK Genealogy CIO.

**Comment by PatReynolds** [comment]
Now back on the to do list (with change at 1st January 2017.

**Comment by benwbrum** [comment]
The new footer reads:

`Search engine, layout and database Copyright © 1998-2015 The Trustees of Free UK Genealogy, a charity registered in England and Wales, Number 1167484. We make no warranty whatsoever as to the accuracy or completeness of the FreeCEN data. `

Is this good enough?

**Comment by PatReynolds** [comment]
Search engine, layout and database Copyright © 1998-2017 Free UK Genealogy CIO, a charity registered in England and Wales, Number 1167484. We make no warranty whatsoever as to the accuracy or completeness of the FreeCEN data.

**Comment by AlOneill** [comment]
FreeCEN or FreeCen ??

**Comment by PatReynolds** [comment]
FreeCEN

**Comment by PatReynolds** [comment]
On FreeCEN2.

**Comment by richpomfret** [comment]
Potential task for our new Ruby dev.

**Comment by richpomfret** [comment]
Is this now complete? Would be great to get it done if it's a super quick task.

**Comment by richpomfret** [comment]
Now added and on test2. To deploy to live.
