### ISSUE TITLE
ADSENSE Try alternative placement of Advert on Detailed Results page (also place on Results page)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#193]
People don't like the current position, which splits the heading from the family

**Comment by PatReynolds** [comment]
New layout sent to Vino 5/4/2017

**Comment by Vino-S** [comment]
Thanks Pat, 
I will start working on this once I finish the current work item(Freereg #842  and #843)

**Comment by PatReynolds** [comment]
Ah, now I realise this was the DETAILED results page.  Will send through new design for this.

**Comment by PatReynolds** [comment]
Advertisement on DETAILED results Page FreeCEN drawing now in folder on google drive.

**Comment by Vino-S** [comment]
Thanks Pat
