### ISSUE TITLE
"viewed" on results page not showing up

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#194]
After viewing details and clicking on "Back to Results" the results list should show "(viewed)" under the detail link for each detail already viewed. This seems to have stopped working at some point.

**Comment by richpomfret** [comment]
Another potential task for our new ruby dev.

**Comment by dougkdev** [comment]
I believe I found and fixed the problem while resolving a conflict during the process of merging master.  There was previously a change in how FreeReg handled the "viewed" status and we didn't notice the change to update the app-specific freecen partial to handle the change.
Will go ahead and fix. Not yet deployed or tested.

**Comment by dougkdev** [comment]
Fix is working in development, not yet deployed.

**Comment by dougkdev** [comment]
Deployed to test2. Fix seems ok.

**Comment by PatReynolds** [comment]
Working for me, too.
