### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#196]
Your search was running too long. Please review your search criteria. Advise is contained in the Help pages.

correct to 'advice'

**Comment by richpomfret** [comment]
Another potential task for our new Ruby dev.

**Comment by dougkdev** [comment]
Typo no longer there- must have already been fixed in Reg before we merged.

**Comment by dougkdev** [comment]
verified already fixed in Reg. This is deployed on test2.
