### ISSUE TITLE
Details page cropped on mobile devices

### ISSUE THREAD

**Issue by draagc** [FreeUKGen/FreeCENMigration#199]
On the details page the table is cropped on mobile phones and can't be scrolled left to right so it is totally unusable.

Please see the following document for more information.

https://drive.google.com/open?id=1MwU3rcLTgRDx53wqYWoDwRqEW2VMZzmZG-giiKUy2rs

**Comment by richpomfret** [comment]
A few possible solutions for this - switch to lists (like FreeREG), or recommend users go into landscape view, or/and allow users to scroll across. To test and action accordingly.

**Comment by richpomfret** [comment]
Most pressing fix for this would be to allow users to scroll across. Let's do this first and consider a message suggesting landscape as a secondary addition.

**Comment by AlOneill** [comment]
To allow horizontal scrolling, simply wrap each table (separately) in a div like so:
`<div style="overflow-x: auto;"></div>

**Comment by AlOneill** [comment]
To enable horizontal scrolling, simply wrap each table (separately) in a div like so:
`<div style="overflow-x: auto;"></div>`

**Comment by richpomfret** [comment]
Doug/Rich to review.

**Comment by dougkdev** [comment]
Scrolling works fine for me on my android phone.
