### ISSUE TITLE
Research: Analyze FC1 VLD files

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#2]
2) The Legacy Data

A more difficult problem is understanding the data produced by the last 15 years of the transcription effort.  Unlike FreeREG, FreeCEN's canonical source format isn't CSV files, but VLD files.  These appear to be a  fixed-field database format which I gather was used at some point in FreeCEN's history.  It's no longer used operationally, but is their standard -- transcribers send CSV files to coordinators, who transform them to VLD files, then ingest them into the MySQL database.

We'll need to figure out how to parse these VLD files, watching out in particular for variations in fields between different census years.

These files live on test.freereg2.org.uk under
 /raid/freecen/pieces/

**Comment by EmJayFry** [comment]
On 2015/01/03 06:59 PM, Ben W. Brumfield wrote:

> We'll need to figure out how to parse these VLD files, watching out in
> particular for variations in fields between different census years.

(Courtesy of the web)

The VLD file extension is mainly related to DataFlex. This file type was 
introduced in DataFlex 3.0.

When VLD files are used, the VLD file holds the real data and the DAT file 
simply holds a pointer to the location in the VLD file where the data resides. 
Therefore, when backing up or restoring a datafile, it's vitally important that 
the DAT and VLD (and HDR) be kept in synchronization with each other. A VLD file 
without a DAT file is completely useless, just like an index file would be 
without its DAT file.

Unable to find a site that describes the physical file format.

-- 
Regards,
Mike Fry (Jhb)
