### ISSUE TITLE
Improve Donate request

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#201]
Improve pathway, placement and text

**Comment by PatReynolds** [comment]
Use google analytics to track pathway?

**Comment by richpomfret** [comment]
Pathway>straight through to Free UK Gen donate page. Nice to have ability to track where users are coming from (i.e. which site) prior to donating. Placement - to remove donate from header? Place below instead (button). Text i.e. 'if you are happy with the results and wish to keep X free, then please donate'. Idea of different text each time.

**Comment by PatReynolds** [comment]
I think this is now all broken down to individual stories.
