### ISSUE TITLE
Prevent deletion of  a piece number in a parms file

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#203]
Trying to delete a specific PIECE number in a current PARMS file. We can amend details within a PIECE number, but cannot delete a PIECE number. These mostly relate to the Records that were lost over 100 years ago before they reached the National Archives. Doug suggested we could possible mark the number as "Data lost" instead. Therefore the system will not need to account for it when all the other PIECES for that Census Year x County are complete and will then show as 100% done. We can however still use the FreeCEN 1 current system for the time being. Brenda

**Comment by PatReynolds** [comment]
CF what is being done with images on FreeREG (marking some as non-existant)

**Comment by Captainkirkdawson** [comment]
Suggest this be closed as we are evolving towards a fixed parms/piece structure based on TNA
