### ISSUE TITLE
improve performance of nightly update file checks

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#204]
Disk i/o is significantly slower on production than I had expected when I initially wrote the nightly update task. Because of that, some reworking of how the script checks for updates needs to be done before we turn on the cron job that automatically runs the update script each night. If we were to enable the script as it is currently written, we would likely see performance problems similar to those that we have been seeing with the nightly freebmd rsyncs bogging down the system (which required the various cron job times to be staggered).

**Comment by richpomfret** [comment]
To discuss on Wed.

**Comment by dougkdev** [comment]
On the test server it only takes about 3 or 4 minutes to check all .vld files for changes (compares md5 digest of the .vld file to digest of the piece stored in the database).  The reason I created this story is because it was taking more like 30 or 45 minutes on production due to the poor disk performance.  If the disk i/o problems on production get resolved there may be no need to make significant changes to the way nightly update file checks are done. I recommend we wait and see if there is resolution on the disk performance issues that makes this story unnecessary.

**Comment by richpomfret** [comment]
Revisit after server re-config changes.
