### ISSUE TITLE
rebuild, redeploy mongo database

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#207]
#206 will require a rebuild (on vervet), followed by deploy of the rebuilt freecen2 database to production. 

The instructions developed by Kirk for deploying to production should be followed, (skip the steps for copying the db from production to vervet first since we are still building directly from FC1 data).
The new developer should be involved in this to learn how. Doug can guide through the rebuild. Ben guide through the deploy.

**Comment by dougkdev** [comment]
Note, this goes hand-in-hand with #206, see comments there.

**Comment by PatReynolds** [comment]
Does this story now include sharding, or does that need creating as a separate issue?

**Comment by dougkdev** [comment]
Let's use a separate story for the sharding tasks. #260 created. Status for this story: rebuild completed, but deploy of the rebuilt database is stuck due to vervet crashing when Kirk tries to clone the database to the new mongo servers.
