### ISSUE TITLE
Email on contact going to Alex and Doug

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#211]
Should go to coms coord only

**Comment by dougkdev** [comment]
Adding @Vino-S to help on this story so she can become familiar with the contact/feedback/system-emails portion of the code.  This is a part of the code that gets clobbered nearly every time we merge master into freecen, so good for her to be familiar with it for resolving conflicts in the future.

**Comment by dougkdev** [comment]
@PatReynolds do you still want the contact email to go to the county coordinator if the user selects a specific county? Or only to coms coord? or copied to both the County Coord and Coms Coord?

**Comment by dougkdev** [comment]
Contacts go to the coms coord email address now instead of admins.
