### ISSUE TITLE
Consider implementing results counter on search page

### ISSUE THREAD

**Issue by draagc** [FreeUKGen/FreeCENMigration#214]
A results counter could be implemented on the search page so that the user knows how many results his search will return before actually searching. This way users won’t have to go back to the search page if there are too many results and they will be able to better adjust their search. Below there is an example from a car marketplace website.

![mobilede1](https://cloud.githubusercontent.com/assets/24566509/23706886/ff8351e6-0407-11e7-8e0a-2cfc1b0338f1.png)
![mobilede2](https://cloud.githubusercontent.com/assets/24566509/23706894/04c30142-0408-11e7-8bc4-29be0a05f0d0.png)

**Comment by Captainkirkdawson** [comment]
Also as systemwide 119

**Comment by Captainkirkdawson** [comment]
But the search has to be done to get the number and if very large would time out
