### ISSUE TITLE
ADSENSE: place advert on Database coverage page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#216]
Banner should be responsive.  Opportunity for another one between two census years?

**Comment by PatReynolds** [comment]
@Vino-S - my mock up had multiple adverts, and I've now remembered we are restricted to 3 per page, so: do we have to have the advert at the top of the page (header)?  Please put the remaining two or three between 1851 and 1861 and 1861 and 1871 (also between 1881 and 1891 if we don't have the one in the header).

**Comment by Vino-S** [comment]
**@PatReynolds** I think keeping an advert at header will be a good idea as it can be easily viewed by our users when the page loads.
