### ISSUE TITLE
Place text (encouragement to donate) and icon on record page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#218]

**Comment by PatReynolds** [comment]
The text is "While most other genealogy sites charge you to find and read records, FreeCEN is dedicated to keeping our searches free. A small donation towards our costs would really help us keep it that way."

**Comment by israelriibeiro** [comment]
@PatReynolds , i think @Vino-S already solve this one: 

https://github.com/FreeUKGen/MyopicVicar/commit/06de18e4318cc98934ebc9929473e494416ef735

Sorry for i'm truly late.

**Comment by PatReynolds** [comment]
thank you @israelriibeiro I will close now.

**Comment by DeniseColbert** [comment]
Can we remove the link 'Make a Donation' below the text?

**Comment by Vino-S** [comment]
Hi Denise,

I had removed the link from records page and details page. Please have a look.

Vino

**Comment by DeniseColbert** [comment]
Yep, confirmed link is gone. Thanks Vino.
