### ISSUE TITLE
Check structuring of Coords as Checkers, etc. - Modify roles from FreeREG to reflect FreeCEN organisation

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#222]

**Comment by richpomfret** [comment]
To define roles - validator, co-ordinators, communications, chair (for Brenda). Check against FreeREG roles.

**Comment by PatReynolds** [comment]
County Coords are for a single census within a county (because some counties have a different coord for different censuses)

**Comment by PatReynolds** [comment]
Ideally, a coordinator who validates or transcribes for another coordinator can do so under their coordinator id - is this possible?

**Comment by richpomfret** [comment]
Not essential for launch.

**Comment by PatReynolds** [comment]
*Role 
All options: researcher, trainee, pending, transcriber, syndicate_coordinator, county_coordinator, volunteer_coordinator, data_manager, technical, system_administrator, contacts_coordinator, project_manager, executive_director, publicity_coordinator, genealogy_coordinator, documentation_coordinator, engagement_coordinator

Suggest: all, PLUS checker

**Comment by richpomfret** [comment]
Also require: validator

**Comment by dougkdev** [comment]
checker and validator roles added. (deployed to test2, not yet on production).

**Comment by dougkdev** [comment]
deployed to production

**Comment by richpomfret** [comment]
Needs population for further testing.
