### ISSUE TITLE
creating new userid fails after merge

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#228]
high priority because other 1.1 stories depend on this (including #211). pulling into current sprint.

**Comment by dougkdev** [comment]
crash was caused by the honeypot / timing code merged in from FreeReg, which handles the workflow through the transcriber signup form, but not the workflow through the admin action for creating new userids.  I have temporarily disabled the honeypot on freecen and created story #229 to fix the admin action. Also notified @Captainkirkdawson and @Vino-S in case the bug is system-wide.

**Comment by Captainkirkdawson** [comment]
Fix applied in FR on the master branch

**Comment by dougkdev** [comment]
Thanks @Captainkirkdawson!

**Comment by dougkdev** [comment]
deployed to test2
