### ISSUE TITLE
filename field null in some pieces in database

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#230]
the freecen1_filename field is not getting propagated to the freecen_piece document in the database for most pieces. The field is null for 13181/16703 pieces. Does not affect search.

**Comment by dougkdev** [comment]
to clarify: we expect the filename to be null for VLDs that have not yet been uploaded.  However, quite a few pieces listed as "Online" also have null filename in the corresponding freecen_piece database document.

**Comment by FreecenBren** [comment]
Do you have a list or one or two I can look at to see if I can see the
problem
Brenda

**Comment by dougkdev** [comment]
This is caused by a bug in the code, so no need to look at the VLDs for this story. I just need to track down where the code fails to propagate the information to a particular part of the database. Thanks.
