### ISSUE TITLE
Import existing users (and their roles and email addresses)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#234]
Follows on from #235

**Comment by PatReynolds** [comment]
Do we need a one volunteer ID = 1 county relationship?

**Comment by FreecenBren** [comment]
FreeCEN has  transcribers, Checkers and Validators that work on multiple
roles and cross Counties.
Example I have one who transcribes  Essex and London, checks both as well
as  is a checker for EWS.
He is not the only one who mixes and matches.

**Comment by PatReynolds** [comment]
@dougkdev to send pat list of field names used

**Comment by PatReynolds** [comment]
@patreynolds to remind @dougkdev and check what development (if any) is still needed on message system

**Comment by dougkdev** [comment]
@PatReynolds I emailed you the list of fields on July 5 and you replied on July 6. Is there something else you are waiting for from me?

**Comment by PatReynolds** [comment]
I have finished the coords for upload.  Not a priority for today, but for next week - will send link to @FreecenBren @Vino-S and @dougkdev.  

Vino/Doug are the multiple roles in Role ok for upload (and what should be added for Brenda, Mike and Rena who have additional roles?)Is the format for 'county' what you were expecting? 

Brenda, can you add more county details, once we know what the format should be?  What should be in Syndicate? If a COORD has a main county it could be the county name (e.g. SomersetSyndicate) or we could just give a number Syndicate1, etc.)

**Comment by PatReynolds** [comment]
Syndicatenames: KentSyndicate,  DevonSyndicate, etc.  Roles to be in a single field. @pat_reynolds to finish for V/C/Ts and send to Vino.

**Comment by PatReynolds** [comment]
@Vino-S do you need now to create all coords as syndicate coords, with same county responsibilities?  KentSyndicate, DevonSyndicate, etc.?

**Comment by PatReynolds** [comment]
Apologies, @Vino-S see you have created the syndicates - I will now update V/C/Ts listing with the syndicates.  @FreecenBren can you check the syndicate coord listing in test2, and ask @vino-s to set to 'false' any counties that do not have records to transcribe at the moment, please.

**Comment by FreecenBren** [comment]
I have done them in Test 3 for England & Wales, Still cannot get into test2.
Scotland ones I am still checking out.


Sent from Mail for Windows 10

**Comment by richpomfret** [comment]
Tested and now on Live.

**Comment by richpomfret** [comment]
Let's test this further with larger files (as we are likely to import 400 plus users).

**Comment by richpomfret** [comment]
Should now be fine, but for Pat to test out too.

**Comment by PatReynolds** [comment]
Syndicate coordinators appear not to have been imported, at least for some (no existing volunteer should be 'all counties'

**Comment by Vino-S** [comment]
Updated the syndicate coordinators for most of the users. 
I need to send @PatReynolds the list of transcribers for whom I do not have syndicate_coordinator.

**Comment by richpomfret** [comment]
@Vino-S to check that there are no 'all counties' users coming through. @PatReynolds to clarify if needed.
