### ISSUE TITLE
cron/task to clean up search records

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#236]
Reg has a cron/task to clean up search records after 40 days. We need to do similarly on Cen.

**Comment by dougkdev** [comment]
no changes are necessary to the script for frecen. just needs to be turned on in cron once merged in from master and deployed to production.

**Comment by PatReynolds** [comment]
@dougkdev can this be done now?

**Comment by Vino-S** [comment]
Hi @PatReynolds ,
This has been implemented.

**Comment by dougkdev** [comment]
Looks like Vino has merged the script from master but the cron job to launch the script has not been added yet.  I will add it.

**Comment by dougkdev** [comment]
Ok, cron job set to launch the script.
