### ISSUE TITLE
don't show unstyled donate icon on print-friendly

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#239]

**Comment by dougkdev** [comment]
The donate icon was being displayed on the print-friendly results list, but without css styling, so it was a sequence of huge (full-page-width) independent shapes instead of the shapes being combined into a single icon. I added logic so the icon is not shown on the unstyled print-friendly page. Deployed to test2.

**Comment by DeniseColbert** [comment]
Working for me- no icon visible, just the external link
