### ISSUE TITLE
Create Birth Place Survey

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#242]
Dependent on #167 Discussion of how current search works now in #167.

**Comment by PatReynolds** [comment]
How does the current search by birthplace work, given that the place may not be associated with a county, and is twys?

**Comment by FreecenBren** [comment]
In FC1 we can select 'all Census Places,  'all Census Counties'  'All birth
Counties' and then type in the Place of birth.
FC1 does not give you the option of All Census Years, so you have to search
one Census year at a time.

FC1 also lets you search by 'occupation ' 'Street' 'ED' 'Civil Parish'
'Folio'  'Language' etc. etc..
Not sure how many people use those options as you need to know most of them
to use them?

**Comment by richpomfret** [comment]
A new survey task has emerged from this in terms of how we change the search.

**Comment by PatReynolds** [comment]
@Vino-S please add link to survey (sent by email) to search page (jcode already exists for the heading 'Birth Place', but rather than any search function, we need at this point the text "We are developing the birth place search feature. We would be grateful if you could spare 10 minutes to fill in our survey - this will take you to a new tab/page, so you can come back to this tab/page to complete your search."  Drawing of layout here: https://docs.google.com/a/freeukgenealogy.org.uk/drawings/d/1LcD-izunL-NPqkC613gyvPZcfwSW2seky5cKXQnuUuE/edit?usp=sharing
