### ISSUE TITLE
Change colour suite of FreeCEN to one more accessible

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#245]
Current yellow/gold does not provide enough contrast for people with low vision.  Brand colour therefore to be changed to more accessible one. 

Milestone: ideally before launch, but should not hold it up.

Economic 1, Urgency 10, Strategy 5, Cost 2?: P=18

Needs FreeUKGen/MyopicVicar#931 on FreeREG

**Comment by PatReynolds** [comment]
Need samples of potential colours (with writing on to see how clear they are).  Also block of colour with the other three logos to check that it is distinctive from other projects and complimentary to them in tone.

**Comment by richpomfret** [comment]
This tool might help assist with this (shows accessibility etc): https://material.io/color/

**Comment by DeniseColbert** [comment]
https://docs.google.com/document/d/1TMj0czJlfSHUoZruiDQ4mrJJaK8ZB4871F27DF3h3mA/edit#heading=h.qmu4ctqqqrh9

**Comment by richpomfret** [comment]
First step to identify all the areas that need to be changed.

**Comment by DeniseColbert** [comment]
On the colour document, the FreeCEN purple colour code doesn't seem to match the actual colour:
![FreeCEN purples.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5728dc91cdca690e00eef9ad/125516c66e82c728ace21e0d46ce869f26a1a687cff9aa51b451f5876b0a65633b0ba92e7391a172fd172f00575e1da8445d5742fcf0892ba4b63c75885e02e4d87f4366846c4ff8e7df46f554f832815d87b0b68b48c9ef3827e2828d4d3f18030ac4.PNG)

**Comment by AlOneill** [comment]
This is the state of play for proposed colour changes to links, in all their varieties. The main navigation, buttons and plain links are all done. The sub navigation and the island/islet styles are still WIPs.

![FreeCen__link__colours.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d6b34aaa56cfab2a492b7c3c16b0693cc7f33ab0487e021b4d44be445c0e4cfdaa8d2ea3be3a70835c0befd16d5a76c43418a5aa9e0dfd50e474d412dcfce9c85ecafa3e27ed8a8b46361e001a8dfb5833a09a5985.png)

**Comment by AlOneill** [comment]
This is where I have got to. 
TODO: breadcrumb styles

![FreeCen__Links.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d6934aaa56e3d665043761260ea62864c7b96aea167a595e0c4aa944505944f5f98929a6b63972885502e4c3714d36976345f3e5db55ea43a82a994d83bcbd8e45c9ea3822ee8c86483c1f1755.png)

**Comment by AlOneill** [comment]
Figured out how breadcrumb class (in current CSS) is intended to be used!

The final item is *not* a link (it denotes the page the user is on) and so should not look like one.

![FreeCen__Links.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d6934aaa56e3d665043761260ea62864c7b96aea167a595e0c4aa944505944f5f98929a6b63972885502e4c3714d36976345f3e5db55ea43a82a994c84bcbd8e45c9ea3b24e5828d4e3d181755.png)

**Comment by PatReynolds** [comment]
@AlOneill to try the purple.

**Comment by AlOneill** [comment]
Here is the FreeCen logo with purple instead of orange/gold.
(other colour change to follow)

![FreeCen__Links.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d6934aaa56e3d665043761260ea62864c7b96aea167a595e0c4aa944505944f5f98929a6b63972885502e4c3714d36976345f3e5db55ea43a82a994d83bcbd8e45c9ea3a26e48e8c4a3e1c1755.png)

**Comment by AlOneill** [comment]
Change made to focus(/hover) background colour — good call, Pat.
Logo changes are mine and thus speculative — I do not know what the design volunteer will/has come up with!

![FreeCen__Links.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d6934aaa56e3d665043761260ea62864c7b96aea167a595e0c4aa944505944f5f98929a6b63972885502e4c3714d36976345f3e5db55ea43a82a994c84bcbd8e45c9eb3824e38889463e1d1755.png)

**Comment by AlOneill** [comment]
This is the proposed hover/focus styling for the project logos. Visible focus styling is required for accessibility; hover styling is up to us — I suggest we make it visible.

![FreeCen__Links.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d6934aaa56e3d665043761260ea62864c7b96aea167a595e0c4aa944505944f5f98929a6b63972885502e4c3714d36976345f3e5db55ea43a82a994c84bcbd8e45c9e03b23e48f8b473f181755.png)

**Comment by PatReynolds** [comment]
Thank you - that looks good to me.

**Comment by AlOneill** [comment]
This is the proposed focus styling for the skiplink. Hover styling is not required. (The skiplink is not initially visible, as requested. It becomes visible when a user hits tab, straight after page load. The link is followed by hitting Enter. Our pages do not currently have a skiplink.)

![FreeCen__Links.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d6934aaa56e3d665043761260ea62864c7b96aea167a595e0c4aa944505944f5f98929a6b63972885502e4c3714d36976345f3e5db55ea43a82a994d83bcbd8e45c9e03b23ef838b4d371f1755.png)

**Comment by AlOneill** [comment]
I think that is all the varieties of link covered. Let me know if I have missed any!

**Comment by DeniseColbert** [comment]
Looks lovely Alison. I sent the logos in last scrum, but I think the jpg is slightly off-colour, dimensions don't match the others, and the background isn't white. Could you please send me your version?

**Comment by AlOneill** [comment]
@DeniseColbert Thanks! Not sure what I can send you exactly as I simply changed the colour values in the CSS file which is built from the individual logo SVG files. But I can tell you the colours I used ...

Using the accessible version of teal plus the new link purple was too dark/murky for logo, so I lightened both a little: the RGB values are respectively 007e78 and 7d29a7. The logo backgrounds are actually transparent — the white you see is from the page background colour.

Sorry, but not aware of receiving any logos from you.

**Comment by DeniseColbert** [comment]
Ah ok, thanks Alison.
So are we going to have accessible link colours, and different logo colours?
Can you tell me the code you're using for the accessible teal please? The values don't match on the working doc.

**Comment by DeniseColbert** [comment]
PS- not sure what happened to the logos email!

**Comment by AlOneill** [comment]
@DeniseColbert Whether or not the link and other accessible colours are used 'as is' in the logo, or modified a little will depend on what your design volunteer comes up with. I did not like the way the accessible colours blended (without other mods to the logo image file) and just wanted a good enough but quick fix for the examples page.

Accessible teal is 00605b

**Comment by AlOneill** [comment]
Lawks! Forgot the palm navigation. Will change colours of Menu button to use accessible teal; menu items will be purple on same light grey as currently. Both will reverse on focus/hover.

The cancel button (big X) colour will be accessible teal. However, the current hover does not work in Firefox (neither does it work in FreeReg on Firefox). Only visible indication is that pointer changes to hand. On Chrome, hover state *is* visible. I do not know why this should be. Chrome developer tools are not entirely helpful, but will attempt to investigate further ...

**Comment by AlOneill** [comment]
Have found the changes for the `icon__cancel ` CSS class.

@richpomfret @Vino-S @dougkdev 

Now ... finding the styles to correct was the easy part: how best to implement?

The easiest and quickest way would be to put all the changes into FreeCen's version of `freereg_contents.css` — however any subsequent edits would be error/anomaly prone and would be bad news for users as they would add 250+ lines, plus the `icons.data.svg.css` edits, to the CSS downloads and browsers would have to work harder to sort it all out for the screen. (I hope that makes sense!)

A better way would be to make the changes in the `app/assets/stylesheets/styles/scss/' folder. All but one of the files are already there: we would need a 'icons.data.svg.scss.erb` file to make the icon changes. I assume this can be done, but I can't find the icons CSS file in the `app/assets/stylesheets/FreeUKGenealogy-Core-Frontend/' folder?

Any comments, corrections (to my understanding!), or suggestions welcome!

**Comment by PatReynolds** [comment]
Is there anything in the Redisign folder on the gdrive?  I've just added @dougkdev and @benwbrum to that folder.  There's an icons.data.svg.scss file in /freereg/styles/css there.

**Comment by AlOneill** [comment]
@PatReynolds  FreeCen must get/create its own version of `icons.data.svg.css`, distinct from the FR (and UKGen) version in that the fill colour of the social media icons is orange rather than teal. So need to find out how and where that magic happens. I will check out the FR file you mention.

**Comment by Vino-S** [comment]
Hi @AlOneill ,
There is a assests folder for Freecen here: https://github.com/FreeUKGen/MyopicVicar/blob/freecen_parsing/app/assets_freecen/styles/css/icons.data.svg.css

**Comment by AlOneill** [comment]
Thank you, Vino. I confess to being a little confused at this point about how the SCSS/CSS files all work together — I will need some thinking time and a chance to draw a diagram or several! (I thought I had understood the flow, but clearly not yet.)

**Comment by richpomfret** [comment]
Vino to rebuild/recompile as test2 is production (rather than development).

**Comment by AlOneill** [comment]
When checking out something else, realised we had forgotten the cookie notice. (This is about the colours — the other issues will still need addressing.)

Taking the notice as it is now, neither the white nor the yellow are accessible with the green. A darker green would work with white, or a lighter green with black.

![FreeCen__Search___and_links-search_html_—_FreeCen_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d68c46a54ff39c1679187227009c27798be83bf2517e001d0c16c3191c0218932b398fc9c07e25df2f5eb3be6f4d68d47d53f3e2d74cfb13b0328e4bd4bebdd948c5ed3523e7828f4f3c1e051d8bfd543ca98b57da1aa715b51208fd596321f47c247d409e1f702c6f6626abfeda55858667b6f7.png)

**Comment by AlOneill** [comment]
Or, we could use a dark neutral background colour which could work with white (and yellow, if wanted).

Or even a light neutral background — although it may not provide enough general contrast to the other page content.

![FreeCen__Search__.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d68c46a54ff39c1679653f6b14b1247a80e03cfd1839545b0e46ad125c5a41f4ff8922a6b63e708a5909efd8645666da2f53fde6d640e258f075c95d8fa4bd8346c1ed3d21e68b8f483d1d071e8fed10.png)

**Comment by PatReynolds** [comment]
Meeting decided dark green for cookie notice.

**Comment by PatReynolds** [comment]
@Vino-S can you advise on role of grunt icon?

**Comment by AlOneill** [comment]
@Vino-S I can see that grunticon decides which version of the icon CSS gets served with an HTML page, but can grunticon do more than this?

For example, line 146 of https://github.com/FreeUKGen/MyopicVicar/blob/freecen_parsing/app/assets/stylesheets/FreeUKGenealogy-Core-Frontend/styles/scss/base/_forms.scss refers to adjusting "grunticon widths", which suggest to me that grunticon could be involved in actually generating the CSS files in the first place.

Any insight? Thanks.

**Comment by AlOneill** [comment]
Aha! Have now found the *correct* Grunticon page on GitHub:
https://github.com/filamentgroup/grunticon

It can be used as either a command line tool or a browser app — Grumpicon. Feed one of them the SVG files , set a bunch of options, and it will produce all 3 CSS files, plus the necessary PNG image files.

Will do some local testing first, then reassess.

**Comment by AlOneill** [comment]
Decided against trying to figure out how to use Grunticon per se (at least for now!), but have gone with Grumpicon plus manual editing.

All icons needing editing are now done; PNG images are done; all 3 icon CSS files updated and tested locally.

NB: have not done anything towards updating "favicons" — these are a whole different kettle of fish!!

**Comment by richpomfret** [comment]
Alison to add new colour scheme for us to take a look at. To then schedule a meeting to review where we are and potential colours.

**Comment by benwbrum** [comment]
@AlOneill, have you tried doing the bower/grunt build on the repository created by the designers?

**Comment by benwbrum** [comment]
@AlOneill says 'no'.

**Comment by Captainkirkdawson** [comment]
New colours have been implemented
