### ISSUE TITLE
Chase N R Scotland (March)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#246]
Review correspondence on Scotland's images - what do we have permission to do?

**Comment by PatReynolds** [comment]
Also contact:
The Church of Scotland
Scottish Catholic Archives
"Several local authority archives and university archives in Scotland share the responsibility for looking after the records of Scotland's government, court and churches"

**Comment by PatReynolds** [comment]
@richpomfret to check Security Policy version 1.1 against requirements of NRS.

**Comment by richpomfret** [comment]
Currently reviewing the requirements but all good so far. Shall confirm.

**Comment by richpomfret** [comment]
Confirmed we are now covered. @PatReynolds please do proceed.

**Comment by PatReynolds** [comment]
Contacted 7 Feb.

**Comment by PatReynolds** [comment]
Contact said she would contact us mid-March.

**Comment by PatReynolds** [comment]
Anna Slater contacted mid-march, and again in April requesting more information. The Past-Present-Future document sent 27/7/2018.

**Comment by PatReynolds** [comment]
Follow up email 23/10/2018

**Comment by PatReynolds** [comment]
Chased 21/11/2018

**Comment by PatReynolds** [comment]
Find Ann moved to Acting Executive Director before my last letter, so wrote to the Business Unit (the address on their website for collaborations 4/12/2018

**Comment by PatReynolds** [comment]
Anne replied 18/12 and will get back to us in January.

**Comment by benwbrum** [comment]
Pat chased Ann in March and may have chased her in April.  @PatReynolds to update with most recent update.

**Comment by benwbrum** [comment]
It's May; Ann needs chasing again.

**Comment by PatReynolds** [comment]
Now have new contact - Gerry D. and discussing date for phone call.

**Comment by richpomfret** [comment]
@PatReynolds to create new task for next steps.
