### ISSUE TITLE
Create anchors and 'jump to' on the database coverage page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#254]
As this page (https://www.freecen.org.uk/freecen_coverage) is now getting long (with adverts), I think it would be helpful if people could jump to the decade they are interested in.

Preceded by 'Jump to', Tags are needed for 1841, 1851, 1861, 1871, 1881, 1891 and Totals.  They should be positioned just above the heading '1841'

E1, U 3, S10, C7: P21

**Comment by richpomfret** [comment]
Moved to Israel to see if this is something he might have time to do.

**Comment by mattkse** [comment]
Can you be more specific about what you mean by "database coverage page" and how one navigates to it?

**Comment by Captainkirkdawson** [comment]
This will be dealt with in the redesign of the Records pages

**Comment by PatReynolds** [comment]
I believe this has been dealt with (excellently!) in the redesign
