### ISSUE TITLE
review record count differences FC1 vs FC2

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#257]
Brenda has found several cases of differences in the record counts reported in FC1 vs FC2 database contents.  We need to determine the cause of the differences and whether there is an error in FC2 loading records, reporting records, or otherwise.

Best for Vino to do this (under my guidance) so she can become familiar with these parts of the system and also with the corresponding freecen1 code that she will need to refer back to when troubleshooting the differences.

E1, U6, S8, C5: P20

**Comment by richpomfret** [comment]
Brenda to check this against the spreadsheet in order to look for any differences - Vino to also check.

**Comment by richpomfret** [comment]
Still a big gap in numbers - currently being explored. Vino/Doug to assist.

**Comment by dougkdev** [comment]
need to generate reports for Brenda to narrow down which pieces have discrepancies. Created story #284 for those reports.

**Comment by benwbrum** [comment]
We have determined that FreeCEN1 and FreeCEN2 count uninhabited records differently.

When a VLD line (representing a census form entry) is parsed in FreeCEN1, we're counting the line as a record, whether the line represents an individual or an uninhabited dwelling.

When VLD files are processed by FreeCEN2, we create a `dwelling` entry for each dwelling and an `individual` entry for each individual, then a `search_record` entry for each individual.  

FreeCEN2 reports the number of "records" by counting `search_record` entries, so it misses uninhabited dwellings.  I suggest we change that display of record counts on FreeCEN2 to be more explicit: "234578 Dwellings and 2345679 Individuals", getting rid of the ambiguous "records" wording.

**Comment by Vino-S** [comment]
@benwbrum  had suggested to ammend Params file for 1841 Census for NTT for FreeCEN2.
We have 2 errors in FC2 which needs fixing.  
If we fix this, it will bring the records of HO108749 in next FC2 update and will be able fix the count difference.
Working on it currently.

**Comment by richpomfret** [comment]
Is this still a valid task considering Ben's above comment relating to how we count things differently btween FreeCen1 and 2?

**Comment by FreecenBren** [comment]
This is nothing to do with the counting.
It is an error in a PARMS file for NTT 1841.
I have sent them a corrected PARMS file
