### ISSUE TITLE
Look at refinining adverts

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#258]
Can we force 1 advert per slot?
Should we reduce to maximum 2 slots per page?
At least on mobiles?

requires #538
requires #391
requires #456

Cost total 19 - so small? 
E8 U6 S7 C9: P30

**Comment by richpomfret** [comment]
@PatReynolds we also need to be looking at advert content - as there appears to be no variety and I wonder if this is related to our settings.

**Comment by PatReynolds** [comment]
Include trialling matched content.

**Comment by PatReynolds** [comment]
As this issue has multiple stories, I have reclassified as an Epic, and am ensuring all the stories mentioned exist.
