### ISSUE TITLE
Household screen shows Place name

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#27]

**Comment by sean-wood** [comment]
Ben can you size this ticket please

**Comment by benwbrum** [comment]
It's completed -- does it still need sizing?

**Comment by sean-wood** [comment]
If you don’t mind . It will help with my forecasting

Kind Regards


Sean Wood
Director and Principal Consultant
Sands View I.T. Consulting Ltd.

E: swood@sandsviewitconsulting.co.uk<mailto:swood@sandsviewitconsulting.co.uk>
T: +44 (0) 7771 824 315
W: www.sandsviewitconsulting.co.uk<http://www.sandsviewitconsulting.co.uk/>
