### ISSUE TITLE
review fc2 site usage patterns

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#271]
In order to decide on sharding strategy and shard key (#260) need to know how users are actually using the new system to choose shard key based on typical usage patterns instead of just a guess at what the patterns will be.  Of particular interest is whether most searches are done by specific census years or by "all years" as all years was not even an option in FC1.

Needs #504

E1 U6 S8 C6: P21

**Comment by Captainkirkdawson** [comment]
Search stats are available
