### ISSUE TITLE
Channel Island census searches on island need removing

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#273]
Currently the names of individual islands (e.g. Jersey) appear in the 'County' table, but searching using these fails to find anything.  If 'Channel Islands' is selected, then the individual islands appear in the 'Place' table, and can be selected.  Remove individual islands from the county list to prevent searches being made from that list.

**Comment by PatReynolds** [comment]
NB, no records for Sark? Possibly with Alderney? Brenda to check

**Comment by PatReynolds** [comment]
Pat to check for Sark

**Comment by dougkdev** [comment]
removed the individual islands from the census county list on test2

**Comment by dougkdev** [comment]
also on production

**Comment by PatReynolds** [comment]
I've now  run some experimental searches, with the conclusion that: for place of Birth search for Sark, FC2 is better than FC1 (i.e. you can do it).
For enumeration place, the structure is Channel Islands (county) > Guernsey (place) > Sark (civil parish).  Sark is often treated as a dependency of Guernsey, but is in fact an independent country (with its own UN code) so people might reasonably expect to see Sark in a listing 'one down' from the Channel Islands.  
I think this issue can now be closed, but I will open a new one about enhancing searches on  place of enumeration.
