### ISSUE TITLE
Cookie audit and Review cookie policy

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#275]
Check that cookie policy is up to date (schedule repeat of this for review as part of future work that might necessitate a change.

**Comment by PatReynolds** [comment]
Brenda keeps being asked to re-accept the policy

**Comment by richpomfret** [comment]
Cookie policy appears just fine and up to date. However, may need to check on any possible bugs with it if anyone is being asked to re-accept it - although I think i've seen this on test2/3..

**Comment by richpomfret** [comment]
To check Barrie's comments and ensure we are consistent across sites.

**Comment by richpomfret** [comment]
A pass has now been completed, therefore closing this. Separate stories are being created to cover the specific tasks for this.
