### ISSUE TITLE
Add feedback survey to FC2

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#276]
Sent to Vino 10/7

**Comment by AlOneill** [comment]
Vino has the code in place for this on test2 (search page). What remains is to tweak the styling of the message/appeal for best effect in this context.

There are a few issues to be considered:
* centred text is hard for some to read comfortably, especially when it extends over more than one line — finding the beginning of the next line becomes a problem.
* lines of text that are very wide are harder to read because the eyes have to track the line for longer.
* there are a lot of boxes with grey borders on this page.
* the message needs to catch the eye of a user without inducing annoyance.

Some ideas for your consideration to follow ...

**Comment by AlOneill** [comment]
@PatReynolds @DeniseColbert @FreecenBren @richpomfret 
For all these options, the width of the message box is constrained to a comfortable reading width and the text is left-aligned. The box is centred on the page to align with the page heading. The "navy" colouring would work with both the current and the proposed new colours (but other colours can be considered, if wished).

**Option 1**

![FreeCen__Search_and_search_message_html_—_FreeCen_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d68c46a54ff39c164729771617a62a6286eb17b24768120e081bc3191c0218932b398fc9c07e25df2f5eb3be6f4d68d47d53f3e2d74cfb13b0328e4bd4bebdd948c5ed3523e7828f4f3c1e051d8bfd543ca98b57da1aa715b51208fd596321f47c247f469e1f702c6b6723a2f9d850868d66b6f7.png)

**Option 2**

![FreeCen__Search_and_search_message_html_—_FreeCen_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d68c46a54ff39c164729771617a62a6286eb17b24768120e081bc3191c0218932b398fc9c07e25df2f5eb3be6f4d68d47d53f3e2d74cfb13b0328e4bd4bebdd948c5ed3523e7828f4f3c1e051d8bfd543ca98b57da1aa715b51208fd596321f47c247e419e1f702c6b6723a2f4de53848465b6f7.png)

**Option 3**
This banner styling (where the whole box is a link) would only be workable with the new colours as currently the hover styling is subtle and there is *no* focus* styling.

![FreeCen__Search_and_search_message_html_—_FreeCen_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d68c46a54ff39c164729771617a62a6286eb17b24768120e081bc3191c0218932b398fc9c07e25df2f5eb3be6f4d68d47d53f3e2d74cfb13b0328e4bd4bebdd948c5ed3523e7828f4f3c1e051d8bfd543ca98b57da1aa715b51208fd596321f47c247e419e1f702c6b6720abfddb568f8565b6f7.png)

Option 4 ?? ...

**What do the team think?**

**Comment by DeniseColbert** [comment]
Option 3 has my nod.

**Comment by PatReynolds** [comment]
Thank you.
Visually, I like 3 best, then 2, then 1.  Could the 'we welcome your feedback' be underlined (i.e. be a pseudo-link)? 
Not sure if navy is the right colour to work with purple, but definitely prefer a solid block.

**Comment by AlOneill** [comment]
Here are two versions of option 3 for your consideration, both with the proposed new navigation colours. They also incorporate styling to make the key part of the link look more like a link, as Pat suggested. (NB there is currently *no* visual indication of hover or focus for the grey styling; the navy background colour changes a bit on hover, but there is *no* change on focus.)

**Option 3a**

![FreeCen__Search__.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d68c46a54ff39c1679653f6b14b1247a80e03cfd1839545b0e46ad125c5a41f4ff8922a6b63e708a5909efd8645666da2f53fde6d640e258f075c95d8fa4be8c46c1ed3d25e38a8e4e391c001e8bed10.png)

**Option 3b**

![FreeCen__Search__.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d68c46a54ff39c1679653f6b14b1247a80e03cfd1839545b0e46ad125c5a41f4ff8922a6b63e708a5909efd8645666da2f53fde6d640e258f075c95d8fa4be8c46c1ed3d25e38b86463817001d8fed10.png)

**Comment by PatReynolds** [comment]
Slight preference for 3a, but both look good. Thanks!

**Comment by DeniseColbert** [comment]
I like 3a also. Where will we stand on accessibility without the change on focus?

**Comment by PatReynolds** [comment]
This appears to be finished.  Anything more to do @DeniseColbert @AlOneill ?

**Comment by DeniseColbert** [comment]
I believe it is done, yes. Maybe a story about what we'll do with the feedback?
