### ISSUE TITLE
Content of Physical Location field

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#278]
Import from FreeREG "Physical location "Just a country will do""

Do we want to use this for 'full address, if telephone number not given, otherwise just a Country will do'?

**Comment by PatReynolds** [comment]
Pat to check page, and  suggest text.

**Comment by PatReynolds** [comment]
@Vino-S can you point me at the page where a volunteer is able to change their contact details?

**Comment by Vino-S** [comment]
Hi @PatReynolds ,
All transcribers have access to Profile Action. A transcriber can update their contact details like Email, Location and Telephone using EDIT action in Profile.

**Comment by PatReynolds** [comment]
@Patreynolds to see what the wording is in Profile Action, and consult on changes needed.  @Vino-S to make any change needed in errbit.

**Comment by PatReynolds** [comment]
I cannot see 'profile action' in my actions.  If I go to 'manage ID' and then 'edit' I can edit my own ID.  @Vino-S Is this what everyone can do?
Current wording:
Just a country will do
Suggested alternative:
Full address, if telephone number not given, otherwise just a Country will do.

**Comment by richpomfret** [comment]
Pat to create new story with regard to adding in profile 'action' for every user type.

**Comment by Vino-S** [comment]
Changed the wording of Physical Location to "Full address, if telephone number not given, otherwise just a Country will do." as @PatReynolds  suggested. 

Updated in Live website
