### ISSUE TITLE
Remove Fiche reader recording (was Enable recording of volunteer transcription skill (was other fields needed)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#279]
1/ Take decision on whether it is useful to know who has a fiche reader

2/ Find where data on fiche readers is input (at signup?). Delete or continue, depending on decision above

3/ Find if fiche reader data is still held, and if so where, and 
3b/ Delete ore retain, depending on decision above.

Previous description:
FreeREG has two more fields - do we want either?  Or anything additional:
*Transcription skill level
All options: Learning, Straight-forward forms, complicated forms, Post 1700 modern freehand, Post 1530 freehand-Secretary, Post 1530 freehand-Latin, Post 1530 freehand-Latin&Chancery

Has a Fiche Reader?

**Comment by PatReynolds** [comment]
To be decided as part of Transcription phase

**Comment by PatReynolds** [comment]
Recording transcription level already there (29/11/2017), also fiche reader there.  Story is therefore changed to 'remove fiche reader recording'

**Comment by PatReynolds** [comment]
Hi priority because it needs prioritization and moving to backlog.

**Comment by PatReynoldsFUG** [comment]
Fiche reader is no longer mentioned in handbook (12 June 2024).

**Comment by Vino-S** [comment]
Is this still needed given Helen's role?

**Comment by DeniseColbert** [comment]
Closing
