### ISSUE TITLE
Household screen shows next/previous household

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#28]
This should navigate from one household to the next within the census page, not the search results

**Comment by FreecenBren** [comment]
This should be backwards and forwards between households

**Comment by dougkdev** [comment]
Brenda:
From your explanation in story #42, I assume that the order of
transcription is always the same as the order of the written entries in the
piece?  So if we just use the dwelling_number to decide which is the
previous/next dwelling, that is the desired order for previous/next
dwelling, correct?

**Comment by FreecenBren** [comment]
Sean you are correct.

I assume that is how it works now in FreeCEN 1.



The difference is the researcher does not need to see that  DWELLING number as it confuses the issue.

It also takes up valuable space on the display.

 

Brenda
