### ISSUE TITLE
Activate Transcription Agreement Sign up (existing  active transcribers)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#280]
Pat to write to existing transcribers and invite to sign up (dependent on #220)

**Comment by PatReynolds** [comment]
Needs to only have the option of signing up (i.e. not options to decline or not declare (at this moment in time).

**Comment by Vino-S** [comment]
Updated the code in test3

**Comment by PatReynolds** [comment]
@richpomfret please add link to forum

**Comment by richpomfret** [comment]
Q&A group is here - https://groups.google.com/a/freeukgenealogy.org.uk/forum/?hl=en#!forum/transcription-agreenment--open-data

**Comment by richpomfret** [comment]
@Vino-S Please ensure the link to the group is given to the user as part of the sign-up text for existing transcribers (as it is for new). Probably done already but thought i'd check. ;)
