### ISSUE TITLE
disable RefineryCMS member action for coords

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#281]
Brenda ran into an issue when she was inadvertently given the role of "syndicate_coordinator" where the RefineryCMS action was taking her to edit county pages.  Unless county pages are planned for CEN, we need to disable  this action in the userid_role.rb for freecen syndicate and county coords to prevent confusion.

**Comment by PatReynolds** [comment]
Yes, county pages are wanted (currently "status page"). County Coord needs, Syndicate Coord doesn't need.  At the moment they do this on independent websites.

**Comment by dougkdev** [comment]
Unable to reproduce the problem without directly typing in the URL for the /cms/refinery/county_pages . The RefineryCMS member action is not presented to syndicate coords, so perhaps when the action did not appear, maybe typing refinery into the browser URL navigation field resulted in it auto-completing to that previously-visited URL?  Hard to know without more info. I do not think there is anything left to be done here unless someone has a similar issue in the future. Recommend we close this.

**Comment by PatReynolds** [comment]
Yes, to close.
