### ISSUE TITLE
multi-county search with YKS does not include all of YKS

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#282]
while investigating #237, I saw that there is also a bug in the logic for YKS if the user selects multiple counties (the user is allowed to select up to 3). I'll fix this bug along with #237 since it is in the same area of the code.

**Comment by dougkdev** [comment]
fix on test2

**Comment by dougkdev** [comment]
deployed to production, ready for user test

**Comment by PatReynolds** [comment]
Tested: Alcock, no forename, 1700 - 1800, Yorkshire - generated error "1 error prohibited this search from being processed:

A forename and surname must be present to perform an all counties search."

**Comment by PatReynolds** [comment]
Multi-county search (test Bucks, Worcs and Yorkshire) works on place of birth and on census place.
