### ISSUE TITLE
Add Coords to New Transcriber Signup

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#285]
Add Counties/years which are suitable

**Comment by PatReynolds** [comment]
Brenda has listed and sent spreadsheets to coords.  Pat to send to Vino when checked

**Comment by PatReynolds** [comment]
@Vino-S I think I sent you the list of coords - please let me know if you still need them.

**Comment by Vino-S** [comment]
Hi Pat,
I have updated the list of coords in test2. Please have a look. I will update in live website after I have your feedback

**Comment by PatReynolds** [comment]
Yes, this all looks good to me!  Please update in Live website.
