### ISSUE TITLE
Houshold screen columns

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#29]
These should be displayed for individuals on the household screen (note that items 1-6  may need special handling, as I suspect that they apply to all individuals within a houshold.)

1.   Civil Parish
2.   ED
3.   Folio
4.   Page No
5.   Schd No
6.   House No Address
7.   Surname
8.   Forenames
9.   Relationship
10.                Condition
11.                Sex
12.                Age
13.                Occupation
14.                Occupation status
15.                CHP  (Chapman Code)
16.                Place of birth
17.                Disability
18.                Language spoken
19.                Notes/Remarks etc

**Comment by PatReynolds** [comment]
Special handling in terms of data, display or both?

**Comment by FreecenBren** [comment]
Yes numbers 1 - 6 are per Dwelling.

1. Civil Parish
2. ED
3. Folio
4. Page No
5. Schd No
6. House No Address

 

Not sure if Household is really the best way to describe it though.

We refer to them as Dwellings as they include

Houses,
Boarding Schools not covered by "Institutions & Shipping"
Hotels and boarding houses etc.,

And then we have the "Institutions & Shipping" as follows.
These do not have ‘Schedule numbers’ except the first occupant who is given the schedule number 0 (zero)

Hospitals, Barracks & Military Quarters 
HM Ships, at Home 
Workhouses & Pauper Schools 
Hospitals (Sick, Convalescent, Incurables) 
Lunatic Asylums 
Prisons 
Certified Reformatory & Industrial Schools 
Merchant Vessels & Lighthouses 



Brenda

**Comment by dougkdev** [comment]
Do we want the per-dwelling fields (1-6) redundantly listed on each
individual, or do we want them in a separate section at the top of the
household page?

**Comment by FreecenBren** [comment]
This is how it is currently shown at the top of each dwelling

It works OK so I think keep it that way

 

Piece: RG12/2663 Place: Basford -Nottinghamshire Enumeration District: 1
Civil Parish: Heanor Ecclesiastical Parish: St Lawrence
Folio: 4 Page: 4 Schedule: 20
Address: Derby Road
