### ISSUE TITLE
set up test2 and test3

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#298]
Test2 production
Test3 development (sorry this may be the wrong way round - issue failed to load yesterday

**Comment by richpomfret** [comment]
To mirror the set-up on FreeREG. @lemon-ukgen I wonder if we might follow a similiar set-up for FreeBMD when we update the test/dev facilities? Although of course for the latter we need sandbox environments and not sure this covers it.

**Comment by lemon-ukgen** [comment]
* https://test2.freecen.org.uk - exists, running in production
* https://test3.freecen.org.uk - I'll set this up, and configure Passenger to run it in development

This is the other way around from FreeREG2. We can switch them if that's a concern.

**Comment by lemon-ukgen** [comment]
Now done. I just cloned `~apache/hosts/freecen/production` (test2) into `~apache/hosts/freecen/development` (test3) so it will have all the same database setup etc. The developers may want to change that.

Both sites are currently errorring 'We're sorry, but something went wrong...' as I found them.
