### ISSUE TITLE
FreeCEN instead of FreeCen used consistently on site

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#300]

**Comment by dougkdev** [comment]
see Pat's response in #125 that FreeCEN not FreeCen should be used (except for the logo). There are several other places on the site that are inconsistent.

**Comment by AlOneill** [comment]
Have updated all (AFAIK!) Refinery pages as per.

**Comment by dougkdev** [comment]
Great! I'll update the places in the code.

**Comment by dougkdev** [comment]
code updated and deployed to test2

**Comment by dougkdev** [comment]
code also deployed to production.  @AlOneill , did you make the changes on test2 or on production or both?  (Just wondering if I need to copy refinery content from one server to the other or if they are both in sync with each other).  Thanks

**Comment by AlOneill** [comment]
@dougkdev  Apologies for delay — did not get message.

I made changes on *production only*: https://freecen2.freecen.org.uk/
