### ISSUE TITLE
Test User Experience for new Volunteer sign-up

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#304]
It apears as though new volunteers are having trouble knowing what to do next after sign-up. For us to test and assess how we might improve the user experience and provide better sign-posts.

**Comment by richpomfret** [comment]
There is no clear 'next step' for a user once they have signed up - they are taken to a blank screen with no 'what to do next' message. We need a blurb here and an automated welcome email.

**Comment by PatReynolds** [comment]
Suggestion sent to @FreecenBren 23/8/2017

**Comment by PatReynolds** [comment]
Text to add: "Welcome to FreeCEN!  Your support is very much appreciated.  Brenda Bowers, our Chair will be emailing you soon with details of how to start.  If you don't get this email, please check your spam.  You can always contact her at bowbren2@gmail.com."

**Comment by PatReynolds** [comment]
Do they get an email asking them to choose their password?

**Comment by Vino-S** [comment]
We send an email which has link to set their password after they complete their initial registration

**Comment by FreecenBren** [comment]
After the registration that is where they do not know what is next.
Does not explain what they have exactly registered for!

Do they get added on to receive newsletters updates etc?
