### ISSUE TITLE
FC2 Feedback: Occupation search facility

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#317]
This is to re-enable the basic search by occupation, available on FC1.

I.e. typing in the search field returns matching records.

Two possible future enhancements:
a) wildcard permissable (e.g. Ag*Lab* returns Ag.Lab., Ag. Lab., Ag. Labourer, etc.  and *smith returns Blacksmith, Goldsmith, Silversmith, Smith, Tinsmith, Whitesmith, etc.).
b) searching uses a reference table to search for synonyms.  One such table is the ONS' Standard Industrial Classification: SIC 2007, the Social History and Industrial Classification, and/or the data classifications used in the census reports.

**Comment by Captainkirkdawson** [comment]
Need to know what is in the field before even making an estimate of the task

**Comment by Captainkirkdawson** [comment]
Well that blew me away the investigation of the content shows.

1841  67,501
1851 232,840
1861 553,696
1871 352,915
1881  36,961
1891 435,585
Total 1,445,529

A SAMPLE is at https://drive.google.com/drive/u/1/folders/0BykgQKwJtk6faHhUWnRsWklNWWc The original files are too big for sharing 35MB.

Cen1 has a test entry box for the selection of occupation. I can only speculate as to how it worked. Likely created a regex and matched content with the field. It could have been implemented at the start of perhaps any part of the field's content

How to proceed??

**Comment by PatReynolds** [comment]
@Captainkirkdawson to see what the performance looks like, before making a decision whether to begin implementation now, or at a later date (solution is a regex).

**Comment by Captainkirkdawson** [comment]
Code available for evaluation on test3 CEN.

**Comment by PatReynolds** [comment]
Testing for Alcock, Farmer, census in Yorkshire, worked fast and fine.
However,
Testing for Alcock, Butcher, born 1800 to 1805, no results to 1810, no results, to 1815, no results, to 1817 too many results.  to 1816, no results.  Just 1817, no results.

Timing wise, seems fine - very quickly either completing search, or announcing that there are too many results.

**Comment by Captainkirkdawson** [comment]
What you are seeing is an interplay between the way the search is conducted and the maximum number of results we process.
As indicated at the very outset when we discussed these additional search criteria. They act as filters on the results of a person search. 
In other words the basic person search must produce less than 500 results BEFORE it attempts to filter those results to see if they satisfy the additional criteria. 
An example; search for SMITH. You MUST first generate a person search that results in a set of 500 SMITHS before we apply the filter. The likelihood that such a set has a restricted occupation is small hence  you get no results.
We are NOT searching the database for a person that meets ALL the criteria and then displaying the result of such a search. Why? Because we are searching a search record collection that DOES NOT include the additional fields.

**Comment by Captainkirkdawson** [comment]
An example of how to proceed. Step 1 conduct a search WITHOUT additional criteria that produces less than
500 results. Then add additional criteria to filter those results.
eg ALCOCK in the Yorkshire census produces 373 results.
Now you can explore those people for the additional criteria. eg 135 were married. 28 were widowed. 
Of the total 30 had far in the occupation field (it is best to apply a small part of the occ this allows for contractions or mistakes in the census eg only 21 had farmer. Add a Male filter to farmer and we are down to 16 Male Farmers.
Go back to the basic search that gives us 373 results and add bu as an occupation and we are down to 1 and she was a Burler (whatever that is) there were no ALCOCKs in Yorkshire who were associated with butchery!
Back to the original 373 and we see that 29 were male lab and that there were 16 single male lab
So the feature is powerful if used in the correct way.

**Comment by PatReynolds** [comment]
Pat to write text for search box to make it clear that the Christmas Gifts are done to the records found on the basic search (including soundex) has found.  S

**Comment by PatReynolds** [comment]
Current: These filters are applied to the results produced by the above search criteria. Please read the Help carefully BEFORE using the filters as their effectiveness varies according to the year of the census.

Suggest.  To use one or more of the filters below: first run the search (press the search button at the bottom.).  Thn press the 'Revise Search' button at the top of the results page, scroll back down to here, and refine your search by one or more of the filters below.  Adding the filters before first doing the search will not provide a result.

Add later 'click here to see a video of this in action'.

**Comment by Captainkirkdawson** [comment]
Deployed
