### ISSUE TITLE
FC2 Feedback: an ad coming up over the working area of the site

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#326]
From Brenda: On iPad, page jumps when pop-up / ad is loading, ad is in front of screen

**Comment by richpomfret** [comment]
To test on Live.

**Comment by richpomfret** [comment]
Will try testing this on tablet.

**Comment by richpomfret** [comment]
Borrowed an ipad so shall finally get a chance to test tonight! HURRAH! ;)

**Comment by richpomfret** [comment]
Seems fine - cannot duplicate.
