### ISSUE TITLE
FC2 Feedback: 'Detail' link not sufficiently clear

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#329]
Users are missing the link and are not aware that there is more information for them to see

**Comment by DeniseColbert** [comment]
Many comments point to users missing the 'Detail' link

**Comment by PatReynolds** [comment]
Place left?
Use button rather than text link.
Text for screen readers = 'Details line 11' (et.)
Button says 'Show dwelling details' (or something like that) maybe text under button 'click to  see all the details of this person and others in the same place' (or something)

**Comment by DeniseColbert** [comment]
I think this has been done?

![image](https://user-images.githubusercontent.com/19173257/39212624-2617246a-4807-11e8-97eb-a9ba6655c0d6.png)

**Comment by AlOneill** [comment]
Note that page is not fully accessible — the tooltip information and the title attribute on the detail button will not be seen by those who can't use a pointing device.

For all users, there is no explanation of what clicking on a column heading would achieve.

**Comment by PatReynolds** [comment]
Completed, so closing.
