### ISSUE TITLE
FC2 Feedback: Inform users that choosing a Census Place can restrict results

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#330]

**Comment by richpomfret** [comment]
Should be simple, just need to establish what text to use.

E0 U3 S5 C8:P16

**Comment by PatReynolds** [comment]
I think other parts of this section of Help may need a re-write in view of the developments over the last few years.

I have (possibly!) addressed this story in this draft: https://docs.google.com/document/d/1X6qUXROl7QVqyoxntx3tiE21StNVnPtJ72QmsVn2EuA/edit?usp=sharing  Other work is probably needed.

**Comment by AlOneill** [comment]
@PatReynolds Hmm. The version that you are wanting to update is Kirk's update of only a few months ago! It has never quite made sense to me. When I tried to clarify the meaning, I was stone-walled.

**Comment by DeniseColbert** [comment]
@geoffj-FUG to take a look and see if it makes sense

**Comment by geoffj-FUG** [comment]
I have added a couple of notes about using control to select multiple counties and using the search around box. Both of these need addressing.

**Comment by PatReynoldsFUG** [comment]
Made changes to address your points, I hope, @geoffj-FUG

**Comment by geoffj-FUG** [comment]
All links work OK.
There is an indent problem at Abbreviated Handbook.
Otherwise OK.
This can be deployed once the indent is fixed.
Geoff

**Comment by DeniseColbert** [comment]
@AlOneill to bring text over from Google Doc to Refinery

**Comment by AlOneill** [comment]
Have begun updating (Researcher) Help as per https://docs.google.com/document/d/1X6qUXROl7QVqyoxntx3tiE21StNVnPtJ72QmsVn2EuA/edit#heading=h.9a7qe19milli

**Comment by AlOneill** [comment]
@PatReynoldsFUG 
Now that I'm making the changes to the Help page, a couple of things are not quite clear to me.

I've made two further comments on the Google doc plus a Suggested edit. I know you are away for now, but please take a look when you return and have the opportunity. Thanks!

**Comment by DeniseColbert** [comment]
To discuss in documentation meeting

**Comment by AlOneill** [comment]
[DRAFT Help](https://test3.freecen.org.uk/cms/draft-help) updated as per this document: https://docs.google.com/document/d/1X6qUXROl7QVqyoxntx3tiE21StNVnPtJ72QmsVn2EuA/edit#heading=h.9a7qe19milli

I'm not sure that the section from the missing image onwards is as intended.

I could not upload an image (as per the document) into Refinery — see issue #1477

**Comment by DeniseColbert** [comment]
@geoffj-FUG is this OK?

**Comment by geoffj-FUG** [comment]
Denise, Looks Ok to me bar the capitalisation of County.
Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG @DeniseColbert 
All instances of County and Counties now begin with a capital letter, even where this breaks the traditional rules of (English) English grammar. If this is not what is required, then please clarify. Thanks.

**Comment by geoffj-FUG** [comment]
Alison

The document I was looking at had a lower case C for some entries of County.

Geoff

**Comment by AlOneill** [comment]
@geoffj-FUG 
Communication failure! Traditional English rules are that 'county' has an initial capital letter _only_ where referring to a specific county — this is the same for other similar nouns such as 'country', 'state' or 'judge', for instance. When referring to a county in general — the concept of a county if you will — then lower case is appropriate.

I have broken these rules in attempting to comply with your requirements. If I have misinterpreted your requirements, then do say so, giving me more specific instructions. In particular, do you want 'Counties'  to be rendered as 'Counties' or as 'counties'? Thank you.

**Comment by DeniseColbert** [comment]
Can we Title Case FreeCEN-specific roles and fields? E.g. the Chapman code field, Proofreader, Transcriber etc.

**Comment by AlOneill** [comment]
@DeniseColbert Just to be clear — is your comment a request to do so or a point for discussion?

**Comment by geoffj-FUG** [comment]
I have changed the instances of County in the Handbook Part 1 (prepared for the end of vld uploads on 31 March) to county unless they were a proper name (e.g. County Clare).
Geoff

**Comment by DeniseColbert** [comment]
To discuss @AlOneill I think, as Geoff has changed/is changing County/county

**Comment by AlOneill** [comment]
Oh my. We urgently need clarification of our policy here.

**Comment by DeniseColbert** [comment]
Let's talk about it at Documentation later; it's very possible I'm not understanding what's going on!

**Comment by AlOneill** [comment]
@DeniseColbert 
As discussed in our Documentation meeting, I have made the casing of all instances of county and counties on this page to be all lowercase (at least until our casing policy is firmed up).

Is this draft now ready to be promoted to 'live'? If so, let me know and I will do so. Thank you. 

BTW I note that there are a number of other terms where the initial letter is a capital, including Place and Census (without a year) that will need to be considered when the policy is drawn up.

**Comment by DeniseColbert** [comment]
Have a temporary decision for future review of policy

**Comment by AlOneill** [comment]
Draft page sync-ready and published on t3.

**Comment by DeniseColbert** [comment]
Vino to do a sync

**Comment by DeniseColbert** [comment]
Done: closing
