### ISSUE TITLE
FC2 Feedback: Birth County keeps defaulting to All Counties which prohibits a Surname only Search on Ipad.

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#338]
Brenda tested this and it appears the Revise Search function isn't working on PC or iPad

**Comment by PatReynolds** [comment]
This story doesn't seem to be about the revise Search function. Searching by surname alone, all birth dates, all census years, all birth counties, all census counties works both as initial search an revised search on my android phone. Is the story that it doesn't on iPads? Other (only?) Story is that  revising a search (on iPad) resets county (birth? Census?) To all counties.  Please could you split stories or clarify if just one.

**Comment by PatReynolds** [comment]
Duh! Says birth county!

**Comment by richpomfret** [comment]
Can anyone replicate?

**Comment by richpomfret** [comment]
Closing as now appears fixed. Although I do have an ipad (borrowed!) so will do some general testing for any such UX issues.
