### ISSUE TITLE
Drop down of pre-entered text isn't working on iPad (Brenda)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#339]

**Comment by richpomfret** [comment]
Let's test this more across a few devices (tablet/mobile)

**Comment by mattkse** [comment]
I cannot reproduce this.  Can you be more specific about where this happens?

**Comment by smrr723** [comment]
I don't think there's an actual dropdown anywhere on FreeCEN?  I can't see one, so I suspect this is autofill form data that the browser saves and pre-populates - making this a browser issue. Can you confirm @Vino-S ?
