### ISSUE TITLE
FC2 Feedback: I can't see the details column when using on my tablet, it won't give me landscape view

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#349]

**Comment by richpomfret** [comment]
Ready for testing on test2

**Comment by richpomfret** [comment]
To test on more devices to see where this might be a problem i.e. different tablet sizes.

**Comment by DeniseColbert** [comment]
![20171111_003534](https://user-images.githubusercontent.com/19173257/32719119-28ce7800-c857-11e7-9524-406c65511591.jpg)
![20171111_003544](https://user-images.githubusercontent.com/19173257/32719120-28e3903c-c857-11e7-8ba4-7e3662f40677.jpg)

**Comment by DeniseColbert** [comment]
These are the results on a 7" tablet, looks solved to me
