### ISSUE TITLE
Find by maiden name (Scotland)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#353]
Scottish women were (maybe still are) legally known by their maiden name, so the census would record both married surname and maiden surname.  This data is recorded in the format MARRIED / MAIDEN in the name field.  FreeCEN1 found the / MAIDEN component (but there was no 'search by maiden name option').

**Comment by Captainkirkdawson** [comment]
I stick by my position that fields should have one purpose only.  

I believe we should create a separate field.

We should plan for it to be populated in the future. If and when we enter Scottish pieces again

 The instructions for Scotland say Scotland occasionally shows two surnames for a wife.  These should both be entered separated by a space, /, space.

That instruction is badly formatted with 2 interpretations surname ,/, surname or surname / surname

Regardless I do not know how the search is  dealing with such an entry (likely badly)

Assuming we add then the search would need to be modified.

But step 1 is to write a story

Step 2 is to add the field at this point

The we proceed with investigation of the search and search record from a pst perspective and then move on.

**Comment by Captainkirkdawson** [comment]
I have confirmed that CEN2 correctly handles the Scottish surname pairing NAME / NAME2 with the record being retrieved with searches on NAME and NAME2
Actually the split is a more general split based on 1 or more spaces; there can therefore be multiple surnames. A surname of a single character are ignored as well as certain stop words
'da', 'de', 'del', 'della', 'der', 'des', 'di', 'du', 'la', 'le', 'mc', 'mac', 'of', 'or', 'van', 'von'

**Comment by Captainkirkdawson** [comment]
Given that the Maiden name pairing works there is no priority on addressing this correctly.with its own field

**Comment by AlOneill** [comment]
@Captainkirkdawson It is tricky to describe succinctly the way of entering a woman's married and maiden surnames in such a way that it will be correctly interpreted by all readers (irrespective of how they understand prose works!). Alternatives tend to become rather clunky — but perhaps the addition of a few words would be better (see below)?

For now, I believe the example given clears up any ambiguity. This is the current paragraph:

* Sometimes, the Scottish census will record two surnames for a wife. Enter both of the names, separated by a space, /, space, as in “murray / smith”. Where it is clear, enter the married surname first.

Would this be better?

* Sometimes, the Scottish census will record two surnames for a wife. Enter both of the names, separated by a space, followed by a /, followed by a space, as in “murray / smith”. Where it is clear, enter the married surname first.

**Comment by Captainkirkdawson** [comment]
@AlOneill yes that is better.

As I noted the / is not required for the search to create the separate surnames. At the same time in the surname print out it will be there and indicative of a Scottish maiden name
WILSON SMITH could be a multi generational surname with neither WILSON nor SMITH as maiden names. Oh well

**Comment by AlOneill** [comment]
@Captainkirkdawson From memory of transcribing records that have both a woman's married-surname and maiden-surname, it is obvious what is going on (I seem to remember that the Enumerator would use a / themselves). 

Further, such records tend to be found only in some regions of Scotland and may even be down to the particular Enumerator. So yes, a double surname entered *without* a / should *not* be assumed to be an example of a married- and maiden-surname, without knowledge of the context.

**Comment by AlOneill** [comment]
Test3 updated with amended text as per above. Page ready to be deployed.

**Comment by rhodamackenzie** [comment]
@geoffj-FUG @PatReynolds 

There is also the issue of teenames for Scotland, where (for men and women). Also known as to-names and tae-names in other areas, depending on the dialect. These social nicknames were used very extensively in north east Scotland fishing towns and villages, often carried down through the generations, to distinguish between different lines with the same surname. My grandad for example, John Cowie, of Buckie, Banffshire, was one of hundreds of John Cowies. His teename was Dougal and he was known as Johnny Dougal right up to his death in the 1970s. It was very common for people to be enumerated with their teename, men and women. This also applied to BMD records. Just for fun, sometimes the teename WAS the wife's maiden name! Eg my GGF, Alexander Geddes "Thain", who had married Mgt Thain. 
eg: 1881 Buckie census

Name | Age
-- | --
Joseph Cowie Pum | 29
Mary A Cowie Pum | 27
Jessie A Cowie Pum | 2
Margaret Cowie Pum | 69

Anyone not familiar with this would mark them down as the surname Pum or Cowie Pum.

**Comment by geoffj-FUG** [comment]
Rhoda

 

Thank you for this. I have learned a lot from this.

 

I will put an explanation in the Instructions.

 

Geoff

**Comment by Captainkirkdawson** [comment]
I assume that your search result was not from FreeCEN as I cannot see that we have transcriptions for Buckie.

Be that as it maybe if the Surname is transcribes as COWIE PUM then it would be retrieved by searching for either COWIE or PUM

Hence is there really a need for a separate field for these forms of surname?. 

In fact I would now go further and say  is there really a need to a maiden surname field????? The search will currently retrieve the record by either married or maiden name. The only benefit COULD be in the display of the record by having two fields. This would be important if the original census document had 2 fields

**Comment by Captainkirkdawson** [comment]
In fact if the maiden name is simply an inference on the transcriber 's part it should not have its own field

**Comment by rhodamackenzie** [comment]
I have to say I have seen very few records with a maiden AND married name for a woman. They sometimes reverted to maiden name in eh census on becoming a widow. The teenames are often used but where could they go if not in a “nickname” or main name column? It seems a shame not to put them anywhere and I always put in the teename if I am searching on ScotlandsPeople, Ancestry or FamilySearch as they come up there in searches.

My example was a transcription from ancestry.

Buckie in the parish or Rathven in Banffshire so is in freeCEN 1841-61. After a few goes, I cannot find any teenames in surname or forename fields in freecen1 or 2.

**Comment by Captainkirkdawson** [comment]
@rhodamackenzie  I was suggesting that they be transcribed but saying that they do not need a separate field. If entered as a second surname in the surname field then a search for either surname will locate the entry. Applies to both maiden and teenames. 
We only need to have separate fields if the original Census document has separate fields. ie they have a specific field for maiden name and teename as well as surname
Do  "ScotlandsPeople", "Ancestry" or "FamilySearch" have a search field for teename  or maiden name or do they just appear as results in a surname search?

**Comment by rhodamackenzie** [comment]
They just turn up in the surname search

**Comment by Captainkirkdawson** [comment]
@PatReynolds Need your agreement that we do nut add fields for maiden name and teenames as these are not fields in the census documents. CEN supports multiple surname in the surname field and searches by the individual ones. Hence both are already supported.

**Comment by geoffj-FUG** [comment]
Kirk

 

The sample I have seen simply has 2 surnames separated by or. There are not 2 columns.

 

Geoff

**Comment by geoffj-FUG** [comment]
Ancestry don’t have a separate field. Their information is very limited and they just have basic info in their search results. 

 

I found the Pums:


Name:

George Conn Pum
 <javascript:OremMetaData.DoOrem(1172238)> [George Conn Cowie "Pum "] 


Age:

48


Estimated birth year:

abt 1843


Relationship:

Head


Spouse's name :

Jane Conn Dugal


Gender:

Male


Where born:

Banffshire, Buckie


Registration Number:

164


Registration district:

Rathven


Civil Parish:

Rathven


Town:

Buckie


County:

Banffshire


Address:

Hall Street


Occupation:

Fisherman


ED:

6


Household schedule number:

64


Line:

5


Roll:

CSSCT1891_47

That is the total record. 

 

Geoff
