### ISSUE TITLE
Review 1st iteration of information for transcribers on Refinery

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#355]
The htm documents are to be put into FreeCEN2 style, in the Information for Transcribers folder.  The CSV files are to be  uploaded, for download from new page on FreeCEN2 to replace https://www.freecen.org.uk/software/incens/SSDOWN.HTM (see story #356)  Documents and filesare in the gdrive, FreeCEN folder, FreeCEN1  documents.

E0 U6 S7 C5: P21

**Comment by FreecenBren** [comment]
Just to put it on record so to speak.
The moving of SSCENS means we are moving instructions that are out of date
in some aspects.
Examples.
No one uses Flopping discs anymore.
Also INCENS has not been used for years and is not workable.
The files that are there for being downloadable contain .EXE files that
anti-virus programs stop you downloading them as well as GOOGLE etc.

I know they are going to be re-worked, but I am concerned that if someone
tries to do a download any of the EXE files from FreeCEN 2 we do not
compromise the site.
I still get occasionally newbies trying to do just that off their own back,
and complain that the FC1 site has come up as spam.

I am sure that someone might know a way round it.
I point out to anyone who wants to download the folders to my DROPBOX
 folder instead.
This covers, WINCC, VALDREV, FCTOOLS  ( which also contains CSVCHECK )
There I have expanded the EXE files and they just have to copy and paste my
file to their PC etc.,

I am probably being a little cautious, but best to put it on record anyway.

**Comment by PatReynolds** [comment]
Yes, the downloads will now be the files themselves, not .exe files that contain the files/documents/spreadsheets.
All documents need to be revised by Rena before making live, so that they are up to date.

**Comment by PatReynolds** [comment]
This now appears to be urgent - the .exe download file may be the one causing our sites (all FreeCEN and FreeREG) to be blacklisted by some web protection sites.  We may need to take the download file off the site.

**Comment by FreecenBren** [comment]
This is what I have been saying.
I get emails from helpers and COORDS alike asking me for what they need as
they are unable to download the files they need.
The EXE files are safe but over the years we have had antivirus programs
rejecting them. Macfee was the first.
Now Google as well as others have joined the reject list.

I send, VALDREV, WINCC,  FCTOOLS  (including the CSVCHECK  that is based
inside FCTOOLS) to whoever wants them via DROPBOX, already executed for
them. (No EXE file included)
So, yes I agree that they need removing.

We also need the PARMS files that are also on the FreeCEN 1 web page
removed.
They are downloadable,  but they are now available under Manage Pieces on
FC2 and are more up to date.
I assume that COORDS will be able to see them there when they need an
updated copy.
The COORDS, Checkers, Validators, use them in WINCC and VALDREV

Richard and I will hopefully get the full set for every Census year for
every Census County done as soon as time permits.
There are a few errors on existing ones for E & W but they will also be
corrected in time.

I was on FreeREG on Monday showing the local U3A, and we got messages to
say it was unsafe and closed us down more than once.
Will try again from home and see if I get the same in a few days, time
permitting?

**Comment by richpomfret** [comment]
@FreecenBren Can you confirm that this is all fine now? If so we can close this issue as should be complete.

**Comment by richpomfret** [comment]
Apparently broken links might might mean an update is needed in Refinery.

**Comment by AlOneill** [comment]
There are a number of issues here: 

**On test3** FWIW, the links to the two CSV files and the Fields PDF now work (links updated). The Fields PDF has page headers with Pat's local file path in the headers (probably a Bad Thing) and we are in the process of updating the Fields, so do we really want volunteers to continue to download this elderly, unfriendly document?

**On test2**, although all 3 files are listed under Refinery > Files, they can't be downloaded from there ('Not found'), so links in pages cannot work.

I could replace the files on **test2**, and update the links — this would put test2 out of step/sync with test3, but that would hardly matter. Suggest I don't replace the Fields PDF, just remove it from test2, along with links from webpages.

When we "copy" webpages to live, it will need to be done in such a way that the Refinery Tables (i.e. database tables for Files and Images) are transferred too, i.e. *not* done manually, **OR** we transfer manually and then update Refinery > Files manually plus the links in the webpages, so that the Live site holds the master tables.

Or maybe I'm not looking at this in the right way ... !!

**Comment by PatReynolds** [comment]
Only the example CVS files are needed, now we have html pages again for the 'how tos'.

I think we had decided that we did not need to test refinery pags on test2 (whichever comes first in the sequence)

Links to downloads needs resolution - perhaps as a separate issue?

**Comment by AlOneill** [comment]
Links to CSV files for download now fixed on test2 for the Transcriber Help pages.

**Comment by richpomfret** [comment]
@PatReynolds to draft 'quick' bit of text in the meantime to include for transcribers once they first login.

**Comment by PatReynolds** [comment]
DRAFT Information for Transcribers (interim) now written. @FreecenBren and @AlOneill to check
DRAFT Fields in the FreeCEN1 spreadsheet in progress - some questions need answering.

**Comment by PatReynolds** [comment]
Notes 9/1 on where we are:
Interim notes DONE
Fields in the FreeCEN1 spreadsheet (awaiting response on 3 queries, 5/12 and 9/1)

**Comment by PatReynolds** [comment]
I believe all now complete, ready for next steps:
Ensure instructions are mature-looking (well presented) and friendly: correct syntax, use sentences, replace unhelpful (or obscure) terms such as "routine", explain the essential terms, reduce the number of instances of the passive voice and tidy the typography
Final content checking
Add some more ids and complete cross-references
?Add each column/field to page navigation
Finalise layout

**Comment by richpomfret** [comment]
For @AlOneill to take a look when possible.

**Comment by benwbrum** [comment]
@AlOneill refreshing memories on this.

**Comment by AlOneill** [comment]
Do not see how the page that that takes a new transcriber through an example spreadsheet can work nicely without instructions to use browser Back button — especially for the final section that asks the reader to look at different parts of the Field descriptions page. So suggest we add some notes to "Info ..." page about when use of Back button is appropriate and safe (static pages), and when it is not (dynamic pages).

I imagine that users will be using the Back button anyway. Best to acknowledge and explain, rather than ignore.

**Comment by AlOneill** [comment]
Not keen on the somewhat inelegant page names: the reader will not care much about FC1/FC2 distinctions in this context. Still thinking re alternatives — suggestions welcome.

**Comment by PatReynolds** [comment]
Files currently on refinery:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/5488301a-ca58-485c-958b-ae2ee63581b9)
Files that were on FC1: was wrapped in: SSCENS.EXE which has been removed from the server as it caused serious issues.
The contents of SSCENS.EXE are now, I believe in refinery, unless @FreecenBren knows better.

This story cannot, however, be closed as there is no way to access these files from a FreeCEN2 web page.  The pages themselves are story #354 Online help and transcriber process documentation for existing systems available which is in back-log.  I will edit that story to say there is information about it in this one.

I suggest, since there is a lot of work to do before #354 is complete - likely to be several months - that in the meantime I make a VERY simple page, that just has the links.  Then this story can be closed.

**Comment by PatReynolds** [comment]
Current html moved to https://drive.google.com/file/d/1BMUjjBivw922K9oDUUbAP4uZB8ls5LU1/view?usp=sharing

Text being edited to remove all out-of-date information, prior to new information being added where needed.

**Comment by AlOneill** [comment]
@PatReynolds Not sure that asking Brenda to edit/comment on a paste of the raw HTML is the best way to go here — it is not pleasant to read. And I am certainly not going to simply copy back an edited version of the raw HTML — too error-prone. Have I missed the point?

**Comment by PatReynolds** [comment]
Hi Alison, I' have amended earlier post, for clarity.

**Comment by FreecenBren** [comment]
I agree with you Pat.

**Comment by PatReynolds** [comment]
Pat to move from Refinery to google docs for review.

**Comment by richpomfret** [comment]
@PatReynolds to finalise for @AlOneill to test/review.

**Comment by PatReynolds** [comment]
Text is on test3.freecen.org.uk

This is not intended for long term use, but to be somewhere new transcribers can be sent to get very, very, basic info on how the system works, and to download the things that are no longer available on FC1. Still needs checking.

**Comment by richpomfret** [comment]
@AlOneill to also take a look.

**Comment by AlOneill** [comment]
@PatReynolds To clarify, which of these two pages do you want me to get ready? I'm guessing it is the page with "interim" in the title, but both have non-CEN things in them!

DRAFT Information for Transcribers (interim) 
DRAFT Information for Transcribers

**Comment by PatReynolds** [comment]
Yes, it's DRAFT Information for Transcribers (interim)

I can't see any non-CEN things in it!

**Comment by AlOneill** [comment]
@PatReynolds Thanks.

See the highlighted "batches" in Transcriber actions. I can re-write the sentence, no worries.

Other issue: "Roadmap" action produces error. Is the page called "Road Map" accurate enough to be re-named and used (after tidying)?

**Comment by PatReynolds** [comment]
Story #778 written to resolve the Roadmap problem.

Yes, please deal with the highlighted sentence.

**Comment by AlOneill** [comment]
@PatReynolds the link to the Roadmap given in #778 requires a log in to GoogleDocs to view.

"Info" page pretty much done otherwise.

Will do "Fields" page next. (It is linked from Info and so needs to be made ready before "Info" is deployed in a sync.)

**Comment by AlOneill** [comment]
@PatReynolds The two PDF files for download in the "Fields" page are not with our files (the links both point to /system/resources/). The files are a list of Places and the instructions for searching them.

Do you have a copy of the PDF files? Or perhaps the links should point elsewhere?

**Comment by PatReynolds** [comment]
Found I had to move the folder containing documents to the "shared drive" (formerly called "team drives" You should have an invite to that drive/folder. Please let me know if has all gone horribly wrong.

**Comment by AlOneill** [comment]
@PatReynolds Thank you. Found and downloaded.

**Comment by AlOneill** [comment]
@PatReynolds Ready for Review  — the 3 initial Transcriber Help pages (together with Info for Coords).

Will remove DRAFT and otherwise get ready for sync once they are approved.

**Comment by PatReynolds** [comment]
@Captainkirkdawson current text on bugs (information for transcribers, main page) is:
If the message is about a bug or system failure, ask your Syndicate Coordinator (SC) to trouble-shoot for you. And try to replicate the problem. Remember to include details of your system, what you were doing, screen shots, etc. SCs can use Contact us, if necessary.

Should that be changed to
If the message is about a bug or system failure, ask your Syndicate Coordinator (SC) to trouble-shoot for you. If they can't help, please use the 'Report a Problem' button at the bottom right of all screens (when you are logged in.  

Otherwise, this page is good to go.

**Comment by PatReynolds** [comment]
On "the spreadsheet fields" links to appendices do not work.  I'm not sure if they _will_ work, on live, or whether they should be removed (or inactivated and some kind of note added about being 'forthcoming'. 

Otherwise, this page is good to go.

**Comment by PatReynolds** [comment]
Abbreviations page is ready for release, thank you for all, @AlOneill

**Comment by Captainkirkdawson** [comment]
@PatReynolds re your question to me. That is much better

**Comment by AlOneill** [comment]
@PatReynolds Yes, the links will work once 'draft' has been removed from page name.

Will replace text on Info page with the shorter (2nd) version.

**Comment by AlOneill** [comment]
There are some issues with the heading of the Feedback form: the logo colours are not correct; the logo is clipped top and bottom, which does not look good.

![FreeCEN2_Feedback](https://user-images.githubusercontent.com/14852554/73757793-aabaf380-4761-11ea-9e1c-b4d6af506b9f.png)

Maybe these are being addressed elsewhere? If not, then we need to open an issue.

**Comment by Captainkirkdawson** [comment]
@AlOneill there is story systemwide for this Implement new colours (inc. logos) on print materials#69 You were assigned

**Comment by AlOneill** [comment]
@Captainkirkdawson TY, but don't think an online form counts as "print" materials.

**Comment by Captainkirkdawson** [comment]
In which case @AlOneill how about Update revised logos#85 then we can use the updated scss

**Comment by AlOneill** [comment]
@Captainkirkdawson If the logo used was the *current* one, then at least the colours would be correct. The further updating of the logo will have to wait.

**Comment by DeniseColbert** [comment]
I've updated the logo

**Comment by AlOneill** [comment]
@DeniseColbert Many thanks! You have fixed both issues with the logo.

**Comment by DeniseColbert** [comment]
Google used to have it so that the form obscured half of the cover image but the recent update fixed the issue. Looks much better now!
