### ISSUE TITLE
Remove all references on FreeCEN1 re downloads, etc. for transcribers.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#356]
Economic 4, Urgency 6, Strategy 8, Cost 6: P=20

Needs #369

Changed title to reflect task.
Task is change all references on FC1 and FC2 to "https://www.freecen.org.uk/software/incens/SSDOWN.HTM" to "https://test3.freecen.org.uk/cms/information-for-transcribers#transcribing" and add text: this link takes you to the Transcriber's help page.  If it does not work, please log in as a member on www.freecen.org.uk and use the 'help' button on the header bar [that text may need improving]. 

Changed story to reflect decision to to implement FreeCEN1 help for transcribers on FreeCEN2 (Oct 2020):
Identify all places/text in FreeCEN1 where change is needed, and implement.

- [ ] Remove page: https://freecen1.freecen.org.uk/censdets.htm 
 - [ ] Contact owner of  page: https://west-penwith.org.uk/fctools and ask them instead to point to:  [appropriate url to be identified]
 - [ ]  Remove the 'Softear and PC Tools' section from the home page
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/4467ff76-803f-4d4a-b6eb-eb8c92ede4f6)

**Comment by PatReynolds** [comment]
Link from https://freecen1.freecen.org.uk/censdets.htm#sscens to https://freecen1.freecen.org.uk/software/incens/SSDOWN.HTM needs replacing with the text 'Login to FreeCEN at , and use the 'help for Transcribers' button".

**Comment by AlOneill** [comment]
@PatReynolds Can't quite see the logic of the text, 'Log in to FreeCEN' taking a user to the Transcriber Help: surely that text should point to the 'Members' URL?

**Comment by PatReynolds** [comment]
Sorry, yes, link should be to Members URL (i.e.
Login to FreeCEN at https://www.freecen.org.uk/cms/refinery/login, and use the help for transcribers button.
I forgot to go and look for the url and copy and paste it in.

**Comment by AlOneill** [comment]
@PatReynolds Good, but what does "use the help for transcribers" button mean? Are you suggesting that the user logs in and then selects the "Help" item in the main menu bar?

**Comment by PatReynolds** [comment]
Yes (I think that's how the help for transcribers page is reached (if not, however it is reached)).

**Comment by PatReynolds** [comment]
Revisiting this story I found two pages called Information for Transcribers on test3.  One in the structure, one at the bottom.  I have added DRAFT to the name of the latter, assuming it's a draft.  My apologies, that was probably me forgetting to do that!

**Comment by AlOneill** [comment]
If you take a deeper look, @PatReynolds , I think you'll find the page at the bottom is marked up as a single paragraph and is David's revised page (removing refs to Syndicates). The **text** is OK but it is useless as a web page without the markup.

**Comment by PatReynolds** [comment]
The transcribers help is now in the hands of @geoffj-FUG who is writing it as a PDF.

So ... is the PDF going to be downloadable from the Transcribers' help web page?  Or ???

This story  - about changing the information on FreeCEN1 still needs doing (I think by a developer) once the place where the new help will be is determined.

**Comment by geoffj-FUG** [comment]
Pat

 

I suggest that we link the Help to open the Handbook Page. 

 

Geoff

**Comment by PatReynolds** [comment]
So (for discussion:) tasks are:
*Transcriber Help*
- [  ] show freecen.org.uk/cms/refinery/pages/freecen-handbook when Transcriber Help button is clicked 
OR
- [  ] place a link to treecen.org.uk/cms/refinery/pages/freecen-handbook from the Transcriber Help page.
OR 
 - [  ] both the above (for ease of use by transcribers, and so that links  to the Transcriber Help page still are useful and don't have to be put back once the handbook moves to html.

*Coordinator Help*
 - [ ] Remove text n ow covered by Hanbook, and start page with a link to the handbook

*General*
Each time a new version of the handbook is made, it is uploaded to Refinery with the same name as the previous version, so that links to it from pages continue to work.

**Comment by AlOneill** [comment]
I do not think that making 'Help' (in the main menu bar) a link to the handbook is a good idea. Transcribers and Coords will want/need help and advice with more than the 'how-to' of transcribing.

**Comment by PatReynolds** [comment]
For Transcribers, I suggest amending the current Information for Transcribers, removing the 'making a transcription section' - and adding in the PDF.

For Coords, I suggest amending the current Information for Coordinators, removing 'transcription Workflow' and adding the PDF.

If you agree, I will make those changes.

**Comment by AlOneill** [comment]
I'm confused. Now I look at the issue description more carefully (!), some of the things discussed here do not seem to be relevant. Or maybe that just reflects my lack of understanding.

Anyway, are we ready to divert transcribers' attention to the new system?

**Comment by geoffj-FUG** [comment]
Pat
I have received feedback on the handbook and ready reference.

I will be removing the Quick reference completely because at the moment it could lead transcribers to miss stuff. I expanded the Ready Reference to include Chapman Codes and abbreviations to match Fields.htm. It was so close to an abbreviated Handbook that I went with an abbrviated copy of the Handbook as a  solution. 

So there will be a Handbook for Coordinators and Validators which is growing!
plus an abbreviated Handbook for transcribing and proofreading England and Wales including Isle of Man and Channel Islands. It is back to a manageable size and does not contain irrelevant information. The content of the abbreviated version is now very stable as it has all been tested and accepted and we have moved well past those steps.

Both will be ready for the beginning of November.

Does this affect your decision above?

Geoff

**Comment by PatReynolds** [comment]
Since it has been decided not to implement the FreeCEN1 systems help on FreeCEN2, I will amend this story to the necessary changes on FreeCEN1

**Comment by Vino-S** [comment]
Ready for the test: test.freecen.org.uk

**Comment by DeniseColbert** [comment]
@PatReynolds could you test this please?

**Comment by PatReynolds** [comment]
AAAggh. This is now about four stories. Note to self: add anything that isn't in the tickyboxes yet, to them, when I return.  Then do all the tickyboxes!

**Comment by Captainkirkdawson** [comment]
No references so presume finished
