### ISSUE TITLE
Change google ad client and add ads.txt

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#357]
It  needs to be pasted in between the <head> and </head> tags

The code is:
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1788116026113570",
    enable_page_level_ads: true
  });
</script>

**Comment by PatReynolds** [comment]
Find out we can't just place on the subdomain, so I will need to ask Lemon to show you how to place on www.freecen.org.uk as well as FreeCen2.  Code is:
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-5379635334920389",
    enable_page_level_ads: true
  });
</script>

**Comment by PatReynolds** [comment]
Also  ads.txt file needs to be hosted to your root domain some further details here: https://iabtechlab.com/ads-txt/ (emailed file 25/1/2018

**Comment by lemon-ukgen** [comment]
I'll use this work as a chance to write FreeCEN-the-first instructions for @Vino-S

**Comment by lemon-ukgen** [comment]
* Two different `google_ad_clients` are mention in this ticket. I used the more recent one (`ca-pub-5379635334920389`)
* FreeCEN previously had non-page-level ads included via `cgi/banner.pl`. I've replaced this with `cgi/pageads.pl` which is included in the `<head>` part
* I've deployed this to `test.freecen.org.uk` only so far

@PatReynolds @Vino-S please can you check the changes are what you expect? I don't actually see any ads but I don't know what's setup inside Google.
[README.intro.txt](https://github.com/FreeUKGen/FreeCENMigration/files/1666290/README.intro.txt)



I attach a worked example of making changes to FreeCEN. This file is present in CVS repo as `README.intro`

**Comment by PatReynolds** [comment]
Thanks, Lemon. Please could one of you deploy to live?

**Comment by Vino-S** [comment]
Thanks @lemon-ukgen.
@PatReynolds  I have updated the FreeCEN and FreeCEN2 live website.
As mentioned by Lemon ads did not show up in FreeCEN2 also.
I have enabled Pagelevelads in header. I had used "ca-pub-1788116026113570" for FreeCEN2 to differentiate from FreeCEN1.
Please have a look and let me know if any changes required.

**Comment by FreecenBren** [comment]
FC1 search page not working


The FreeCEN site has encountered an error. Please try again later.The error
that has been reported is: *Bad name after GoogleAnalyticsObject' at
/home/apache/hosts/freecen/cgi/search.pl <http://search.pl> line 181. on
brazza*

*Only if the problem persists* please mail cen-web@freecen.org.uk giving
full details of the problem -

   - Full details of the error that was reported (see above)
   - Exactly what actions you took prior to the error
   - What browser software (including version) you are using

**Comment by Vino-S** [comment]
Hi @FreecenBren ,
I had fixed the issue. Could you please have a look again?

**Comment by FreecenBren** [comment]
Thanks Vino.
Up and running ok. Tested in with a search and worked fine.
Many thanks
Brenda

**Comment by PatReynolds** [comment]
Sorry, I told Adsense to check when it was only in test, and now they want new code:
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-5379635334920389",
    enable_page_level_ads: true
  });
</script>

Please let me know when that is on live of www.freecen.org.uk (don't worry about other websites at this point.

**Comment by Vino-S** [comment]
Hi @PatReynolds ,
script is now live at www.freecen.org.uk. Please have a look. But as Lemon mentioned ads are not showing up

**Comment by PatReynolds** [comment]
Thanks - I've now activated the Adsense account.  It might need pasting into every page :-(

**Comment by lemon-ukgen** [comment]
Funny you mention it. In the situation before we replaced the old Google Ads code was this

* the code was abstracted away into its own file so it could be easily included in every page with a one-line `<!--#exec`> tag

* but this tag was only present on the index page

I didn't look to change this, since it appeared to reflect a conscious decision about ads on FreeCEN from before.

Adding the code to the search page and other `.shtml` pages should be straightforward.

**Comment by PatReynolds** [comment]
Working fine now on FreeCEN1 and FreeCEN2, but not test2

**Comment by Vino-S** [comment]
Hi @PatReynolds ,
Updated test2. Please have a look

**Comment by PatReynolds** [comment]
Perfect!
