### ISSUE TITLE
Enable Google Analytics on FreeCEN1

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#359]

**Comment by richpomfret** [comment]
Vino to take a look at FreeCEN1 code and see how easy it is to add in the analytics code.

**Comment by Vino-S** [comment]
Hi @PatReynolds ,
I do not have the google analytics code for Freecen1.  Could you please send me the code so that I can add it the website?

**Comment by PatReynolds** [comment]
Code sent 29/11

**Comment by DeniseColbert** [comment]
Code seems to have fallen over:

![image](https://user-images.githubusercontent.com/19173257/34304313-30694bfa-e731-11e7-96c9-d753f88eb189.png)

**Comment by Vino-S** [comment]
Google Analytics script enabled.

**Comment by PatReynolds** [comment]
Working fine now!

**Comment by richpomfret** [comment]
Also tested here and all fine now. :)

**Comment by PatReynolds** [comment]
Needs adding to all pages (see email from Dragos 5 Feb 2018)

**Comment by Vino-S** [comment]
Added google analytics on search page, search_results page, history page, censdets.htm
