### ISSUE TITLE
Remove ccsens.exe from FreeCEN1

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#360]
This file, while innocent, is being flagged as hosting a trojan.  This means it it is impossible to get to FreeCEN1/2 and FreeREG from local authority libriary computers.
So needs to be deleted. 
Contents will be available soon on FreeCEN2, and meanwhile Brenda can send via dropbox.

**Comment by lemon-ukgen** [comment]
I think we're actually talking about `SSCENS.EXE`, of which there appear to be many variants tailored for each district (?)

```
SSCENS.EXE
abdcen41.exe
abdcen51.exe
agycen91.exe
anscen41.exe
anscen51.exe
argcen41.exe
```

If they're all based on the same code I expect they'll all trip whatever test we're dealing with. I'll remove all these `.exe`s.

**Comment by lemon-ukgen** [comment]
Done.
