### ISSUE TITLE
22 P - Validation (VLD correction) possible

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#361]
E.g download, correction software, upload, or
correct on-line.
See https://www.freecen.org.uk/manual/peidx.htm for Validation on FreeCEN1
https://www.freecen.org.uk/manual/6c.htm describes what VALDREV (the old software) does
Dependent on #378 for standardized place names to pick from
Three parts - can be done in any order
(a) place of birth 'normalised' form #
(b) final pair of eyes on uncertainty
(c) computer checking (passed or corrected by a human).

needs #459
needs #378
needs #85
needs #195
needs #89
needs #84
needs #378
needs #92
needs #492
needs #176
needs #195

Economic 0, urgency 6, strategic 9, cost ?2: total 17

**Comment by PatReynolds** [comment]
Suggest Validation should be done online, with final action to be committing to the FreeCEN2 database.

**Comment by FreecenBren** [comment]
Alternate ways besides online, as not all people  have access to Online
services/WiFi all the time.
Restricted service comes to mind. I.e. The Outback, Scotland, remote areas
etc. WW.

Also we have to remember that it can a take a long time to Validate a PIECE.
A PIECE can have many entries between a few hundred  ( Mostly Shipping) up
to 25,000 +
Just thinking out of the box.
Being able to upload a completed VLD Validated as now, needs to be
available to upload to FC2 as well.

**Comment by PatReynolds** [comment]
The new VLD programme will either need to
a) accept a .che file (i.e. probably a .dat file) or the existing system (via FC1)will need to be maintained until the transcriptions in progress are all up in the system.  When developing the CHE programme, it may be possible to take in transcriptions at that point. Or
b) have a temporary conversion from the .che file to the input to the VLD programme.

**Comment by PatReynolds** [comment]
What is the size of the largest .che file submitted to VLD so far?  How does it compare in size to the resulting .vld file?

**Comment by FreecenBren** [comment]
It was also discussed many moons ago to combine the Checking and the
Validation stage into one.
The agreement between the COORDS at that time was about 50/50.
Some said that if it was combined they would still like to do the post
Validation on the VLD before it was uploaded, as they do now, as they felt
that they often find things that were missed or wrong!

**Comment by FreecenBren** [comment]
It depends on what you are meaning by size.  KB/MB or actually rows of DATA.

The largest VLD uploaded I think was one for about 32,000 entries/rows for the 1851 Census.
I am uploading one this week for 21,767 entries/rows and the size is 6356KB.

The average VLD is about 4000 to 15,000 rows as it very much depends on the Census year.
The sizes for each Census year by County depends on how the NA split each County up at the time.
That often depended as well on the population/rural/urban of an area!

The CHE and the VLD will be the same size as they both contain the same number of rows.
The VLD might have some extra data in the Validators choice column.
That would normally be the only difference give or take any odd query the Checker left for them.


Sent from Mail for Windows 10

**Comment by PatReynolds** [comment]
Thanks, Brenda.  I meant size of files (kb). I'm guessing that the largest files might reach a couple of mb.    

I hadn't heard about the discussion on combining checking and validation.  I think we might split the processes as follows
checking: a checker looks at those rows where the transcriber has noted that checking is needed
verification: a coord looks at the data before final sign-off and publication
validation: the computer runs some checks (e.g. 'scholar' as employment and 'age' of 34 is marked as warranting a human check

'validation' might come between transcription and checking, or checking and verifification, or between verification and validation.

**Comment by FreecenBren** [comment]
Uploading the following 6 later today with others.

21767 = 6.356MB my example I example I gave you
5250   = 1.533MB
12500   = 3.65mb
17240   = 5.034mb
2544     =  0.717mb
2815      = 0.822mb

So the average for these 6 would work out at 10337 at 3.019MB

The discussion took place with your processors I believe about merging WINCC & VALDREV.

I think the COORDS would prefer looking at the final version before it gets uploaded as they do now. 

The Checker finds a lot more errors than just those the transcriber has marked with an X. The writing is so bad sometimes as well
The Checker CHECKS it all.  These were the rules set out when FreeCEN started due to the poor quality found in Ancestry etc. Which is just the same today.

The Validator checks the POB and all those query X’s the Checker has left for the 3rd opinion.

The AGE, Occ,  etc., is not a problem as long as we have something  that works like CSVCHECK as that sorts those issues out anyway. 
So I am assuming that you mean the computer can or will do what the CSVCHECK does now..a///


Sent from Mail for Windows 10

**Comment by PatReynolds** [comment]
VLD software had two elements: (a) place of birth name and (b) coordinator's look at data before final sign-off.

**Comment by PatReynolds** [comment]
No field length constraints on FreeCEN2 means that current offline software will need replacing.

**Comment by Captainkirkdawson** [comment]
Validation is now an integral part of CSV Proc
All sub stories have been completed
Propose we close
