### ISSUE TITLE
Flowchart for Transcriber registration

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#364]

**Comment by edickens** [comment]
Should be the same as FreeREG.

**Comment by richpomfret** [comment]
To include automated emails (or need for them).

**Comment by PatReynolds** [comment]
Pat to check with coords whether one or multiple options training pathway - e..g. starting off the spreadsheet with first two pages, and first line of third page, or not having a start.

**Comment by PatReynolds** [comment]
Draft shared with Brenda and developers 9/11/2017
