### ISSUE TITLE
Put a * before 'all counties' and 'any questions' so they go to the top of the list of syndicates to be chosen by new transcribers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#366]

**Comment by FreecenBren** [comment]
Information.

We do not now have a COORD or any Images for Sussex, and therefore no new transcribers needed.

So a Syndicate is also not needed.

The 1851, 1861, 1871 & 1891 Census are all completed and online.

That only leaves the 1841 Census and we do not have any images for them

Sent from Mail for Windows 10

From: PatReynolds
Sent: 26 October 2017 11:36
To: FreeUKGen/FreeCENMigration
Cc: Subscribed
Subject: [FreeUKGen/FreeCENMigration] Put a * before 'all counties' and 'anyquestions' so they go to the top of the list of syndicates to be chosen bynew transcribers (#366)

**Comment by benwbrum** [comment]
This may be doable by reordering the list programmatically, so that we might not need the asterisk.
