### ISSUE TITLE
Add 'contact' link to Help page

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#368]
Contact is rather hidden away on the site. Intuitively, I would look for this on the HELP page and I wonder if we can add a link there? This could be in the opening paragraph or in the right-hand menu options.

**Comment by richpomfret** [comment]
To also add a more prominent 'contact us' below the advert box on right-hand side.

**Comment by Vino-S** [comment]
Ready for testing in test2

**Comment by richpomfret** [comment]
Looks good. Happy to deploy to staging>production.

**Comment by AlOneill** [comment]
The .islet around the .banner is causing trouble at some tablet-range widths. Suggest we remove the div.

@Vino-S As the page is in Refinery, I can fix it if you like.

**Comment by AlOneill** [comment]
@Vino-S Have fixed as described. Also removed style attribute on a.banner as it was breaking responsiveness.

**Comment by Vino-S** [comment]
Moved the changes by @AlOneill to live
