### ISSUE TITLE
Ireland is missing from Birth County list

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#370]
These are in FC1 and should have been copied over

**Comment by DeniseColbert** [comment]
AFAICT only the Northern Ireland counties have been added. FC1 has both NI and Southern Irish counties

**Comment by PatReynolds** [comment]
Yes, all counties are needed.  At the time of these censuses, Ireland was undivided and entirely part of the UK (United Kingdom of Great Britain and Ireland as it was then)

**Comment by Vino-S** [comment]
Updated all counties of Ireland in Live website
