### ISSUE TITLE
Update IPR and Terms of Use notices

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#371]
See https://docs.google.com/a/freeukgenealogy.org.uk/document/d/1ua6ODxzxxgUgvsXkRONpZjiP0C-XRE_K-9ajJQ2J0Kc/edit?usp=sharing
Economic 0, Urgency 10, Strategy 3, Cost 7?: P=20
needs #246

**Comment by malgamves** [comment]
Which repo does this edit go into? I'm up to do it.

**Comment by PatReynolds** [comment]
Hi @malgmves, @vino-s can you explain, please?

**Comment by Vino-S** [comment]
Sure @PatReynolds . I am about to finish a task in FreeBMD and then I will support Malgmves

**Comment by Vino-S** [comment]
Hi @malgamves , Can you send your email address so I can discuss and explain the task?

**Comment by malgamves** [comment]
Sure thing, malgamves@gmail.com

**Comment by mahesh15230** [comment]
If more hands on deck needed, happy to help. Email : mahesh15230@mechyd.ac.in

**Comment by smrr723** [comment]
Is this just a case of adding a direct link to our updated Privacy Notice as with FreeREG here - https://github.com/FreeUKGen/MyopicVicar/issues/1383 ?

**Comment by PatReynolds** [comment]
No - see https://docs.google.com/document/d/1ua6ODxzxxgUgvsXkRONpZjiP0C-XRE_K-9ajJQ2J0Kc/edit?usp=sharing
