### ISSUE TITLE
remove /free-uk-genealogy-transcriber-agreement

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#373]
This page is not needed - link is now to www.freeukgenealogy.org.uk page(s)

**Comment by PatReynolds** [comment]
Changed to a dummy webpage on test3

**Comment by richpomfret** [comment]
Where is the direct URL to test this? It's unclear..

**Comment by richpomfret** [comment]
Let's push this to live.
