### ISSUE TITLE
Request a reset of your FreeREG password

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#375]
Shows FreeREG instead of FreeCEN.

Also, not sure if it worked as no confirmation after reset and not sure if it responds appropriately if a non email address is used in the email box. Please test and update as necessary.

**Comment by richpomfret** [comment]
Still shows 'freereg' instead of 'freecen'. Also there is no confirmation message that a new password has been sent once the user has pushed the 'reset password' button.

**Comment by PatReynolds** [comment]
Now correctly showing 'freecen' in test 2 please push to live.

**Comment by richpomfret** [comment]
Tested here too and all good. Is it also on TEST3? Do push it there and then it can be deployed as normal. :)
