### ISSUE TITLE
Publish FreeCEN information for Coordinators

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#377]
Draft ready for circulation

E0 U6 S7 C7:P20

**Comment by PatReynolds** [comment]
Pat to circulate draft, Alison to add links to other help pages.

**Comment by richpomfret** [comment]
@PatReynolds can you add the link here once the draft is ready?

**Comment by PatReynolds** [comment]
Draft here: https://docs.google.com/document/d/1p2vGWunfRpnBxnIUeU_BZfnfGORDJ9wSm_V4yhkRGzg/edit?usp=sharing

**Comment by richpomfret** [comment]
@AlOneill can you take a look when you get a chance?

**Comment by richpomfret** [comment]
@geoffj-FUG to take a look before Alison.

**Comment by geoffj-FUG** [comment]
Rich, Pat, Alison

 

I am not sure how to upload this so I have attached it to this email.

 

It is the response to action #377.

 

It is a simple first pass feedback response. My view is that the document cannot just be cloned as the FreeCEN process is so different. My comments are in Red.

 

Where do you want me to go from there?

 

Regards

 

Geoff Jarvis

**Comment by AlOneill** [comment]
@geoffj-FUG Your attachment has not survived — can you add your comments to the doc linked in Pat's msg to this issue of 5 Dec — https://docs.google.com/document/d/1p2vGWunfRpnBxnIUeU_BZfnfGORDJ9wSm_V4yhkRGzg/edit?usp=sharing ? 

That would keep all the comments together.

**Comment by geoffj-FUG** [comment]
Alison

 

I have added my comments to the end of the original document.

 

I trust that the formatting survives as I have put all my comments in red in a copy of the original document.

 

Regards

 

Geoff

**Comment by PatReynolds** [comment]
Thanks, both.  I have melded your versions together, suggested a new structure .  It may be easiest to see this in 'viewing' mode.

**Comment by richpomfret** [comment]
@geoffj-FUG to review new melded version.

**Comment by geoffj-FUG** [comment]
Rich

 

Done

 

Geoff

**Comment by benwbrum** [comment]
The Google Doc has been reviewed, so the contents can be published (but still need to be published).

**Comment by PatReynolds** [comment]
@PatReynolds to transfer draft to Refinery, for review

**Comment by PatReynolds** [comment]
Ready for your review, @AlOneill

**Comment by AlOneill** [comment]
@PatReynolds Had a quick look yesterday and fixed the broken, nested lists. Don't worry about the links, I'll assign ids as I go through.

**Comment by AlOneill** [comment]
@PatReynolds  @FreecenBren @geoffj-FUG  Work not complete yet, but have listed a number of questions/comments at the top of the page: some are as a result of not being able to see what Coords see; others are more general. (There may be more to follow ...)

Page can be viewed at:
https://test3.freecen.org.uk/cms/draft-information-for-coordinators

**Comment by PatReynolds** [comment]
Thanks, @AlOneill   I've made some changes,  comments and sent a couple of questions over to Brenda.

**Comment by AlOneill** [comment]
The draft Coord Help page has been restructured and is available for viewing on test3. Four questions remain: these are also listed at the top of the page, with links to the relevant part of the text.

1. The "List of Civil Parishes" section seems wrong/incomplete: What does cause a Piece to be rejected? Coords do not upload at present.

2. Workflow, item 5: mention of assessing data images for "language" — all returns are in English AFAIK, except maybe the Channel Islands — French?? Is this simply a hangover from REG where Latin could be used?

3. Workflow, item 18: CEN does not use UCF or anything similar: have deleted. Which reports, if any, are available to a CC re a transcriber's work?

4. Transcriber skill level: does sentence re default difficulty of images make any sense in CEN? Are the available skill levels now appropriate for CEN?

**Comment by richpomfret** [comment]
@PatReynolds to take a look.

**Comment by PatReynolds** [comment]
I have responded (with some alterations to text.

**Comment by AlOneill** [comment]
@PatReynolds The Info for Coords (interim) page is nearly done. Apart from the final tidying up, there is one outstanding question:

Workflow, item 18 reads, "Run stats scan monthly to assess errors rates per transcriber. Advise SC." Does this make any kind of sense for CEN?

AFAIK, the database does not know who transcribed what. Individual coords should have such a record, but that is as far as it goes. (I do not have access to Coord Actions, so can't check directly what is available.)

**Comment by geoffj-FUG** [comment]
Alison

 

FreeCEN Coordinators do not do this.

 

Because FreeCEN is a 3 step process Coordinators get to know who their good and not so good transcribers are. Proofreaders pick up a lot of the errors. There is no quality control of volunteers work in a statistical sense.

 

However FreeCEN1 had an error report that Coordinators accessed each month. This showed which pieces had crashed at upload and when Coordinators did their own uploading they would go and correct the crashed pieces ready for the next upload. The wording does not seem to apply to this instance. Brenda processes all the errors that cause crashes at the moment.

 

Geoff

**Comment by FreecenBren** [comment]
AFAIK.
Not all COORDS will know who did what and when.
Some Counties  over the last 20 years have changed COORDS (Retired : Ill or
Died) and not all the volunteers names of those Pieces that were already
online were passed over.
Others do not want their names shown neither, for whatever reason and that
has to be respected.
Obviously when FreeCEN 2 is up and running things will be different when it
is automated.

I agree with what Geoff has said Re the failures/Crashes etc.
They are not all straight forward. The most failures we are getting are
those that passed OK in FC1, but failing in FC2, past examples were the
Lancs failures.

CEN does not always fit in with REG ways of working.

**Comment by AlOneill** [comment]
@geoffj-FUG @FreecenBren Thank you both.

@PatReynolds Propose to remove Workflow, item 18, for now.

**Comment by AlOneill** [comment]
Also propose that, as the Transcriber Help is not far behind, we hold back (just a little longer), and then publish the two together (with cross-references from Coord Help to Transcriber Help as working links, rather than promises.

**Comment by PatReynolds** [comment]
Good idea, @AlOneill

**Comment by AlOneill** [comment]
@PatReynolds Ready for Review  (as are the 3 initial Transcriber Help pages).

Will remove DRAFT and otherwise get ready for sync once approved.

**Comment by PatReynolds** [comment]
Good to go.  Thank you, @AlOneill

**Comment by AlOneill** [comment]
"Info for coords" is sync-ready, as are the accompanying 3 pages for Transcribers.
