### ISSUE TITLE
Update/replace GENIE place locator and Supplementary Places lists (was PlaceSup.GEN in VALDREV)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#378]
Possibly replace with FreePASTplace.
?Needed before new transcription tools?
?Needed before Images online?

needs #165

E2, U3, S8, C5?:P18

**Comment by richpomfret** [comment]
To discuss/review - can do this via Slack or here.

**Comment by PatReynolds** [comment]
GB1900 (https://geo.nls.uk/maps/gb1900) could be used by Validators for hard-to-find places

**Comment by geoffj-FUG** [comment]
The Place Names Database replaces both Genie and Placesup in CSVProc.
It is far more comprehensive that the old tools.
This story can be closed.
Geoff
