### ISSUE TITLE
Change "Household" to "Dwelling" throughout

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#38]

**Comment by sean-wood** [comment]
Ben - quick question who would normally verify this, I will reassign to them. Would it be Brenda?

**Comment by benwbrum** [comment]
We cannot reassign the story for testing until this feature is deployed on the test server so that it can be accessed by Brenda or others. Usually this deployment  is done shortly before the Sprint review, which is when the story would be marked as ready for testing and reassigned. So hold off for a bit.

Ben

**Comment by sean-wood** [comment]
I will do Ben
