### ISSUE TITLE
Open Data Day

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#382]
Open Data Day is Saturday 3rd March.  What could we do to celebrate? http://opendataday.org/

**Comment by richpomfret** [comment]
Potentially provide Cornish data as 'open data' access on a page for this?

**Comment by richpomfret** [comment]
To get confirmation from Trustees.

**Comment by PatReynolds** [comment]
Open Death Data - undertakers blog
