### ISSUE TITLE
Cloud9: Create FreeCEN workspace

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#385]

**Comment by AlOneill** [comment]
As someone whose main task is to update our SCSS/CSS, I don't think things are quite right yet: amongst other things, I am investigating why the current icons CSS is not served to a browser preview page. I suspect that the `config/initializers/assets.rb` file needs either editing or deleting !!! (BWDIK)

**Comment by benwbrum** [comment]
We think this has been resolved, and will re-open if it comes up again.
