### ISSUE TITLE
Email update fails

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#386]
I tried to update an email reported as undeliverable (to a gmail.co.uk address), but got an error report - 'The update of the profile was unsuccessful ["Email address Userid email already exists on change", "Email address Refinery email already exists on change"] '

**Comment by FreecenBren** [comment]
I assume all gmail email address are

@gmail.com

And NOT  .co.uk

 I could be wrong!!!!

**Comment by PatReynolds** [comment]
Exactly, Brenda - I was trying to change a .co.uk to a .com, as that should work (the .co.uk failed)

**Comment by smrr723** [comment]
Hi @PatReynolds - could you send me an email with the email address in question, so that I can check if it does actually exist on the system or not? Thanks.

**Comment by smrr723** [comment]
So the .co.uk email address for the user already existed in the system which is why you got the error - so probably not an issue here, but will test with another user just to make sure.

**Comment by smrr723** [comment]
Tested this with a test userid and the email update works with no errors. 

Issue can be closed.
