### ISSUE TITLE
Citation Generator

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#387]
See FreeREG #1374 for details
Needs #410.

**Comment by richpomfret** [comment]
Vino to assist Sudaraka with information on how the database is structured (afte receiving relevent models).

**Comment by richpomfret** [comment]
@sudaraka94 can we now test this on test3 or 2?

**Comment by sudaraka94** [comment]
I got the information on how to deploy it on test2 or 3 . I am preparing my implementation to be deployed.

**Comment by PatReynolds** [comment]
Looking good on test2 @sudaraka94 !

**Comment by AlOneill** [comment]
Looking good, except that I cannot tab to Citation Generator button because it is an empty link (href="#"). Also there is no warning that the citations themselves will appear in a new browser tab.

[I use Evidence Explained style citations, but it is so long since I did any proper FH that I can't remember what to expect — however, will check if I am the only EE user on the team!]

**Comment by PatReynolds** [comment]
Contacted Wikitree, Family Tree Maker and Evidence Explained 13/9/2018

**Comment by richpomfret** [comment]
Sounds like we are now ready to make any final adjustments and then push live.

**Comment by PatReynolds** [comment]
@sudaraka94 asked about final adjustments via email and slack  17/10/2018

**Comment by richpomfret** [comment]
Awaiting final changes by Ben and Sudaraka.

**Comment by richpomfret** [comment]
@benwbrum has now completed his bit. Now trying to establish availability for @sudaraka94 to finish it off.

**Comment by richpomfret** [comment]
@benwbrum to add in the permalink code.

**Comment by sudaraka94** [comment]
I am available @richpomfret . Let's finish this off. I will contact @benwbrum fore required details

**Comment by richpomfret** [comment]
@benwbrum to work through 410 first.

**Comment by Captainkirkdawson** [comment]
Have picked this up. Integrating freereg citation code approach  ( #1374)

**Comment by Captainkirkdawson** [comment]
The citation generator is available for viewing on test2

**Comment by Captainkirkdawson** [comment]
It should be noted that the citation is only generated for results. It is not generated for next and previous dwellings. See issue #675

**Comment by PatReynolds** [comment]
Title of Button "Citation Generator" is not in bold, as the other buttons are.
Permanent URLS work.

Wikitree generates incorrect citations (only one tested so far - correcting these might resolve issues in other formats - nb (search Elizabeth Lawson or Thomas Lawson - not the same Elizabeth and Thomas as in the correct examples further down, which are my ancestors, because their records are  not in the test2 database, and I can't get to test3 to generate the proper ones from there).: 
1841: """ database, FreeCEN (https://test2.freecen.org.uk/search_records/59693ffbe93790e11bd19ef6 : viewed 15 Apr 2019), in household of , ; from 1841 "England, Scotland and Wales census," database and images; citing PRO /, Folio , Page , Schedule , The National Archives, Kew, Surrey.
1851: "" database, FreeCEN (https://test2.freecen.org.uk/search_records/59041b8ae9379091b1aacef8 : viewed 15 Apr 2019), in household of , ; from 1851 "England, Scotland and Wales census," database and images; citing PRO /, Folio , Page , Schedule , The National Archives, Kew, Surrey.
1861: "" database, FreeCEN (https://test2.freecen.org.uk/search_records/59038b95e9379091b1281f1f : viewed 15 Apr 2019), in household of , ; from 1861 "England, Scotland and Wales census," database and images; citing PRO /, Folio , Page , Schedule , The National Archives, Kew, Surrey.
1871: {{Cite web|url=https://test2.freecen.org.uk/search_records/59039492e9379091b14650d0|title=FreeCEN - UK Census Records (England, Scotland, Wales)|accessdate=15 Apr 2019|work=FreeCEN|publisher=Free UK Genealogy}} 
1881: "" database, FreeCEN (https://test2.freecen.org.uk/search_records/5902aa75e9379091b1de964d : viewed 15 Apr 2019), in household of , ; from 1881 "England, Scotland and Wales census," database and images; citing PRO /, Folio , Page , Schedule , The National Archives, Kew, Surrey. (had to go to another name as 1881 not covered for Notts or Lincs
1891:"" database, FreeCEN (https://test2.freecen.org.uk/search_records/590442a5e9379091b1e39a8b : viewed 15 Apr 2019), in household of , ; from 1891 "England, Scotland and Wales census," database and images; citing PRO /, Folio , Page , Schedule , The National Archives, Kew, Surrey.


Should be in this format: 
↑ "England and Wales Census, 1851" database, FreeCEN (https://www.freecen.org.uk : viewed 6 Oct 2018), Elizabeth ROBINSON in household of John ROBINSON, Claypole, Newark, Nottinghamshire, England; from 1851 "England, Scotland and Wales census," database and images; citing PRO /2138, Folio 328, Page 34, Schedule 137, The National Archives, Kew, Surrey.
"England and Wales Census, 1861" database, FreeCEN (https://www.freecen.org.uk : viewed 6 Oct 2018), Thomas LAWSON, Bassingham, Nottinghamshire, England; from 1861 "England, Scotland and Wales census," database and images; citing PRO RG 9/2477, Folio 99, Page 13, Schedule 79, The National Archives, Kew, Surrey.
Nb difference between person 'in the household of' and head of household citations.

**Comment by Captainkirkdawson** [comment]
I need help from @Vino-S  to advise on missing field definitions associated with head of household. Question raised on slack.

**Comment by Captainkirkdawson** [comment]
Wording on other citations need to be checked by an expert!

**Comment by Captainkirkdawson** [comment]
Have completed the citation clean up noted by @PatReynolds  
Need final confirmation by experts on citations. Running on https://test2.freecen.org.uk/

**Comment by PatReynolds** [comment]
Family search and Legacy are both missing the end of the PRO reference (just showing PRO, should have a / and a number, Folio and Page.
Evidence Explained has an extra (unwanted) space before the final full stop.
Had a very peculiar result from https://test2.freecen.org.uk/search_records/5904214be9379091b1b35e50 - only three citation types appeared - but fine now, and problem not replicated in any of the other tests I made, so assuming it was actually a chronically slow load speed.

**Comment by Captainkirkdawson** [comment]
Fixed those formats on test2
