### ISSUE TITLE
Change banner ad to images only (check 4 Dec 18)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#392]
Test to see impact on earnings

**Comment by richpomfret** [comment]
See issue #511, where Scott theorised that 'image only' ads setting might be responsible for adverts not being shown at all in some cases e.g. on the search results page.

**Comment by PatReynolds** [comment]
Tests in progress on FreeCEN1, to do on FreeCEN2

**Comment by PatReynolds** [comment]
Test started on FreeCEN2  Responsive ad 16/10/18

**Comment by PatReynolds** [comment]
ADvert on FC1 search earned 19% more as image only - so chosen.

**Comment by PatReynolds** [comment]
Ad Unit "FreeCEN2 Responsive Header" up 26% as images only, so chosen
Ad Unit "FreeCEN1 Homepage" up 7% as images only, so chosen
