### ISSUE TITLE
23 P - Forums (was Newsletter distribution)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#394]
To create alternatives to Rootsweb as discussion groups (newsletters being addressed separately) - title changed to reflect this.

Urgent as Rootsweb is continuing problematic and longevity of the site in a way that supports us is very uncertain (see#1033, see FreeREG #620 and #692).  This feature will allow opt-in / opt-out distributions on the message system.  Needs to be done first on FreeREG, where users are very used to messaging system,  first.

E0  U10 S7 C6: P23

**Comment by edickens** [comment]
When the website message system on the server has had the change to allow pdf attachments made live, I will use that, not the mailgroups, to send out my newsletters.

**Comment by PatReynolds** [comment]
@edickens I believe that an opt-out is needed, both here on FreeCEN, and on FreeREG.  Will be implemented first on FreeREG.

**Comment by richpomfret** [comment]
Helen is currently workin on this.

**Comment by PatReynolds** [comment]
Sent out invites 23/09/2018.  I will make  Denise, Rich and @FreecenBren managers when they have accepted their invitations.  I've sent an email to the helpers list, Brenda - could you un-embago it, please?

**Comment by PatReynolds** [comment]
Invites don't seem to have gone out ...
I've sent another email to the helpers list letting everyone know that.
Brenda - could you  un-embargo it, please?

**Comment by FreecenBren** [comment]
You are not embargo now as I released it the other day.

Brenda

**Comment by helhyde** [comment]
Thanks, Brenda

Best wishes,

Pat

Executive Director, Free UK Genealogy

**Comment by richpomfret** [comment]
Invite test works ok. Shall send out full invite to everyone else.

**Comment by richpomfret** [comment]
Invites have been sent out. Will need to resend to those who have not accepted the invite/check our process for inviting new transcribers to the group upon sign-up.

**Comment by richpomfret** [comment]
Shall also troubleshoot any people who have had issues joining..

**Comment by richpomfret** [comment]
Resent invites today for those that had 'expired'. I will send a final round of invites at the start of Feb and state that unless they join now, they will be removed from the list. We may wish to have a separate pipeline for contacting past transcribers who are now 'dormant' in terms of letting them know that they are welcome to begin again.

**Comment by richpomfret** [comment]
I think we can consider this complete. Closing.
