### ISSUE TITLE
Add message to those blocking adverts

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#395]
Message to explain that we are a charity, adverts are a vital part of our income, and that if you prefer not to see adverts, please consider making a donation

E6 U3 S8 C8: P27

**Comment by richpomfret** [comment]
Alternative is to provide our own donate 'advert' to replace blocked adverts when users are utilising an adblocker. Variety of these are preferable e.g. donate, easyfundraising etc.

**Comment by DeniseColbert** [comment]
Some draft designs in Projects folder of drive

**Comment by smrr723** [comment]
Hey @DeniseColbert - have put a banner ad (header) based on your designs up on https://test2.freecen.org.uk/ for testing (alongside Issue #506).  If this looks ok, I'll go ahead and add the same to the other ads, so let me know what you think!

I also noticed that our message with a white bg, or any ads which show with white bgs don't stand out very much, so have added a small CSS box-shadow on the ad unit.

**Comment by richpomfret** [comment]
To fix the issue with the donate ad appearing prior to the advert. To experiment with the box shadow and see if there is a flat alternative which still makes it standout.

**Comment by smrr723** [comment]
Have tested a solution to delay the adblock message load by 2 seconds, which seems to allow adsense enough time to load and display.  Will put on test2 shortly.

**Comment by smrr723** [comment]
Added the Adblock BG to other responsive ad units and tested as much as possible - currently on test2, with Issue #506.

Only the box ad on volunteering opportunities page remains as I'll have to make these edits in Refinery, on production.

**Comment by richpomfret** [comment]
Still flashes up with the donate prior to the advert clicking in. Let's explore alternative ways to check if the advert is loading or not. Still requires hyperlinks (ideally too).

**Comment by smrr723** [comment]
Hyperlink to donations page now added to all banners and also fixed the flash up using javascript to detect if Adblock is being used.  Deployed to production.
