### ISSUE TITLE
Define levels of Adsense/AdExchange targeting

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#396]
i.e on non search pages you may be able to add MPU's 300x250's and define sections for targeting in case needed down the line
Work being undertaken by Kate Peskett, Adsense/AdExchange volunteer

Economic 4, Urgency 3, Strategy 3, Cost ?5: P=15

**Comment by richpomfret** [comment]
Not sure if this is at all related, but a few weird adverts (spam-like) are cropping up on FreeCEN2 at the moment..

**Comment by katepeskett** [comment]
Hi Rich, do you have any screenshots of the spam like ads?

**Comment by richpomfret** [comment]
@katepeskett these are now fixed (apologies for missing your message). It will be an ongoing task to block any 'bad ads'.

**Comment by PatReynolds** [comment]
To discuss whether this issue is still live.
