### ISSUE TITLE
Restrict change of Transcription Agreement status to the individual, through the interface

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeCENMigration#397]

**Comment by Vino-S** [comment]
Refer FreeREG issue 35

**Comment by Vino-S** [comment]
The Agreement status can now be updated by the transcribers only by themselves not by others like( system_administrators, "syndicate_coordinator" etc.)
Updated in test2 for testing.

**Comment by richpomfret** [comment]
Pat has tested and seems fine to deploy to test3 - I will also see if I can break it once it is on there.

**Comment by richpomfret** [comment]
Ready to be pushed to live.
