### ISSUE TITLE
Ad between search results is broken

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#399]

**Comment by DeniseColbert** [comment]
![image](https://user-images.githubusercontent.com/19173257/35066530-d7df4f6e-fbc8-11e7-9d03-86c894c09421.png)

**Comment by AlOneill** [comment]
I think the CSS could be part of this issue: it is a little complicated, so will investigate and report back.

**Comment by richpomfret** [comment]
Is this now fixed?

**Comment by richpomfret** [comment]
Advert is broken if no results are found - it shows an empty advert box below the results. If no results are found, no advert should be shown.

**Comment by Vino-S** [comment]
Added to code in test2 for testing

**Comment by richpomfret** [comment]
Tested and fixed on test2. Please do push to live.
