### ISSUE TITLE
Create tool to manage place of birth names

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#402]
This is to replace (part) of the old VLD software.
Place of birth is recorded 'as is' in the census - for example if the enumerator wrote Brighton in the county of Kent, the transcriber records Brighton, Kent.  Or if they wrote Flower (local pronunciation of Floor) Northamptonshire, the transcriber records Flower, Northamptonshire.  Some researchers will find this useful, but it makes it difficult to search, so the old VLD tool allowed a Validator to choose alternative placenames from a drop-down list (or add to the list if missing) so that searches would be conducted on the assumed correct name.  The new tool will build on this to create a single pick list of places which are linked open data - enabling us to build relationships across our projects and beyond, in due course
needs #378
Potential way that place of birth could be standardized after #816 ?

**Comment by geoffj-FUG** [comment]
There is a problem with the definition of this story.
vld has never had a pck list for the alternative POB. It has always been a research and type in exercise for validators.
The old Place names used by vld has been replaced in the CSVProc by the Place Names Database. This is not a drop dowen pick list.
The problem with a pick list is that it leads the validator to an answer. For best results the validator must decide on the best answer. This means that they will consult various references and arrive at a conclusion and enter that conclusion int the Alternative POB fields.
The ability to enter an Alternative POB has also been extended to the Transcriber and Proofreader in CSVProc. They often come across obscure places within the addresses in the census piece. 
Many Transcribers take pride in resolving Place Names themselves. It gives them satisfaction in achieving a higher standard of work. They can do this in CSVProc.
Geoff

**Comment by PatReynolds** [comment]
Tahnks, Geoff, that means this story can be closed.
