### ISSUE TITLE
Review UX on ipad

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#405]
E1, U3,  S10, C 7: P21

**Comment by rhodamackenzie** [comment]
On iPad:
Looking at search page on freeCEN2, before i do any searching:
the page looks professional, clear, elegant, everything big enough (even for old eyes). All seems fine on safari and on chrome on iPad.

off to do some searching

**Comment by rhodamackenzie** [comment]
Seaching on chrome and safari:
advert on right covers part of table (top end)
Everything works fine except:

Wildcard searches (with a place) work fine on PC, but they don't work on either safari or chrome.
"no results found" is displayed.
Need Info on wildcards in "help" .e. which can be used.

**Comment by PatReynolds** [comment]
Wildcard help - think that @AlOneill has this in hand.

@Captainkirkdawson is the rescriction still needed?Anything we can do to broaden the search?

Wildcard searches not working on IPad needs fixing.

Advert covering table needs fixing.

@Captainkirkdawson should I make new stories for these individually?

**Comment by PatReynolds** [comment]
Closing as Rhoda has made new stories resulting from her findings.
