### ISSUE TITLE
Old Coord uploaded to system

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#407]
Vino to send Brenda list for checking

**Comment by Vino-S** [comment]
Created a button in Syndicate Coordinators action to download list of Syndicate coordinators in CSV format. The button is located at the bottom of the page.
 Ready for testing in test2

**Comment by richpomfret** [comment]
@FreecenBren please take a look if you get a chance.

**Comment by richpomfret** [comment]
Replace by more spefici task (503) so closing.
