### ISSUE TITLE
Merge Master code changes into FreeCEN

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#408]
In order to pick up the enhancements made to the codebase for FreeREG (including search percentages, CONTRIBUTING.md, etc) we need to merge the code from `master` into `freecen_parsing`.  There is a pull request for this at https://github.com/FreeUKGen/MyopicVicar/pull/1339 ,
 but the work should be tracked here.

**Comment by benwbrum** [comment]
This is deployed to test2, including all software changes made to the `master` branch for FreeREG for the last few months.

**Comment by richpomfret** [comment]
We shall do a general test and make sure nothing has broken.

**Comment by richpomfret** [comment]
Tested and no major issues. Please push to Live if this hasn't already been done.

**Comment by richpomfret** [comment]
Part of a wider discussion on merging between FC and FR.
