### ISSUE TITLE
Implement friendly URLs

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#410]
Follow the specs in https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/801

**Comment by richpomfret** [comment]
@benwbrum we may move this back out of the sprint backlog unless you think it will be completed within the next sprint. We're doing a bit of spring cleaning.

**Comment by benwbrum** [comment]
This work has been completed in `master` for FreeREG, and should be plucked over once it has been tested there.

Likely, we will want to address the SEO-related issues as well before deploying or announcing this, since we need to remove our dependency on having the `search_query_id` around on the server.  (That parameter is used to let users navigate from one record of their search results to another from the record view, which means the URLs will break after 30 days when we clean up the search queries.)

**Comment by benwbrum** [comment]
An example of a friendly URL for FreeREG:
`http://localhost:3000/search_records/58ea2b94a020dd02bffac8ec/john-whittle-burial-staffordshire-wolstanton-1637-03-10?search_id=5b17f0a8a020dd665730cbff&ucf=false`
and
`http://localhost:3000/search_records/58ea2b94a020dd02bffac8ec/john-whittle-burial-staffordshire-wolstanton-1637-03-10`

**Comment by richpomfret** [comment]
Fine for FC (and FreeBMD) - may be an issue on FR for baptisms.

**Comment by richpomfret** [comment]
@benwbrum did you get a chance to do this?

**Comment by richpomfret** [comment]
Ready for testing on TEST2. Specific details over on Slack.

**Comment by DeniseColbert** [comment]
Searched Joseph Colbert, 1800 - 1900. Clicked first result:

![image](https://user-images.githubusercontent.com/19173257/52355564-6ef42d80-2a2a-11e9-97a8-9087b13c9e8f.png)

**Comment by PatReynolds** [comment]
@benwbrum is any further testing needed?  If so, please let me know what to test

**Comment by Captainkirkdawson** [comment]
The friendly url is running on test2 for a search result.
It is independence of citation and visa versa

**Comment by PatReynolds** [comment]
https://test2.freecen.org.uk/search_records/59037c10e9379091b1f27c0b generated from  England, Scotland and Wales Census, 1861 database, FreeCEN (https://test2.freecen.org.uk/search_records/59037c10e9379091b1f27c0b : viewed 25 Apr 2019), Ann PATRICK head of household, Market Harborough, Leicestershire, England; from 1861 England, Scotland and Wales Census database and images; citing PRO RG 9/2252, Folio 36, Page 12, Schedule 58, The National Archives, Kew, Surrey. and opened in an anonymous browser generates error screen:
![CaptureErrorURL.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c37263d9b190120013e30d/125516c66e82c728ace21e0d46cb958a379791acaafbad4cb668c2b86b0a65633b0ba92e7391a172fd172f00575e1da8445d5742fcf0892ba4b63c75885e02e4d87f4366846c4ff8e7df46f554f832815d84bfb68b49c5ee3f24e58c8d4d3c1c020ac4.JPG)
Please let me know if you want me to download the session dump or env dump

**Comment by Captainkirkdawson** [comment]
Fixed on test2 cen

**Comment by PatReynolds** [comment]
Agreed, now works fine.
