### ISSUE TITLE
Review nature of adverts on search results page

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#416]
Site adverts look like 'spam' adverts rather than appropriately targeted for user demographics.

**Comment by PatReynolds** [comment]
The one I blocked on FreeREG/FreeBMD has not been served on FreeCEN (the one you shared on slack looks identical, though, but gives a different url - that can't be found on FreeCEN either.

**Comment by richpomfret** [comment]
Seems to be ok now. On-going task to block such ads.
