### ISSUE TITLE
Contact Email of Free UK Genealogy doesn't work

### ISSUE THREAD

**Issue by mahesh15230** [FreeUKGen/FreeCENMigration#418]

**Comment by mahesh15230** [comment]
I have tried to send a mail to soc@freeukgenealogy.org.uk twice
![Screenshot (194).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a9805ac6214ce0011a4df7d/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca9c060046b313916ac217586f76ae5002e550e574fff455d5a4cfaf9802ba6b43c708f5e09e4d8644d68d47f40f2ecdd42e64bef62994597b7bb804dc5e9342ce68e8d4f391601109bb2.png)

**Comment by mahesh15230** [comment]
I'm new here and I got the Delivery Status Notification (Failure) email twice. Any assistance is appreciated

**Comment by richpomfret** [comment]
This has now been updated and SoC email addy is working again. Thanks for letting us know.
