### ISSUE TITLE
Change Doug's role - ensure he doesn't receive emails

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#419]
To update his role so he doesn't continue receiving emails he isn't required to receive.

**Comment by richpomfret** [comment]
@Vino-S can you check the fix for this over the next sprint and establish why it is still happening?

**Comment by richpomfret** [comment]
@FreecenBren please recheck as this may now be fixed.

**Comment by PatReynolds** [comment]
As a temporary fix, I have changed Doug's email addresses.  He does not appear to be on live.  He is on in several roles in test2, that should now be allocated to their proper persons.

**Comment by FreecenBren** [comment]
I have tried to change both Country Coordinators and Manage Countries from Doug to myself for England & Wales, and Margaret for Scotland but it comes up each time as an error.

Tried in Test 2 and then in FC2 both the same error message.
We're sorry, but something went wrong with processing your request. 
A report has been produced and sent to the webmaster. 
Please return to your prior activity but try to avoid doing the exact same action again.


Sent from Mail for Windows 10

**Comment by richpomfret** [comment]
@Vino-S to investigate this - perhaps to change so Doug is no longer on here.

**Comment by richpomfret** [comment]
@FreecenBren to test.
