### ISSUE TITLE
fix dwelling_nummber typo in database

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#42]

**Comment by dougkdev** [comment]
Actually, I don't see the dwelling_nummber (or dwelling_number) in the database at all, just in the code (models/freecen_dwelling.rb and the automatically generated views).  I don't see that we actually use it anywhere.

**Comment by FreecenBren** [comment]
We do not transcribe a dwelling number.  This is generated by the program 'fctools'  when it converts a Completed "Transcription" from a  CSV to a DAT for checking.
This is done to ensure that all the 'people' in each 'dwelling' are kept together. Example : the first Dwelling in a PIECE will have the unique Piece number, 
Then the Civil Parish,
ED number,
Folio number
Schedule number,  
The first " family " in a Dwelling will start with the number 1.
So the first person in that family will be 1,1
The next  person in that Dwelling will be number 1,2
Then  1, 3  1,4  1,5  etc. 
So if the first Dwelling has 12 people living in it they will be numbered in the order transcribed. 1,1 : 1,2 : 1,3 : etc., through to 1,12 :

The next dwelling will then be 2,1 : 2,2 etc through to the last member of that dwelling.
If it is say a school with 120 people in it then the same applies from 1 to 120 in the order transcribed.
So each unique Piece number is done the same.

I could send a copy of an original Csv, how it changes in conversion at the following stage so you can see how these numbers are generated.
This numbering however is to no concern to the Researcher, only for keeping the people in Dwellings together for Freecen.

Hope that makes sence!




Sent from Samsung tablet


-------- Original message --------

**Comment by dougkdev** [comment]
Thanks for the clarification

**Comment by dougkdev** [comment]
This is fixed in the code
