### ISSUE TITLE
Update Freecen2 Roadmap

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#421]
Re: feedback on making it more user friendly.

E 1, U 6, S 7, C7: P21

**Comment by PatReynolds** [comment]
DRAFT FreeCEN Roadmap page with summary which is sufficient for most (but link for those wanting more) created, draft now with @nirgo9116 for proofing

**Comment by DeniseColbert** [comment]
@PatReynolds to delineate the two Roadmap stories and clarify

**Comment by PatReynolds** [comment]
This (html roadmap page with a link to a google doc that does not need to be updated) needs no further changes, so closing.
