### ISSUE TITLE
Remove incorrect publisher ID advert

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#425]
See FreeCEN taxonomy for errors

**Comment by richpomfret** [comment]
Sent to Scott & Vino.

**Comment by richpomfret** [comment]
Important to know that we do have 2 publisher IDs - one for trading and one for us as a charity.

**Comment by smrr723** [comment]
ca-pub-7825403497160061 shows on the volunteering opportunities and transcriber registration page. Do we want to replace this with ads from ca-pub-5379635334920389 which appears to be the correct one?

If so, we will need a new ad unit set up in our ..89 adsense account - unit should be 336x280px size according to the taxonomy doc.

**Comment by richpomfret** [comment]
On hold until Kate provides info for us. @PatReynolds  to chase.

**Comment by smrr723** [comment]
Deployed to production with latest Adsense ID code - ads are now appearing at https://freecen2.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen

@PatReynolds - the ad on the transcriber registration page is a different size to the page above.  Could you create another ad unit in Adsense please, this time being 728px x 90px ?  Thanks!

**Comment by PatReynolds** [comment]
Something odd is happening ... I can't see advert number 9555045725 (or advert name  FreeCEN2 Volunteering opportunities in my adsense account now - others also seem to be missing).

None of the FreeCEN2 adverts should be a specified size - they are all responsive.

could you grab the ad names and numbers on FreeCEN2 for me please - I don't see where they are when I view source code.

**Comment by smrr723** [comment]
Hm, odd.  I could have a look if you'd like but I'd need access.

Regarding the responsiveness of our ad units, I tested creating an ad unit in my own account and got the following snippet when creating a responsive ad:

`<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>`
`
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2653017886319747"
     data-ad-slot="2853979388"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>`
`<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>`

Compared to what you sent me earlier with the new pub-id:

`<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>`
`
<ins class="adsbygoogle"
     style="display:inline-block;width:366px;height:280px"
     data-ad-client="ca-pub-5379635334920389"
     data-ad-slot="9555045725"></ins>`
`<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>`

So, it appears that you might not be selecting the responsive ad creation option - the ad you sent me has width/height defined, compared to the one I sent above which has auto/responsive properties.  Will need to review others if they're the same and supposed to be responsive.

**Comment by PatReynolds** [comment]
Have given you access.  Will send screen shot of what I see.

**Comment by smrr723** [comment]
Thanks - it's showing fine for me in the control panel.  I'll test one of our responsive ad units in place of the code you gave me, and see how it responds.

**Comment by smrr723** [comment]
Second ad unit added here on test2 (is also responsive) - https://test2.freecen.org.uk/userid_details/transcriber_registration - this one will be updated on the next production update, the other ad is already in production because it's in a refinery page.

All units should have the correct pub.ID with the next production update.

RE: the unit on the volunteering opportunities page @PatReynolds - I've tested this with a responsive ad and it doesn't show at all because the container it's in hasn't been coded to be responsive.  Similarly, the header banner across all pages has a responsive issue where it's container makes it disappear on smaller screens.  I'll address both of these in a separate issue.

**Comment by PatReynolds** [comment]
Second ad unit is fine.

**Comment by richpomfret** [comment]
Check and ensure fixed upon deployment - otherwise the issue remains elsewhere.

**Comment by PatReynolds** [comment]
Thanks - can take up to 48 hours to run through, so I'll check Monday.

**Comment by PatReynolds** [comment]
Error message was still there earlier this week, but is now gone.  Issue resolved! Thank you!

**Comment by PatReynolds** [comment]
Error message now back ...

**Comment by PatReynolds** [comment]
Snip of the warning: https://drive.google.com/file/d/0BzRDUeF70Mtpa0o3clQtQ3R2cVU/view?usp=sharing  Nb this is on the old account (for FreeBMD and FreeREG, not the new account for FreeCEN)

Looking for something else, I found te code in the header section of the freeBMD Home page mentions www.freecen.org.uk .... maybe that's the issue?

**Comment by smrr723** [comment]
Ah ok, thanks Pat.  That won't be an issue on FC then, if it's not on the FC adsense account.  It looks like FR & FBMD are missing the ads.txt file though which lets Google know which publisher IDs are allowed on our site.

This issue can be closed - the error above is related to FR/FBMD.

**Comment by richpomfret** [comment]
Fine now on FC. Closing.
