### ISSUE TITLE
Add sitemap for FreeCEN2

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#426]
Sitemap is very useful for tracking all of our pages (what's active) and user journey flow. Helps to identify 'blocks' and refine user experience. Original request via Denise/Rane

**Comment by richpomfret** [comment]
Option of creating this within Refinery. To investigate whether there is an easy way of automating this for any new page added (rather than have to manually update it every time a page is added).

**Comment by richpomfret** [comment]
@DeniseColbert could we also have specific examples of how a sitemap would be used by Rane? This will help when it comes to priority.

**Comment by smrr723** [comment]
Added a sitemap here - https://test2.freecen.org.uk/sitemap.txt - whilst working on Issue #511.

I've made it the same as FR for now - https://www.freereg.org.uk/sitemap_location.txt - but would recommend we add all pages on the site so will do this on deploy to production, and will also submit our new sitemap to Google via webmaster tools, in line with best practices here - https://support.google.com/webmasters/answer/183668?hl=en

**Comment by richpomfret** [comment]
Ready to be deploye.
