### ISSUE TITLE
Give Denise same level of 'Actions' as per FreeREG

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#427]
I don't have the full range of permissions I need in FC2-  e.g. Message System

E2, U6, S7, C9: P24

**Comment by richpomfret** [comment]
@DeniseColbert Now has manage user IDs but not all options currently available in FR.

**Comment by richpomfret** [comment]
Should now be live and complete. @DeniseColbert to check and sign-off.
