### ISSUE TITLE
Remove non-Adsense/AdExchange adverts from FreeCEN1

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#434]
FreeCEN1 is publishing old partners - we don't get any benefit  - adverts are on https://www.freecen.org.uk/UsageInfo.html

E2 U2 S3 C7: P14

**Comment by smrr723** [comment]
![screenshot 2019-01-22 at 22 14 22](https://user-images.githubusercontent.com/2768445/51569023-1e5dcb80-1e93-11e9-85f0-124fb2cccc08.png)

Just to clarify what needs removed @PatReynolds - are we talking about the 3 images shown above?  And do we want them replaced with an Amazon ad?

**Comment by smrr723** [comment]
Resolved & now live - https://freecen1.freecen.org.uk/UsageInfo.html
