### ISSUE TITLE
Switch name order to First name -> Surname

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#436]
I dislike the transposition of surnames and given names in your transcriptions, and the forcing of surnames to uppercase. I would prefer the names to be transcribed exactly as they are written in the original records.

**Comment by Captainkirkdawson** [comment]
The results are presented forename/ surname. We have always presented Surnames in Capitals to distinguish then from Forenames. There are many case where only one part of the name is present. Capitalization makes it clear which name part is being displayed
