### ISSUE TITLE
Preserve method of communicating updates to database

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#437]
I notice you are copying the format of your sister site FreeReg so my question/feedback is do you propose to keep the present update information format ie saying which pieces have been added in an update. FreeReg just say XXXX records added and you have to trawl through the list of parishes to find if any new records have been added to the area you are researching which can be very time consuming for a county which has a lot of records already in the database. Your current update list of pieces in an update is very useful in finding if your area of interest has been added to the database and I hope that you keep this method of update information.

**Comment by PatReynolds** [comment]
Has this been done, or is it still to be done?

**Comment by DeniseColbert** [comment]
This has been preserved (and enhanced) - done.
