### ISSUE TITLE
New chapman codes for OUC and OVF/OVB

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#44]
Out of county/ Overseas foreign/overseas british

**Comment by dougkdev** [comment]
The new codes were added, but user test needs to wait until in-progress
work on places (#27) is finished.

**Comment by dougkdev** [comment]
Birth counties will need to be handled differently than census counties

**Comment by dougkdev** [comment]
depends on #45

**Comment by FreecenBren** [comment]
Can this also include EWS.
This is the CHP we use for all the England and Wales Shipping.
This covers persons on Boats and Royal Navy etc that were in Ports during the Census.  I look after the 1861 census but there are other census years to do in time
Brenda


Sent from Samsung tablet


-------- Original message --------

**Comment by dougkdev** [comment]
Yes, EWS is already on there (in the "Special" section)

**Comment by dougkdev** [comment]
EWS and SCS only show up in the record transcriptions for census county,
not birth county, right?  And OUC/OVB/OVF only show up for birth county?

**Comment by FreecenBren** [comment]
Look on the link here to get an idea of what EWS census shows as regards Parish's covered.
 These Stats pages reflex the Parms for each piece.
So what we typed in the csv for each parms for each county x census year is what is shown here.
http://www.freecen.org.uk/coverage-EWS.html#1861

So EWS covers Ports for all the Counties not just one County like CON or DUR etc., The address can include the Port Name and Vessel
The Civil Parish can also be a Port or Town etc.. Can be Royal Navy or Merchants and will include Foreign ships if in port.

What we type in the POB columns are the same as normal census. 
I.e. Shows CHP and POB just the same.

OVF and OVB chapman code will then have a  POB  of one of these but it will say, France, Germany, Prussia, USA etc., etc all around the World.

The UNK Chapman code , the  POB, will show a place of birth but the County was not given so we use UNK .

Not all Chapman codes with have a POB, some will just have a hypen.

Hope that helps.
Brenda





Sent from Samsung tablet


-------- Original message --------

**Comment by dougkdev** [comment]
Thank you
