### ISSUE TITLE
Include Validators' manual entry of place name on Freecen2

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#442]
I noticed during a recent search on Freecen2 that the POB for a Margaret Gardner In Orwell Kinrossshire 1861 was given as Lanarkshire Moffat. When validating this parish I added a Validator's choice of Dumfriesshire Moffat (the correct county for Moffat). This information appears on Freecen1 correctly. Is there no facility to include Validators' choices on Freecen2?

**Comment by PatReynolds** [comment]
Just checking .... is this a transcription/validation process issue, or a research query issue, or a database structure issue?

**Comment by Captainkirkdawson** [comment]
Replace by #1312
