### ISSUE TITLE
Explain what has driven change from FC1 to FC2

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#445]
Would be helpful had there been an explanation as to what was driving the need to change and to this format.

Needs #550

**Comment by PatReynolds** [comment]
Draft Refinery page for review: https://docs.google.com/document/d/1SpGhDHuH_INIjozIeyRDT8Xe4S71jA758aolbVr_wAE/edit?usp=sharing

This will be linked from search page.

**Comment by richpomfret** [comment]
@DeniseColbert to also add this into feedback.

**Comment by PatReynolds** [comment]
Draft now on test2, sub-page of System Documents (unless anyone can think of a better place? @geoffj-FUG @DeniseColbert do you have any comments?  How do I put a link from the 'landing page' to this page?

**Comment by DeniseColbert** [comment]
I can't log in to test 2 to view. Raised a story.

**Comment by richpomfret** [comment]
Review still needed.

**Comment by richpomfret** [comment]
@Vino-S to take a look at the access issue on Refinery so this can move forward (we have another story for this 550).

**Comment by DeniseColbert** [comment]
In now (thanks Vino)

Have proofed and addresses a couple of styling issues (added paragraphs and bullet points to improve flow). Querying this line is correct?
![image](https://user-images.githubusercontent.com/19173257/51186587-dc041f80-18d1-11e9-9f55-ec0bd2caf36e.png)

This is now out of date: "The first test piece was transcribed in August 2018 and is with a Proofreader as of November 2018. We expect the piece to have been proofread and validated by the end of 2018."

"If you do give it a go, please give us feedback." How do we want them to do this? I could add a mailto link?

I've changed the 'FC flip' text to past tense.

**Comment by DeniseColbert** [comment]
Page finished, from my POV. 

@AlOneill is it in the 'right place' (system documentation)? 

@PatReynolds can you clarify the landing page you mean? (from your earlier question:  How do I put a link from the 'landing page' to this page?)

**Comment by AlOneill** [comment]
@DeniseColbert I am confused as to where this text is intended to go. I had thought it was to be added to the "About" page, but as I commented on the draft in GoogleDocs, there is a lot of volunteer-related info which may or may not be appropriate there.

So, in short, I don't know.

@PatReynolds How do you see this fitting with our current pages?

**Comment by geoffj-FUG** [comment]
Alison, Pat, Denise

 

If this is the document that I prepared I thought that it was to be used as part of the change management process. That is how I wrote it.

 

If that is so I would be sending every volunteer a copy.

 

Regards

 

Geoff

**Comment by PatReynolds** [comment]
Apologies - I got stories confused @geoffj-FUG is correct.  It has already gone in the Newsletter. 

This story has already been completed (i.e. there is an explanation on the About section). So moving to Needs Review (in case further work on About page is needed).

**Comment by DeniseColbert** [comment]
https://www.freeukgenealogy.org.uk/news/2019/02/06/how-do-freecen-changes-affect-researchers-and-volunteers?token=BKUpF2_dmhGPZb9ONMKsplwSUT~9lZr6

Needs proofing

**Comment by richpomfret** [comment]
@DeniseColbert to check the new version is correct.

**Comment by DeniseColbert** [comment]
Done, now live on FUG website in News section

**Comment by richpomfret** [comment]
It would appear some of the content in this has triggered a few strong reactions - we need to review in light of anything that might be miscontrued and aim to provide clarification where/if necessary. How we do this can be discussed. To discuss with @PatReynolds and @FreecenBren.

**Comment by benwbrum** [comment]
The rationale and clarifications have been provided.
