### ISSUE TITLE
Ability to sort results

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#446]
Is it possible to sort the results, perhaps by forename or other column? For example to list all the Ann Smiths together, which might include open a search of information about possible individuals who hadn’t previously come to your attention.

**Comment by PatReynolds** [comment]
Need to add instructions above the blue "i" that clicking will sort the results.

**Comment by Captainkirkdawson** [comment]
The sort is there. The info button has that information. Are you suggesting we adopt the REG approach? Its an additional comment under the number of results (The latter is missing in CEN)

**Comment by richpomfret** [comment]
Agreed to replicate what we do in REG (and clean it up while we are there).

**Comment by Captainkirkdawson** [comment]
Code has been modified for BOTH REG and CEN available on both test3s

**Comment by AlOneill** [comment]
Removing the `caption` element seems like a step backwards in terms of accessibility:

"The caption for a table is a table identifier and acts like a title or heading for the table.

"The caption element is the appropriate markup for such text and it ensures that the table identifier remains associated with the table, including visually (by default). In addition, using the caption element allows screen reading software to navigate directly to the caption for a table if one is present." (WAG guidelines)

This would be especially so if the info that used to be in the caption remains separated from the table by an advertisement. (Things that belong together should be close together.)

**Comment by AlOneill** [comment]
Think the first sentence under "n Search Results" would read better with an "a" inserted:
          Select [a] column heading of the table below to sort results on that column.

**Comment by Captainkirkdawson** [comment]
Revised test and positioning to make it logical.

Removed ad as it interfered with the flow of the page; **side ads are preferable**

Running on test3 CEN and REG

Dealt also with 762 and 767

**Comment by PatReynolds** [comment]
Working fine on Test3 (both CeN and REG)

**Comment by PatReynolds** [comment]
Font change to source sans pro, other wise good to deploy.
