### ISSUE TITLE
Search engine supports county of birth

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#45]

**Comment by benwbrum** [comment]
One question I have here is whether we should support County-of-Birth searches in a separate set of form fields from County-of-Enumeration as is done in FC1, or whether a generic "County" search on `CON` should match records in which CoE=`CON` `OR` CoB=`CON`.  

In general, I'm in favor of folding such things together when possible (as in FreeREG where "date" matches baptism or birth dates) to simplify the search form.  In this case I think I can see an argument for separating them, however.

What do you think, @FreecenBren, @PatReynolds, and @dougkdev?

**Comment by PatReynolds** [comment]
This is a question that #52 will answer.

Best wishes,

Pat

On Monday, 19 October 2015, Ben W. Brumfield <notifications@github.com>
wrote:

> One question I have here is whether we should support County-of-Birth
> searches in a separate set of form fields from County-of-Enumeration as is
> done in FC1, or whether a generic "County" search on CON should match
> records in which CoE=CON OR CoB=CON.
>
> In general, I'm in favor of folding such things together when possible (as
> in FreeREG where "date" matches baptism or birth dates) to simplify the
> search form. In this case I think I can see an argument for separating
> them, however.
>
> What do you think, @FreecenBren <https://github.com/FreecenBren>,
> @PatReynolds <https://github.com/PatReynolds>, and @dougkdev
> <https://github.com/dougkdev>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/45#issuecomment-149184087>
> .
>


-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by FreecenBren** [comment]
It has been requested that on the first search page under the  Census Year box, can we add a new box to enter the Birth County please.
