### ISSUE TITLE
Keyword search

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#453]
This has been suggested a few times, but not sure if this would be covered by the story for occupation search?

**Comment by richpomfret** [comment]
@DeniseColbert can we keep a log of the key words people are using or wish to use? If only occupation then yes, but no doubt other key words are coming up too.

**Comment by DeniseColbert** [comment]
We have a log, off the top of my head it's things like names of other possible household members; "visitor"; "blind" etc.

**Comment by DeniseColbert** [comment]
Does this still need more info? I think we would need to offer a field that searches for the inputted word across the records?

**Comment by PatReynolds** [comment]
More research needed on what is required.

**Comment by PatReynolds** [comment]
I have seen what's needed, and added them.  So this can be closed.

**Comment by richpomfret** [comment]
All other stories have now (we think) been created so closing.
