### ISSUE TITLE
Review Too Many Results text

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#458]
"Search result :
""Too many search results
Please refine (narrow down) your search.
Your 250 results exceeds our display limit of 250 to avoid overloading your device with too much information at one time.""
So ....... 250 is bigger than ..... 250?
"

**Comment by DeniseColbert** [comment]
Duplicate of #332 ?

**Comment by PatReynolds** [comment]
Agreed, duplicate so closing.
