### ISSUE TITLE
Include place of census (sub-district) search using standardised places (e.g. from GENUKI)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#459]
EG "I used to be able to search for Ashburton entries for 1891, but this does not seem to be possible now. Putting in just Devon brings up too many results."

Proposed way this would work
a) use a high level variant of place name in Pelagios (level of the Census Sub-District) in the drop down list, but do not put years in, as linked open data will be used to identify the districts to be searched - both those with that name, and those with other names in other censuses.
also
b) allow a free text search that looks for all records that might cover that name (Civil and Ecclesiastical Parishes, using Pelagios linked open data to identify the districts to be searched, OR use Pelagios to identify georeference, and run georeference against database.  
also
c) allow a street and house name search (free text) and run against database to find results, OR use Pelagios to identify georeference, and run georeference against database.

**Comment by Captainkirkdawson** [comment]
Overtaken by CSVProc
suggest this be closed
