### ISSUE TITLE
Possible Shaftesbury / Weymouth error

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#462]
If I search for Sarah Voss born Dorset in Dorset in FreeCEN2, household in 1841 says place=Shaftesbury but when you open it, civil parish is Weymouth - is that really right? Although the search on FreeCEN1 has Shaftesbury when you Show Household, it says Weymouth on the index result placing the emphasis on Weymouth which is more helpful.

**Comment by FreecenBren** [comment]
Hi Denise,
Your answer is in the details for the Piece number HO107295.
Look at the National Archives at this link

*Piece:* HO107/295/16 *Place:* Shaftesbury -Dorset *Enumeration District:* 4
*Civil Parish:* Weymouth *Ecclesiastical Parish:* Melcombe Regis
*Folio:* 16 *Page:* 25
*Address:* Melcombe Regis East Street

http://discovery.nationalarchives.gov.uk/details/r/C3761028

Then look at the Stats page at this link or in FC2 under manage Pieces.
These are what the PARMS file pick up from the NA

Details for all the Parishs in this PIECE number are below.

https://www.freecen.org.uk/coverage-DOR.html#1841

This is what it says for the 1841 Census.
The Place is Shaftesbury and the Ed names are all those in the *Comprising*
column below.
These Parishes match up with the NA Page.
In this instance ED 4 is Weymouth,

You will see that is the name at the top left hand corner of the image.
I can send you a copy should you need it.

1841
PiecePlaceComprising

HO107/295 Shaftesbury  Shaston Borough , Holy Trinity S James, Alcester ,
St Peter , Sherborne Town , Sherborne , Overcoombe , Pinford , Wareham ,
Holy Trinity , Stoborough , Middlesbere , Redge , Lady S Mary Within , Lady
S Mary Out , Worgrete , Wargate , St Martin Within , St

It is rather like a jigsaw puzzle. Get all the details together and it
should then all join up.

Hope that helps
Brenda

**Comment by richpomfret** [comment]
@DeniseColbert I don't think there is any action here on our part. However, we can use this as an example in documentation in order to help clarify places/locations over time (maps will help with this).
