### ISSUE TITLE
Ability to search without inputting county

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#465]
I find freecen 2 great if you can actually state the actual area, rather awkward if you don't know a certain county

E2 U3 S5 =???P18 based on estaate of 3

**Comment by richpomfret** [comment]
@DeniseColbert can we have more info? We can get it to work with 'all counties' selected, so unsure what they were doing to create the issue.

**Comment by richpomfret** [comment]
Discussed adding in a drop-down list of places which include cities e.g. Liverpool, London (and so on). To be reviewed as part of our work on Places.

**Comment by PatReynolds** [comment]
cf #459

**Comment by Captainkirkdawson** [comment]
One can search without a county for sparsely populated names
