### ISSUE TITLE
PARMS issue - Bideford

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#471]
From Brenda: 

We have completed Bideford in 1841, 1851, 1861, 1891 censuses

If you look on the search and select Devon then look on the list of places, Bideford only shows for 1861 and 1891 Census.

This is all PARMS connected

If you search for say 1841 Census and select Place: Bideford you get this message:

Place: Bideford -DEV (1861/1891) incompatible with year 1841
Please correct the above error(s) and try again

If instead of selecting Place you enter in the  CIVIL PARISH box and type Bideford then you will get a result in FreeCEN1

In FreeCEN2 however it will only let you select from the list and not let you type Bideford as a Place/Parish

**Comment by richpomfret** [comment]
Duplicate so closing.
