### ISSUE TITLE
105102717 Amended search cause fail  (Mark Young)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#472]
Issue reported by **Mark Young** at 2018-05-01 11:11:57 UTC
Time: 2018-05-01T11:08:57+00:00
Session ID: 923f0a1ee7b6c682471bda5e5c692bf1
Problem Page URL: []()
Previous Page URL: [https://freecen2.freecen.org.uk/contacts/new](https://freecen2.freecen.org.uk/contacts/new)
Reported Issue:
About 75% of the time I try to do a search on your Freecen2 site I get this meassge:

"We encountered a problem completing your request. Please resubmit. If this situation continues please let us know through the Contact Us link at the foot of this page "

I believe it also happens every time I try to do an amended search, like I go back, change the census year and click search. 

It is frustrating as I want to use Freecen2 but am forced to go back to 1 every time.    

![Screenshot](https://freecen2.freecen.org.uk/uploads/contact/screenshot/5ae84b7df493fd44d3f9b16b/_old_)

**Comment by DeniseColbert** [comment]
Have asked for more info on device, OS and browser.

**Comment by DeniseColbert** [comment]
I am running Windows 10 Home with all latest updates on a desktop PC. Accessing the site through Chrome Version 66.0.3359.139 (Official Build) (64-bit).

**Comment by Captainkirkdawson** [comment]
This is 1 year old; there is no current indication that there is any issue with revising a search. I propose it be closed

**Comment by benwbrum** [comment]
Pat remembers a similar problem which has been resolved since.  She will open a new issue if she encounters it again.
