### ISSUE TITLE
Comms Coord receives FreeCEN update reports

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#479]

**Comment by PatReynolds** [comment]
Available on FC1 - what else does Chris need?

**Comment by richpomfret** [comment]
@DeniseColbert can you clarify requirements for this one?

**Comment by DeniseColbert** [comment]
Am waiting to hear from Chris.

**Comment by DeniseColbert** [comment]
Chris would like to cut out the middle man I think, as he currently has to trouble Brenda for info. Is there something that Brenda gets that can also be sent to Chris?

**Comment by PatReynolds** [comment]
Brenda says all the info is on FC1.

**Comment by FreecenBren** [comment]
I only look at the FC1 STATS pages. Nothing is sent I just go online.

1. FC1 Project Page gives you the date of the latest upload.
https://www.freecen.org.uk/

It also gives you links to the following

2. Stats gives you the new total that is Online, also by Census Year and
each County and the new %.

https://www.freecen.org.uk/statistics.html

3. Recent additions gives you the list of new Pieces added at the update by
County and Census Year.

https://www.freecen.org.uk/recent.html

4. The Error report can be found at

https://www.freecen.org.uk/errors.html

Anyone can look at all of these. The COORDS all know where to find them
anyway.
Many helpers know as well.
I always did an email to the lists to let them know I had done the update
anyway and give details.

I keep a spreadsheet myself of the totals from one upload to the next.
I presume that Chris does something similar?

When Chris took on that role I used to send him an email after the update.
Sometimes I forget to send it him as I am often working on the Error report
or the issues that crop up.
The  information he needs though is there for him or anyone to look at
whenever.
It does seem a little odd that I send him details that are there for him to
pick up himself.
If he prefers that I send them to him I will set a reminder in my calendar,
no problem.

FC2 is different.

1. The STATS are there as per FreeCEN 1. This is the link.
https://freecen2.freecen.org.uk/freecen_coverage

2. We do not as yet have a Recent Additions report that anyone can look at
on FC2.

3. The “FC2 Error  Report” is a job in progress
Scott, Vino and myself are still working on getting the FC2 report more
user friendly.
At the moment it is a TXT report and is not ideal to send out yet.
We are working on the issues that are failing in FC2 as it picks up
different things that FC1 lets through.
When that is sorted and we stop getting these little issues then hopefully
the report will be more user friendly.

4. The upload totals do not always match exactly between FC1 and FC2 anyway.
This is an ongoing issue to do with what is counted on FC1 and what
 details are counted in FC2.
That is another story!

The FreeCEN 2 update is only done when I have done any major corrections in
FC1 and sent them to Lemon to update.
Then I let Vino/Scott know so they can update FC2.
Even then  the  2 reports are not always identical?

Hope that helps.

**Comment by DeniseColbert** [comment]
Thanks Brenda, if Chris knows where to find the stats there's no need for you to do the extra work of emailing him.

Closing.
