### ISSUE TITLE
Adverts are served and click-tracking works

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#48]

**Comment by PatReynolds** [comment]
The adverts are being served - is click-tracking functioning?

**Comment by dougkdev** [comment]
By click-tracking, do we mean the google analytics?  If so, it is a quick
(5 minutes) task.  I just need to know the google-analytics key for freecen
so I can embed it in the website header.  I will check with the others to
see who has access to the analytics account and can send me the key to
embed.  I'll go ahead and assign this story to myself as in-progress.

**Comment by PatReynolds** [comment]
Hi Doug,

Again, this was a straight lift from the FreeREG work plan - I had imagined
that it was something to enable us to get paid when someone actually clicks
on an advert, and then buys something.

Best wishes,

Pat

On Monday, 26 October 2015, dougkdev <notifications@github.com> wrote:

> By click-tracking, do we mean the google analytics? If so, it is a quick
> (5 minutes) task. I just need to know the google-analytics key for freecen
> so I can embed it in the website header. I will check with the others to
> see who has access to the analytics account and can send me the key to
> embed. I'll go ahead and assign this story to myself as in-progress.
>
> On Fri, Oct 23, 2015 at 7:37 AM, PatReynolds <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > The adverts are being served - is click-tracking functioning?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/FreeUKGen/FreeCENMigration/issues/48#issuecomment-150574796
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/48#issuecomment-151211741>
> .
>


-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by dougkdev** [comment]
In that case, it should be working fine since all of the projects share the
same advertising key.  I will move it to ready for user test.

**Comment by dougkdev** [comment]
Actually, we may need a separate client id and ad slot id since it is a
different URL.  I will look into it.  Back to in-progress.

**Comment by dougkdev** [comment]
Pat,
Do you know who has access to the AdSense account?  Like the analytics key,
I can easily change the AdSense client ID and slot ID in the code, but
whoever has access to the AdSense account will need to be the person who
creates the slot ID if we need a separate ID for each site.

**Comment by PatReynolds** [comment]
Hello Doug,

It is Ben Laurie.

Best wishes,

Pat

On Monday, 26 October 2015, dougkdev <notifications@github.com> wrote:

> Pat,
> Do you know who has access to the AdSense account? Like the analytics key,
> I can easily change the AdSense client ID and slot ID in the code, but
> whoever has access to the AdSense account will need to be the person who
> creates the slot ID if we need a separate ID for each site.
>
> On Mon, Oct 26, 2015 at 3:25 PM, Doug Kennard <doug.kennard@gmail.com
> <javascript:_e(%7B%7D,'cvml','doug.kennard@gmail.com');>>
> wrote:
>
> > Actually, we may need a separate client id and ad slot id since it is a
> > different URL. I will look into it. Back to in-progress.
> >
> > On Mon, Oct 26, 2015 at 2:57 PM, Doug Kennard <doug.kennard@gmail.com
> <javascript:_e(%7B%7D,'cvml','doug.kennard@gmail.com');>>
> > wrote:
> >
> >> In that case, it should be working fine since all of the projects share
> >> the same advertising key. I will move it to ready for user test.
> >>
> >> On Mon, Oct 26, 2015 at 2:32 PM, PatReynolds <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> >> wrote:
> >>
> >>> Hi Doug,
> >>>
> >>> Again, this was a straight lift from the FreeREG work plan - I had
> >>> imagined
> >>> that it was something to enable us to get paid when someone actually
> >>> clicks
> >>> on an advert, and then buys something.
> >>>
> >>> Best wishes,
> >>>
> >>> Pat
> >>>
> >>> On Monday, 26 October 2015, dougkdev <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >>>
> >>> > By click-tracking, do we mean the google analytics? If so, it is a
> >>> quick
> >>> > (5 minutes) task. I just need to know the google-analytics key for
> >>> freecen
> >>> > so I can embed it in the website header. I will check with the others
> >>> to
> >>> > see who has access to the analytics account and can send me the key
> to
> >>> > embed. I'll go ahead and assign this story to myself as in-progress..
> >>> >
> >>> > On Fri, Oct 23, 2015 at 7:37 AM, PatReynolds <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> >>> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> >>> > wrote:
> >>> >
> >>> > > The adverts are being served - is click-tracking functioning?
> >>> > >
> >>> > > —
> >>> > > Reply to this email directly or view it on GitHub
> >>> > > <
> >>> >
> >>>
> https://github.com/FreeUKGen/FreeCENMigration/issues/48#issuecomment-150574796
> >>> > >
> >>> > > .
> >>> > >
> >>> >
> >>> > —
> >>> > Reply to this email directly or view it on GitHub
> >>> > <
> >>>
> https://github.com/FreeUKGen/FreeCENMigration/issues/48#issuecomment-151211741
> >>> >
> >>> > .
> >>> >
> >>>
> >>>
> >>> --
> >>> *- -*
> >>>
> >>> *Dr Pat Reynolds*
> >>> Executive Director
> >>> Free UK Genealogy <http://www.freeukgenealogy.org.uk/>
> >>> A charity registered in England and Wales, number 1096940
> >>>
> >>> ​+44 ​1904 541411​ +44 7943 145387
> >>>
> >>> 36 Albemarle Road, York, YO23 1ER, UK
> >>>
> >>> —
> >>> Reply to this email directly or view it on GitHub
> >>> <
> https://github.com/FreeUKGen/FreeCENMigration/issues/48#issuecomment-151276049
> >
> >>> .
> >>>
> >>
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/48#issuecomment-151295798>
> .
>


-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by dougkdev** [comment]
Ben Laurie replied that the AdSense client ID and slot ID are the same for FreeCen and FreeReg, so no change is needed for the ads.  He provided me with a FreeCen-specific google analytics tracking id.  I have added it to the code and it will be ready for user test next time we update test2.
