### ISSUE TITLE
Remove 'volunteering' and 'registration' pages from FreeCEN1

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#481]
Remove Brenda's email address as well as the these pages.

**Comment by Captainkirkdawson** [comment]
Is there any more to do with this story?

**Comment by DeniseColbert** [comment]
@DeniseColbert to tell Vino what to remove

**Comment by DeniseColbert** [comment]
Brenda's email needs to be removed:

![image](https://user-images.githubusercontent.com/19173257/196633128-bd98603e-d670-4f5c-9bd9-123e2e358927.png)

Will look at County pages and have a think

**Comment by DeniseColbert** [comment]
Denise to provide text re data Problem directing to FC2

**Comment by DeniseColbert** [comment]
Denise to provide text and test changes already made on test.freecen.org.uk

**Comment by DeniseColbert** [comment]
https://test.freecen.org.uk/project.htm basically needs replacing wholesale, I will write the text. We must preserve the page via archiving or such.

**Comment by DeniseColbert** [comment]
Done so closing
