### ISSUE TITLE
Change scotland syndicate coord from Rena to Brenda

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#485]
New volunteers' who choose Scotland - email goes to Brenda

**Comment by smrr723** [comment]
That's all of Rena's syndicates in Scotland changed to Brenda now, but I noticed the "Accepting Transcribers" field is set to false for all of them.  Should this be set to true @DeniseColbert ?

**Comment by DeniseColbert** [comment]
No, we have no images to transcribe for Scotland so it should be set to false. I think there was some cross-over with volunteers choosing Scotland and the emails being sent to Rena, before the Scottish syndicates were set to false. Should be fixed now, cheers Scott :)

**Comment by AlOneill** [comment]
This strikes me as back to front! As there are no images for SCT, then surely the logical response is to set all the 'Accepting transcribers' fields to false, **not** to change the name of the Coord. As it happens, I believe Rena is stepping down as SCT Coord, but that is not the point here.

**Comment by FreecenBren** [comment]
I changed Margaret Singletons role to Scotland Syndicate Role at Rena’s
suggestion and request the other day.
It is still that way at the moment as I have just looked?

Not sure what else to change as Dougs names is still associated with a
Country Syndicates list?
Should I alter them as well?

Not amended anything else so confused even more now!

**Comment by DeniseColbert** [comment]
I think Brenda and I had our wires crossed, have emailed her for more info.

**Comment by richpomfret** [comment]
Done and closing.
