### ISSUE TITLE
Overseas place of birth policy

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#489]
For discussion (to be read in conjunction with current instructions): abbreviate all as OVF?  Continue OVB? TWYS (search using emendation list so Gibraltar finds Gib., USA finds United States of America, etc.?  a reason for abandoning OVB: https://en.wikipedia.org/wiki/History_of_British_nationality_law#Early_English_and_British_nationality_law shows it is very difficult to judge whether someone is, or isn't a British subject.

**Comment by FreecenBren** [comment]
We also have to take into account that some enumerators do actually enumerate entries as British Subject irrespective of where they were born.

We also get “Naturalised British Subject” as well, and they could have been anywhere in the world, Timbuctoo’ for example.

 

So not all those that say they were born in France, USA, Germany etc., are given an OVF as the Chapman Code, if the enumerator has added the codicil “British Subject” or  “Naturalised British Subject” etc.

 

Parents could have been working there, visiting etc., but registered the ‘Child’ in the UK on their return!

So it is not safe to assume that all those born “outside of the Commonwealth Countries list” are classed as OVF.

They could therefore be a “British Subject” or  “Naturalised British Subject” and therefore be OVB irrespective of where they were born!

 

A lot more to think about!

**Comment by AlOneill** [comment]
Yes, irrespective of the quality of the information, we still need a clear way to indicate that the person has been described as British, in addition to just stating their place of birth. Doing genealogy involves all kinds of judgement calls by the researcher.

**Comment by PatReynolds** [comment]
Comments posted on a different story, moved here:
Pat 11/7/2018 : Possibly remove OVB except for where person is stated to be British? Possibly remove OVB except for where country is known to be a British colony/dominion at the time of birth - or leave this for a Validation task?
Brenda replied same day: I would say that 90%+ of OVB are transcribed because the Enumerator added
the words British Subject.
Therefore the Transcriber would transcribe it AS IS.

The remainder would/should be picked up by the Validator.
Removing the OVB option would go against what we tell them to Transcribe AS
IS.
Leave it for the Validation Process is my preference.

**Comment by Captainkirkdawson** [comment]
The new validation process permits the inclusion of OVB and OVF for  COB and alt COB. There are presently no places in those "counties" but they can be added as needed cy coordinators

**Comment by richpomfret** [comment]
We have the policy now - closing.
