### ISSUE TITLE
Place of Birth: specify ordering?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#490]
E.g. specify that a place written Portishead Bristol should be transcribed as Bristol, Portishead - or that ordered name should go in the 'normalised' place name field?

E0 U6 S6 C7: P19

**Comment by FreecenBren** [comment]
Not quite sure about this example.
Portishead is in Somerset. It is about 10 miles from Bristol on the coast.
Bristol does not have a CHP as Bristol is a town and also in Somerset (Som)
Census state a County and a POB.
Can you clarify please.

Example:

We could use say instead as an example, Clifton, Bristol  as Clifton is a
Parish of Bristol.
The  POB can be either SOM or GLS as the Chapman code
Different 19th Century Census vary on which County as it boarders both.
The transcriber would enter the CHP code AS IS , as per the enumerators
recording!

So do we use Clifton, Bristol  or Bristol, Clifton in the 'normalised'
place name field?

**Comment by PatReynolds** [comment]
Thanks, Brenda, a better example!

**Comment by richpomfret** [comment]
Standardise smallest to largest place. To discuss with coords and establish which may be preferable.

**Comment by PatReynolds** [comment]
Geoff notes:
Pat, 
Kirk and I are working on the Place Names issues at the moment. It is going to take a while but we believe that we can come up with a workable solution.
We have established a Place of Birth protocol in the manual of Bigger to Smaller. So Bathpool Nr Taunton would be transcribed as is and then SOM Taunton Bathpool would be entered in the suggested place of birth fields in the spreadsheet by the transcriber.
In the master place names file you will find Bathpool as originally created from the Gazetteer. The validator will enter Taunton Bathpool into the alternative place field  in the master file and in the future all transcriptions containg Taunton Bathpool will pass validation. 
To take that further we could include international codes under OVF or OVB. 
Lets take we have a place such as Calcutta Bengal. We would transcribe it as Bengal Calcutta (larger to smaller). We would ensure that it exists (it did and it does), add it to the database as OVB Bengal Calcutta (it was a British Colony at the time), add the lat/long and whenever it crops up in the future the system will accept it. We would also add alternatives such as East Indies Calcutta (larger to smaller) so that it is validated in those cases too.
Geoff

**Comment by richpomfret** [comment]
Ordering now specified, so shall close.
