### ISSUE TITLE
Search crashes

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#491]
There are approximately 100 crashes per day of the FR2 search app
ActionController::UrlGenerationError
SearchQueriesController#create
23 Jun 2018, 08:40
Error message
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"search_queries", :id=>nil} missing required keys: [:id]

Error details
Filed tickets
Stack trace[Show framework code]
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"search_queries", :id=>nil} missing required keys: [:id]
…/freecen2/production/app/helpers/application_helper.rb:  201:in `google_advert'
/home/apache/hosts/freecen2/production/app/views/search_queries/_form_freecen.html.erb:194:in `_app_views_search_queries__form_freecen_html_erb__2477835353264903732_17357765060'
/home/apache/hosts/freecen2/production/app/views/search_queries/new.html.erb:14:in `_app_views_search_queries_new_html_erb__2173609002657814540_17357921340'
…roduction/app/controllers/search_queries_controller.rb:   72:in `create'

**Comment by smrr723** [comment]
@Captainkirkdawson what was the source of this error report, and is it still happening?  I can't see it on Errbit so assume it's from another tool or logfile?

**Comment by Captainkirkdawson** [comment]
The GET errors are visible in the passenger log. I believe that the specific GET issue for this which was raised last July may have been overtaken by events. However there are still well over 100 GET errors a day in the colobus log
Its a real pain tracking them down as the log is for both CEN and REG and is purely time stamped so hard to find where it originated. We really should spend more time looking at the log but there are only so many hours in a day
Most of them do not result in a red crash page for the user!  they can be a result of bot traffic!!

**Comment by smrr723** [comment]
Deployed to production.

**Comment by richpomfret** [comment]
@smrr723 to check fix in the log before closing.

**Comment by smrr723** [comment]
Can't see any errors similar to the above in the `passenger.log` on colobus, so the fix seems to have worked.
