### ISSUE TITLE
Parms can be used

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#492]
PARMS files contain metadata on (cencus) places and pieces. This is used as an authority file - giving the places to be searched - and for validation of data entered.
needs #195
needs #203

Ecomomic 0, urgency 6, strategy 6, cost 5: P19

**Comment by Captainkirkdawson** [comment]
The CSVProc uses the pieces for validation of a csv uploaded file.

**Comment by PatReynolds** [comment]
I have compiled a document on PARMS and placenames from a long email chain which developed in April 2020 - https://docs.google.com/document/d/10OVzCtZyY3NcVxShw6hnHRU8ezPz_oxPdAVuC2TZzPc/edit?usp=sharing - I have added some comments in and some questions - when we get to a decision on action I will create separate stories for those and copy or summarise their discussion/decision into the description.

**Comment by Captainkirkdawson** [comment]
I think it would be helpful to specify what decisions are required. It really is not clear.

**Comment by PatReynolds** [comment]
Good idea @Captainkirkdawson Have made new stories for the issues needing discussion and/or decision.

**Comment by Captainkirkdawson** [comment]
Suggest this be closed as we are evolving towards a fixed parms/piece structure based on TNA
