### ISSUE TITLE
Add CEN to ERRBIT

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#493]
There are no reports from CEN system crashes on ERRBIT

**Comment by richpomfret** [comment]
Looking into this. We think Vino may have this fixed - which means we should see error reports coming through IF there is a crash. Need to check.

**Comment by smrr723** [comment]
Tested and configured ok on local dev environment.  Will be live on FreeCEN2 production, test2 & 3 after running the update scripts for this sprint.
