### ISSUE TITLE
Donations page created, using existing Free UK Gen content as a basis

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#50]
Includes creating a Paypal button identifying that donations came via FreeCEN2 (Pat task)

**Comment by dougkdev** [comment]
I added the donations page in refinery (copied from FreeReg, changed
appropriate text to FreeCen).  It is currently using the FreeReg button.
When we have the button identifying FreeCen as the donation source, it can
be switched in refinery.

**Comment by PatReynolds** [comment]
Thanks, Doug.  I now have the new form of wording for GiftAid (the scheme
where we can claim the income tax paid by our donors), so can re-make the
PayPal buttons next week when I am back with a secure connection to Paypal.

Best wishes,

Pat

On Tuesday, 27 October 2015, dougkdev <notifications@github.com> wrote:

> I added the donations page in refinery (copied from FreeReg, changed
> appropriate text to FreeCen). It is currently using the FreeReg button.
> When we have the button identifying FreeCen as the donation source, it can
> be switched in refinery.
>
> On Tue, Sep 22, 2015 at 10:53 AM, PatReynolds <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Includes creating a Paypal button identifying that donations came via
> > FreeCEN2 (Pat task)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/FreeUKGen/FreeCENMigration/issues/50>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/50#issuecomment-151563178>
> .
>


-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by dougkdev** [comment]
Added the FreeCen-specific button from Pat to the donate page.  Users can
tick the checkbox to be sent to the paypal page for giftaid, or leave it
unchecked to be sent to the paypal page without giftaid.
Wording on the page is currently a copy/paste from the donate page on
FreeReg. It can be edited with refinery.
