### ISSUE TITLE
23 P - Discussion of CSI transcription importer tool

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#502]
CSI allows for Download as CSV (Excel) | Download as SQL | Download as XML | Download as JSON

E2 U3 S7 C?5: P22

**Comment by richpomfret** [comment]
@benwbrum what format is best out of the above?

**Comment by PatReynolds** [comment]
This is potentially another dataset for testing upload to FC2.  Do you want me to download as CSV, @Captainkirkdawson  and send you a link?

**Comment by PatReynolds** [comment]
Hi @geoffj-FUG saw this while looking for something else and wondered if it could be used by CSV-proc?

**Comment by geoffj-FUG** [comment]
Pat
CSVProc has settled with CSV files and that seems to be working well.
I think that your query is best suited to How we download Open Data requests. 
It is a technical issue that is best directed to Kirk.
I do not see it as much use to bread and butter researchers looking for family information. Their files are normally GEDCOM format if they want to upload the information to their trees. That becomes dangerous ground as people dont check, they just grab data and stuff things up. Best left alone or we will get the blame for wrong data.
Geoff

**Comment by PatReynoldsFUG** [comment]
Found this hiding in FreeCEN's "on ice" column, so moving to ComeTT

**Comment by PatReynoldsFUG** [comment]
Issue moved to [FreeUKGen/ComETT #29](https://github.com/FreeUKGen/ComETT/issues/29) via [**Zenhub**](https://www.zenhub.com/)
