### ISSUE TITLE
Listing of County and Country Coords on live is out of date

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#503]
Doug is given as the coord on many of them.  Needs copying from  list of syndicate coords (role holders are identical at the moment.  NB list of county cords on test2 is out of date.

**Comment by richpomfret** [comment]
@FreecenBren to move forward with this.

**Comment by FreecenBren** [comment]
I have updated what I could on both Test 2 and FC2.

 

It would not let me amend the following two.





I get this message.

 



 

I did report the following if you look in Feedback 114255810, 3rd one down.

The other 2 feedbacks relate to Duplicate Counties that one of each needs to be deleted.

 



 

If you look at  https://freecen2.freecen.org.uk/counties

 

I was able to amend them OK but looking at the top row it needs amending as that is copied from FreeREG, I assume.

Therefore does not relate to FreeCEN

Listing of all counties


County

County Coordinator

email address

Files

Total Records

Baptisms

Burials

Marriages

Action

 

Brenda

**Comment by smrr723** [comment]
@FreecenBren I get the same error - so it looks like a bug.  Have created a separate issue #522 to fix the bug first.

**Comment by smrr723** [comment]
Fixed bug #522 which was blocking this story, and removed dougkdev as Country Coord on test2 (replaced with CENManager account which goes to my email).  

@FreecenBren you'll be able to update the Country Coord on production after the update next week

**Comment by richpomfret** [comment]
Appears to be done, shall close.
