### ISSUE TITLE
Place Google Tag Manager code on every page of website

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#504]
IIUC, once the code is on the website, we will configure Tag Manager, and then we will need the existing analytics code to be removed.

Copy the code below and paste it on to every page of your website.
Paste this code as high in the < head > of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-PJP93GW');</script>
Additionally, paste this code immediately after the opening tag:

<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PJP93GW" height="0" width="0" style="display:none;visibility:hidden"></iframe>

**Comment by richpomfret** [comment]
@DeniseColbert can we have a summary or overview of why we're switching over to Tag Manager? Thanks :)

**Comment by DeniseColbert** [comment]
There are lots of benefits, the main one for us being less reliance on developer time to implement and manipulate tags. This is a decent article: https://moz.com/blog/an-introduction-to-google-tag-manager

**Comment by smrr723** [comment]
Tested this as part of other stories and would like to add it in soon, as I've figured it out now.  It's very easy for those with permission to change something (and therefore break something) on a site page, so we would need to agree on the correct process for changing stuff.

It doesn't have direct integration with Adsense but would be useful for Analytics and adding Analytics event tracking for form entry, and you can also use it to change the content/source of images.

So, it basically gives you access to "containers" or tags which you place on a page, and lets you put what you want in them, edit them etc (different analytics code, new image source, new text), which saves you having to update production code.

**Comment by richpomfret** [comment]
We need to keep in mind how tags play with cookie consent - do tags entirely replace our current GA code? There is 'some' info here in relation to how we ensure anonymous IP is switched on - https://www.en.advertisercommunity.com/t5/Google-Analytics-Code/IP-anonymization-in-Google-Tag-Manager/td-p/1688320

**Comment by smrr723** [comment]
Yep - the tag manager code entirely replaces our GA code.  Fields like `anonIP` can then be set on or off from the Tag Manager Admin control panel, which I have set by default.

Have gone ahead and created a FreeCEN2 container in our Tag Manager account - so will give it a run for stories #475 & #494 over the next few days.
