### ISSUE TITLE
Adsense ads responsive issues

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/FreeCENMigration#506]
Have spotted two ads which are not responsive:

1. Header ad across all pages (same issue as on FreeREG)
2. Square ad on Volunteering Opportunities page - https://freecen2.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen

The non-responsiveness is not due to the ad settings in the adsense control panel, it's due to incorrect CSS design of the ad containers.

needs #515 before home page change can be implemented

**Comment by smrr723** [comment]
Have made the banner ad on test2 responsive - to be tested and compared to what we have on live. Also needs tested with/without adblock, alongside issue #395

If the above looks ok, I'll add the same functionality to the other site ads. 

Note: a minor annoyance is that Google doesn't appear to support 'hot-reloading' of the ads if the window is resized after they load, i.e. they are only responsive to the page size when the page is loaded.  Not a huge issue since the majority of users won't be constantly resizing their browsers, but still would like to have this feature.

**Comment by PatReynolds** [comment]
If you narrow the window (e.g. so you can see two pages side by side, you get this:
![image](https://user-images.githubusercontent.com/6338822/45412751-5f390e80-b66f-11e8-9620-1631cb09404c.png)

**Comment by PatReynolds** [comment]
No advert showing on my mobile.

I'd expect it to come below the logo (which takes up the whole width of the screen - even 'menu' appears over the top of it.  Advertisement DOES appear right at the end.

**Comment by smrr723** [comment]
A couple of things on this - creating a custom solution to refresh the ads upon page resize is apparently against Googles terms of service, ad it could artificially inflate ad views.  The other thing is that actual page resizing in the wild is a very rare user behavior.  

For these reasons, the best solution going forward is just to set the ad to just not display if a user does resize the window, which will keep the page layout from breaking and keep us within Googles TOS.

More info on this here - https://productforums.google.com/forum/#!topic/adsense/Mdy90s_pXrM

**Comment by smrr723** [comment]
Have also tested this as much as possible on test2, on all banner ad units, which should now show on tablet devices and smaller laptops. Logo positioning on mobile also corrected.  On test2 with #395 currently.

The volunteering opportunities box ad will be changed on production, as it's in refinery.

No good solution for refreshing ads upon resize at the moment, but won't affect very many users anyway.

**Comment by richpomfret** [comment]
Banner ads look good on test2. No advert appearing at all (the box ad) on the volunteering page (768 x 1024 in 'ipad' mode), so this story should remain open until the necessary change has been made. Also appears to be a non-appearing box ad on the Help page, scroll down and it is on the right.

**Comment by richpomfret** [comment]
Looks like the ads are fixed on the Production volunteering page - not on TEST2 though.
