### ISSUE TITLE
Review FC1 Ad Strategy

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/FreeCENMigration#508]
There is a much higher CTR (click through rate) and therefore higher rate of earnings per user (approx 4x that of FC1) on FC2. FC1 still has the higher earnings though, due to a higher volume of users.

Actions I would suggest:-

1.  Review ad placements on FC1 (we either have too few ads, or they are poorly placed - it looks to be the former)
2.  Encourage migration from FC1 > FC2 with our own image ad, to benefit from the higher CTR on FC2.  Currently, we have a link pointing to FC2 which blends in with the other text, so new users may not notice it.

**Comment by PatReynolds** [comment]
Pat to circulate other options blog

**Comment by richpomfret** [comment]
Now signed up to Amazon. Blog circulated.

**Comment by PatReynolds** [comment]
Draft of new FC1 homepage: https://docs.google.com/drawings/d/1St3vAXSTIpYaa6X8sJkFOBCKeyLtkJCf6fFHWWjzuz0/edit?usp=sharing

**Comment by PatReynolds** [comment]
Other places proposed for adverts (in order of priority)
* Search page - suggest no additions
* Search results page - suggest below the previous and next household buttons.  Also probably need to add aadditional 'new query' and 'return to query' buttons above advert, as well as retaining them higher up the page.
* https://www.freecen.org.uk/statistics.html above the table (probably an Amazon banner, to reduce confusion)
* https://www.freecen.org.uk/recent.html above the table (probably an Amazon banner, to reduce confusion)
* https://www.freecen.org.uk/project.htm above the first table, and above the "How FreeCEN Works" table 

@FreecenBren what do you think?

**Comment by PatReynolds** [comment]
Hi Brenda, 
The bottom of the page will remain unchanged (from Search the database, etc, on down).

**Comment by FreecenBren** [comment]
Thanks that is good to know

**Comment by smrr723** [comment]
Layout & Amazon Ad Units for this are covered @PatReynolds, thanks.

The only thing I need is a pointer on where I can find documentation for contributing to FC1 since it's completely different to FR & FC2.  

This is the only technical page I've been able to find - https://www.freebmd.org.uk/addons/wincvs/cvs.html but I assume there is more than that somewhere @richpomfret ?

**Comment by smrr723** [comment]
@lemon-ukgen - I remember you mentioned that there was a minimal README file somewhere for contributing to FC1, but I can't find it on the server at all. Any ideas where it would be?

**Comment by Vino-S** [comment]
Readme document sent  to @smrr723
