### ISSUE TITLE
Change 'Blog' in footer to 'News' and point to https://www.freeukgenealogy.org.uk/news

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#509]
E0 U2 S4 C8: P14

**Comment by UTpH** [comment]
Hi!
This issue has been resolved right?

**Comment by DeniseColbert** [comment]
@UTpH No, it seems this still needs doing. The newly added 'Developer' label may mean that the person who takes this task on needs to be able to access our systems. @smrr723 can you advise?

**Comment by smrr723** [comment]
@DeniseColbert correct - needs to be a Developer and will need to be set up on cloud9 or have FreeCEN running locally after going through the instructions in https://github.com/FreeUKGen/FreeCENMigration/blob/master/CONTRIBUTING.md

**Comment by DeniseColbert** [comment]
Wondering if the GFI label is appropriate here, in that case?

**Comment by smrr723** [comment]
I think so @DeniseColbert  - it's still a Good First Issue for new volunteer developers.

**Comment by DeniseColbert** [comment]
Ah, so GFI + Dev = GFI for Dev. Gotcha 👍

**Comment by Captainkirkdawson** [comment]
closing as superseded by systemwide 112 and 115
