### ISSUE TITLE
22 P - Place link to Terms of Use page in Footer

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#510]
Needs #371
Economic 0, Urgency 8, Strategy 7, Cost 7: P=22

**Comment by PatReynolds** [comment]
Or perhaps "By using this site, you agree to our Terms and Conditions" in the bar, after "... County Record Office, local Family History Society or LDS Family History Centre." ?

**Comment by Captainkirkdawson** [comment]
Completed as part of systemwide
