### ISSUE TITLE
Ads on search page appear only some of the time, or not at all.

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/FreeCENMigration#511]
If you perform a search on FC2, the banner ad (not the one in the header) doesn't seem to appear most of the time.

I've checked our adsense account and the ad appears to be active, but it's been set to "Display Ads only", meaning that ads with just text won't appear, so if no image ads are available on the ad network it will just show as blank.  I suspect this is the problem, and should be set to "Text and Display Ads".

**Action**: change setting and test.

E4 U4 7 C?5: P20

**Comment by smrr723** [comment]
@PatReynolds @richpomfret 

Changed setting from "Display Ads only" to "Text and Display Ads", which seems to have done the trick.

Following a test with Rich, there are still times where some ads don't seem to appear - perhaps need an Adsense review to ensure we aren't targeting too narrow a demographic.

**Comment by richpomfret** [comment]
Labelled urgent and moved across into the sprint backlog - we can't have adverts failing on FC2, even if it's specifically adverts on the search results page.

**Comment by smrr723** [comment]
Have just discovered what is probably the cause - https://github.com/FreeUKGen/MyopicVicar/blob/freecen_parsing/public/robots.txt

We're not allowing bots to crawl the search page (including Adsense bots).  We are allowing this on FR, however.  https://github.com/FreeUKGen/MyopicVicar/blob/master/public/robots.txt

**Comment by smrr723** [comment]
Fix deployed on test2 - https://test2.freecen.org.uk/search_queries/5b719acde93790d1d34875a0

Looks to be working for me:-

![screen shot 2018-08-14 at 12 52 47](https://user-images.githubusercontent.com/2768445/44090154-178a703e-9fc1-11e8-99f1-fd745fe6317a.png)

**Comment by smrr723** [comment]
**Update:** Don't test yet please.  I've just found yet another two problems (third/fourth so far..) with this page - a bunch of code that looks like it was _meant to be_ removed, is still lingering there:

`      $(document).ready(function(){(adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-1788116026113570",
        enable_page_level_ads: true
      })`

..with the wrong Adsense publisher ID and for some reason, a whole page ad.  This is no doubt conflicting with the two correct ads we have on page.

The fourth problem I've just spotted is a couple of incorrect ad-slot-numbers embedded in the logic for rendering our ads on the search pages.

`  def google_advert`
 `   @data_ad_slot = ""`
`    case`
`    when current_page?(freecen_coverage_path)`
`     @data_ad_slot = "9056426667"`
`    when current_page?('/') || ('/search_queries') || current_page?(new_search_query_path) || current_page?(new_search_query_path(:search_id => @search_query))`
`      @data_ad_slot = "2003577939"`
`    when current_page?(search_query_path(@search_query))`
`      @data_ad_slot = "3316180679"`
`    when current_page?(:action => 'show', :controller => 'search_records')`
`      @data_ad_slot = "5173021979"`
`   end`

Not sure where these ad slot numbers are from but they don't exist in our Adsense account - 5173021979 & 3316180679 are both wrong, so definitely explains the blank ads. 

**Possible / Probable cause:**  Updating / Deleting Ads in the adsense account without informing the developers.

Not sure how any ads have appeared at all for me given the issues above.

Working to resolve the above now.

**Comment by smrr723** [comment]
Ad Managers' delivery tools seem to be for inspecting delivery of Adwords ads, as far as I can tell, so not much use for diagnosing the Adsense issue on this FC2 page, unfortunately.

**Comment by PatReynolds** [comment]
Multiple repetition of identical adverts seems to be how it works if our content is attractive to only a small number of advertisers: https://support.google.com/adsense/answer/32843?hl=en-GB
