### ISSUE TITLE
Place link to Cookie Policy page in Footer

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#512]
To allow ease of access for users who wish to change their settings.

Priority = 21: economic 0, urgency 10, strategic importance 3, cost 8

**Comment by richpomfret** [comment]
The lack of an easy option to find/change the cookie policy options is a bit of a concern - not sure if this conflicts with GDPR or not (a user must be able to change their settings) although I am sure there is a route to the page somewhere. It is, however, rather infuriating and an easy change i'm sure. This should be included in the footer for FreeBMD2.

**Comment by PatReynolds** [comment]
Seems to have been implemented in Great Merge.

Reference to .freereg2_session - does the refinery page need updating to .freecen_session ???

**Comment by richpomfret** [comment]
It's there so closing.
