### ISSUE TITLE
FC1 Move cookie banner to bottom of the screen

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#513]
Cookie banner currently covers the advert at the top  of the page and it is unclear for first time users how to proceed. Move to the bottom and check background colour on banner (it has appeared white within my browser and needs to standout).

e6 U4 S7 C6:P23

**Comment by smrr723** [comment]
Seems to be an issue with the FC1 production site not picking up the folder with the CSS files, but works fine on `test.freecen.org.uk` for some reason.  Have embedded the CSS into the HTML file for now which fixed the white/unstyled banner issue.

**Comment by smrr723** [comment]
Deployed to production - CSS files seem to be working fine now.
