### ISSUE TITLE
FC1 Add FC2 logo image on homepage

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#515]
To add in under the text that suggests users go and check out FC2. This will make the link more prominent and improve transition of people over to the new site.

Requires #514

**Comment by PatReynolds** [comment]
See #508 for draft layout.

**Comment by smrr723** [comment]
Added my version of this to live.

Separate issue, but I noticed on FreeREG, FreeUKGen and FreeBMD where we advertise each of our other websites, none of them are linking to FC2 - all point to FC1.  Should we not be pointing users to the newer site?

**Comment by PatReynolds** [comment]
Once we flip www.freecen.org.uk to FR2, all links will go to the correct site.  Except those pointing at freecen2.freecen.org.uk, which will need changing.
