### ISSUE TITLE
Mongo::Error::OperationFailure [rake#build:delete_search_queries]

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/FreeCENMigration#520]
See exception on errbit - https://errbit.freeukgen.org.uk/apps/5b633174e937903f2020c695/problems/5b639711e937906323369785

**Comment by smrr723** [comment]
Looking into this, requires further looking into but the cause appears to be the scheduled rake task which clears search queries is taking too long to process because it's trying to do them all in one go.  

It looks like the task has a parameter allowing you to limit the number of queries to clear per run, so this might be a possible solution.

**Comment by Vino-S** [comment]
It seems that the Sort by "c_at" field has timed out,  as it exceeded the mongodb in-memory threshold for sorting. 
We have an index in `c_at` field for SearchQuery collection. Having an index at `c_at` field should speed up the process, yet it failed.
The `getIndexes()` command in mongo shell, only fetched the default index(_id) field not the other indexes.
However I checked only in vervet not in production servers.
