### ISSUE TITLE
"Help" link on Navbar points to the wrong URL

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/FreeCENMigration#521]
"Help" on the navbar points here, which is blank - https://freecen2.freecen.org.uk/cms/information-for-coordinators

**Action**: Change link to point to https://freecen2.freecen.org.uk/cms/help

**Comment by richpomfret** [comment]
It does point to the right page, however it is placeholder and does not yet contain required info/links. Shall keep this story but change the title - please remove if it's a duplicate.

**Comment by richpomfret** [comment]
Closing.
