### ISSUE TITLE
Error when updating country coordinator

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/FreeCENMigration#522]
undefined method `empty?' for nil:NilClass - error given on errbit - 
https://errbit.freeukgen.org.uk/apps/5b63313de937903f2020c67f/problems/5b73f57de9379056f2d2e6de

Related to #503

**Comment by smrr723** [comment]
Caused by .empty? check returning a NoMethodError so have replaced with .blank? and corrected a few other errors.  

Fixed on test2 - will be deployed next sprint so should be able to remove `dougkdev` as Country Coordinator.

**Comment by FreecenBren** [comment]
Done
