### ISSUE TITLE
Rotate 'ad' messages

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#524]
Needs #395
Economic 4, Urgency 3, Strategy 3, Cost 7: P=17

**Comment by richpomfret** [comment]
Can you add more info into this story?

**Comment by DeniseColbert** [comment]
Sorry - I linked the wrong story. 

This is to (once #396 is done) have it so that the 'ads' rotate i.e. users don't see the same one twice in a row.

**Comment by PatReynolds** [comment]
Maybe use a different not-an-ad in each ad space, so that there is variety, and from time to time swap change the ones in the most seen positions.

**Comment by richpomfret** [comment]
Might be tricky to rotate (not impossible), so back-up plan is a good idea.
