### ISSUE TITLE
Add URL channels to Adsense & link Google Analytics Account

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/FreeCENMigration#526]
Suggestion to add URL channels to our adsense account, for page specific tracking, and also to link our Google Analytics account with adsense, for same reasons.

Currently, we can see how each individual ad unit is performing, but not by a clear breakdown of page.

This would be particularly useful for Issue #511 so we can compare a pages' performance against another's, and make appropriate changes when one is underperforming.

Economic 4, Urgency 3, Strategy 7, Cost 9: P=23

**Comment by smrr723** [comment]
Have added new channels to track different pages in FC2.  Google Analytics still to be linked, after some discussion.

**Comment by richpomfret** [comment]
@smrr723 anyupdate on this?

**Comment by smrr723** [comment]
Slight issue with this.  I didn't realise we had a separate analytics account for each of our websites.  Adsense only allows you to link one account at a time - and at the moment our FreeBMD analytics account is linked to our FreeCEN adsense account, which makes no sense.  

I'll have to firstly unlink the BMD account, which I seem to have permissions to do.  What I don't have permission to do is to complete the setup via Analytics (`Select FreeCEN2 > Admin > Property Column > Adsense Linking`).  @richpomfret are you able to either increase my permissions in Analytics or complete this step https://support.google.com/adsense/answer/6084409?hl=en&utm_id=ad&visit_id=636765796332926564-3324492529&rd=1

**Comment by PatReynolds** [comment]
Hi @smrr723 I am not sure what you mean by 'linked'.  Each site has its own code, and is separately managed through one institutional dashboard.  I've added permissions to FreeCEN (1) for you.

**Comment by smrr723** [comment]
Hi Pat - by 'link' i mean the ability to link the Adsense account of a website to its equivalent Analytics account (as mentioned in this story title), which will give us increased insights.

And thanks - that seems to have worked for FC1 but it's the FC2 one I need at the moment.

P.S. At the moment we also seem to have FC1 & FC2 websites bundled together in one Adsense account, but separated into two accounts in Analytics. We will have to change that in the future if we also want insights for FC1, i.e. by either creating a separate adsense account for FC1, or having both FC sites under one Analytics property.

**Comment by PatReynolds** [comment]
Thanks for the explanation.  I have given you permissions on the FC2 analytics account.

**Comment by smrr723** [comment]
Thanks, Pat.  That's Analytics & Adsense for FreeCEN1 & 2 linked, as of last week.  Hopefully, it'll give us some useful revenue insights over time.
