### ISSUE TITLE
22 P - Coord can review and correct errors and contents of pieces/vlds

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#530]
Needs #361
#36 merged into this story

**Comment by Captainkirkdawson** [comment]
This story as written combines 2 totally different collections into one. There are Pieces that essentially defines a census book.  Then there are VLDs that contain the transcription of the actual contents of a census book. They require totally different approaches. This story should be split into 2. 1) Deals with Pieces and 2) One that deals with VLDs
