### ISSUE TITLE
22 P - Coord can amend Place metadata (PARMS)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#533]
needed by #361

**Comment by PatReynolds** [comment]
If not changed by the Coord, what role can change?

**Comment by Captainkirkdawson** [comment]
I closed this as coordinators can amend pieces which are the contents of a parms file.
What is NOT clear is what are Places within the context of FreeCEN and how they differ from Census Districts which is what they currently appear to be or how they are managed

**Comment by PatReynolds** [comment]
Thanks, @Captainkirkdawson I thought that a PARMS file + transcriptions of a subdistrict in one census year = Piece.

**Comment by Captainkirkdawson** [comment]
In my mind that is a very dangerous connection as it leads to
miscommunication especially when we get to the point of having multiple
files of transcriptions each being a part of the census document

Kirk Dawson
Fairmont Hot Springs, B.C.
