### ISSUE TITLE
22 P - Coord can ammend non-place part of validation

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#534]
needed by #361

**Comment by geoffj-FUG** [comment]
A Coordinator can edit any field in a piece in CSVProc.
I am not sure what caused the issue here. It is not clear.
Geoff

**Comment by PatReynolds** [comment]
Thanks, Geoff, this is an old story part of listing all the things we wanted CSVProc to do (before CSVProc had a name), so closing now.
