### ISSUE TITLE
Announce change of Freecen url to FC2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#541]
Put notice on FC1, announce on social media

Needed by #138

**Comment by PatReynolds** [comment]
@DeniseColbert can you announce in Newsletter please, and put a 'something coming soon' on social media this week (or to go on sm while you are away?)

**Comment by PatReynolds** [comment]
@Pat to announce to volunteers

**Comment by DeniseColbert** [comment]
Do we have a timeframe? Will it actually happen when I'm away, or should I schedule a post for coming soon?

**Comment by PatReynolds** [comment]
Will check when the December newsletter will be out.

**Comment by PatReynolds** [comment]
Emailed coords and transcribers 1/12/2018.
Chris will put in newsletter with full details after switch (anticipated for the December upload).

**Comment by richpomfret** [comment]
@PatReynolds can you provide the 'notice text' for us to add onto FC1? I'll speak to Scott about putting that up today.

**Comment by PatReynolds** [comment]
The URL (website address) of this website will shortly be changing to freecen1.freecen.org.uk.  The URL www.freecen.org.uk will go to the FreeCEN2 website - there will be a link back to this website.

Is that OK @DeniseColbert ?

**Comment by DeniseColbert** [comment]
Yes that's fine I think

**Comment by richpomfret** [comment]
Thanks @PatReynolds @DeniseColbert. Can you add this text onto FC1 and replace the current text/advert we have for the FC2? I think the text will need to be a bit bigger so it is more legible - possible underline the 'FreeCEN is changing' bit and see how it looks..
