### ISSUE TITLE
Update and make live the 'About' page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#543]
Information about the drivers for change has been added on test3 - for expansion/correction and making live

E0 U3, S10, C7: P20

**Comment by AlOneill** [comment]
Looking on test **2**, the markup needs some attention (no container for list items): will fix and then review other details.

**Comment by PatReynolds** [comment]
May have already been done?  On Live?

**Comment by AlOneill** [comment]
Have just noticed a messy confusion of tenses  — will fix today.

**Comment by AlOneill** [comment]
Ended up tweaking quite a lot of the text in the end: updated version on test2 (select About from main menu), older version still on live.

**Comment by richpomfret** [comment]
@DeniseColbert to take a look/review.

**Comment by richpomfret** [comment]
To review versions on TEST3/Live and see which is preferable @DeniseColbert @AlOneill

**Comment by DeniseColbert** [comment]
I think live has the best version. Differences are minor but live is a bit of an easier read.

**Comment by richpomfret** [comment]
In which case, these changes on live also need to be on TEST3 or we risk the old version moving over onto 'live' when an automated update takes place.

**Comment by DeniseColbert** [comment]
Done, can be closed.
