### ISSUE TITLE
FreeCEN2 image on FC1 is out of alignment with the box

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#547]
![image](https://user-images.githubusercontent.com/19173257/48712221-23896a80-ec05-11e8-857e-3190e296be1a.png)

E3 U3 S9 C8: P23

**Comment by smrr723** [comment]
What browser (& version) / device are you using, Denise?  OK on Chrome, Firefox and Safari for me.

**Comment by DeniseColbert** [comment]
Chrome here. Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by richpomfret** [comment]
Appears to be resolution related and not browser.

**Comment by smrr723** [comment]
Should now be fixed @DeniseColbert

**Comment by DeniseColbert** [comment]
Yes, fixed. Thanks Scott.

**Comment by richpomfret** [comment]
Looks good to me too.
