### ISSUE TITLE
Put out request for more coords

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#549]
Perhaps in newsletter?

Needs #377 

E3 U3 S8 C8: P22

**Comment by DeniseColbert** [comment]
This awaits the Info for Coords documentation but in the meantime, we're going to approach Coords about training up helpers to the role (and also proofers & validators)

**Comment by richpomfret** [comment]
Draft email being prepared to cover this.

**Comment by richpomfret** [comment]
Request has gone out!

**Comment by richpomfret** [comment]
Discussion on aim to recruit more proofreaders (and transcribers), with opportunity to train people up as proofreaders who may then eventually move onto becoming validators etc.

**Comment by edickens** [comment]
FreeREG needs them as well.

**Comment by richpomfret** [comment]
Looks like this is complete in terms of putting out the request. Shall create new story to cover other discussion on recruiting more proofreaders etc.
