### ISSUE TITLE
Tablet users supported

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#55]

**Comment by PatReynolds** [comment]
Issue a copy-and-paste from FreeREG2 roadmap - is this needed for FreeCEN2?

**Comment by PatReynolds** [comment]
This issue was copy-and-pasted from an early FreeREG2 roadmap. Do we still want this as an issue - or is this covered by smartphones?  Or is it the question Kirk and I were discussing on FreeREG (i.e. do we give tablet users the choice of desktop or mobile interface?)

**Comment by sean-wood** [comment]
Sean to test on ios device
