### ISSUE TITLE
Add Amazon to FC2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#552]
Needed by #258

**Comment by richpomfret** [comment]
Conversation on the slack sprint channel for this.

**Comment by smrr723** [comment]
I think the Amazon login issues have been resolved now and Pat has access again.  

Have we decided where the new Amazon / Audible ads are to be placed?

**Comment by richpomfret** [comment]
Any update on this one @PatReynolds?

**Comment by benwbrum** [comment]
Quoth @PatReynolds: "No."

**Comment by PatReynolds** [comment]
Tried to sign in 29/5 - Amazon are working on website 'come back later'.

**Comment by richpomfret** [comment]
Closing as per plan for new advertising partnership/strategy.
