### ISSUE TITLE
Archive rootsweb transcriber group content

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#559]
Move across what we can or what might be useful for transcribers (old and new).

E0 U6 S7 C7: P20

**Comment by DeniseColbert** [comment]
Pat's idea for this was to go to the Internet Archive and screengrab what's there in case historical information is needed in the future.

Contact Coordinators to see who has meaningful info still on RW, but do this anyway as there may be Coords who are no longer with us that we may need the info for.

**Comment by DeniseColbert** [comment]
Ancestry are now removing Rootsweb so this is now urgent

**Comment by DeniseColbert** [comment]
Done, nothing came back to us so closing
