### ISSUE TITLE
Other places to change the URL

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#560]
* Information for Digital Inclusion trainers
* our websites

Needs #138

**Comment by DeniseColbert** [comment]
Is this something that needs/can be changed? https://www.freecen.org.uk/sitemap.txt

Other than this, all done.

**Comment by richpomfret** [comment]
@smrr723 to update the text file.

**Comment by smrr723** [comment]
Sitemap updated - (will merge code before the update).

**Comment by DeniseColbert** [comment]
This is fine- closing
