### ISSUE TITLE
Remove volunteer link from FC1

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#563]
Remove text on volunteering page ("How to Volunteer

You can contact the  individual COORD from the County list above. 
Alternatively please contact Brenda Bowers") and replace with '"
To find out more about volunteering, and volunteer to help please visit the sign up page on FreeCEN2: https://www.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen"

Needed by #481

**Comment by smrr723** [comment]
@PatReynolds the new text you mention - "To find out more about volunteering, and volunteer to help please visit the sign up page on FreeCEN2: https://www.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen" appears to already be on the volunteering page.  

Can you clarify if the page still needs editing?
