### ISSUE TITLE
FC2 Cookie Banner update

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#564]
As cookies will no doubt need to be refreshed upon the URL change (to check), this is an ideal time to:

a) move the cookie banner position from top of the screen to the bottom and 

b) double the size of the banner (see freeukgen site as example).

**Comment by richpomfret** [comment]
@smrr723 do you think this is still necessary for the switch? Would still be GOOD to have either way.

**Comment by smrr723** [comment]
Not necessary, but I've added it anyway since I'm doing a production update - so will be live later today.

**Comment by smrr723** [comment]
Now in production.

**Comment by richpomfret** [comment]
Moving to done.
