### ISSUE TITLE
Almost none of the system performance tools work.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#569]
Myopicvicar has system administrator  tools to measure and monitor system and search performance. These tools are essential for the ongoing maintenance and future development of the application. These tools do not currently work on the CEN branch.
The first step in addressing this is to respond to issue #1339 on FR and deploy the master code updates into the CEN parsing branch

3/6/7/4 = P20.

**Comment by richpomfret** [comment]
Thanks @Captainkirkdawson shall use this as an epic and then create substories for each tool.
