### ISSUE TITLE
23 P - Move censfaq to FC2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#571]
Currently at https://freecen1.freecen.org.uk/censfaq.htm

**Comment by PatReynolds** [comment]
For index section of this page, follow the style used on https://www.freecen.org.uk/cms/help (code in refinery will show how this is achieved).

**Comment by AlOneill** [comment]
@PatReynolds David Housman (who has been asked to make a sub-menu (index) on this page has asked for more details. So I took a look at the original page on FC1.

The questions are mainly to do with IN-CENS: the original input app that I don't think is used by transcribers any more.

There are also a couple of sections on CHECK-CENS and VAL-CENS, for proofreaders and validators: I believe these are used by some, but by no means all.

I seem to remember another FAQ page (somewhere!) that concentrated on what/how to enter rather than how to wrestle with IN-CENS.

The page is set out using tables for layout and lots of other markup clutter. Do I clean it up first? (Not sure what David is comfortable with — awaiting his reply.)

How to proceed?

**Comment by AlOneill** [comment]
@PatReynolds David is not comfortable with de-cluttering the markup, so have done that myself. Neither is he familiar with FreeCEN.

**However**, even the cleaned up page is **too long to be saved in Refinery**.

I can think of some approaches for reducing the page length:
* There is some effective duplication of information: it is difficult to tell exactly how much as the 180-odd questions are in random order — similar questions *are* linked together in 24 daisy-chains, which is charming but not the most helpful approach for our needs!
* Some of the questions relate purely to (wrestling with) IN-CENS; some are of the "what do I put where" kind; others are mixed, with elements of each. We could thus separate the questions (and parts of questions) into two groups, IN-CENS and general.

I propose to proceed by grouping the questions by subject (i.e. by daisy-chain) to get a better sense of just how much duplication there is.

**Comment by PatReynolds** [comment]
Goodness, it is big.  Your suggested process sounds good.  Maybe ignore INCENS entirely, since it is redundant.  Also, a task for a new volunteer, I think (but one very familiar with the project's history and previous tools).

**Comment by AlOneill** [comment]
Except that there must be some overlap between IN-CENS and WIN-CENS — the latter is still in use by some, I believe.

**Comment by FreecenBren** [comment]
Regards INCENS.
 
I have written to the COORDS and there replies are as follows
 

COORD
REPLY

Beki
None

Bev
None

Carol
None

Dave
None

Geoff
None

Ian
Waiting reply

John
None

Myself
None

Neil 
None
 
Ian was a COORD after INCENS was replaced so I will assume none for him as well.
It is therefore safe to assume that we do not have any transcribers using INCENS.

**Comment by geoffj-FUG** [comment]
There is a FAQ section in Appendix G of the Handbook.
They are things that came up as we implemented the transcribing for CSVProc during test, plus things that were obvious questions if someone doesn't read their Handbook.
It seems to be stable, but implementation will tell.
Is this of any help?
Geoff

**Comment by PatReynolds** [comment]
https://freecen1.freecen.org.uk/censfaq.htm
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/ff56fc51-1897-423e-ba59-4e4928d1a0ee)
Have put these in a spreadsheet: https://docs.google.com/spreadsheets/d/1uxU6pkBEQKPRsNGHm1RSV_sheT_DO9HN0jHfajPLpEM/edit?usp=sharing

For most, decision on what (if anything) needs to be preserved post-shutdown of FreeCEN1 transcription and uploading, needs to be undertaken by Geoff.

**Comment by geoffj-FUG** [comment]
Pat

 

This is old. It refers to Incens which was floppy disc based.

 

I joined the project about 2004 and it was old technology then.

 

I have put my notes in column E

 

Geoff

**Comment by richpomfret** [comment]
@PatReynolds to review comments/notes.

**Comment by PatReynolds** [comment]
Thanks to @geoffj-FUG for his comprehensive review.  I have actioned those elements identified by Geoff as needing action by someone other than himself, so takingmyself off this story now.
