### ISSUE TITLE
Change advertiser (was change product category for Amazon)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#572]
We have had 180 clicks, but no purchases on the Amazon advert (1/12/18 to 18/1/19) so need to change the offer.  Audiobooks, perhaps?

**Comment by PatReynolds** [comment]
Haveing successfully changed our  password, Amazon now denies we have an affiliate account.

Therefore have begun to set up Blackwells as an advertiser for this slot (longer term we were planning to use them on FUG.org.uk to advertise individual books, alongside using Worldcate). Not sure what category to sign up for, so emailed them 4/2/2020.

**Comment by PatReynolds** [comment]
Signed up for Blackwells 5/2/2020, awaiting approval.

**Comment by PatReynolds** [comment]
Account approved, advert selected and sent to Vino for inclusion in FreeCEN1 in place of the Amazon Advert.

Should we also replace the Adsense advert at the bottom of FreeCEN2 search page?

**Comment by Vino-S** [comment]
ready to be tested:
https://test.freecen.org.uk/

**Comment by PatReynolds** [comment]
Thank you, @Vino, that works fine.

**Comment by Vino-S** [comment]
Thanks @PatReynolds , deployed to live
