### ISSUE TITLE
23 P - Review statistics provision

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#577]
Following the Great Merge, review statistics available and make stories for those needed.

Needs freeukgen/myopicvicar#1339

Currently (pre great merge) available:

On test16:
site statistics (number of searchers/time)
% last name vs all searches
% first name vs all searches
% max results vs %no results vs all searches
% all (birth?) county searches vs all searches
% date searches vs all searches
% specific year vs all searches
 % place (district), % place+nearby vs all searches
searches total (for last 9 days)

Site Statistics
Interval end	Year	Month	Day	Number of records	Number of searches	Number of records added
Not working (last worked 2017-05-19 on live site) - Make story

Search performance reporting
Not working. - Make story

Available on FC1
The number of searches that produced a result. - available on FC2
The number of searches could not be performed because the server was busy, resulting in the Server is busy message - not available on FC2  - add issue (low priority)
The number of searches that had to be terminated because they were taking too long (available on FC2)
The number of searches that were not started because the search was too complex (and would therefore have taken too long) Not applicable to FC2 because process of weeding out searches and not running them not available does not exist.

E4, U6, S7, C6: P23

**Comment by richpomfret** [comment]
Be very useful to compare search stats between FC1 and 2.

**Comment by richpomfret** [comment]
@PatReynolds to check on smaller stats stories created and create a suitable stats epic to order them by.

**Comment by PatReynolds** [comment]
Reviewed, epic ("the Statistics Epic") created and stories added there.  Closing as agreed in meeting.
