### ISSUE TITLE
TEST2 logo/ad issue

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#578]
Not experiencing on production

**Comment by DeniseColbert** [comment]
![image](https://user-images.githubusercontent.com/19173257/52355317-0ad16980-2a2a-11e9-86c4-24d45cd03e10.png)

**Comment by smrr723** [comment]
My bad Denise - I was switching branches in git on test2 and forgot to recompile assets to update the CSS.  Should be fine now.
