### ISSUE TITLE
Access to transcriber stats by county

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#584]
Brenda requested this. May be good for others to have access too.

E0 U6 S7 C?8: P21

**Comment by Captainkirkdawson** [comment]
Being dealt with in the site statistics and county drill down.
Also CSV files are associated with the transcriber
Is there more if so it should be added to the requirements that those actions are doing. 
This should be closed

**Comment by PatReynolds** [comment]
Agreed and closing.
