### ISSUE TITLE
22 P - Implement all needed actions for Coords (was Enable Coords to download updated PARMs Files (Some (possibly all) Coords do not have option to Edit Pieces in county pages of Database Coverage page - where download is)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#586]
Brenda believes that Coords need to be able to download PARMS.DAT files that have had corrections made to them.

Coords should have 'download parms file' button.

E 0, U 6, S 8, C8: P22

**Comment by DeniseColbert** [comment]
Some coords report not seeing this option:

![image](https://user-images.githubusercontent.com/19173257/52854248-ca52a980-3115-11e9-9d08-567e1d1fa128.png)

**Comment by richpomfret** [comment]
To provide 'download parms' link for all coordinators rather than 'edit..' (the latter is only accessible to Brenda).

**Comment by PatReynolds** [comment]
The name of the link (in Actions) is "Manage Pieces".

**Comment by Captainkirkdawson** [comment]
This will be replaced by the fixed parms structure using TNA information. Only questions will the be a need for a download of a county parms file

**Comment by PatReynolds** [comment]
In tne new system, if an error found in published record(s), corrections will be made at the Piece level, rather than the County level, so closing.
