### ISSUE TITLE
Challenge the idea that 'almost all' features have been removed

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#590]
Why have nearly all the features been removed?
FreeCEN2 seems to have 90+% of the features of FreeCEN1 removed.

**Comment by DeniseColbert** [comment]
See email PDF re. this story from Brenda.

**Comment by PatReynolds** [comment]
Still needed?

**Comment by richpomfret** [comment]
@DeniseColbert to note recent update in FC2 feedback form. Newspost a month ago also helped with this in terms of communicating recent changes.

**Comment by DeniseColbert** [comment]
Added new features to form, and updated news post with them too. Closing.
