### ISSUE TITLE
Not clear where Overseas births can be selected

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#596]
They are in 'Special' section of dropdown menu, but this is unclear to users. Possibly as it's right at the bottom of the list?

**Comment by FreecenBren** [comment]
It was suggested that the birth County search list was changed to strict
alphabetical instead of by Country/Special etc.

**Comment by DeniseColbert** [comment]
Potential Machine Learning task to go through Notes and pick up e.g. USA

**Comment by DeniseColbert** [comment]
Change the Hint that Overseas births are in the Special section at the bottom of the list.

**Comment by PatReynolds** [comment]
This is, I think, resolved as OVB and OVF are present in the place of birth drop down

**Comment by Captainkirkdawson** [comment]
Neither of the suggestions has been actioned nor discussed/rejected

**Comment by PatReynolds** [comment]
It works for OVB (search for Jane Lamb, OVB place of birth, census county Nottinghamshire finds two entries (1851 and 1861).
It works for OVF (search for Murphy -surname only - OVF place ofbirth, census county Nottinghamshire finds three entries but not the one I had anticipated (edit to add, he turns up as born Ireland, of course).

Ah, my mistake in reading the action proposed in the story!

**Comment by AlOneill** [comment]
@Captainkirkdawson The county tooltips are good, except that the birth county one needs a bit of a tweak of the middle part for case and punctuation. Also, "including" works better than "includes".

I suggest that the birth county tooltip would be better as:
`<small>These are grouped into sections for England, Ireland, Islands, Scotland, Wales and a Special category (including overseas, out of county, ships and military). If you select more than one county, <em>all</em> places within those counties will be searched</small>`

@All For the "Help", I suggest re-iterating and expanding on the order of the sections in the select boxes.

Do we want to explain how to use repeated key presses to cycle through all counties beginning with the same letter or is that too basic an internet skill to be worth mentioning?

[As for putting the counties in strict alphabetical order, whilst it could help some users, it could disorientate others as information — the section name — would be lost.]

**Comment by PatReynolds** [comment]
I agree with  your suggestions, @AlOneill

**Comment by Captainkirkdawson** [comment]
@AlOneill thanks for picking up the punctuation error. Change made on test3. I agree that some reordering of the text in the Help would be logical; I kept my edits to a minimum as I do not like to play with the structure.

**Comment by AlOneill** [comment]
@Captainkirkdawson, thank you for fixing the tooltip text.

@All, edits to Help in progress offline.

**Comment by AlOneill** [comment]
Is it me or does anyone else find this paragraph troubling? "You can also select a Birth County, but only counties that have been transcribed are displayed."
So, I cannot choose a _birth county_ in the search form unless that county has transcriptions, which is surely not necessary as long as the _census county_ has transcriptions?

**Comment by PatReynolds** [comment]
I think "troubling" is putting it a bit mildly.

More than troubling - I think it is just wrong.  The county pob list seems to be  the whole county list, which also  includes such things as "Military Locations" (checked and no Smiths born in a military location were found but there might be an entry ....).  Perhaps replace with "You can also select a Birth County. Places of Birth which are outside the counties of the British Isle are listed at the bottom". I can't find where this text actually is so my suggestion may be inappropriate.

**Comment by AlOneill** [comment]
@PatReynolds The information you are looking for has been added (not by me) to the draft version of the "Help" page:
https://test3.freecen.org.uk/cms/draft-help#birth
It looks misplaced — perhaps it was intended for the 'Census county' information?

I agree that that all possible counties appear to be in the 'Birth county' select box

**Comment by AlOneill** [comment]
[DRAFT Help](https://test3.freecen.org.uk/cms/draft-help) returned to Refinery and is ready for review.

NB the DRAFT also addresses #367.

**Comment by Captainkirkdawson** [comment]
@AlOneill I have no problems with the draft TY

**Comment by Captainkirkdawson** [comment]
Tooltips change has been deployed.

**Comment by Captainkirkdawson** [comment]
Help deployed
