### ISSUE TITLE
Multi-server deployment

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#60]

**Comment by dougkdev** [comment]
As indicated in email threads and discussion during the last scrum, there were concerns about possible performance impacts to FreeReg when building the production deployment database. Kirk and I did some initial tests to measure impact while building small parts of the CEN database on the production servers. The measurements indicated that the impact was small enough to be acceptable. I went ahead and started the full build and we continued to measure it. After a few hours, the impact continued to increase (response time had risen from 3 sec to 9 sec). Kirk determined it had reached an unacceptable level, so we stopped the Cen deployment build.  We will instead use a method similar to the one Kirk is planning for the Reg rebuild next week. This story is on hold for a couple of weeks until the next scheduled Freecen build slot.

**Comment by dougkdev** [comment]
We have deployed to freecen2.freecen.org.uk but have not yet thoroughly tested the deployment.  Before opening to the public, there are some performance issues that we need to look into (response times are slow), and we need to fix #156 and test all functionality more thoroughly.
