### ISSUE TITLE
Printing issues

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#600]
This is all the info we have here, with no contact details to get more. Not sure what they mean...

"A big black logo on some pages, makes printing difficult. Clear white page would be better. Bottom of 1st page of census data 1841, 1851 data written on top of each other. Unable to read or print out clearly."

**Comment by helhyde** [comment]
This sounds like an issue we had a while back on FreeREG.  Probably fixed
there, and not (yet) on FreeCEN.

**Comment by PatReynolds** [comment]
Printing now works fine on Chrome and Firefox, so closing as almost certainly now working on all browsers.
