### ISSUE TITLE
Gold text (e.g. hyperlinks) are too pale to read

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#603]
Please make the "pale orange" text darker or bolder as it is hard to read in a semi bright room

Is there a quick/easy way to make all links bold or is it best to wait until accessible colours are implemented?

**Comment by DeniseColbert** [comment]
More:
* The orange lettering is difficult to read. it has been found that most people only get interested in their family history about the age of 55. At that age eyesight is much poorer and requires more light. Even on a 22" screen I can barely read the orange print.

**Comment by richpomfret** [comment]
This should be resolved by the new accessible colours - @AlOneill what do you think?

**Comment by AlOneill** [comment]
@richpomfret Yes, will be fixed by new colours.
