### ISSUE TITLE
Ability to put a letter in the county to 'jump'

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#607]
Could use the ability to put a letter in the county area so we don’t have to scroll so far. The old one allows it and is really helpful.

**Comment by richpomfret** [comment]
You can already do this. However, I noticed that there appear to be a few conditions where this stops working - not quite clear why this is the case (perhaps there's a bit of a lag if you do it to much?).

**Comment by Captainkirkdawson** [comment]
It works as expected. closing
