### ISSUE TITLE
Make error text easier to understand

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#609]
I am having difficulty finding an ancestor which I found before. There are no results but what is frustrating is the language used to tell me why. I do not understand eg 'A Place must have been selected as a starting point to use the nearby option.'

**Comment by richpomfret** [comment]
We might want to review our text here, or consider adding more pronounced links or breadcrumbs to search FAQs in order to help users understand what the language means.
