### ISSUE TITLE
The new site doesn't seem to show everyone in the same household.

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#610]
Quite a few of these, not sure how to test?

**Comment by FreecenBren** [comment]
This has happened before and it related to an error in the file for FC1
where all the occupants were all as one person households.
It was corrected and re uploaded.
It is one of those that I really need to know the Piece number to correct
it if it has not already been done.
Do you have that information?

**Comment by richpomfret** [comment]
We need to have specific examples here or test cases.

**Comment by geoffj-FUG** [comment]
If this is an 1841 issue then it is related to teh schedule number 0 problem. This problem is affecting both vld download and the display of vld search results to researchers.
Geoff

**Comment by geoffj-FUG** [comment]
Does this problem still exist? The rewriting of the code that identified the break between households has been re-written and has removed several anomalies. This issue may also have been fixed by this re-write.
Geoff

**Comment by geoffj-FUG** [comment]
The 1841 breakup problem has been resolved.
I have not come across the problem elsewhere.
I think that this issue can be closed.
Geoff

**Comment by DeniseColbert** [comment]
Closing as complete
