### ISSUE TITLE
Searches crashing / taking too long

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#611]
Quite a few recent comments. E.g.
* A real disaster - searches are "too long"
* Searches don't complete
* Now, even queries with forename, surname, birth county, and a range of 2 years for birth comes back with "Your search was running too long".  I did test out Freecen2 earlier, and did not come up against this problem. I am quite willing to get used to the newer interface, but am finding the continuous error messages for long running queries a bind.
My background is as a DBA and I am fully aware of how the processing behind the website works. The queries I am using should be using key look-ups, and therefore should not be long running. In my experience, either the key structure is not being used, or the limiters in place are too low.

**Comment by richpomfret** [comment]
Explore ways of determining search result duration - should have info here somewhere. Might be useful for us to have some stats for this - perhaps an alert for any patterns where search results take too long.

**Comment by Captainkirkdawson** [comment]
You have them at https://www.freecen.org.uk/search_statistics
![cen.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb919461cec1b99de6b546a749b2ce6b1373727155a07f25d0bb7eef1b2b515d5f4ea9435a564df5eb9539e4e76224d50152a7842f4d7ed43c19a6b9871abd07ba23894d87b1ba8a5e8d.JPG)

**Comment by Captainkirkdawson** [comment]
The actual search performance can be looked at in one of the actions if you log in.
There is no indication of long running searches in the past 2 days.
![cen2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb919471c0cfeb9ffbb049a15ee4d673047227285cf22824d0b670e91222515f5d4eac445a5d4df5f09b37b4f46d2ede0356b49b381d66cc2f10abb2831aba03bc20884b8cb2ba8d49d2a5.JPG)
![cen1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb919472c0cfeb9ffbb049a15ee4d673047227285cf22824d0b670e91222515f5d4eac445a5d4df5f09b37b4f46d2ede0356b49b381d66cc2f10a4b2831aba03bc20884b8cb2ba8c4ad2a5.JPG)

**Comment by Captainkirkdawson** [comment]
Mind you at the same time it is clear from errbit that FreeCEN2 crashes many times a day
https://errbit.freeukgen.org.uk/problems

**Comment by Captainkirkdawson** [comment]
By way of an observation CEN appears to be using indexes and index hinting originally designed for FreeREG and are likely inappropriate for CEN

**Comment by Captainkirkdawson** [comment]
What is also troubling is that there are close to 100 search failures a day on just one server with a log entry FREECEN:PHC WARNING: browser may have jumped across servers mid-session. The actual message is likely incorrect but the searches failed or it  was a bot!! Regardless something is not right

**Comment by Vino-S** [comment]
> Mind you at the same time it is clear from errbit that FreeCEN2 crashes many times a day
> https://errbit.freeukgen.org.uk/problems

We had crashes on search everyday. I thought may be it was a bot as it happened exactly at same time everyday.
https://errbit.freeukgen.org.uk/apps/5b63313de937903f2020c67f/problems/5b8fe8a7e93790df64ef4fd0

I concluded them to be bot as most of the crashing `search ids` are the one's that do not exist in our collection. At present I have re-directed these searches(one's with search ids that do not exist in our collection) to home page with a flash message.

**Comment by Vino-S** [comment]
But We need to design to filter out these bots or similar attacks for long run of our application

**Comment by Vino-S** [comment]
> By way of an observation CEN appears to be using indexes and index hinting originally designed for FreeREG and are likely inappropriate for CEN

Ah. Yes. Indexing can be a issue too

**Comment by Captainkirkdawson** [comment]
I started a slack channel thread on indexing if you wish to chat about it

**Comment by Captainkirkdawson** [comment]
Having looked at FC2 over several days there is a) no evidence of timeouts b) very few crashes affecting users c) there is generally good performance. 
At the same time I would urge testing and deployment of the great merge so FC2 can take advantage of and build upon the guarding developed for FR2 as well as the latest versions of software.
The biggest performance weakness of FC2 is that it uses FR2 indexes and not indexes tailored to support the FC2 search.

**Comment by richpomfret** [comment]
Closing - we need details for any specific issue. Checked and no major issues. Sep story being created for improving indexing.
