### ISSUE TITLE
Movie next/previous household buttons

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#612]
These are not being seen, possibly bring buttons to the next line down? Or somewhere else more prominent.

Updated:
* I have commented adversely on the absence of the next/previous household search. I have now found it, right at the top of the screen where it is not visible if you have scrolled down to view the full list of names in a household of more than have a dozen people. Not a clever place to put it.

E1, U3, S8, C6: P18

**Comment by FreecenBren** [comment]
The wording needs amending as well. Someone assumed the link would go to
the occupants ‘previous’ address instead of being able to look who was
living next door and up the road etc.

**Comment by richpomfret** [comment]
To investigate and propose possible solutions, update wording.

**Comment by DeniseColbert** [comment]
As per updated comment, suggest moving or adding to below results/details

**Comment by Captainkirkdawson** [comment]
Here are 2 options
Option1/1a the a shows that it was a dwelling move. This basically just forces the header break with dwelling  in 2nd line

![option 1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/fd95f079-133d-41c9-9cc6-51951657cf42)
![option 1a.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/dcf573a4-6fb7-4a6c-a461-bbd0fe67da43)

Option 2 splits the header into 3 parts. Basic control of print;citation; Dwelling control and lastly individual control. Again the a shows the effect of a dwelling move

![option 2.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/b634ba45-f778-419e-8bce-5c8a72ad708e)
![option 2a.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/f49c3b28-0d87-490e-9bff-2b58ac1e34c3)

**Comment by PatReynolds** [comment]
Split between two groups is good - above and below dwelling block.

**Comment by Captainkirkdawson** [comment]
Deployed to test3

**Comment by Captainkirkdawson** [comment]
Revised version on test3
