### ISSUE TITLE
Search button not working most of the time

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#613]

**Comment by richpomfret** [comment]
Need more info. It has happened on desktop/laptop (could be a hardware issue?).

**Comment by PatReynolds** [comment]
@DeniseColbert  is this still happening?

**Comment by PatReynolds** [comment]
I have been using FreeCEN2 a lot over the last few months and this seems to be resolved.  So removing high priority.
