### ISSUE TITLE
Communicate feature where results are labelled as 'viewed' after being shown

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#614]
When you get a list of possible outcomes for a person in a particular locality it is difficult to know which entries you have already clicked on if you are going in to several entries. It would be useful if entries could be coloured to show they have already been checked.

E1, U3, S8, C7: P19

**Comment by richpomfret** [comment]
We do have this, however it is only stored within a single session and then the user must select 'back to results' and the file is then 'viewed'. If a user clicks back on the browser button, the file is not described/labelled as 'viewed'. Story here therefore is to communicate this to the user. Perhaps a secondary story for allowing persistent 'viewed' labels upon login (perhaps saved searches too).

**Comment by Captainkirkdawson** [comment]
CEN did not store the fact that it had viewed a record. It does now.

**Comment by Captainkirkdawson** [comment]
This also implements the View n (Seen) capability

**Comment by DeniseColbert** [comment]
Fantastic, thanks Kirk- I'll put it on SM and in Newsletter.
