### ISSUE TITLE
Handle blank rows of VLD file FC2 update process

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeCENMigration#616]
E0, U6, S7, C5: P18

**Comment by Captainkirkdawson** [comment]
Do not know what the requirement is and given that
CSVProc can handle the traditional format of csv file so there is no basic requirement to load a VLD file.
CSVProc will download the traditional headed csv file in the correct format for the year.
We can download a VLD file from CEN2 in csv format and it can be processed by CSVProc
Suggest this be closed.

**Comment by PatReynolds** [comment]
@geoffj-FUG can you explain what is needed, please?

**Comment by geoffj-FUG** [comment]
Brenda
Have the blank rows in vld files that vldrev stated were ignored been loaded and are they causing problems?
Geoff

**Comment by FreecenBren** [comment]
They do not cause an issue on their own.

If a VLD  fails at upload as an ERROR, and i correct it by amending and
replacing in FC1, then if I do find some blank rows,  mostly at the end of
the piece,  I do delete them when I adjust the error.
Not sure if other COORDS do the same.

They are picked up in CSVCHECK.
Before sending it to be  Proof Read, using Visual Checking ,  I do run it
through CSVCHECK .  Again cannot vouch for other COORDS.

Brenda

**Comment by PatReynolds** [comment]
Recent updates not having such errors.  Closing, to re-open if errors recurr.
