### ISSUE TITLE
FC1 - update announcement box

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#617]
It is now out of date. Replace announcement box with text:

Please visit www.freecen.org.uk (also known as FreeCEN2) to use the new site, which has new features, including a citation generator (evidence explained, wikitree, family search, legacy and others)

www.freecen.org.uk should link to FreeCEN2.

E0 U1 S3 C7?: P11

**Comment by richpomfret** [comment]
@PatReynolds to test.

**Comment by PatReynolds** [comment]
Still seeing 
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/548e1e8a-5a57-4b2b-b983-f1a6ae006e4d)

My fault - did not make the story clear! Have clarified above

**Comment by PatReynolds** [comment]
duplicates #1374, so closing
