### ISSUE TITLE
Silsden not listed in FC2

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#624]
I have complained for several years that Freecen does not list Silsden in West Riding and have been assured that Freecen 2 will be more inclusive. You have introduced a list of places when a county is selected but have still not included Silsden (a town of 10,000 people).

Needs #165

**Comment by FreecenBren** [comment]
This is just one of many as I have been saying recently.

**Comment by Captainkirkdawson** [comment]
Silsden is a civil parish in WRY; i=the images including Silsden have not been transcribed hence it will not appear in the Census Places list. It would automatically appear if it was ever tyranscribed
