### ISSUE TITLE
Database Coverage link being missed

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#625]
Comment was: * Would be helpful if a list of areas completed was provided
It is presumed that the user did not spot that 'database coverage' has the data wanted.
It is also possible that the user wanted more granular data - if so, a separate story will be created.

E3, U3,  S9, C5:P20

**Comment by FreecenBren** [comment]
Are we talking ‘Areas’  completed or ‘PIECES’ or Counties by Census Year.

 

The STATS on both FC1 and FC2 give you a list and the percentage  that each County is up to.

They also show all Counties by Census Year that are 100% complete.

 

Can we clarify please which we are wanting.

**Comment by richpomfret** [comment]
To explore how to make 'database coverage' more visible - including providing 'recent additions' somewhere and communicating this info to users.

**Comment by richpomfret** [comment]
To also clarify this - what is meant by 'areas'? We DO provide completion % for county..

**Comment by FreecenBren** [comment]
The STATS show details of specific areas like this this example for NTT 1851 Census.

This shows the number of records online and the % done.

 


Nottinghamshire    (NTT)

281,601

100.0%

 <https://www.freecen.org.uk/freecen_coverage/NTT#1851> Details

 

Click on the “Details” option of the above example and you get details of the areas covered for any particular PIECE number.

 

As per this example for NTT 1851 Census PIECE number HO512412

 


Piece

Place

Comprising

Status


2412 

 <https://google.com/maps/place/53.4,-0.9/@53.4,-0.9,10z> Gringley

 <https://google.com/maps/place/53.4,-0.9/@53.4,-0.9,10z> Gringley-on-the-Hill,
  <https://google.com/maps/place/52.133333,-0.233333/@52.133333,-0.233333,10z> Everton,  <https://google.com/maps/place/53.4,-1.016667/@53.4,-1.016667,10z> Scrooby,  <https://google.com/maps/place/53.4,-0.966667/@53.4,-0.966667,10z> Mattersey,
  <https://google.com/maps/place/53.383333,-0.9/@53.383333,-0.9,10z> Clayworth,  <https://google.com/maps/place/53.35,-0.866667/@53.35,-0.866667,10z> North Wheatley, 

             <https://google.com/maps/place/53.35,-0.85/@53.35,-0.85,10z> South Wheatley

Online

 

---------------------------------------------------------------------------------

Or this one for NTT 1861 RG092417

 


Nottinghamshire    (NTT)

322,200

100.0%

 <https://www.freecen.org.uk/freecen_coverage/NTT#1861> Details

 


Piece

Place

Comprising

Status


2417  

 <https://google.com/maps/place/53.216667,-0.883333/@53.216667,-0.883333,10z> Tuxford

 <https://google.com/maps/place/53.266667,-0.883333/@53.266667,-0.883333,10z> Askham,  <https://google.com/maps/place/53.233333,-0.85/@53.233333,-0.85,10z> Darlton, East Drayton,  <https://google.com/maps/place/53.283333,-0.833333/@53.283333,-0.833333,10z> Stokeham,  <https://google.com/maps/place/53.266667,-0.8/@53.266667,-0.8,10z> Laneham,  <https://google.com/maps/place/53.25,-2.8/@53.25,-2.8,10z> Dunham, Ragnall,  <https://google.com/maps/place/53.233333,-0.8/@53.233333,-0.8,10z> Fledborough, Marnham,  <https://google.com/maps/place/53.2,-0.816667/@53.2,-0.816667,10z> Normanton-upon-Trent,  <https://google.com/maps/place/53.216667,-0.883333/@53.216667,-0.883333,10z> Tuxford,  <https://google.com/maps/place/53.25,-0.883333/@53.25,-0.883333,10z> East Markham, West Markham, Bevercoates,  <https://google.com/maps/place/53.266667,-0.933333/@53.266667,-0.933333,10z> West Drayton,  <https://google.com/maps/place/53.233333,-0.983333/@53.233333,-0.983333,10z> Bothamsall,  <https://google.com/maps/place/52.783333,-2.2/@52.783333,-2.2,10z> Haughton, Markham Clinton

Online

 

The same applies for each census year. 

Again if they click on any of the areas that are in ORANGE that will take them to a map of the “Area”

 

Hope this is what you are wanting as a guide.
