### ISSUE TITLE
"Wildcard can only be used with a specific place" error

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#630]
This is frustrating... what if I don't know the place?

E1, U3, S8, C6: P18

**Comment by richpomfret** [comment]
Can we do a wildcard search without a place? @Vino-S to check if this is possible without search/performance issues.

**Comment by richpomfret** [comment]
Investigate using 'county' instead of specific place for wildcard.

**Comment by Captainkirkdawson** [comment]
I doubt very much that we could ever go beyond a small number of places. The performance demand of a wildcard search is enormous.
