### ISSUE TITLE
Birth County Sorting function not working

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#631]
The sorting function for results does not work - for example I've just tried to sort on county of birth in the results page, and I get a different order from the original, but nothing remotely resembling an alphabetical sort. Even allowing for additional spaces at the beginning of entries the results are in no apparent logical order

E1, U4, S9, C7: P23

Needs #579

**Comment by DeniseColbert** [comment]
I tested this and replicated:
![image](https://user-images.githubusercontent.com/19173257/53642151-019e7b80-3c29-11e9-8084-f7e5443052ee.png)

**Comment by FreecenBren** [comment]
FC2 having issues with  getting it to search filled in a report online.
Tried again after a few minutes after working ok now.
Had same issue yesterday.

Anyway just got a search and it found 144 records and clicked on Census
Place column and it sorted them all alphabetically Ok.
This was on FC2  search NOT test mode!

Then clicked on Census Year and it then re-sorted them  again ok in year
order.
Also worked on Birth Year column ok.

**Comment by DeniseColbert** [comment]
Clicking on Birth County seems to sort by Census County

**Comment by richpomfret** [comment]
The merge may well assist us here.

**Comment by Captainkirkdawson** [comment]
Birth county sort code needs to be written

**Comment by Captainkirkdawson** [comment]
@Vino-S  since I have worked with this on FR do you want me to take this on? especially in light of your work load

**Comment by benwbrum** [comment]
Currently the code is in `master-into-freecen` deployed on `test2` and has been tested by @Captainkirkdawson .  We will wait to deploy it until `master-into-freecen` is deployed to FreeCEN production, and *not* add it to `freecen_parsing`.
