### ISSUE TITLE
keeps asking for repeat info 
 131417124 Website Problem (roy hill)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#635]
Issue reported by **roy hill** at 2019-03-02 00:45:24 UTC
Time: 2019-03-02T00:40:35+00:00
Session ID: 240e95f93d638c6148bb332ae4866ca0
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
keeps asking for repeat info is the fault my end let me know still a good system    

![Screenshot](https://freecen2.freecen.org.uk/uploads/contact/screenshot/5c79d224f493fd864ae1db7a/_old_)

**Comment by richpomfret** [comment]
Requires more info - shall keep open for now.
