### ISSUE TITLE
125424521 link to google doc (Kirk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#637]
Issue reported by **Captkirk** at 2018-12-22 16:08:41 UTC
Time: 2018-12-22T15:46:12+00:00
Session ID: c4f773fb216de16e38107465c0d856b2
Problem Page URL: [/cms/system-documents/road-map](/cms/system-documents/road-map)
Previous Page URL: [https://www.freecen.org.uk/manage_resources/new](https://www.freecen.org.uk/manage_resources/new)
Reported Issue:
I question having a link to a google doc that is open for editing. I am unsure about the specific link but it opens in my google docs folder and I can navigate and see all my own personal documents that I have on google.
https://freecen2.freecen.org.uk/uploads/feedback/screenshot/5c1e6189f493fd11d74bd9e1/freecenc.JPG    

![Screenshot](https://freecen2.freecen.org.uk/uploads/feedback/screenshot/5c1e6189f493fd11d74bd9e1/freecenc.JPG)

**Comment by PatReynolds** [comment]
Yes: opening the document logs you into your own drive (when I do this, it shows my documents, not yours).  If you wish to comment anoymously, you can do this by opening the link in an incognito browser window.

**Comment by richpomfret** [comment]
Can you clarify what the exact issue is?
