### ISSUE TITLE
114258742 Shetland Isles (Brenda)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#638]
Issue reported by **Brenhanna** at 2018-08-15 10:32:22 UTC
Time: 2018-08-15T10:31:44+00:00
Session ID: c38a9c9061be702ead0bdef814ec4daa
Problem Page URL: [/counties/59026141e937908f5b92e089/edit](/counties/59026141e937908f5b92e089/edit)
Previous Page URL: [https://freecen2.freecen.org.uk/counties](https://freecen2.freecen.org.uk/counties)
Reported Issue:
Why do we have 2 Shetland isles on FC2    

![Screenshot](https://freecen2.freecen.org.uk/uploads/feedback/screenshot/5b740136f493fd0d5c428fed/_old_)

**Comment by PatReynolds** [comment]
There  is now only one shetland in Birth county and one in Census county, so resolved.
