### ISSUE TITLE
114258246 Orkney (Brenda)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#639]
Issue reported by **Brenhanna** at 2018-08-15 10:24:06 UTC
Time: 2018-08-15T10:23:13+00:00
Session ID: c38a9c9061be702ead0bdef814ec4daa
Problem Page URL: [/counties/59026141e937908f5b92e081](/counties/59026141e937908f5b92e081)
Previous Page URL: [https://freecen2.freecen.org.uk/counties](https://freecen2.freecen.org.uk/counties)
Reported Issue:
Why do with have Orkney twice in FC2    

![Screenshot](https://freecen2.freecen.org.uk/uploads/feedback/screenshot/5b73ff46f493fd0d5c428fe0/_old_)

**Comment by PatReynolds** [comment]
Orkney is now only there once in the search dropdowns for Birth County and Census County so it has been resolved,
