### ISSUE TITLE
Compare FreeREG2 Quality Control functions with FreeCEN2 needs

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#64]
Compare FreeREG2 Quality Control functions with FreeCEN2 needs and specify issues for subsequent milestones.

**Comment by sean-wood** [comment]
discussion to be scheduled

**Comment by PatReynolds** [comment]
Quality control helps not only researchers, but also transcribers, who are reassured, particularly with difficult transcriptions, that they alone are not responsible for the quality of their work.

**Comment by PatReynolds** [comment]
I think this story has been completed in the Policy Group discussions.  We need to ensure that stories now exist (with appropriate milestones) for all the quality control functions which are desired for FreeCEN2.

**Comment by PatReynolds** [comment]
Functions are listed at #84.

**Comment by PatReynolds** [comment]
#84 and #85 now replace this
