### ISSUE TITLE
Explore where Report a Problem button reports are going

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#640]
Brenda has submitted many reports and not received a response. Also, they don't appear to be in Contacts. Data Problems are there from users, but not Brenda's.

I sent a test today and received a response (below) but it hasn't appeared in Contacts.

![image](https://user-images.githubusercontent.com/19173257/53966061-4f642980-40ea-11e9-82ee-34ee437092de.png)

**Comment by Vino-S** [comment]
They should be listed in Feedback action

**Comment by DeniseColbert** [comment]
Aha! Thanks Vino, I've now found my test. However, the ones that Brenda said she sent are not there. I wonder if she used the FreeCEN2 Feedback form to report the problem instead of the button...

**Comment by richpomfret** [comment]
Reqires further investigation..

**Comment by richpomfret** [comment]
A good issues for John T to take a look at perhaps.

**Comment by richpomfret** [comment]
@DeniseColbert to investigate and see if this is still a problem.
