### ISSUE TITLE
27 P - Update links to security policy in Volunteer sign-up and/or Members' Area

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#641]
Version for Transcribers: https://freeukgen.page.link/SecPab

E2, U10, S7, C8: P27

**Comment by Vino-S** [comment]
Added link in Members page on test3

**Comment by richpomfret** [comment]
@DeniseColbert to take a look.

**Comment by richpomfret** [comment]
Yes, let's include this within the volunteer sign-up process (tick box for 'read').

**Comment by richpomfret** [comment]
@PatReynolds to create new stories based on the above and to allow users to then access the policy after having signed up/ticked. We can then close this one.

**Comment by PatReynolds** [comment]
Policies all  now accessible on 'Free UK Genealogy Policies' button, so no new story made.
Story already exists to add to sign up - #745
New story made on addition to user profile #788 

Task complete, so now closing.
