### ISSUE TITLE
"The record you are trying to access doesn't exist" message

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#642]
![image](https://user-images.githubusercontent.com/19173257/54198700-1a2b5300-44bf-11e9-9aad-c73d3dd5d30c.png)

I've had this quite frequently on different areas, but the record does exist... in this instance I'd clicked on the link to report an error in transcription on Search Record page.

E2, U4, S5, C9:P20

**Comment by DeniseColbert** [comment]
When I completed the Test report, I received this:
![image](https://user-images.githubusercontent.com/19173257/54199043-dd139080-44bf-11e9-8212-9b1c06cc1d1f.png)

**Comment by DeniseColbert** [comment]
Contact Us link clicked:
![image](https://user-images.githubusercontent.com/19173257/54279501-2251c400-458d-11e9-9a48-3c42a701530c.png)

**Comment by Vino-S** [comment]
@DeniseColbert  we have two bugs here
1. One is as the title says,  'We are sorry' message: Minor change
2. Second one is the Red Error page when we report an error: needs investigation

**Comment by PatReynolds** [comment]
REd error message story no issue #646

**Comment by richpomfret** [comment]
To test on Live (the message has been changed). To try and replicate/investigate the second bug (captured in the other story Pat mentions).
