### ISSUE TITLE
We should be able to have 2 Syndicate COORDS doing one County when they are split by Census Year. (Brenda)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#643]
From email about new GLS coord:

I cannot update her through on FC2 for GLS as that would then go to Chris as a new helper, and I have her set up for my 1891 GLS?

We need to split up  GLS somehow???? 

 

We should be able to have 2 COORDS doing one County when they are split by Census Year.

I have updated  her for ENG in the meantime

E2, U3, S7, C5 :P17

**Comment by edickens** [comment]
We have the same problem in FreeREG.  Some large counties need more than one Coordinator, so we have some with Assistant Coordinators.  I think it is important that you have one person in overall control and who gets the feedback messages.

**Comment by PatReynolds** [comment]
I think FreeCEN may be slightly different, Eric, as the counties differ from census to census.  Perhaps having one person as County Coord and a number as Syndicate Coords would work in FreeCEN?

**Comment by geoffj-FUG** [comment]
Kirk
This issue will be a problem on cutover.
I was hoping to have Coordinators assist other Coordinators with the PARMS set up. Also coopt Validators to assist. 
We cant do this unless we can have more than one Coordinator to a County.
We have a one to many relationship for Transcribers, Proofreaders and Validators. So why cant the system accept a one to many relationship for Coordinators? A Coordinator can have many Counties so is there not a linking table?
If itis not possible to have more than one Coordinator can we create a role of Assistant Coordinator with the same permissions as a Coordinator to resolve the problem?
Geoff

**Comment by FreecenBren** [comment]
If you do decide to go down this route, then only one County Coord will
need to receive the New Volunteers email. Otherwise we could have
duplication of setting up the new volunteers.
Unless you have another plan to deal with that issue.

Brenda

**Comment by geoffj-FUG** [comment]
Brenda

 

The story was on Zen Board for review. 

 

I don’t understand why we cant have more that one Coordinator to a County if we can have more than one Transcriber etc. To me it is a simple one to many relationship without seeing the code. I am sure that Kirk will be able to tell me.

 

I am looking for a short-term solution to help get the new PARMS files sorted when we cutover. 

 

When Pat has launched CSVProc I have a Newsletter to explain the new PARMS to Coordinators. I want to wait until Pat’s launch message has gone, otherwise there will be too many messages out there at the same time.

 

I do not see it as the long term solution, especially as it seems to be a FreeREG problem as well from the Board messages. It must be a design problem.

 

Geoff

**Comment by geoffj-FUG** [comment]
After discussion with Kirk a County cannot have 2 Coordinators. The system has not been designed for a one County many Coordinators model. It is one Coordinator Many Counties model. The joining table does not exist and its introduction would be a major project. It all comes down to the original design brief.
Geoff

**Comment by Captainkirkdawson** [comment]
@FreecenBren @geoffj-FUG @rhodamackenzie 
I have been quite clear that  a syndicate can have only one coordinator and a county can have only one coordinator. That was the design adopted for better or worse 8 years ago. Changing that is an enormous task and the pain in doing it it likely bigger than the gain.
It is essential though that you recognise that county coordinators and syndicate coordinators perform very different functions. 
County coordinators manage the **data** in the database; getting the data and ensuring, it is all completed and consistently retrievable. They concern themselves predominantly the parms and places.
Counties are geographical regions designated by a chapman code with one coordinator
Syndicate coordinators manage the **people**, recruiting them, training them, assigning then work, helping them with problems, checking their work and entered into the system.
There are NO design limitation to the number of syndicates; there are no geographical boundaries to a syndicate
The software for all three project are based on the same concept to a greater or lesser degree. 
BMD had had thousands of syndicates over the past 20 years; they have come and gone with their syndicate coordinators. They may have been people in a specific countries in Australia or New Zealand or Canada or a region in the UK; they focused on certain blocks of records; some focussed on a specific district, some a specific year.
REG has far fewer syndicates and tend to focus on a certain county but there are multiple syndicate. It has a training syndicate that most new volunteers pass through where they are trained by the volunteer coordinator.,
CEN has never embraced the concept and has been county focussed.
Now if the actual requirement is **Can we have different groups of people working by year in the same county?** The answer is yes. We could have the a 1901 syndicate that deals with all counties; we could have 8 syndicates in SOM each one focussed on a specific year. People are in one syndicate though! but they can be moved to another at any time if needed. The same person can be the syndicate coordinator for all SOM syndicates but there can only be one syndicate coordinator for a syndicate. 
The syndicate structure is up to the project to establish; and it can change as your needs change.

**Comment by PatReynolds** [comment]
Yes, we can have tso syndicate cords (not 'County cords') doing one county - limitelsss syndicate cords per county coords per county!
