### ISSUE TITLE
Contact Us --> Thank You

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#644]
Email upon sending reads "Thank you for your General Comment". "Thank you for your thank you" doesn't sound right, but maybe "Thank you for your Bouquet"?

E1, U3, S7, C9: P21

**Comment by richpomfret** [comment]
Perhaps 'Thank you for letting us know, we appreciate your support'?

**Comment by PatReynolds** [comment]
'Thank you for your review' (as per systemwide #134

**Comment by Captainkirkdawson** [comment]
Current set of subject of response emails is
{
      'Website Problem' => 'RE: Thank you for reporting a website problem',
      'Data Question' => 'RE: Thank you for your data question',
      'Data Problem' => 'RE: Thank you for reporting a problem with our data',
      'Volunteering Question' => 'RE: Thank you for question about volunteering',
      'General Comment' => 'RE: Thank you for the general comment',
      'Thank-you' => 'RE: Thank you for your compliments',
      'Genealogical Question' => 'RE: Thank you for a genealogical question',
      'Enhancement Suggestion' => 'RE: Thank you for the suggested enhancement'
    }

**Comment by DeniseColbert** [comment]
Could this 'Thank-you' => 'RE: Thank you for your compliments', be changed per Pat's comment above, to 'Thank you for your review'?

**Comment by Captainkirkdawson** [comment]
Done and applied to test3
