### ISSUE TITLE
FC2 STATS is not showing updated totals in ‘Percentage Graph’ and the ‘Totals Graphs’ columns have not been updated since 1/1/2018.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#645]
On FC2 STATS is there a reason as to why the ‘Percentage Graph’ and the ‘Totals Graphs’ columns have not been updated since 1/1/2018. [Reported by Brenda]

**Comment by Vino-S** [comment]
Hi @PatReynolds ,
FC2 stats page in brazza show has updated 'Percentage Graph' and 'Totals Graphs'
Below is an example for LAN: 
Percentage Graph:
http://www16.freecen.org.uk/freecen_coverage_graph/pct/LAN/1861
Totals Graph:
http://www16.freecen.org.uk/freecen_coverage_graph/ind/LAN/1861

The FC2 was updated on March 12th on brazza. The new count is not reflected in other servers yet. Lets wait until the count are reflected on other servers and see the the graphs are updated.
