### ISSUE TITLE
Link to place/map

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#649]
@Brenda reports that she saw links from place of birth to a map - now no longer there on test2 or 3.  Maybe a product of bringing the genuki link on place and/or church to FreeCEN?  

Sounds like a nice feature - do we want to enable it (working for FreeCEN, of course)

**Comment by Captainkirkdawson** [comment]
@FreecenBren  @PatReynolds Please review this story. 
The Transcriptions link and the Manage Counties member action on FreeREG access a places database collection. Every place in FreeREG has a location link which displays the location of the Place on a Genuki Map. 
The FreeCEN coverage link takes one to a County with the details providing a pieces listing which contains a Place name as a field for the piece. That has no links to the Place on a Map.
If you log into FreeCEN and use the Manage Pieces Action you get the same display available to Researchers. HOWEVER if you select the EDIT option then the list of places and many of the comprising list have links to Place on a Google map. In other words the edit display has the link while the show does not. Was it intended that the show action contain the links?
This works the same on test2 as well as production so is not a Merge issue
The Manage Counties member action is also available on FreeCEN but it appears to be the same functionality as  FreeREG but without any real data. Is this Action meant to be there?

**Comment by PatReynolds** [comment]
The (?missing ?never there) link was from a results page (i.e. a researcher view).

**Comment by Captainkirkdawson** [comment]
There has never been a researcher accessible link to a map.  Does there need to be one?

**Comment by PatReynolds** [comment]
Maybe - I have added #657 to consider this as part of wider Place discussions.  As it was never there, this story can be closed.
