### ISSUE TITLE
Message send process ends on the wrong screen

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#651]

**Comment by PatReynolds** [comment]
After sending, arrives at this screen:
![Message-end screen.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c37263d9b190120013e30d/125516c66e82c728ace21e0d46c59189308384acc2ecb147e44ef3862c4329316546b3397f8fe62bab0021435a5b1fa4400b5b41f9f18f2bafb63c728a5c0eefd364567dd42103eee9dc4be05ce36ade0d97bcae8b44cae93820e4898b483917001e8afc4f78.JPG)

Pressing the 'send' button again generates error red box.

**Comment by Captainkirkdawson** [comment]
The initial message was created on test3 not test2.
I created and sent a message to Pat. It basically worked OK but message reports it is from FreeREG also it does not contain the server link

**Comment by benwbrum** [comment]
Still needs testing; could be done by @DeniseColbert

**Comment by DeniseColbert** [comment]
Seemed to work OK on test2

Test3 gave me this error when I pressed 'send':
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/d8076883-2b24-4efd-b687-d0d2796aaafd)

**Comment by richpomfret** [comment]
Should be resolved on TEST3 once multi-modal is rolled out later this week.
