### ISSUE TITLE
Volunteering registration does not work

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#653]
@PatReynolds   reported. Testing Volunteer sign up seems to work fine - but changing password generates an error:
![image001.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c37263d9b190120013e30d/125516c66e82c728ace21e0d46e1999b2487d3f9deabf301b44fff9e2c4533317346f67f71ddb22beb172e59595f47ac415a5f44f9fb8b22afbf2e6c981e5ab38532022d8c6853beb2901eb80bbb258e4c84b6ba8a48c3eb3b26f5c6.png)

**Comment by Captainkirkdawson** [comment]
Volunteering and password reset both work as expected on my testing with test2.

**Comment by Captainkirkdawson** [comment]
@PatReynolds  could you please recheck. How did you get the reset message as all mail on test2 is currently trapped and goes to me at this point.

**Comment by richpomfret** [comment]
Shall test this too.

**Comment by richpomfret** [comment]
Password reset works fine for both current/new users on LIVE.

**Comment by richpomfret** [comment]
CLOSING. Will do general current/new user tests post multi-modal deployment.
