### ISSUE TITLE
Contact system mails integration

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#658]
The contact system from REG need integration with some changes made for CEN and the messages adjusted where needed to be multi-modal

**Comment by Captainkirkdawson** [comment]
1. Not all messages are being trapped; not necessarily a big issue
2. The contact message needs to go multi-modal
3. Need to investigate what changes have been made to customize contacts for CEN

**Comment by Captainkirkdawson** [comment]
WRT 1) it would appear  at first glance that the development mail intercept does not intercept cc or bcc

**Comment by Captainkirkdawson** [comment]
All components of Communications, Contacts, Feedback and Messages and Syndicate Messages appear to work as expected with multi-modal information and correct server links

**Comment by benwbrum** [comment]
The contact system needs to be tested to see if the mailings go out correctly.

**Comment by PatReynolds** [comment]
Am unable to log in on test2.  Will now test password recovery!
