### ISSUE TITLE
Database Coverage - explain why some counties are not included in the tables for some  years

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#659]
E.g. Ayrshire - 100% complete for 41 & 51 but absent from list for other censuses. Do we not have images for these? We should let users know somehow.

**Comment by FreecenBren** [comment]
That is because I have not added the PARMS files yet.  Have them all for
the missing ones to edit.
It will not change the % as we do not have the images anyway so once added
they will say 0%
I thought this issue was on a waffle board anyway? I know it has been
discussed.

**Comment by DeniseColbert** [comment]
It might be, if it is we can delete this one. Thanks Brenda.

**Comment by richpomfret** [comment]
To check for duplicate before closing.

**Comment by PatReynolds** [comment]
@AnneV-Learn has put in some text, for review in testing.

**Comment by PatReynolds** [comment]
I _think_ this may be resolved by the new records coverage page - i.e. Catterick, North Riding of Yorkshire:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/d6f0e99d-ad51-4d6c-9b18-324390508793)

1841 = no pieces exist
1851 = 1 piece exists, but we have not transcribed it yet
1861 = 1 piece exists, and this is transcribed and online

Suggested text "a zero in the total pieces column means Catterick [or 'this place'] was not the title of this area in that census year".

What is not resolved is if we can / should list here or somewhere which pieces we will never have (destroyed) and which we have but are not yet fully transcribed.

**Comment by PatReynolds** [comment]
Duplicate is possibley #701
