### ISSUE TITLE
Review feedback from testers

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/FreeCENMigration#66]
Review tester feedback and create user stories if required

**Comment by benwbrum** [comment]
This is absolutely essential for further progress.  I'll take this on in the next day or two if needed.

**Comment by PatReynolds** [comment]
Thanks, Ben.  Can you distinguish between stories/actions which are needed
to complete 1.1 and those which are for 1.4 or 1.7 (or other stages).

On 27 January 2016 at 15:07, Ben W. Brumfield <notifications@github.com>
wrote:

> This is absolutely essential for further progress. I'll take this on in
> the next day or two if needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/66#issuecomment-175674627>
> .
>



-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by benwbrum** [comment]
I may be able to distinguish and assign milestones appropriately, but at minimum I can convert the feedback documents into stories which we can triage into releases. I worry that we have been asking testers to give us feedback but have taken no action on it so they may not feel that their issues are being addressed.

**Comment by PatReynolds** [comment]
If you could start with a document, we could sort into phases, and then
circulate that so people have some idea when things would be happening?

On 27 January 2016 at 16:42, Ben W. Brumfield <notifications@github.com>
wrote:

> I may be able to distinguish and assign milestones appropriately, but at
> minimum I can convert the feedback documents into stories which we can
> triage into releases. I worry that we have been asking testers to give us
> feedback but have taken no action on it so they may not feel that their
> issues are being addressed.
>
> Sent from my iPhone
>
> > On Jan 27, 2016, at 10:36 AM, PatReynolds <notifications@github.com>
> wrote:
> >
> > Thanks, Ben. Can you distinguish between stories/actions which are needed
> > to complete 1.1 and those which are for 1.4 or 1.7 (or other stages).
> >
> > On 27 January 2016 at 15:07, Ben W. Brumfield <notifications@github.com>
> > wrote:
> >
> > > This is absolutely essential for further progress. I'll take this on in
> > > the next day or two if needed.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/FreeUKGen/FreeCENMigration/issues/66#issuecomment-175674627
> >
> > > .
> > >
> >
> >
> >
> > --
> > *- -*
> >
> > *Dr Pat Reynolds*
> > Executive Director
> > Free UK Genealogy <http://www.freeukgenealogy.org.uk/>
> > A charity registered in England and Wales, number 1096940
> >
> > ​+44 ​1904 541411​ +44 7943 145387
> >
> > 36 Albemarle Road, York, YO23 1ER, UK
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/66#issuecomment-175736936>
> .
>



-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by benwbrum** [comment]
We've got two documents that Brenda has assembled.  What we need to do is translate those documents into separate issues in waffle.

**Comment by PatReynolds** [comment]
Yes - translate to issues (text) > group into phases >circulate to testers
> add to github/waffle (I think)

On 27 January 2016 at 17:37, Ben W. Brumfield <notifications@github.com>
wrote:

> We've got two documents that Brenda has assembled. What we need to do is
> translate those documents into separate issues in waffle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/66#issuecomment-175762364>
> .
>



-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
