### ISSUE TITLE
P19 Site Statistics for FreeCEN

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#665]
The site statistics need to list the Cen records
Required by #648

Interval end Year Month Day Number of records Number of searches Number of records added
Not working (last worked 2017-05-19 on live site) - Make story

E1 U6 S7 C6: P19

**Comment by richpomfret** [comment]
@Captainkirkdawson Can you add a size?

**Comment by Captainkirkdawson** [comment]
This is duplicate of 685
