### ISSUE TITLE
Import from FreeREG buttons (or other solution) used to solve FreeREG#1870

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#672]
Taking solution for this from FR in terms of allowing for easy share of permanent links/URL to social media & adding on FC. See other story on FR for further info.

P17? if its size is 5

**Comment by Captainkirkdawson** [comment]
Do not understand the requirement

**Comment by PatReynolds** [comment]
Hope that clarifies, @Captainkirkdawson - seems to have lost half the title!

**Comment by richpomfret** [comment]
@Captainkirkdawson can you add a size when appropriate.
