### ISSUE TITLE
P 18 Separate database for test instances

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#674]
Currently both test2 and test3 are using the same mongodb database. This is bad practice.
Solution is to clone the test database and save under a separate name.
E0 U6 S7 C5: P18

**Comment by richpomfret** [comment]
@Captainkirkdawson . Agreed. Can we have a size estimate?

**Comment by Captainkirkdawson** [comment]
Implemented
