### ISSUE TITLE
FreeCEN2 Roadmap on FC2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#68]
Move structure/documents from gdrive to FC2

**Comment by PatReynolds** [comment]
Currently only the roadmap?

**Comment by AlexAvlonitis** [comment]
Once the document is finalized i'll upload it on the website

**Comment by PatReynolds** [comment]
Reopened as found not to be done. Now live, open to team to comment/check.

**Comment by richpomfret** [comment]
Now on the site but requires an update.
