### ISSUE TITLE
Bring alternative saving of detailed results from FreeREG

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#681]
Export to CSV and Json

E1 U1 S4 C?7: P15

**Comment by richpomfret** [comment]
Likely to inherit this during the merge? In which case this 'may' already be done..

**Comment by PatReynolds** [comment]
FC2  test 3 has 'SH' and 'Remove' versus FR2 live "Show' and 'Replies'.  the FC2 set-up is very different, with the message being the author-view, not the recipient-view (as far as I can see).

**Comment by PatReynolds** [comment]
Alternative means are missing on FreeCEN:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/d3d2bea8-2488-4ddd-a04c-3ee532505aa2)

**Comment by PatReynolds** [comment]
Now there, so closing.
