### ISSUE TITLE
FreeCEN2 GA has been 'broken' since Saturday - not reporting expected numbers

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#697]
FC2 Google Analytics has gone from reporting a few thousand unique users per day to under 10. It looks like this reported traffic is now being picked up by FreeREG instead due to an incorrect ID being used. This coincides with the code deployment at the weekend.

**Comment by richpomfret** [comment]
Revisiting/updating TAG Manager should resolve this (re: Kirk's theory) - we also need to assess how this might be impacting upon bounce rate.

**Comment by richpomfret** [comment]
To make multi-modal.

**Comment by Captainkirkdawson** [comment]
It is clear that there  are 2 tag manager codes. 1 for FreeREG and 1 for FreeCEN. 
The code at https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/layouts/application.html.erb#L11-L17
needs to be made dependent on appname similar to 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/layouts/_header.html.erb#L4-L31
