### ISSUE TITLE
Donate button is broken on https://www.freecen.org.uk/cms/opportunities-to-volunteer-with-freecen

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#699]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/16762f99-95e8-482f-82fc-2bf92f9ce7c3)

Image needs adding to Refinery

E2 U2 S5 C8: P17

**Comment by AlOneill** [comment]
Will fix issues once edits on FreeREG are accepted as good. (Issue there is in Needs Review.)

**Comment by PatReynolds** [comment]
FreeREG on test3 still broken on chrome and comodo:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/47c29e94-e5be-4b1b-8c88-9d22bbe79bf9)

And on Firefox it all looks a bit off:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/49852292-4d1d-4fd9-bd59-b0bb80276c1f)

**Comment by AlOneill** [comment]
@PatReynolds Please see the DRAFT version of the REG page.
https://test3.freereg.org.uk/cms/draft-opportunities-to-volunteer-with-freereg

**Comment by AlOneill** [comment]
Page fixed and sync-ready.

Found that the :hover is not visible on the Donate icon — :focus is fine. Applied a temporary, scoped style. Note there is no such problem on REG (have yet to tackle BMD). Will open an issue to investigate — at some point!
