### ISSUE TITLE
Search by Birth Year (`search_date`)

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#70]
Currently we populate the `search_date` field on our search records with the date of the census year.  This field holds the date searched by the "First Year" and "Last Year" inputs on the search form. 

As @FreecenBren has pointed out, this gives a confusing UI experience -- if a researcher searches for 1863-1867, they will find no records, since no census was taken that year.

At the same time, FC1 supports search by age/birth-year, which is a feature we should implement for FC2.  

I propose that, during SearchRecord creation, we calculate the birth date of the individual from the census year and age on the form, and use that to populate `search_date` instead of shoving the census year in that field.  Then users will be able to do date searches on likely birth years, and the form UI will be meaningful.

(Support for searching census year is addressed in issue #69)

We'll also need to change the help text/tool-tip to explain that the year range is a birth year.

**Comment by PatReynolds** [comment]
I believe that researchers will want both to search by year(s) of census
and by birthdate.

We need to complete #52 before deciding what to do.

Best wishes,

Pat

On Monday, 19 October 2015, Ben W. Brumfield <notifications@github.com>
wrote:

> Currently we populate the search_date field on our search records with
> the date of the census year. This field holds the date searched by the
> "First Year" and "Last Year" inputs on the search form.
>
> As @FreecenBren <https://github.com/FreecenBren> has pointed out, this
> gives a confusing UI experience -- if a researcher searches for 1863-1867,
> they will find no records, since no census was taken that year.
>
> At the same time, FC1 supports search by age/birth-year, which is a
> feature we should implement for FC2.
>
> I propose that, during SearchRecord creation, we calculate the birth date
> of the individual from the census year and age on the form, and use that to
> populate search_date instead of shoving the census year in that field.
> Then users will be able to do date searches on likely birth years, and the
> form UI will be meaningful.
>
> (Support for searching census year is addressed in issue #69
> <https://github.com/FreeUKGen/FreeCENMigration/issues/69>)
>
> We'll also need to change the help text/tool-tip to explain that the year
> range is a birth year.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/70>.
>


-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by FreecenBren** [comment]
Where it now says First Year and then Last Year can we amend it to read Birth Year From  and  Birth Year To  please  as it is misleading as it is. Thanks
