### ISSUE TITLE
Need for viewed records to be noted on return to results list as "viewed"(139897433 Website Problem -Geoff Masters)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#700]
Brenda and Pat believe this has already been raised as an issue, but cannot find it on the board.

Issue reported by **Geoff Masters** at 2019-06-08 04:23:53 UTC
Time: 2019-06-08T04:07:00+00:00
Session ID: ee2ee8e49e96aeb54345af25b1dcb366
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
This is both a Website Problem but also an Enhancement Suggestion. 
When multiple results appear to a question  and you check one,  then go back to results, if those results have more than one entry with the same forename there is no way to differentiate the one/s you have already checked.
My suggestion is to make  the DETAIL button change colour once it has been pressed. Would save a lot of frustration when you have 80 odd results to check out.    

![Screenshot](https://www.freecen.org.uk)

Was there ... has gone ... may be a bug.

Adding the coulour change is a 'nice to have' / another story

/Geoff Masters's email ends

Story:
Implement FreeREG design for alerting users that a record has already been reviewed to FreeCEN

E1 U4 S5 C7: P 17

**Comment by AlOneill** [comment]
FreeREG results get "(viewed)" added to each result that has been viewed: can this be applied to CEN?

![image](https://user-images.githubusercontent.com/14852554/62137023-2a609500-b2dd-11e9-9f33-425a96f1c5f6.png)


**A colour change will mean nothing to a screen-reader.**

**Comment by PatReynolds** [comment]
Hi @AlOneill no-one spot that Geoff's suggestion wasn't to use FreeREG solution, which is accessible. So changed changed story accordingly.

**Comment by Captainkirkdawson** [comment]
See systemwide  story 47.
Conclusion to date for all apps is that we should have the detail link as first column and that viewed gets added. Still no decision on adding row number as in REG or sticking with generic title as in CEN.

**Comment by PatReynolds** [comment]
Completed, so closing
