### ISSUE TITLE
Add link to System Documentation Folder in Gdrive (from Systems Documentation page in Refinery)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#702]
E0 U6 S7 C8 : P21

**Comment by PatReynolds** [comment]
In test 3 - needs review.

**Comment by PatReynolds** [comment]
REady for you to check, on test3 @AlOneill

**Comment by richpomfret** [comment]
Link is in TEST3 refinery (systems doc page).

**Comment by richpomfret** [comment]
@PatReynolds  to check and put link back in (and link here for testing).

**Comment by PatReynolds** [comment]
Systems page now has links to sub-pages and the Systems documenation folder on G.drive.

The roadmap looks very out of date.

Are the other documents fine to publish?

**Comment by richpomfret** [comment]
@richpomfret to check and ensure current roadmap is linked.

**Comment by richpomfret** [comment]
@richpomfret nudge to check.

**Comment by richpomfret** [comment]
@PatReynolds can you provide a link to the Systems page for me? Can't locate it on TEST3 to check - but the roadmap link should be this one - https://drive.google.com/open?id=1FNUijfW3586xE-m9W3U1gyxstSYwO7cD3jbqS9V33A8 (hate that it doesn't open in a new tab when accessed by the link in User profile!).

**Comment by PatReynolds** [comment]
Removed link to roadmap and "This link provides further information for FreeCEN volunteers." as these links are now from the top level of 'actions'.

Placed 'reasons for the change below the link to systems folder, as seems of lesser priority.

For review on test3 refinery: DRAFT Systems Documentation.
