### ISSUE TITLE
Validation - identify which fields are checked, and for what

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#706]
Who has a list of what VALDREV checks?
Have Vino/Lemon got a list of errors that need to be added?
Are there other checks which are made on FreeREG which could be added?

Later story about enhanching the check further in 1.5~ #140

Pat to list fields and work with Brenda what needs to be checked 

E0 U6 S7 C6: P19

**Comment by PatReynolds** [comment]
Notes from Rena, re Scotland Census and validation checking
1/ Main problem is Scholar has to be 16 or under: therefore Scotland transcribes 'scholar' as something like 'at school' or 'student (orig: scholar)'.

2/ All Scottish coordinators have had to add every Scottish parish /place name to a supplementary file as the one in valdrev lists only English places I think.  It may list Welsh as well.

3/ Married women in Scottish censuses sometimes put in both married and maiden names. Rena reports:
https://www.freecen.org.uk/search_queries/5e590a2ff493fd7056bc149e is found searching for either Mitchel or Ivel.  On Freecen1 I only get a result when I type in Mitchel / Ivel Margaret.

**Comment by geoffj-FUG** [comment]
Every field in CSVProc has been defined and a test. The Handbook now provides a description to the transcriber etc of what can or cannot be entered. There is not one list of tests applied to CSVProc fields.
The issues identified by Rena have been addressed. Scholars are no longer an error. However, there was some debate as to whether it even needed identifying as the entry had been transcribed and proofread. In the end there is a Warning as an Error creates a catchh 22 in CSVProc (It cannot be cleared and transcribed 'as is').  So it is now a Warning and needs Validating.
The supplementary file is no longer needed. The problem has been addressed in teh Place Names Database.
There is a description of how to handle Scottish married women in the Handbook.
Geoff

**Comment by PatReynolds** [comment]
Thanks, Geoff, that means this can now be closed.
