### ISSUE TITLE
CEN is using the same Chapman Code eliminations as REG

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#707]
While researching the Chapman Codes for REG I found that CEN is using the same elimination code list defined for REG this means that CEN2 is not offering the  'England and Wales Shipping',                               'Out of County', 'Overseas British', 'Overseas Foreign', 'Scottish Shipping' birth county options provided in CEN1.
REG also eliminates 'Unknown', 'Clwyd', 'Dyfed', 'Gwent', 'Gwynedd', 'Powys', 'Mid Glamorgan',                               'South Glamorgan', 'West Glamorgan', 'Borders', 'Central', 'Dumfries and Galloway', 'Grampian', 'Highland', 'Lothian', 'Orkney Isles','Shetland Isles', 'Strathclyde', 'Tayside', 'Western Isles'
Is that appropriate for CEN?

**Comment by Captainkirkdawson** [comment]
This was fixed when I fixed REG

It is running for basic checkout on test2

**Comment by Captainkirkdawson** [comment]
One further observation the birth and census counties INCLUDE Ireland. Is that appropriate?????

**Comment by FreecenBren** [comment]
I am not sure what you are doing anyway, but I do know that FreeCEN use the
CHP for Ireland, IRL, and all the Counties Irish Chapman codes, example for
Mayo, Limerick etc., etc., in the Birth County Column (CHP) and in the POB
column of course we enter the place of birth as well.
We get quite a few Irish people living in England, Wales and Scotland in
the 19th Century.
Not sure if that helps or not! Full list of CHP codes we use you will find
in the FiELDS document.

**Comment by Captainkirkdawson** [comment]
Thank you for the clarification on Birth County but what about Census counties? Do we have Census data for the counties in Ireland?

**Comment by FreecenBren** [comment]
Hi,

 

Not at the moment, but it is on Pats list for the future!

 

Brenda
