### ISSUE TITLE
Transcriber statistics now showing fewer signed-up transcribers than new transcribers in the last 30 days

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#708]
Find out what has happened to data and re-instate.

**Comment by Captainkirkdawson** [comment]
I am afraid no one can research this without far more information.

**Comment by Captainkirkdawson** [comment]
Only comment practical is to say there are ![tranns2.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/d54eeb95-932b-4493-8ecc-d3b13452b167)

**Comment by richpomfret** [comment]
Having issues accessing the stats currently - @Vino-S taking a quick look at that prior to us moving forward with or shelving this story.

**Comment by PatReynolds** [comment]
Still not able to access stats:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/ad5551b2-813f-4340-a87e-0b950ba8f54c)

**Comment by Captainkirkdawson** [comment]
Fix has yet to be deployed into production. We did not do a release after the last scrum as only 1 story had been declared ready

**Comment by PatReynolds** [comment]
What info is needed?

**Comment by PatReynolds** [comment]
Now appears to have been made live, so needs closing.
