### ISSUE TITLE
Do FreeCEN files have headers?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#711]
Looking at the initial text for updated FreeCEN coords, realised that some actions within FreeREG depend on headers.  Do CEN files have Headers in the same way as REG files? Are they different in any way?

This information will be needed in planning Validation.

**Comment by FreecenBren** [comment]
Not knowing what the header does in FreeREG makes it hard to understand the
question.
The only thing that FreeCEN have that could be construed as  Header(s) by
this order.
1. Census Year then by
2. Census County, and then by
3. Piece number
From that we then allocate it to a transcriber to start the Transcribing in
the pre designed Spreadsheet  ( Each of the 25 columns has a title.)

As I said not knowing FreeREG this can only be a guess.

**Comment by richpomfret** [comment]
@pat and @richpomfret to find out methodology for transcriber to make a change to something that has already been upload. Or perhaps @FreecenBren can assist?

**Comment by PatReynolds** [comment]
Example of header row (from FreeCEN1 example spreadsheet)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/ea3f6b57-88f8-4ada-8f8b-3c67f0cc6b24)

Additional fields needed in header row:
transcriber ID
image source (e.g. LDS)

**Comment by richpomfret** [comment]
Establish what a VLD file looks like and how a file changes when it gets processed (via CVS check etc).

**Comment by richpomfret** [comment]
Ability to see/view the VLD 'headers' now on TEST3 and will be deployed to production too.
