### ISSUE TITLE
Evidence Explained citation incorrect

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#713]
Currently: Free UK Genealogy "England, Scotland and Wales Census" database,(etc.)

Should be: Free UK Genalogy “General Register Office: 1891 Census Returns” database,(etc.)

I

**Comment by richpomfret** [comment]
Will be corrected when REG changes are deployed to CEN.

**Comment by richpomfret** [comment]
Not present on TEST3. Has this been deployed yet?
