### ISSUE TITLE
Coord can VIEW contents of pieces/vlds

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#714]
First step of bigger epic (#530) is to see if we can find a way for coords to view contents of a file online.

**Comment by Captainkirkdawson** [comment]
Initial comment. Access to the pieces metadata is presently available for the total database to the system administrator and technical roles through an augmentation of the database_coverage system. There is an edit capability for a piece though that interface and there is the ability to download the piece metadata in DAT and CSV formats. However it must be remembered that the database is reloaded monthly so edits may be meaningless unless the downloaded pieces are moved to FR1. There is no ability to view the records associated with the piece.

**Comment by Captainkirkdawson** [comment]
Brenda commented `We will continue to do the amendments as we do at present until such time as things change.
At present the COORDS amend the VLD, send me a copy, and at the FreeCEN ONE  upload slot, the amended VLD,s are sent to Lemon in a different folder to the NEW VLD,s. 
Lemon then removes the current one in FC1 Database, and uploads the newly amended VLD.
As you quite rightly say, not much point in amending the VLD in FC2 as it will be replaced by the amended version from the FC1 upload.
The future method/system will sort that out, as and when, that stage is reached.`

**Comment by Captainkirkdawson** [comment]
Just to clarify. My initial comment was about the Pieces and the associated freecen1_fixed_dat_files and their entries not the VLD files and their entries. I have yet to look at that aspect.

**Comment by Captainkirkdawson** [comment]
A first cut at the show of Pieces, DAT, VLD and Places is available on test3 for evaluation

**Comment by FreecenBren** [comment]
Unfortunately it will not let me into Test 3 anymore.  
I have not been in for a while so not sure if you have moved the site or renamed it.
Can someone send me a link please so I can try again.

**Comment by richpomfret** [comment]
Here you go: https://test3.freecen.org.uk/

We now need a username and password to access our Test sites, shall email that directly to you.

**Comment by Captainkirkdawson** [comment]
@FreecenBren  the change to the access to the test sites was the subject of the message sent to  with the subject `Test servers from Kirk Dawson of FreeCEN. Reference 145285686`

**Comment by Captainkirkdawson** [comment]
@FreecenBren @Vino-S @richpomfret have improved the Pieces displays for the County Coordinator on **test3**.
Log on and select the Manage Counties action
![manage_pieces0.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/8ea49656-6b71-4d46-bd3c-b02ee7f39d15)
The systemtem administrators can select a county; CCs go straight to theirs.
Select Manage Pieces
![manage_pieces1.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/340a3fca-9e5f-4a71-acbe-aa70ae93be05)
A scrollable display of the pieces is provided. 
![manage_pieces2.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/0d0676d3-5bcc-4836-87d4-0c867528be0e)
You can select the **show** for a little more info
![manage_pieces3.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2c3d7f56-dc03-4d8b-adbd-dd86fe46f87c)
This has links to the Place information and the freecen1_fixed_dat_entry.

**Comment by richpomfret** [comment]
Fine to deploy 1st iteration of this. We can then refine and get more input as appropriate.
