### ISSUE TITLE
Are Newark and Newark on Trent the same District in 1841

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#716]
The drop-down list/records for 1841 have both 'Newark' and 'Newark on Trent' as names.  Is this correct? A mis-transcription? If one (or more) sub-districts called the district by a different name, do we show both?  Or show one name that finds both?

Similarly, why do some District names start with a number?

**Comment by FreecenBren** [comment]
They are both.
 

This is just one example from the National Archives as per our PARMS.
Other census years are the same

Registration Sub-District 3 Newark. P
PIECE NO. RG092468  1861 Census


Reference:  and Description  

Description:
Registration Sub-District 3 Newark.
Parish: Newark; Hamlet: Newark-upon-Trent.
 
 
Example of an 1841 Census.


HO107868
Newark
Newark upon Trent   East Stoke

**Comment by richpomfret** [comment]
@PatReynolds to close? Assuming the question is now answered.

**Comment by PatReynolds** [comment]
Thanks, Brenda, I don't think I asked the question correctly.

This is what I'm talking about:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/4e38636c-efaf-4cca-b3d9-9c85debb2ebf)

What I wanted to know is why both "Newark" and "Newark on Trent" show as registration districts for the 1841 census.  https://www.ukbmd.org.uk/reg/districts/newark.html suggests that "Newark on Trent" was NEVER a census district, it was always "Newark", there was always a sub-district "Newark", and always a Civil Parish "Newark on Trent".  

So .. I think some records from the 1841 have been mis-transcribed as being in the "Newark-upon-Trent" registration district- and a are in fact in "Newark" - e,.g
https://www.freecen.org.uk/search_records/5c38d140f4040b8d325094ad/john-smith-1841-nottinghamshire-newark-on-trent-1776-?locale=en

and
https://www.freecen.org.uk/search_records/5c38d149f4040b8d32509d6b/john-smith-1841-nottinghamshire-newark-on-trent-1810-?locale=en

**Comment by PatReynolds** [comment]
Thanks, Brenda!  I'm still not sure whether what we are seeing is an enumarators' error, or a National Archives error.  Or whether it is not an error, but that Newark-on-Trent, Newark, and Bassetlaw (or any other of the Nottinghamshire Districts) are three separate districts, and there is  no error.  
Do you think, if it is an error, we should (for clarity) on the search form just list "Newark (on Trent)" as the district?

**Comment by FreecenBren** [comment]
I believe that in 1841 there was a Newark and a Newark-on-Trent.
We cannot decide that the National  Archives got it wrong.
It is not our job to decide one way or the other the course of History. We can only record what we have. 
I have had a look at the Census images and it clearly has them both written on the images.
 
1.	Each PIECE consists of several ED’s.  Each ED has an introduction page. 


2.	There are 2 PIECES in question.


3.	Attached are copies of some of them.
a.	Some are the ED pages at the start of each ED. This is where we find the ED number etc.,
b.	The other types are copies of the actual Census pages. 
Each one of these shows at the top, the ED the name that we use for the transcription, either Newark or Newark-on-Trent.


4.	These exonerates the  NA as the enumerator has written Newark or Newark-on-Trent very clearly.
The National Archives produced theirs from these images from the 1841 census.



HO107/862
Newark
Balderton , Barnby-in-Willows , Coddington , Cotham , Elston , Farndon , Girton , Hawton , Kelvington , Langford , North Clifton , Shelton , Sibthorpe , South Collingham , South Scarle , Staunton , Syerston , Thorney , Winthorpe , Torpe

HO107/868
Newark on Trent
East Stoke , Newark on Trent
 
It is FreeCEN’s objective to record AS IS. 
That is what we have done.  They are not Enumerator errors nor the National Archives errors.
These are facts and we recorded them as they were written in 1841, some 160 years+  ago.
In 1841 Newark was a district. If it changed by 1851, OK so be it.
Why cannot we have both!  Let’s not change History, that was not FreeCEN’s objective.
 
 
 
  _____  

On Thu, 10 Oct 2019 at 17:03, PatReynolds <notifications@github.com <mailto:notifications@github.com> > wrote:
Thanks, Brenda! I'm still not sure whether what we are seeing is an enumarators' error, or a National Archives error. Or whether it is not an error, but that Newark-on-Trent, Newark, and Bassetlaw (or any other of the Nottinghamshire Districts) are three separate districts, and there is no error.
Do you think, if it is an error, we should (for clarity) on the search form just list "Newark (on Trent)" as the district?

**Comment by FreecenBren** [comment]
Rest of the images too large to send them all
 
From: bowbren2@gmail.com <bowbren2@gmail.com> 
Sent: 10 October 2019 19:32
To: 'FreeUKGen/FreeCENMigration' <reply@reply.github.com>
Subject: RE: [FreeUKGen/FreeCENMigration] Are Newark and Newark on Trent the same District in 1841 (#716)
 
 
I believe that in 1841 there was a Newark and a Newark-on-Trent.
We cannot decide that the National  Archives got it wrong.
It is not our job to decide one way or the other the course of History. We can only record what we have. 
I have had a look at the Census images and it clearly has them both written on the images.
 
1.	Each PIECE consists of several ED’s.  Each ED has an introduction page. 


2.	There are 2 PIECES in question.


3.	Attached are copies of some of them.
a.	Some are the ED pages at the start of each ED. This is where we find the ED number etc.,
b.	The other types are copies of the actual Census pages. 
Each one of these shows at the top, the ED the name that we use for the transcription, either Newark or Newark-on-Trent.


4.	These exonerates the  NA as the enumerator has written Newark or Newark-on-Trent very clearly.
The National Archives produced theirs from these images from the 1841 census.



HO107/862
Newark
Balderton , Barnby-in-Willows , Coddington , Cotham , Elston , Farndon , Girton , Hawton , Kelvington , Langford , North Clifton , Shelton , Sibthorpe , South Collingham , South Scarle , Staunton , Syerston , Thorney , Winthorpe , Torpe

HO107/868
Newark on Trent
East Stoke , Newark on Trent
 
It is FreeCEN’s objective to record AS IS. 
That is what we have done.  They are not Enumerator errors nor the National Archives errors.
These are facts and we recorded them as they were written in 1841, some 160 years+  ago.
In 1841 Newark was a district. If it changed by 1851, OK so be it.
Why cannot we have both!  Let’s not change History, that was not FreeCEN’s objective.
 
 
 
  _____  

On Thu, 10 Oct 2019 at 17:03, PatReynolds <notifications@github.com <mailto:notifications@github.com> > wrote:
Thanks, Brenda! I'm still not sure whether what we are seeing is an enumarators' error, or a National Archives error. Or whether it is not an error, but that Newark-on-Trent, Newark, and Bassetlaw (or any other of the Nottinghamshire Districts) are three separate districts, and there is no error.
Do you think, if it is an error, we should (for clarity) on the search form just list "Newark (on Trent)" as the district?

**Comment by PatReynolds** [comment]
For decision: do we want to add this information to Help, or just close?

**Comment by PatReynolds** [comment]
Closing as new 'help' story created
