### ISSUE TITLE
Improve FC2 database error report

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#717]
Request from Brenda - report output is currently a .txt and tricky for her to decipher. 'A simple spreadsheet similar to FC1 would do nicely', see attached. ![Screen Shot 2019-08-05 at 12.23.20.png](https://images.zenhubusercontent.com/5c8ff5bf777e5f767e486db5/d637d639-0640-4c1a-b669-991687fe6cbf)

**Comment by richpomfret** [comment]
We could link this to the story @Captainkirkdawson is currently working on (#714)

**Comment by Captainkirkdawson** [comment]
@FreecenBren @Vino-S @richpomfret A first version has been deployed to *test3*. Currently implemented as system administrator action (brenda, vino , rich and myself). Can be implemented at county level if desired.
On login ino *test3*. Select the FreeCen Errors action
![freecen_errors.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/dd444135-481e-4981-b373-cc5496e371e7)

**Comment by richpomfret** [comment]
@Vino-S did you also contribute some work or create a report here? Brenda has mentioned that you sent something through..
