### ISSUE TITLE
Coordinators (& transcribers?) can see list of other coordinators

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#719]
This could be addressed by internal comms system, if so please close and I'll communicate this to volunteers.

**Comment by Captainkirkdawson** [comment]
All Members on both CEN and REG can send messages to coordinators 
![list](https://user-images.githubusercontent.com/2874694/63275752-52e60a00-c25f-11e9-9c5e-721afdd99d63.JPG)

**Comment by DeniseColbert** [comment]
Sorry Kirk I mean for example, that the SOM Coord can see who the DBY Coord is (and send them a message if the list exists in the Communication system).

**Comment by Captainkirkdawson** [comment]
Compose communication, select send, select county coordinators, select the specific person or persons from the list
![lista](https://user-images.githubusercontent.com/2874694/63355938-3364e500-c324-11e9-888c-fb3e3c0eae2f.JPG)

**Comment by DeniseColbert** [comment]
Wonderful, thank you. Closing.
