### ISSUE TITLE
Revise Search is buggy

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#72]
Pat reports:

Searching for Alcock in Durham.  Tried the first registration district over the border (Dalton on Tees), but got a null.  Hit 'revise search' to try another rd, and there appears to be a stray bit of code on the screen, and the list of rd does not appear. I've attached a screen shot.

**Comment by benwbrum** [comment]
I believe that previous work has fixed this problem, as I am not able to duplicate it on test2.

**Comment by PatReynolds** [comment]
Stray code on search page still there (between Place and (i) symbol), but revising the search now works fine.
