### ISSUE TITLE
Enhance On Line Error Report 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#722]
Based on usage enhancements are required

**Comment by Captainkirkdawson** [comment]
Some enhancements made as a result of stories #726 and #727 others are being considered. 
![problems with files.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2f7fb19c-bd51-48c0-b86e-a6c3222db76e)

**Comment by richpomfret** [comment]
@AlOneill request to add in commas to help interpret the large numbers (totals). Also right-aligned for totals to help stand-out.

**Comment by Captainkirkdawson** [comment]
Delimiters added to totals; see Database Statistics action for members on test3
Delimiters will be apparent in the error message after database creation with changed code

**Comment by richpomfret** [comment]
Done and closing.
