### ISSUE TITLE
Make the freecen_upload code detect and report non UTF-8 characters as data errors and continue processing.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#725]
E 2 U6 S8 C6: P22

**Comment by AlOneill** [comment]
From a transcriber's perspective, CEN does not use UCF. However, a "?" is allowed in Notes field only.

**Comment by Captainkirkdawson** [comment]
My mistake meant to say UTF-8

**Comment by Captainkirkdawson** [comment]
Have added code to ensure conversion to UTF-8. Tested on my development setup

**Comment by Captainkirkdawson** [comment]
Code tested on a test3 freecen update. Ran OK. Difficult to test. So suggest the fix be deployed.

**Comment by richpomfret** [comment]
Let's deploy.
