### ISSUE TITLE
Correct undefined method `match' for nil:NilClass  at freecen1_vld_transformer.rb:23 in block in transform_file_record`.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#726]

**Comment by Captainkirkdawson** [comment]
This occurs if the uninhabited flag is nil.

**Comment by Captainkirkdawson** [comment]
It appears that a number of the system crashes are caused by attempting to process incorrect data. This happens if the file does not include complete records. The current code splits a file into records of 299 characters and then populates the fields according to the stated record layout. If the file is incorrect then it assigns wrong information to the fields within a record.
I propose to check that the VLD file is actually a multiple of 299 characters in length before processing the records.

**Comment by Captainkirkdawson** [comment]
So far I have confirmed that 2 files are of an incorrect size

**Comment by Captainkirkdawson** [comment]
@lemon-ukgen your comments on those 2 files and their history would be welcome. Did they load on Cen1?

**Comment by lemon-ukgen** [comment]
The first was updated in the August build:
```
[update-pieces] replace - BRK/rg121002.vld (BRK, rg121002.vld)
[update-pieces] COPY /raid/freecen/inbound/replace/BRK/rg121002.vld -> /raid/freecen/pieces/BRK/rg121002.vld
```

The second was updated in June:

```
[update-pieces] replace - GLS/rg091797.vld (GLS, rg091797.vld)
[update-pieces] COPY /raid/freecen/inbound/replace/GLS/rg091797.vld -> /raid/freecen/pieces/GLS/rg091797.vld
```

The FreeCEN1 build appears to process both ok:

```
[05:38] rg091797.vld - 5921 records
[05:48] rg121002.vld - 4904 records
```

**Comment by Captainkirkdawson** [comment]
Interesting. The reported file length of BRK/rg121002.vld is 1,466,296 on colobus, brazza and on my copy however the reported file size was 1,466,272. I took another copy from colobus and processed it and the reported size this time is 1,466,273 so perhaps the ftp transfer is dropping some bits. It will be interesting to see what we get in the test3 testing

**Comment by Captainkirkdawson** [comment]
Have run the freecen update on test3. Some 5 files were found to have an incorrect file length which would have given rise to system crashes and the file not processed. Information on them sent to @FreecenBren 
As part of solution the error field for a piece was enhanced. This identified additional files that need to be corrected.
Suggest this is ready for deployment and be used for the next production update.

**Comment by richpomfret** [comment]
Let's deploy.
