### ISSUE TITLE
Process the 18 VLD files previously reported as Errors not subsequently processed

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#727]
ERY/rg093557.vld, GLS/rg091797.vld, HAM/RG120865.VLD,  LAN/rg092663.vld, LAN/rg092682.vld, LAN/rg092696.vld, LAN/rg092705.vld, LAN/rg092720.vld, LAN/rg092721.vld, LAN/rg092722.vld, LAN/rg092728.vld, MDX/RG090798.VLD, NTT/rg103530.vld, NTT/rg103534.vld, 
SFK/RG121477.VLD, SOM/RG121886.VLD, SOM/RG121889.VLD, SOM/RG121890.VLD, WRY/rg093302.vld, WRY/rg093303.vld, WRY/RG104320.VLD, WRY/RG104534.VLD, WRY/RG104576.VLD, WRY/RG104603.VLD, WRY/RG104671.VLD, WRY/RG104719.VLD, WRY/RG104725.VLD all failed to process into the database because `waiting for replication timed out`.  All of these **EXCEPT** the 8 LAN are showing as errors after the latest update. The replication timed out issue has been fixed so why **were the LAN files apparently and the other 18 not processed in the August update** ??? 

E2 U6 S7 C5: P 20

**Comment by FreecenBren** [comment]
They are all still in the Amended Dropbox folder that Lemon picks them up
from so this will have to be referred to Lemon.
The 8 LAN ones have been a problem since January and beyond.
We could not find the problem
So 3 weeks ago I stripped one of them right back myself and found the
problem. So then did all 8 and we kept our fingers crossed.
They all went through as you see.

The others were done by myself and COORDS according to the County.
I will check the  LIN ones tomorrow (off out now) and see which version is
in FreeCEN ONE ie. Before the amendment or after the amendment.
Then we will know if Lemon did them all or not.

**Comment by Captainkirkdawson** [comment]
A review of the code shows that once a file has been processed it will never be reprocessed unless the file is changed. So if the processing failed for some system crash or other reason the current code will ONLY reprocess the file if it is changed in some way so that the digest is different. The update processing code needs to be modified to force reprocessing of the file if its piece status in not Online.

**Comment by lemon-ukgen** [comment]
Most of the VLDs @Captainkirkdawson mentions were not in the August update, which was for the following:

```
new/DBY/RG122778.VLD
new/CUL/RG124312.VLD
new/ERY/rg093564.vld
new/SFK/RG121495.VLD
new/SFK/RG121445.VLD
new/SFK/RG101729.VLD
new/STS/RG092010.VLD
new/LEI/RG122530.VLD
new/LEI/RG122515.VLD
new/DOR/RG121640.VLD
new/DOR/HO107277.VLD
new/NRY/rg104814.vld
new/MGY/rg094264.vld
new/SOM/RG102398.VLD
new/SOM/RG102477.VLD
new/SOM/RG102479.VLD
new/SOM/RG102482.VLD
new/SOM/RG102508.VLD
new/SOM/RG102506.VLD
new/SOM/RG102446.VLD
new/SOM/RG121951.VLD
new/SOM/RG121932.VLD
new/SOM/RG102491.VLD
new/KEN/rg090534.vld
new/KEN/rg100899.VLD
new/KEN/rg100898.VLD
new/KEN/rg090516.VLD
new/GLA/rg105383.vld
new/WRY/rg104485.vld
new/WRY/RG104444.VLD
new/WRY/rg104297.vld
new/WRY/RG104443.VLD
new/WRY/RG104493.VLD
new/WRY/rg104679.vld
new/WRY/RG104491.VLD
replace/LEI/RG092291.VLD
replace/LEI/RG103293.VLD
replace/LEI/RG103275.VLD
replace/BRK/rg121002.vld
replace/MLN/HS539685.VLD
replace/NTT/rg103530.vld
replace/STI/HS513490.VLD
replace/NBL/RG093877.VLD
replace/SOM/RG121890.VLD
replace/SOM/RG121886.VLD
replace/SOM/RG121889.VLD
replace/SOM/RG091687.VLD
replace/DEV/ho511865.vld
replace/LIN/RG092373.VLD
```

The intersection with Kirk's list:

```
replace/NTT/rg103530.vld
replace/SOM/RG121890.VLD
replace/SOM/RG121886.VLD
replace/SOM/RG121889.VLD
```

(All the LAN VLDs were processed in the two July updates.)

```
[update-pieces] replace - NTT/rg103530.vld (NTT, rg103530.vld)
[update-pieces] COPY /raid/freecen/inbound/replace/NTT/rg103530.vld -> /raid/freecen/pieces/NTT/rg103530.vld
[update-pieces] replace - SOM/RG121886.VLD (SOM, RG121886.VLD)
[update-pieces] COPY /raid/freecen/inbound/replace/SOM/RG121886.VLD -> /raid/freecen/pieces/SOM/RG121886.VLD
[update-pieces] replace - SOM/RG121889.VLD (SOM, RG121889.VLD)
[update-pieces] COPY /raid/freecen/inbound/replace/SOM/RG121889.VLD -> /raid/freecen/pieces/SOM/RG121889.VLD
[update-pieces] replace - SOM/RG121890.VLD (SOM, RG121890.VLD)
[update-pieces] COPY /raid/freecen/inbound/replace/SOM/RG121890.VLD -> /raid/freecen/pieces/SOM/RG121890.VLD
```

Not sure if we _are_ using the digest code, since that's in `MakeDB3.pl` but the `Makefile` uses `MakeDB2.pl`. The text from

```
print Util::TS()."$file - $linedata[2] records - from saved \n";
```

never appears in the output, at least. I may be looking at different code than Kirk though, and this is my first time looking at it!

**Comment by Captainkirkdawson** [comment]
@lemon-ukgen the code does use the digest to decide whether or not a file has been changed. If unchanged it does not process it.  Unfortunately if there was a problem with the file we note there is an error in the piece record and store the digest. That means the file never gets processed.
I am currently testing a small change that forces a file in for reprocessing if its piece status is NOT Online. This will ensure we try to reprocess those files on a subsequent update. It is currently working OK on my development setup so the next step is to test on vervet. You may also want to have a look at #726 for another issue with processing

**Comment by lemon-ukgen** [comment]
Confirmed, we _are_ talking about different code ( me: FreeCEN1, you FreeCEN2, presumably :)

Given that, I'm unsure what I am being asked to do here.

**Comment by Captainkirkdawson** [comment]
I know not the answer to why you were added to the story. As far as I can tell it is a purely Cen2 issue

**Comment by Captainkirkdawson** [comment]
Have added code to the freecen update processor that reprocesses any file that had an piece status that was NOT Online.
Works fine in multiple tests on the freecen update on test3. 
Suggest this be deployed before the next production update of freecen

**Comment by richpomfret** [comment]
Let's deploy.
