### ISSUE TITLE
Warn user of reset password feature that email address does not exist in our database146399971 Reset password (Geoff)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#729]
Issue reported by **somt.cen** at 2019-08-22 10:39:31 UTC
Time: 2019-08-22T10:32:37+00:00
Session ID: 0757add5d063589f0789fde599c316bf
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freecen.org.uk/freecen_coverage?locale=en](https://www.freecen.org.uk/freecen_coverage?locale=en)
Reported Issue:
When I went to reset my password at the login screen I entered the incorrect email account (it was a valid one but not the one I use for FreeCEN. 
I asked to be sent a password reset. I was not sent one (which was correct). However neither was I told that the email account was unknown.
I realised what I had done so I entered another email address with the incorrect country at the end. The email address does not exist (Yes, I am sure). Again I was not told that the email address entered was invalid.
This is an important message when someone has got their email addresses mixed up and therefore cannot sign in. The natural thing is to fight with the password (or it is for me).
Regards
Geoff Jarvis    

![Screenshot](https://www.freecen.org.uk)

E0 U 3 S5 C8: P 16

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Additional wording added to password reset and to the form for profile editing

**Comment by geoffj-FUG** [comment]
Kirk
OK
Can be closed
Geoff
