### ISSUE TITLE
Update Help to cover absence of citations on next/previous dwellings.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#730]
A  note needed in help to explain why there is no citation button on records found through next/previous dwelling. 

Insert between "using the search page" and "exploring your results":

Why is there no citation button on every result?
If you have moved to a previous or next dwelling, there is no citation button because the way we generate the citations means that they refer to the original dwelling found, not the dwelling being viewed.  If you want to generate a citation for a person found in the next/previous dwelling, please search for that person: the citation generator will then be there, and generate the correct details for this person.

P0 U3 S5 C9:P17

**Comment by PatReynolds** [comment]
Done on systemwide draft on FreeREG.

**Comment by DeniseColbert** [comment]
Is this still something for @dhousman to take a look at?

**Comment by PatReynolds** [comment]
Yes, to proof, as per the instructions (may need to revise instructions, or the text).

**Comment by PatReynolds** [comment]
Assigned to @dhousman .  Please let me know if you have any questions, David.

**Comment by dhousman** [comment]
OK @PatReynolds I am looking at refinery and the help page, but I don't see what this task is describing. From the description, it sounds like he's talking about a search result page. I checked the pages in refinery, and I can't figure out what is generating the search/search result page. Can you tell me where i should be looking?

**Comment by DeniseColbert** [comment]
@PatReynolds I answered David's query above in our Meet.

**Comment by DeniseColbert** [comment]
@dhousman could you hold off on adding the text in test3 Help page until after next Weds Scrum, please? There's a lot of changes being made to the Help and it seems we may not be ready for this one just yet. We can update you in the Scrum if you are able to join us.

**Comment by PatReynolds** [comment]
Hi @dhousman  Run a search, and then move from the detailed results page to the 'next dwell'ing' (or 'previous dwelling' and you will see that the citation generator does not function.  Please let me know if the draft help doesn't make sense.

**Comment by PatReynolds** [comment]
@dhousman, Alison is going to make a new DRAFT which you can copy and edit, as she is bringing over some code from FreeREG and wants you to work on that, rather than the existing page.

**Comment by DeniseColbert** [comment]
In Scrum, @PatReynolds advised that this text needs to be added to a DRAFT of the Help page (Pat created in Scrum), in between _**Using Filters**_ and **_Exploring your Results_**
@AlOneill is your DRAFT Help with Citations page still relevant for #760 ?

**Comment by richpomfret** [comment]
@AlOneill any update or help needed on this one?

**Comment by AlOneill** [comment]
@richpomfret Work stalled until UCF documentation is complete — then this will be my next task.

**Comment by AlOneill** [comment]
Updates done and pages are sync-ready.

**Comment by AlOneill** [comment]
This appears to be a duplicate of #760 …

**Comment by PatReynolds** [comment]
Not a duplicate, Alison, but could be part of it - I will add to that, and close this

**Comment by PatReynolds** [comment]
Duplicate, and done, so clusing
