### ISSUE TITLE
Database coverage on a mobile device is unreadable 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#732]
The format used to display on a mobile device is the same as for  desktop. As such it is unreadable

e1 U 4 S 9 C5: P19

**Comment by richpomfret** [comment]
We can make it scrollable if @Captainkirkdawson you feel that will suffice?

**Comment by Captainkirkdawson** [comment]
I am not a user of CEN hence cannot comment on whether scrollable would be adequate. 
Certainly would make it usable in its current form.
In all other cases we avoided Tables on mobile devices.  
The best solution technically is likely a selection of year and country and a a simple display of the one record. Browsing with a 500 entry table is bad news on a mobile

**Comment by PatReynolds** [comment]
On Google Pizel 3Xl, the table is scrollable, as is the 'details' table.  The two graphs pages are  not scrollable, but viewable in horizontal view.  Agree that a page to select year and county (with resulting page having links to the two graphs) is an improvement.  Graphs will still need to be scrollable for smaller phones. Will create new story for improvement.

**Comment by Captainkirkdawson** [comment]
I really should learn not to comment on the fly. Yes the current basic table is scrollable hence my comment about it `Certainly would make it usable in its current form.` is incorrect.
At the same time the original comment about the need for improvement remains. I would never use the current display on a phone

**Comment by PatReynolds** [comment]
New Records pages work fine on a Pixel XL using DuckDuckGo (have found it impossible to test on Chrome as chrome won't recognise any website it can't crawl, it seems...).
