### ISSUE TITLE
Different ad units for different pages/actions?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#733]
Cen defined different fields for different pages/actions that originally pointed to different ad units
advert_key:
    data_ad_client:
    data_ad_slot_header:
    data_ad_slot_google_advert:
    data_ad_slot_coverage:
    data_ad_slot_fullwidth:
originally these were set to different ad units
template_set: 'freecen'
  advert_key:
    data_ad_client: *****************
    data_ad_slot_header: "7868124617"
    data_ad_slot_google_advert: "2003577939"
    data_ad_slot_coverage: "2287166112"
    data_ad_slot_fullwidth: "4565274273"

These were all responsive and overflowed our defined containers which were 728x90

Hence part of the solution was to use fixed ad units. **Since I am unaware of the value of defining different ad units with the same size** I gave them all the same ad unit

The fix was
advert_key:
    data_ad_client: ******************
    data_ad_slot_header: "2287166112"
    data_ad_slot_google_advert: "2287166112"
    data_ad_slot_coverage: "2287166112"
    data_ad_slot_fullwidth: "2287166112"

Clearly if we wish we can define different add units if there is any economic benefit

**Comment by richpomfret** [comment]
Already been deployed to live.
