### ISSUE TITLE
Search performance report not working

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#736]
Search performance reporting not working. - 

E0 U6 S7 C6: P19

**Comment by Captainkirkdawson** [comment]
As far as I am aware the report is working. (Other than yellow heading!)
![search performance.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2d3ae449-f8cc-4610-a6d9-3af95448e48c)
