### ISSUE TITLE
Add to statistics on searches

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#737]
In comparison with statistics on  FC1
The number of searches could not be performed because the server was busy, resulting in the Server is busy message - not available on FC2 - (low priority)

E1 U1 S3 C?7: P12

**Comment by PatReynolds** [comment]
@Captainkirkdawson is this stat still needed?

**Comment by Captainkirkdawson** [comment]
The reports provide this information. Suggest it be closed

**Comment by PatReynolds** [comment]
I agree, Kirk
