### ISSUE TITLE
Check that statistics on www16 are working

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#738]
Check, post merge that statistics on test16 are working :
site statistics (number of searchers/time)
% last name vs all searches
% first name vs all searches
% max results vs %no results vs all searches
% all (birth?) county searches vs all searches
% date searches vs all searches
% specific year vs all searches
% place (district), % place+nearby vs all searches
searches total (for last 9 days)

E0 U2 S7 C6: P15

**Comment by Captainkirkdawson** [comment]
I do not understand the issue. The seach_statistics reports will be the same regardless of the production server being accessed. ie www , wwwnn 
Do not understand reference to test16. There is no such server. We have the www , wwwnn and test2 or test3.
test2 and test3 will produce zero results as there is no rake task being run in those environment. Do you wish for one

**Comment by PatReynolds** [comment]
http://www16.freecen.org.uk/search_statistics
Sorry, it was www16 not test16 ...

**Comment by Captainkirkdawson** [comment]
Noted. Changed title, As far as I am aware all wwwnn accesses will provide identical results to www. Is this story needed?

**Comment by helhyde** [comment]
I'll check this tomorrow. Please assign me.

Executive Director, Free UK Genealogy

**Comment by PatReynolds** [comment]
Page displays fine, thank you.  The percentage of last name searches to all searches looked weird until I recognised that the scale ran from 99% to 100%.

**Comment by PatReynolds** [comment]
Also, no difference between www16 and www - I have no idea why we ever used www16 (only used fo this feature, afaik), but one less thing to remember.
Should I make a link from https://test3.freecen.org.uk/site_statistics? (or somewhere)? Then would not need to even remember it.

**Comment by Captainkirkdawson** [comment]
The only people who need direct access to a specific server are the developers. We need to be able to check a specific server when we role out a release. I suggest we close
@PatReynolds if you want to see those graphics they are there for production. Bookmark that. ie 
https://www.freecen.org.uk/search_statistics
In systemwide 118 I ask a question `Should we provide access to the search_results graphics we produce?`
