### ISSUE TITLE
"Your Actions" page, the "Recent Changes/Coming Soon" part is one large link to security policy

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeCENMigration#739]
On test3, the whole of the lower part of the "Your Actions" page is a link to the Security Policy! It has link styling throughout (all text is orange).

**Comment by richpomfret** [comment]
@AlOneill could you confirm this is now fixed?

**Comment by richpomfret** [comment]
This has now been removed so closing.
