### ISSUE TITLE
Data is uploaded into FreeCEN2, and corrected there,  and not FreeCEN1. 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#741]

**Comment by Captainkirkdawson** [comment]
CSVProc can handle the traditional format of csv file so there is no basic requirement to load a VLD file.
CSVProc will download the traditional headed csv file in the correct format for the year.
We can download a VLD file from CEN2 in csv format and it can be processed by CSVProc
Suggest this be closed.

**Comment by Captainkirkdawson** [comment]
CSVProc and all its components have been deployed
Suggest we close and deal with new issues and problems as identified
