### ISSUE TITLE
Create Help section for Newark/Newark on Trent

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#746]

**Comment by PatReynolds** [comment]
FreeCEN1 search is free text, and looks for strings anywhere, e.g. search for "pauper" finds "Pauper - Lab's. Widow " and "Farm Labs Widow/pauper", as well as "Pauper".

For this version, I think implement as is at the moment.  But Phase 2, implement a search which uses a structure created from the various census models (see http://www.visionofbritain.org.uk/census/EW1911GEN/5 for details of changes from 1841 to 1911).

**Comment by AlOneill** [comment]
@PatReynolds The "Census location" section of the "Help", 2nd para, ends rather abruptly with:

"We use the exact names and spellings that were used in the Census records we transcribe.  For example, " [sic]

The 3rd para starts with"
"You may search in up to three specific counties, … "

Did the example not get pasted, or did you abandon it?

**Comment by AlOneill** [comment]
@PatReynolds Have made the assumption that the trailing sentence in the 2nd para was an oversight and deleted it.

There were 3 separate updates to this page, and the section on Filters is urgent, so had to act fast — there are still a few hrs to correct it if my assumption was wrong.

**Comment by PatReynolds** [comment]
UPDATED Comment: I thought this was on Filtering not "the Newark issue".  That is fine, thank you.

**Comment by richpomfret** [comment]
Now done and deployed so closing.
