### ISSUE TITLE
Unnocupied dwelling (possibly) breaks FC2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#748]
Trying to find an unnocupied dwelling for testing in another story, I used 'next dwelling' feature on FC2, and got as far of Christopher Owen in Hardingstone, Northamptonshire.  Moving to next record generates an error: is this an empty dwelling?  In the other direction, household before Ernest Jolley generates an error: is this an empty dwelling?  Separate issue needs to be created for this. 
Trying in Scarborough, 1861, Moved back to William Dickinson,  13 Lower Conduit Street, and moving back further (to lower street numbers) generated the error.

Implementing #690 may clarify this issue.

**Comment by geoffj-FUG** [comment]
See story #1432

**Comment by geoffj-FUG** [comment]
This is looking OK with the latest upgrade.
I have asked Chris Mahoney to re-download a piece that he had experienced problems with and see whether the problem has been rectified.
Geoff

**Comment by geoffj-FUG** [comment]
This story was resolved by #1432
Geoff

**Comment by geoffj-FUG** [comment]
I have retested Pat's routine and it all now works OK. I suspect the problem was eliminated when we changed the way that the system sees households imported from FC1. I am therefore closing this story.
Geoff
