### ISSUE TITLE
Add Marital Status search

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#755]

**Comment by Captainkirkdawson** [comment]
Assuming this is simply a filter of a broad search then it is relatively straightforward

**Comment by Captainkirkdawson** [comment]
The rake task shows the following contents for this field

1841 "-"
1851 "M", "U", "W", "-", "S", "Y", "F"
1861 "M", "-", "U", "W", "S", "F", "2", "N", "_", "E",  "X", "I", "1", "7", "3", "4", "8", "6", "5", "9"
1871 "M", "U", "-", "W", "S", "F", "Y", "Q", "N"
1881 "U", "M", "-", "W", "S"
1891 "M", "S", "W", "-", "U",  "D", "0", "F", "6"
Totals "-", "M", "U", "W", "S", "Y", "F", "2", "N", "_", "E", "X", "I", "1", "7", "3", "4", "8", "6", "5", "9", "Q", "D", "0"

CEN1 provides 4 options Any, Married, Widowed and Single

It would be useful to know the mapping of the codes and what we wish to implement

**Comment by FreecenBren** [comment]
Marital Status can only be, 
W = Widow or Widower
M = Married
U =- Unmarried
S= Single
If none of these none should be entered.
 
Would like to see a PIECE that they were used in and how they got through in the first place.
 
Not sure where you got the ‘Any’ from

**Comment by Captainkirkdawson** [comment]
This is the CEN1 Search selection for Marital status
![any.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/0921f02a-9cbe-48c6-a2f5-486cc8a1f28a)

All I can tell you is what is in my post is what is actually in the field; which piece is beyond the scope of the story or the task

**Comment by FreecenBren** [comment]
Strange that as Rick Parsons has it on the Incens page
Q M 143 1 Condition (M, S, U, W or -)

https://west-penwith.org.uk/fctools/doc/reference.html

And the Fields PDf that we go by now has it as

Column M
(Marital)
Status
Default
Hyphen
'-'
One character
Do not make assumptions!
Enter a single letter m, s, u, or w (Married, Unmarried, Single, or
Widowed) as defined on the Census Page.
If the Enumerator left it blank - so must you.
Any other letter will be rejected, at conversion, as 'invalid'

**Comment by PatReynolds** [comment]
Implement dropdown as suggested (with default being Any Status)

**Comment by Captainkirkdawson** [comment]
Code available for evaluation on test3 CEN.

**Comment by PatReynolds** [comment]
This works as expected, thank you.

**Comment by Captainkirkdawson** [comment]
Deployed
