### ISSUE TITLE
Add Disability Search

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#757]

**Comment by Captainkirkdawson** [comment]
Assuming this is simply a filter of a broad search then it is relatively straightforward

**Comment by FreecenBren** [comment]
Column  W on the FIELDS document for Disabilities says this.
This is what transcribers go by which replaced INCENS instructions

*Column W*
*Disability Blank *
*Up to six characters*
*Strictly, the Census asked only "Deaf, Dumb, Blind"; many Enumerators*
*also wrote such comments as "Imbecile", or "Cripple"*
*We can record these options, with abbreviation as necessary (enter the
full*
*wording in Column Y).*
*"Df&Dm", "Imbcil", "Crippl" would be acceptable. *

The instructions given to transcribers suggests that if the Disability is
too large to explain in 6 digits we can also add the full disability in the
notes column.

Hoping that FreeCEN two might have more digits to use instead of the 6
maximum we use now when transcribing.

I have looked at the google docs and all the different ones we have used.
As you see all are only 6 digits.
That is why we add the longer version in Notes to hopefully explain the
full disability .

**Comment by Captainkirkdawson** [comment]
Sorry @FreecenBren but I cannot comment on what should be there. All I can do is report on what is actually there.

**Comment by PatReynolds** [comment]
Question is (I think) should search be on 'column w' or 'column Y' - as column Y is twys, and column W is a FreeCEN abbreviation, there are arguments for both.
For column Y - will pick up entries if people are specifically looking for something (e.g. Limbless, or mentioning Heart).  But such searches will be better served by providing access to the records as Open Data.
Column W on the other hand is already used for a reduced set of possible disabilities.  

So I think we should go with a ticky that returns any record with entry in W.

**Comment by Captainkirkdawson** [comment]
I am totally lost @PatReynolds we have no such fields as Y and W in individuals. The available fields are 
field :sequence_in_household, type: Integer
  field :individual_flag, type: String
  field :surname, type: String
  field :forenames, type: String
  field :name_flag, type: String
  field :relationship, type: String
  field :marital_status, type: String
  field :sex, type: String
  field :age, type: String
  field :age_unit, type: String
  field :detail_flag, type: String
  field :occupation, type: String
  field :occupation_flag, type: String
  field :birth_county, type: String
  field :birth_place, type: String
  field :verbatim_birth_county, type: String
  field :verbatim_birth_place, type: String
  field :birth_place_flag, type: String
  field :disability, type: String
  field :language, type: String
  field :notes, type: String

**Comment by FreecenBren** [comment]
This is the best I can do with what relates back to the FreeCEN Spreadsheet.
Fields attached give you more details re the columns in the initial transcription.
 

Column Letter in FreeCEN   Spreadsheet         
Rake Report

System produced to form the final VLD
field :sequence_in_household, type: Integer

System produced to form the final VLD
field :individual_flag, type: String

I
field :surname, type: String

J
field :forenames, type: String

K = query on names etc. we use an X
field :name_flag, type: String

L
field :relationship, type: String

M
field :marital_status, type: String

N
field :sex, type: String

O
field :age, type: String

Query Column P
field :age_unit, type: String

 
field :detail_flag, type: String

Q
field :occupation, type: String

R =  occupation Status
field :occupation_flag, type: String

T
field :birth_county, type: String

U
field :birth_place, type: String

Query column V
 

System produced to form the final in Valdrev
field :verbatim_birth_county, type: String

System produced to form the final in Valdrev
field :verbatim_birth_place, type: String

 
field :birth_place_flag, type: String

W
field :disability, type: String

X
field :language, type: String

Y
field :notes, type: String

**Comment by PatReynolds** [comment]
Implement "Restrict search to persons with disabilities (tickybox)"

**Comment by Captainkirkdawson** [comment]
Code available for evaluation on test3 CEN.

**Comment by PatReynolds** [comment]
Search found two records, but neither was of a disabled person:
![image](https://user-images.githubusercontent.com/6338822/71410884-f5176380-263e-11ea-9c3f-9223b763ef6e.png)

Repeat with wider search has 9 results, two view 4 and view5, Eliza Alcock are correct, the others are false positives.
![image](https://user-images.githubusercontent.com/6338822/71411007-7969e680-263f-11ea-8ead-ea2ff864bbc2.png)

Suspect is search interpreting a "dash" as being a positive result?  I have tried other searches, false positives always have a dash in the disability field.  Those without dashes are never false positves.

**Comment by Captainkirkdawson** [comment]
There are no false positives from a code perspective. The ticky box implementation does NOT look at the actual contents. It simply asks 'is there anything in this field' There is no quality assessment as to it content.  
As the original checking of this field showed there are many strange entries. Look at the sheet for all years in the spreadsheet
https://drive.google.com/open?id=1afnPVobQXI8o44_PuRSlYLRm5lVHstHo

**Comment by PatReynolds** [comment]
Need to add to help: Disability search can sometimes give a "false positive" - when you check the details, there is a dash or some other entry in the disability field, rather than an indication of disability.

**Comment by Captainkirkdawson** [comment]
deployed
