### ISSUE TITLE
Analyse data in Coords Status Page and County Pages and decide where it is best placed, if still needed

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#758]
Spreadsheet detailing pages and contents, as a basis for discussion:
https://docs.google.com/spreadsheets/d/1Q5Ow2IYDszhVJMP1OkaPGkSideMuF4dQ8DoGAuOCvPQ/edit?usp=sharing

NB Scotland's psite is much fuller, reflecting the differences between the E+W and Scotland censuses.

E0 U6 S8 C5:P19

**Comment by PatReynolds** [comment]
Covered in #847?

**Comment by Captainkirkdawson** [comment]
Not DT Explain 'syndicate' fand 'county' in documentation #847

**Comment by PatReynolds** [comment]
@PatReynolds to check story referred to.

**Comment by PatReynolds** [comment]
Yes, #847 coverage of  syndicte and county documentation covers this.
