### ISSUE TITLE
Automate transfer of test3 refinery on CEN to production

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#759]
Duplicate the process used on REG for transfer of refinery page from test3 to production

**Comment by Captainkirkdawson** [comment]
@lemon-ukgen reported working on Refinery transfer stuff for FreeCEN2, and getting a bit lost about where uploaded assets live. on FreeREG2 they’re at public/system/refinery (which is symlinked into /raid and copied around the production servers automatically)
on vervet, this path does not exist, and i’ve not yet found an equivalent.
there’s public/assets/refinery but that looks more like pipeline stuff (eg: computed css)
does FreeCEN2 have uploaded assets? if so, where are they on disk?

**Comment by Captainkirkdawson** [comment]
On test3 of CEN the refinery resources also live at public/system/refinery however there appears to be no symlink. CEN at this time has essentially no uploaded assets. I added a file and an image today for test purposes..
For CEN on colobus public/system/refinery also exists but again with no symlink. There is 1 test file and 1 image again early test files.

ie Refinery on CEN is very much  in its infancy.

**Comment by Captainkirkdawson** [comment]
@pat_reynolds @rich_pomfret @Alison O'Neill @denisecolbert The automatic transfer process of CEN refinery from test3 to production is ready for a final test by @lemon; this one will zap what is on production with test3. As far as I can see there is nothing on production other than holding pages. We would really like to get this going as the manual process is a real pain

**Comment by Captainkirkdawson** [comment]
The test by @lemon-ukgen was successful.

**Comment by AlOneill** [comment]
Agree that the test was successful, except that it was not a full test in that there were no files or images on t3 to be transferred. (Why not is a another question!)

**Comment by Captainkirkdawson** [comment]
There were 3 files and 1 image transferred. So it was a full test. The image was a test image only and will be deleted. It was added to test3  for testing the transfer.
