### ISSUE TITLE
Add "Help with Citations" to Help for Researchers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#760]
Include warning/explanation of absence of citations on next/previous dwelling (done)

**Comment by AlOneill** [comment]
As I work on the text, I am wondering whether "Next Dwelling" and "Previous Dwelling" are the best terms? As I understand it, the buttons show the next or previous "Household", i.e. the next group of people. Dwelling seems a little ambiguous — could be a place/building rather than a household. The Transcriber info (currently) refers to Households as the basic unit.

Maybe this has been discussed already and I have forgotten!

**Comment by Captainkirkdawson** [comment]
Never discussed.  Actually it is next or previous building. It may or may not be a dwelling and it may or may not be occupied and there a household. It could be a church or empty building or or or . It is something that the enumerator has entered into the census return

**Comment by AlOneill** [comment]
I believe it is next Schedule number or building without a schedule number — usually the next household, but sometimes an empty/non-occupied building.

Multiple occupancy (by several household groups) was very common, in the 19th century at least, especially in cities.

**Comment by AlOneill** [comment]
In other words, a single building (or address) may well have several households, and each household will have its own schedule number. Unoccupied buildings are less common, and the transcriber will use zero as the schedule number for every one of these.

Tricky.

**Comment by FreecenBren** [comment]
Cannot be Households as they are not always.

Each dwelling/Building can contain people, families, lodgers, boarders
etc., but they can also be a Church, shop, blacksmiths, Doctors,
Dressmakers, Workhouses, Barracks, schools, Hospitals, Inns, Hotels, Boats,
Farms, Carpenters, Stables, Caravans, Shipping, etc, etc,
Researchers are not always looking for people, but are interested in the
Dwellings as well as many are now using the site to find out what their
family dwelling was when it was first built. This is a knock on effect from
the TV programme searching for the History of a .Building.
So this must be included if we are thinking of renaming dwellings.
I personally think dwelling covers all. But I am only one.

**Comment by AlOneill** [comment]
Thanks @Captainkirkdawson @FreecenBren. So, to summarise, none of the terms Dwelling, Household or Schedule is quite right as they all imply an occupied space: this is not always the case.

I cannot think of a better (concise) term, but perhaps there is one??

(I think Dwelling set me off partly because it puts "Good King Wenceslas" — "… where and what his dwelling" — in my head and partly because we come across dwelling used as a verb more often than a noun. Tricky.)

**Comment by AlOneill** [comment]
After further reflection, have opened a new issue to discuss our use of 'dwelling' #909.

Will get back to issue in hand!

**Comment by PatReynolds** [comment]
What is the action for me, please, or is this still waiting for a decision on 'Dwelling' or alternative term?

**Comment by richpomfret** [comment]
@AlOneill any update on this one (or if Pat needs to do anything?).

**Comment by AlOneill** [comment]
@PatReynolds @richpomfret Am back on this now — don't think I have questions but will let you know if anything crops up! (Was muted in Scrum and missed the opportunity to say something then.)

**Comment by AlOneill** [comment]
@PatReynolds The two DRAFT pages, [**Help**](https://test3.freecen.org.uk/cms/draft-help) and [**Help with citations**](https://test3.freecen.org.uk/cms/draft-help/draft-help-with-citations) are ready for review.

**Comment by AlOneill** [comment]
@PatReynolds Will move full version to 'About' page, as per the REG and BMD.

**Comment by AlOneill** [comment]
Full version moved to About page. Ready for Review.

**Comment by AlOneill** [comment]
Will make ready for sync when Review is passed.

**Comment by PatReynolds** [comment]
Is there anything to review in About? or Help - I can't see citations in either on test3 FreeCEN

**Comment by AlOneill** [comment]
@PatReynolds The pages for Review are both drafts (as per protocol). Does that help?

**Comment by AlOneill** [comment]
@PatReynolds Pages are About DRAFT and Help DRAFT.

**Comment by PatReynolds** [comment]
Duh!  I have reviewed in About, and good to go.

Cannot see in DRAFT Help?   Maybe add it to the index so it can be more easily picked up by bears of little brain like me?

**Comment by AlOneill** [comment]
@PatReynolds Fixed in DRAFT Help.

**Comment by PatReynolds** [comment]
Perfect thanks @AlOneill

**Comment by PatReynolds** [comment]
Reviewed, and marked 'ready for deployment'.

**Comment by AlOneill** [comment]
The updated About and Help pages are now sync-ready.
