### ISSUE TITLE
Census County 'i' box (on hover) is truncated

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#764]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/3b5d3e9d-a3c7-4c00-a08c-d4f2c3f6e9a6)

**Comment by PatReynolds** [comment]
No longer have 'i' boxes so can this be closed?

**Comment by richpomfret** [comment]
Closing.
