### ISSUE TITLE
Write rake task to extract and list the contents of the various possible search fields

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#765]
Before attempting to write any code to filter on the basis of the occupation field we need to know the range of information currently contained in that field

**Comment by Captainkirkdawson** [comment]
Have generalized it to look at occupation, marital status, sex, language, disability.
Running time will be about 3 hrs

**Comment by Captainkirkdawson** [comment]
The rake task has been run against the CEN database on test3. That database is extremely close to the production version so the statistics should be meaningful. 

Year	Pieces	Pieces Online	Individuals	Dwellings
1841	1,847	1,470	5,392,415	        1,193,527
1851	1,582	1,268	4,055,657	        899,293
1861	4,089	3,087	11,618,172	2,738,371
1871	4,585	2,270	7,204,704	        1,713,344
1881	571	          116	455,945	        110,181
1891	4,549	1,551	8,841,790	        2,060,268
Total	17,223	9,762	37,568,683	8,714,984

**Comment by PatReynolds** [comment]
Closing as done.
