### ISSUE TITLE
Results display is using the REG formatting and positioning left

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#767]
The application of the formatting to permit side ads is being applied to CEN as well resulting in the display being left positioned and compressed instead of centered

**Comment by AlOneill** [comment]
Is that because the left `grid__item one-sixth` is empty? And so occupies no space?

**Comment by AlOneill** [comment]
Tests in browser confirm my suspicions above.

**Comment by Captainkirkdawson** [comment]
Yes that's because the code is applying reg formatting that now displays side ads.
Code made app specific. Can be removed when Cen goes to side ads as well
