### ISSUE TITLE
Records missing (there in FC1)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#768]
Searched for John McKendrick (born c 1801) could not be found, then tried his son Robert (born c 1830) again could not be found: However, both records can be found on FreeCEN1 (Piece: SCT1841/272 Place: Arbroath -Angus Enumeration District: 2) so I know the record exists, therefore there is a problem with the search on FreeCEN2.

**Comment by Captainkirkdawson** [comment]
@DeniseColbert what year?

**Comment by Captainkirkdawson** [comment]
@DeniseColbert please ignore stupid question!

**Comment by Captainkirkdawson** [comment]
I had no trouble locating on CEN2
![one](https://user-images.githubusercontent.com/2874694/70453461-0882d600-1a66-11ea-8710-ea33cb3e951e.JPG)
![two](https://user-images.githubusercontent.com/2874694/70453474-0de02080-1a66-11ea-9589-718b9a42b923.JPG)

**Comment by FreecenBren** [comment]
I also found them OK on both search sites.

**Comment by DeniseColbert** [comment]
Brenda also told me offline that she found the record. Must have been an odd glitch! Will close.
