### ISSUE TITLE
Add sex search field 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#769]

**Comment by Captainkirkdawson** [comment]
The rake task provided the following make up of this field

1841 "M", "F", "-", "_", 
1851 "M", "F", "-", "_", "U", "W", "G"
1861 "M", "F", "-", "_", "D", "U", "G", "W", "R", "S", "`", "4", "7", "J", "6", "3", "1", "5", "0", "9", "2", "8"
1871 "M", "F", "-", "N", "S", "_", "W", "U", "D"
1881 "M", "F", "-"
1891 "M", "F", "-", "_", "8", "2", "W", "S", "1", "D", "N"
Totals "M", "F", "-", "_", "U", "W", "G", "D", "R", "S", "`", "4", "7", "J", "6", "3", "1", "5", "0", "9", "2", "8", "N"

CEN1 provides  3 options Either Male Female

Before proceeding a mapping of what is in there would be required.

**Comment by FreecenBren** [comment]
Only M or F should be the rule.
CSVCHECK gives errors if any other used.
Again be interested to be able to see where they were used and how they got accepted.
 
Are they new ones or anytime in the past 20 years?

**Comment by Captainkirkdawson** [comment]
What is in there is in there I am afraid

**Comment by PatReynolds** [comment]
Implement: "Restrict search to: males (tickybox) females (tickybox)."

**Comment by Captainkirkdawson** [comment]
Code available for evaluation on test3 CEN.

**Comment by PatReynolds** [comment]
Code tested sucessfully.

**Comment by Captainkirkdawson** [comment]
deployed
