### ISSUE TITLE
Roadmap page needs updating

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#778]
Button on live links to https://www.freecen.org.uk/cms/system-documents/development-roadmap? but on freeREG links to google doc (https://docs.google.com/document/d/1A8sEE7yAaT-2Y8rxWxunRT85BpwAkGaIQBEzVE6dNx8/edit#heading=h.24wxxstl5bsr) - this may need changing as it may not be accessible to all?  And do we want read only, or comment access?

test3.freecen.org.uk has html code of an old roadmap (saved as a .txt file to the system documents folder).

Link on FreeCEN should be from button to https://docs.google.com/document/d/1FNUijfW3586xE-m9W3U1gyxstSYwO7cD3jbqS9V33A8/edit?usp=sharing (this assumes comment access).

**Comment by AlOneill** [comment]
@PatReynolds the link above will not let me view the doc without logging in to GoogleDocs.

A link to the Roadmap is needed on the "Info for transcribers" page, under Sending Messages.

**Comment by PatReynolds** [comment]
Link (that I hope works) added.

**Comment by Captainkirkdawson** [comment]
I am not sure why I am flagged to action this.

The Roadmap action in both REG and cen are sent to 'Roadmap' => '/cms/system-documents/development-roadmap',
It is up whomever to either put in the relevant comment or redirect  to the appropriate place

The refinery page of that name on REG redirects to the https://docs.google.com/document/d/1A8sEE7yAaT-2Y8rxWxunRT85BpwAkGaIQBEzVE6dNx8/edit#heading=h.24wxxstl5bsr which is NOT a suggesting link.

The refinery page of that name on CEN does NOT exist. There is a page https://test3.freecen.org.uk/cms/system-documents/road-map which contains a very old page.

The action required is to change the name of that page to Development Roadmap and to have it redirect to the link given above by Pat
Link on FreeCEN should be from button to https://docs.google.com/document/d/1FNUijfW3586xE-m9W3U1gyxstSYwO7cD3jbqS9V33A8/edit?usp=sharing

**Comment by PatReynolds** [comment]
Sorry, Kirk, should have assigned @AlOneill

**Comment by PatReynolds** [comment]
This link should be available all, comment.  It is now on a shared drive, in a folder for publicly accessible documents for FreeCEN2..... 
https://drive.google.com/open?id=1FNUijfW3586xE-m9W3U1gyxstSYwO7cD3jbqS9V33A8

**Comment by PatReynolds** [comment]
Pat to create roadmap page on Refinery (Development Roadmap), and put text on it and link to the google doc.

**Comment by PatReynolds** [comment]
New page made on Test3, ready for review.

**Comment by AlOneill** [comment]
Reviewed: a couple of small changes to text plus layout to constrain the line-length for more comfortable reading on a wide screen.

**Comment by PatReynolds** [comment]
Thank you all, that works fine!

**Comment by Captainkirkdawson** [comment]
deployed
