### ISSUE TITLE
About this search does not reflect FreeCEN

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#781]
The About This Search does not use the FreeCEN fields of Birth County nor Census County and Census Place.

It also needs modification to add the additional search criteria

**Comment by Captainkirkdawson** [comment]
Resolved in test3

**Comment by PatReynolds** [comment]
Working correctly
e.g.
This search will also select those individuals who were: SINGLE: had an occupation with starting with the following characters Coal:

Possible improvements (for discussion)

Maybe remove colon before type of filter, e.g.
This search will also select those individuals who were SINGLE: had an occupation with starting with the following characters Coal:

This search will also select those individuals who were: speak BOTH:
should be
This search will also select those individuals who were: speakers of BOTH: (or "were speakers of both".

This search will also select those individuals who were: had an occupation with starting with the following characters Coal:
(probably a ' following an occupation' than 'had an occupation'?

**Comment by Captainkirkdawson** [comment]
Revisions were made and applied to test3; also being included in the release version. Future improvements can be made

**Comment by PatReynolds** [comment]
Working as expected, thank you.

**Comment by Captainkirkdawson** [comment]
deployed
