### ISSUE TITLE
You searched for does not include census place

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#783]
If you include a census place in the search. The place is not included in the You searched for display.
![No census place.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/81afbc59-c2c9-468c-bb89-d9973ea4732b)
We just refer to Place; should be census place
![add census.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/66a52493-f714-47ca-8100-9f3ab0c7fd4a)

**Comment by PatReynolds** [comment]
Birth county not being reported:

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/2837c188-0d58-4b52-b9f7-3dc9edbb8b6f) (there was no census county selected for this search)

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/508f35b8-a833-4220-a7ec-75f84a3be774)

When just census county, or both birth and census county, are selected, report works fine.

**Comment by Captainkirkdawson** [comment]
Fixed

**Comment by Captainkirkdawson** [comment]
deployed
