### ISSUE TITLE
158430587 Unable to edit profile to update my Transcription Agreement status.  (Ronald)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#790]
Issue reported by **Semiloof** at 2020-01-08 16:29:47 UTC
Time: 2020-01-08T16:24:06+00:00
Session ID: 0c2351f65eb6e7838ee42752f086043c
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freecen.org.uk/manage_resources/new?locale=en](https://www.freecen.org.uk/manage_resources/new?locale=en)
Reported Issue:
When I login to FreeCen as a transcriber I am prompted to update my Transcription Agreement.  When I click on the link 'click here' I am transferred to the FreeReg site, with a message that states that 'I must be logged in to access that action'.  
https://www.freecen.org.uk/uploads/feedback/screenshot/5e16037bf493fde07de332ac/Freeecen.png    

![Screenshot](https://www.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
Corrected; will be changed in the next deployment

**Comment by PatReynolds** [comment]
Works fine.

**Comment by Captainkirkdawson** [comment]
deployed
