### ISSUE TITLE
Recruit Data Manager(s)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#791]
Role Description in progress. Have asked EricB for more info on the role in FreeREG.

**Comment by Captainkirkdawson** [comment]
@DeniseColbert Made comments on the document

**Comment by DeniseColbert** [comment]
@Captainkirkdawson could you look at the changes I've made?

**Comment by Captainkirkdawson** [comment]
@DeniseColbert done
