### ISSUE TITLE
Recruit Researcher Specialist(s) 

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#792]
Role Description complete. Now working on Recruitment process. Awaiting completion of the other 3 roles  so all can be presented at once.

**Comment by Captainkirkdawson** [comment]
Any chance of seeing these role descriptions?

**Comment by DeniseColbert** [comment]
Shared Data Manager RD for your comments, and have given you access to the parent (FreeCEN) folder so you can see the others. Documentation Volunteer is in a very early draft stage.

**Comment by Captainkirkdawson** [comment]
@DeniseColbert added a comment to document

**Comment by DeniseColbert** [comment]
@PatReynolds Researcher form is in the folder ready for your review

**Comment by DeniseColbert** [comment]
> @DeniseColbert added a comment to document

Thanks Kirk; I added your suggestion.

**Comment by PatReynolds** [comment]
Good, thank you, Denise.

**Comment by DeniseColbert** [comment]
Add 'Liaise with Brenda' to RD
