### ISSUE TITLE
Recruit Documentation volunteer(s)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#793]
Role Description in progress. Will ask Kirk and Alison for their thoughts when first draft is complete.

**Comment by Captainkirkdawson** [comment]
@DeniseColbert that's a pretty good document

**Comment by DeniseColbert** [comment]
@AlOneill do you have any comments?

**Comment by AlOneill** [comment]
@DeniseColbert Have made some comments/suggestions.

In the main, a good document.
