### ISSUE TITLE
Help for using filters

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#795]
Need to add a section in the Help on Using Filters

**Comment by Captainkirkdawson** [comment]
Initial draft section written ready for @AlOneill to improve

**Comment by AlOneill** [comment]
It might be better to take the example from a county that has been transcribed completely (unless I'm being far too literal about it all), otherwise the numbers will change as more pieces go online. Cornwall is the obvious choice (all years done, including 1881), or ?

**Comment by Captainkirkdawson** [comment]
Personally I see nothing wrong with the example; sure things will change over time. The idea of an example is to convey the process of how to use the filter. I think it does that but you could have a better understanding of what confuses people. I think they will be totally confused without one.

**Comment by AlOneill** [comment]
OK — I can make it work, with a couple of caveats for the reader. I agree that an example is invaluable.

As for what confuses people: many prefer a picture to words, especially if the idea of a filter is not familiar to them. So will probably add a couple of screenshots. Lots to think about …

**Comment by Captainkirkdawson** [comment]
Look forward to the suggestions. Deployment has been placed on hold until then.

**Comment by richpomfret** [comment]
@AlOneill are we close with this one or can Pat & I help? We will aim to deploy tomorrow evening (28/01/20).

**Comment by AlOneill** [comment]
I will do my best to have something more friendly ready for tomorrow evening — though it may need further work at some point. 

Also depends on getting an answer on the changes to "Census location" section of "Help" — the Newark issue #746 (both being edited together).

**Comment by AlOneill** [comment]
@Captainkirkdawson Are we still showing language results for only 1891? It was recorded in other years too (the details will be with the issue that explored the field).

Are there plans to show the other years too?

**Comment by Captainkirkdawson** [comment]
@AlOneill Not at this point. Too much uncertainty. Will be addressed in a future revision

**Comment by AlOneill** [comment]
@PatReynolds @richpomfret @Captainkirkdawson 
The draft Help page is ready for review. As well as the new section on Filters, it includes the updates to "Census location" — Newark and the withdrawal of "Nearby places".

I will make the page ready for syncing once the changes are approved.

**Comment by Captainkirkdawson** [comment]
@AlOneill I have no concerns with amended text

**Comment by AlOneill** [comment]
Page ready for sync.

**Comment by Captainkirkdawson** [comment]
@AlOneill TY

**Comment by Captainkirkdawson** [comment]
deployed
