### ISSUE TITLE
404 issue with missing schedule number

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#797]
From issue #796, mistakenly placed there - following is not associated with that problem

On 24 Jan 2020 Pat Reynolds wrote:
May be unrelated[it was!], but on live looking at
(https://www.freecen.org.uk/search_records/5a153c30f4040b9d6e4c67cd : viewed 24 Jan 2020), Sarah ALCOCK in household of Thomas ALCOCK, Bennington Grange, Newark, Nottinghamshire, England; 1851 
moving to second next dwelling generates a 404 error. Maybe hit last record in piece?

FreeCENBren on same day notes:
If you do the same search in FreeCEN one you will find that the next but
one record relates to a missing schedule number but FC1 shows it and FC2
shows the error 404. I will look at the original CSV and see why. We
recorded a Missing schedule of Zero. It could will be an empty dwelling but
will double check.
Why FC2 does nothing is out of my control but the CSV might give me a clue.
Will let you know my findings when I get home to look at it.

I then said (same day)
Just tried with Agnes Austin, born 1840 - 1860, resident Horncastle,
Lincolnshire: moves forward, fine. Backwards 2 and #404 error.

.Same but resident Manchester, no problems four forewards or back.

Pat Reynolds to test further

**Comment by Captainkirkdawson** [comment]
Crash is caused by line 105 in 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/controllers/search_records_controller.rb#L101-L106
NoMethodError (undefined method `[]' for nil:NilClass):
@family_head_name = @dwelling.freecen_individuals.asc(:sequence_in_household).first['forenames'] + " " + @dwelling.freecen_individuals.asc(:sequence_in_household).first['surname']
 {"dwel"=>"590396d9e9379091b14d5252", "locale"=>"en", "page_number"=>"0", "id"=>"590396dfe9379091b14d63d2"}

**Comment by Captainkirkdawson** [comment]
Dwelling exists
"_id" : ObjectId("590396d9e9379091b14d5252"),
        "deleted_flag" : null,
        "dwelling_number" : 60,
        "civil_parish" : "Horncastle",
        "ecclesiastical_parish" : "Horncastle",
        "enumeration_district" : "1",
        "folio_number" : "10",
        "page_number" : 13,
        "schedule_number" : "0",
        "house_number" : null,
        "house_or_street_name" : "-",
        "uninhabited_flag" : "u",
        "unoccupied_notes" : null,
        "freecen1_vld_file_id" : ObjectId("590396d6e9379091b14d4403"),
        "freecen_piece_id" : ObjectId("590261e2e9379091b1b66cf1"),
        "place_id" : ObjectId("590261d0e9379091b1b6473e")

However that dwelling has no individuals. 
Code needs to ensure that we have individuals before attempting to look up their names!
We can either test for individual existence or use the "uninhabited_flag" : "u", or both. Then generate appropriate empty dwelling page

**Comment by Captainkirkdawson** [comment]
Fix deployed to test3

**Comment by PatReynolds** [comment]
Fix works perfectly, thank you @Captainkirkdawson

**Comment by Captainkirkdawson** [comment]
deployed
