### ISSUE TITLE
Only show search filters when a user selects 'revise' search

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#798]
Users are advised (in 'help') not to select filters until they have already run an initial search - this begs the question, why are filters available to use beforehand if they will not function correctly?

This story therefore suggests that we include these search filters on the revised search page and, perhaps only IF there are enough results. The latter would need to be clearly conveyed, or perhaps the filters would be 'greyed out' with a bit of a blurb saying 'you need x results before using these search filters'.

**Comment by PatReynolds** [comment]
Already discussed - cannot now find the issue on Filters, but it is documented. there.

**Comment by AlOneill** [comment]
Accessibility could be an issue here, both visually (contrast ratio) and otherwise, if 'greyed out' filter options are shown.

**Comment by Captainkirkdawson** [comment]
Not convinced this is really required. If one has established the search criteria then to go straight to the use of a filter makes sense

**Comment by PatReynolds** [comment]
Now I understand that if one knows a search will return 200 or so records, one can go straight to filtering, the accessibility issue means that we should not grey out.

**Comment by Captainkirkdawson** [comment]
Perhaps need a comment in the help to make that clear.

**Comment by AlOneill** [comment]
@PatReynolds @Captainkirkdawson  Have appended the following to the first para:

"You may already have made such a search and want to explore the results more easily — there is no need to run the search again before you apply any of the filters — simply set up your successful search, adding any filters that you wish."

**Comment by Captainkirkdawson** [comment]
I would prefer something along the lines of 
If you know that your search will generate a useful number of results then you may apply filters directly to the search.

**Comment by AlOneill** [comment]
@Captainkirkdawson I agree that your suggestion is more compact than mine (!), but am uneasy about how an ordinary user will understand "apply filters directly" … will think on.

Have either of us properly addressed the misunderstanding expressed in the scrum? I'm not sure. I look forward to @PatReynolds take on our efforts.

**Comment by Captainkirkdawson** [comment]
Difficult to say as I had no misunderstanding just in creating them. How about
If you know that a previous search has generated a useful number of results then you may include the filters when entering that search in the future. i.e. you do not need to go through the revising a search process

**Comment by richpomfret** [comment]
@AlOneill to amend text with above suggestion.

**Comment by AlOneill** [comment]
Text amended as per.
