### ISSUE TITLE
Make sure PARMS.DAT synchronized across SVN, vervet, production

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#80]

**Comment by dougkdev** [comment]
Let's also make sure the .VLD files are synchronized.

On Thu, Jan 14, 2016 at 12:02 PM, Ben W. Brumfield <notifications@github.com

**Comment by benwbrum** [comment]
Doug and I had a chat about this and discussed options for moving Brenda's current tools for controlling metadata (editing a CSV  file and generating `PARMS.DAT` from that) onto the online system.  This would invove building a simple web interface for editing places and pieces, then generating the DAT files from it.
