### ISSUE TITLE
UCF results need to be filtered by record type if included in search params

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#809]

**Comment by AlOneill** [comment]
A little puzzled by this as CEN does not use UCF. What am I missing?

**Comment by Captainkirkdawson** [comment]
Issue moved to [FreeUKGen/FreeUKRegProductIssues #1279](https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/1279) via [**ZenHub**](https://www.zenhub.com/)
