### ISSUE TITLE
soundex works differently than FC1

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#81]

**Comment by dougkdev** [comment]
I think the examples mentioned that were not returning the same results on
FC2 as FC1 were Tom and Thomas as well as Wm and William.  Soundex is a
specific phonetic encoding and none of those should be considered to have
the same soundex value (Tom=T500 in soundex, Thomas=T520 in soundex,
William=W450, Wm=W500).  Although the report was that the difference was
with soundex selected, I believe the difference between FC1 and FC2 would
show up regardless of whether or not soundex is selected.  This is not an
issue with soundex, but instead with the list of which abbreviations and
alternate versions of names should be considered to be equivalent to each
other in a search (these are what are called "emendation rules" in the
database).  The emendation rules were not loaded and applied to the
database on test2.  I started the script to apply the emendation rules
about an hour ago (about 5:30pm Saturday USA MST time).  It looks like it
will take several hours to finish running.  I will check first thing Monday
morning to verify that applying the emendation rules solved the problem.

**Comment by PatReynolds** [comment]
Thanks, Doug.  Only partially relevant to this thread: now I understand a
little more about Soundex, I am wondering if we should explain it a bit on
the websites.  For example I was assuming that there was both vowel and
consonant matching - so Elcott would find Alcott. It's also important to
know that at least one interchangable pairs of consanant (t/k) is not
treated as an interchangable pair.

So with a 'real' name of Alcock / Allcock (A422) you are also going to need
Allcott (A423), and E422 and E423 to cover the common variants.

Cheers,

Pat

On 24 January 2016 at 01:36, dougkdev <notifications@github.com> wrote:

> I think the examples mentioned that were not returning the same results on
> FC2 as FC1 were Tom and Thomas as well as Wm and William. Soundex is a
> specific phonetic encoding and none of those should be considered to have
> the same soundex value (Tom=T500 in soundex, Thomas=T520 in soundex,
> William=W450, Wm=W500). Although the report was that the difference was
> with soundex selected, I believe the difference between FC1 and FC2 would
> show up regardless of whether or not soundex is selected. This is not an
> issue with soundex, but instead with the list of which abbreviations and
> alternate versions of names should be considered to be equivalent to each
> other in a search (these are what are called "emendation rules" in the
> database). The emendation rules were not loaded and applied to the
> database on test2. I started the script to apply the emendation rules
> about an hour ago (about 5:30pm Saturday USA MST time). It looks like it
> will take several hours to finish running. I will check first thing Monday
> morning to verify that applying the emendation rules solved the problem.
>
>
> On Thu, Jan 14, 2016 at 12:10 PM, sean-wood <notifications@github.com>
> wrote:
>
> > Assigned #81 <https://github.com/FreeUKGen/FreeCENMigration/issues/81>
> to
> > @dougkdev <https://github.com/dougkdev>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/FreeUKGen/FreeCENMigration/issues/81#event-515358051
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/FreeCENMigration/issues/81#issuecomment-174241136>
> .
>



-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by PatReynolds** [comment]
I am afraid we didn't get any additional applicants, so won't be
interviewing on Thursday.

I will see if it is possible/practicable to widen the internship to recent
graduates and/or those who are not from the University of York.

With best wishes,

Pat

-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
