### ISSUE TITLE
Missing adverts

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#811]
The detailed results page does not show adverts even though they advert code is correct.![advert missing.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/a5660be8-05ae-4b6d-b5ad-b41b9ead081d)
![advert missing1.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2e6068ce-68ca-4b84-93e8-c47d79991c3c)

**Comment by helhyde** [comment]
I have checked the account and nothing seems to have changed or be wrongly
configured.

I'm not seeing and advert displaced on either slot on detailed results (but
they are on results).

I've set the AdBalance back to 100% to see if that makes a difference.

Best wishes,

Pat

**Comment by Captainkirkdawson** [comment]
I believe the problem is in our js code. What I know not

**Comment by richpomfret** [comment]
@richpomfret to take a look/test cookie toggle (see if this effects it at all).

**Comment by richpomfret** [comment]
@Vino-S can you see if you spot anything in the JS code that might be causing this?

**Comment by Vino-S** [comment]
@richpomfret updated code is running in test3. It has been few days since the code change, however still I could not see any adverts.

**Comment by richpomfret** [comment]
@richpomfret to test and see what I can find.

**Comment by Vino-S** [comment]
moved the code to production
