### ISSUE TITLE
Data Quality for Birth Place  and Verbatim Birth

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#812]
A report on what is contained in production in total and by chapman is available at the following link
https://drive.google.com/drive/u/1/folders/1MQdWRjfwq7PUlWezwdoVzYPWbE5jvN5h

**Comment by Captainkirkdawson** [comment]
It indicates that most "fake" chapman codes are single place entries

**Comment by Captainkirkdawson** [comment]
These results show some of the same issues we faced with the move from reg to reg2 a decade ago. Considerable variety in place and church name spelling. This was why we introduced control over Place and Church name spelling. 
It took nearly 3 years of pain and complaints about work and TWYS but the end result is a consistent database with quality data that is comparable and meaningful. Those field are considered meta data and predefined for a transcriber.
Should CEN go the same route?

**Comment by PatReynolds** [comment]
@FreecenBren @geoffj-FUG - the results of following what @Captainkirkdawson suggests are very good - searches find what they are meant to, and additional features that depend on consistence are now in place. Communication to volunteers about this would need to be planned - happy for us in the support team to take this on (if you would not want to).  What do you think of Kirk's proposal?

**Comment by FreecenBren** [comment]
Hi
 
The only thing that bothers me is that FreeCEN has always advocated that the Transcriber has to Transcribe AS IS.
Will this then change in FC2?
 
1.	They spell the POB as Enumerated and are encouraged to add any alternative spelling  to column Y in the spreadsheet.
The Validator has the option of changing them if they wish.


2.	The Place and Church spelling is also taken from the Census Images or from the National Archives.
Some are so bad to read then they will look elsewhere normally Genuki or the attached lists, or nowadays they just Google it!


3.	Will FreeCEN Two have all the Place names etc., for the Validator to chose from and amend if they so wish?


a.	They  have at the moment that option in Valdrev that uses the Genie file  and also a Place txt file attached.
They have an option to amend or add an alternative at the moment so just wondering how this will work in FC2.


 
They are my only concerns.  We do need something quicker and easier when Validating as we do now.
A list of possible places to select from after typing the first 3 letters of a Place etc. would be beneficial.
But  at the same time do not want to lose the integrity of what FreeCEN was based on AS IS.
I am sure I have missed something but it is a start.

**Comment by PatReynolds** [comment]
I too want to keep the TWYS - the quality of the results depends on it.  The quality of the search depends on having both a 'verbatim' and a 'searching' field - so the person may have written 'Flower' (that is what we show to the searcher), but that gets matched to Floor. I think issue #378 "Update/replace GENIE place locator and Supplementary Places lists (was PlaceSup.GEN in VALDREV)" covers this. The work Richard Light has been doing with the Administrative Units would form a part of the newGENIE .

**Comment by Captainkirkdawson** [comment]
I withdraw my suggestion. We should retain TWYS on this place

**Comment by PatReynolds** [comment]
First, implement #816.

Longer term, use a second field, alongside the TWYS, which is filled in valudation.

**Comment by geoffj-FUG** [comment]
#816 is now closed. Below is an update:
CSVProc addresses the problem of Place Names. We have 2 sets of fields. The first pair contain the verbatim Chapman Code and verbatim Place of Birth (i.e. TWYS). The second set are there for an alternative Chapman Code and POB to be entered. This can be done by the transcriber, proofreader or validator. If it is entered by the transciber or proofreader it is presented for validation. If the validator is happy with the entry they can just 'Accept' the record and move on.
This will eventually reduce the load on the validator as some alternative place names will already be entered.
When we cutover there will be only 50,000 records in the Place Names Database. We are addressing the London area problem and a large number of valid LND Place Names will be added to the existing database. 
Validators will therefore be creating place names in the database as they go. Unlike Placesup, which was only used by the one validator, adding a Place Name to the Database means that it is immediately available to all Validators.  So populating the database to a very detailed level will be a combined effort.
Once we are up and running and time has bedded down the database validation should be less onerous for the validator than at present. The database will become a very powerful search tool for the transcriber too.
Geoff
