### ISSUE TITLE
Coordinator can release a csv file to be processed into the CEN2 database

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#814]
At that point the Coordinator does any final validations and when satisfied indicates to CEN2 that the csv file can be processed into the database.

**Comment by Captainkirkdawson** [comment]
Writing an overview document to describe how it works.

**Comment by Captainkirkdawson** [comment]
The incorporation process is documented
https://drive.google.com/file/d/12uuSmqTHwVwU2i-OvvhaIrLkL17CvWPZ/view?usp=sharing

**Comment by geoffj-FUG** [comment]
Tested and worksd OK.
Documentation included in October version 1.2 of Handbook
Geoff
