### ISSUE TITLE
Are uploaded files to always be retained in the folder of the original uploader?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#815]
Currently FC1 has no real userid physical files scheme since they are not involved directly with the servers. When we implement a transcriber upload scheme the file will be stored into a physical folder under the userid name. This is what is done in FR1/2 and FB1. The question comes what to do with the file when uploaded by proofreaders and validators and coordinators? My preference is that the file will always stay with the original transcriber userid where we can maintain the archival history of the file rather than move the file from userid to userid. That has the benefit of being able to start tracking the contributions of transcribers over time. It is the recommended process for FR2

**Comment by PatReynolds** [comment]
This proposal makes sense, as any rights that might be deemed to exist in the file belong to the Transcriber.  I

**Comment by Captainkirkdawson** [comment]
Will work on this basis
