### ISSUE TITLE
Implement and evaluate a text index of place of birth

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#816]
Implement a text index of place of birth in FreeCEN, and evaluate the effectiveness.

See Systemwide #128 for background and further information.

See #812 for data quality

See also #402 for how to cope with indexing pob after the initial index is produced.

**Comment by PatReynolds** [comment]
Potential for index to be created as a stand-alone project? Using the names from the placenames at sub-county levels found in the files produced by @richardofsussex to validate placenames and chapman code in place of birth - and then to fuzzy-match the remaining birth placenames?  Then to allocate hamlets to the correct civil parishes for the search function to work on a parish list. Parishes list would need a 'no place within county specified' tickybox so that the the 1841 censuses, and ambigious hamlets within a county would be returned, as well as the specified parish.

Added high priority as a potential stand-alone piece of work.

**Comment by Captainkirkdawson** [comment]
As a first step a text index of the place_name field in the freecen2_place collection has been created on test3. 
A standalone search place action has been written and accessed by the **SEARCH PLACE NAME** action available to **all members**. 
The text search is case insensitive; ignores stop words (eg a I the you me an), and reduces words to their root, base or .. well .. **stem**.
If multiple words are entered; they are treated as either/or. 
There is an option to limit the search to a specific country.

**Comment by richpomfret** [comment]
Can now close.
