### ISSUE TITLE
FreeCEN message system email has FreeREG in text and CC

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#823]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/a4978965-9dd5-4d88-a921-f09a2fe6bae7)

**Comment by Captainkirkdawson** [comment]
The message does indicate FreeCEN; but I will check to see if FreeREG appears somewhere else

**Comment by Captainkirkdawson** [comment]
I have gone through the code and found one possible source of the error. Have corrected and applied to test3.
Requires testing

**Comment by DeniseColbert** [comment]
Looks fine for the purposes of the story. Should we be concerned about the potential spam warning? (redacted Kirk's personal email address)

![image](https://user-images.githubusercontent.com/19173257/77300331-c2384680-6ce5-11ea-94e3-8b330715420b.png)
