### ISSUE TITLE
Replace SOM in list of counties accepting transcribers

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#828]
For 1901 census

**Comment by FreecenBren** [comment]
Hi Denise,
Notts are also accepting 1901 transcribers as well

**Comment by DeniseColbert** [comment]
Thanks, Brenda. Just to note, Allan tells me that FreeBMD Coords are able to do this themselves:

> Coordinators are able to switch on and off a recruitment flag, when
it is switched off their details will not appear in the selection list
mentioned in 1 above.

**Comment by Captainkirkdawson** [comment]
Done for CEN2; no idea on CEN1

**Comment by FreecenBren** [comment]
Hi, 
 
Not checked but the COORDS are happy to be getting more helpers.
Therefore the ability to turn it off is not an issue at the moment.
I will check it out though as I have not seen it myself.
 
I have just tried to find it but not had any luck so if someone can say which of the many boxes to search is the one I need.
I did not know that it was switched off so I assume that Geoff raised this query now he has some 1901 to work on.

**Comment by Captainkirkdawson** [comment]
All syndicate coordinators in both REG2 and CEN2 have that ability now
![recruitment](https://user-images.githubusercontent.com/2874694/77355008-6384c400-6d09-11ea-9596-74a3373b7b5a.png)

**Comment by PatReynolds** [comment]
Hi Brenda, ] If a Coord has a county with no/limited images, they might need to turn that county off.  
I will draft instructions, for you to road test, if you will.

**Comment by PatReynolds** [comment]
No change needed on FreeCEN1 as there is no information on that site about counties looking for transcribers.

**Comment by helhyde** [comment]
Hi Brenda,

It is ihe list of coord actions in FreeCEN2.  If a Coord has a county with
no/limited images, they might need to turn that county off.

I will draft instructions, for you to road test, if you will.

Cheers,

Pat

**Comment by PatReynolds** [comment]
Draft sent to Brenda 29/4/2020

**Comment by PatReynolds** [comment]
@PatReynolds to ask Brenda again

**Comment by PatReynolds** [comment]
Tansferring to Denise.

**Comment by PatReynolds** [comment]
@Pat to ask Geoff

**Comment by PatReynolds** [comment]
contacted 11/8/2020

**Comment by geoffj-FUG** [comment]
I have tested this in test3 and it works fine.
I have also included Pats notes on how to use it in  the FreeCEN Handbook.
Geoff

**Comment by PatReynolds** [comment]
Thanks @geoffj-FUG
