### ISSUE TITLE
Button hasn't updated to new colour

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#829]
On the 'Volunteer' page:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/705c0162-bdee-4fd4-a588-918675199907)

E2 U2 S4 C8: P16

**Comment by PatReynolds** [comment]
Checked 13/10/2020 and still needs action.

**Comment by AlOneill** [comment]
The Volunteer page has been updated on t3 — needs a sync to appear on live.

**Comment by PatReynolds** [comment]
Thank you, @AlOneill. I will move to 'Ready for User Testing'

**Comment by geoffj-FUG** [comment]
Button is Purple, not ornage. If that is correct this one can be closed.
Geoff
