### ISSUE TITLE
make VLD processor handle errors gracefully instead of crashing

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#83]

**Comment by dougkdev** [comment]
instead of crashing and possibly leaving database collections in an inconsistent state when errors occur, handle the errors gracefully and notify email address specified as optional parameter to rake task, then continue processing.

**Comment by dougkdev** [comment]
Partially implemented.  VLD parser will now skip VLD files that do not correspond to any pieces defined in the PARMS.DAT files and continue on to process the next file instead of crashing.

**Comment by FreecenBren** [comment]
Hi

 

Just asking if any of the VLD’s that were causing the issue relate to Census year 1851 for England & Wales.

 

As an example a VLD uploaded for 1851 can say HO512130 or ho512130

The corresponding PARMS file will say HO107/2130.

 

When the 1851 PIECE is converted using FCTOOLS it will not accept the extra character and it is changed from HO1072130 to HO512130. 

This number is then kept through WINCC and VALDREV and uploaded the same.

There must be a conversion in the full system to accept this.

 

If this is not the problem then please ignore.  Just a thought I was having.

 

Cheers

 

Brenda

**Comment by dougkdev** [comment]
Thanks Brenda.  We were already handling the situation you described.  The
problem was arising when a VLD file was processed for which no piece could
be found in the PARMS.DAT files.   This mainly relates to issue #80, where
we need to make sure that we are using the correct PARMS.DAT files.  If a
PARMS.DAT file was out of date and VLDs were encountered for a piece that
the system didn't know about yet, it would raise an error to let us know
something was wrong, but then stop processing instead of continuing to
handle the pieces it did know about.

Processing would also stop if a .VLD file was in the wrong folder (for
example, on vervet/test2, HS410899.VLD was incorrectly in the ABD directory
but should have only been in WIG).

The correction allowed me to get ABD back onto test2 (with the exception of
the few VLD files that will not load due to missing piece information on
vervet).  However, please wait to test places until issue #80 is resolved
so that we know we are using the correct PARMS.DAT files on test2.

Thanks.
