### ISSUE TITLE
How and when to add the Ecclesiastical Parish

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#830]
@geoffj-FUG wrote the following: When should the Ecclesiastical Parish be added?
 
To do this review right I think that we should review when the Ecclesiastical Parish is added. Why? Because the answer affects CSVCheck.
Initially it was added by the proofreader in winCC. With the demise of WinCC it was added by the Validator (mostly by fudging!)
I believe that as it appears on every census page it should be added by t he transcriber and therefore allowed for in the transcription spreadsheet / csvfile.
In 1911 it moves to the fly sheet at the beginning of each ED.
So once recorded it just needs carrying down, not the tedious process used in winCC.
In 1911 This sheet also records Urban Boroughs and Parliamentary Boroughs.
So what and how when we record it needs to be thrown into the pot now, not later when Kirk is past the point of no return.

**Comment by Captainkirkdawson** [comment]
Brenda commented:
Just been giving this a little thought.

The EP is already in the PARMS CSV in column two.
Ie.
Column one has the piece number
Column 2 has the EP. (The single a in column H)
Column 3 has the Civil Parish (The single b, in column H)
Row one you will see Census year/county example. DOR1851
Etc.,

Why cannot this be picked up by the transcribe for FC2 (perhaps insert a new column  at the start of the spreadsheet so they are all at the start)
As they are on the PARMS they should be on the new FC2 spreadsheet on a list from the PARMS  for them to select along with the Civil Parish?

VALDREV also gives them an option to select a different CHP and POB.
This creates an extra column in the VLD CSV last stage.
Will this column still be needed as hopefully the facility to select a CHP and POB will be more advanced with the new way of selecting from a drop down list. 
( well I am thinking/assuming, that is what will happen?)

So just a thought to add a column at the start of the CSV and remove a column at the end that might not be needed.

But then I have just got up and not at my best after a bad night, so will think it over again when I do wake up.  But it is a start of my thinking, so if any one thinks it might not work, then OK, just one of my thoughts.

The EP on the final VLD spreadsheet is the last column.
Why not make it the first from the dropdown list from the PARMS file.
I am sure I might have missed something so over to you all.

**Comment by Captainkirkdawson** [comment]
If we can extract the Ecclesiastical Parish from the Freecen Piece that would be the simplest. 

But is that going to work in all case; ie all census and all countries.

Is the Ecclesiastical Parish constant for a Freecen Piece?

I seem to recall that the "a" field in the params referred to Parish Name yet it is also referred to as a Place.

I know that in most cases an Ecclesiastical Parish  was one an the same as Civil Parish but not all cases. 

Does this argue that it should have its own field?

It could be added to the csv file under a column header of Ecclesiastical Parish. OK there would likely only be one entry and that would be applied to all subsequent entries until it was changed which of course might be never. 

Alternatively it could be added as an online edit to the any new Civil Parish

**Comment by geoffj-FUG** [comment]
Brenda, Kirk

 

Overall responsibility for a district is held by a superintendent registrar. Registration districts are not always co-terminous with county boundaries, and so in the past were grouped into "registration counties" for statistical purposes. They remained in use for the census from 1851 to 1911. (Wikipedia)

 

So in my view the PARMS is a useful reference file here. My interpretation is that it is Registration Districts (a entries) and Parishes (b Entries). The Dropdown worked most of the time in WinCC but was overwritable. I know that happened quite often. So was that the quality of the PARMS? I know I built my first PARMS by going through the census images for the whole County/year ED by ED.

 

So I will go back to my original contention that the EC should be entered by the Transcriber. It only needs to be entered when it changes.

 

One of the things that gives FreeCEN credibility is the fact that we enter Validators Choices for POB but leave the original entry intact. That is important. So if I have a POB for Tyntesfield SOM I can give a validators choice of Wraxall SOM. That is where the stately home is. It enhances the researchers information. If I get Road WIL I can enter Rowde WIL but put a note in Comments saying or Road SOM (they are each side of the border). Preservation of the original is important. If we change things physically, we will get it wrong one day and decrease our credibility. I think that we should keep those fields. The Drop down list should be used in the same way as Placesup. 

 

That my thoughts

 

Geoff

**Comment by rhodamackenzie** [comment]
This should be entered, imho, by the transcriber, it is not difficult to carry this on in the same way as many other repeating values would be continued. No empty cells allowed for this column. One freecen piece will likely have several enumeration books so could potentially contain differing EPs, but I doubt a single book would have a change in EP?

**Comment by Captainkirkdawson** [comment]
Thanks for the responses. At this point it seems best to permit this to come in as part of the Augmented CSV file.

**Comment by geoffj-FUG** [comment]
Kirk et al

 

A little bit more information for the PARMS debate.

 

In 1841 the ‘a’ record was the Hundred and the ‘b’ record was the Parish. The National Archives do not say whether it is Civil or Ecclesiastical. 

 

Hundreds were however closely linked with Common Law so my presumption would be that it is the Civil Parish. If it was Ecclesiastical they would have been linked to Church Law. 

 

So I see the later censuses (1851 onwards) as acknowledging the different jurisdictions. That is why we have both Civil and Ecclesiastical parishes recorded.

 

I have posted this simply to complete the story.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Working on basis that Ecclesiastical parish is added to CSV file
