### ISSUE TITLE
Decide how to disambiguate place of birth 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#835]
Suggestion:l ambiguation can be placed in the notes (e.g. 'This is probably the Swinton near Malton, as other household members are born in Malton, rather than either of the other two Swinton's in North Yorkshire'. Or for a TWYS of 'Newton - in Pressbury' (county Cheshire) might need to be indexed as Newton (a lot of people born in this Newton, still living there probably wouldn't distinguish it from the other Cheshire Newtons (Ashton-under-lyme and Middlewich) so creating a Newton (Prestbury) [ie 'correct spelling of 'Pressbury'] for the corrected, indexed, place-of-birth field.

If agreed: modify help for transcribers to indicate this.

**Comment by rhodamackenzie** [comment]
I agree with your suggestion
