### ISSUE TITLE
Adjust syndicate management system to accommodate work flow management between transcribers, checkers, validators and coordinators

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#836]
Modify the Manage syndicates system for freecen_csv_files

**Comment by PatReynolds** [comment]
Decided: Syndicate management to be developed as and when needed.

**Comment by Captainkirkdawson** [comment]
Currently there is a 1 to 1 correspondence between county and syndicate. A county coordinator is therefore a syndicate coordinator. The people management aspects are in the syndicate and the data in the county. They could be combined if desired

**Comment by Captainkirkdawson** [comment]
duplicate
