### ISSUE TITLE
The detail and individual flags

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#838]
@geoffj-FUG @rhodamackenzie 
The vld entry has 2 flags detail and individual 
The csv appears to have just 1 the individual one used to specify uncertainty in the relationship/marital status/age/sex fields.
It appears that the  detail flag is added later to the process so it appears in the vld.
What uncertainty does it reflect?

**Comment by rhodamackenzie** [comment]
I do not know.

**Comment by Captainkirkdawson** [comment]
Have emailed Brenda

**Comment by Captainkirkdawson** [comment]
Having dug into the CEN2 code there are 5 flag fields. name , detail (status age etc), uninhabited, occupation and birth place entered by the transcriber. There is 1 deleted entered by the proof reader/ validator. For some reason CEN2 creates an individual flag that is identical to the uninhabited flag! 
It is possible this was used for efficiency purposes in processing vld entries; it does not appear to be required for csv entry processing.
