### ISSUE TITLE
Quality control functions defined and implemented

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#84]
replace WinCC and Valdrev - possibly with element(s) from FreeREG
Needs #85
Needs #64

**Comment by PatReynolds** [comment]
Dependent on #64 (version 1.1)

**Comment by PatReynolds** [comment]
Quality control systems include automated checking (e.g. of metadata) leading to rejection (nb need for transcriber/checker-over-write of rejection for TWYS entries - may need to be 1.3 action if pathway is for transcriber to undertake check)

**Comment by PatReynolds** [comment]
Coordinators / checkers can review work of their transcribers, errors and all pieces/EDs they have loaded. Quality Control takes place between Transcription and making transcription live. Multiple access means by errors/filename/date of load/userid/

**Comment by PatReynolds** [comment]
Correct errors in pieces on-line (For decision: no facility for off-line correction?)

**Comment by PatReynolds** [comment]
Does any other function need adding to this list, before I create individual stories for them?

**Comment by PatReynolds** [comment]
@patreynolds to contact Rick Parsons to get rules from current checking systems, and create document for review

**Comment by Captainkirkdawson** [comment]
The CVSProc has been written to replace the existing off line tools
