### ISSUE TITLE
Birth counties and places

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#840]
@geoffj-FUG 
The original CSV file prepared by a transcriber has a Birth County and a Birth Place. These become the Verbatim birth county and the Verbatim birth place in the final database. The checker or validator either selects those or enters a preferred birth county and birth place. These become the actual Birth County and Birth Place in the database. The CSV file therefore has to incorporate BOTH Verbatim and preferred fields just as the vld entry does.

Hence it is proposed to add 2 additional fields coming after the the notes field for the preferred fields. Is this acceptable or is there and alternative.

**Comment by geoffj-FUG** [comment]
Kirk

 

That is exactly how I understood it. 

 

Lock it in.

 

Geoff
