### ISSUE TITLE
Transcriber, Coord or Tech can assign a file to a Transcriber

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#844]
Needed to allow a transcriber to amend an existing file, and also to associate the file with their Transcription Agreement preference.

E0 U3 S7 C4: P 14

**Comment by Captainkirkdawson** [comment]
Do not understand.

**Comment by PatReynolds** [comment]
Coord to identify who transcribed a file, and assign the transcriber's ID to the file.

**Comment by Captainkirkdawson** [comment]
Coordinator can do now

**Comment by DeniseColbert** [comment]
Complete - new story for FC1 files being made- closing
