### ISSUE TITLE
Additional location information.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#845]
@geoffj-FUG wrote
I have been matching up the census fields with the census years.
When we got to 1911 Scotland we found extra fields in the enumerator’s book. They were all at the level of ED. On examination these fields, except one, are also on the fly of the England and Wales EDs. So in my last Spreadsheet format file on Google Docs I included them.
I am currently doing up a table which matches the proposed fields with the census year. (see attached)
All went OK for a while then …
I started to look at the ED flys of previous years. I have now got back to 1891 and this data is recorded on them also. It does not appear in 1881.
The FC1 spreadsheet took the 1891 census into account. It included the employment types. So it seems to me that it was decided not to record this information on FreeCEN.
So our decision to record it is now inconsistent with a previous decision.
My view is that as we are now Opendata the information should be captured. That will allow researchers to examine occupations or other demographics by Parliamentary Constituency of Borough Wards for instance.
If we decide to include the information in 1901 and 1911 then what happens about 1891? Do we make the fields accessible in the spreadsheet for that year?
![ED fields.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/a785b13f-5ce7-4bb7-8bcf-fad81c42b208)

**Comment by geoffj-FUG** [comment]
Up to now, FreeCEN has been able to handle information from the 1841 to 1891 censuses. Some information such as Parliamentary Constituency and Maiden Name available in some censuses was not collected. The new system will allow this type of information to be collected in the future.
To accommodate the 20th Century censuses we have had to allow for additional information such as:
England and Wales
1901 census 
•	As per 1891, with occupation details changed to ‘Employer, Worker or Own account’
•	a new column ‘If working at home’
•	language spoken (added for Isle of Man only)
1911
As 1901, with extra questions:
•	For married women only, the number of years of their present marriage, the number of children born of that marriage, the number still living, and the number that had died.
•	As well as their occupation, the industry in which the person was employed. If employed by a government, municipal or other public body, the name of that body.
•	Parish and county of birth for anyone born in the UK (which included all of Ireland). If born elsewhere in the British Empire, the colony or dependency, and the state or province.
•	For anyone born outside England and Wales, whether they were resident or visitor in the country.
•	Nationality of anyone born overseas whether British by parentage, British by naturalisation (including year of naturalisation) or, if a foreign national, of which country.
•	In the Infirmity column, the age at which the person had become afflicted.
(Source: National Archives)
Scotland
1901
Scotland added other information, but some of this did not necessarily appear in England and Wales censuses.
There were several changes to the questions that had been asked in 1891.
•	The question on Gaelic was restricted to those aged three years and over
•	Persons born abroad were asked to indicate if they were “foreign subjects”
•	The term idiot was omitted leaving the categories deaf and dumb, blind, lunatic and imbecile, feeble-minded.
•	There was an additional question on occupation to find out the number of people who carried out their trade or industry at home. 
1911
There were new questions relating to fertility of marriage:  on duration of marriage;  the number of living children born to each marriage;  and the number alive at the time of the census.
There were changes to several others:
•	Categories for people with disabilities were revised and the introductory section to the third report on the 1911 census refers to the intended use of the terms as:
o	Lunatic - in cases where the infirmity had been acquired during life
o	Imbecile - in extreme cases where the infirmity had existed from birth or an early age
o	Feeble-minded - in milder cases where the infirmity had existed from birth or an early age. 
•	The question on occupation was extended to find out which industries or services a worker was connected to in addition to their personal profession or occupation
•	The question on place of birth was extended to include nationality for those born in a foreign country, that is, outwith British territory, colonies and dependencies. 
(Source National Records of Scotland)
Ireland
In 1901 and 1911 the whole of Ireland was part of the UK. These 2 years are the only years available.
The returns for 1901 and 1911 are arranged by townland (the smallest division of land) or, in urban areas, by street.  The 1901 census lists, for every member of each household; name, age, sex, relationship to head of the household, religion, occupation, marital status and county or country of birth.  The census also records an individual’s ability to read or write and ability to speak the Irish language.  All of this information is given on Form A of the census, which was filled in and signed by the head of each household. Where the head of the household could not write, his or her mark, usually an X, was recorded and witnessed by the enumerator.
The same information was recorded in the 1911 census, with one significant addition: married women were required to state the number of years they had been married, the number of their children born alive and the number still living.
…
The returns for both censuses also give details of houses, recording the number of windows, type of roof and number of rooms occupied by each family.  Each house is also classified according to its overall condition.  The number of out-offices and farm buildings attached to each household is also given. This information is recorded by the enumerator, who provided summaries of the returns for each townland and street, including the religious denomination of occupants. These summaries include a list of heads of household, thus providing a nominal index for each townland or street.
(Source National Archives of Ireland)
Note: The National Archives of Ireland do not currently charge for access to this material online.

**Comment by PatReynolds** [comment]
My view is also that the information should be captured. Not only will this be of value to historians of place, and building historians, but also to family historians as there is potential to hyperlink employment types to a resourse such as this: https://www.visionofbritain.org.uk/census/EW1861GEN/9?show=ALL - which may help users to understand what it was a "Overmantle Painter's Apprentice" did!
I  would want to make the fields accessible in the spreadsheet for 1891.
Earlier spreadsheets may also need the fields accessible: https://www.repository.cam.ac.uk/bitstream/handle/1810/264233/WP%202%20CENSUS%20EMPLOYERS.pdf?sequence=1&isAllowed=y has some interesting information about the instructions to Enumerators.

**Comment by geoffj-FUG** [comment]
Pat

 

We have preempted the decision by including all fields that we found.

 

I am currently doing a sweep of Scotland and Ireland to identify any additional fields. There are some in Ireland. I still have Scotland to go.

 

Geoff

**Comment by PatReynolds** [comment]
@rhodamackenzie to also take a look.

**Comment by rhodamackenzie** [comment]
@geoffj-FUG 
do you want the sample sheets for all years from Scotlandspeople? Or just 1891, 1901 and 1911?

**Comment by geoffj-FUG** [comment]
Rhoda

 

We need to look at an ED cover sheet and a census page every year to make sure that every year fits into our fields set. If there were special returns for Islands etc we need to cover that as well.

 

Geoff

**Comment by rhodamackenzie** [comment]
OK, I will get sample page for every year of the scotland census

**Comment by rhodamackenzie** [comment]
scotland fields 1841-1911 in reverse order plus pdfs of pages
[ScotlandsPeople_C1911.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4495084/ScotlandsPeople_C1911.pdf)
[scotland census 1841.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4495086/scotland.census.1841.pdf)
[scotland census 1851.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4495088/scotland.census.1851.pdf)
[scotland census 1861.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4495089/scotland.census.1861.pdf)
[scotland census 1871.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4495091/scotland.census.1871.pdf)
[scotland census 1881.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4495092/scotland.census.1881.pdf)
[scotland census 1891.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4495095/scotland.census.1891.pdf)
[scotland census 1901.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/4495096/scotland.census.1901.pdf)
[Scotland Census fields 1841-1911.docx](https://github.com/FreeUKGen/FreeCENMigration/files/4495098/Scotland.Census.fields.1841-1911.docx)

**Comment by rhodamackenzie** [comment]
I have looked at the header pages for the Scottish returns and there is no more information to be had there that is not in the census pages. Also there we no sample pages other than for 1911 on scotlandspeople.

**Comment by geoffj-FUG** [comment]
If the header pages are the cover sheets for each ED then my Sections spreadsheet is finalised.

 

Geoff

**Comment by PatReynolds** [comment]
Agreed: these fields should be added to the spreadsheets, and transcribed.

**Comment by Captainkirkdawson** [comment]
Incorporated into fields.
Suggest this be closed

**Comment by PatReynolds** [comment]
Agree with you, @Captainkirkdawson so closing
