### ISSUE TITLE
A data file for a piece can be devided into parts, and parts managed as separate entities within FreeCEN (as registers and parts of registers are managed within FreeREG)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#848]
Tools need to be created/modified to permit this.
CEN1 works on the basis that there is one vld file per piece. ie all of the transcriptions are contained within 1 file. This leads to massive files and means coordinators often have to merge multiple sets of transcriptions into 1.
There is no reason why  data should not be uploaded in chunks of transcriptions and effectively merged at the database level

**Comment by Captainkirkdawson** [comment]
The new file naming scheme permits parts
File naming in CEN2#881
No further components are required.
This can be closed
