### ISSUE TITLE
Modify the CSV record view to display the additional ED fields

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#859]

**Comment by Captainkirkdawson** [comment]
Fields added to the display.
deployed to test3 to have user testing

**Comment by PatReynolds** [comment]
Hi @Captainkirkdawson I don't have any files on FreeCEN to modify.

**Comment by Captainkirkdawson** [comment]
Pat; this story was about modifying the program that displays records that have been uploaded as csv directly into CEN and processed by CEVProc.
You have access to Manage Counties ; so select SOM and select the Review Batches by Filename.
You will see 3 files uploaded by Geoff for testing.
Select the second RG102359 which is recently uploaded.
On the subsequent display in the header options  select the Browse Individuals
![browse](https://user-images.githubusercontent.com/2874694/83154647-9bb7d280-a0bd-11ea-9654-38a71abab6e8.png)

On the list just show any of them
![entry](https://user-images.githubusercontent.com/2874694/83154795-ca35ad80-a0bd-11ea-9839-8d84e8ce7cc4.png)

**Comment by helhyde** [comment]
Hi Kirk,

When I go to Manage Counties, this is what I see:
[image: image.png]
What am I doing wrong?

Thanks,

Pat

**Comment by Captainkirkdawson** [comment]
@PatReynolds there is no image

**Comment by PatReynolds** [comment]
![image](https://user-images.githubusercontent.com/6338822/84173767-a2f3be80-aa75-11ea-8661-e536ce66b10a.png)

**Comment by Captainkirkdawson** [comment]
Permission to access all counties added for Executive Director
