### ISSUE TITLE
Coordinator can manage their transcribers using variety of displays

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#86]
Coordinator can review/add/delete/disable their transcribers using variety of displays; lists by all/active/name/email address/userid. Dependent on #85.

**Comment by PatReynolds** [comment]
Many of these features already brought over from FreeREG. @Vino-S can you list what remains?

**Comment by Captainkirkdawson** [comment]
The ones required are operational on test3

**Comment by PatReynolds** [comment]
Pat to work with Geoff on recruiting / trainig coords for testing.
