### ISSUE TITLE
In display of a csv entry we do not display the carry down fields. Should we?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#862]
Civil parish, folio page etc etc are not displayed on every record. The individual record display displays what is in that record rather than what is possible to carry down. Question is should the display in the CSV entry display what could be there through carry down or what is actually there. **Now the result from a search will contain the carry down**. I thought that in the display of what is in a file and record we should solely display the actual content. Will raise for general input of is your recommendation a decision.

**Comment by PatReynolds** [comment]
Closing as duplicate
