### ISSUE TITLE
167220533 Action Mouseovers (Geoff)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#866]
Issue reported by **somt.cen** at 2020-04-19 10:08:53 UTC
Time: 2020-04-19T10:06:44+00:00
Session ID: 2c1112efb97275884ab43dcb4485512f
Problem Page URL: [/freecen_csv_files/my_own](/freecen_csv_files/my_own)
Previous Page URL: [https://test3.freecen.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2020-04-19+10%3A05%3A10+UTC&session_id=2c1112efb97275884ab43dcb4485512f&user_id=somt.cen&problem_page_url=%2Ffreecen_csv_files%2Fmy_own&previous_page_url=https%3A%2F%2Ftest3.freecen.org.uk%2Fmanage_resources%2Fnew%3Flocale%3Den&feedback_type=issue](https://test3.freecen.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2020-04-19+10%3A05%3A10+UTC&session_id=2c1112efb97275884ab43dcb4485512f&user_id=somt.cen&problem_page_url=%2Ffreecen_csv_files%2Fmy_own&previous_page_url=https%3A%2F%2Ftest3.freecen.org.uk%2Fmanage_resources%2Fnew%3Flocale%3Den&feedback_type=issue)
Reported Issue:
Kirk

Can we do a mouseover on the Actions, please? 
It saves a newbie keep going back to the information. I naturally look for mouseover information on these types of screens

Geoff
    

![Screenshot](https://test3.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Added mouseover to all actions and deployed to tets3
Also made a number of clean up changes including making links have buttons in almost all cases

**Comment by geoffj-FUG** [comment]
Kirk

 

Mouseover works well.

 

What happened to editing? Is that now all off line? 

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

Got it

 

Makes sense. Show the error messages and warnings and edit there. Less confusing.

 

Geoff

**Comment by Captainkirkdawson** [comment]
The edit of an entry is still there but is only apparent when the entry is
being displayed. I was concerned about people going straight to an edit
without first looking at the entry they were about to eidt.

Perhaps I am being over cautious but!!!! If you think the action should
appear earlier it is trivial to add.

The edit of the file header  has been moved to a coordinator level action.
The only fields available were who transcribed the original and the locks.
I wanted to force the lock removal by the download to avoid transcribers
making a change and then removing the lock and then replacing the file
hence losing the edits. Again perhaps I am being over cautious but!!!
Kirk Dawson
Programmer and Technical Advisor
FreeUKGEN

**Comment by geoffj-FUG** [comment]
Kirk

 

I agree with both of those amendments.

 

Geoff
