### ISSUE TITLE
167220404 Locking file did not lock (Geoff)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#868]
Issue reported by **somt.cen** at 2020-04-19 10:06:44 UTC
Time: 2020-04-19T10:05:10+00:00
Session ID: 2c1112efb97275884ab43dcb4485512f
Problem Page URL: [/freecen_csv_files/my_own](/freecen_csv_files/my_own)
Previous Page URL: [https://test3.freecen.org.uk/manage_resources/new?locale=en](https://test3.freecen.org.uk/manage_resources/new?locale=en)
Reported Issue:
HO107935 was locked accordingto the screen message when I made an edit to a record. The screen shows it as having errors (red) and does not show it as locked.

Geoff
    

![Screenshot](https://test3.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
Unable to duplicate
