### ISSUE TITLE
Add links to good gazetteers to help for Transcribers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#869]
https://www.genuki.org.uk/gazetteer
https://www.visionofbritain.org.uk/expertsearch
gazetteer.org.uk

**Comment by geoffj-FUG** [comment]
May I fly a kite?
We now have a Gazetteer of our own with Latitude and longitude. In transcription etc we can use a Locate button to open Google maps and see the place. In Validation we make sure that the POB is valid and in our database (unless we cant).
If this locate facility was added to the person in a household in the search results when Birth Places are displayed to the researcher, then the researcher could see the Place on Google Maps. 
Geoff

**Comment by Captainkirkdawson** [comment]
Is there any further need for this?

**Comment by PatReynolds** [comment]
I don't see a need for the original story - but there doesn't seem to be a story covering Geoff's suggestion, so I'll make one.

**Comment by geoffj-FUG** [comment]
The original story is no longer required.
We have created a Gazetteer which will become very comprehensive, and not restricted to the UK, over time. The Handbooks recommend three other Gazetteers, two of which were used as sources for our original version. 
There is no longer a need for other links from FreeCEN. Our Gazetteer is gaining in popularity and credibility and we should back it.
Geoff

**Comment by PatReynolds** [comment]
Thanks, Geoff - It is closed, and I have made the story for your suggestion that we link from the place shown to the researcher to google maps - something like this already exists in FreeREG  - I will comment more on that story.
