### ISSUE TITLE
Coords can Add information to profile of transcribers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#87]
Include transcriber agreement status

**Comment by PatReynolds** [comment]
I now have a csv spreadsheet of transcribers, to each of which I've given a unique ID.  It contains a lot of information about some (such as role, the name of their co-ordinator, etc.

**Comment by richpomfret** [comment]
@FreecenBren to look at this - the functions should now be there - what do we need to do in order to make it accessible?

**Comment by PatReynolds** [comment]
This appears to work.  I have just modified @Captainkirkdawson  's data - he now lives "Somewhere cold" and has a skill level of "complicated forms".

**Comment by Captainkirkdawson** [comment]
There is no new code. The capability has been there since FC was updated to multimodel.
Closing
