### ISSUE TITLE
Add latitude and longditude to the FreeCEN Gazeteer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#870]
Add lat and long to the FreeCEN Gazeteer (the list of standardized place names to be used alongside the TWYS of Place of Birth, part of Validation) to enable search by 'nearby places' and stories involving mapping.

NB the Ecclesiastical Parish point data is established for FreeREG.

The Vision of Britain data is available (aka the Administrative Unit Ontology) for all administrative units - see https://www.visionofbritain.org.uk/expertsearch#tab04  We have the point data for these, are working to gain access to the boundary data.

**Comment by PatReynolds** [comment]
https://www.ordnancesurvey.co.uk/business-government/products/open-map-names a possible data source

**Comment by Captainkirkdawson** [comment]
Is there really such a thing as the Freecen Gazetteer? It is not part of Freecen2

**Comment by geoffj-FUG** [comment]
This has been done on FreeCEN2 in the Place Names Database in CSVProc.
Our starting point is about 50,000 British Place names with latitude and longitude plus 2800 Irish Civil Parishes and Baronies also with latitude and longitude. This will be added to by Validators during validation.
Geoff
