### ISSUE TITLE
Search issue: PARMS Function (for discussion)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#875]
PARMS2 will check the civil parish name against a list of standardized parish name (i.e in the files produced by @richardofsussex), and the Chapman Code  against the Chapman Code of that civil parish (e.g. Bitton GLOS causes a reject, and Bitton SOM an accept.)

NB this is a search issue, not a database structure/content issue.
It could be resolved by using the  **Freecen2CivilParish** data, which has both the name and the appropriate chapman code.

**Comment by PatReynolds** [comment]
Not sure why I'm on this - could someone let me know what is needed?

**Comment by Captainkirkdawson** [comment]
@PatReynolds You raised the story and assigned it to yourself on May 28. Until its discussed I for one do not know what is required

**Comment by PatReynolds** [comment]
Putting for review as I thinkn this has been completed as part of the PARMS2 work.

**Comment by richpomfret** [comment]
Completed.
