### ISSUE TITLE
Update instructions for amending transcriptions of pieces using FreeCEN2 systems

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#877]
Update instructions: for editing files in FreeCEN2: 
Those editing existing pieces need to understand that “just fixing a typo” may involve quite a lot of work.  Instructions need writing on how to do a bulk update of the abbreviated format to the full format.

**Comment by Captainkirkdawson** [comment]
There will be NO amending of pieces under Freecen2 parms

**Comment by PatReynolds** [comment]
@PatReynolds to check in Geoff's handbook.

**Comment by PatReynolds** [comment]
An example of where a correction might be needed:
Transcriber transcribes a surname as 'Allcock' (it is a dreadful photograph and that is as good an interpretation of bad handwriting badly reproduced as can be expected).

Someone later has access to a better photograph, and realises that the name is Aucock.  Following the due checks, it is agreed by the project that 'Allcock' is an error, and 'Aucock' is the name that should be in the database.

I believe the function may be "reload a file".

Is that the case @geoffj-FUG

**Comment by geoffj-FUG** [comment]
Pat
Its not in the Handbook yet.
We have got to Incorporation. Editing a piece after Incorporation has not been tested yet so there is no process.
Geoff

**Comment by geoffj-FUG** [comment]
Rich 
Currently in progress. Once testing is completed I will prepare the instructions.
Geoff

**Comment by geoffj-FUG** [comment]
First darft of the Instructions is in the November version of the Full Handbook in Coordinator's Actions.
I have sent the pdf version of the Handbook to Kirk this eveing to replace the existing Handbooks on test 3.
Geoff

**Comment by richpomfret** [comment]
Thanks @geoffj-FUG. Now closing this story. Let's open a new one if appropriate.
