### ISSUE TITLE
File naming in CEN2

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#881]
I have just realized that we adjust not only civil parish and census district names to fit within 20 characters (A constraint we are removing)

But we actually change the piece naming used by TNA in our naming of vld files and in much of our documentation. rg RS 9/1 .... RS 9/1889

We drop the space after the RS , we insert a leading 0 before the 9, we drop the / after the series and before the numeric  ie RS091889

I gather this was also to accommodate an 8 character limitation. 

We are going to run into a problem with 1911 and likely 1921 there there are more than 9999 pieces ie the series runs from  RG14/1 to RG14/19412 

The initial design of CSVProc was it uses the file name to identify the piece. My initial coding had been around an 8 character field (I knew not better)

Is now the time to stop messing with the names provided by TNA and have the code extract according to their formatting as well as the old structure. All old names would not have / present. All new ones would.

E0 U3 (needed for 1911) S8 C6: P17

**Comment by FreecenBren** [comment]
NA use HO107xxx and HO107xxxx for 1841 and 1851

FreeCEN to upload to the Database we only use 8 digits so with some 1841
only having 3 digits for the PIECE number for all the PIECE Numbers we
improvise as follows.

FreeCEN for uploading to the DATABASE

For the 1841  3 digit numbers we use HO107xxx
for the 4 digit numbers for the piece number we use  HO41xxxx

1851 we use HO51xxxx

Then the NA use RG /xxxx  for all 1861 to 1901 (note the space before the
slash)

We use the following to make sure they are all in line with the rest and
have 8 digits.

1861 RG09xxxx
1871  RG10xxxx
1881  RG11xxxx
1891  RG12xxxx
1901  RG13xxxx

1911  different set up all together as each household is a separate page.
Geoff has been looking into that. And knows more about the numbering.

Not sure where you get the RS though, but Scotland use it  but it changes
when it goes online, but  England & Wales use as above.

**Comment by Captainkirkdawson** [comment]
TY @FreecenBren 

So you agree we manipulate the the File name  (or piece name) used by TNA  in order to met the FreeCEN1 requirement for an 8 character name. We do some heavy duty changes to 1841/51 because they were both in HO 107
The question I raised was since FreeCEN2 does not care about the length of a file name should we replace the structure and stay closer to the original. 
There would be no requirement to change existing files
But do we design one that remains closer to TNA. There would still have to be changes as a file name could not contain the / and spaces are undesirable. 
Likely more important issues

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @FreecenBren @rhodamackenzie 
We need to establish a file naming convention for CSV file uploads to CEN2. These files will not be processed into CEN1 so CEN1 limitations and structure do not need to be imposed.
The piece number field is now a string NOT an integer
The naming convention needs to support all countries including Ireland.
The naming convention needs to support multiple files for a specific piece; lets get away from massive files where there is just 1 file for a piece.
Naming should be as close to TNA naming but supporting Scotland and Ireland. 
Their structure is basically series/number. We cannot use that directly as the / is illegal in a file name. We could use series_number_part eg HO 107_989_1 or HO107-989-a ie use the hyphen or have the system accept either _ or - as the separator.
If we adopt that should we adopt that in our online numbering of a piece  ie RS10-1898 rather than RS 10/1898 as it is at that time

**Comment by geoffj-FUG** [comment]
Kirk et al
I am comfortable with the 3 part underscored solution.
England and Wales would be for instance RG10_1234_a (1871)

Or HO107_1234_a (1851)

OR HO107_234_a (1841)

Ireland would be ANT01_123_a (1901)

ANT11_123_a (1911)

Though I doubt the a, b etc will be used as the Coordinator can break up the DEDs into Townlands which are themselves small.
Now Scotland has me completely miffed. They had a numbering system. Now they have a table which converts pieces from their old numbering system to their new numbering system! Any logic that might be applied has eluded me as they have not explained their system the way that Ireland has. 

There are 2 options:

Brenda or Rhoda understand the system and can provide advice

We adopt our own numbering system as Scotland Archives seem to be playing silly b’s with it. 

Looking at what is online on FreeCEN for ABD

Aberdeenshire – 1841 (Scotland)


Piece

Place

Comprising

Status

Remarks


168/a

Aberdeen

East

Online

	
	
Aberdeen

Greyfriars

Online

	
	
Aberdeen

North

Online

	
	
Aberdeen

South

Online

	
	
Aberdeen

St. Clements

Online

	
	
Aberdeen

West

Online

	

168/b

Old Machar

Bon Accord

Online

	
	
Old Machar

Gilcomston

Online

	
	
Old Machar

Holburn

Online

	

 

                     

So, We could invent ABD41_168_a

This would conform to the Ireland solution and keep the existing FreeCEN references aligned with what Scotland Archives used to have. It would also be transparent as to which year and county 168_8 belongs to. That may not be so in 10 years time if the conversion table has disappeared.

 

Regards

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG since we have no material for Scotland the question is academic for CSV files which are the only ones that will use this system
Will proceed to amend the ingest code for TNA to follow the proposed sructure

**Comment by Captainkirkdawson** [comment]
Revised file naming implemented and deployed to test3

**Comment by richpomfret** [comment]
Closing - Ireland is a separate parms story.
