### ISSUE TITLE
Coordinators/checkers can add a piece or ED on-line

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#89]
Includes method for allowing ED (part of piece) to be added for whole piece - e.g. through creation of EDs within PARMS files.  Dependent on #85.

**Comment by PatReynolds** [comment]
May be amended following #89 - definition of work flow

**Comment by Captainkirkdawson** [comment]
Coordinators can edit and/or create a piece on line including the ability to add Civil Districts as well as the Enumeration District.  Running on test3

**Comment by Captainkirkdawson** [comment]
As we are moving towards a fixed complete parms structure based on TNA I suggest this be closed
