### ISSUE TITLE
Implement CEN2 parms while permitting CEN1 VLD file loading and searching

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#893]
The parms for CEN2 will have a different structure from CEN1 parms. Field lengths are relaxed in CEN2 so civil parish names can be inconsistent with CEN1 where they we shortened in a manner unique to FreeCEN. VLD files will use the CEN1 parms 
We need to consider how best to proceed with CEN2 parms implementation

**Comment by Captainkirkdawson** [comment]
Perhaps the cleanest solution is to create a separate collection freecen2_piece to support csv files rather than have 1 collection try to support both cen1 vld and cen2 csv That would leave freecen_piece  to support the vld files.

**Comment by Captainkirkdawson** [comment]
Have discussed with Geoff at some length and propose to use a parallel collection used only by CSV loaded files; at least initially.
Changing title to implementation

**Comment by Captainkirkdawson** [comment]
The conceptual logical relationship being proposed is:
Year / Country (Archive) / Region (County, Island, Navy) / Registration District (. Superintendent Registrar's District) /  Registration Sub District or Piece (Local Registrar's District) / Enumeration District  / Civil Parish /   Dwelling / Individual.  
That does not mean a collection at each level; initially I plan to evaluate performance with 4 collections
1. Year / Country (Archive) / Region (County, Island, Navy) / Registration District (. Superintendent Registrar's District) /
2. Registration Sub District or Piece (Local Registrar's District) / Enumeration District  / Civil Parish /  (This will also contain information on hamlets, townships and tythings)
3. Dwelling
4. Individual
The Dwelling and Individual collections will be common to both vld and csv files and at this point a common search_record

**Comment by Captainkirkdawson** [comment]
Have implemented a Freecen2Place collection based on The REG place collection of 49000 records.
Have implemented a Freecen2District Collection that belongs to the place collection.
Have implemented a Freecen2Piece Collection that belongs to the district.
Have implemented a Freecen2CivilParish Collection that belongs to a piece.
All TNA extracts have been loaded into these collections and will serve as the basis for checking CSV files and their entries.
Deployed to test3
Reports on missing place names for Districts/Piece?Civil Parish have been generated. These need to be reviewed and the Freecen2Place collection updated

**Comment by Captainkirkdawson** [comment]
@PatReynolds @richpomfret @geoffj-FUG @FreecenBren 
To summarize. We no longer talk about a or b pieces where a and b have the meanings used in CEN1. 
We have instead a number of distinct collections,. All these collections have names that incorporate Freecen2; (the purpose of this is to enable the collections associated with Cen1 coexist with the new structure for CEN2 CSV files. )
At the top we have a collection called **Freecen2Places**. This is a collection of places their names, alternate place names together their Latitude and Longitude, the source of the information, the chapman code in which it is located, a link to the place on a map  and notes about the place.  Place can be edited. and the history of their edits is maintained. They cannot be deleted but they can be disabled. The cen1 places collection is extremely small (2000 places) so the Freecen2Places collection has been populated from the FreeregPlaces collection which has nearly 50,000 places.
The second collection is the **Freecen2District** collection which has its name, chapman code, the census year, the type of district (Registration District or hundred etc), a link to the archive (for England and Wales) and any codes used by the archive. This collection belongs to the Freecen2Places providing we can find an appropriate place to which it can be linked. **(When created from TNA we note if we are unable to find the place. We need to go through these reports and make the appropriate linkages or creation of places before final deployment)**
The third collection is the **Freecen2Pieces** collection. This contains the year, number and name of the piece, this is the sub district from which the census was managed. (**Note the number is NOT an integer and can contain a suffix if so designated by  the archive)**. This collection belongs to both the Freecen2District collections and to Freecen2Places providing we can find an appropriate place to which it can be linked.; initially if there is no place name we use the place with which the district is associated.**(When created from TNA we note if we are unable to find the place. We need to go through these reports and make the appropriate linkages or creation of places before final deployment)**
The fourth collection is the **Freecen2CivilParish** collection. This contains the name and notes of the civil parish. This collection belongs to both the Freecen2Piece collections and to Freecen2Places providing we can find an appropriate place to which it can be linked.; initially if there is no place name we use the place with which the piece is associated.**(When created from TNA we note if we are unable to find the place. We MAY need to go through these reports and make the appropriate linkages or creation of places before final deployment; this could be a LARGE task)**
There are 3 additional collections associated directly with Freecen2CivilParish. These contain any information provided on hamlets, townships and wards.
There are display and edit (restricted access) capabilities for the Districts, Piece and Civil Parish collections. The latter includes information on any hamlets, townships and wards. Access to the display is open county coordinators at this time and is available through the **Mange Freecen2 Pieces** action. There is no ability to create or delete any entries since these are a direct creation by a rake task using input extracted from the archives
Similarly display, edit, create and disable capabilities for Freecen2Place is open to county coordinators at this time and is available through the **Mange Freecen2 Places** action.

**Comment by PatReynolds** [comment]
For clarifciation - my understanding is: 
Search will be by County and then by  Freecen2Places ?
Place of Birth search will be by Country*/county/freecen2Places??
(*country being the chapman codes, including Overseas, etc., and including 'Scotland', 'Wales', 'Ireland' as requested in story #594?) 

Search results will show FreeCEN2 place as "census place" (i.e. not FreeCEN2District or FreeCEN2Piece or FreeCEN2Civil Parish)???

Detailed search results show data as at present (ie. FreeCEN2Place is not shown).

**Comment by PatReynolds** [comment]
How do the new proposed collections relate to the four collections mentioned earlier - are they a sub-set, or do they represent a replacement set of collections?

**Comment by Captainkirkdawson** [comment]
@PatReynolds there is no change in the search proposed or required of this structural implementation. It permit VLD and CSV to coexist. It prepares the ground work for changes to be made in the future.
For census it remains as it is now County / piece name. 
For birth it remains country/county with no ability to do country wide searches.
For now the search result will show what it does now; the piece name
Once implemented and once we can link VLDs to this new structure then we can make significant changes to the search and the displays
If your question **How do the new proposed collections relate to the four collections mentioned earlier**  refers to the comment of June1 then these 4 FreeCEN2Place; FreeCEN2District; FreeCEN2Piece; FreeCEN2Civil Parish do replace 1 and 2. Individual and Dwelling will remain as is.
