### ISSUE TITLE
Do not report setting initial values for fields that are not in the census year

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#896]

**Comment by Captainkirkdawson** [comment]
Code added. Deployed to test3

**Comment by richpomfret** [comment]
@geoffj-FUG if you have tested this, can you confirm and comment here.

**Comment by geoffj-FUG** [comment]
Rich 

 

I have now tested the broad functionality of CSVProc using 1871 and have extended this to the other years (I expect the same results but it has to be done). This all looks OK. Any problems can be handled within the testing regime.

 

This story can therefore be closed.

 

Geoff
