### ISSUE TITLE
FreeCEN1 failing to search

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#897]
A record I can find on FreeCEN2, e.g. Richard Alcock, born Yorkshire in the 1841 census) fails to generate a result in FreeCEN1.

**Comment by richpomfret** [comment]
Looks like we are having some issues on FC1. @lemon-ukgen any idea if anything has occurred recently or fallen over which might cause issues with search results?

**Comment by richpomfret** [comment]
@FreecenBren have we had any complaints or reports from users about search?

**Comment by lemon-ukgen** [comment]
I'm aware that we have two Norfolk VLDs showing as errors since their data is already present in other VLDs. I don't believe this would cause a missing result for another county.

**Comment by PatReynolds** [comment]
https://www.freecen.org.uk/search_records/59040e56e9379091b1907935  found on freecen2

Searching Richard Alcock born 1812, North Yorkshire on FreeCEN1for 1861 census now works.

Using chrome.  Be good to get a second pair of eyes to confirm this to confirm.

**Comment by DeniseColbert** [comment]
Description states 1841, however I've done the search in your last comment @PatReynolds and found your guy (also Chrome).
