### ISSUE TITLE
Correct the Census Place name in CEN1 1891 parms

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#899]
In the 1851_1881 parms the Place field was taken from the value in TNA Sub District field.
But in 1891 it was taken from the value in TNA District field not the Sub District as in all prior years.
This leads to a significant discontinuity in the Census Place values when doing the search?
For example look at  https://discovery.nationalarchives.gov.uk/browse/r/h/C131725 
Each of the pieces in that district have been given the Place name of Williton 
Rather than the Place names of  Minehead, Dunster, Williton, Stogursey, Stogumber respectively. As a result the latter do not appear as options for 1891.
This is common to all counties in 1891
The 1901 and 1911 Census will also use the Sub District
Brenda explained: _It is probably because we started with the 1891 census when we were using Micro Fiche and had to use the images to do the Parms as nothing was online as we know it today._
I believe it will be highly important to make corrections.

E3 U6 S8 C5: P22

**Comment by Captainkirkdawson** [comment]
What is required is to rebuild the search_records for 1891 having corrected the piece

**Comment by PatReynolds** [comment]
added priority just to check if this story is still live / has become urgent

**Comment by Captainkirkdawson** [comment]
The story is still relevant. What it means in the initial example is that for the census places for 1861, 1871, 1881 has Minehead, Dunster, Stogursey, Stogumber and Williton but in 1891 there is just the one place Williton which has them all.
