### ISSUE TITLE
Make the entry edit census sensitive

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#910]
Currently the csv entry edit includes all fields for all census years

Geoff correctly notes we should only include those fields relevant to the year

**Comment by Captainkirkdawson** [comment]
Edit is census sensitive; need to add validation

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Validation added. in addition to census sensitivity. 
Only individual information is permitted for on-line editing. Census location, Folio/Page and dwelling information must be changed off line because of need for propagation.
Ready for review on test3

**Comment by richpomfret** [comment]
Closing as per recommendation.
