### ISSUE TITLE
Check fields against spreadsheet

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#912]

**Comment by Captainkirkdawson** [comment]
Error if missing field

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 

First cut of checking of field headers has been deployed to test3.

Still have to add fine tuning for Channel Islands; 

Note that there may be an issue with the language field as we do not currently distinguish between England and Wales

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
There are 2 ways of dealing with language.

We create Wales spreadsheets that include language for the appropriate years

We detect that it is an english county and do not expect a language field

**Comment by geoffj-FUG** [comment]
Kirk

 

That sounds good. I now understand.

 

Isle of Man uses England and Wales spreadsheets and has language too. Is that covered?

 

Geoff

**Comment by Captainkirkdawson** [comment]
Sorry @geoffj-FUG I was less than clear. What my posting was meant to provide was an either or

**Either** we introduce spreadsheets for Wales for the years 1891-1911 and IOM for 1911 **or**  they and England use the existing spreadsheets but we do not require English counties to have the language field.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG I have programmed the or option **we do not require English counties to have the language field**

**Comment by geoffj-FUG** [comment]
Kirk

 

I am quite happy with the English counties not required to populate the language field.

 

I am comfortable with where we were at. I just needed to understand.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

Sounds Good

 

Geoff

**Comment by Captainkirkdawson** [comment]
geoff.jarvis@freeukgenealogy.org.uk
06:13 (11 hours ago)
to Kirk

Kirk

 

I am now happy with the way that spreadsheets are examined and tested for correct year when uploaded.

 

I am also happy with the way that language is handled.

 

Story 912 can be closed.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Leaving open as we still need to validate Scotland and Ireland

**Comment by geoffj-FUG** [comment]
Kirk

 

OK, that makes sense

 

Geoff
