### ISSUE TITLE
Unoccupied tests

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#914]
somt.cen/rg10_2377_b.csv processed at 2020-07-13 11:21:43 +0100 with errors over period
Testing unoccupied_flag (in Red below)

Row 10 OK

Row 11 special b not reported

Row 12 OK

Row 13 Special n not reported

ERROR: line 10 Schedule number is blank and not a page transition.
Warning: line 10 has special u but no schedule number.
ERROR: line 11 Schedule number is blank and not a page transition.
ERROR: line 12 Schedule number is blank and not a page transition.
Warning: line 12 has special v but no schedule number.
ERROR: line 13 Schedule number is blank and not a page transition.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
Corrected (I think)

**Comment by geoffj-FUG** [comment]
Kirk

 

The problem was the entries without schedule numbers that were not reported. They test OK now.

 

The items in red should be Info not warnings as they are correct.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Hope I have got it right this time; deployed to test3

**Comment by geoffj-FUG** [comment]
Kirk

 

Another glitch

 

If I put data on the same row as a flag (u, b, n, but not v) into fields after the address then we need an error that individual information cannot be included in a vacant dwelling. 

With the same test but a v is recorded we need a warning that that an individual is recorded who was away on census night.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Fixed on text3

**Comment by Captainkirkdawson** [comment]
Geoff is now satisfied so closing
