### ISSUE TITLE
Years Married Tests

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#915]
We need a set of rules here. (Similar to age)I have based them on age so you may be able to copy and paste the code and edit it.

 

My instructions now say:

 

Field name                     years_married

Column Contains              Years Married

Year/s Used                        1911 only

What Can Be Entered        Number or Complex number or blank

Description and Rules      Enter the value as shown in the census. The value should be entered only once for each married couple next to the female member of the family, usually enumerated as wife. Where no information is recorded leave the field blank.

Standard Rules for Years Married

·         If only a number is entered, it will be converted as 'years'. E.g. 26 or 26y will be converted to mean "26 Years".

·         y (Years) minimum value = 1, maximum value = 99

·         m (Months) minimum value = 1m, maximum value = 12m

·         w (Weeks) minimum value = 1w, maximum value = 4w

·         d (Days) minimum value = 1d, maximum value =7d

Any values outside the above guidelines will create Warning or Error messages when the transcription is tested.

If a duration is enumerated as 1½ years enter 1y 6m (note the space between the entries) and enter “years married enumerated as 1½ years” in the Notes column. Do not set a query flag when this happens.

If the census states "less than 1 year" then enter 1 or 1y and enter a note in the Notes field. Do not set a query flag when this happens.

Complex years married can be entered. For instance, if a marriage has been enumerated as 1 year 3 months it can be entered as 1y 3m (note the space between the entries). The transcription must still comply with the above rules for limits of both the years and months.

In England and Wales it is shown on the census return, in Scotland in the Enumerator’s return and in Ireland on Form A.

Note: Where the years married has been crossed out but is legible, record it with a note in the Notes field that the entry has been crossed out.

**Comment by geoffj-FUG** [comment]
Kirk

 

I have made a slight change to the notes at the end. I have added In this case set a flag so that the doubt is highlighted to the researcher.

 

It does not affect your coding.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG validation added and deployed to test3

**Comment by Captainkirkdawson** [comment]
Geoff is now satisfied so closing
