### ISSUE TITLE
Folio tracking 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#916]
Folio numbers are not being tracked.

 somt.cen/rg10_2377_a.csv processed at 2020-07-13 11:12:05 +0100 with errors over period

I missed folio 6 and put 4 pages on folio 7.

The gap needs to be reported similarly to pages.

A folio can only have 2 pages on it. Folio 7 has 4. It needs to be reported.

 

Both instances should be Warnings.

A folio consists of two pages back to back. So the number should change on every second page.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 

Have activated the warning on a folio skip

Do not know at this point how i would deal with the count of page test as to all intents each line is an entity on its own. CSV Proc uses prior value tracking for specific fields but the proposed test would require a matrix of prior values

**Comment by geoffj-FUG** [comment]
Kirk

 

I think a Folio skip should cover us OK. It has the same effect.

 

Whenever I got the old warning of too many pages it was because of a folio skip.

 

I will mark it as resolved.

 

Geoff
