### ISSUE TITLE
Marital Status

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#917]
somt.cen/rg10_2377_e.csv processed at 2020-07-15 12:25:42 +0100 with errors over period -
Marital status

 

I put the following sequence from Row 1 to Row 12

 

M

s

u

w

d

-

A

b

c

D

W

 

Rows 1 – 6 were valid entries and so no report – Correct

Row 7 is a – This is not valid on FreeCEN2 but was on FreeCEN1. I am happy to amend the instructions.

Row 8 is an A did not report despite it not being a valid character

Rows 9 and 10 reported OK

Rows 11 and 12 were valid entries so no report. OK.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 

Validation accepts  m,  s, u, w, d, - or blank 
test is NOT case sensitive

I suggest you amend instructions

**Comment by geoffj-FUG** [comment]
Kirk

 

I have added a note in the instructions re case sensitivity.

 

My concern is the handling of the -. The instructions in FreeCEN1 allow for it. The instructions in FreeCEN2 do not.

 

How do you want to handle it?

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG  CEN2 is happy with the -
