### ISSUE TITLE
Check for possible duplication on processing a file with a suffix into the database

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#919]

**Comment by geoffj-FUG** [comment]
Thinking about this one. What happens when we upload? Will there be a check as to whether the piece is a new piece or a replacement? Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG need to work out how to do this.

How about we save a list of the Enumeration districts in a file with the file then we go to incorporate a new file for a piece we check to see if the new piece has an enumeration district that has already been incorporated.

Means that a file cannot be smaller than a single enumeration district. 

Does this make sense?

Do we need to have an incorporated lock that the coordinator must remove before they can remove the records of an incorporated file from the database. There is a confirmation check on the removal action but I think we should make it more difficult. Comments?

**Comment by geoffj-FUG** [comment]
Kirk

 

I am happy with the ED being the smallest unit.

 

When we get a data error report from a researcher we need to download the last published piece. Is that in CSVProc or do we download the live piece? If so the ED would be a logical unit to download.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

Make sure you do not make a rod for your own back:

 

“For Ireland the ED number will always be 0 (zero) unless a special category is being transcribed”.

 

So an index style file will not work.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
Will go with ed for England and Wales. Ireland and Scotland will have to be thought about when we get closer.

It will be a CSV Proc download, edit replace or online edit: remove the incorporated entries and then incorporate the new version of the file
What about the incorporated lock?

**Comment by geoffj-FUG** [comment]
Kirk

 

Missed that bit, sorry.

 

Yes to an Incorporated Lock. It saves an accident one day.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Code written that checks that the civil district/ED for the new file do not match any that have been incorporated.
![duplicate incorporation.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/cd22fece-0b1e-45f3-a671-f9e41a7cb8a0)
incorporation lock developed.
Once incorporated the ability to reprocess the file or do further validation is removed.\
Deployed to test3

**Comment by geoffj-FUG** [comment]
Lock set when piece Incorporated successfully.
I still have to test an attempt to overwrite the file.
Geoff

**Comment by geoffj-FUG** [comment]
Kirk
I have created 2 identical files and validated them. RG14_14141_a and RG14_14141_b. (only 12 records)
I incorporated RG14_14141_a successfully.
I then tried to Incorporate RG14_14141_b. It was rejected.
Test for duplicate contents of files at Incorporation successful.
Geoff

**Comment by Captainkirkdawson** [comment]
Thank you
