### ISSUE TITLE
Handling of the hyphen - in the Verbatim POB

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#923]
If the Verbatim POB is unknown then a hyphen - is entered

**Comment by Captainkirkdawson** [comment]
As part of the Validation process we determine if the Verbatim POB exists in the Freecen2 Place collection.
If a Place does exist we generate a warning
"Warning: line #{num} Verbatim Place of Birth #{record[:verbatim_birth_place]} in #{record[:verbatim_birth_county]} was not found so requires validation.<br>"
If a Place does exist we generate an information message
"Info: line #{num} Verbatim Place of Birth #{record[:verbatim_birth_place]} in #{record[:verbatim_birth_county]} was found so does not require validation.<br>"

Clearly a Place with the name - does not exist. hence would generate the warning. However this is unnecessary as there is no expectation of finding a place.
It has been suggested that  a hyphen - place name is created for each county so that the the test passes.
This creates a great deal of work.
An alternative is to detect the hyphen and bypass the place look up and generate a new information message.
"Info: line #{num} Verbatim Place of Birth #{record[:verbatim_birth_place]} in #{record[:verbatim_birth_county]} was not present in the census so does not require validation.<br>"

**Comment by geoffj-FUG** [comment]
Kirk

 

Your summary is correct but I have done away with 2 info messages. If the POB is valid it does not need info (we do not generate info for other correct transcriptions, so lets keep things standard). 

 

See in red below.

 

Geoff

**Comment by PatReynolds** [comment]
Does this relate to #913 ?

**Comment by geoffj-FUG** [comment]
Pat

 

No. #913 is specially about ‘- being used in spreadsheets and causing errors in testing. It is used to stop the spreadsheet trying to create a formula or name. Because marriage and sex are only 1 character fields ‘- creates an error report.

 

This is about matching of place names where only the County has been enumerated. There is no place called – in the Place name file so we need to address the problem when the verbatim place of birth and place of birth fields are examined at validation.

 

Geoff

**Comment by geoffj-FUG** [comment]
Pat 

 

See comment on #498

 

Geoff

**Comment by Captainkirkdawson** [comment]
Do not attempt to search for POB if it is - so no warning message generated. Hence record will be valid if no other warnings or errors.
Deployed to test3

**Comment by geoffj-FUG** [comment]
Kirk

 

Sounds good. I will rerun a test piece

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG hold off the test; there is something odd in the code I need to look at

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG fixed it; Found that titlesize on a - ended up as blank!!!! New one on me

**Comment by geoffj-FUG** [comment]
This now works OK Geoff
