### ISSUE TITLE
Add accept record as an option on the record display

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#926]
Currently the only way of accepting a record is multi step (edit the record, set the record true flag, submit) returned to record display after processing.
It has been proposed that we add a Record is Valid, with challenge? as an additional option

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG added accept and reject options for the validator and deployed to test3

**Comment by geoffj-FUG** [comment]
Kirk

 

The button works well

 

Geoff
