### ISSUE TITLE
Add search of Alternative Place Names to POB validation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#931]
The current validation place name search only search the place name need to add search of the alternative names

**Comment by Captainkirkdawson** [comment]
Have added the alternative place names to the POB validation for both verbatim and Alt. Deployed to test3

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG please review

**Comment by geoffj-FUG** [comment]
I have run a test with the verbatimplace name and the alternate place name against both the main field and the alternative field in the master file. I have included 2 alternative names in the master file and it all runs OK. I have also tested - and that seems to be working as well.
Geoff
