### ISSUE TITLE
How to handle the difference between the Freecen2 Place collection and what was in the original Gazetteer of British Place Names

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#932]
Some 6 years ago we obtained a copy of the Gazetteer of British Place Names  as part of the development of REG. 
Over a period of 2 years we modified its content to ensure there was only a **single place name** with lat and lon for a specific county thus enabling  searches to be localized to a specific place and to support search of nearby places.
When making changes we were careful to not destroy any content. Any place name not required was simply disabled. When a place name was changed then the previous name was retained in an original name field
Most of the disabling was to remove place names with little or no habitation such as cross roads or geographic features since these were unlikely to have or have had a religious entity associated with it 
So the database still hold that information.

We have transported this database as is to Freecen2 Places for use in the validation of POB. 

Initial testing has shown that some (all?) of the disabled place names may be of relevance to CEN so likely should be enabled as a first step.

The other issue is that the modified place names designed for REG means that some place names that would likely have used to original name will not validate. 
An example of this is Wraxall in Somerset. The original Gazetteer had 2 entries with that name but with different Lat/Lon ie they were different places. For REG these places were made distinct One was called Wraxall (Nailsea) and the other Wraxall (Shepton Mallet).  Ant census POB using Wraxall will not validate using the the Freecen2 Place Name. A warning will be generated and the validator will be required to review the record.
The Search Place Names will immediately show there are the 2 options however they will not likely be able to say which of the 2 is the valid Place name.  Hence how to proceed? There are a number of possible solutions.
1. The validator reviews and accepts the record as valid since Wraxall is present in Somerset. This will have to be done for every occurence of the POB Wraxall. The basic collection would still  have unique places in a county.  A Nearby POB might still be feasible but research on how to handle the records with multiple possible locations would have to be established. 
2. We could do a second search is the first search fails. The second would search on the original place name field. In which case the Wraxall  is found and the record is validated with no reference to the validator.  The basic collection would still  have unique places in a county.  A Nearby POB might still be feasible but research on how to handle the records with multiple possible locations would have to be established. 
3. We could use the place name text index as the search field (as we do in the  Search Place Names app) This would find multiple entries for Wraxall and hence the record is validated with no reference to the validator. However the search is likely to pass many more records as valid e.g. in the case of  place name entry of St Ann any Place Name with Ann will result in the record being validated (Ann's Hill or The Ann Priory etc). The basic collection would still  have unique places in a county.  A Nearby POB might still be feasible but research on how to handle the records with multiple possible locations would have to be established. 
4. Revert to the original Gazetteer entries in Freecen2 Places collection.This would find multiple entries for Wraxall and hence the record is validated with no reference to the validator. But we no longer have a collection with unique places in a county. Any further attempt to reimplement a Nearby POB would have to be based on different concepts than unique locations: possibly using a selection from possible starting points based on the multiple locations.

There might well be other options.

My preference would be to implement option 2 as this preserves a unique places collection while permitting automatic validation if the place existed in the original Gazetteer.

**Comment by geoffj-FUG** [comment]
Kirk
Option 1 is impractical. Wraxall (just one) had a population of 769 in 1831 so it is probable that if you were validating a piece for the village and surrounding villages  there would be several hundred people to accept individually.
Option 3 would defeat the point of validation which is to have the best quality data set that can achieve. If that was adopted there would be no point in validation.
Option 4 is unacceptable for the future development of FreeCEN
So that leaves Option 2. I am quite comfortable with that solution from a validation point of view. 
I agree with the comment regarding nearby places but multiple place names were always going to create a problem to nearby places searches. 
Geoff

**Comment by Captainkirkdawson** [comment]
Will proceed on basis of option 2 and at same time add a display of the 2 original field (county and place) to the place name display

**Comment by geoffj-FUG** [comment]
Kirk

 

I am happy with that

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG We now check against 1) Current place names, then 2) alternate place names then 3) original place names from gazetteer 
We use a standardized format for the name and the name being search for to avoid case and whitespace and - in the name. We could consider other standardization if warranted.
The display of a place now includes the alternate and original names (also added the standardized version primarily for information at this time. Could be removed if it is confusing.
Running on test3

**Comment by geoffj-FUG** [comment]
Kirk

 

You said “We use a standardized format for the name and the name being search for to avoid case and whitespace and - in the name.”

 

We have a case at the moment which is being tested for results.

Braunton RUT is transcribed as Braunton, Braunton in Rutland or Braunton-in-Rutland depending on the enumerator.

 

My solution was to add 2 alternatives to the Place name file (John is looking to see what exists). So notionally we could end up with Braunston and 2 alternative names Barunston in Rutland and Braunston-in-Rutland. Validators have got around this in the past by using their Placesup file to allow ‘as is’ transcription of the name, which should continue and the alt POB fields be used for the standardised name. 

 

We are currently using Broad test which allows the transcriber to enter a – in the place name (that is the text version that we need).

 

The Warnings are dropping the – in the name. 

 

How do you want us to handle this? Or does the search just ignore the difference between white space and the -?

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
Taking your case
RUT has Braunston-in-Rutland  from the Gazetteer which provides a standardized name of  [braunston in rutland] see
https://test3.freecen.org.uk/freecen2_places/53cbf605eca9eb03a60084d2?locale=en
This means that multiple versions entered by a transcriber will match to this place as **their entry is also standardized for matching**
eg
Braunston-in-Rutland
Braunston in Rutland
Braunston - in - Rutland
Braunston  in  Rutland
braunston-in-rutland
BRAUNSTON-in-RUTLAND
And many other similar variations
There is no need to enter those preceding types as alternates
**You would however need to enter Braunston as an alternate to get a match**
Similarly if there are entries that drop the s from Braunston  as you seem to imply
You would likely want to add
Braunton-in-Rutland and Braunton as alternates
Yes the - does not like being titliezed looking for the solution

**Comment by geoffj-FUG** [comment]
Kirk

 

I now understand, thank you.

 

From that I assume that any searches that are developed in future for researchers to use will also be standardised. (E.g. Search for Jarvis living in Backwell SOM)

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

Does this titliezing resolve the Bishops Hull / Bishop’s Hull inverted comma problem?

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
The standardization drops the following characters from the name .,'(){}[] so there is no issue with using Bishops Hull or Bishop’s Hull both will match to the same Place
It also converts Saint to St for consistent matching 
St. or St will both match to the same place as will nr and nr.
There are other standardizations that **could be considered if needed eg on/upon nr/near**

Yes it provides the basis for improved searches **in the future**

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

I have just learnt something new.

 

I have included this is FAQ in the Handbook.

 

Geoff

**Comment by PatReynolds** [comment]
Hi Kirk, what will happen with Stockton-on-Tees vs Stockton on Tees?  Sometimes I think the hyphen is needed 

Stooke on Trent is six towns one of which is Stoke upon Trent.... see https://en.wikipedia.org/wiki/Stoke-upon-Trent for the dates involved.

**Comment by Captainkirkdawson** [comment]
@PatReynolds well there may be differences from an academic perspective. I am sure that the census takers were unaware of such differences.
I am unable to find any differences between Stockton-on-Tees and Stockton on Tees that would affect the searches being performed.  The location is centered in the same place.
I would say the same for Stoke.
The benefits of standardization far out way such nuances. At least in my opinion

**Comment by PatReynolds** [comment]
Sorry Stockton was a red herring.  But Stoke on Trent is a different geolocation to Stoke upon Trent (just as London (metropolitan area) is different to the City of London.  Stoke on Trent only comes into existence in 1910 (as a couunty borough).  But thinking about this further - the old borough / county boroughs were often identical names, so for most places, there is no remidying the confusion.  So yes, we'll take the criticism for 'the wrong name' for Stoke in order to have the advantages of standardization.
