### ISSUE TITLE
Make County of Birth UNK appear in search results with the text:  Unknown

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#936]
See for example a search for this Mary Alcock:
"General Register Office: 1871 Census Returns database, FreeCEN (https://www.freecen.org.uk/search_records/59047549e9379091b1457681 : viewed 18 Aug 2020), Mary Ann ALCOCK in household of Wm ALCOCK, Wickhambrook, Suffolk, England; from 1871 "England, Scotland and Wales census," database and images; citing The National Archives RG 10/1712, Folio 82, Page 6, Schedule 30, The National Archives, Kew, Surrey.

Interestingly the 'unknown' county of the place is the same place the census was taken - but this issue is not about which county Wickhambrook is in - it is about what would happen if a place could not be identified, or (as with Newport) could be in a number of counties.

**Comment by AlOneill** [comment]
I have a problem with the word "Unknown". Surely "Not recorded", or similar, is more appropriate? That is, the county will have been known, just not written down (by householder and/or enumerator).

**Comment by Captainkirkdawson** [comment]
But all the counties have the chapman code displayed in the detail but not
the summary results

Kirk Dawson
Fairmont, B.C. Canada

**Comment by PatReynolds** [comment]
I thought on search restults an expanded version of the Chapman code was used: e.g. code is  LDN displayed is  London.

Hence story to make WLS (etc) display Wales (etc).

UNK needs a word that both covers 'not recorded' and 'a place is recorded but cannot be allocated to a county - e.g. is "Newport".

**Comment by FreecenBren** [comment]
The CHP code for London is LND not LDN

**Comment by Captainkirkdawson** [comment]
@PatReynolds 
The search results uses the name; the details uses the Chapman Code.
![details](https://user-images.githubusercontent.com/2874694/90659894-780ab100-e202-11ea-8c03-52bc34535988.png)
![results](https://user-images.githubusercontent.com/2874694/90659896-78a34780-e202-11ea-8062-5cfd4d8854cd.png)

We have always used Unknown for UNK on both Reg and Cen.

**Comment by geoffj-FUG** [comment]
This is directly related to #937.
UNK appears to be displaying properly, as are SCT, IRL and ENG. WLS is not.

**Comment by geoffj-FUG** [comment]
This is completed and can b closed.

Wales is issue #937.

Geoff
