### ISSUE TITLE
Breadcrumbs for Search Place Names need to handle navigation back to it after Place Name Creation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#938]

**Comment by Captainkirkdawson** [comment]
Search Names Breadcrumbs updated and reecen2_place creation/editing form edited to  permit multiple alternates at the same time.
Deployed to test3

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Please review

**Comment by geoffj-FUG** [comment]
Kirk
Tested and works well. I have both added a new place and added an alternate name. I have also destroyed a name. In each case I can return and research using the breadcrumbs.
Geoff
