### ISSUE TITLE
Create error message address is not associated with a schedule number

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#941]
I got caught the other day and John got caught today so it is going to happen often.

 

Can we have a new error please for ‘address is not associated with a schedule number’ where the address and /or house number field is completed but the schedule number is not.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG That condition would have generated the following Error Message
"ERROR: line #{num} Schedule number is blank and not a page transition.<br>"
The situation will now generate 
"ERROR: line #{num} Schedule number is blank and there is an address.<br>"

The former message may still occur for other conditions

Deployed to test3

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

Will test later.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

Works well

 

Geoff
