### ISSUE TITLE
Check error message on reload

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#942]
If I try to Reload a file that is locked because it has been edited it will not reload. That is correct. There is no message on the screen to indicate that the file could not be reloaded because it had been edited.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Message was missing in 1 of four situations, Fixed and deployed to test3

**Comment by geoffj-FUG** [comment]
Rich
Working fine now
Geoff
