### ISSUE TITLE
Create link to download FreeCEN Handbook

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#943]

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Link to Handbook added

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

I will send you the next version of the Handbook in a few days.

 

It will be a monthly update for the time being.

 

Geoff

**Comment by Captainkirkdawson** [comment]
No problem
