### ISSUE TITLE
Investigate report of stray messages

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#944]
Almost all actions result in the generation of an "action report message". 
This is in the form of a flash notice. All pages are designed to display and clear the the flash notice. 
Normally the page being displayed is  associated with the action. For example if we edit something we display the recult of the edit together with the edit flash notice.
Sometimes it is not; a good example is the download. we generate the flash message but do not go anywhere. Therefore the message that the file was downloaded will appear whenever we go to a new page..

![image001.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/cfe32b28-09e6-4703-b700-f9d47f11fb2f)

These situations will be extremely difficult to track as they depend on the series of actions undertaken which often cannot be replicated.

Use of the browser back button does not display a new flash message. It will appear when a new page is downloaded from the server

**Comment by AlOneill** [comment]
@Captainkirkdawson Isn't there an alternative to flash, flash_now or something similar, that displays the flash message only once? I think it is designed to cope with this sort of situation, where a repeat is not helpful or needed.

(Previously posted to wrong issue and deleted there.)

**Comment by Captainkirkdawson** [comment]
Have removed the download successful message as this could appear anywhere.
Other cases need to be specifically identified.
This should be closed after review

**Comment by geoffj-FUG** [comment]
Kirk
To be honest I have not come across the problem. As I dont have an instance I cannot try to replicate it.
I will see if John has come across it.
Geoff
