### ISSUE TITLE
Possible issue with breadcrumbs after failed upload

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#945]
Kirk

I tried to upload a piece that was already there. I got the correct message to tell me to reload it.

 

I tried to follow the breadcrumbs to My Files but it has locked into this screen. The breadcrumbs do not work.

 

I can get back via the main menu at the top of the page.

 

Geoff!
![image001 (1).png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/7d91d5a3-6469-4482-b847-54ede789ab72)

**Comment by Captainkirkdawson** [comment]
Believe this to have been corrected following related changes to issues around locked files. Propose to close unless it is shown that there is still an issue

**Comment by geoffj-FUG** [comment]
Kirk
Now works well
It can be closed
Geoff
