### ISSUE TITLE
1841 POB issue

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#946]
Kirk

 

We have a problem in 1841.

 

There were no entries in verbatim_place_of_birth, only in the verbatim_birth_county. Every entry is being rejected as needing validation.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Turned out to be a miss positioned end after the test for 1841 when adding validation.
fixed on test3
@geoffj-FUG please review

**Comment by Captainkirkdawson** [comment]
See comment is review of #947 by @geoffj-FUG

**Comment by geoffj-FUG** [comment]
Kirk

Tested by myself and John and now working correctly

Geoff
