### ISSUE TITLE
Warning on POB when Chapman invalid

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#947]
FW: somt.cen/RG12_1936.csv processed at 2020-08-21 12:05:42 +0100 with errors over period

See Rows 157 and 158

 

These have produced errors on the Chapman Code quite correctly.

 

But then the Warning comes up that the POB is found but MAY require validation. Once the error occurred this warning should not have come up because the Chapman Code is incorrect.

ERROR: line 157 Alt. Birth County SON is invalid value.
Warning: line 157 Alt. Birth Place - in SON found but MAY require validation.
ERROR: line 158 Alt. Birth County XYZ is invalid value.
Warning: line 158 Alt. Birth Place - in XYZ found but MAY require validation.
ERROR: line 159 Alt. Birth County OUC is only used in 1841.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG deployed fix  to test3 for this and similar situations.

**Comment by geoffj-FUG** [comment]
Kirk

 

Now working fine (including rejection of ouc except 1841).

 

Geoff
