### ISSUE TITLE
Verify alt place name when on line edit

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#948]
Currently there is no look up or verification of the alt place name entered during an on line edit.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG The validation code used in CSV Proc added to the on line edit and deployed to test3

**Comment by geoffj-FUG** [comment]
Rich, Kirk
There seem to be 2 issues on this #948. 
The first is testing the Alt Place Name entered suring an online edit. That works fine.
The second id Propagation. That will be a post-cutover enhancement and is covered in #934. That has not been instituted yet. 
Geoff
