### ISSUE TITLE
1901 Census does not separate the ridings of Yorkshire

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#949]

**Comment by Captainkirkdawson** [comment]
In every Census year EXCEPT 1901 TNA has the census for Yorkshire separated by Riding. In 1901 they are all combined under a single county of Yorkshire

**Comment by PatReynolds** [comment]
I know of no reason why the TNA chose to break with tradition in 1901.  If there is no reason to hold to the TNA's structure, I would retain the three-ridings model for consistency.

**Comment by Captainkirkdawson** [comment]
I am afraid that since TNA has lumped 1901 Yorkshire we have no alternative but to follow along as we have no simple way of separating the pieces into the ridings. Ancestry also has followed along!

**Comment by PatReynolds** [comment]
I'm assuming that (worst case scenario) that some pieces cover more than one riding.  How many pieces are we talking about?  @richardofsussex would the ontology help here?  The Ridings were summarised separately, so presumably the tables listing the pieces could be downloaded/purchased from the TNA.
In the Internet archive they have the Census of England and Wales. (63 Vict. C. 4.) 1901: General Report which lists the districts covering more than one county (nb Leeds and West Yorkshire are different counties). 
![image](https://user-images.githubusercontent.com/6338822/91875167-08210f80-ec73-11ea-87a0-9c85c51919d7.png)
![image](https://user-images.githubusercontent.com/6338822/91875538-82519400-ec73-11ea-8864-87eb797cc488.png)

**Comment by richardofsussex** [comment]
I think we can tackle this using the data we already have from TNA. There are 60 top-level Districts within Yorkshire: we just need to know which Riding each was in.  Then, within the data, out-of-'county' parishes are flagged up specifically:
![image](https://user-images.githubusercontent.com/2197102/91885829-4ec93680-ec80-11ea-8d08-f4807621c48f.png)
(This doesn't apply just to Yorkshire - other out-of-'county' parishes are also flagged up, if we have the energy and interest to analyse them out.)

**Comment by PatReynolds** [comment]
If you send me the list of districts Richard, I can allocate them to Ridings (or Ridings and York) - I'll put those that are in two ridings in both ridings.  Ill do that in my own time as I've been meaning to do it for ages as a help to other genealogists who don't really have any clue just how big, how diverse, Yorkshire is.  

What would be the best way of getting the information to you,  Kirk - I was thinking maybe a table with  each District being in a separate line, and a column for each Riding/York?

**Comment by richardofsussex** [comment]
Here are the districts with their TNA identifiers, in a CSV file.
[1901 Yorkshire districts.zip](https://github.com/FreeUKGen/FreeCENMigration/files/5161493/1901.Yorkshire.districts.zip)

**Comment by Captainkirkdawson** [comment]
@PatReynolds Simplay add an additional field riding to the csv file created for you by @richardofsussex 
In the case where you want 2 ridings put both in the field with the second in () eg east (west)

**Comment by Captainkirkdawson** [comment]
@PatReynolds I am sorry to say that the file you have provided 
https://docs.google.com/spreadsheets/d/1PLjnwi4dz0d8Bf0pOsmc4F4SnCAAv9nKnw_z-W-jkao/edit?ts=5f676c5c#gid=0
does not help me
In the file that @richardofsussex provided there were 60 districts. We need to know which riding each of those districts are to be placed. 
I looked for the first 2 entries in the list of districts (Aysgarth, Barnsley) in your file and they were not there

**Comment by Captainkirkdawson** [comment]
Having looked up the districts in out Places collection I would propose to use the following ridings of Yorkshire for 1901
https://drive.google.com/file/d/1vwFJ6Wu-hCe-VOKaAK-Y-PT3r3s1SZzx/view?usp=sharing

**Comment by richpomfret** [comment]
@PatReynolds to review above list.

**Comment by PatReynolds** [comment]
I have checked Richard and Kirk's list, and noted two districts (Selby and Ripon) that appear only in Kirk's list.
There aretwo  districts that cross riding boundaries: I've suggested if only one is possible, it should be NRY (although for different reasons for Scarborough than for Malton).  Notes are on Kirk's document.

**Comment by Captainkirkdawson** [comment]
@PatReynolds about to action this story.
As you noted I have included Selby and Rippon as they do appear in the 1901 extraction.

We have Selby as WRY while you have indicated ERY 
 
We have Rippon as WRY while you have indicated NRY 

Checking the ABC Gazetteer our versions are the historic riding. The versions being suggested are not ridings but are the administrative divisions of Eastern Yorkshire and Northern Yorkshire.

**Comment by Captainkirkdawson** [comment]
Hane replaced YKS with the ridings for 1901 on test3

**Comment by Captainkirkdawson** [comment]
Test by selecting Manage County and use one of the ridings. Select Manage Districts and then select by year using 1901

**Comment by geoffj-FUG** [comment]
Kirk
Can you give me Coordinator rights to YKS please? I can then check that the above is complete (unless somebody else is already doing it?).
Geoff

**Comment by Captainkirkdawson** [comment]
Provided you with YKS and the 3 ridings

**Comment by geoffj-FUG** [comment]
The PARMS is now showing the Districts, Sub-Districts and Civil Parishes in their Ridings for 1901.
YKS no longer has any Civil Parishes in 1901.
I have not proofread for the integrity of the breakup on 100% of the County but all appears to be OK.
Geoff
