### ISSUE TITLE
Display relevant years in place selection form

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#95]
Doug wrote in #75:
"I do think we should consider opening a story to add the years with data into the places selection list, like it is in FC1. That would reduce confusion when users see things like Chester le Street / Chester-le-Street. It is confusing in FC2 to have both places because nothing indicates what the difference is, but it is obvious at a glance in FC1 that they are from different census years. Listing the years also indicates to the user whether data is available for a place during a given year without having to look through the database coverage pages and without unnecessary searches on places with no data."

This makes a lot of sense.  We could also filter the place list based on the selected census year(s) similarly to how we filter counties, though that might be laborious.

**Comment by FreecenBren** [comment]
I agree. I have emails complaining that they cannot find an entry that they found on Ancestry etc.

I have to explain that the year they were looking at has not been completed as yet or we have not started it.

I have to then also give them the STATS page link for them to see what is available.
