### ISSUE TITLE
Decision on level(s) (District? Subdistrict? Civil Parish? Hamlet?) that will need georeferencing 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#950]
Georeferencing is needed for map stories and for searching by 'nearby places'

P20 based on an estimate of 1

**Comment by Captainkirkdawson** [comment]
Please explain what you mean. I do not understand

**Comment by Captainkirkdawson** [comment]
We currently geo-reference District, Piece and Civil Parish places within the Gazetteer.
Hamlets and townships are not themselves geo-referenced.
Suggest this be closed

**Comment by DeniseColbert** [comment]
All levels are now georeferenced in gazetteer so closing
