### ISSUE TITLE
Complete linkages from Freecen2 Civil Parishes to Freecen2 Places 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#951]
Many Civil Parishes named in TNA have no current entry in the Places collection.

This connection is required to ensure that we can ultimately  use the Place and a Nearly capability.

Manual additions of connection will take months if not years.

As a temporary measure we will assign the Place for a Piece to the Civil Parishe if a direct Place does not exist. 

If the Piece does not have a Place we will assign the Place for the District to both the Piece and the Civil Parish

**Comment by Captainkirkdawson** [comment]
As a result of making the district /place linkage we have the following situation

![census parms.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/10a58e34-adb8-4eb5-b1c5-e6f8d97c85f3)

**Comment by Captainkirkdawson** [comment]
1841 has a unique problem in that the params are using hundreds rather than places. Not sure how to address this.
In the years after 1861 onwards the use of LND creates a specific problem as many of the places are in MDX KEN etc. It appears there are 30 LDN Districts to be located.
The effort to identify places for districts is now a relatively limited task.

**Comment by Captainkirkdawson** [comment]
1901 is caused by Yorkshire being used by TNA rather than a riding

**Comment by Captainkirkdawson** [comment]
Have added the ability to list those Districts/pieces/civil parishes that have no place Deployed to test3
![list place.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/6a566ec7-a1f5-47d2-881c-de770cbf2b56)![list missing places.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/e94d61e8-8b37-4123-96bf-c92db0a980c8)

**Comment by Captainkirkdawson** [comment]
and those pieces/civil parishes that are using the district place.
![list district.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/dc2c3e17-8eb7-4b63-8eac-8d5b0e83cb48)![district names.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/de2d9c22-601a-4ae2-9034-b6c9cd6d13ed)

**Comment by richpomfret** [comment]
@PatReynolds @richpomfret to take a look and have a play/test with this.

**Comment by geoffj-FUG** [comment]
I have tried it within the linking of the PARMS and it seems to work well in that context
Geoff

**Comment by Captainkirkdawson** [comment]
Need to ensure that coordinators are aware of their need to clean up the linkages

**Comment by geoffj-FUG** [comment]
Kirk

 

That is part of the Newsletter that is scheduled for week commencing 16 November. The detail is scheduled for week commencing 7 December so that nobody starts trying to do things whilst you are setting up the system.

 

Geoff
