### ISSUE TITLE
Cancel edit button

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#954]
Paul wrote
I suggest that a Cancel button might be a good idea in the Edit page, to be used if one wants to leave the record being edited unchanged. Back buttons might also be useful, though one can use the browser back button. 
@geoffj-FUG commented
Kirk, can we include the Cancel button please? I have been using the breadcrumbs without Submitting but a cancel button is more user friendly.
My comment
It would duplicate exactly what the breadcrumb is designed to do. Personally I would prefer to see people get used to the breadcrumbs. You can step many steps backwards with them

**Comment by Captainkirkdawson** [comment]
Added a Cancel button to the Edit of an entry. Test3

**Comment by geoffj-FUG** [comment]
Kirk
Works well. 
It would be better if it could be moved down to the bottom next to the Submit button. That puts the 2 decisions together.
Geoff

**Comment by Captainkirkdawson** [comment]
Change made; added additional cancel above the Submit

**Comment by geoffj-FUG** [comment]
Kirk

 

Tested and works OK

Can be closed

 

Geoff
