### ISSUE TITLE
Make upload preset csv file type

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#956]
Paul wrote
When replacing a file it would be better if the file selector dialogue was set for *.csv rather than any file, assuming that only CSV files can be uploaded. 
@geoffj-FUG  wrote
Kirk, this is a good idea. Can it be done easily?

**Comment by Captainkirkdawson** [comment]
I know of no easy way to do this.
Reg volunteers have been using this upload capability for 5 years as it is configured

**Comment by geoffj-FUG** [comment]
Kirk

 

In that case let it go.

 

It was a ‘nice to have’ but not essential.

 

Geoff
