### ISSUE TITLE
Extend YKS and CHI and HAM POB testing

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#958]
Many entries have POB as YKS CHI or HAM we need to test all ridings and island for these

**Comment by Captainkirkdawson** [comment]
Implemented into test3

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG requests removal of CHI for POB testing; treat as Country

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Removed Channel Islands as requested

**Comment by geoffj-FUG** [comment]
Thank you Geoff
