### ISSUE TITLE
Coordinator lock to remain after download

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#961]
That is the way it was originally designed for Freereg. There the transcriber is the owner of the file at all times. The purpose of the coordinator lock is to show to the transcriber that their coordinator has made changes to the file. They then cannot make any changes until they have downloaded the file. Locks are then removed. There has been discussion about adding a permanent coordinator lock. 
In FreeCEN the lock would be applied by the Coordinator when the transcriber tells them that the piece is completed. This prevents overwriting.
The FreeCEN pipeline can be very long (I had a situation a couple of years ago where Somerset had a million transcribed records in it, though this is now considerably reduced). So the piece can sit for a while between transcription and proof reading for instance. The Coordinator will not want the file being fiddled with.
So can we make that lock only removable by the Coordinator please, and block any updating until the Coordinator removes the lock.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Coordinator Lock is now permanent on test3

**Comment by geoffj-FUG** [comment]
Kirk

 

Thank you. I will test it this evening

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk
All good. Can be closed
Geoff
