### ISSUE TITLE
Flag removal after validation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#962]
Further to my query last night about checked and passed records still appearing in the listings. This is only true in the “View Flags” button, so you still see all the records after you have corrected them.
For the “View Warning Messages” button, as you correct them they disappear form the listing and reviewing the page they are no longer there. 
It would be nice if the “View Flags” had the same coding to lose them from the display once actioned.

**Comment by Captainkirkdawson** [comment]
Requested clarrification

**Comment by Captainkirkdawson** [comment]
The flags are removed if a record is accepted. Deployed to test3 for testing

**Comment by geoffj-FUG** [comment]
Kirk 
The flags that went through to the database after validation used to convert the text to italics to highlight the doubt to the researched. Is this no longer so?
If it converts to italics we need to keep an accepted flag but ignore it if the record is accepted, It should no longer create a Warning as the flag is True but will be needed for the Researchers screen display.
Geoff

**Comment by Captainkirkdawson** [comment]
I thought you asked me to remove them in your request. So I did

**Comment by geoffj-FUG** [comment]
Kirk

 

I think we were at cross purposes. 

 

Now that I understand the Actions better, it was right the first time. Sorry.

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG **The flags that went through to the database after validation used to convert the text to italics to highlight the doubt to the researched. Is this no longer so?** This is news to me and does not happen so please clarify requirement. Are there others that I am missing?

**Comment by geoffj-FUG** [comment]
Kirk

 

It may have been lost between FC1 and FC2 or I may have it wrong.

 

Let me check

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

I was wrong.

 

So I am amending the instructions so that all flags have been resolved or replaced by Notes by the time Validation has been completed.

 

That means that we can test for zero Errors, 0 Warnings at Incorporation. If any exist then Incorporation cannot happen.

 

That removes a risk of a piece with Warnings or Errors being Incorporated and ending up with Garage in / Garbage out.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk
The test for 0 Errors, 0 Waeningsshould now be a story. "Cannot Incorporate unless 0 Errors, 0 Warnings"
It will need to be implemented to stop faulty records being incorporated into the database.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Deployed to test 3 a check that the file is clean before incorporation

**Comment by geoffj-FUG** [comment]
Tested and works fine
This story can be closed.
Geoff
