### ISSUE TITLE
Adjust Freecen2 Place fields that are displayed and/or edited

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#963]
I am looking at the form for entering a new Place to the place name file.

 

The screen appears to have been copied from FreeREG, who only deal with UK places and therefore Genuki becomes a reference.

 

I am currently adding New South Wales, so obviously that is not in Genuki.

 

Can we amend the caption to become more general please? Perhaps ‘Gazetteer website (e.g. Genuki)’ would be more suitable as it is less specific.

**Comment by Captainkirkdawson** [comment]
Changes made. Deployed to test3

**Comment by geoffj-FUG** [comment]
New caption is fine.
This item can be closed.
Geoff
