### ISSUE TITLE
Edit problem on next entry

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#964]
I have just looked at 3 consecutive entries of OVB Italy British subject. I decided to validate them together.

 

They are not in the Place names file as the default for Italy is OVF and OVB is an exception. So that is correct.

 

I accepted the first entry then clicked on ‘next entry’ so that I could accept that as well (and then the one after that).

 

When the next entry was displayed he button at the top of the page is still ‘remove acceptance’.

 

I have accepted the previous entry so when I click on ‘next entry’ I did not expect to still have focus on the previous record. I clicked on ‘remove acceptance’ and it removed the previous acceptance.

 

Once a record has been accepted can focus move to  the next entry when this button has been clicked please?

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
Lets discuss functionality.
The way acceptance is implemented is bimodal

Any record that has an invalid record (False) displays Accept Entry.
Any record that has a valid record (True) displays Remove Acceptance

This way the validator can declare  a valid entry to be invalid if they want to review it again for some reason.
It sets a warning message of Line nn: Validator requested reprocessing

So you wish to eliminate the ability to  declare  a valid entry to be invalid?

**Comment by geoffj-FUG** [comment]
I have just validated a piece and am comfortable with the system now. The enhancement of the buttons has helped a lot.
The condition that I had has diappeared. The Record Being Validated button has resolved this.
Geoff
