### ISSUE TITLE
Enhance navigation during validation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#965]
John has raised an issue that I have found to be an annoyance too.

 

He states

If you are in the view flags and view warnings panels, I think it would be beneficial to have a button to take you to the next flag or warning as appropriate rather than breadcrumb back to the previous panel and click on display for the next record.

 

I agree that it would be a big improvement if we could have a button that takes us directly from Warning to Warning in validation.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Have implemented better navigation when viewing the lists of records. Deployed to test3

**Comment by Captainkirkdawson** [comment]
A number of issues were identified during testing
The feature no longer applies the Individual list as that is the basic next and previous.
The feature has been split into 2 lines; next/previous navigation on one and edit and accept/reject on the second. With all on one line there were times when the edit/accept were selected in error.
Challenges are there for edit and accept/reject to give time for second thought.
The purpose of the Force Review is the opposite to the Accept. It enable a validator to say I want to look at this record again. The warning message entered is "Validator requested reprocessing"  This may be an unnecessary feature.
I believe to button naming is now consistent. One observation is that using next and previous work correctly but the next and previous flag etc buttons retain their PREVIOUS values; they are not recomputed.
Deployed to test3

**Comment by geoffj-FUG** [comment]
Kirk

 

This all looks good and works well. It is very user friendly.

 

You have also addressed my OVB Italy family report. You have stated 

“One observation is that using next and previous work correctly but the next and previous flag etc buttons retain their PREVIOUS values; they are not recomputed.”

 

I will put a note for the Handbook that that needs to be mentioned. The Next Warning ability eliminates this as an issue.

 

Geoff

**Comment by geoffj-FUG** [comment]
Kirk

 

Comments in red below

 

Geoff

**Comment by Captainkirkdawson** [comment]
Thanks @geoffj-FUG 
The comment “One observation is that using next and previous work correctly but the next and previous flag etc buttons retain their PREVIOUS values; they are not recomputed.” is no longer really an issue as in the latest update I added a current flag record (and equivalents) to overcome the issue. It means that after any navigation using next and previous  to sequentially look at records you can always go back to the warning or flag or whatever you were looking at by selecting the current button

**Comment by geoffj-FUG** [comment]
Thanks Kirk

 

I will look at it this evening

 

Geoff

**Comment by geoffj-FUG** [comment]
I have just validated a small piece and the buttons seem to be logical and work as intended.
Geoff
