### ISSUE TITLE
Write a log of changes when parms collections are edited or added to

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#966]
Version 1 that writes the log of changes for an edit to the District, Piece and Civil Parish collections is written and committed to test3

**Comment by Captainkirkdawson** [comment]
This is the content of the log that is created.![TNA Change Log.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/49f82e58-f144-4776-aed1-ad56c87c1e24)

**Comment by Captainkirkdawson** [comment]
At this point in time we do not have the ability to create a new document in the Districts, Piece and Civil Parishes collections as the initial specification indicated we would rely solely on TNA extraction.
If we move from this specification then a log capability will be required.

**Comment by richpomfret** [comment]
Completed - closing.
