### ISSUE TITLE
Country place of birth

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#967]
Currently POB is limited to county and the special counties. SCT Glasgow is not permitted. Do we need to permit country and check POB in all counties for that country in similar manner to YKS. Actual code implementation would be different.

**Comment by FreecenBren** [comment]
I have just had a PIECE for Gloucestershire and London that has a lot of ENG used 
(POB says England and nothing else and no County given)

**Comment by Captainkirkdawson** [comment]
Countries to be permitted but only with - hyphen as POB
No places to be added to country

**Comment by Captainkirkdawson** [comment]
@johnt-freecen The country codes are now permitted. A - hyphen will pass without comment. Anything else will raise a warning for the validator. Deployed to test3
@geoffj-FUG I believe this is what we agreed

**Comment by johnt-freecen** [comment]
Hi Kirk,

I have had a quick look and there is still a problem with what is displayed.

I had a record for SCT Hamilton which obviously gave a warning message. When you view the page the Verbatim County is blank not SCT. I selected the record to edit and entered LKS Hamilton and submitted the record which was successful. On viewing the record again the verbatim county field is still blank it should have SCT.

Regards

John

**Comment by Captainkirkdawson** [comment]
You may have to reprocess the file to get it set up correctly in the first place or enter SCT in the verbatim county field

**Comment by johnt-freecen** [comment]
Hi Kirk,

I think the problem is in the display of the data. The view panel is not displaying SCT in the Birth county entered field. When you edit the record then SCT is in the dropdown list of counties correctly, so the problem has moved from the original one.

Regards

John

**Comment by Captainkirkdawson** [comment]
@johnt-freecen please let me know the file and entry number so I can look directly

**Comment by johnt-freecen** [comment]
Hi Kirk, the piece in question is RG12_2489 and it's the 209th record

**Comment by Captainkirkdawson** [comment]
@johnt-freecen appears to be working now

**Comment by geoffj-FUG** [comment]
That sounds correct. I have not yet tested it. Geoff

**Comment by Captainkirkdawson** [comment]
Thanks I reprocessed the file
Kirk Dawson
Programmer and Technical Advisor
FreeUKGEN

**Comment by geoffj-FUG** [comment]
John wrote:
The edit screen is now allowing SCT at least to be in the Verbatim County and you can see it in the dropdown list, so the correction process is now working fine.
However if you look at the record as you view the individual, then the Birth County is blank not SCT so we are not seeing what is transcribed. I think this is a minor issue that should not impede us moving forward,

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @johnt-freecen I believe that the file has to be reprocessed to get the field to display

**Comment by johnt-freecen** [comment]
Hi Kirk,

I have reprocessed the file 2 or 3 times now and still the verbatim county does not displat.

Regards

John

**Comment by geoffj-FUG** [comment]
John also says
This problem was fixed and working a few days ago. The value SCT was in the Verbatim County drop down list.
I have just tried another Scottish place I entered the new county and place ,hit submit and we are rack to the message.
The update of the entry failed ["Verbatim birth county Invalid; blank"]
When I checked the drop down county box SCT has disappeared again.
Not certain what has happened.
Geoff

**Comment by Captainkirkdawson** [comment]
I need to confirm this reporting is still for RG12_2489.
I have downloaded that specific file; the first version uploaded. Now loading onto my server and testing.

**Comment by Captainkirkdawson** [comment]
@johnt-freecen hopefully I fixed it properly this time on test3

**Comment by Captainkirkdawson** [comment]
Sorry @johnt-freecen something strange is going on

**Comment by Captainkirkdawson** [comment]
@johnt-freecen have restarted the server and things look like they should. So please see if we are now getting Scotland and Ireland correctly and that editing is OK

**Comment by johnt-freecen** [comment]
Hi Kirk,

I have just tried it again with our old faithful 2489 file, when I use the “view the individual” button for record 209 the Birth County entered field shows as blank.

I have another Scotland record waiting to be edited, record 2426, I entered the correct Scottish county and place, hit submit and the error “verbatim birth county invalid ; blank” appears.

So I cannot pass it off

Regards

John

**Comment by Captainkirkdawson** [comment]
@johnt-freecen @geoffj-FUG After multiple head scratches (now totally bald) and multiple false paths and possible solutions I believe the the root cause has been detected and resolved. Cause if you are interested was that what I believed to be an immutable constant was being changed by the initial search page. It is now firmly immutable. Hence Scotland and other countries should now be visible ans the selection codes for them should be there.. Deployed to test3

**Comment by johnt-freecen** [comment]
Hi Kirk,

It seems to be working now and displaying when you just view the record.

Regards

John

Sent from Mail for Windows 10

**Comment by Captainkirkdawson** [comment]
@johnt-freecen thank you

**Comment by geoffj-FUG** [comment]
Kirk
Tested OK.
Just a bit of housekeeping - Can we widen the Drop Down Chapman Code lists slightly please. Dublin for instance (DUB) only shows up as DU the B is hidden.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
Width of selection box for chapman widened. 
Note to some degree these are affected by character size being used on users computer 
Deployed to test3 please review again

**Comment by AlOneill** [comment]
@Captainkirkdawson Suspect that 3em (could need a little more to allow for padding/margin) would be better than setting width in px here (if that is what current unit is). Just a thought.

**Comment by Captainkirkdawson** [comment]
@AlOneill we set width as % and there are 4 versions with padding: 10px for all

**Comment by geoffj-FUG** [comment]
Thanks Kirk
Width is a lot better now. 
Geoff
