### ISSUE TITLE
Data error reports should open new window

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#97]
Mike S suggests that any problem report should open a new window, so that the user can consult the problematic page as they are filing their report

**Comment by edickens** [comment]
There are times when we would like this in FreeREG, such as the Help 
pages.  Is it easy to do?  E

**Comment by AlOneill** [comment]
Eric,

For the Help pages, I would be reluctant to foist a new tab (easy to do) on any link other than an outside-our-site link. Surely the solution is for a user to right-click (ctrl+click on a Mac) on the link and choose either 'New tab' or 'New window'.

Perhaps what is needed is a reminder of how to do this?

Alison

**Comment by edickens** [comment]
But if you do that, then you have to open FreeREG again and perhaps
    login, and I'm not sure that the cookies would work properly with
    two versions open at the same time.  Eric
    
    On 25/03/2016 17:38, AlOneill wrote:
    
    Eric,
      
      For the Help pages, I would be reluctant to foist a new tab (easy
      to do) on any link other than an outside-our-site link. Surely the
      solution is for a user to right-click (ctrl+click on a Mac) on the
      link and choose either 'New tab' or 'New window'.
      
      Perhaps what is needed is a reminder of how to do this?
      
      Alison
      
      
      On 24 Mar 2016, at 18:42, Eric Dickens wrote:
      
      > There are times when we would like this in FreeREG, such as
      the Help 
      > pages. Is it easy to do? E
      > 
      > —
      > You are receiving this because you are subscribed to this
      thread.
      > Reply to this email directly or view it on GitHub
      > 
      
      —
        You are receiving this because you commented.
        Reply to this email directly or view
          it on GitHub

**Comment by AlOneill** [comment]
I work regularly with several FreeReg (Help pages) tabs open at the same, and sometimes with more than one window. Have not encountered a problem, and certainly do not need to log in again. Just right-click and choose.

Have not had a need to try with multiple non-static pages.

Alison
