### ISSUE TITLE
Add soundex to Place Names in Freecen2 Places

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#970]

**Comment by richpomfret** [comment]
To discuss.

**Comment by geoffj-FUG** [comment]
This is not a Researcher enhancement, it is a Validator enhancement.

The following functions are required:
Sounds like (Soundex)
Starts With (substring)
Ends With (substring)
Contains (substring)
If possible, the Wild card ?. This is less important as starts with and ends with will solve the query in most cases.

They are the missing functions for Validators and would simplify their job immensely. For instance, there are often small spelling errors in the enumerator’s record and they are not found using our Gazetteer. 

They would be very effective in preventing validators adding rubbish to the  Gazetteer to make things pass. It was open slather in FC1.
 
Geoff

**Comment by Captainkirkdawson** [comment]
Remove non soundex components and place in other stories
Starts With (substring)
Ends With (substring)
Contains (substring)
If possible, the Wild card

**Comment by Captainkirkdawson** [comment]
Components of this story are:
Add soundex place name field to Freecen2Place.
Add soundex field to Freecen2Place creation and update
Add option to search on soundex to basic Search Place Names search page
Add soundex search
Add flag to search place names results so indicate soundex search
Rake task to add soundex field to existing documents.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Anne has developed the soundex code. Running in test3 needs evaluation
![soundex search.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/0e2d88a9-4386-4c71-ba4e-7a738a7df827)
![soundex results.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/30d638cd-11c0-455b-974e-fd4eda9112eb)

**Comment by geoffj-FUG** [comment]
Kirk

 

I am not getting a result.

 

I started with a hard match and gradually narrowed it down.

 

It appears that I don’t have the option to select Soundex so it is not happening.

 

Geoff

**Comment by AnneV-Learn** [comment]
Hi Geoff,

Are you not seeing the Place Name Soundex checkbox on Test3? I am - see screenshot below.

KR
Anne
[cid:896AEAEB-4DA7-407B-90DC-EF3EED426A0C-L0-001]

**Comment by geoffj-FUG** [comment]
Anne

Got it!

 

It gets lost in the text below it. Can we move it across so that it is in line with the other 2 entry boxes?

 

Otherwise it works well. Can we migrate it please?

 

Let me know when it has been migrated and I will post to the Boards.

 

Geoff
