### ISSUE TITLE
Expend fields contained in display of Freecen2 Place

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#971]

**Comment by Captainkirkdawson** [comment]
Committed to test3

**Comment by richpomfret** [comment]
@geoffj-FUG can you take a look at this for @Captainkirkdawson

**Comment by geoffj-FUG** [comment]
Kirk
What is this ine about please? Neither John nor I remember it.
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG @johnt-freecen We added additional field to the display of a place
![Extra fields](https://user-images.githubusercontent.com/2874694/95003858-0bc0f280-05a1-11eb-8b68-f2ab94f8053a.png)
