### ISSUE TITLE
Display Occupation Category not code

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#977]
The 1891 census introduced the Occupation Category. 
This field was not transcribed in Freecen1 hence never displayed.
It appears in subsequent census
Freecen2 csv accepts the field and displays it.
Should we find a way of interpreting the key?
eg. Try to explain in a hover/roll over (not done for any other field)
or Put the full word in place of the key (adds more space usage to an already crowed display)

**Comment by PatReynolds** [comment]
We expand the abreviation/code and present it as a term, e.g. Employee

**Comment by Captainkirkdawson** [comment]
Code does look up  for both working at home and for the occupational category. Applied to test3
Note the wording changes to reflect 1901 as well 
![occ.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/60eb2476-39f1-4dcc-ab64-2edaac01f15a)

**Comment by geoffj-FUG** [comment]
Will test after #831 and #1028
Geoff

**Comment by geoffj-FUG** [comment]
Tests OK
Geoff
