### ISSUE TITLE
Move folio/page number information to dwelling line

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#979]
Currently the CSV display has the folio and page number as part of the census information (as done in the Cen1 record display) 
The census line is quite cramped now with additional information. The address line is now separate because of the cramping. Also the house information is not really part of the census information. 
Should we move the folio and page number to be with the address? If so should it be at the start or end?

**Comment by richpomfret** [comment]
Agreed that yes we do.

**Comment by Captainkirkdawson** [comment]
Changes made and applied to test3

**Comment by richpomfret** [comment]
@PatReynolds to test this out.

**Comment by Captainkirkdawson** [comment]
@PatReynolds @richpomfret suggest you do a search on test3 for Boon in Somerset and look at the details for a 1901 census year. You can compare with the FC1 format by looking at the 1851 census result. Remember we display mush more information on the census
![boon 1901.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/cb1cee3c-e0a2-4147-809c-ec6c819f011b)

![boon 1851.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/ac3edc50-c6af-4fb1-8fc9-259ebd47da85)

**Comment by PatReynolds** [comment]
Tested and looking good.  Could not find a place 'Boon' but found a John Smith in Crewkerne in 1901.

**Comment by Captainkirkdawson** [comment]
@PatReynolds Sorry I should have been clearer search for a **surname** Boon in the Census for Somerset

**Comment by geoffj-FUG** [comment]
Kirk
If it is relevant I am comfortable with the way that these are appearing in the View Flags / View Error Maessages / View Warning messages screens.
These are critical to teh validator finding the correct image to view during validation.
Geoff
