### ISSUE TITLE
Update the edit form for userids to remove REG specific fields

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#981]

**Comment by geoffj-FUG** [comment]
Kirk
The role is still not displayed for teh Coordinator to change
![image.png](https://images.zenhubusercontent.com/5e8c52a8b7c1d94d472bb276/91a51731-faf7-40c7-9a29-e98f50bfb1f9)
Image attached
Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG Have fixed and deployed to test3

**Comment by geoffj-FUG** [comment]
Kirk
Loks good thank you.
You can close this one
Geoff
