### ISSUE TITLE
Loss of gender field on csv entry edit

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#982]
The gender field setting is being lost on en edit

**Comment by Captainkirkdawson** [comment]
@johnt-freecen @geoffj-FUG Fixed in test3

**Comment by johnt-freecen** [comment]
Hi Kirk,

Thanks for the update, the system is displaying the value but can you please check what is there. The Gender field now displays four values M m F f-. I am not certain what the last character is.

Regards

John

Sent from Mail for Windows 10

**Comment by Captainkirkdawson** [comment]
@johnt-freecen clarified selection box entries. TY

**Comment by geoffj-FUG** [comment]
Kirk

Now working OK
This item can be closed
Geoff
