### ISSUE TITLE
Add incorporation lock as second level of protection against removal without thought

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#983]

**Comment by Captainkirkdawson** [comment]
Deployed to test3

**Comment by richpomfret** [comment]
@geoffj-FUG can you take a look/test this for @Captainkirkdawson

**Comment by geoffj-FUG** [comment]
Rich
I will test once I have a piece ready to go.
Geoff

**Comment by geoffj-FUG** [comment]
I have now incorporated a batch and received the report. The Incorporation lock is active.
I have asked one of my testers (who was also the validator) to review about 50 random records to ensure that the records have been incorporated successfully.
I will keep you up to date.
Geoff
