### ISSUE TITLE
Populate the LND Place Names

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#984]
Populate the london Place Names as proposed in https://drive.google.com/drive/u/1/folders/150Uh4r_lvGT9_nVaxf3R4wvvub3EoyDI

https://drive.google.com/file/d/1KMThl0O1XqdE18PrTBp2n_4rQEEp0MQc/view?usp=sharing  appears to be the link to this document

**Comment by Captainkirkdawson** [comment]
Paul T has started entering the LND Places into a spreadsheet. These will converted to a .csv file be loaded into the Place Names Database at cutover. The area concerned is the City of London Wards, the City of London Parishes and the Metropolitan Boroughs. These entries generate Place Names and Alternative Place Names. These are all being recorded.
This will give us a good starting point for London Place Names. I am sure that we will need to add some more - as will happen for all Counties. I have had a look at a couple of 1871 spreadsheets and I think we have validatoon fo London covered fairtly well.
I will let you know how Paul goes.
Geoff

**Comment by PatReynolds** [comment]
Is the validation going to be checking for both formal name (e.g. Queenhithe Ward) and common name (name without 'Ward' e.g. Queenhithe)? Or just the formal name as in the document?

Later, will less obvious common names be added (e.g. common name Cheapside is accepted with the formal name Cheap Ward)?

**Comment by geoffj-FUG** [comment]
Rich
Paul T is capturing as many alternative names as he can. So both Cheapside and Cheap Ward will be captured and will automatically validate. There will inevitably be some that will be missed but he is being very thorough.
Geoff

**Comment by geoffj-FUG** [comment]
Update
So far Paul T has captured over 250 Place Names (plus alternates) in LND and is still going. He is recording l;at/long and references as he goes, so they should be ready to upload when he has finished. We should have a comprehensive list when it is complete.
Geoff

**Comment by geoffj-FUG** [comment]
First batch of almost 500 Place Names have been sent to Kirk and uploaded
Still progressing
Geoff

**Comment by Captainkirkdawson** [comment]
Final batch of 600 names received and deployed
