### ISSUE TITLE
Correct 1851 Parms extraction

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#985]
The 1851 parms from TNA have multiple sub districts in the same piece. Out current extraction give each the same piece number. Making all but the first subdistrict in accessible.

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
For 1851 there are 1157 duplicated file names (read numbers) with different sub district names ,ie a file may have multiple sub districts in the file. 
![2093.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/abc1baa9-1944-4aa2-9fb4-1438a5c57a87)

Our structure and file look up was based on the assumption of a single sub district in the file. Specifically we used the file name to look up the Sub district and its civil parishes. Hence the problem @johnt-freecen encountered

The are 2 possible solutions 
1) we rename the files that contain the multiple Seb Districts by adding an upper case Alphabetic character to the name eg 
![2093A.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/99a070be-a4e5-4c1a-976b-0edce02d0414)

If we proceed this way the transcriber has to enter HO107_2093 or HO107_2093A or HO107_2093B depending on the sb district that are transcribing
2) we read the first enumeration district in the file, extract the civil parish and attempt to find the appropriate sub district to determine which of the file entries we should be using. This is unfortunately subject to errors in inputting the civil parish and there are occasions when civil parishes are split across multiple files. In other words it is not a fail safe approach.
My preferred approach is option 1.
PS The issue is unique to 1851

**Comment by geoffj-FUG** [comment]
Kirk

 

1851 was an abomination to transcribe. I only had a couple of transcribers who could cope with files with 20 to 25 thousand entries. The a, b, c, d etc break up in file names that we proposed will be a godsend to Coordinators as they can break up the pieces into EDs for transcription etc.

 

Your proposal 1 is not that far different logically. I am happy with it.

 

Geoff

**Comment by Captainkirkdawson** [comment]
Completed and deployed to test3

**Comment by geoffj-FUG** [comment]
@johnt-freecen This was raised whilst you were testing an 1851 piece. I dont have one ready to test for that year. Does this resolve the problem that you had? Geoff

**Comment by johnt-freecen** [comment]
Hi Geoff,

As far as I am aware this is still open. For 1851 HO107_2093 there are three different piece names each with a different list of civil parishes.

I know that the proposal was to call these 2093A, 2093B and 2093C or some such, but am not aware of any actual chances to the system yet.

How I picked this piece by random I do not know.

Regards

John

Sent from Mail for Windows 10

**Comment by Captainkirkdawson** [comment]
@johnt-freecen @geoffj-FUG The code to create 1851 Parms is working. It has not been run on test3 as I would need to delete the existing set. This would mean that all 1851 test files would need to be rerun. Not sure how big an impact that is. If it is small we should do the recreate. Advise please

**Comment by johnt-freecen** [comment]
Hi Kirk,

I only have the one 1851 piece which I have not really started work on yet, other than getting the civil parish errors. I have taken my original largish file and spilt it into two pieces, the first matching block one of the district groups, just to check that the civil parish was ok. 

I can do nothing with the second batch until this is done. It would be nice to run the second group against the change to see it works.

This is then something that needs spelling out to the co-ordinators when they have 1851 pieces to run.

Regards

John

Sent from Mail for Windows 10

**Comment by geoffj-FUG** [comment]
@johnt-freecen @geoffj-FUG I have no 1851 files on test3 that I cannot do without. So I am happy for you to proceed if John is OK.
Beki is working on 1871 so it should not affect her. Chas is working on 1901 so it should not affect him.
Just get the all clear from John
Geoff

**Comment by johnt-freecen** [comment]
! am happy for the 1851 changes to go ahead. I only have the one 1851 file there and not really done anything with it due to this problem.

Just let us know what the change to the file name needs to be please.

Regards

John

Sent from Mail for Windows 10
