### ISSUE TITLE
180892498 Error message on blank WARD (John)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#987]
Issue reported by **johnt** at 2020-09-24 15:54:58 UTC

Reported Issue:
I am in the process of editing during validation I added a new place to the location table, submitted as true this record. As there were several known occurrences of this error I selected the reprocess option. When complete it gave error messages that the ward field was blank on each change of district. I am not certain where this is disappearing in the edit or process routine    

![Screenshot](https://test3.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@johnt-freecen Need to know the file and county in question

**Comment by johnt-freecen** [comment]
Hi Kirk,

I think this was another hyphen problem, when you fixed the other problem with hyphens this is now working as well so can be closed.

Regards

John

Sent from Mail for Windows 10

**Comment by Captainkirkdawson** [comment]
Thank you @johnt-freecen ; suspected that might be the case.
