### ISSUE TITLE
180892818 Download process losing Hyphen in forename (John)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#988]
Issue reported by **johnt** at 2020-09-24 16:00:18 UTC

Reported Issue:
I was going to perform some off-line editing for validation, so selected the download file option as I needed to correct some "Header" info.

Having performed the change of addresses I launched the replace option. This worked ok, but produced error messages that were not present previously, namely the forename was blank.

Investigation showed that the download routine had converted the hyphen in the forename field to blank, but the surname field was ok.    

![Screenshot](https://test3.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@johnt-freecen can you point me to the file in question; can you send the downloaded file off line please.
I have downloaded HO107_895_t (johnt) in East of RUT from test3. It has a - in record 1727 forename and 3633 surname.
My downloaded file has them present
![forename hyphen.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/1ed09279-fb4d-420b-bf5d-e3d6c993dad7)
![surname hyphen.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/33caa75f-e780-425b-8bdc-f328a5f7f1e5)
However it appears to vanish on replace. Still investigating

**Comment by Captainkirkdawson** [comment]
@johnt-freecen Problem located. Nothing to do with the download. Caused by using the titleize method on a hyphen; had forgotten it was a no no.
Resolved and fix deployed to test3

**Comment by johnt-freecen** [comment]
Hi Kirk,

This is now working ok thanks.

Regards

John

Sent from Mail for Windows 10
