### ISSUE TITLE
180893020 Invalid Verbatim error message (John)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#989]
Issue reported by **johnt** at 2020-09-24 16:03:40 UTC

Reported Issue:
When editing a record for 1841, I corrected the field I needed to and selected submit, the program returned an error message that the verbatim place of birth cannot be blank. This does not exist in the 1841 census.    

![Screenshot](https://test3.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@johnt-freecen Fixed and deployed to test3

**Comment by johnt-freecen** [comment]
Hi Kirk,

Tested ok.

Regards

John
Sent from Mail for Windows 10
