### ISSUE TITLE
Online place editor for PARMS.DAT

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/FreeCENMigration#99]
We need to have an admin function allowing a coordinator to edit places and pieces, generating PARMS.DAT files to be distributed (but importantly also keeping the online system in sync with the DAT files).  This could be a CSV upload function using the same format used currently.

**Comment by benwbrum** [comment]
What we're talking about is a way of updating place/piece records online so that we can keep the metadata in the system in sync with the data and add geolocation to support nearby-place search.

**Comment by dougkdev** [comment]
I have made some good progress on this, still some more to do.

**Comment by dougkdev** [comment]
I believe this is still ready for user-testing, not sure why it was moved to backlog.  We discussed it in a scrum sometime around early August (with a "share-screen" demo if I remember right) and we are waiting for feedback from @FreecenBren about whether it is a reasonable solution for her.  @FreecenBren : we exchanged emails about how to log in to try it (original email sent Aug 6 with title "FreeCen2 piece/place editing" with some back-and-forth emails through Aug 18).

**Comment by FreecenBren** [comment]
It would not let me in the refinery. It still will not.
Unless there is a different link been set up.

Brenda



Sent from Samsung tablet


-------- Original message --------

**Comment by dougkdev** [comment]
I sent you a password reset link a moment ago.  Will that work for you?

**Comment by suffolkroots** [comment]
I am not at all happy with the National Archives links. They seem to be incorrect in so many cases.

Classic examples are Islandshire and Norhamshire for DUR 1841.

These are NBL places, pieces are in FreeCEN1 for NBL. How have they changed to DUR in CEN2?

It seems a bit of a mess.

Nearby places seems a pipe dream if the going live timescale is to remain.

**Comment by Captainkirkdawson** [comment]
@suffolkroots 
This an old and obsolete story that is no longer active.
It was replaced by the Epic **Manage Parms and their Pieces Directly on CEN2#852**
This is now operational.
Geoff's handbook covers much of this starting on page 67 in the section **How to Manage the PARMS Files**
The Intercounty you raise has been recognized and addressed through the section  **How to Handle Inter-County Pieces**
In recognition of the complexity of this the data manager will assist a coordinator by making the appropriate changes once the specific detail of what needs to be done is identified by the coordinator.

**Comment by suffolkroots** [comment]
Sorry to reply on closed post---just to be clear---the two 1841 districts mentioned above are not inter-county/inter-parish problems, they are erroneously linked by TNA to wrong county, being far away from Durham border. Yes, they will need moving, due to mistakes by TNA.

**Comment by Captainkirkdawson** [comment]
Thanks for that clarification
