### ISSUE TITLE
Add Birth Place to Results display

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#990]
Suggested by one of the coordinators

**Comment by Captainkirkdawson** [comment]
Birth place added to results on test3 (No order by birth place yet)![birth place.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/72a07d96-5be4-40b1-8d7b-8ce4af3feda6)

**Comment by geoffj-FUG** [comment]
Looks good. That is a big improvement.
Geoff
