### ISSUE TITLE
Test for - hyphen in forename and surname

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#993]
Can we also test Forename and Surname for a hyphen please? Generate a Warning if a hyphen exists as the only character in the field. At the moment I only think we look for a blank.

**Comment by Captainkirkdawson** [comment]
Added and deployed to test3

**Comment by richpomfret** [comment]
@Captainkirkdawson to send @PatReynolds and @richpomfret a file to test this out.

**Comment by geoffj-FUG** [comment]
Test successful
This story can be closed.
Geoff

**Comment by Captainkirkdawson** [comment]
Thank you
