### ISSUE TITLE
181140522 when you are paging to the next dwelling the folio and page number do not change in line with the actual records (John)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#995]
Issue reported by **johnt** at 2020-09-27 12:48:42 UTC
Time: 2020-09-27T12:44:59+00:00
Session ID: 2d49da896b7cfa8b80be612ba2ced376
Problem Page URL: [/search_records/5f6376a1e9379077cbd355cd/sarah-franks-1841-rutland-stamford-1776-?locale=en](/search_records/5f6376a1e9379077cbd355cd/sarah-franks-1841-rutland-stamford-1776-?locale=en)
Previous Page URL: [https://test3.freecen.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2020-09-27+12%3A44%3A15+UTC&session_id=2d49da896b7cfa8b80be612ba2ced376&user_id=johnt&problem_page_url=%2Fsearch_records%2F5f6376a1e9379077cbd355cd%2Fsarah-franks-1841-rutland-stamford-1776-%3Flocale%3Den&previous_page_url=https%3A%2F%2Ftest3.freecen.org.uk%2Fsearch_queries%2F5f708914e93790647489e386%3Flocale%3Den&feedback_type=issue](https://test3.freecen.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2020-09-27+12%3A44%3A15+UTC&session_id=2d49da896b7cfa8b80be612ba2ced376&user_id=johnt&problem_page_url=%2Fsearch_records%2F5f6376a1e9379077cbd355cd%2Fsarah-franks-1841-rutland-stamford-1776-%3Flocale%3Den&previous_page_url=https%3A%2F%2Ftest3.freecen.org.uk%2Fsearch_queries%2F5f708914e93790647489e386%3Flocale%3Den&feedback_type=issue)
Reported Issue:
I have noticed the following problems

1) when you are paging to the next dwelling the folio and page number do not change in line with the actual records, they remain as 1st viewed

2) it would be nice if the word uninhabited, building under construction or visiting could be displayed rather than a blank page    

![Screenshot](https://test3.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@johnt-freecen Fix applied to test3

**Comment by johnt-freecen** [comment]
Hi Kirk, this is now working ok and can be closed.

Regards

John

Sent from Mail for Windows 10
