### ISSUE TITLE
181225853 Cannot edit a record which is for uninhab place (John)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#997]
Issue reported by **johnt** at 2020-09-28 12:30:53 UTC
Time: 2020-09-28T12:27:39+00:00
Session ID: 2d49da896b7cfa8b80be612ba2ced376
Problem Page URL: [/freecen_csv_entries/5f71976be937903d470a3ceb?locale=en](/freecen_csv_entries/5f71976be937903d470a3ceb?locale=en)
Previous Page URL: [https://test3.freecen.org.uk/freecen_csv_entries/5f71976be937903d470a3ceb/edit?locale=en](https://test3.freecen.org.uk/freecen_csv_entries/5f71976be937903d470a3ceb/edit?locale=en)
Reported Issue:
I had got a warning message on an uninhabited dwelling. I have tried to edit the record to set the message to true on line and got the error stating that the sex and many other fields are blank.

    

![Screenshot](https://test3.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
@johnt-freecen 
On line editing is only for individual edits  not census  information or dwelling. That must be done off line.

Need to find a way of enforcing that for the edit so that this issue is not created

**Comment by Captainkirkdawson** [comment]
@johnt-freecen Added test to avoid online edit of an inhabited dwelling. Deployed to test3

**Comment by richpomfret** [comment]
Can @johnt-freecen take a look and test this to see if it is now fixed?

**Comment by johnt-freecen** [comment]
This can now be closed.

Regards

John

Sent from Mail for Windows 10

**Comment by Captainkirkdawson** [comment]
Thanks @johnt-freecen
