### ISSUE TITLE
Requirements for Incorporation Statistics

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#998]
There is a need to establish the management and research requirements for incorporation information

There currently are none. Is there a requirement for any? Incorporation is the action of adding the records from a csv file processed by CSV Proc into the search records database. Is there a need for keeping any specific statistics on this? Or will these be incorporated into the Statistic reports for CEN #735. It also relates to the Database Coverage (Records) #749

E0 U6 S8 C6:P20

**Comment by PatReynolds** [comment]
Not part of #749 as the Records page is about current status, not historical data (doesn't matter when a record was added to the database, all that matters is that it is there.

#735 needs review and stories adding.

For this story - incorporation - decisions need to be made about
- periodicitity - do we want to know the figures for a day, a week, a month, a quarter, a year?
- detail - do we want to know figures by civil parish, by sub district, by district, by county, by country, by total?  

No additional requirements for reserchers / social media from https://docs.google.com/document/d/1LD9zyYV1en5uzx0zP2_QSnMtSEuH3Vz_IQWWqvMEytU/edit?usp=sharing
