### ISSUE TITLE
Remove non freecen chapman codes in  birth codes

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#999]
There has always been a removal of certain chapman codes  both for reg and cen These included the country codes. When we added in the country codes we allowed back in the other codes as well.

**Comment by Captainkirkdawson** [comment]
The following Counties need to be hidden or they will cause havoc during validation. We cannot allow Place Names to be attached to the following Counties in the list. Some of them are modern (post 1974) Counties and others such as LND and YKS need to be locked off. Orkney and Shetland are already covered as Orkney Isles and Shetland Isles and are duplicates.

 

Is there a dump available of the data in the Place Names Database please? I need to check whether there are any place names already attached to them.

 

Central

Clwyd

Dumfries and Galloway

Dyfed

England and Wales Shipping

Grampian

Gwent

Gwynedd

Highland

London (City)

Lothian

Mid Glamorgan

Military

Orkney

Other Locations

Out of County

Powys

Royal Navy Ships

Scottish Shipping

Shetland

South Glamorgan

Strathclyde

Tayside

Unknown

West Glamorgan

Western Isles

Yorkshire

 

The following counties need additions in brackets as they had 2 names:

To be inserted in brackets

After County

Chapman Code

Edinburghshire

Midlothian

MLN

Elgin

Morayshire

MOR

Haddington

Elgin

ELN

Kings

Offlay

OFF

Linlithgow

West Lothian

WLN

Mearns

Kincardineshire

KCD

Queens

County Laois

LEX

West Galloway

Wigtownshire

WIG

Zetland

Shetland Isles

SHI

 

 

 

Geoff

**Comment by Captainkirkdawson** [comment]
@geoffj-FUG 
Removed as requested. Could not do the bracketing; added as hint instead. Deployed to test3

**Comment by geoffj-FUG** [comment]
Kirk
Thank you.
Looks OK except the first hint should be For Edinburghshire use Midlothian.
Geoff

**Comment by Captainkirkdawson** [comment]
Corrected
